Помогите коллеге BJS2-23935
CorporationX/god_bless pull request #10019
Opened 2024-08-24 05:36 UTC by sultan-inked

2024-08-24 20:57 UTC, 20cognosce requested changes
CompletableFuture не к месту

2024-08-24 20:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/help/collegue/Main.java
> +    private static final int NUMBER_OF_PEOPLE = 1000;
их 10.000

2024-08-24 20:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/help/collegue/Main.java
> +    private static final int THREAD_POOL_SIZE = 5;
мало потоков, проведи бенчмарк на оптимальное их количество

2024-08-24 20:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/help/collegue/PersonNamePrinter.java
> +        people
people.forEach()
people.stream()

первый вызов не отрывай

2024-08-24 20:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/help/collegue/PersonNamePrinter.java
> +                .forEach(person -> log.info("{}",person.getName()));
пробел после запятой

2024-08-24 20:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/help/collegue/Main.java
> +        futures.addAll(getFutures());
не getFutures, там ты потоки уже запустил
runTasks как-нибудь

2024-08-24 20:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/help/collegue/Main.java
> +    private static final List<CompletableFuture<Void>> futures = new ArrayList<>();
Зачем ты создаешь CompletableFuture если тебя возвращаемый результат не интересует, и ты применяешь Void? 
Чисто чтобы join вызвать?

2024-08-24 20:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/help/collegue/Main.java
> +        allOf.join();
Ты опять конструируешь оверинжиниринг

2024-08-24 20:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/help/collegue/Main.java
> +        allOf.join();
KISS принцип, погугли

2024-08-25 12:36 UTC, 20cognosce approved these changes

2024-08-25 12:36 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/help/collegue/Main.java
> +            if (executor.awaitTermination(TASK_TIMER, TimeUnit.MILLISECONDS)) {
Бессмысленное ожидание, ждем секунду - и ничего не предпринимаем
Это тоже самое что sleep(1000) тогда

2024-08-25 12:36 UTC, merged

2024-08-25 14:30 UTC, sultan-inked commented on src/main/java/faang/school/godbless/task/multithreading/help/collegue/Main.java
> +            if (executor.awaitTermination(TASK_TIMER, TimeUnit.MILLISECONDS)) {
В задаче написано его использовать