Matters of the heart
CorporationX/god_bless pull request #10012
Opened 2024-08-23 22:12 UTC by SharkB38

Задача Matters of the heart
https://faang-school.atlassian.net/browse/BJS2-24334
Наворотил ужаса, адекватно не получилось сделать.

2024-08-24 19:17 UTC, mysosnovskaya requested changes

2024-08-24 19:17 UTC, mysosnovskaya commented on src/main/java/heart/ChatManager.java
> +        chatUsers.remove(user);
Кажется, по логике и второго пользователя нужно удалить :) А то чего он там один будет делать))

2024-08-24 20:23 UTC, SharkB38 commented on src/main/java/heart/ChatManager.java
> +        chatUsers.remove(user);
Я сначала так и сделал, но потом решил сделать по другому, а то как-будто бы второго пользователя сразу выбивает из чата если выходит первый. Мне это показалось как-то неправильно

2024-08-26 20:18 UTC, mysosnovskaya commented on src/main/java/heart/ChatManager.java
> +        chatUsers.remove(user);
Был бы у нас аналитик, уточнили бы у него) Мне как-то по условию задачи захотелось реализовать именно так. Просто нет механизма, который был позволит что-то делать с чатом с одним пользователем: дать уйти этому пользователю или присоединить к нему кого-то ещё.

2024-08-26 20:18 UTC, mysosnovskaya approved these changes

2024-08-26 20:18 UTC, merged