Telegram-bot
CorporationX/god_bless pull request #10023
Opened 2024-08-24 07:37 UTC by SharkB38

Задача Telegram-bot
https://faang-school.atlassian.net/browse/BJS2-24419

2024-08-24 19:22 UTC, mysosnovskaya requested changes

2024-08-24 19:22 UTC, mysosnovskaya commented on src/main/java/bot/TelegramBot.java
> +            while (requestCounter >= REQUEST_LIMIT) {
По-моему этот while можно объединить с if, разве нет?

2024-08-24 20:31 UTC, SharkB38 commented on src/main/java/bot/TelegramBot.java
> +            while (requestCounter >= REQUEST_LIMIT) {
Вынес из-за Thread.sleep(), ide подсказывает использовать вместо Thread.sleep() wait() с параметром, но не понимаю почему, они же по разному работают? В задаче то это сработает, наверное даже с wait() без параметра, но тогда вот этот пункт:
`Если прошедшее время меньше секунды, увеличивать requestCounter на 1, и если он становится больше REQUEST_LIMIT, то подождать до конца секунды.` не будет выполнятся без Thread.sleep()

2024-08-28 12:41 UTC, SharkB38 commented on src/main/java/bot/TelegramBot.java
> +            while (requestCounter >= REQUEST_LIMIT) {
Не придумал как по другому сделать

2024-08-28 17:19 UTC, mysosnovskaya requested changes

2024-08-28 17:19 UTC, mysosnovskaya commented on src/main/java/bot/TelegramBot.java
> +            while (requestCounter >= REQUEST_LIMIT) {
А почему не подойдет wait? Работают по-разному, да. В sleep жестко задается время сна, а в wait с параметром - задается максимальное время ожидания, но если кто-то разбудит раньше, то поток выйдет из ожидания. Он всё равно в while проверит, можно ли теперь обработать реквест и если нет, то опять будет ждать. Можем на дейлике голосом обсудить)

2024-08-29 13:54 UTC, SharkB38 commented on src/main/java/bot/TelegramBot.java
> +                }
Без этого условия бесконечно крутится в цикле

2024-08-29 13:55 UTC, SharkB38 commented on src/main/java/bot/TelegramBot.java
> +    private AtomicLong lastRequestTime;
Сделал так, убрал с метода synchronized результат один, отправляет от 9 до 13 сообщений в секунду

2024-08-29 18:41 UTC, mysosnovskaya requested changes

2024-08-29 18:41 UTC, mysosnovskaya commented on src/main/java/bot/TelegramBot.java
> +    public void sendMessage(@NonNull String message) {
Да, перемудрил =)
1. Метод лучше оставить synchronized
2. Вложенный if (26 строка) должен привести к обнулению requestCounter и lastRequestTime (т.к. после последнего реквеста прошло больше секунды).
3. Осталось разобраться с изменениями requestCounter: инкрементировать нужно тогда, когда реквест "прошел" в рамки по времени. Т.е. не на 24 строке, а после цикла. И обрати внимание на строчку, где ты делаешь requestCounter.set(0); - почему 0? Понятно, что лимит по времени преодолен, но в данный момент ты как раз "принимаешь" реквест, т.е. уже не 0, а 1 (либо можно оставить как есть, а потом ниже сделать инкремент).
4. И notifyAll нужно переместить - оставляю на подумать)

2024-08-30 17:58 UTC, mysosnovskaya commented on src/main/java/bot/TelegramBot.java
> +    public void sendMessage(@NonNull String message) {
notifyAll можно делать в самом конце метода (т.е. в любом случае, когда из метода выходим, тем самым сообщая остальным потоком, что значения полей изменились и может быть они теперь могут продолжать работу, пусть проверят). Но в текущей реализации тоже будет работать корректно.

2024-08-30 17:58 UTC, mysosnovskaya approved these changes

2024-08-30 17:58 UTC, merged