BJS2-23647
CorporationX/god_bless pull request #10033
Opened 2024-08-24 09:04 UTC by aassylkhan

2024-08-24 17:53 UTC, mysosnovskaya requested changes

2024-08-24 17:53 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/BJS223647/Knight.java
> +            new Thread(trial).start();
А зачем тогда нужен executorService?) Лучше всё-таки скормить задачки в него, а не создавать поток самостоятельно

2024-08-26 04:48 UTC, aassylkhan commented on src/main/java/faang/school/godbless/BJS223647/Knight.java
> +            new Thread(trial).start();
исправил

2024-08-27 17:44 UTC, mysosnovskaya approved these changes

2024-08-27 17:44 UTC, merged