Chibisovaanastasiia0318 bjs2 23845
CorporationX/god_bless pull request #10041
Opened 2024-08-24 09:58 UTC by ChibixAnastasia

BJS2 - 23845 - Mice are very nice!

2024-08-24 19:45 UTC, 20cognosce requested changes

2024-08-24 19:45 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task23845/House.java
> +        List<Food> mainCours = new ArrayList<>();
mainCours это who

2024-08-24 19:45 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task23845/House.java
> +        }
Зачем 5 раз собирать еду в одних и тех же комнатах несколько раз?...
Надо собрать - и затем эту еду удалить

Несколько потоков должно быть, и каждый собирает в своей комнате(-ах)

2024-08-24 19:45 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task23845/House.java
> +    }
Так вообще не годится.

2024-08-25 15:51 UTC, 20cognosce requested changes
Я ожидаю увидеть:
В начале - еда в комнатах
В конце - еда в списке, еды в комнатах нет
И это должно быть достигнуто несколькими параллельными потоками

2024-08-25 15:51 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task23845/House.java
> +        List<Food> mainCours = new ArrayList<>();
Что значит эта переменная? Необходимо понятное имя

2024-08-25 15:51 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task23845/House.java
> +            executorService.schedule(() -> house.collectFood(), 30, TimeUnit.SECONDS);
Ты создала пул на 5 потоков, но используешь только один
Каждый поток должен собираться еду в своих отдельных комнатах

2024-08-25 15:51 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task23845/House.java
> +    }
Это не соответствует условию задачи

В цикле for запустите каждый поток в пуле с интервалом в 30 секунд, используя метод executor.schedule() и передавая ему лямбда-выражение, которое вызывает метод collectFood() из объекта house.

В методе collectFood() из объекта house, соберите еду из двух комнат и добавьте её в список собранной еды.

Удалите собранную еду из списков еды в комнатах.

После выполнения всех задач, закройте пул потоков и выведите сообщение о том, что еда собрана.

2024-08-29 19:52 UTC, 20cognosce requested changes

2024-08-29 19:52 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task23845/House.java
> +        }
forEach
через 30 секунд ты запустишь сбор еды во всех комнатах одновременно, а надо с задержкой между стартом сбора в каждой комнате

00:00 - первая комната пошла собирать еду
00:30 - вторая
01:30 - третья

Можно меньше интервал сделать, секунд 10

2024-08-29 19:52 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task23845/House.java
> +        roomList.remove(room);
Надо не комнату убирать, а еду из нее

2024-08-29 19:52 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task23845/House.java
> +    private static List<Food> foodList = new ArrayList<>();
Почему static?

2024-08-29 19:52 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task23845/House.java
> +    }
У тебя многопоточная среда, нельзя допускать модификации объектов без синхронизации между потоками, на foodList должна быть блокировка

2024-08-31 17:19 UTC, mysosnovskaya requested changes

2024-08-31 17:19 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/task23845/Room.java
> +    private List<Food> food = new ArrayList<>();
Это поле судя по реализации должно быть финальным, т.к. не предполагается его изменений (ты как раз даже сеттер не добавляла для него - именно по этой причине)

2024-08-31 17:19 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/task23845/House.java
> +            executorService.schedule(() -> house.collectFood(room), i * 10, TimeUnit.SECONDS);
По условию задачи каждый поток должен собирать еду из двух комнат, а у тебя сейчас из одной

2024-08-31 17:19 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/task23845/House.java
> +        executorService.shutdown();
Ещё нужно сообщение о том, что вся еда собрана. Т.е. нужно дождаться окончания всех потоков, а потом вывести в консоль какой-то подходящий текст

2024-08-31 17:19 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/task23845/House.java
> +    private static List<Food> foodList = new ArrayList<>();
static не нужен, т.к. если мы создадим другой объект класса House, то у него должны быть свои списки roomList и foodList. А со static получается, что для всех объектов House списки будут общие

2025-01-17 21:21 UTC, closed without merging