BJS2-24509 Блокировка Spotify
CorporationX/god_bless pull request #10056
Opened 2024-08-24 13:28 UTC by Alginin

2024-08-24 18:59 UTC, 20cognosce requested changes

2024-08-24 18:59 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS224509/Player.java
> +    private boolean isPlaying;
Почему нигде не обновляешь её?
нажали плэй - она осталась false

2024-08-24 18:59 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS224509/Player.java
> +    private boolean isPlaying;
А ты вообще не задал первоначальное значение, что внутри твоих методов проверяется?
Ты тестировал всех их?

2024-08-25 09:51 UTC, Alginin commented on src/main/java/faang/school/godbless/BJS224509/Player.java
> +    private boolean isPlaying;
Переделал задачу (плоховато понял ее). 
private boolean isPlaying по дефолту ведь имеет значение false или лучше указывать все равно?

2024-08-25 13:37 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS224509/Player.java
> +    private boolean isPlaying;
Изначально, когда ты заходишь в плеер у тебя же ничего не играет
Значит false

2024-08-25 13:38 UTC, 20cognosce approved these changes

2024-08-25 13:38 UTC, merged