Очередь в Walmart BJS2-23956
CorporationX/god_bless pull request #10058
Opened 2024-08-24 13:51 UTC by sultan-inked

2024-08-28 17:27 UTC, 20cognosce requested changes
Убирай все Future и упрощай всё

2024-08-28 17:27 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/walmart/queue/CashierThread.java
> +                .stream()
print - это ты делаешь для себя, а не по логике программы, этого упомнаться в сигнатуре метода не должно

customer.items().stream()
peek()

2024-08-28 17:27 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/walmart/queue/Main.java
> +    }
Выноси это в отдельный класс куда-нибудь "Configuration"
Настройка - это одна стадия
Исполнение - это другая, они не должны лежать рядом вперемешку

2024-08-28 17:27 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/walmart/queue/Main.java
> +    }
Настройка в данном контексте - это все эти объекты-пустышки, которые нужно чисто для сеттинга

2024-08-28 17:27 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/walmart/queue/Main.java
> +    }
То что касается настройки потоков - должно остаться тут

2024-08-28 17:27 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/walmart/queue/Main.java
> +        return cashierThread.getSum();
Вот это выглядит стрёмно
run() - это просто выполнения метода, это не запуск потока

Поток запускается на start
Затем, ты сразу берешь sum, без ожидания готовности, без callback'а какого-нибудь, это выглядит некорректно

2024-08-28 17:27 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/walmart/queue/Main.java
> +                        .supplyAsync(() -> serveClient(cashierThread), executor))
Ну и вообще CompletableFuture в этих задачах не надо использовать, тема не об этом
Ты один раз его заюзал и теперь каждую задачу пытаешься к CompletableFuture притянуть

2024-08-28 17:27 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/walmart/queue/Main.java
> +    }
Ну вот это опять 10-тиколёсные велосипеды, ну что это
Почему нельзя завести на все потоки один AtomicInteger, и дождаться, пока все они его просуммируют через thread.join()

2024-08-29 07:14 UTC, sultan-inked commented
Исправил, удалил `CompletableFuture`, каждый поток копит сумму в `AtomicInteger`

2024-08-29 17:38 UTC, 20cognosce approved these changes

2024-08-29 17:38 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/walmart/queue/CashierThread.java
> +    private final static AtomicInteger totalSum = new AtomicInteger();
Окей, это корректно, но static быть не должно

2024-08-29 17:38 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/walmart/queue/CashierThread.java
> +        sum = getSum();
И это бессмысленная строчка, поле sum не нужное вообще

2024-08-29 17:38 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/walmart/queue/CashierThread.java
> +    }
static - нельзя

2024-08-29 17:38 UTC, merged