Решение задачи Путь пальцем проложи…
CorporationX/god_bless pull request #10079
Opened 2024-08-24 18:19 UTC by wmwmaks

Сложная задача, не до конца понял, как программа должна работать. Каким образом метод public long getJourneyDistance должен высчитывать расстояние и от чего?

2024-08-24 18:55 UTC, mysosnovskaya requested changes

2024-08-24 18:55 UTC, mysosnovskaya commented on src/main/java/thread/seven/City.java
> +    int rangeToGerald;
А это поле почему не приватное?)

2024-08-24 18:55 UTC, mysosnovskaya commented on src/main/java/thread/seven/CityWorker.java
> +        System.out.println("Путешествие длинной " + city.getRangeToGerald() +
Геральт находится в одном городе, а монстр - в другом, вот между ними нужно посчитать разницу) Но в целом можешь так оставить, т.к. условие и правда непонятное :)

2024-08-24 18:55 UTC, mysosnovskaya commented on src/main/java/thread/seven/CityWorker.java
> +        long killTime = getKillTime(nearestMonster);
Может быть методы getJourneyDistance и getKillTime имеет смысл сделать void и поменять им название? В текущей реализации их возвращаемые значения не используются. Или всё-таки как-то их использовать (например, для вывода текста на экран).

2024-08-24 19:36 UTC, wmwmaks commented on src/main/java/thread/seven/CityWorker.java
> +        long killTime = getKillTime(nearestMonster);
Что-то я быстро не придумал, где бы их можно было использовать, чтобы что-то выводить на экран. Вроде, и так выводится неплохо. Подскажите, куда это можно было бы вставить? 
Сделаю void)

2024-08-24 19:51 UTC, mysosnovskaya commented on src/main/java/thread/seven/CityWorker.java
> +        long killTime = getKillTime(nearestMonster);
Можно было бы выводить на экран то, что сейчас написано внутри методов. Например, getJourneyDistance возвращает 0 или какое-то другое число, а здесь, в run, выводится "Путешествие длинной ... км до города ...". Но у тебя сейчас выводы на экран хорошо сделаны, разные в зависимости от разных ситуаций. Поэтому void хорошо подходит. Единственное - если методы void, то их названия не могут начинаться с get (get - это "получить", т.е. это означает, что метод должен что-то вернуть). Можно переименовать используя print/calculate/display

2024-08-24 19:59 UTC, wmwmaks commented on src/main/java/thread/seven/CityWorker.java
> +        long killTime = getKillTime(nearestMonster);
Точно. Про эти детали пока забываю. Я еще не привык, что мой код кто-то смотрит. 
И, наверное, лучше getKillTime заменю на printBattleInfo, потому что вывожу не время, а ход битвы.
Еще такой вопрос. Я, когда вношу правки, везде пишу "Исправил код" и догадываюсь, что это неправильно, но не знаю, как лучше комментировать эти коммиты. Как это делается в реальных проектах?

2024-08-25 18:52 UTC, mysosnovskaya commented on src/main/java/thread/seven/CityWorker.java
> +        long killTime = getKillTime(nearestMonster);
Поддерживаю новое название метода, так правда лучше 👍 
В идеале нужно писать, что именно исправлено. В твоем случае можно было бы последний коммит назвать "rename method getKillTime to printBattleInfo" (или то же самое на русском, но я рекомендую учиться на английском писать. На русский всегда переехать не сложно будет). Или "fix code style" (если ошибки по стилю). Если много маленьких правок и нет ничего критичного, то допустимо писать "refactoring after review".

2024-08-25 18:52 UTC, mysosnovskaya approved these changes

2024-08-25 18:52 UTC, merged