Решение задачи Mice are very nice!
CorporationX/god_bless pull request #10108
Opened 2024-08-25 08:08 UTC by wmwmaks

2024-08-25 18:49 UTC, mysosnovskaya requested changes

2024-08-25 18:49 UTC, mysosnovskaya commented on src/main/java/thread/eight/House.java
> +            executor.schedule(() -> {
По заданию задачи должны стартовать через 30 секунд друг от друга. Т.е. первая через 30 секунд от текущего момента, вторая - через минуту от текущего момента, третья - через полторы и так далее

2024-08-25 18:49 UTC, mysosnovskaya commented on src/main/java/thread/eight/House.java
> +        if (roomIndex1 < rooms.size() && roomIndex2 < rooms.size()) {
А если `roomIndex1 < rooms.size() == true`, а ` roomIndex2 < rooms.size() == false`, то тогда из последней комнаты еду не соберем? Хотя нужно из всех комнат в доме собрать)

2024-08-25 18:49 UTC, mysosnovskaya commented on src/main/java/thread/eight/Room.java
> +    private List<Food> foodList = new ArrayList<>();
Кажется, это поле можно сделать финальным?) Т.к. мы не подразумеваем, что кто-то может вместо текущего списка foodList может подставить какой-то другой. Это потенциальный баг: если другой разработчик решит так сделать, то он легко может "затереть" тот список еды в комнате, который был изначально

2024-08-26 08:34 UTC, wmwmaks commented on src/main/java/thread/eight/Room.java
> +    private List<Food> foodList = new ArrayList<>();
Я почему-то пока затрудняюсь с тем, где стоит final прописывать, а где нет. final поля всегда прописывать в верхнем регистре или можно, как обычные поля оставлять?

2024-08-26 20:13 UTC, mysosnovskaya requested changes

2024-08-26 20:13 UTC, mysosnovskaya commented on src/main/java/thread/eight/House.java
> +        if (roomIndex1 < rooms.size() || roomIndex2 < rooms.size()) {
Как будто бы теперь и нет необходимости в этом if, всё равно потом эти проверки ниже будут

2024-08-26 20:14 UTC, mysosnovskaya commented on src/main/java/thread/eight/Room.java
> +    private List<Food> foodList = new ArrayList<>();
final нужен там, где мы не предполагаем, что поля могут изменяться. С коллекциями это почти всегда так. 
Если после final, то это всё равно обычное поле и его написание не меняется. А вот если поле static final, то это уже константа и тогда нужен верхний регистр)

2024-08-30 17:45 UTC, mysosnovskaya approved these changes

2024-08-30 17:45 UTC, merged