Решение задачи Google Photo sync
CorporationX/god_bless pull request #10142
Opened 2024-08-25 14:00 UTC by wmwmaks

2024-08-25 19:12 UTC, mysosnovskaya requested changes

2024-08-25 19:12 UTC, mysosnovskaya commented on src/main/java/threadtwo/two/GooglePhotosAutoUploader.java
> +    List<String> photosToUpload = new ArrayList<>();
Модификаторов не хватает :)

2024-08-25 19:12 UTC, mysosnovskaya commented on src/main/java/threadtwo/two/GooglePhotosAutoUploader.java
> +                        lock.wait();
Ждать лучше в цикле while, т.к. поток может выйти из ожидания и по другим причинам, не только из-за notify

2024-08-25 19:12 UTC, mysosnovskaya commented on src/main/java/threadtwo/two/GooglePhotosAutoUploader.java
> +                        uploadPhotos();
Думаю, что этот метод нужно вызвать сразу после того, как поток выйдет из ожидания. Так, конечно, тоже будет работать, но как-то логичнее будет видеть, что поток не зря ждал =) Когда дождался (вышел из wait), тогда и сделал то, что хотел (вызывал uploadPhotos)

2024-08-25 19:12 UTC, mysosnovskaya commented on src/main/java/threadtwo/two/GooglePhotosAutoUploader.java
> +                    Thread.currentThread().interrupt();
С interrupt хорошо сделано 👍

2024-08-26 08:49 UTC, wmwmaks commented
В этой задаче нормально же, что вывод вразноброс происходит?

2024-08-26 20:20 UTC, mysosnovskaya approved these changes

2024-08-26 20:20 UTC, mysosnovskaya commented
> В этой задаче нормально же, что вывод вразноброс происходит?

Да, тут всё ок)

2024-08-26 20:20 UTC, merged