Решение задачи Supercow!
CorporationX/god_bless pull request #10143
Opened 2024-08-25 14:02 UTC by wmwmaks

Я не запутался. У меня joinBattle работает как надо или нет?
Вроде, все проходят по списку пользователей, но как-то неправильно по ощущениям вывод сообщений происходит.
Player Tom создал лобби.
Цель: Победить босса Diablo
Player Mary присоединился.
Текущее число игроков в лобби:2
Это верно, а дальше...
Mary вышел из лобби. Текущее число игроков: 1
Лобби полное. Вы в очереди на подключение.  ------- почему тут выводится, что лобби полное.
Player Maks присоединился.

2024-08-25 19:34 UTC, mysosnovskaya requested changes

2024-08-25 19:34 UTC, mysosnovskaya commented on src/main/java/threadtwo/three/Boss.java
> +            while (currentPlayer == maxPlayers) {
Лучше на >= проверять. Это своего рода валидация, что случайно нигде не превысили лимит. Всё-таки в многопоточной среде обитаем и может быть где-то в коде ошибка и такая ситуация может случиться)

2024-08-25 19:34 UTC, mysosnovskaya commented on src/main/java/threadtwo/three/Boss.java
> +    public synchronized boolean isLobbyCreated() {
Этот метод нигде не используется, можно удалить

2024-08-25 19:34 UTC, mysosnovskaya commented on src/main/java/threadtwo/three/Boss.java
> +                System.out.println("Лобби полное. " +
Нужно сначала вывести информацию о том, что лобби полное, а потом уже ожидать. Сейчас получается так: лобби полное, вызывается метод wait, поток ожидает какое-то время и как только он выходит из ожидания, так первым делом он выводит в консоль вот это сообщение - о том, что лобби полное, хотя это уже не является правдой)

2024-08-26 08:27 UTC, wmwmaks commented on src/main/java/threadtwo/three/Boss.java
> +                System.out.println("Лобби полное. " +
Просто поменять строчки местами... а я сидел голову ломал

2024-08-26 20:28 UTC, mysosnovskaya approved these changes

2024-08-26 20:29 UTC, merged