Асинхронность и Future BJS2-24619
CorporationX/god_bless pull request #10162
Opened 2024-08-25 19:19 UTC by sultan-inked

2024-08-28 20:26 UTC, 20cognosce requested changes

2024-08-28 20:26 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/async/async/and/future/MasterCardService.java
> +    }
Ты достаешь еще не посчитанные результаты, и на get() просто встаешь в блокировку, где тут ожидание вычислений?

Надо доставать значение от get() только когда уже всё посчитано.
Проверь isDone() перед get()

Нужно “присоединиться” к тому потоку, завершения которого ждём. Какой метод может помочь?

2024-08-29 07:56 UTC, sultan-inked commented
Прости, я не совсем понял, что ты имеешь ввиду, вот так в цикле проверять `isDone()`?
```
private int paymentGet(Future<Integer> payment) {
    try {
        while(!payment.isDone()) {
        }
        return payment.get();
    } catch (InterruptedException | ExecutionException e) {
        throw new RuntimeException(e);
    }
}
```
Чем это будет отличаться от просто вызова .get()? Так ведь точно так же поток ждет, и в Future нет метода join. Или что ты имел в виду под “присоединиться”?
В `CompletableFuture` как ты написал, применил join, а в `Future` метод `get()` только, и в условии ведь так и задумано что вызывающий метод поток должен ждать?

2024-08-29 17:43 UTC, 20cognosce approved these changes

2024-08-29 17:43 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/async/async/and/future/MasterCardService.java
> +        }
Это лишнее

2024-08-29 17:43 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/async/async/and/future/MasterCardService.java
> +        return analytics.join();
Нужно было просто задействовать этот метод

2024-08-29 17:43 UTC, merged