Решение задачи Счетчик просмотров на YouTube
CorporationX/god_bless pull request #10199
Opened 2024-08-26 10:29 UTC by wmwmaks

Тут нужно обязательно использовать map? Сначала сделал и потом открыл подсказку. 
Получается тогда в addView и getViewCount нужно делать synchronized(map), но без wait и notify просто, чтобы одновременно не меняли значения мапы?

2024-08-26 20:26 UTC, mysosnovskaya requested changes

2024-08-26 20:26 UTC, mysosnovskaya commented on src/main/java/threadtwo/five/VideoManager.java
> +    private static List<Video> videos = new ArrayList<>();
Нужна именно Map<String, Video>. В синхронизации ничего не измениться, но привязывание id видео к индексу в списке в будущем вызовет проблемы. Например, если какое-нибудь видео удалиться. Или если мы захотим генерировать id по-другому. В общем, в таком виде List никогда не используют, для хранения данных по id есть Map

2024-08-26 20:28 UTC, mysosnovskaya commented
> Тут нужно обязательно использовать map? Сначала сделал и потом открыл подсказку. Получается тогда в addView и getViewCount нужно делать synchronized(map), но без wait и notify просто, чтобы одновременно не меняли значения мапы?

Да, Map обязательно, написала в комментарии об этом.
Синхронизацию менять не нужно, она от выбранной коллекции не зависит. А задача действительно без wait и notify

2024-08-30 17:54 UTC, mysosnovskaya requested changes

2024-08-30 17:54 UTC, mysosnovskaya commented on src/main/java/threadtwo/five/VideoManager.java
> +    private static Map<String, Video> videos = new HashMap<>();
А почему поле не финальное? В реализации не предполагается, что videos можно будет изменять (когда говорим про final, то имеется в виду именно ссылка на созданный объект (в нашем случае HashMap), а содержимое по этой ссылке, конечно, может меняться)

2024-08-30 18:09 UTC, wmwmaks commented on src/main/java/threadtwo/five/VideoManager.java
> +    private static Map<String, Video> videos = new HashMap<>();
Чего ж я так в этих полях путаюсь. Постараюсь больше этому внимания уделять

2024-08-30 18:12 UTC, wmwmaks commented on src/main/java/threadtwo/five/VideoManager.java
> +    private static Map<String, Video> videos = new HashMap<>();
И если они у меня static final, пишу заглавными

2024-08-30 18:22 UTC, mysosnovskaya commented on src/main/java/threadtwo/five/VideoManager.java
> +    private static Map<String, Video> videos = new HashMap<>();
Вообще VIDEOS лучше не делать static, т.к. у нас всё-таки предполагается, что оно индивидуально для каждого объекта класса  VideoManager

2024-08-30 19:13 UTC, wmwmaks commented on src/main/java/threadtwo/five/VideoManager.java
> +    private static Map<String, Video> videos = new HashMap<>();
Понял, сделал его не static и методы тоже сделал не static, чтобы можно было поле использовать. И main поменял чуть-чуть.

2024-08-30 20:12 UTC, mysosnovskaya approved these changes

2024-08-30 20:12 UTC, merged