Железный трон любой ценой
CorporationX/god_bless pull request #10224
Opened 2024-08-26 15:25 UTC by fragmatik-top

Правильно ли добавлять в конструктор элементы в Map ? или есть другой способ ? (Мне нужно было, при создании объекта типа house, были одни и те же элементы в Map) 
И что лучшее использовать Map или EnumMap ?

2024-08-28 16:57 UTC, mikhailov26 requested changes

2024-08-28 16:57 UTC, mikhailov26 commented on src/main/java/com/multithreading/thron/Main.java
> +            }
Очень странная конструкция, проведи рефакторинг

2024-08-29 15:46 UTC, mikhailov26 commented
Относительно твоего вопроса, покажу на дейлике

2024-08-31 10:56 UTC, mikhailov26 requested changes

2024-08-31 10:56 UTC, mikhailov26 commented on src/main/java/com/multithreading/thron/Main.java
> +            service.shutdownNow();
Так, я прошу прощения, видимо не совсем корректно выразился, !awaitTermination в if и в фигуржных скобках shutdownNow

2024-08-31 10:58 UTC, mikhailov26 commented
Относительно вопроса про мапу, ты в классе можешь сделать статический метод, который принимает/создаёт новую мапу, наполняет её и возвращает, и его вызвать в конструкторе

2024-08-31 13:13 UTC, fragmatik-top commented
А можно ли создать в статическом блоке map и добавить элементы ?

2024-09-01 14:44 UTC, mikhailov26 commented
В целом да, но на практике эти блоки используются немного для другого, а главное не часто, т.к. возникают некоторые проблемы, лично мне больше нравится для таких задач стат методы

2024-09-01 14:44 UTC, merged