Mice are very nice!
CorporationX/god_bless pull request #10272
Opened 2024-08-27 07:23 UTC by RuslanIovlev

2024-08-27 17:43 UTC, mysosnovskaya requested changes

2024-08-27 17:43 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/BJS2_23869/Room.java
> +    private List<Food> foodInRoom;
Поле лучше сделать final, т.к. мы не подразумеваем, что кто-то может его изменить (ты как раз поэтому не добавил сеттер для него)

2024-08-27 17:43 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/BJS2_23869/Food.java
> +    private String foodDescription;
Поле лучше сделать final, т.к. мы не подразумеваем, что кто-то может его изменить (ты как раз поэтому не добавил сеттер для него)

2024-08-27 17:43 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/BJS2_23869/House.java
> +    public void collectFood() {
По заданию этот метод должен собирать еду только из двух комнат

2024-08-27 17:43 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/BJS2_23869/House.java
> +            executor.schedule(house::collectFood, 30 * i, TimeUnit.SECONDS);
Сейчас будет так: каждые 30 секунд происходит сбор еды сразу из всех комнат. А кроме того, на 43 строке вся еда из комнат уже исчезнет. Это произойдет даже до того, как стартанет первый поток. Так не должно быть =)  Нужно, чтобы каждые 30 секунд еда собиралась из очередных двух комнат. После сбора еды комнаты должны стать пустыми.

2024-08-31 17:22 UTC, mysosnovskaya requested changes

2024-08-31 17:22 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/BJS2_23869/House.java
> +        foodsInHouse.addAll(foodToCollect);
В соответствующих комнатах теперь не должно быть еды, её нужно оттуда удалить

2024-08-31 17:22 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/BJS2_23869/House.java
> +    public void collectFood(int startIndex) {
Сейчас из сигнатуры метода непонятно, что он собирает еду именно из двух комнат. Я бы не усложняла и просто передала бы сюда два индекса - индексы тех комнат, откуда нужно собрать еду. Так будет очевидно и другим разработчикам, и код будет выглядеть проще

2024-09-01 04:06 UTC, RuslanIovlev commented on src/main/java/faang/school/godbless/BJS2_23869/House.java
> +        foodsInHouse.addAll(foodToCollect);
я создал в room отдельный метод для собирания еды и сразу удаления ее из комнаты

2024-09-01 17:39 UTC, mysosnovskaya approved these changes

2024-09-01 17:39 UTC, merged