BJS2-24943 Асинхронность и Future
CorporationX/god_bless pull request #10281
Opened 2024-08-27 08:44 UTC by cemeh666

2024-08-28 21:02 UTC, 20cognosce requested changes

2024-08-28 21:02 UTC, 20cognosce commented on src/main/java/asynchrony/and/future/Main.java
> +            System.out.println("Результат выполнения collectPayment: " + resultCollectPayment.get());
Ты достаешь еще не посчитанные результаты, и на get() просто встаешь в блокировку, где тут ожидание вычислений?

Надо доставать значение от get() только когда уже всё посчитано.
Проверь isDone() перед get() и после

2024-08-29 06:58 UTC, cemeh666 commented on src/main/java/asynchrony/and/future/Main.java
> +            System.out.println("Результат выполнения collectPayment: " + resultCollectPayment.get());
подправил

2024-08-29 17:47 UTC, 20cognosce approved these changes

2024-08-29 17:47 UTC, 20cognosce commented on src/main/java/asynchrony/and/future/Main.java
> +            while (!resultCollectPayment.isDone()) {
Так делать не надо, я для самопроверки написал его пробовать

2024-08-29 17:48 UTC, merged