Решение задачи Асинхронность и Future
CorporationX/god_bless pull request #10315
Opened 2024-08-27 14:53 UTC by lexus-74

2024-08-28 20:50 UTC, 20cognosce requested changes

2024-08-28 20:50 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_24790/MasterCardService.java
> +import java.util.concurrent.*;
Не сворачивай импорты

2024-08-28 20:50 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_24790/MasterCardService.java
> +            completableFuture.thenAccept(System.out::println);
Сделай на аналитику 10 секунд, на оплату 1 секунду

И напиши в таком порядке:
```
Future<Integer> collectIntegerFuture = service.submit(this::collectPayment);

CompletableFuture<Integer> completableFuture = CompletableFuture.supplyAsync(this::sendAnalytics, service).thenAccept(System.out::println)

collectPaymentResult.get();
```

2024-08-28 20:50 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_24790/MasterCardService.java
> +            completableFuture.thenAccept(System.out::println);
И это нужно доработать так, чтобы сначала вывелась 10-ти секундная аналитика, а потом 1-секундная оплата.

2024-08-29 17:45 UTC, 20cognosce approved these changes

2024-08-29 17:45 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_24790/MasterCardService.java
> +import java.util.concurrent.*;
Где исправление

2024-08-29 17:45 UTC, merged

2024-08-30 10:05 UTC, lexus-74 commented
import lombok.NoArgsConstructor;

import java.util.concurrent.*;

Где исправление

Не понял, что здесь нужно исправить?