BJS2-25107 Fan out – Fan In
CorporationX/god_bless pull request #10380
Opened 2024-08-28 07:07 UTC by vestmen

2024-08-30 12:11 UTC, 20cognosce requested changes

2024-08-30 12:11 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint4/fanOutFanIn/Main.java
> +        executor = Executors.newFixedThreadPool(requests.size());
Зачем он тебе нужен?

2024-08-30 12:11 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint4/fanOutFanIn/Main.java
> +                        .runAsync(() -> request.longTimeSquare(resultConsumer), executor));
Ты можешь дефолтный использовать

2024-08-30 12:11 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint4/fanOutFanIn/Main.java
> +    private static Stream<CompletableFuture<Void>> streamOfCompletableFutures() {
Стрим нельзя хранить или возвращать, это не коллекция

2024-08-30 12:11 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint4/fanOutFanIn/Main.java
> +        return resultConsumer.add(0L);
?

2024-08-31 07:30 UTC, vestmen commented on src/main/java/faang/school/godbless/sprint4/fanOutFanIn/Main.java
> +                        .runAsync(() -> request.longTimeSquare(resultConsumer), executor));
попробовал использовать дефолный, по времени стало намного дольше обрабатывать 1000 потоков. Сделал вывод потоков в обоих случаях, со своим выводилось:
pool-1-thread-809 и тд до 1000 (в одном пуле все сразу), а с дефолтным в одном пуле только до 11 (ForkJoinPool.commonPool-worker-11).

2024-08-31 07:30 UTC, vestmen commented on src/main/java/faang/school/godbless/sprint4/fanOutFanIn/Main.java
> +    private static Stream<CompletableFuture<Void>> streamOfCompletableFutures() {
понял

2024-09-01 10:27 UTC, 20cognosce approved these changes

2024-09-01 10:27 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint4/fanOutFanIn/Main.java
> +//                        .thenRun(() -> System.out.println(Thread.currentThread().getName()))
Никаких археологических находок в коде быть не должно

2024-09-01 10:27 UTC, merged