BJS2-24883 Турнир трех волшебников
CorporationX/god_bless pull request #10416
Opened 2024-08-28 12:14 UTC by vestmen

2024-08-29 19:40 UTC, 20cognosce requested changes

2024-08-29 19:40 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint4/triwizardTournament/MagicalTournament.java
> +    }
Вот это криво написано, надо навести красоту
null нельзя возвращать, избегай этого

2024-08-29 19:40 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint4/triwizardTournament/Tournament.java
> +        return CompletableFuture.supplyAsync(() -> school, executor)
Что это за задача в supplyAsync, что она делает? Ничего

2024-08-29 19:40 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint4/triwizardTournament/Tournament.java
> +                .thenApply(skilledSchool -> {
нет, школа станет "skilled" когда оценки уже увеличены
где-то я уже видел это решение

2024-08-29 19:40 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint4/triwizardTournament/MagicalTournament.java
> +    private static final ExecutorService executor = Executors.newFixedThreadPool(QUANTITY_OF_SCHOOLS);
А нужен планировщик вообще? 3 CompletableFuture можешь создать без него

2024-08-31 06:32 UTC, vestmen commented on src/main/java/faang/school/godbless/sprint4/triwizardTournament/Tournament.java
> +        return CompletableFuture.supplyAsync(() -> school, executor)
исправил

2024-08-31 06:33 UTC, vestmen commented on src/main/java/faang/school/godbless/sprint4/triwizardTournament/Tournament.java
> +                .thenApply(skilledSchool -> {
понял

2024-08-31 06:33 UTC, vestmen commented on src/main/java/faang/school/godbless/sprint4/triwizardTournament/MagicalTournament.java
> +    }
поправил

2024-09-01 10:12 UTC, 20cognosce approved these changes

2024-09-01 10:12 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint4/triwizardTournament/MagicalTournament.java
> +                School winner = winners.get(0);
Не очень понятно, почему метод победителя отдает список
Это не логично

2024-09-01 10:12 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint4/triwizardTournament/MagicalTournament.java
> +                School winner = winners.get(0);
Назови его тогда, arrangeTournamentScores() типо того

2024-09-01 10:12 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint4/triwizardTournament/Tournament.java
> +                    .forEach(student -> student.setPoints(student.getPoints() + task.getDifficulty() * task.getReward()));
Хорошо, но не в одну строчку

2024-09-01 10:12 UTC, merged