Пошлите ворона!
CorporationX/god_bless pull request #10437
Opened 2024-08-28 14:00 UTC by SharkB38

Задача Пошлите ворона!
https://faang-school.atlassian.net/browse/BJS2-24788

2024-08-28 18:16 UTC, mysosnovskaya requested changes

2024-08-28 18:16 UTC, mysosnovskaya commented on src/main/java/crow/Main.java
> +        try (ExecutorService executor = Executors.newFixedThreadPool(POOL_SIZE)) {
Также как и в других ПР вопрос про оправданность executor-а

2024-08-28 18:16 UTC, mysosnovskaya commented on src/main/java/crow/Main.java
> +            var futures = kingdoms.stream()
Сейчас очень сложно написано.
1. Я бы использовала два цикла for для упрощения чтения.
2. Создание CompletableFuture можно вынести в метод sendRaven. Сейчас sendRaven вообще никакой логикой по сути не обладает и не особо понятно, зачем он нужен. В целом можно было бы код из sendMessage перенести в sendRaven, т.к. в данный момент иметь оба этих метода выглядит избыточным
3. В handle вместо r и e всё-таки лучше использовать result и exeption (или хотя бы ex). Однобуквенные имена переменных пугают, хотя иногда допускаются. Например, в блоке catch, где очевидно, что e - это исключение и ничего другого. Но в основном всё-таки лучше стараться не экономить на буквах =)

2024-08-29 17:46 UTC, mysosnovskaya requested changes

2024-08-29 17:46 UTC, mysosnovskaya commented on src/main/java/crow/Main.java
> +                            .handle((result, ex) -> {
Давай ещё порефакторим) Такой уровень вложенности пугает. Предлагаю следующие шаги:
1. Обработку вынести в отдельный приватный метод
2. Для результата sendRaven создать отдельную переменную, а уже потом её сложить в futures
3. Можно вместо for-each циклов использовать обычный for: первый с индексами от 0 до n-1, а второй от 1 до n. Тогда if можно не делать.

2024-08-30 05:29 UTC, SharkB38 commented on src/main/java/crow/Main.java
> +                            .handle((result, ex) -> {
Немного по другому сделал, надеюсь подойдет

2024-08-30 18:27 UTC, mysosnovskaya approved these changes

2024-08-30 18:28 UTC, mysosnovskaya commented on src/main/java/crow/Main.java
> +                            .handle((result, ex) -> {
Да, так значительно лучше 👍

2024-08-30 18:28 UTC, merged