BJS2-25118 Качаем алхимию
CorporationX/god_bless pull request #10458
Opened 2024-08-28 17:14 UTC by vestmen

2024-08-30 14:16 UTC, 20cognosce requested changes

2024-08-30 14:16 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint4/elderScrolls/Main.java
> +                .join();
Вот это упростить и переделать

2024-08-30 14:16 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint4/elderScrolls/Main.java
> +                .join();
Зачем ты тут делаешь addAndGet

2024-08-30 14:16 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint4/elderScrolls/Main.java
> +        sumOfAllIngredients.addAndGet(requiredIngredients);
Если ты это и тут делаешь

2024-08-30 14:16 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint4/elderScrolls/Main.java
> +                        .forEach(future -> sumOfAllIngredients.addAndGet(future.join())))
И почему ты обращаешься к future, ты должен работать с тем, что тебе пришло из Future

2024-08-31 07:41 UTC, vestmen commented on src/main/java/faang/school/godbless/sprint4/elderScrolls/Main.java
> +                .join();
да, получается 2 раза суммировал, исправил

2024-09-01 10:35 UTC, 20cognosce approved these changes

2024-09-01 10:35 UTC, merged