BJS2-24909 - Синхронность и Future
CorporationX/god_bless pull request #10474
Opened 2024-08-28 20:32 UTC by mrkorolev

2024-08-28 21:00 UTC, 20cognosce requested changes

2024-08-29 19:51 UTC, mrkorolev commented on src/main/java/faang/school/godbless/sprint4/async_future/Main.java
> +            int payment = paymentFuture.get();
@20cognosce А в задании сказано не просто блокироваться? Но ок, переделаю

2024-08-29 21:19 UTC, mrkorolev commented on src/main/java/faang/school/godbless/sprint4/async_future/Main.java
> +            int payment = paymentFuture.get();
Для сбора аналитики блокируюсь на join(), для платежа проверяю isDone() внутри цикла (хотел сначала написать print, но оставил без лишней нагрузки, while же очень часто проверяется).

2024-08-30 11:41 UTC, 20cognosce approved these changes

2024-08-30 11:41 UTC, merged