Mice are very nice! : Giuseppe bjs2 23871
CorporationX/god_bless pull request #10493
Opened 2024-08-29 08:33 UTC by GaribAghayev

2024-08-29 19:46 UTC, 20cognosce requested changes

2024-08-29 19:46 UTC, 20cognosce commented on src/main/java/faang/school/godbless/ThirdSprint/BJS2_23871/House.java
> +        while (house.roomList.stream().flatMap(r -> r.getFoodList().stream()).toList().size() > 0) {
в условии жесть написана

2024-08-29 19:46 UTC, 20cognosce commented on src/main/java/faang/school/godbless/ThirdSprint/BJS2_23871/House.java
> +                });
Не писать стрим в стриме

2024-08-29 19:46 UTC, 20cognosce commented on src/main/java/faang/school/godbless/ThirdSprint/BJS2_23871/House.java
> +                });
Где блокировки? Несколько потоков модернизируй комнаты, и одновременно еще пишут в collectFood (да, с задержкой, но все равно это чревато)

Почему ты не раскидал каждому потоку по 2 комнаты?

Всё переделать

2024-08-30 07:27 UTC, GaribAghayev commented on src/main/java/faang/school/godbless/ThirdSprint/BJS2_23871/House.java
> +        while (house.roomList.stream().flatMap(r -> r.getFoodList().stream()).toList().size() > 0) {
Согласен. Удалил

2024-08-30 07:28 UTC, GaribAghayev commented on src/main/java/faang/school/godbless/ThirdSprint/BJS2_23871/House.java
> +                });
стрим в collect переделал.
Блокировку чего ты хочешь увидеть? в задаче не было пункта про блокировку. Уточни пожалуйста

2024-08-30 07:32 UTC, GaribAghayev commented on src/main/java/faang/school/godbless/ThirdSprint/BJS2_23871/House.java
> +                });
Что ты имеешь ввиду под "раскидал каждому потоку по две комнаты" ?

2024-08-30 11:36 UTC, 20cognosce commented on src/main/java/faang/school/godbless/ThirdSprint/BJS2_23871/House.java
> +                });
В методе collectFood() из объекта house, соберите еду из двух комнат и добавьте её в список собранной еды

две комнаты для каждого потока
список собранной еды должен быть синхронизирован

2024-08-30 11:37 UTC, 20cognosce requested changes

2024-08-30 11:37 UTC, 20cognosce commented on src/main/java/faang/school/godbless/ThirdSprint/BJS2_23871/House.java
> +            },5, TimeUnit.SECONDS);
все 5 потоков запустятся через 5 секунд, это неправильно

2024-08-30 11:37 UTC, 20cognosce commented on src/main/java/faang/school/godbless/ThirdSprint/BJS2_23871/House.java
> +//                }
Что это

2024-08-30 11:37 UTC, 20cognosce commented on src/main/java/faang/school/godbless/ThirdSprint/BJS2_23871/House.java
> +                });
Где блокировки, почему каждый поток собирает еду во всех комнатах

2024-09-01 09:50 UTC, 20cognosce requested changes

2024-09-01 09:50 UTC, 20cognosce commented on src/main/java/faang/school/godbless/ThirdSprint/BJS2_23871/House.java
> +            },30, TimeUnit.SECONDS);
Ты все потоки запускаешь одновременно через 30 секунд

А надо
00:00 - первый
00:30 - второй
01:00 - третий
и т.д.

scheduledAtFixedRate или вместо 30 надо передавать 30 * (i + 1)

2024-09-01 09:50 UTC, 20cognosce commented on src/main/java/faang/school/godbless/ThirdSprint/BJS2_23871/House.java
> +                    .sorted((a, b) -> b.getFoodList().size() - a.getFoodList().size())
Ты жестко синхронизировал этот метод, так еще и в нем выполняешь долгие операции сортировки всего списка комнат

Какая тут параллельность?

2024-09-01 09:50 UTC, 20cognosce commented on src/main/java/faang/school/godbless/ThirdSprint/BJS2_23871/House.java
> +                    .limit(2)
Тебе не надо это делать, каждому потоку надо передавать заготовленные Pair<Room> и всё

2024-09-01 09:50 UTC, 20cognosce commented on src/main/java/faang/school/godbless/ThirdSprint/BJS2_23871/House.java
> +                        collectedFood.addAll(u.getFoodList());
Синхронизация нужна только на строчке collectedFood.addAll, всё остальное можно отпустить

2024-09-02 08:19 UTC, merged