BJS2-25328 Оставляем комментарий
CorporationX/god_bless pull request #10506
Opened 2024-08-29 11:11 UTC by cemeh666

2024-09-01 02:39 UTC, amilosh commented on src/main/java/leave/comments/PostService.java
> +            Post post = removingPost.get();
Тут можно
this.findPostById(postId)
.ifPrsent(post -> {...});

2024-09-01 02:42 UTC, amilosh commented on src/main/java/leave/comments/PostService.java
> +                            post.get().removeComment(comment);
Не рекомендовано внутри стрима удалять элемент.

В интерфейсе Collection есть красивый метод.

2024-09-01 10:39 UTC, cemeh666 commented on src/main/java/leave/comments/PostService.java
> +                            post.get().removeComment(comment);
согласен

2024-09-01 10:39 UTC, cemeh666 commented on src/main/java/leave/comments/PostService.java
> +            Post post = removingPost.get();
переделал

2024-09-03 19:03 UTC, 20cognosce requested changes

2024-09-03 19:03 UTC, 20cognosce commented on src/main/java/leave/comments/PostService.java
> +    }
Это не поиск, это перебор
Поработай над эффективностью

2024-09-03 19:03 UTC, 20cognosce commented on src/main/java/leave/comments/PostService.java
> +    public void removeComment(long postId, Comment comment) {
volatile тебе дает единство чтения, но не какой-либо синхронизации

2024-09-03 19:03 UTC, 20cognosce commented on src/main/java/leave/comments/PostService.java
> +            synchronized (this.lock) {
Тут состояние всего могло 150 раз поменяться, пока ты до лока дошел

2024-09-03 19:03 UTC, 20cognosce commented on src/main/java/leave/comments/PostService.java
> +    private final Object lock = new Object();
Если бы у каждого поста был свой лок
ты бы в чем-то выиграл?

Посты между собой ведь никак не связаны.

2024-09-04 07:36 UTC, cemeh666 commented on src/main/java/leave/comments/PostService.java
> +            });
переделал лок

2024-09-04 07:36 UTC, cemeh666 commented on src/main/java/leave/comments/PostService.java
> +                    });
вынес логику в Post

2024-09-04 07:36 UTC, cemeh666 commented on src/main/java/leave/comments/PostService.java
> +            synchronized (this.lock) {
переделал

2024-09-04 07:37 UTC, cemeh666 commented on src/main/java/leave/comments/PostService.java
> +    private final Object lock = new Object();
убрал общий лок

2024-09-04 07:37 UTC, cemeh666 commented on src/main/java/leave/comments/PostService.java
> +    }
переделал на Map

2024-09-04 07:37 UTC, cemeh666 commented on src/main/java/leave/comments/PostService.java
> +    public void removeComment(long postId, Comment comment) {
добавил блокировку

2024-09-04 17:39 UTC, 20cognosce approved these changes

2024-09-04 17:39 UTC, 20cognosce commented on src/main/java/leave/comments/PostService.java
> +public class PostService {
Вся логика в классе супер гуд

2024-09-04 17:39 UTC, 20cognosce commented on src/main/java/leave/comments/Post.java
> +    private volatile List<Comment> comments = new ArrayList<>();
Вот это непонятно зачем

2024-09-04 17:39 UTC, 20cognosce commented on src/main/java/leave/comments/Post.java
> +    }
И в Post нежелательно иметь логику, так как 
1. Сущность только хранит данные, они ими сама не оперирует, сущность изменяет сервис
2. В PostService ты все засихнронизировал, а если другой сервис захочет использовать Post, и увидит в нем такие методы, он о синхронизации и не подумает, ты же уже сам что-то имплементировал

2024-09-04 17:39 UTC, merged