Оставляем комментарий
CorporationX/god_bless pull request #10511
Opened 2024-08-29 12:15 UTC by SharkB38

Задача Оставляем комментарий
https://faang-school.atlassian.net/browse/BJS2-25371

Не понял зачем тут volatile на списке комментариев

2024-08-29 18:09 UTC, mysosnovskaya requested changes

2024-08-29 18:09 UTC, mysosnovskaya commented on src/main/java/commenting/PostService.java
> +    private final List<Post> posts = new ArrayList<>();
Про volatile согласна. Если поле final, то в volatile нет смысла. Если бы поле могло изменяться, то смысл был бы, но в текущей задачи такого не подразумевается

2024-08-29 18:09 UTC, mysosnovskaya commented on src/main/java/commenting/PostService.java
> +        synchronized (postLocks.get(posts.get(id))) {
Я бы не стала привязывать id к позиции в списке. В общем случае это неверно (комментарий может быть удален или, например, id могут начинаться с 1, а позиции в списке - с 0)

2024-08-29 18:09 UTC, mysosnovskaya commented on src/main/java/commenting/PostService.java
> +            posts.get(id).getComments().add(comment);
Если представить, что за каждым постом мы ходим в базу данных, то в текущей реализации к базе данных будет два запроса, а это довольно дорого по времени. Лучше обойтись одним запросом, тем более здесь это сделать очень легко.

2024-08-29 18:09 UTC, mysosnovskaya commented on src/main/java/commenting/PostService.java
> +    private final Map<Post, Object> postLocks = new HashMap<>();
Если ты используешь Post в качестве ключа в хэш-мапе, то нужно переопределить у него equals и hashcode

2024-08-29 18:09 UTC, mysosnovskaya commented on src/main/java/commenting/PostService.java
> +public class PostService {
В шестом пункте задания также предлагается добавить методы для просмотра и удаления постов и комментариев и протестировать с ними. Настоятельно рекомендую это сделать

2024-08-30 06:19 UTC, SharkB38 commented on src/main/java/commenting/PostService.java
> +            posts.get(id).getComments().add(comment);
А как? Чтобы синхронизация по локу сохранилась и с теми же переменными?

2024-09-02 18:50 UTC, mysosnovskaya requested changes

2024-09-02 18:50 UTC, mysosnovskaya commented on src/main/java/commenting/PostService.java
> +            postIdx.remove(id);
Поток 1: начинает выполнять addComent, убеждается, что пост с заданным id есть
Поток 2: делает все проверки и удаляет пост с заданным (тем же самым) id
Поток 1: получает лок для поста
Поток 2: Удаляет лок для этого же поста
Поток 1: получает пост, чтобы добавить коммент -> NullPointerException

Похоже, здесь и сломается)

2024-09-02 18:50 UTC, mysosnovskaya commented on src/main/java/commenting/PostService.java
> +    public void addComment(@NonNull Comment comment, int id) {
Вместо id лучше назвать postId

2024-09-02 18:50 UTC, mysosnovskaya commented on src/main/java/commenting/PostService.java
> +                if (commentIdx.get(commentId) == id) {
Поток 1: начинает выполнять addComent, убеждается, что пост с заданным id есть, получает лок для поста, получает пост
Поток 2: делает все проверки и удаляет пост с заданным (тем же самым) id, удаляет лок для этого же поста, формирует idSet и удаляет комментарии
Поток 1: добавляет комментарий для полученного ранее поста -> неконсистентность данных

2024-09-02 18:50 UTC, mysosnovskaya commented on src/main/java/commenting/PostService.java
> +            synchronized (postLocks.get(postId)) {
Если другой поток уже успел удалить пост и лок для него, то здесь будет ошибка. Или на следующей строке, если успели удалить только пост

2024-09-02 18:50 UTC, mysosnovskaya commented on src/main/java/commenting/PostService.java
> +            posts.get(id).getComments().add(comment);
Это я перепутала, думала, что в обеих строчках к одной и той же коллекции доступ происходит. Сейчас увидела, что это не так, тогда ок)

2025-01-17 21:22 UTC, closed without merging