Решение задачи Fan out – Fan In
CorporationX/god_bless pull request #10597
Opened 2024-08-30 13:33 UTC by lexus-74

2024-08-30 14:34 UTC, 20cognosce requested changes

2024-08-30 14:34 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_25170/Main.java
> +        ExecutorService service = Executors.newFixedThreadPool(requests.size());
Он тебе нужен?

2024-08-30 14:34 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_25170/Main.java
> +        CompletableFuture.allOf(futures.get(0)).join();
Не понял, почему ты дожидаешься только один поток?

2024-08-30 14:34 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_25170/Main.java
> +                .forEach(index -> requests.add(new SquareRequest(index)));
Вот это объединить в одно действие, возвращающее список

2024-08-31 10:10 UTC, lexus-74 commented on src/main/java/faang/school/godbless/BJS2_25170/Main.java
> +        ExecutorService service = Executors.newFixedThreadPool(requests.size());
Не понял вопроса

2024-09-01 10:28 UTC, 20cognosce approved these changes

2024-09-01 10:29 UTC, merged