Качаем алхимию
CorporationX/god_bless pull request #10595
Opened 2024-08-30 12:51 UTC by fragmatik-top

2024-09-01 18:35 UTC, mikhailov26 requested changes

2024-09-01 18:35 UTC, mikhailov26 commented on src/main/java/com/multithreading/alchemy/Сreation.java
> +    private static final Random RANDOM = new Random();
Не вижу где он используется

2024-09-02 12:38 UTC, fragmatik-top commented on src/main/java/com/multithreading/alchemy/Сreation.java
> +    private static final Random RANDOM = new Random();
38 строчка
Мы определяем кол-во ингредиентов для нужного зелья

2024-09-02 19:19 UTC, mikhailov26 approved these changes

2024-09-02 19:19 UTC, merged