Задача Турнир трех волшебников
CorporationX/god_bless pull request #10623
Opened 2024-08-30 19:07 UTC by wmwmaks

2024-08-31 17:54 UTC, mysosnovskaya requested changes

2024-08-31 17:54 UTC, mysosnovskaya commented on src/main/java/async/four/School.java
> +@Getter
Пустой строчки перед аннотацией не хватает

2024-08-31 17:54 UTC, mysosnovskaya commented on src/main/java/async/four/Tournament.java
> +        ExecutorService executor = Executors.newSingleThreadExecutor();
На мой взгляд, executor можно не заводить. Достаточно будет того, который есть внутри CompletableFuture. Свой собственный мы заводим только тогда, когда это по каким-то причинам выгодно. Например, когда нужно увеличить количество потоков

2024-08-31 18:20 UTC, wmwmaks commented on src/main/java/async/four/Tournament.java
> +        ExecutorService executor = Executors.newSingleThreadExecutor();
Посмотрел запись дейли встречи, увидел ваши рассуждения на эту тему, но на тот момент уже отправил задачу)
У меня так же, как у парней, из-за того, что Влад в лекции говорил, что хорошо было бы так делать)

2024-09-01 17:56 UTC, mysosnovskaya approved these changes

2024-09-01 17:56 UTC, merged