wow
CorporationX/god_bless pull request #10659
Opened 2024-08-31 10:43 UTC by natalia-dch

2024-08-31 10:46 UTC, natalia-dch commented
На 99% уверена, что сделала неправильно. Почему без join thenAccept не выполняется? В целом логично, без  join main-thread умрёт и (правда же?) убъет дочерние потоки.

Но с join последней строкой main-а у меня тоже не заработало.

2024-09-01 19:31 UTC, 20cognosce requested changes

2024-09-01 19:31 UTC, 20cognosce commented on src/main/java/faang/school/godbless/wow/Main.java
> +                " " + player.getExperience() + " experience points."));
С помощью thenAccept ты описываешь как обработать результат future КОГДА он вычислится

join - дожидаешься их выполнения

Неправильный порядок, startQuest().thenAccept()

```
CompletableFuture<Void> player1Quest = questSystem.startQuest(player1, quest1)
                .thenAccept(player -> System.out.println(player.getName() + " has completed the quest and now has " + player.getExperience() + " experience points."));

CompletableFuture<Void> player2Quest = questSystem.startQuest(player2, quest2)
                .thenAccept(player -> System.out.println(player.getName() + " has completed the quest and now has " + player.getExperience() + " experience points."));

CompletableFuture.allOf(player1Quest, player2Quest).join();
```

2024-09-01 19:32 UTC, 20cognosce commented on src/main/java/faang/school/godbless/wow/Main.java
> +                " " + player.getExperience() + " experience points."));
Так всё должно работать

2024-09-08 14:27 UTC, 20cognosce approved these changes

2024-09-08 14:28 UTC, merged