25141 - WOW
CorporationX/god_bless pull request #10709
Opened 2024-08-31 20:14 UTC by evgenywork

2024-09-01 19:40 UTC, 20cognosce requested changes

2024-09-01 19:40 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/four/wow/App.java
> +        player2Quest.join();
Почему сначала дожидаешься выполнения Future, а потом говоришь как результат обработать

2024-09-02 03:25 UTC, evgenywork commented on src/main/java/faang/school/godbless/sprint/four/wow/App.java
> +        player2Quest.join();
Не сообразил , что join можно вызвать после thenAccept, потому что одна из первых задач была

2024-09-02 16:21 UTC, 20cognosce approved these changes

2024-09-02 16:21 UTC, merged