Задача Качаем алхимию
CorporationX/god_bless pull request #10741
Opened 2024-09-01 11:31 UTC by wmwmaks

2024-09-01 18:22 UTC, mysosnovskaya requested changes

2024-09-01 18:22 UTC, mysosnovskaya commented on src/main/java/async/six/Main.java
> +    public static AtomicInteger gatherIngredients(Potion potions) {
По условию этот метод должен быть асинхронным, т.е. должен вернуть CompletableFuture

2024-09-01 19:24 UTC, wmwmaks commented on src/main/java/async/six/Main.java
> +    public static AtomicInteger gatherIngredients(Potion potions) {
В этом коде нужно было делать private static final List<Potion> potions? Он как бы не должен меняться, но мне так странно делать его константой почему-то по внутренним ощущениям.

2024-09-02 18:29 UTC, mysosnovskaya commented on src/main/java/async/six/Main.java
> +    public static AtomicInteger gatherIngredients(Potion potions) {
Учитывая специфику реализации (то, что ты из main вызываешь методы и работаешь с полями), да, должно быть private static final. А вообще, если разбивать по классам в ООП стиле, то это поле должно быть private final. На групповом проекте static почти не будет встречаться, как и в реальной разработке) Сейчас он часто нужен, т.к. у нас main является static и он тянет за собой другие статик поля и методы

2024-09-02 18:30 UTC, mysosnovskaya approved these changes

2024-09-02 18:30 UTC, merged