Работа стоит
CorporationX/god_bless pull request #10757
Opened 2024-09-01 13:44 UTC by SharkB38

Задача Работа стоит
https://faang-school.atlassian.net/browse/BJS2-25390

2024-09-01 19:03 UTC, mysosnovskaya requested changes

2024-09-01 19:03 UTC, mysosnovskaya commented on src/main/java/work/waiting/department_resources/DesignResources.java
> +public class DesignResources extends Resources {
Есть ли смысл в этих классах, если они в точности повторяют класс Resources и не несут никакой дополнительной логики?

2024-09-01 19:03 UTC, mysosnovskaya commented on src/main/java/work/waiting/departments/ThreadDepartment.java
> +public class ThreadDepartment extends Thread {
Судя по всему этот класс должен быть абстрактным, т.к. по нашей логике у него обязательно должны быть наследники, переопределяющие метод run

2024-09-01 19:03 UTC, mysosnovskaya commented on src/main/java/work/waiting/departments/DesignDepartment.java
> +            lock.readLock().lock();
Блокировкой нужно заниматься внутри ресурсов. Это в нашей реализации всего два класса, которые к ним обращаются, а теоретически их может быть бесконечно много, тогда будет слишком накладно в каждом делать блокировку, к тому же про это очень легко забыть и ошибиться. А вот когда внутри Resources это будет происходить, тогда гарантированно любые обращения к нему пройдут без проблем

2024-09-02 07:16 UTC, SharkB38 commented on src/main/java/work/waiting/department_resources/DesignResources.java
> +public class DesignResources extends Resources {
Я сначала хотел оставить только Resources класс, но оставил так, чтобы было как в задании

2024-09-02 07:18 UTC, SharkB38 commented on src/main/java/work/waiting/departments/DesignDepartment.java
> +            lock.readLock().lock();
Я сделал так потому что по другому не смог воссоздать deadlock, ну и соответственно от этого уже исходил используя ReadWriteLock. Переделал с блокировками внутри Resources

2024-09-02 18:55 UTC, mysosnovskaya commented on src/main/java/work/waiting/departments/DesignDepartment.java
> +            lock.readLock().lock();
Сейчас тоже не получилось? Выглядит всё корректно. Для тестирования можно Thread.sleep добавить, чтобы убедиться, что deadlock случается.

2024-09-02 18:55 UTC, mysosnovskaya approved these changes

2024-09-02 18:55 UTC, merged