BJS2-25446 Работа стоит
CorporationX/god_bless pull request #10766
Opened 2024-09-01 15:43 UTC by ArstanSubanov

2024-09-01 19:08 UTC, mysosnovskaya requested changes

2024-09-01 19:08 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/BJS2_25446/DesignResources.java
> +public class DesignResources extends Resources {
Есть ли смысл в классах DesignResources  и MarketingResources, если они в точности повторяют класс Resources и не несут никакой дополнительной логики?

2024-09-01 19:08 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/BJS2_25446/MarketingDepartment.java
> +public class MarketingDepartment extends ThreadDepartment {
Этот класс абсолютно идентичен DesignDepartment. Точно ли так должно быть? Если да, то значит от дублирования можно избавиться

2024-09-01 19:08 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/BJS2_25446/DesignDepartment.java
> +        lock.readLock().lock();
Блокировкой нужно заниматься внутри ресурсов. Это в нашей реализации всего два класса, которые к ним обращаются, а теоретически их может быть бесконечно много, тогда будет слишком накладно в каждом делать блокировку, к тому же про это очень легко забыть и ошибиться. А вот когда внутри Resources это будет происходить, тогда гарантированно любые обращения к нему пройдут без проблем

2024-09-03 14:13 UTC, ArstanSubanov commented on src/main/java/faang/school/godbless/BJS2_25446/MarketingDepartment.java
> +public class MarketingDepartment extends ThreadDepartment {
Нет, не должны быть идентичны. Они должны были вызывать методы в разном порядке. Я когда убирал deadlock случайно сделал их идентичными(

2024-09-03 17:51 UTC, mysosnovskaya approved these changes

2024-09-03 17:51 UTC, merged