BJS2-27254: Managing team members. V.01
CorporationX/god_bless pull request #10834
Opened 2024-10-01 11:46 UTC by kraiush

2024-10-02 16:11 UTC, mikhailov26 requested changes

2024-10-02 16:11 UTC, mikhailov26 commented on src/main/java/ru/kraiush/spring/BJS2_27254/service/impl/TeamMemberServiceImpl.java
> +    }
зачем тут принудительно кидать исключение, разве не может быть такого что таблица пустая будет? провести рефакторинг с использованием Optional и подумать какой уровень логгирования взять в случае, что лист придёт пустой

2024-10-02 16:11 UTC, mikhailov26 commented on src/main/java/ru/kraiush/spring/BJS2_27254/service/impl/TeamMemberServiceImpl.java
> +    }
Аналогичная ситуация к прошлому комментарию

2024-10-02 16:11 UTC, mikhailov26 commented on src/main/java/ru/kraiush/spring/BJS2_27254/util/MapperUtil.java
> +                .setFieldMatchingEnabled(false)
Никаких комментариев в коде оставаться не должно, тем более если они не несут описательный характер

2024-10-02 16:11 UTC, mikhailov26 commented on src/main/resources/application.yml
> +#      // update // create-drop // none
убрать комментарий

2024-10-02 16:11 UTC, mikhailov26 commented on src/test/java/ru/kraiush/spring/BJS2_27254/repository/TeamMemberRepositoryTest.java
Насколько мне известно @sql выполняется каждый раз перед вызовом метода, если я прав, то в данном случае это очень затратно. В качестве альтернативы могу предложить статический метод, который нам билдит нужные сущности, затем мы кладём их в базу, достаём и делаем необходимые ассерты

2024-10-07 15:42 UTC, mikhailov26 requested changes

2024-10-07 15:42 UTC, mikhailov26 commented on src/main/java/ru/kraiush/spring/BJS2_27254/model/TeamMember.java
> +    }
зачем нам тогда нужна @AllArgsConstructor?

2024-10-07 15:42 UTC, mikhailov26 commented on src/main/java/ru/kraiush/spring/BJS2_27254/service/impl/TeamMemberServiceImpl.java
> +        return listMembers;
Зачем нам тратить время на сортировку?

2024-10-07 15:42 UTC, mikhailov26 commented on src/main/java/ru/kraiush/spring/BJS2_27254/util/MapperUtil.java
> +                .setFieldMatchingEnabled(false)
Не увидел реакции на замечание

2024-10-07 15:42 UTC, mikhailov26 commented on src/test/java/ru/kraiush/spring/BJS2_27254/repository/TeamMemberRepositoryTest.java
> +    TeamMemberRepository repository;
Используем Mockito или MockMVC

2024-10-09 15:58 UTC, mikhailov26 requested changes

2024-10-13 11:58 UTC, mikhailov26 requested changes
В рамках данной задачи не нужно реализовывать спринг секьюрити, просьба откатить на вариант без использования безопасности!

2024-10-13 12:04 UTC, mikhailov26 commented
И опять я не вижу никакой реакции на сови замечания!
![image](https://github.com/user-attachments/assets/0bf805b2-9d7b-45d6-94e9-bfb07ad95793)
![image](https://github.com/user-attachments/assets/fcb29771-3cae-428d-88d7-722f3aeabf56)
![image](https://github.com/user-attachments/assets/da1979c0-c2b2-4e2e-b2af-8849c56066f4)

2024-10-13 12:58 UTC, kraiush commented
1) @AllArgConstructor  был раньше в классе TeamMember, где не было @Builder
но было и отношение List<Phone> phones. Поэтому и стоял конструктор для
всех элементов, кроме phones. Это класс заменен на User с @Builder  и такой
конструктор действительно теперь (!) не нужен  - убрал  (раньше замечания
не было)!
2) Пропустил - убрать коммент в MapperUtil - убрал (все коммменты в
остальных местах удалены)!
3)  Сортировку в сервисе для findAll() по индексу убрал (раньше замечания
не было)
4) Я не представляю как реализовать такую задачу без Spring Security! Вот
требование из задачи: "Добавление участников в команду. Добавлять
участников в команду может только владелец проекта (*owner*), либо участник
с ролью *TEAMLEAD*. При добавлении участника в команду ему можно присвоить
роль на проекте, уровень доступа к ресурсам."



On Sun, Oct 13, 2024 at 3:04 PM Viacheslav Mikhailov <
***@***.***> wrote:

> И опять я не вижу никакой реакции на сови замечания!
> image.png (view on web)
> <https://github.com/user-attachments/assets/0bf805b2-9d7b-45d6-94e9-bfb07ad95793>
> image.png (view on web)
> <https://github.com/user-attachments/assets/fcb29771-3cae-428d-88d7-722f3aeabf56>
> image.png (view on web)
> <https://github.com/user-attachments/assets/da1979c0-c2b2-4e2e-b2af-8849c56066f4>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/CorporationX/god_bless/pull/10834#issuecomment-2408951926>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEE7BGPNP2CUNP7S26JBO2LZ3JOVRAVCNFSM6AAAAABPFMLX7OVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMBYHE2TCOJSGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-16 16:54 UTC, mikhailov26 requested changes

2024-10-16 16:54 UTC, mikhailov26 commented on src/test/java/ru/kraiush/spring/BJS2_27254/repository/TeamMemberRepositoryTest.java
Так не пойдёт.  Насколько мне известно @Sql выполняется каждый раз перед вызовом метода, если я прав, то в данном случае это очень затратно. В качестве альтернативы могу предложить статический метод, который нам билдит нужные сущности, затем мы кладём их в базу, достаём и делаем необходимые ассерты. Писал об этом ранее

2024-10-18 14:48 UTC, kraiush commented
Вячеслав, консенсус безусловно необходим. Я прекрасно помню наш разговор, и тогда я согласился, что это может быть не лучшее решение. Но, поскольку, еще раз, нет установленных раз и навсегда правил в программировании – они постоянно меняются и настаивать, что только так и не иначе – неприемлимо! Да, и поэтому, я пробовал идти именно по вашему сценарию и пришел к выводу, что он не годиться, что подтвердили изыскания и советы с другими пользователями.      

   Впрочем, когда я все переведу на Docker, это уже совсем другая песня. Прошу понять!!

2024-10-20 15:56 UTC, mikhailov26 requested changes
Я не вижу реакции на свои замечания (некоторые)

2024-10-20 16:00 UTC, mikhailov26 commented
Правил нет, я согласен. Но есть мои требования, к которым, увы, нужно прислушиваться и их выполнять. Мы с вами не на рынке, чтобы торговаться. Я Вам говорю что каждый тест делать инсерт в таблицу, это очень ресурсозатратно и из-за этого не продуктивно. Используем аннотацию @BeforeAll, Java кодом создаём необходимые сущности и проводим тест нашей логики. В таком виде не приму!

2024-10-20 21:12 UTC, kraiush commented
То, что вы предлагаете противоречит теории - использовании @DataJpaTest,
где данные загружаются каждый раз для теста и
и после каждый раз выгружаются.  Если вы действительно программист, то
аот вам последние  туториалы на этот счет - прилагаютсяю
Так что ничего я переделывать больше не буду! .И какой смысл настаивать на
том что вы сказали видите ли род запись если это неправильно!
Так что советую как следует подумать! А мне нужна срочная работа - курсы
недолггие, а стоят огого!

On Sun, Oct 20, 2024 at 7:00 PM Viacheslav Mikhailov <
***@***.***> wrote:

> Правил нет, я согласен. Но есть мои требования, к которым, увы, нужно
> прислушиваться и их выполнять. Мы с вами не на рынке, чтобы торговаться. Я
> Вам говорю что каждый тест делать инсерт в таблицу, это очень
> ресурсозатратно и из-за этого не продуктивно. Используем аннотацию
> @BeforeAll, Java кодом создаём необходимые сущности и проводим тест нашей
> логики. В таком виде не приму!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/CorporationX/god_bless/pull/10834#issuecomment-2425069482>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEE7BGKSPFKPXSEVWHMTUMDZ4PHTHAVCNFSM6AAAAABPFMLX7OVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMRVGA3DSNBYGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-21 15:59 UTC, mikhailov26 requested changes
В очередной раз прошу провести рефакторинг без использования sql скриптов, что в main'е , что в тестах. Из новых замечаний, мне не ясен замысел пуша каких-то лекций в общий репозиторий проекта, убрать данную директорию. Для общения у нас есть дискорд, там можете поделиться материалами. Жду возможности выбрать с вами время для нашего 1:1 созвона. Мои требования такие же, но повторю: 1) избавиться от новой директории GUIDES, 2) провести рефакторинг main'a и тестов без использования .sql скриптов

2024-10-24 15:35 UTC, kraiush commented
Сделал тест репозитория без @Sql.
Но оставил старый тест для оценки другими - убедился, что он гораздо компактней.

2024-11-10 18:31 UTC, mikhailov26 approved these changes

2024-11-10 18:31 UTC, merged