BJS2-18367: Monitoring of ElectricalSubstations. V.03
CorporationX/god_bless pull request #10831
Opened 2024-09-25 12:33 UTC by kraiush

2024-09-25 12:33 UTC, kraiush commented
BJS2-18367: Monitoring of ElectricalSubstations. V.03

2024-09-26 16:21 UTC, mikhailov26 requested changes

2024-09-26 16:21 UTC, mikhailov26 commented on src/main/java/ru/kraiush/threads/BJS2_18367/MonitoringSystem.java
> +    private final ArrayList<ArrayList<Double>> sublist = new ArrayList<>();
Прочитать почему инициализацию лучше делать через конструктор, а не так

2024-09-26 16:21 UTC, mikhailov26 commented on src/main/java/ru/kraiush/threads/BJS2_18367/Substation.java
>      private List<SensorData> listSensorsData;
final, инициализация в конструкторе

2025-01-17 21:26 UTC, closed without merging