BJS2-31295
CorporationX/god_bless pull request #11013
Opened 2024-10-03 08:35 UTC by mad1xx1dam

2024-10-04 13:13 UTC, BobrAll requested changes
Код хороший, но нужно чуть подправить. За тесты лайк

2024-10-04 13:13 UTC, BobrAll commented on src/main/java/school/faang/BJS2_31295/Archer.java
> +        }
Круто, что предусмотрел кейс, когда здоровье меньше 0. Попробуй сделать через тернарный оператор, чтобы код выглядел лаконичнее

2024-10-04 13:13 UTC, BobrAll commented on src/main/java/school/faang/BJS2_31295/Warrior.java
> +        }
Тут так же как в Archer

2024-10-04 13:13 UTC, BobrAll commented on src/test/java/school/faang/BJS2_31295/ArcherTest.java
> +        //assert
#В идеале код должен читаться понятно без комментариев (подробно описано в книге "Чистый код" от Р. Мартина). В целом в твоем коде все понятно, поэтому можно избавиться от лишних комментариев. То же самое и про все остальные комментарии

2024-10-04 13:13 UTC, BobrAll commented on src/test/java/school/faang/BJS2_31295/ArcherTest.java
> +class ArcherTest {
Молодец, что сделал тесты (еще и осмысленные). По поводу их именования - видел такой же формат с нижними подчеркиваниями, но по большей части для java стандарт именования - camelCase, лучше подправить + попробуй сделать имена покороче. Безусловно, понятное длинное имя на 100% лучше короткого и непонятного, но тут можно просто чуть абстрактнее выразить идею теста в имени.

2024-10-04 13:13 UTC, BobrAll commented on src/main/java/school/faang/BJS2_31295/Main.java
> +                : "Победил лучник, осталось здоровья " + warrior.health);
В обоих случаях выводится здоровье warrior

2024-10-04 13:13 UTC, BobrAll commented on src/main/java/school/faang/BJS2_31295/Character.java
> +        }
Для таких коротки if'ов можно опускать фигурные скобки. В целом это не минус точно, но код будет короче и приятнее для глаз

2024-10-04 13:26 UTC, mad1xx1dam commented on src/main/java/school/faang/BJS2_31295/Archer.java
> +        }
А можно так написать? character.health -= Math.min(character.health, agility);
Это идея предложила. Или лучше нормально расписать через тернарный оператор?

2024-10-04 13:55 UTC, mad1xx1dam commented on src/main/java/school/faang/BJS2_31295/Character.java
> +        }
Вот здесь хотел бы тоже спросить: Влад про это говорил, что, наоборот, если даже только одна команда выполняется, то лучше в фигурные скобки помещать. Потом привел пример, что у себя в коде не увидел, что не было фигурных скобок, поставил еще одну команду, но она была вне блока if, что по итогу сломало логику.

У себя я опустил скобки, но так как мнение техлида и Влада отличаются, не совсем понимаю, как правильнее.

2024-10-04 21:52 UTC, BobrAll commented
> [#11013 (comment)](https://github.com/CorporationX/god_bless/pull/11013#discussion_r1787717795) [#11013 (comment)](https://github.com/CorporationX/god_bless/pull/11013#discussion_r1787758889)
> 
> На всякий случай, а то пока не знаю, может ли затеряться коммент в замечании, если я отметил его resolved

Лучше не отмечать как resolved, это больше для проверяющего)

2024-10-04 21:54 UTC, BobrAll commented on src/main/java/school/faang/BJS2_31295/Archer.java
> +        }
Можно и так - тут уже на твое усмотрение)

2024-10-04 22:02 UTC, BobrAll commented on src/test/java/school/faang/BJS2_31295/WarriorTest.java
> +        assertEquals("Invalid name.", argumentException.getMessage());
Кажется, что требования к имени одинаковы для всех наследниках класса Character. Может быть этот факт поможет убрать дублирование?

2024-10-04 22:07 UTC, BobrAll commented on src/main/java/school/faang/BJS2_31295/Character.java
> +        validateIntelligence(intelligence);
Обычно валидация проходит в сеттерах (по факту для этого они и существуют). Если вдруг добавятся новые требования и нужно будет в другом месте (кроме конструктора) устанавливать значения, то везде нужно будет также и валидацию вызывать. А так просто вызвал сеттер - и голова не болит, там либо установится значение, либо вылетит exception

2024-10-05 11:44 UTC, mad1xx1dam commented
ОООчень сомневаюсь, что это так делается, был еще вариант создать абстрактный класс для тестов

2024-10-06 16:36 UTC, BobrAll commented
> ОООчень сомневаюсь, что это так делается, был еще вариант создать абстрактный класс для тестов

Чутка избыточно вышло (не по твоей вине, а из-за того по факту конструктор тестировался, с методами было бы проще). Ты молодец, что смог реализовать)

2024-10-06 16:36 UTC, merged