Вторая задча
CorporationX/god_bless pull request #11027
Opened 2024-10-03 09:51 UTC by ilya-ishanov

Не знал что можно передавать методы в конструктор. До того как узнал долго думал как можно проверить валидацию для хэш сет если они final static.

2024-10-03 18:24 UTC, Mixalight commented on src/main/java/school/faang/userregistration/Users.java
> +    private String name;
Эта задача - продолжение предыдущей, то есть в классе должны быть все 4 поля(имя, возраст, место, адрес) и на всех должна быть валидация, как в условии

2024-10-03 18:25 UTC, Mixalight commented on src/main/java/school/faang/userregistration/Users.java
> +    private final Set<String> VALID_JOBS = Set.of("Google", "Uber", "Amazon");
Оба списка должны быть статическими константами по условию

2024-10-03 18:27 UTC, Mixalight commented on src/main/java/school/faang/userregistration/Users.java
> +    private void setValidation() {
У тебя здесь небольшая путаница вышла. Есть два константных множества с компаниями и местами работы
Они статические и общие для всех объектов класса
А дальше у класса должны быть поля работа и её адрес(см первый комментарий)
И вот их ты должен валидировать, сравнивая с константными множества

2024-10-03 18:30 UTC, Mixalight commented on src/main/java/school/faang/userregistration/Users.java
> +        if (age < 18) {
Это уже по желанию, но классно, когда человек смотрит твой код и легко понимает все такие моменты. Я читал условие, но без этого - я бы мог не понять, откуда взялось число 18
Вариант решения - сделать константу с говорящим именем(MIN_AGE например) и присвоить ей значение
А дальше использовать её
Кроме читабельности, ты получишь возможность легкого редактирования. Например у тебя в нескольких местах есть проверки, связанные с возрастом и ты поставил везде число. И внезапно тебе нужно его изменить. Придётся в каждом месте менять, велика вероятность ошибки и неудобно. А так тебе нужно будет изменить лишь константу

2024-10-03 18:34 UTC, Mixalight commented on src/main/java/school/faang/userregistration/Main.java
> +    public static void main(String[] args) {
Было бы классно написать сюда минимальный тест, чтобы не оставлять пустым
В дальнейшем у вас будут полноценные тесты в отдельных классах, а пока можно просто пару объектов создать и проверить, что код корректно отработал локальным запуском

2024-10-03 19:47 UTC, ilya-ishanov commented on src/main/java/school/faang/userregistration/Users.java
> +    private void setValidation() {
я совсем не понял

2024-10-03 20:02 UTC, Mixalight commented on src/main/java/school/faang/userregistration/Users.java
> +    private void setValidation() {
Статические поля - это поля, которые одни на весь класс. То есть у любого созданного тобой объекта будет такое значение. Пример для понимания - тебе нужно узнать, сколько в коде создали объектов твоего класса. Ты заводишь статическую переменную счётчик(простой int) и каждый раз, создавая объект, делаешь +1. Посколько переменная общая для всех классов - задача будет выполнено

Теперь к нашей задаче. По условию от тебя хотят, чтобы у User было 4 поля(это из прошлой задачи)
Имя, возраст, место работы и адрес
Также должно быть ещё 2 поля - это две статические константы(public static final)
В константах будет несколько работ и адресов, которые у тебя прописаны в условии

Дальше твоя задача будет в том, что нужно проверять, есть ли указанное у объекта место работы и адрес в этих константных множествах и делать валидацию

Если есть какой-то вопрос ещё или после прочтения - смело задавай)

2024-10-03 20:30 UTC, Mixalight commented on src/main/java/school/faang/userregistration/Users.java
> +    private void setValidation() {
От задачи зависит
В твоём случае они используются только для валидации внутри класса, а значит могут быть приватными
Но иногда бывает, например, что у класса может быть ряд констант и некоторые его публичные методы принимают эти константы как аргументы. Тогда конечно публично нужно делать

2024-10-03 21:04 UTC, ilya-ishanov commented on src/main/java/school/faang/userregistration/Users.java
> +    private void setValidation() {
сори я прочитал коменты уже после того как исправил все

2024-10-03 21:44 UTC, Mixalight requested changes

2024-10-03 21:44 UTC, Mixalight commented on src/main/java/school/faang/userregistration/Users.java
> +    private final Integer MIN_AGE = 18;
Как правило - константы статические

2024-10-03 21:44 UTC, Mixalight commented on src/main/java/school/faang/userregistration/Users.java
> +        for (String element : VALID_JOBS) {
Множество - структура данных по многом похожая на мапу, только в чуть более просто виде. И от мапы оно сохранило свойство получить элемент за константное время. Для этого есть метод contains(obj), который возвращает  true или false в зависимости от наличия элемента во множестве

2024-10-03 21:44 UTC, Mixalight commented on src/main/java/school/faang/userregistration/Users.java
> +        for (String element : VALID_ADDRESSES) {
Комментарий выше про множество актуален и тут

2024-10-03 22:16 UTC, ilya-ishanov commented on src/main/java/school/faang/userregistration/Users.java
> +        for (String element : VALID_JOBS) {
Я это понимаю, тут оно возвращает true -  if (element.contains(workPlace)) 
Вы имеете ввиду код можно как то сократить?
Не понимаю (

2024-10-03 22:24 UTC, Mixalight requested changes

2024-10-03 22:24 UTC, Mixalight commented on src/main/java/school/faang/userregistration/Users.java
> +        for (String element : VALID_JOBS) {
Смотри
У тебя VALID_JOBS - множество работ
Если ты сделаешь 
```
VALID_JOBS.contains(obj)
```
То ты проверишь наличие obj в этом множестве
То есть за одно действие ты можешь проверить наличие работы юзера в множестве, без использования цикла
А сейчас ты просто сравниваешь каждый элемент с работой юзера и смотришь, ок или нет
Это вполне рабочий метод, просто не оптимальный
Ещё небольшой комментарий
В твоём текущем коде ты используешь contains применимо к строке. А это значит что ты ищешь аругмент в строке как подстроку. Это работает в текущей задаче, но вообще строки проверяются так
```
str1.equals(str2)
```

2024-10-03 22:32 UTC, ilya-ishanov commented on src/main/java/school/faang/userregistration/Users.java
> +        for (String element : VALID_JOBS) {
как научиться мыслить так же?

2024-10-03 22:45 UTC, ilya-ishanov commented on src/main/java/school/faang/userregistration/Users.java
> +        for (String element : VALID_JOBS) {
грамотней будет сделать так?

 private String workPlaceValidation(String workPlace) {
        boolean logicValue = VALID_JOBS.contains(workPlace);
        if (!logicValue) {
            throw new IllegalArgumentException("Этого элемента workPlace нет в сэте");
        }
        return workPlace;
    }

2024-10-03 22:48 UTC, Mixalight commented on src/main/java/school/faang/userregistration/Users.java
> +        for (String element : VALID_JOBS) {
Да, всё верно
Пару лайфхаков
1) Хочешь удобно выдялеть код в комментариях - напиши перед ним и после три символа ` 
Это не кавычка, а символ на клавише с ~ и если у тебя не мак, то там ещё буква ё
2) Код верный, но есть одна хорошая практика
Если ты используешь локальную переменную в коде 1 раз - нет смысла её создавать
Ты можешь сразу сделать
```
if (!VALID_JOBS.contains(workPlace)) { }
```

2024-10-03 22:49 UTC, Mixalight commented on src/main/java/school/faang/userregistration/Users.java
> +        for (String element : VALID_JOBS) {
А отвечаю на вопрос про мыслить - решать такие задачи)
Без шуток, это приходит с опытом. Постепенно, с каждым новом pr и правками к нему будешь лучше понимать и лучше писать код

2024-10-03 22:51 UTC, ilya-ishanov commented on src/main/java/school/faang/userregistration/Users.java
> +        for (String element : VALID_JOBS) {
блин ) да как научиться так же мыслить )

2024-10-03 22:54 UTC, ilya-ishanov commented on src/main/java/school/faang/userregistration/Users.java
> +        for (String element : VALID_JOBS) {
ну вот последний момент я мог бы сам догадаться но я же не догадался

2024-10-03 22:55 UTC, ilya-ishanov commented on src/main/java/school/faang/userregistration/Users.java
> +        for (String element : VALID_JOBS) {
да и в целом я задание то не понял до конца нормально

2024-10-03 22:56 UTC, Mixalight commented on src/main/java/school/faang/userregistration/Users.java
> +        for (String element : VALID_JOBS) {
Зато теперь ты запомнил и поправил все issue и в следующий раз сможешь писать код с учётом этого
Постепенно будешь писать код лучше

2024-10-03 22:56 UTC, Mixalight commented on src/main/java/school/faang/userregistration/Users.java
> +        for (String element : VALID_JOBS) {
> да и в целом я задание то не понял до конца нормально

Распиши подробно пожалуйста, чтобы было непонятно, чтобы мы учли это на будущее

2024-10-03 22:57 UTC, ilya-ishanov commented on src/main/java/school/faang/userregistration/Users.java
> +        for (String element : VALID_JOBS) {
я надеюсь на это ) но не уверен что буду так вдумчиво относиться
Спасибо большое за урок это было очень интересно и позновательно

2024-10-03 22:59 UTC, Mixalight approved these changes

2024-10-03 22:59 UTC, merged

2024-10-04 06:42 UTC, ilya-ishanov commented on src/main/java/school/faang/userregistration/Users.java
> +        for (String element : VALID_JOBS) {
мне в джире в done перенести задачу?