Java HashMap: Считаем прогулы
CorporationX/god_bless pull request #11035
Opened 2024-10-03 10:35 UTC by allitov

2024-10-04 14:35 UTC, BobrAll requested changes
Небольшие правки, а так выглядит хорошо

2024-10-04 14:35 UTC, BobrAll commented on src/main/java/school/faang/truancy/Main.java
> +    public static void addStudent(Student student) {
Предлагаю сначала проверить, что такого студента в списке еще нет

2024-10-04 14:35 UTC, BobrAll commented on src/main/java/school/faang/truancy/Main.java
> +    }
Хорошо, что знаешь про инициализаторы. Но они больше для случаев, когда у нас несколько конструкторов и перед каждым из них мы хотим выполнять одинаковую логику во избежание дублирования. Я бы перенес это в main. Почему? Если можно сделать проще - нужно делать проще (можно почитать про KISS). Но это не вообще критично

2024-10-04 14:35 UTC, BobrAll commented on src/main/java/school/faang/truancy/Main.java
> +    }
Хороший вариант. Можно попробовать сократить эти 10+ строчек, используя в качестве ключа строку "факультет + год". Тоже относится к KISS и в целом можно так и оставить

2024-10-04 14:35 UTC, BobrAll commented on src/main/java/school/faang/truancy/Main.java
> +    private static final List<Student> STUDENTS = new ArrayList<>();
Нужен ли нам тут final?

2024-10-04 15:39 UTC, allitov commented on src/main/java/school/faang/truancy/Main.java
> +    public static void addStudent(Student student) {
Реализовал проверку через Set<Student>, чтобы быстро находить уже добавленных студентов

2024-10-04 15:40 UTC, allitov commented on src/main/java/school/faang/truancy/Main.java
> +    }
Про применение инициализаторов интересно, спасибо. В данном случае действительно без него гораздо лучше

2024-10-04 15:40 UTC, allitov commented on src/main/java/school/faang/truancy/Main.java
> +    }
Да, думал про такой вариант, но остановился на реализации через record, чтобы была возможность быстро обратиться к полям без парсинга строки

2024-10-04 15:41 UTC, allitov commented on src/main/java/school/faang/truancy/Main.java
> +    private static final List<Student> STUDENTS = new ArrayList<>();
Тут он и правда не сильно нужен, но поле не меняет своего значения, из-за чего IDE выделяло его как warning. Сделал final в угоду IDE :)

2024-10-04 21:32 UTC, BobrAll requested changes
Чуть-чуть правок, хотя мысли интересные

2024-10-04 21:32 UTC, BobrAll commented on src/main/java/school/faang/truancy/Main.java
> +    public static void addStudent(Student student) {
Идея с сетом очень хорошая (учитывая что ты её сделал в целях оптимизации). Но в таком случае расходуется в ~x2 раза больше памяти, что не есть гуд + дальше в коде приходится лепить костыли (например, удаление из обоих списков), что само по себе не оч, а если где-то об этом забыть, то еще и будут проблемы. 
В целом STUDENTS можно было бы сетом сделать и это очень хорошо решило бы проблему, но по заданию нужен список. Поэтому предлагаю просто сделать проверку на наличие элемента в списке и если его еще нет - добавлять и в обратном случае - игнорировать

2024-10-04 21:32 UTC, BobrAll commented on src/main/java/school/faang/truancy/Main.java
> +    private static final List<Student> STUDENTS = new ArrayList<>();
Ох уж эти IDE）

2024-10-05 10:44 UTC, allitov commented on src/main/java/school/faang/truancy/Main.java
> +    public static void addStudent(Student student) {
Сет убрал, сделал проверку наличия в списке

2024-10-06 07:22 UTC, BobrAll reviewed
Решение выглядит аккуратно и без излишеств, засчитываю

2024-10-06 07:22 UTC, BobrAll commented on src/main/java/school/faang/truancy/Main.java
> +    private static final List<Student> STUDENTS = new ArrayList<>();
Теперь, когда уже не final, переменная должна быть в lower case :)
Но это скорее на будущее, а так задачу засчитываю. Теперь все выглядит гуд

2024-10-06 07:22 UTC, merged