считаем прогулы
CorporationX/god_bless pull request #11047
Opened 2024-10-03 12:25 UTC by m1rroxxx

2024-10-05 16:52 UTC, MiraGlaceon requested changes

2024-10-05 16:52 UTC, MiraGlaceon commented on src/main/java/school/faang/countingAbsenteeism/FacultyInfo.java
> +public class FacultyInfo {
Дай название получше. Это не совсем информация об факультете. У тебя идет паза значений факультет/курс

2024-10-05 16:52 UTC, MiraGlaceon commented on src/main/java/school/faang/countingAbsenteeism/Institute.java
> +    LinkedList<Student> students = new LinkedList<>();
Почему использование связного списка? У тебя в задаче много операций по поиску и удалению. Использовать обычный список будет эффективнее, так как у него обращение к элементу по индексу (время константное O(1))

2024-10-05 16:52 UTC, MiraGlaceon commented on src/main/java/school/faang/countingAbsenteeism/Institute.java
> +            if (map.containsKey(new FacultyInfo(student.getFaculty(), student.getYear()))) {
1) Тебе не нужно проверять, что мапа содержит ключ. Сразу применяй метод get. Если значения в мапе не будет, то вернется значение null. 

2) В целом непонятно зачем ты вызываешь метод get и не используешь возвращаемое значение.

3) Тебе нужно разобраться что происходит в мапе, если мы пытаемся добавить значение с ключом, который уже содержится в мапе. Если поразмышлять, то мы либо запишем одинаковые ключи, либо новое значение затрет старое, что ты думаешь по этому поводу?

2024-10-05 16:52 UTC, MiraGlaceon commented on src/main/java/school/faang/countingAbsenteeism/Institute.java
> +    private Map<FacultyInfo, List<Student>> listToMap(List<Student> students) {
Слишком абстрактное имя метода. По этому названию я думаю, что любой список переданный в этот метод можно превратить в мапу

2024-10-05 16:52 UTC, MiraGlaceon commented on src/main/java/school/faang/countingAbsenteeism/Institute.java
> +    public String showStudentsByFacultyAndYear(String faculty, int year) {
В постановке задачи не сказано распечатывать студентов. Тебе нужно реализовать поиск по входным параметрам. Например, у тебя есть мапа с ключом "Факультет/курс" и значение "Список студентов". Тебе нужно из этой мапы получить список студентов у которых факультет и курс такие, как передали через параметры метода. Прочитай еще раз требования задачи

2024-10-05 16:52 UTC, MiraGlaceon commented on src/main/java/school/faang/countingAbsenteeism/Institute.java
> +        students.remove(new Student(name, faculty, year));
Здесь ты создаешь новый объект, чтобы удалить существующий похожий из списка. А почему это работает? В целом если бы я создал новый объект, он же ничем не схож с существующим, потому что у объектов разные ссылки. Подсказка обрати на методы hashCode, equals и аннотацию @ Data

2024-10-05 17:01 UTC, MiraGlaceon commented
По поводу вывода списка студентов поторопился. Там действительно нужно выводить список студентов с группировкой

2024-10-05 21:36 UTC, m1rroxxx commented on src/main/java/school/faang/countingAbsenteeism/Institute.java
> +        students.remove(new Student(name, faculty, year));
аннотация @Data содержит в себе несколько аннотаций, среди них @EqualsAndHashCode, эта аннотация добавляет методы hashCode и equals, они обязательны, например для использования объекта в HashMap, так как под капотом Map юзает оба этих метода, метод remove сравнивает объекты методом equals
<img width="674" alt="image" src="https://github.com/user-attachments/assets/025f68d1-6f2e-40d2-ada1-780e987e8b08">

2024-10-05 21:50 UTC, m1rroxxx commented on src/main/java/school/faang/countingAbsenteeism/Institute.java
> +            if (map.containsKey(new FacultyInfo(student.getFaculty(), student.getYear()))) {
спасибо за комент) если в map добавить значение с уже существующим ключём значение просто перезапишется, это логично так как в Map не может быть одинаковых ключей

2024-10-05 22:03 UTC, m1rroxxx commented on src/main/java/school/faang/countingAbsenteeism/Institute.java
> +            if (map.containsKey(new FacultyInfo(student.getFaculty(), student.getYear()))) {
я эту задачу делал ещё на онбординге, щас я уже немного научился юзать computeIfAbsent, думаю тут нормально вписывается

2024-10-06 20:31 UTC, MiraGlaceon approved these changes

2024-10-06 20:31 UTC, MiraGlaceon commented on src/main/java/school/faang/countingAbsenteeism/Institute.java
> +public class Institute {
Совет: давай классам имена, которые отражают то, что он делает. Ты назвал класс существительным, как будто он отражает объект "Универ"

2025-01-17 21:26 UTC, closed without merging