added Student, University
CorporationX/god_bless pull request #11056
Opened 2024-10-03 13:18 UTC by abdddev

2024-10-04 21:20 UTC, BobrAll requested changes
В целом все хорошо, небольшие правки. Классно, что в этой задаче уже правильно именуешь тесты.

2024-10-04 21:20 UTC, BobrAll commented on src/main/java/school/faang/students/Student.java
> +    public static Map<FacultyYearKey, List<Student>> groupStudentsByFacultyAndYear(List<Student> students) {
Этот метод оперирует набором студентов, а не конкретным студентом. Обычно подобные утилитарные функции выносятся в отдельный класс. Например, есть класс List, он может добавлять/удалять и т.д. какой-нибудь конкретный элемент. Но функции для работы с целой коллекцией уже вынесены в отдельный класс - Collections. Поэтому для сортировки того же list'a используется Collections.sort(list)
Стандарт именования для такого утилитарного класса - StudentService. В контексте данной задачи можно вообще в University поместить этот метод, тоже будет логично.

2024-10-04 21:20 UTC, BobrAll commented on src/main/java/school/faang/students/University.java
> +    public void add(Student student) {
Предлагаю сначала проверить, что такого студента в списке еще нет

2024-10-04 21:20 UTC, BobrAll commented on src/test/java/school/faang/students/UniversityTest.java
> +    }
В этом тесте ничего не проверяется

2024-10-04 21:20 UTC, BobrAll commented on src/test/java/school/faang/students/UniversityTest.java
> +        List<Student> allByFacultyAndYear = university.findAllByFacultyAndYear("Faculty 2", 2022);
У тебя в 34 строке хорошее название для списка студентов, я бы тут использовал такое же

2024-10-04 21:20 UTC, BobrAll commented on src/test/java/school/faang/students/UniversityTest.java
> +    void addAndFindByFacultyAndYearTest() {
Тут хороший пример, как можно использовать первый принцип SOLID - single responsibility. Сейчас тест выполняет 2 вещи - проверяет метод добавления студента и проверяет метод поиска студента. Можно разбить на 2 отдельных теста. Потому что если тест начнет падать, не будет понятно в чем дело - ошибка в добавлении или ошибка в поиске

2024-10-04 21:20 UTC, BobrAll commented on src/main/java/school/faang/students/FacultyYearKey.java
> +public class FacultyYearKey {
Нет необходимости создавать отдельный класс для хранения можно использовать, например Pair или просто в качестве ключа строку "факультет + год". Но в целом это не критично

2024-10-05 00:32 UTC, abdddev commented on src/test/java/school/faang/students/UniversityTest.java
> +    }
Согласен, просто вывожу в консоль список как в задании:
вывод списка всех студентов сгруппированных по факультетам и курсам

2024-10-05 00:34 UTC, abdddev commented on src/test/java/school/faang/students/UniversityTest.java
> +        List<Student> allByFacultyAndYear = university.findAllByFacultyAndYear("Faculty 2", 2022);
Ага через .var, само такое дало) поправил)

2024-10-05 00:37 UTC, abdddev commented on src/test/java/school/faang/students/UniversityTest.java
> +    void addAndFindByFacultyAndYearTest() {
переделал, но кажется как будто дублируют одно и то же

2024-10-05 00:44 UTC, abdddev commented on src/main/java/school/faang/students/FacultyYearKey.java
> +public class FacultyYearKey {
Да, поленился сразу зависимость закинуть, поправил))

2024-10-06 17:15 UTC, BobrAll reviewed
В целом все гуд, засчитываю

2024-10-06 17:15 UTC, BobrAll commented on src/test/java/school/faang/students/UniversityTest.java
> +    }
Вообще таких тестов не должно быть, тест на то и тест, чтобы тестировать)
При этом глазами-то не всегда заметишь, все должно быть программно.

2024-10-06 17:17 UTC, BobrAll commented on src/test/java/school/faang/students/UniversityTest.java
> +    void addAndFindByFacultyAndYearTest() {
В целом в коде дублирование плохо, но в тестах - не критично

2024-10-06 17:17 UTC, merged