Задача Абстракция, абстракция BJS2-31322
CorporationX/god_bless pull request #11083
Opened 2024-10-03 15:20 UTC by YaKokin

1. Создал абстрактный класс Character
2. Сделал два конструктора
3. Создал классы-наследники от Character: Warrior и Archer
4. Добавил абстрактный метод attack
5. Переопределил метод attack в Warrior и Archer

P.S. доступ к полям супер класса реализовал через геттеры и сеттеры, вместо protected, чтобы не нарушать инкапсуляцию

2024-10-03 20:46 UTC, mysosnovskaya requested changes
Хорошая работа, ещё и с юмором 👍 Молодец! И ещё мне понравилось, как ты продумал работу с полями абстрактного класса: геттеры, сеттеры, модификаторы.
ПР сейчас смержить не могу, нужно разрешить конфликт, поэтому отправляю на доработку. После этого смержу

2024-10-03 20:46 UTC, mysosnovskaya commented on src/main/java/school/faang/abstraction/Archer.java
> +        if (target.equals(this)) {
Круто, что ты предусмотрел такую проверку 👍

2024-10-03 20:46 UTC, mysosnovskaya commented on src/test/java/ru/kraiush/BJS2_18616/abstraction/ArcherTest.java
> +    @Test
Лучше оставить пустую строчку перед аннотацией

2024-10-03 20:46 UTC, mysosnovskaya commented on src/test/java/ru/kraiush/BJS2_18616/abstraction/WarriorTest.java
> +        school.faang.abstraction.Character target = new Warrior("Груша для битья");
Пакет должен быть в импорте

2024-10-03 22:23 UTC, YaKokin commented
Привет, комментарии учел, конфликты поправил. Изменения запушены. @mysosnovskaya

2024-10-04 18:25 UTC, mysosnovskaya approved these changes

2024-10-04 18:26 UTC, merged