Java HashMap: Поисковый мини-движок Google
CorporationX/god_bless pull request #11089
Opened 2024-10-03 15:36 UTC by m1rroxxx

2024-10-05 17:26 UTC, MiraGlaceon requested changes

2024-10-05 17:26 UTC, MiraGlaceon commented on src/main/java/school/faang/searchEngine/nodes/MyLinkedList.java
> +public class MyLinkedList {
Реализация связного списка здесь не нужна. Используй обычный список. Он удобнее и эффективнее в конкретной задаче

2024-10-05 17:26 UTC, MiraGlaceon commented on src/main/java/school/faang/searchEngine/WebPageRepository.java
> +public class WebPageRepository {
Переименуй в сервис, репозиторий обычно используется для общения с базой данных

2024-10-05 17:26 UTC, MiraGlaceon commented on src/main/java/school/faang/searchEngine/WebPageRepository.java
> +    String[] words = page.getContent().split(" ");
А если у тебя слова будут содержать дефисы, запятые, точки или другие символы?

2024-10-05 22:40 UTC, m1rroxxx commented on src/main/java/school/faang/searchEngine/nodes/MyLinkedList.java
> +public class MyLinkedList {
понял, думал удаление в связанном списке круче будет) ещё в видосе из подсказки это говорилось)

2024-10-06 22:15 UTC, MiraGlaceon commented on src/main/java/school/faang/searchEngine/nodes/MyLinkedList.java
> +public class MyLinkedList {
Тут надо всегда смотреть какие проблемы решает задача. Например, если тебе нужно обрабатывать данные в том порядке, в котором они пришли, то связный список подойдет лучше. Если тебе нужно хранилище данных и в любой момент ты хочешь достать данные в произвольном порядке, то лучше обычный список, там обращение по индексу эффективно. 
Вообще, тут от себя скажу, что есть крутая книжка, она вообще легкая как чтиво, называется "Грокаем алгоритмы". Попробуй обязательно, как время будет

2024-10-06 22:29 UTC, MiraGlaceon commented on src/main/java/school/faang/searchEngine/WebPageService.java
> +@Getter
Вообще, то что ты сделал, вполне нормально, но я такого в практике никогда не видел. Обычно геттеры и сеттеры по умолчанию используют в классах-сущностях, dto или pojo классах. 
В классах, которые реализовывают какую-то бизнес-логику не требуется возвращать значения. В целом ты разберешься с этим больше, когда будем работать с сервисами спринга. Сейчас допускаю такое, но прими к сведению.
В твоем случае, мапу и список можно создать извне, например, в классе Main, а в методы передавать через параметры. Не забывай как будут работать ссылочные типы, переданные в метод

2024-10-06 22:30 UTC, MiraGlaceon approved these changes

2024-10-06 23:07 UTC, m1rroxxx commented on src/main/java/school/faang/searchEngine/WebPageService.java
> +@Getter
Понял, я изначально так делал, возможно в какой то задаче сделано так), я по этому поводу спрашивал в help и там вроде сказали делай как хочешь и так и так норм)) а геттер забыл убрать, я тестил что то незначительное а убрать забыл

2025-01-17 21:26 UTC, closed without merging