Alexeyzimin5726 bjs2 31318
CorporationX/god_bless pull request #11113
Opened 2024-10-03 17:50 UTC by Alexey-Zimin

Согласно замечаний из задания некоторые поля класса Character сделал protected. Можно было сделать доступ через геттеры  и сеттеры

2024-10-03 21:36 UTC, jibulani requested changes
В целом все хорошо, молодец!
Есть немного небольших замечаний, думаю, легко с ними справишься :)

2024-10-03 21:36 UTC, jibulani commented on src/main/java/school/faang/abstractclasses/Character.java
> +    protected int health;
я бы предпочел сразу тут проинициализировать переменную значением HEALTH_DEFAULT 
если в будущем появится еще один конструктор, из которого не получится вызвать тот, в котором сейчас проставляется health, то в нем можно забыть проинициализировать этот параметр дефолтным значением, а если и не забыть, то придется писать лишнюю строчку кода
а когда инициализируется при объявлении, то явно понятно, что это значение по умолчанию

2024-10-03 21:36 UTC, jibulani commented on src/main/java/school/faang/abstractclasses/Character.java
> +    public String toString() {
в данном проекте подключен lombok, который позволяет не писать такие конструкции, а заменить их аннотацией `@ToString`
ну и там еще много других полезных аннотаций, позволяющих сэкономить время, рекомендую почитать про него и применить :)

2024-10-03 21:36 UTC, jibulani commented on src/main/java/school/faang/abstractclasses/Archer.java
> +package school.faang.abstractclasses;
получается, в пакете abstractclasses лежат и абстрактные, и не абстрактные классы, не самый удачный нейминг, обычно подобные классы кладут в пакет models

2024-10-03 21:36 UTC, jibulani commented on src/main/java/school/faang/Main.java
> +        System.out.println(archer);
молодец, что проверил работу классов!
если есть время и желание, можешь пойти дальше и написать тест с использованием JUnit, проверяющий правильность работы кода

2024-10-03 21:36 UTC, jibulani commented on src/main/java/school/faang/abstractclasses/Character.java
> +    private int intelligence;
некоторые из переменных потребовалось использовать в наследниках и ты дал им модификатор доступа protected - это правильно
для единообразия можно и остальным параметрам дать этот же модификатор доступа, к тому же возможно, что в будущем понадобиться работать и с ними в наследниках

2024-10-04 00:39 UTC, Alexey-Zimin commented on src/main/java/school/faang/Main.java
> +        System.out.println(archer);
желание есть, со временем не очень... дальше буду разбирться с JUnit

2024-10-04 00:40 UTC, Alexey-Zimin commented on src/main/java/school/faang/abstractclasses/Archer.java
> +package school.faang.abstractclasses;
название неудачное выбрал. хотел назвать по наименованию работы, чтобы все классы одном пакете лежали

2024-10-04 00:42 UTC, Alexey-Zimin commented on src/main/java/school/faang/abstractclasses/Character.java
> +    public String toString() {
я уже использовал ломбок, мне здесь нужен был только один метод toString(), решил сделать так

2024-10-04 00:48 UTC, Alexey-Zimin commented on src/main/java/school/faang/abstractclasses/Archer.java
> +package school.faang.abstractclasses;
переименовал пает на abstractions

2024-10-04 00:48 UTC, Alexey-Zimin commented on src/main/java/school/faang/Main.java
> +        System.out.println(archer);
спасибо за совет!

2024-10-04 09:16 UTC, jibulani approved these changes
Все хорошо, молодец!

2024-10-05 15:55 UTC, merged