BJS2-32424 count absent
CorporationX/god_bless pull request #11127
Opened 2024-10-03 19:02 UTC by VovaBuzivskyi

2024-10-04 15:10 UTC, BobrAll commented on src/main/java/school/faang/absenteeism_BJS2_32424/Main.java
> +            new Student("Petr Volkov", "Physics", "3")
У тебя есть специальный метод для добавления студентов, лучше использовать его. Почему? В нем может как-раз быть проверка, что такой студент уже существует и мы не добавим его еще раз по ошибке. Это заодно подсказка, что нужно поменять в методе добавления студентов :)

2024-10-04 15:13 UTC, BobrAll commented on src/main/java/school/faang/absenteeism_BJS2_32424/Main.java
> +        System.out.printf("Student %s was successfully added \n", student.getName());
Если мы говорим про идеальную функцию, то она должна делать ровно то, что указано в ее названии. Функция добавления - добавляет, функция вывода информации - выводит информацию. По факту так можно делать в целях логирования, но System.out.println() - это не логирование :) Поэтому лучше просто убрать эту строку вывода

2024-10-04 15:16 UTC, BobrAll commented on src/main/java/school/faang/absenteeism_BJS2_32424/Main.java
> +        printDivider();
В целом идея с printDivider() хороша тем, что ты таким образом избавился от дублирования. Но если идейно говорить про эту функцию - она не несет полезной нагрузки, но при этом добавляет много лишних строк кода (6 строк вызова и 3 строки определения функции)

2024-10-04 15:17 UTC, BobrAll commented on src/main/java/school/faang/absenteeism_BJS2_32424/Main.java
> +            sortedStudents.computeIfAbsent(faultyAndCourse, k -> new ArrayList<>()).add(student);
Круто!

2024-10-04 15:20 UTC, BobrAll commented on src/main/java/school/faang/absenteeism_BJS2_32424/Main.java
> +            System.out.println(entryStudent.getValue());
Было бы неплохо выводить при этом, к какому факультету/году относится список

2024-10-04 15:22 UTC, BobrAll commented on src/main/java/school/faang/absenteeism_BJS2_32424/Main.java
> +        Map<String, List<Student>> allSortedStudents = sortStudentByFacultyAndCourse(allStudents);
Студенты сортированы или все-таки сгруппированы?

2024-10-04 15:31 UTC, BobrAll commented on src/main/java/school/faang/absenteeism_BJS2_32424/Main.java
> +    public static void printAllGroupedStudentsByFacultyAndCourse() {
Станет ли хуже, если мы сократим имя метода до printGroupedStudents()?

2024-10-04 15:33 UTC, BobrAll commented on src/main/java/school/faang/absenteeism_BJS2_32424/Main.java
> +            String facultiesAndCoursesFromList = student.getFaculty() + student.getYear();
Может быть получится сократить имя facultiesAndCoursesFromList? Безусловно, длинное и понятное имя лучше, чем короткое и непонятное. Но тут есть что сократить. Небольшая подсказка - можно оттолкнуться от того, какую роль играет переменная facultiesAndCoursesFromList

2024-10-04 15:34 UTC, BobrAll commented on src/main/java/school/faang/absenteeism_BJS2_32424/Main.java
> +    public static Map<String, List<Student>> sortStudentByFacultyAndCourse(List<Student> students) {
Сортировка или группировка? :)
При этом в названии неплохо было бы указать, что мы работаем со студентами, а не со студентом

2024-10-04 18:40 UTC, VovaBuzivskyi commented on src/main/java/school/faang/absenteeism_BJS2_32424/Main.java
> +        Map<String, List<Student>> allSortedStudents = sortStudentByFacultyAndCourse(allStudents);
Думаю что все-таки сгруппированы :)

2024-10-04 18:41 UTC, VovaBuzivskyi commented on src/main/java/school/faang/absenteeism_BJS2_32424/Main.java
> +    public static void printAllGroupedStudentsByFacultyAndCourse() {
Согласен это длинное название в этом случае излишне.

2024-10-04 18:46 UTC, VovaBuzivskyi commented on src/main/java/school/faang/absenteeism_BJS2_32424/Main.java
> +            String facultiesAndCoursesFromList = student.getFaculty() + student.getYear();
Не знаю, правильно ли я понял подсказку )

2024-10-04 19:21 UTC, VovaBuzivskyi commented on src/main/java/school/faang/absenteeism_BJS2_32424/Main.java
> +        printDivider();
Я просто добавлял эти строки для того чтобы в консоли было лучше видно. Но в принципе без них все тоже работает отлично.

2024-10-04 21:48 UTC, BobrAll requested changes
Близимся к завершению
P.S. отметка resolved больше для проверяющего)

2024-10-04 21:48 UTC, BobrAll commented on src/main/java/school/faang/absenteeism_BJS2_32424/Main.java
> +    public static void addNewStudent(Student student) {
Небольшая викторина: какое слово можно убрать в названии метода и он при этом не поменяет своего смысла? :)

2024-10-04 21:48 UTC, BobrAll commented on src/main/java/school/faang/absenteeism_BJS2_32424/Main.java
> +    public static List<Student> findAllStudentsByFacultyAndCourse(String faculty, String course) {
В целом эту функцию можно вообще удалить. Если нужно найти студентов по факультету и курсу - у нас для этого как раз и есть HashMap, получаемый из функции groupStudentsByFacultyAndCourse()

2024-10-05 08:23 UTC, VovaBuzivskyi commented on src/main/java/school/faang/absenteeism_BJS2_32424/Main.java
> +    public static void addNewStudent(Student student) {
понял)

2024-10-06 07:26 UTC, BobrAll commented on src/main/java/school/faang/absenteeism_BJS2_32424/Main.java
> +    private static final List<Student> allStudents = new ArrayList<>();
Обязательно ли тут final? 
В данном случае он только сигнализирует о том, что ссылка на List неизменна, а сами значения меняться могу. 
Но когда человек видит final, сразу в голове может возникнуть мысль, что ничего менять не надо, может привести к путанице.
Это скорее на будущее, а так засчитываю

2024-10-06 07:29 UTC, BobrAll approved these changes
Все гуд, оставил коммент по коду, но это просто для прочтения на будущее, исправлять не нужно, засчитываю

2024-10-06 07:29 UTC, merged