BJS2-31319 реализовал абстрактный класс, двух наследников и функционал метода attack
CorporationX/god_bless pull request #11152
Opened 2024-10-03 20:45 UTC by evgen-backend-rostov

2024-10-03 21:45 UTC, jibulani requested changes
В целом все хорошо, молодец!
Оставил несколько небольших замечаний

2024-10-03 21:45 UTC, jibulani commented on src/main/java/school/faang/abstraction/Archer.java
> +        super(name);
у тебя же есть второй конструктор, который принимает сразу все эти параметры, почему бы не воспользоваться им?

2024-10-03 21:45 UTC, jibulani commented on src/main/java/school/faang/abstraction/Archer.java
> +        person.health = String.valueOf(Integer.parseInt(person.health) - Integer.parseInt(power));
чтобы не приходилось так заморачиваться с преобразованиями типов, лучше сразу объявить переменные с теми типами, которые им на самом деле соответствуют, т.е., если понятно, что сила у нас число, то лучше так и объявить переменную:` int power;`
ну и с остальными переменными такая же ситуация, кроме имени, для него действительно хорошо подходит `String `:)

2024-10-03 21:45 UTC, jibulani commented on src/main/java/school/faang/abstraction/Warrior.java
> +
тут те же замечания по конструктору и типам

2024-10-03 21:45 UTC, jibulani commented on src/main/java/school/faang/abstraction/Main.java
> +        Character archer = new Archer("Legolas");
молодец, что проверяешь работу кода!
если есть время и желание, можешь пойти дальше и написать для проверки правильности работы тест на JUnit

2024-10-04 16:42 UTC, evgen-backend-rostov commented on src/main/java/school/faang/abstraction/Main.java
> +        Character archer = new Archer("Legolas");
Привет! Спасибо за комментарии)

2024-10-04 21:01 UTC, jibulani requested changes
Все супер!
Осталась одна небольшая правочка

2024-10-04 21:01 UTC, jibulani commented on src/test/java/school/faang/abstraction/WarriorCharacterTest.java
> +    void attackMethodTest() {
хороший тест, молодец!

2024-10-05 10:25 UTC, evgen-backend-rostov commented on src/main/java/school/faang/abstraction/Archer.java
> +        person.health -= power;
Видимо и я прошляпил. Спасибо)

2024-10-05 10:25 UTC, evgen-backend-rostov commented on src/test/java/school/faang/abstraction/WarriorCharacterTest.java
> +    void attackMethodTest() {
Пасиб!

2024-10-05 10:36 UTC, jibulani approved these changes
Все супер! В прод!

2024-10-05 10:36 UTC, merged