Realized AbstractionAbstraction task
CorporationX/god_bless pull request #11163
Opened 2024-10-03 23:25 UTC by drakesbrother

2024-10-04 09:08 UTC, jibulani requested changes
Хороший код, молодец!
Немного доработок и в прод!

2024-10-04 09:08 UTC, jibulani commented on src/main/java/abstractionAbstraction/Archer.java
> +        character.decreaseHealth(ARCHER_AGILITY);
тут я бы не передавал сюда константу, а использовал параметр agility
вдруг у нас позже по требованиям появится возможность создавать лучников с кастомной ловкостью, тогда эта константа тут не подойдет

2024-10-04 09:08 UTC, jibulani commented on src/main/java/abstractionAbstraction/Character.java
> +        this.health = 100;
лучше проинициализировать health сразу при объявлении

в будущем может понадобиться создавать другие конструкторы и в каждом из них прописывать дефолтное значение здоровья будет неудобно, выше риск ошибиться

а в случае, если при объявлении указано дефолтное здоровье, то это наглядно и нет риска забыть его проинициализировать

2024-10-04 09:08 UTC, jibulani commented on src/main/java/abstractionAbstraction/Warrior.java
> +        character.decreaseHealth(WARRIOR_STRENGTH);
ситуация аналогична той, что в Archer

2024-10-04 09:08 UTC, jibulani commented on src/main/java/abstractionAbstraction/Main.java
> +        Warrior warrior = new Warrior("Tank");
тут и в тестах можно использовать переменные типа Character, если там метод attack будет публичным

2024-10-04 09:08 UTC, jibulani commented on src/test/java/AbstractionAbstractionTest.java
> +import abstractionAbstraction.Archer;
Хорошие тесты, молодец!
Небольшое замечание - обычно тесты располагают в пакете, который по имени совпадает с пакетом в котором лежат тестируемые объекты, это позволяет проще находить нужный тест, если проект большой и тестов много
Поэтому в папке test/java можешь создать пакет abstraction (в зависимости от того, как переименуешь пакет в main/java) и туда поместить этот тест, но сейчас это не принципиально :)

2024-10-04 12:41 UTC, drakesbrother commented on src/main/java/abstractionAbstraction/Main.java
> +        Warrior warrior = new Warrior("Tank");
@jibulani поправил, но не совсем понял почему лучше тип Character?

2024-10-04 19:25 UTC, jibulani requested changes
В целом все хорошо, остался финальный рывок :)

2024-10-04 19:25 UTC, jibulani commented on src/main/java/abstraction/Archer.java
> +        character.decreaseHealth(archerAgility);
тут ты по сути продолжаешь использовать заранее проинициализированный статический параметр, не относящийся к конкретному объекту

нужно использовать параметр конкретного персонажа, который в данный момент атакует (this.agility)

2024-10-04 19:25 UTC, jibulani commented on src/main/java/abstraction/Warrior.java
> +        character.decreaseHealth(warriorStrength);
та же ситуация, что и у лучника

2024-10-04 19:25 UTC, jibulani commented on src/main/java/abstraction/Archer.java
> +    public static int archerStrength = 3;
тут можно было оставить final, как было изначально

2024-10-05 09:55 UTC, jibulani commented on src/main/java/abstraction/Character.java
> +    public abstract void attack(Character character);
сорри, что-то сразу не заметил, так что комментарий на будущее
обычно сначала идут объявления переменных, потом конструкторы, потом методы, тут некритично, но в будущем так лучше упорядочивать

2024-10-05 09:56 UTC, merged