Pirozhok1043 bjs2 33000
CorporationX/god_bless pull request #11170
Opened 2024-10-04 04:16 UTC by abdddev

2024-10-06 16:13 UTC, BobrAll requested changes
В целом гуд, немного фиксов

2024-10-06 16:13 UTC, BobrAll commented on src/main/java/school/faang/google/Google.java
> +            String[] words = webPage.getContent().split("\\s+");
Что будет, если обработать 2 текста: "Казнить, нельзя помиловать" и "Казнить нельзя, помиловать"? Найдет ли он оба текста по слову “Казнить“ или ”нельзя“?

2024-10-06 16:13 UTC, BobrAll commented on src/main/java/school/faang/google/Google.java
> +        if (!existingPages.contains(webPage)) {
Чтобы длинный if не тянулся на всю функцию, можно сделать просто
if (existingPages.contains(webPage))
return;

2024-10-06 16:13 UTC, BobrAll commented on src/main/java/school/faang/google/Google.java
> +                pages.computeIfAbsent(word.toLowerCase(), key -> new ArrayList<>()).add(webPage);
За lowerCase +

2024-10-06 16:13 UTC, BobrAll commented on src/main/java/school/faang/google/Google.java
> +    public void removeWebPage(String url) {
Может быть кейс, когда у нас в результате работы этого метода ключ(ключи) ведет в пустые списки, такое по-хорошему бы устранить

2024-10-06 16:13 UTC, BobrAll commented on src/test/java/school/faang/google/GoogleTest.java
> +    void notAddIfAlreadyExistTest() {
Not add что? Что не добавляем-то?)

2024-10-07 06:31 UTC, abdddev commented
и сразу тесты поправил с учетом комментов с другой задачи)

2024-10-07 09:15 UTC, BobrAll requested changes
Чуть исправлений и принимаю

2024-10-07 09:15 UTC, BobrAll commented on src/main/java/school/faang/google/Google.java
> +        String content = webPage.getContent().replaceAll("[^a-zA-Zа-яА-ЯёЁ0-9\\s]", "");
Выкрутился)
Можно было в регулярку сделать "\\W+"

2024-10-07 09:15 UTC, BobrAll commented on src/main/java/school/faang/google/Google.java
> +        removeFromPages(url);
Вопрос по именованию: глядя на эти 2 строчки складывается ощущение, что сначала удаляем с существующих страниц, а потом .. с несуществующих?

Другой вопрос - что удаляем? remove?From..

2024-10-07 09:15 UTC, BobrAll commented on src/main/java/school/faang/google/Google.java
> +        findRequestsWithEmptyPagesAfterRemoval(url).forEach(pages::remove);
Обычно советуется методы разбивать. Но в данном случае я бы оставил логику findRequestsWithEmptyPagesAfterRemoval() в этом же методе. Ты постарался описать прям все, что происходит внутри метода в его имени. Можно сделать более абстрактно - метод removePageFromIndex, в котором будет удаляться url из всех ключевых слов и затем удаляться ключевые слова, которые ведут на пустые листы - это все входит в логику удаления страницы из индексации.

2024-10-07 17:28 UTC, BobrAll reviewed
принято

2024-10-07 17:28 UTC, merged