Gadzhi bjs2 32430
CorporationX/god_bless pull request #11173
Opened 2024-10-04 05:28 UTC by GadzhiGadzhiev

Решение задачи считаем прогулы

2024-10-05 17:45 UTC, MiraGlaceon requested changes

2024-10-05 17:45 UTC, MiraGlaceon commented on src/main/java/school/faang/counting_absenteeism/Main.java
> +public class Main {
Молодец, что стал раскидывать классы по пакетам. Но имена пакетов старайся давать маленькими буквами без пробелов. У тебя counting_absenteeism можно заменить на countingabsenteeism. Так же не забывай разделять классы по логике и назначению по разным пакетам

2024-10-05 17:45 UTC, MiraGlaceon commented on src/main/java/school/faang/counting_absenteeism/Main.java
> +    public static void main(String[] args) {
Оставь классе Main только метод main и вспомогательные методы. А методы по работе со студентами выдели в отдельный класс по работе и операциям со студентами

2024-10-05 17:45 UTC, MiraGlaceon commented on src/main/java/school/faang/counting_absenteeism/Main.java
> +        students.remove(new Student(name, faculty, year));
Ты тут создаешь нового студента и удаляешь его из списка. Это работает, но почему? Ведь у нового объекта и объекта, который потенциально лежит в списке разные ссылки. Подсказка: посмотри на методы hashCode, equals и аннотацию @ Data и расскажи почему твой код по удалению объекта работает

2024-10-06 13:38 UTC, GadzhiGadzhiev commented on src/main/java/school/faang/counting_absenteeism/Main.java
> +public class Main {
То есть нижние подчеркивания использовать в пакете это плохой тон? Я думал это читабельности добавляет и поэтому ставил

2024-10-06 14:13 UTC, GadzhiGadzhiev commented on src/main/java/school/faang/counting_absenteeism/Main.java
> +        students.remove(new Student(name, faculty, year));
Аннотация @Data предопределяет equals и hashCode и когда мы передаем новый объект в remove вызывается метод equals для сравнения этого нового объекта с каждым элементом в коллекции и если equals возвращает true то объекты считаются равными если даже ссылки разные

2024-10-08 19:17 UTC, MiraGlaceon commented on src/main/java/school/faang/counting_absenteeism/Main.java
> +        students.remove(new Student(name, faculty, year));
Корректно. А в мапе еще задействован hashCode так же

2024-10-08 19:17 UTC, MiraGlaceon approved these changes

2025-01-17 21:26 UTC, closed without merging