BJS2-32466: Считаем прогулы
CorporationX/god_bless pull request #11182
Opened 2024-10-04 08:51 UTC by Sanasar1

2024-10-04 18:53 UTC, mysosnovskaya requested changes

2024-10-04 18:53 UTC, mysosnovskaya commented on src/main/java/bjs2_29013/AcademicProgram.java
> +public class AcademicProgram {
Это ты интересно с отдельным классом AcademicProgram придумал) Мне нравится! И молодец, что не забыл переопределить equals и hashcode

2024-10-04 18:53 UTC, mysosnovskaya commented on src/main/java/bjs2_29013/Student.java
> +public class Student extends AcademicProgram {
Это наследование по логике неверно. Студент не является расширением класса AcademicProgram, это как если бы стол наследовался от класса "геометрическая фигура" - вроде бы длина, ширина, высота, площадь, объем - всё есть, но стол это не геометрическая фигура, это неверно. Здесь также - студент это не академическая программа. Тут будет в тему почитать про "наследование или композиция", можешь поискать информацию по этому вопросу) Вот в данном случае тебе подойдет композиция: у класса Student будет поле AcademicProgram

2024-10-04 18:53 UTC, mysosnovskaya commented on src/main/java/bjs2_29013/Main.java
> +            groupedStudents.computeIfAbsent(new AcademicProgram(student.getFaculty(), student.getYear()),
Круто, что применил computeIfAbsent, это здесь очень подходит 👍

2024-10-04 18:53 UTC, mysosnovskaya commented on src/main/java/bjs2_29013/Main.java
> +    public static void removeStudent(List<Student> students,
Здесь переусложнено получилось. Вообще задание звучит как "удаление студента из списка по его имени", а у тебя удаляется не по имени. Я думаю, с studentIndices это лишнее. Посмотри на метод removeIf из List

2024-10-04 20:26 UTC, Sanasar1 commented on src/main/java/bjs2_29013/Main.java
> +    public static void removeStudent(List<Student> students,
Ну я хотел решить за константное время, поэтому так и сделал)

2024-10-05 14:38 UTC, mysosnovskaya commented on src/main/java/bjs2_29013/Main.java
> +    public static void removeStudent(List<Student> students,
Я поняла, но программисты не любят решать проблемы, которые ещё не наступили (если этого явно не требуется в задаче). Может быть они никогда и не наступят? А на их решение сейчас можно потратить кучу времени. Поэтому самое лучшее решение - это простое решение. Если потом возникнут проблемы с производительностью, тогда вернемся к этому коду и оптимизируем его.

2024-10-05 14:38 UTC, mysosnovskaya approved these changes

2024-10-05 14:38 UTC, merged