BJS2-32422
CorporationX/god_bless pull request #11205
Opened 2024-10-04 11:47 UTC by Macacin

Есть ощущение, что я навалил лютого кринжа, но вроде методы простенькие и рабочие. Надеюсь я правильно понял все условия...

2024-10-04 19:07 UTC, mysosnovskaya requested changes
Не пугайся 10 комментариев, они все об одном и том же: между двумя мапами нужна согласованность, поэтому в каждом методе нужно работать сразу с двумя мапами)

2024-10-04 19:07 UTC, mysosnovskaya commented on src/main/java/school/faang/doubleCash/Student.java
> +@EqualsAndHashCode
Молодец, что не забыл переопределить equals и hashcode 👍

2024-10-04 19:07 UTC, mysosnovskaya commented on src/main/java/school/faang/doubleCash/Main.java
> +    private static void addStudentAndGrades(Student student, List<Subject> subjects, List<Integer> grades) {
Думаю, тут предполагалось вместо двух отдельных списков с предметами и оценками одна мапа `Map<Subject, Integer>`

2024-10-04 19:07 UTC, mysosnovskaya commented on src/main/java/school/faang/doubleCash/Main.java
> +        studentsGrades.put(student, gradeMap);
А learntSubjects тоже обновить нужно)

2024-10-04 19:07 UTC, mysosnovskaya commented on src/main/java/school/faang/doubleCash/Main.java
> +                gradeMap.put(subject, grade);
Здесь тоже нужно learntSubjects обновлять

2024-10-04 19:07 UTC, mysosnovskaya commented on src/main/java/school/faang/doubleCash/Main.java
> +        studentsGrades.remove(student);
И здесь нужно работать с learntSubjects тоже

2024-10-04 19:07 UTC, mysosnovskaya commented on src/main/java/school/faang/doubleCash/Main.java
> +        System.out.println(studentsGrades);
Может быть как-то покрасивее выведем?) Можно как-то так:
```
Студент1: Иван
Его оценки:
Алгебра - 5
Java - 5
Физкультура - 3
```
В идеале на английском)

2024-10-04 19:07 UTC, mysosnovskaya commented on src/main/java/school/faang/doubleCash/Main.java
> +        learntSubjects.put(subject, students);
А здесь наоборот нужно не забыть про studentsGrades

2024-10-04 19:07 UTC, mysosnovskaya commented on src/main/java/school/faang/doubleCash/Main.java
> +        learntSubjects.computeIfAbsent(subject, k -> new ArrayList<>()).add(student);
И здесь нужно studentsGrades обновлять

2024-10-04 19:07 UTC, mysosnovskaya commented on src/main/java/school/faang/doubleCash/Main.java
> +            List<Student> students = entry.getValue();
И здесь studentsGrades нужна

2024-10-05 08:09 UTC, Macacin commented on src/main/java/school/faang/doubleCash/Main.java
> +        learntSubjects.put(subject, students);
я так понимаю надо получается еще список с оценками на вход получать? Типа для каждого студента вот такая то оценка по полученному предмету

2024-10-05 08:17 UTC, Macacin commented on src/main/java/school/faang/doubleCash/Main.java
> +        learntSubjects.put(subject, students);
Я решил тогда на вход получать мапу с студентом и его оценками вместо двух листов, вроде норм

2024-10-05 09:46 UTC, Macacin commented
У меня получился супер громадный код в методе удаления студента, я там всё учёл что можно было, но я уверен что это супер неоптимизированное решение и можно как-то лучше, не знаю правда как :/

2024-10-05 14:35 UTC, mysosnovskaya requested changes

2024-10-05 14:35 UTC, mysosnovskaya commented on src/main/java/school/faang/doubleCash/Main.java
> +        grades.put(subject, grade);
Не хватает работы со второй мапой

2024-10-05 14:35 UTC, mysosnovskaya commented on src/main/java/school/faang/doubleCash/Main.java
> +    private static void removeStudent(Student student) {
В целом хорошо, но можно ещё улучшить) Попробуй проходить не по всем  learntSubjects.entrySet(), а только по тем, которые студент точно изучал. У тебя эта информация есть, посмотри, что возвращает метод ` studentsGrades.remove(student);`

2024-10-05 14:35 UTC, mysosnovskaya commented on src/main/java/school/faang/doubleCash/Main.java
> +    private static void addSubjectAndStudents(Subject subject, Map<Student, Integer> grades) {
Предполагалось, что метод принимает предмет и список студентов, которые его изучают (без оценок)

2024-10-05 14:35 UTC, mysosnovskaya commented on src/main/java/school/faang/doubleCash/Main.java
> +    private static void removeStudentFromSubject(Student studentToRemove, Subject subject) {
Здесь аналогично методу removeStudent: проходи не по всем  learntSubjects.entrySet() и studentsGrades.entrySet() (это слишком сложно), а только по нужным. Если поймешь, как реализовать removeStudent, то и здесь будет похожая идея) Если не разберешься - тэгай меня в чате, обсудим. Ну или завтра на встрече тоже сможем об этом поговорить)

2024-10-05 17:12 UTC, Macacin commented on src/main/java/school/faang/doubleCash/Main.java
> +    private static void addSubjectAndStudents(Subject subject, Map<Student, Integer> grades) {
А как тогда обновлять studentsGrades? Задавать null значение оценкам? Попробую так

2024-10-05 18:52 UTC, Macacin commented on src/main/java/school/faang/doubleCash/Main.java
> +    private static void removeStudentFromSubject(Student studentToRemove, Subject subject) {
Спасибо за комменты, натолкнули на вот такое простенькое и красивое (вроде) решение, не знаю правда это ли решение ты имела ввиду, но получилось неплохо вроде)

2024-10-06 03:44 UTC, mysosnovskaya approved these changes

2024-10-06 03:44 UTC, mysosnovskaya commented on src/main/java/school/faang/doubleCash/Main.java
> +    private static void removeStudentFromSubject(Student studentToRemove, Subject subject) {
Да, красиво получилось)

2024-10-06 03:44 UTC, mysosnovskaya commented on src/main/java/school/faang/doubleCash/Main.java
> +            studentsGrades.computeIfAbsent(student, k -> new HashMap<>()).put(subject, null);
Да, с null верно. Т.е. мы уже знаем, что студент изучает этот предмет, но оценок он ещё не получил

2024-10-06 03:45 UTC, merged