added homm III
CorporationX/god_bless pull request #11207
Opened 2024-10-04 12:14 UTC by abdddev

2024-10-07 09:53 UTC, BobrAll requested changes
Круто, с именованием виден прогресс. С тестами тоже, короткие и эффективные - какие и должны быть. Есть немного правок

2024-10-07 09:53 UTC, BobrAll commented on src/main/java/school/faang/homm/Creature.java
> +    public Creature(String name, int level, int damage, int defense, int speed) {
Тут была бы прям в тему аннотация @AllArgsConstructor

2024-10-07 09:53 UTC, BobrAll commented on src/main/java/school/faang/homm/Creature.java
> +    private int damage;
Атака это attack 
damage как поля нет - просто функция (ты ее уже определил)

2024-10-07 09:53 UTC, BobrAll commented on src/main/java/school/faang/homm/Creature.java
> +    public Integer getAmountOfDamage() {
А можешь сделать с учетом того, что у каждого класса-наследника getAmountOfDamage() рассчитывается по-разному?

2024-10-07 09:53 UTC, BobrAll commented on src/main/java/school/faang/homm/Battlefield.java
> +                .sum();
Гуд! Можно еще в отдельный метод вынести, чтобы не было дублирования

2024-10-07 09:53 UTC, BobrAll commented on src/main/java/school/faang/homm/Battlefield.java
> +        return totalDamageHero1 > totalDamageHero2 ? hero1 : hero2;
А если ничья?)

2024-10-07 09:53 UTC, BobrAll commented on src/test/java/school/faang/homm/BattlefieldTest.java
> +    void battleWinSecondHeroBecauseArmySecondHeroEmptyTest() {
ухх длинное название, попробуй более абстрактно, например armyWinEmptyArmyTest() хотя бы)

Но опять-таки, длинные название не приговор, если их нельзя сократить без потери смысла, если можно - лучше сократить

2024-10-07 13:32 UTC, abdddev commented on src/main/java/school/faang/homm/Battlefield.java
> +                .sum();
точно точно блин) спасибо

2024-10-08 20:06 UTC, BobrAll reviewed
Принимаю, выглядит хорошо

2024-10-08 20:06 UTC, BobrAll commented on src/main/java/school/faang/homm/Battlefield.java
> +        return getTotalDamage(hero1) >= getTotalDamage(hero2) ? hero1 : hero2;
Тут скорее было про то, что у тебя не предусмотрена ничья)
Но это не критично

2024-10-08 20:06 UTC, merged

2024-10-09 04:46 UTC, abdddev commented on src/main/java/school/faang/homm/Battlefield.java
> +        return getTotalDamage(hero1) >= getTotalDamage(hero2) ? hero1 : hero2;
Я да подзавис что делать, не помню чтобы в оригинальных HMM III была ничья, наверное просто кидать рандом от 0 до 1 и отдавать победу рандомно, в случае одинакового количества дамага