Java HashMap: Двойной кэш-кэш
CorporationX/god_bless pull request #11200
Opened 2024-10-04 10:46 UTC by allitov

2024-10-06 11:25 UTC, BobrAll requested changes
Хороший код, чуть исправлений
Буду final по талонам выдавать тебе

2024-10-06 11:25 UTC, BobrAll commented on src/main/java/school/faang/hashhash/Subject.java
> +    private final String name;
IDE нас погубят
У меня в университете только на моем направлении за год поменялось название нескольких предметов.
final идеально подходит для констант, которые железно неизменны. Например, число пи - оно и в Африке пи - никогда не поменяется. А там где есть сомнения final лучше не писать

2024-10-06 11:25 UTC, BobrAll commented on src/main/java/school/faang/hashhash/Main.java
> +        addSubject(physics, new ArrayList<>(List.of(alex, ivan, petr)));
А если добавить студента, но забыть предмет? Было бы удобно при добавлении студента, чтобы он сразу заносился в мапу предметов

2024-10-06 11:25 UTC, BobrAll commented on src/main/java/school/faang/hashhash/Student.java
> +    private final String name;
Строгий ты, конечно
Имя даже в паспорте можно поменять, а у тебя - нет)

2024-10-06 12:42 UTC, allitov commented on src/main/java/school/faang/hashhash/Main.java
> +        addSubject(physics, new ArrayList<>(List.of(alex, ivan, petr)));
Согласен, надо добавить такой функционал

2024-10-06 12:42 UTC, allitov commented on src/main/java/school/faang/hashhash/Subject.java
> +    private final String name;
Здесь я использовал final, чтобы избежать непредсказуемого поведения HashMap. Читал, что использование объектов с изменяемыми полями, по которым вычисляется хэш, в качестве ключа является плохой практикой, так как может привести к тяжело находимым ошибкам. Возможно, я понял это правило слишком буквально :)

2024-10-06 12:42 UTC, allitov commented on src/main/java/school/faang/hashhash/Student.java
> +    private final String name;
Ну да, довольно абсурдно выглядит. Очень интересно узнать твое мнение на счет объектов, используемых в качестве ключа в хэш-структурах

2024-10-07 08:22 UTC, BobrAll commented on src/main/java/school/faang/hashhash/Subject.java
> +    private final String name;
На самом деле ты правильно понял)
В контексте данной задачи можно поступить так: переопределить метод hashCode() и equals(), чтобы в них учитывался только id. Это сработает, потому что у нас он уникальный и неизменный - как студентов, так и для предметов. Таким образом, даже если мы поместим объект в мапу, затем поменяем имя (предмет) и постараемся найти этот объект - он найдется, т.к. хеш рассчитывается по id (без учета измененного поля) и мы попадем в нужный бакет (а если в бакете будет несколько объектов - там по equals() уже пройдет сравнение id'шников)

2024-10-08 20:03 UTC, BobrAll approved these changes
Найс! И прям хорошо, что руками попереопределял методы, так больше приходит понимание. На будущее, чтобы это каждый раз не делать, - можно в аннотации lombok'а указывать, по каким полям делать equals() и hashCode()

2024-10-08 20:03 UTC, merged