BJS2-32377 Double cache cache
CorporationX/god_bless pull request #11211
Opened 2024-10-04 12:26 UTC by VovaBuzivskyi

2024-10-06 11:48 UTC, BobrAll requested changes
В целом гуд, написал что подправить нужно.
Если хочешь все-таки оставить тесты, то их нужно переделать (расписал там как именно)

2024-10-06 11:48 UTC, BobrAll commented on src/main/java/school/faang/double_cache_cache_BJS2_32377/Main.java
> +    private Map<Student, Map<Subject, Integer>> studentsListWithSubjects = new HashMap<>();
1) У нас не лист студентов, а мапа
2) Название структуры можно не указывать в названии - тип переменной же виден. А так имя короче и не перегружено. То есть, если мы увидим students - мы же поймем, что он там не один, значит какая-то коллекция студентов

2024-10-06 11:48 UTC, BobrAll commented on src/main/java/school/faang/double_cache_cache_BJS2_32377/Main.java
> +        targetMap.put(student, subjectsAndGrades);
Лучше не затирать имя мапы, targetMap не дает хорошего понимания о том, куда мы помещаем студентов и группы с оценками. Да, это видно из 

>  Map<Student, Map<Subject, Integer>>

Но при чтении сбивает, как минимум нужно глянуть что за targetMap такая. И так в других местах тоже

2024-10-06 11:48 UTC, BobrAll commented on src/main/java/school/faang/double_cache_cache_BJS2_32377/Main.java
> +    public void addNewSubjectForExistingStudent(Subject subject, int grade, Student student,
Поменяется ли смысл, если опустим слова new и existing?
И лучше не for, а to

2024-10-06 11:48 UTC, BobrAll commented on src/main/java/school/faang/double_cache_cache_BJS2_32377/Main.java
> +        targetMap.put(student, subjectsAndGrades);
А если в коде добавить студента, но забыть предмет? Было бы удобно при добавлении студента, чтобы он сразу заносился в мапу предметов

2024-10-06 11:48 UTC, BobrAll commented on src/main/java/school/faang/double_cache_cache_BJS2_32377/Test.java
> +public class Test {
Очень большой тест. Тесты должны быть маленькими и предназначенными для проверки конкретной функциональной единицы. Они поэтому так и называются - unit тесты. Пример такого теста: addUserTest() - проверяет, что студент добавляется. Как именно? Нужно почитать про assert - assertNull(), assertTrue() и т.д. - именно они делают тест тестом.

2024-10-06 14:58 UTC, VovaBuzivskyi commented on src/main/java/school/faang/double_cache_cache_BJS2_32377/Main.java
> +    public void addNewSubjectForExistingStudent(Subject subject, int grade, Student student,
Понял , нужно чуть упрощать названия.

2024-10-06 16:04 UTC, VovaBuzivskyi commented on src/main/java/school/faang/double_cache_cache_BJS2_32377/Main.java
> +        targetMap.put(student, subjectsAndGrades);
Хорошая идея)

2024-10-06 16:10 UTC, VovaBuzivskyi commented on src/main/java/school/faang/double_cache_cache_BJS2_32377/Test.java
> +public class Test {
Я про юнит тесты немножко только знаю. По-этому пока не пытаюсь их использовать. Я проверяю функционал каждого метода в Main() методе ,  а так как эта проверка заняла много места , я вынес ее в отдельный класс.

2024-10-06 16:31 UTC, VovaBuzivskyi commented on src/main/java/school/faang/double_cache_cache_BJS2_32377/Test.java
> +public class Test {
В Main классе 8 методов , и после вызова большинства из них нужно вызвать метод для принта в консоль ,иначе будет не понятно что они работают правильно.

2024-10-06 16:45 UTC, BobrAll commented on src/main/java/school/faang/double_cache_cache_BJS2_32377/Test.java
> +public class Test {
> Я про юнит тесты немножко только знаю. По-этому пока не пытаюсь их использовать. Я проверяю функционал каждого метода в Main() методе , а так как эта проверка заняла много места , я вынес ее в отдельный класс.

Ага, понял. Просто слово Test сбило с толку

2024-10-06 16:53 UTC, BobrAll reviewed
Чуть исправлений и принимаю

2024-10-06 16:53 UTC, BobrAll commented on src/main/java/school/faang/double_cache_cache_BJS2_32377/Test.java
> +public class Test {
> В Main классе 8 методов , и после вызова большинства из них нужно вызвать метод для принта в консоль ,иначе будет не понятно что они работают правильно.

Это очень легко фиксится. Смотри, у тебя встречается в коде что-то подобное:
main.printSubjectsAndStudyingStudents(main.getSubjectsWithStudents());
        printGaps();

Можно просто в printSubjectsAndStudyingStudents() в конце метода добавить то, что у тебя сейчас находится в printGaps(). Таким образом тебе и по 2 функции не нужно вызывать, и отступы красивые.

2024-10-06 17:40 UTC, VovaBuzivskyi commented on src/main/java/school/faang/double_cache_cache_BJS2_32377/Test.java
> +public class Test {
Понял, спасибо за подсказку) Ничего что я разграничил немного код пустыми строками между ним? Просто иначе этот прямоугольник кучного кода меня пугает, там тяжело понять что за чем идет, если не разграничить.

2024-10-07 08:26 UTC, BobrAll commented on src/main/java/school/faang/double_cache_cache_BJS2_32377/Test.java
> +public class Test {
Да, норм)

2024-10-07 08:27 UTC, merged