BJS2-32437 - Java HashMap: Считаем прогулы
CorporationX/god_bless pull request #11235
Opened 2024-10-04 15:26 UTC by Shakhaev

Задача: Считаем прогулы. Создание классов Student и StudentProfile. Тестирование методов в классе Main

2024-10-05 20:38 UTC, MiraGlaceon requested changes

2024-10-05 20:38 UTC, MiraGlaceon commented on src/main/java/school/faang/count_absenteeism/Main.java
> +public class Main {
1) Общее замечание: имена пакетам давай маленькими буквами без пробелом. У тебя count_absenteeism лучше переписать на countabsenteeism  
2) STUDENTS, INDEX_STUDENT - Заглавными буквами пишем только константы. Ты объявил мапу и список как final, но по логике они не константные
3) INDEX_STUDENT - эта ассоциативная мапа лишняя. Ты добавляешь индекс, который находишь из списка студентов по конкретному студенту, который можешь получить во всех ситуациях. Ты усложнил код тем, что нагрузил его логикой и дублируешь операции, например, две вставки в массив и мапу, два удаления и тд

2024-10-05 20:38 UTC, MiraGlaceon commented on src/main/java/school/faang/count_absenteeism/Student.java
> +public class Student {
Совет: Даже если задачка тривиальная, по логике видим, что студенту вполне пригодятся сеттеры. Подправь аннотации

2024-10-05 20:38 UTC, MiraGlaceon commented on src/main/java/school/faang/count_absenteeism/StudentProfile.java
> +@EqualsAndHashCode
Тут тоже самое, вполне пригодятся сеттеры

2024-10-05 20:38 UTC, MiraGlaceon commented on src/main/java/school/faang/count_absenteeism/Main.java
> +    public static HashMap<StudentProfile, ArrayList<Student>> groupingStudents(List<Student> students) {
Логику по работе со студентами лучше вынести в отдельный класс-сервис

2024-10-06 08:29 UTC, Shakhaev commented on src/main/java/school/faang/count_absenteeism/Main.java
> +public class Main {
1. Имя пакета изменил, но в таком случае возникает та же путаница, как если бы мы при именовании переменных не использовали CamelCase. Если пакет имеет довольно длинное название, например, "com.data.my.new.project" (условное имя, для примера), то в случае, если убрать пробелы и спец. символы, то получил "comdatamynewproject". Получается какая-то солянка.
2. В моем случае данные структуры данных имеют синтаксис вида "public static final...", что, как мне известно, является объявлением констант, соответственно, имя данных структур данных я написал заглавными буквами. Но, может быть, в моей логике они не константные. В таком случае, не очень понимаю, где именно мои константы используются не в качестве констант.
3. Согласен! Удалил лишнюю мапу.

2024-10-07 19:33 UTC, MiraGlaceon approved these changes

2024-10-08 19:25 UTC, MiraGlaceon requested changes

2024-10-08 19:25 UTC, MiraGlaceon commented on src/main/java/school/faang/countabsenteeism/StudentProfile.java
> +public class StudentProfile {
EqualsAndHashCode, ToString, Setter и Getter можно объединить аннотацией @ Data

2024-10-08 19:25 UTC, MiraGlaceon commented on src/main/java/school/faang/countabsenteeism/Main.java
> +    public static final List<Student> STUDENTS = new ArrayList<>();
students напиши маленькими буквами, у тебя обозначено final, но значение по логике совсем не константное

2024-10-08 19:25 UTC, MiraGlaceon commented on src/main/java/school/faang/countabsenteeism/StudentService.java
> +import static school.faang.countabsenteeism.Main.STUDENTS;
Очень плохая практика. Никогда не импортируй логически рабочие переменные через строку импорта. Разрешено, если константа, но у тебя список студентов это совсем не константное значение. 
Если тебе нужно получить список студентов в сервисе, то передавай его через методы, например,
public void add(Student student, List students). У тебя сервис не должен зависеть от внешних переменных. Он выполняется максимально в абстрактной среде, принимая значения в методах и отдавая в методах

2024-10-08 20:39 UTC, MiraGlaceon approved these changes

2025-01-17 21:26 UTC, closed without merging