Проверьте пожалуйста.
CorporationX/god_bless pull request #11256
Opened 2024-10-04 18:12 UTC by Darkselect

Вкусненько

2024-10-07 17:51 UTC, Mixalight requested changes

2024-10-07 17:51 UTC, Mixalight commented on src/main/java/school/faang/lightsect/BJS233245/StreamEvent.java
> +@Data
Data - аннотация, которая тащит за собой очень много лишнего. Лучше использовать точечно нужные тебе аннотации

2024-10-07 17:51 UTC, Mixalight commented on src/main/java/school/faang/lightsect/BJS233245/Event.java
> +    static final Map<Integer, StreamEvent> STREAM_EVENT = new HashMap<>();
Не очень понятные названия
В случае мап можно делать что-то вида streamEventById

2024-10-07 17:51 UTC, Mixalight commented on src/main/java/school/faang/lightsect/BJS233245/Event.java
> +    List<StreamEvent> searchStreamEvenByType(String type) {
Event*

2024-10-07 17:51 UTC, Mixalight commented on src/main/java/school/faang/lightsect/BJS233245/Event.java
> +
Лишняя строка

2024-10-07 17:51 UTC, Mixalight commented on src/main/java/school/faang/lightsect/BJS233245/Event.java
> +            LIST_OF_EVENT_WITH_TYPE.get(event.getEventType()).removeIf(e -> e.getId() == id);
Можно сделать просто remove по id из массива, без доп проверки

2024-10-08 09:05 UTC, Mixalight requested changes

2024-10-08 09:05 UTC, Mixalight commented on src/main/java/school/faang/lightsect/BJS233245/StreamEvent.java
> +@Data
Всё ещё актуально

2024-10-08 09:05 UTC, Mixalight commented on src/main/java/school/faang/lightsect/BJS233245/Event.java
> +        STREAM_EVENT_BY_ID.remove(id);
Удаление должно быть из двух мап
Мой прошлый комментарий был как раз про лёгкое удаление из второй мапы(вытащить массив по типу и сделать remove)

2024-10-08 16:25 UTC, Darkselect commented on src/main/java/school/faang/lightsect/BJS233245/StreamEvent.java
> +@Data
Ну так я же использую геттеры и сеттеры

2024-10-09 11:14 UTC, merged