задача Ловим события
CorporationX/god_bless pull request #11254
Opened 2024-10-04 18:06 UTC by IrinaKrasnova

2024-10-06 17:38 UTC, Mixalight requested changes

2024-10-06 17:38 UTC, Mixalight commented on src/test/java/StreamEventPak/StreamEvent.java
> +    public int getId() {
Можно использовать аннотацию Getter из Lombock, это позволит не писать каждый раз стандартные геттеры

2024-10-06 17:38 UTC, Mixalight commented on src/test/java/StreamEventPak/StreamEvent.java
> +    public boolean equals(Object o) {
Аналогичное с equals, hashCode и toString
Можешь не менять, но если тебе нужны базовые, то есть ты не вносишь какого-то нового функционала - можно ставить аннотации из Lombock

2024-10-06 17:38 UTC, Mixalight commented on src/test/java/StreamEventPak/Main.java
> +        if (!eventByType.containsKey(streamEvent.getEventType())) {
Есть метод computeIfAbsent у мапы, он позволяет добавлять элемент, если его не было и потом в любом случае возвращает элемент по ключу
Тут подробнее https://www.baeldung.com/java-map-computeifabsent

2024-10-06 17:38 UTC, Mixalight commented on src/test/java/StreamEventPak/Main.java
> +    public static void findEventTupe(String type) {
Type*

2024-10-06 17:38 UTC, Mixalight commented on src/test/java/StreamEventPak/Main.java
> +    private static void printStreamEent() {
Event*

2024-10-07 17:41 UTC, IrinaKrasnova commented on src/test/java/StreamEventPak/StreamEvent.java
> +    public boolean equals(Object o) {
У меня не работает Lombock. на созвоне с ментором не смогли оешить эту проблему. Он пообещал поискать другое решение. Но пока работаю так.

2024-10-07 17:42 UTC, Mixalight commented on src/test/java/StreamEventPak/StreamEvent.java
> +    public boolean equals(Object o) {
А, окей, вопрос снят тогда

2024-10-07 17:45 UTC, IrinaKrasnova commented on src/test/java/StreamEventPak/StreamEvent.java
> +    public int getId() {
У меня не работает Lombock. на созвоне с ментором не смогли оешить эту проблему. Он пообещал поискать другое решение. Но пока работаю так.

2024-10-08 09:21 UTC, Mixalight requested changes

2024-10-08 09:21 UTC, Mixalight commented on src/test/java/StreamEventPak/Main.java
> +        if (!eventByType.containsKey(streamEvent.getEventType())) {
Всё ещё актуально

2024-10-09 11:15 UTC, merged