Slava k bjs2 32402
CorporationX/god_bless pull request #11250
Opened 2024-10-04 17:50 UTC by 24slavaK

2024-10-05 20:05 UTC, MiraGlaceon requested changes

2024-10-05 20:05 UTC, MiraGlaceon commented on src/main/java/school/faang/task135/Main.java
> +    private static final Map<Student, Map<Subject, Integer>> STUDENTS_GRADE = new HashMap<>();
Заглавными буквами пишем только константы. У тебя мапы объявлены как final но по логике совсем не константные

2024-10-05 20:05 UTC, MiraGlaceon commented on src/main/java/school/faang/task135/Subject.java
> +@AllArgsConstructor
У тебя среди аннотаций есть лишняя, посмотри какие аннотации в себе объединяет аннотация @ Data

2024-10-05 20:05 UTC, MiraGlaceon commented on src/main/java/school/faang/task135/Student.java
> +@AllArgsConstructor
У тебя среди аннотаций есть лишняя, посмотри какие аннотации в себе объединяет аннотация @ Data

2024-10-05 20:05 UTC, MiraGlaceon commented on src/main/java/school/faang/task135/Main.java
> +    public void addNewStudent(Student student, HashMap<Subject, Integer> subject) {
1) Логику по работе со студентами вынеси в отдельный класс-сервис
2) subject не совсем отражает сущность параметра. По названию я думаю, что у нас класс Subject, а на самом деле мапа

2024-10-06 12:15 UTC, 24slavaK commented on src/main/java/school/faang/task135/Main.java
> +    public void addNewStudent(Student student, HashMap<Subject, Integer> subject) {
Не совсем понимаю какую логику выносить в отдельный класс-сервис там всего 2 метода и 1 цикл . Если эту логику выносить в отдельный класс то тогда логику из остальных методов тоже нужно вынести ? и тогда у нас в методах просто останется 1 вызов метода из класса-сервиса ?

2024-10-09 15:18 UTC, MiraGlaceon approved these changes

2025-01-17 21:26 UTC, closed without merging