Davidx5 bjs2 31375
CorporationX/god_bless pull request #11271
Opened 2024-10-04 20:01 UTC by davidx5x5

Спасибо за проверку

2024-10-04 21:19 UTC, jibulani requested changes
Хороший код, молодец!

Осталось сделать немного правок и можно будет смержить :)

2024-10-04 21:19 UTC, jibulani commented on src/test/java/Character.java
> +    public Character(int power, int intelligence, int skil) {
по условию:
_Сделать в Character два конструктора: один принимает только имя, а другой все доступные параметры, кроме здоровья_
а у тебя почему-то второй конструктор имя не принимает, надо поправить

2024-10-04 21:19 UTC, jibulani commented on src/test/java/Archer.java
> +    public Archer(int power, int skil,int intelligence,String name) {
тут можно только name принимать, ты же остальными параметрами не пользуешься, а задаешь заранее известные значения в конструктор класса-предка

2024-10-04 21:19 UTC, jibulani commented on src/test/java/Archer.java
> +    private String name;
тут не нужно, отнаследуется этот параметр от предка

2024-10-04 21:19 UTC, jibulani commented on src/test/java/Main.java
> +        Character Pasha = new Warrior(10, 18, 33, "Pasha");
Молодец, что используешь переменные общего типа Character, так обычно и делается :)

понимаю, что тут названия переменных это имена, но все-таки по конвенциям java-кода они должны быть с маленькой буквы в camelCase, например, в [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html#s5.2.5-non-constant-field-names)

2024-10-04 21:19 UTC, jibulani commented on src/test/java/Archer.java
> +public class Archer extends Character{
код с основной логикой нужно располагать в src/main/java + в отдельный пакет, который ему соответствует, в данном случае можно придумать название пакета по задаче

2024-10-04 21:19 UTC, jibulani commented on src/test/java/Archer.java
> +        health = health - character.power;
по условию атака лучника зависит от ловкости, а не от силы:
_в Archer персонаж наносит урон противнику в количестве собственной ловкости_

2024-10-04 21:19 UTC, jibulani commented on src/test/java/Warrior.java
> +
лучше не оставлять пустых строк в конце метода или класса, но не принципиально :)

2024-10-04 21:19 UTC, jibulani commented on src/test/java/Main.java
> +    public static void main(String[] args) {
молодец, что проверяешь работу кода!

если будет время и желание, можешь попробовать написать тест на JUnit для полноценной проверки, но это пока необязательно :)

2024-10-05 10:54 UTC, davidx5x5 commented on src/test/java/Character.java
> +    public Character(int power, int intelligence, int skil) {
спасибо,не доглядел

2024-10-05 10:58 UTC, davidx5x5 commented on src/test/java/Archer.java
> +public class Archer extends Character{
Ок учту в будущем, спасибо

2024-10-05 11:26 UTC, davidx5x5 commented on src/test/java/Archer.java
> +    public Archer(int power, int skil,int intelligence,String name) {
спасибо, немного передалал

2024-10-05 11:34 UTC, davidx5x5 commented on src/test/java/Main.java
> +        Character Pasha = new Warrior(10, 18, 33, "Pasha");
Спасибо учту

2024-10-05 11:34 UTC, davidx5x5 commented on src/test/java/Main.java
> +        Character Pasha = new Warrior(10, 18, 33, "Pasha");
учту

2024-10-05 11:37 UTC, davidx5x5 commented on src/test/java/Archer.java
> +        health = health - character.power;
да что то не обратил внимание, спасибо

2024-10-05 20:20 UTC, jibulani commented on src/test/java/Archer.java
> +public class Archer extends Character{
это важный момент, надо поправить в этом коммите

2024-10-05 20:28 UTC, jibulani requested changes
Осталось совсем небольшие правки сделать и все будет четко :)

2024-10-05 20:28 UTC, jibulani commented on src/test/java/Archer.java
> +        super(3,5,10,name);
по код-стайлу обычно принято везде после запятых пробелы ставить, некритично, но лучше поправить, чтобы код приятнее смотрелся

2024-10-05 20:28 UTC, jibulani commented on src/test/java/Warrior.java
> +        super(10,5, 3, name);
тоже пробелами везде раздели, пожалуйста

2024-10-05 21:11 UTC, jibulani commented on src/test/java/Archer.java
> +public class Archer extends Character{
вижу, что перенес в src/main/java, но отдельный пакет не создал, в следующий раз не забудь и про пакет

2024-10-05 21:14 UTC, jibulani approved these changes
все хорошо, но не забывай в будущем про пакеты и форматирование кода

2024-10-05 21:14 UTC, jibulani commented on src/main/java/Warrior.java
> +        health = health - character.power  ;
некритично, но тут какой-то лишний пробел перед `;`
постарайся в будущем внимательнее за этим следить, можно автоматически отформатировать весь код сочетанием клавиш Ctrl-Alt-L

2024-10-05 21:14 UTC, merged

2024-10-05 21:18 UTC, davidx5x5 commented on src/test/java/Archer.java
> +public class Archer extends Character{
Ок спасибо обязательно учту