Davidx5 bjs2 31805
CorporationX/god_bless pull request #11286
Opened 2024-10-04 22:25 UTC by davidx5x5

2024-10-05 19:56 UTC, Liberate520 reviewed
вы немножко неправильно работает с проектом. Сейчас вы пишите код в пакете для тестов. В основном проекте God_bless внесли правки и пакет с тестами совсем убрали и создали рабочую директорию, где и надо писать код. Подтяните обновления и перенесите в рабочую директорию ваши файлы

2024-10-05 19:56 UTC, Liberate520 commented on src/test/java/User.java
> +            throw new IllegalArgumentException("address can be only" + "London" + "New York" + "Amsterdam");
В текст исключения можно добавлять значение переменной, которая не прошла валидацию, тогда сообщение в исключении будет еще более информативно.

Валидацию можно вынести в отдельный метод, что должно улучшить читаемость кода

2024-10-05 19:56 UTC, Liberate520 commented on src/test/java/User.java
> +import java.util.*;
Старайтесь не скрывать импорты под звездочкой. Правильным стилем будет указывать каждый импорт, чтоб было точное понимание из какое библиотеки пришел класс. Ведь часто бывает, что в разных библиотеках существуют классы с одинаковым именем. Если звездочку ставит идея, то вам следует изменить ее настройки, чтобы она так не делала. По изменениям настройки есть инструкция на платформе

2024-10-06 15:18 UTC, Liberate520 commented on src/main/java/User.java
> +    public static final int AGE = 18;
Константы принято описывать выше полей класса

2024-10-06 15:18 UTC, Liberate520 commented on src/main/java/User.java
> +            throw new IllegalArgumentException(age + "can`t be less then 18");
В текст сообщения можно добавлять текущие значения переменной, которая не прошла проверку. Так понять причину ошибки, если она возникнет будет еще проще

2024-10-06 15:18 UTC, Liberate520 commented on src/main/java/User.java
> +            throw new IllegalArgumentException(age + "can`t be less then 18");
Все проверки можно объединить в один метод валидации. Тогда код станет еще красивее)

2024-10-06 20:48 UTC, Liberate520 commented on src/main/java/User.java
> +                throw new IllegalArgumentException("This is IllegalArgumentException");
Хорошо бы, чтобы исключение было более информативно. Представляешь ты ловишь такое исключение и ведь непонятно чего править. Лучше будет, если текст сообщения указывает на конкретную проблему, например, что неверно указан возраст

2024-10-06 20:48 UTC, Liberate520 commented on src/main/java/User.java
> +                throw new IllegalArgumentException("This is IllegalArgumentException");
В текст сообщения можно добавлять текущие значения переменной, которая не прошла проверку. Так понять причину ошибки, если она возникнет будет еще проще

2024-10-06 20:48 UTC, Liberate520 commented on src/main/java/User.java
> +                throw new IllegalArgumentException("This is IllegalArgumentException");
Все методы валидации можно вынести в отдельный метод. Так код станет еще чище

2024-10-15 19:40 UTC, mysosnovskaya requested changes

2024-10-15 19:40 UTC, mysosnovskaya commented on src/main/java/school/faang/createuser/User.java
> +    public boolean equals(Object o) {
Лучше пользоваться аннотациями от ломбока, чтобы не писать однотипный код

2024-10-15 19:40 UTC, mysosnovskaya commented on src/main/java/school/faang/createuser/User.java
> +        if (name == null || name.isEmpty()
Предыдущие комментарии по этой части неисправлены

2025-01-17 21:26 UTC, closed without merging