Задача Java HashMap: Считаем прогулы
CorporationX/god_bless pull request #11301
Opened 2024-10-05 10:11 UTC by YaKokin

1. Создал Student
2. Создал AccountingSystem - система учета студентов
3. Добавил метод добавления, поиска, удаления, печати.
4. Покрыл тестами

2024-10-05 14:56 UTC, mysosnovskaya requested changes

2024-10-05 14:56 UTC, mysosnovskaya commented on src/main/java/school/faang/count/skipping/AccountingSystem.java
> +    public Map<Course, List<Student>> transform(List<Student> students) {
Метод нужно переименовать, чтобы было понятно, что является результатом метода (во что трансформируется список студентов?)

2024-10-05 14:56 UTC, mysosnovskaya commented on src/main/java/school/faang/count/skipping/AccountingSystem.java
> +    private final Map<String, Integer> index = new HashMap<>();
На мой взгляд, этот индекс здесь является переусложнением. Программисты не любят решать проблемы, которые ещё не наступили (если этого явно не требуется в задаче). Может быть они никогда и не наступят? А на их решение сейчас можно потратить кучу времени. Поэтому самое лучшее решение - это простое решение. Если потом возникнут проблемы с производительностью, тогда вернемся к этому коду и оптимизируем его.
Можешь не удалять этот код, всё равно получилась хорошая практика) Но это так, на будущее.

2024-10-05 14:56 UTC, mysosnovskaya commented on src/test/java/ru/kraiush/BJS2_18616/count/skipping/AccountingSystemTest.java
> +public class AccountingSystemTest {
Как же круто, что ты пишешь тесты 👍 Молодец!

2024-10-05 14:56 UTC, mysosnovskaya commented on src/main/java/school/faang/count/skipping/AccountingSystem.java
> +        Map<Course, List<Student>> courseToStudents = transform(students);
А вот тут как раз можно было оптимизировать: пусть метод сразу принимает эту мапу courseToStudents. Тогда в main тебе достаточно будет один раз вызвать метод transform, запомнить его результат и дальше этот результат передавать в другие методы. А то сейчас получается, что для выполнения методов get и print приходится ещё раз выполнять ту же самую логику, которая скорее всего уже была выполнена

2024-10-06 13:38 UTC, YaKokin commented on src/main/java/school/faang/count/skipping/AccountingSystem.java
> +        Map<Course, List<Student>> courseToStudents = transform(students);
решил по-другому поправить. сделал поддержку такой мапы внутри AccountingSystem.
Если требовать в методе get мапу, то мы перекладываем на клиента ответственность не только предоставление нам такого экземпляра, но и за поддержание в мапе актуальных данных.
К тому же если у клиента есть эта мапа, он и без специального метода может вытянуть список студентов.

2024-10-06 21:18 UTC, mysosnovskaya requested changes

2024-10-06 21:18 UTC, mysosnovskaya commented on src/main/java/school/faang/count/skipping/AccountingSystem.java
> +        //удаление элемента
Комментарии из кода нужно удалить. Если что-то хочется прокомментировать, то нужно вынести это в отдельный приватный метод с понятным названием (deleteElement, updateIndex, updateCourseToStudentsMap)

2024-10-06 21:18 UTC, mysosnovskaya commented on src/main/java/school/faang/count/skipping/AccountingSystem.java
> +    private final Map<Course, List<Student>>  courseToStudents = new HashMap<>();
Пробельчик лишний)

2024-10-07 23:33 UTC, mysosnovskaya approved these changes

2024-10-07 23:33 UTC, merged