bjs2 32403 game of thrones
CorporationX/god_bless pull request #11319
Opened 2024-10-05 13:21 UTC by VovaBuzivskyi

2024-10-07 17:14 UTC, Mixalight requested changes

2024-10-07 17:14 UTC, Mixalight commented on src/main/java/school/faang/game_of_thrones_BJS2_32403/Main.java
> +@Data
Data - аннотация, которая тащит за собой очень много лишнего. Лучше использовать точечно нужные тебе аннотации

2024-10-07 17:14 UTC, Mixalight commented on src/main/java/school/faang/game_of_thrones_BJS2_32403/Main.java
> +
Лишняя строка

2024-10-07 17:14 UTC, Mixalight commented on src/main/java/school/faang/game_of_thrones_BJS2_32403/Main.java
> +        if (houses.containsKey(house.getName())) {
Лучше использовать методы мапы computeIfAbsent. Он позволяет добавить значение, если его ещё нет и в любом случае потом возвращает значение. Подробнее можно найти тут
https://www.baeldung.com/java-map-computeifabsent

2024-10-07 17:14 UTC, Mixalight commented on src/main/java/school/faang/game_of_thrones_BJS2_32403/Main.java
> +        if (!houses.containsKey(houseName)) {
Классно, что делаешь валидацию!

2024-10-07 17:14 UTC, Mixalight commented on src/test/java/ru/kraiush/BJS2_18616/PersonTest.java
> -package ru.kraiush.BJS2_18616;
Лучше всего работу с файлами, даже удаление, делать отдельным pr, чтобы потом понятнее было по истории что происходило и было легче чинить, если что-то ломается после коммитов

2024-10-07 17:14 UTC, Mixalight commented on src/main/java/school/faang/game_of_thrones_BJS2_32403/House.java
> +@Data
Комментарий ниже про дату актуален и тут

2024-10-07 19:59 UTC, VovaBuzivskyi commented on src/test/java/ru/kraiush/BJS2_18616/PersonTest.java
> -package ru.kraiush.BJS2_18616;
Сразу не понял что нужно переделать это. Думал это как замечание на будущее) Не знаю правильно ли я все сделал.

2024-10-08 09:14 UTC, Mixalight commented on src/test/java/ru/kraiush/BJS2_18616/PersonTest.java
> -package ru.kraiush.BJS2_18616;
Лучше просто убрать из этого pr удаление файла и сделать отдельным перед мёржем. Чтобы лишнего не было

2024-10-08 12:24 UTC, mighty-mhsl approved these changes

2024-10-08 12:24 UTC, merged