Считаем прогулы
CorporationX/god_bless pull request #11312
Opened 2024-10-05 11:35 UTC by bozhedar

2024-10-08 19:40 UTC, MiraGlaceon requested changes

2024-10-08 19:40 UTC, MiraGlaceon commented on src/main/java/school/faang/HashMap3/Main.java
> +
Не оставляй пустых пространств. Оставляй код чистым

2024-10-08 19:40 UTC, MiraGlaceon commented on src/main/java/school/faang/HashMap3/Student.java
> +    public int hashCode() {
Круто, что сам переопределил методы equals и hashCode, но ты уже используешь аннотацию @ Data. У тебя уже эти методы переопределены этой аннотацией. Нужно выбрать что-то одно, либо сам, либо аннотация

2024-10-08 19:40 UTC, MiraGlaceon commented on src/main/java/school/faang/HashMap3/Student.java
> +    public static HashMap<Student, List<Student>> groupedStudents(List<Student> list){
Класс Student оставь с минимальным содержимым. У тебя класс просто описывает сущность, а все операции и логику вынеси в отдельный класс, например, StudentService и перенеси туда логику по работе со студентами

2024-10-08 19:40 UTC, MiraGlaceon commented on src/main/java/school/faang/Student.java
> +public class Student {
Вот здесь у тебя в коммит попал лишний класс, убери его, если он лишний

2024-10-09 06:03 UTC, bozhedar commented on src/main/java/school/faang/HashMap3/Student.java
> +    public int hashCode() {
ещё на онбординге очень долго пытался решить эту задачу, тогда же в чате дали подсказку и стало понятно как это можно использовать

2024-10-09 15:09 UTC, MiraGlaceon approved these changes

2025-01-17 21:27 UTC, closed without merging