Naku-bjs2-33234 Ловим события
CorporationX/god_bless pull request #11322
Opened 2024-10-05 13:35 UTC by The-Naku

2024-10-07 17:37 UTC, Mixalight requested changes

2024-10-07 17:37 UTC, Mixalight commented on src/main/java/catchingEvents/StreamEvent.java
> +    public static int sum(int a, int b) {
А зачем нам эта функция и тест на неё?

2024-10-07 17:37 UTC, Mixalight commented on src/main/java/catchingEvents/StreamEvent.java
> + * ВОПРОС
Лучше в другое место
Либо в main и там же ты создашь мапы
Либо унести вообще в отдельный класс и в main просто создать его экземпляр и работать с ним

2024-10-07 17:37 UTC, Mixalight commented on src/main/java/catchingEvents/StreamEvent.java
> +    public static void addStreamEvent(Map<Integer, StreamEvent> streamEventMap,
Когда строка с аргументами в функцию выходит очень длинной, советую её разибивать так:
```
public static void func(
    Obj obj1,
    Obj obj2,
    Obj obj3
) {
```

2024-10-07 17:37 UTC, Mixalight commented on src/main/java/catchingEvents/StreamEvent.java
> + * ВОПРОС
В обоих случаях, что я описал, можно будет избавится от передачи мап каждый раз в функцию

2024-10-07 17:37 UTC, Mixalight commented on src/main/java/catchingEvents/StreamEvent.java
> +
Лишняя строка

2024-10-07 17:37 UTC, Mixalight commented on src/main/java/catchingEvents/StreamEvent.java
> +            if (id.equals(streamEvent.getId())) {
В твоём случае можно без двух циклов. Не складывать в доп массив и бежать по нему, а сразу с этим идти удалять 

А вообще, если ты получишь из одной мапы тип события по его id, а потом просто вытащишь массив из другой мапы по типу и сделаешь к нему remove - этого хватит

2024-10-07 17:37 UTC, Mixalight commented on src/main/java/catchingEvents/StreamEvent.java
> +
Лишняя строка

2024-10-07 17:37 UTC, Mixalight commented
Очень круто, что написаны тесты!

2024-10-08 05:11 UTC, The-Naku commented on src/main/java/catchingEvents/StreamEvent.java
> +            if (id.equals(streamEvent.getId())) {
к сожалению, не получается сократить код так, как итератор выбрасывает исключение при тестировании удаления потока. Потому что нельзя изменять саму коллекцию при обходе ее циклом из-за того, что у итератора ломается логика работы

2024-10-08 10:04 UTC, Mixalight commented on src/main/java/catchingEvents/StreamEvent.java
> +            if (id.equals(streamEvent.getId())) {
А зачем тебе обход цикл в принципе?
Ты вытаскиваешь ивент из мапы по айди в переменную и удаляешь одним действием из мапы которая id -> event
А дальше за одно действие из второй мапы ты вытаскиваешь нужный массив и применяешь к нему функцию remove

2024-10-08 10:26 UTC, The-Naku commented on src/main/java/catchingEvents/StreamEvent.java
> +            if (id.equals(streamEvent.getId())) {
Стыд и только...

2024-10-08 10:59 UTC, merged