Java HashMap: Библиотека Вестеросса
CorporationX/god_bless pull request #11325
Opened 2024-10-05 13:48 UTC by HoneyLegs

Так же добавил аннотацию @EqualsAndHashCode, но закомментировал её. Я правильно понимаю что мог вместо переопределения equals() и hashCode() её использовать?

2024-10-06 16:32 UTC, Mixalight commented
> Так же добавил аннотацию @EqualsAndHashCode, но закомментировал её. Я правильно понимаю что мог вместо переопределения equals() и hashCode() её использовать?

В целом да, но в рамках задачи лучше оставить твои функции, раз на этом сделали акцент в условии

2024-10-06 17:25 UTC, Mixalight requested changes

2024-10-06 17:25 UTC, Mixalight commented on src/test/java/BookTest.java
> +
Здесь и в нижнем тесте можно без пустых строк, они не улучшают читабельность кода

2024-10-06 17:25 UTC, Mixalight commented on src/test/java/BookTest.java
> +public class BookTest {
Круто, что написал тесты!

2024-10-06 17:25 UTC, Mixalight commented on src/main/java/school/faang/Main.java
> +        return library.getOrDefault(new Book(title, author, year), "");
Интересная задумка с пустой строкой по умолчанию
У тебя как раз тесты есть, так что было бы классно на это увидеть тест, но это по желанию

2024-10-10 19:57 UTC, HoneyLegs commented on src/test/java/BookTest.java
> +
Спасибо, поправил. Не стал убирать все пустые строки, но кажется получилось читабельнее, чем если бы убрал все пустые строки. Но если я не прав, то думаю вы дадите мне знать

2024-10-10 19:57 UTC, HoneyLegs commented on src/test/java/BookTest.java
> +public class BookTest {
Спасибо

2024-10-10 19:58 UTC, HoneyLegs commented on src/main/java/school/faang/Main.java
> +        return library.getOrDefault(new Book(title, author, year), "");
Спасибо, написал

2024-10-10 19:59 UTC, mighty-mhsl commented
Конфликты...

2024-10-11 19:18 UTC, HoneyLegs commented
Начальник, никаких конфликтов, я мирный человек)

2024-10-12 11:36 UTC, merged