Task Java HashMap: Считаем прогулы
CorporationX/god_bless pull request #11339
Opened 2024-10-05 15:10 UTC by SergeyZhitenev

2024-10-06 03:51 UTC, mysosnovskaya requested changes

2024-10-06 03:51 UTC, mysosnovskaya commented on src/main/java/school/faang/HashMaps/countingAbsenteeism/FacultyYear.java
> +    public boolean equals(Object o) {
А equals и hashcode, которые сгенерированы ломбоком (благодаря аннотации Data) не подходят? Если нет, то почему?

2024-10-06 03:51 UTC, mysosnovskaya commented on src/main/java/school/faang/HashMaps/countingAbsenteeism/Main.java
> +    public static Map<FacultyYear, List<Student>> getStudents(List<Student> studentList) {
Давай другое название методу придумаем. Странно в метод с названием  getStudents передавать список студентов (из названия ожидается, что метод должен вернуть студентов, но ничего не принимать)

2024-10-06 03:51 UTC, mysosnovskaya commented on src/main/java/school/faang/HashMaps/countingAbsenteeism/Main.java
> +        List<Student> studentsList = new ArrayList<>();
Будет оптимальнее пользоваться здесь той мапой, которую ты получаешь из метода getStudents

2024-10-06 03:51 UTC, mysosnovskaya commented on src/main/java/school/faang/HashMaps/countingAbsenteeism/Student.java
> +    public boolean equals(Object o) {
Аналогично, почему не подходит то, что генерируется через @Data?

2024-10-06 03:51 UTC, mysosnovskaya commented on src/main/java/school/faang/HashMaps/countingAbsenteeism/Main.java
> +        students.removeIf(s -> s.equals(student));
Очень круто, что ты используешь методы computeIfAbsent, removeIf - это тема следующего спринта, а ты идешь на опережение 👍

2024-10-06 08:56 UTC, SergeyZhitenev commented on src/main/java/school/faang/HashMaps/countingAbsenteeism/FacultyYear.java
> +    public boolean equals(Object o) {
Подходят, но, честно говоря, я забыл, что @Data генерирует еще и equals() с hashCode()

2024-10-06 21:00 UTC, mysosnovskaya requested changes

2024-10-06 21:00 UTC, mysosnovskaya commented on src/main/java/school/faang/HashMaps/countingAbsenteeism/Main.java
> +        return sortingStudentsByFacultyAndCourse(students).get(new FacultyYear(faculty, year));
Эту мапу лучше передать в метод, чем каждый раз при вызове searchStudents ещё раз группировать всех студентов в мапу и потом искать. Т.е. ты один раз в main эту мапу получаешь, а потом везде (searchStudents, printStudents) её передаешь и ей пользуешься

2024-10-07 23:33 UTC, mysosnovskaya approved these changes

2024-10-07 23:33 UTC, merged