Java HashMap: Поисковой мини-движок Google
CorporationX/god_bless pull request #11336
Opened 2024-10-05 15:07 UTC by allitov

2024-10-06 14:43 UTC, BobrAll requested changes
Код хороший, небольшие исправления

2024-10-06 14:43 UTC, BobrAll commented on src/main/java/school/faang/searchengine/Main.java
> +        for (String index : page.getContent().split(" ")) {
Посмотри как отработает на странице с контентом "first    second        third"

2024-10-06 14:43 UTC, BobrAll commented on src/main/java/school/faang/searchengine/Main.java
> +            if (!indexedPages.contains(page)) {
Гуд!

2024-10-06 14:43 UTC, BobrAll commented on src/main/java/school/faang/searchengine/Main.java
> +            }
Для разгрузки метода можно эту часть вынести в отдельный метод, так код будет легче восприниматься

2024-10-06 14:43 UTC, BobrAll commented on src/main/java/school/faang/searchengine/Main.java
> +    public static void removePageFromIndex(String url) {
Может быть кейс, когда у нас в результате работы этого метода ключ(ключи) ведет в пустые списки, такое по-хорошему бы устранить

2024-10-06 14:52 UTC, BobrAll commented
И еще при таком раскладе "мем" и "Мем" - разные слова. Хотя проводя поиск по слову "мем", мы хотим найти все мемы, даже если они с большой буквы

2024-10-08 06:31 UTC, allitov commented on src/main/java/school/faang/searchengine/Main.java
> +        for (String index : page.getContent().split(" ")) {
Точно, не учел такой вариант. Изменил регулярное выражение на "\\s+", чтобы удалять любые пробельные символы

2024-10-08 06:33 UTC, allitov commented on src/main/java/school/faang/searchengine/Main.java
> +            }
Вынес в приватный метод, действительно выглядит аккуратнее

2024-10-08 19:59 UTC, BobrAll reviewed
Принято

2024-10-08 19:59 UTC, merged