Sars bjs2 31324
CorporationX/god_bless pull request #11337
Opened 2024-10-05 15:07 UTC by sars33

2024-10-05 20:16 UTC, jibulani requested changes
Отличный код, даже не к чему придраться особенно :)
Осталось поправить пару замечаний и можно будет мержить

2024-10-05 20:16 UTC, jibulani commented on src/main/java/school/faang/Character.java
> +    public Character(int power, int agility, int intelligence) {
по условию, этот конструктор должен еще имя принимать:
_два конструктора: один принимает только имя, а другой все доступные параметры, кроме здоровья_

2024-10-05 20:16 UTC, jibulani commented on src/main/java/school/faang/Main.java
> +        Warrior warrior = new Warrior("Peter", 0, 0, 0);
Молодец, что проверяешь свой код!
Если есть время и желание, можешь попробовать еще написать тест на JUnit, но сейчас это необязательно :)

2024-10-06 21:31 UTC, jibulani requested changes
еще немного правок осталось и будет хорошо :)

2024-10-06 21:31 UTC, jibulani commented on src/main/java/school/faang/warrior/Archer.java
> +    public Archer(String name, int power, int agility, int intelligence) {
тут в параметрах должно быть только имя:
_для Archer сила всегда выставляется в 3, ловкость в 10, интеллект в 5. Имя передаётся извне._

2024-10-06 21:31 UTC, jibulani commented on src/main/java/school/faang/warrior/Archer.java
> +        super("Archer",3, 10, 5);
первым аргументом надо передать имя, тогда вторая строка `this.name = name` будет не нужна

2024-10-06 21:31 UTC, jibulani commented on src/main/java/school/faang/warrior/Warrior.java
> +public class Warrior extends school.faang.warrior.Character {
для класса Character не нужно указывать полный путь

2024-10-06 21:31 UTC, jibulani commented on src/main/java/school/faang/warrior/Warrior.java
> +    public Warrior(String name, int power, int agility, int intelligence) {
ситуация аналогична с Archer

2024-10-07 10:45 UTC, sars33 commented on src/main/java/school/faang/warrior/Warrior.java
> +public class Warrior extends school.faang.warrior.Character {
а это не я ставил полный путь это мне идея что-то предложила а я повелся

2024-10-08 09:57 UTC, jibulani requested changes
Хороший код, осталось немного поправить логику и можно будет мержить

2024-10-08 09:57 UTC, jibulani commented on src/main/java/school/faang/warrior/Archer.java
> +        character.health -= character.agility;
тут получается, что character занимается самовредительством :D
он же не сам себя атакует, а его атакует объект текущего класса, к которому можно обратиться через this и использовать его параметр ловкости: `this.agility` или просто `agility`

2024-10-08 09:57 UTC, jibulani commented on src/main/java/school/faang/warrior/Warrior.java
> +        character.health -= character.power;
та же ситуация, что и в Archer

2024-10-08 15:30 UTC, jibulani approved these changes
Все хорошо, мержим!

2024-10-08 15:30 UTC, merged