Naku-BJS2-32522 Считаем прогулы
CorporationX/god_bless pull request #11363
Opened 2024-10-05 18:03 UTC by The-Naku

2024-10-06 21:07 UTC, mysosnovskaya requested changes

2024-10-06 21:07 UTC, mysosnovskaya commented on src/main/java/countStudent/StudentOrganize.java
> +        int year = student.getYear();
Дублирование с тем, что выше. Надо бы от него избавиться

2024-10-06 21:07 UTC, mysosnovskaya commented on src/main/java/countStudent/StudentOrganize.java
> +    public List<Student> addStudent(Student student) {
Вообще задача была чуть о другом, там список студентов жил отдельно своей жизнью. Т.е. есть `List<Student>`, в него можно добавить студентов и из него можно удалить студентов по имени. А также из этого списка можно получить мапу. И уже с этой мапой работают методы поиска студентов и вывода на экран

2024-10-06 23:26 UTC, The-Naku commented on src/main/java/countStudent/StudentOrganize.java
> +    public List<Student> addStudent(Student student) {
Поняла. почему-то когда делала подумала, что надо сразу добавлять студента и в список и в мапу. Показалось что, администратор вуза стал бы делать этот список студентов сразу  по факультету и курсу

2024-10-07 23:34 UTC, mysosnovskaya approved these changes

2024-10-07 23:34 UTC, merged