BJS2-32496 программа для хранения студентов
CorporationX/god_bless pull request #11362
Opened 2024-10-05 18:00 UTC by evgen-backend-rostov

2024-10-05 22:06 UTC, jibulani requested changes
Очень хорошее решение!
Оставил несколько небольших замечаний, но в целом все круто!

2024-10-05 22:06 UTC, jibulani commented on src/main/java/school/faang/absenteeismCount/University.java
> +        while(iterator.hasNext()) {
понимаю, что функциональные интерфейсы еще не проходили, но если интересно, можешь глянуть, как можно упростить этот код с помощью метода списка `removeIf`
но если времени нет, такой вариант тоже ок :)

2024-10-05 22:06 UTC, jibulani commented on src/main/java/school/faang/absenteeismCount/University.java
> +        return null;
если из метода нечего возвращать, можно было его возвращаемый тип указать как void

2024-10-05 22:06 UTC, jibulani commented on src/main/java/school/faang/absenteeismCount/Student.java
> +public record Student(String name, String faculty, String year) {}
круто, что используешь `record`!

2024-10-06 10:06 UTC, evgen-backend-rostov commented on src/main/java/school/faang/absenteeismCount/University.java
> +        while(iterator.hasNext()) {
Привет! Спасибо на идею, я разобрался)

2024-10-06 10:07 UTC, evgen-backend-rostov commented on src/main/java/school/faang/absenteeismCount/University.java
> +            groups.putIfAbsent(student.faculty() + "-" + student.year(), new ArrayList<>());
мозг чуть поскрипел, но вроде въехал) По крайней мере, всё работает. Спасибо

2024-10-06 10:39 UTC, jibulani approved these changes
Все супер!

2024-10-06 10:39 UTC, merged