Task is done
CorporationX/god_bless pull request #11386
Opened 2024-10-05 20:18 UTC by Galay007

Task is done, please give a feed back.

2024-10-05 20:45 UTC, jibulani requested changes
Хороший код, осталось его немного подтюнить и будет вообще супер!

2024-10-05 20:45 UTC, jibulani commented on src/main/java/school/faang/Archer.java
> +
по условию задачи:
_3. Создать классы-наследники от Character: Warrior и Archer. Переопределить их конструкторы:
для Warrior сила всегда выставляется в 10, ловкость в 5, интеллект в 3. Имя передаётся извне;
для Archer сила всегда выставляется в 3, ловкость в 10, интеллект в 5. Имя передаётся извне._

то есть тут должен быть один конструктор, принимающий имя и задающий остальные параметры уже заранее известными значениями

2024-10-05 20:45 UTC, jibulani commented on src/main/java/school/faang/Archer.java
> +        int healthAfterAttach = archer.getHealth() - this.getAbility();
можно заменить более простой конструкцией:
character.health -= ability;

2024-10-05 20:45 UTC, jibulani commented on src/main/java/school/faang/Archer.java
> +    public void attack(Character archer) {
почему параметр метода называется archer, а не character, как у класса-родителя?

2024-10-05 20:45 UTC, jibulani commented on src/main/java/school/faang/Character.java
> +    public void setName(String name) {
по код-стайлу после объявления переменных обычно идут конструкторы и уже после них другие методы

2024-10-05 20:45 UTC, jibulani commented on src/main/java/school/faang/Character.java
> +    public Character(int strength, int ability, int intellect) {
по условию в этом конструкторе еще должно быть имя:
_2. Сделать в Character два конструктора: один принимает только имя, а другой все доступные параметры, кроме здоровья_

2024-10-05 20:45 UTC, jibulani commented on src/main/java/school/faang/Character.java
> +    public void setHealth(int health) {
в данном проекте подключен lombok, который позволяет не писать такие конструкции, а заменить их аннотациями `@Getter` `@Setter` `@ToString`
ну и там еще много других полезных аннотаций, позволяющих сэкономить время, рекомендую почитать про него и применить :)

2024-10-05 20:45 UTC, jibulani commented on src/main/java/school/faang/Character.java
> +    public String getString() {
обычно не пишут метод getString, а переопределяют метод toString из класса Object

2024-10-05 20:45 UTC, jibulani commented on src/main/java/school/faang/Main.java
> +        System.out.println("Archer after warrior attack update: " + archerFirst.getString() );
если бы переопределил toString(), не пришлось бы писать archerFirst.getString()

2024-10-05 20:45 UTC, jibulani commented on src/main/java/school/faang/Warrior.java
> +        super(strength, ability, intellect);
аналогичная ситуация с контроллером, что и в Archer

2024-10-05 20:45 UTC, jibulani commented on src/main/java/school/faang/Warrior.java
> +        int healthAfterAttach = archer.getHealth() - this.getStrength();
тоже надо поправить имя параметра и тело метода, как и в классе Archer

2024-10-05 20:45 UTC, jibulani commented on src/main/java/school/faang/Main.java
> +    public static void main(String[] args) {
молодец, что проверяешь работу кода!
если есть время и желание, можешь попробовать написать тесты на Junit, но на данном этапе это необязательно :)

2024-10-05 20:45 UTC, jibulani commented on src/main/java/school/faang/Archer.java
> +package school.faang;
рекомендую под каждую задачу еще дополнительно отдельный пакет создавать, но некритично :)

2024-10-06 10:25 UTC, Galay007 commented on src/main/java/school/faang/Character.java
> +    public void setName(String name) {
Буду знать, спасибо!

2024-10-06 13:13 UTC, jibulani requested changes
В целом все хорошо! Еще немного доработок и можно будет мержить :)

2024-10-06 13:13 UTC, jibulani commented on src/main/java/school/faang/abstraction_task/Archer.java
> +package school.faang.abstraction_task;
по [код-стайлу](https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names) имя пакета принято писать в нижнем регистре только буквами, если хочется разделить слова, можно сделать это через точки

2024-10-06 13:13 UTC, jibulani commented on src/main/java/school/faang/abstraction_task/Archer.java
> +    public Archer(String name, int strength, int ability, int intellect) {
тут этот конструктор не нужен, достаточно первого
_для Archer сила всегда выставляется в 3, ловкость в 10, интеллект в 5. Имя передаётся извне._

2024-10-06 13:13 UTC, jibulani commented on src/main/java/school/faang/abstraction_task/Archer.java
> +        intellect = 5;
можно все это сделать через вызов второго конструктора, тогда тут длина конструктора будет из одной строки

2024-10-06 13:13 UTC, jibulani commented on src/main/java/school/faang/abstraction_task/Main.java
> +        System.out.println("Archer after warrior attack update: " + archerFirst.toString() );
тут и ниже toString автоматом сработает, можно написать просто archerFirst

2024-10-06 13:13 UTC, jibulani commented on src/main/java/school/faang/abstraction_task/Main.java
> +        System.out.println("Archer after warrior attack update: " + archerFirst.toString() );
пробелы перед закрывающей скобкой обычно не ставят, можно применить автоформатирование через сочетание клавиш Ctrl-Alt-L

2024-10-06 13:13 UTC, jibulani commented on src/main/java/school/faang/abstraction_task/Warrior.java
> +    public Warrior(String name) {
та же ситуация с конструкторами, что и в Archer

2024-10-06 17:38 UTC, jibulani requested changes
класс Book откуда-то появился, для этой задачи он не нужен, видимо надо удалить, в остальном все хорошо, молодец!

2024-10-06 17:38 UTC, jibulani commented on src/main/java/school/faang/hashmap_library/Book.java
> +public class Book {
как оно тут оказалось?

2024-10-08 05:36 UTC, Galay007 commented on src/main/java/school/faang/hashmap_library/Book.java
> +public class Book {
Это я со сташем баловался... Удалю сейчас и запушу)

2024-10-08 10:02 UTC, jibulani approved these changes
Есть некритичное замечание, постарайся в будущем не оставлять неиспользуемые импорты, а по логике все ок, молодец!

2024-10-08 10:02 UTC, merged