Добавил новый пакет с классами согласно задаче. В Main классе реализо…
CorporationX/god_bless pull request #11387
Opened 2024-10-05 20:19 UTC by Kitamuro

…вал нужные методы

2024-10-06 07:38 UTC, BobrAll requested changes
Немного понаписывал тебе тут)
В целом код хороший, но нужно подправить

2024-10-06 07:38 UTC, BobrAll commented on src/main/java/school/faang/BJS232449/Main.java
> +    static Map<Map<String, Integer>, List<Student>> LIST_STUDENTS = new HashMap<>();
1) В UPPER_CASE обычно именуются константы
2) Переменная называется LIST_STUDENTS, а там по факту мапа
3) Даже если бы там был лист - это видно исходя из типа, поэтому слово list в любом случае можно опустить

2024-10-06 07:38 UTC, BobrAll commented on src/main/java/school/faang/BJS232449/Main.java
> +    static Map<Map<String, Integer>, List<Student>> addStudentsToList(List<Student> students) {
1) Метод называется addStudentToList, при этом добавляет в мапу
2) Он возвращает статическую переменную, которая и так доступна в пределах этого класса

2024-10-06 07:38 UTC, BobrAll commented on src/main/java/school/faang/BJS232449/Main.java
> +        LIST_STUDENTS.computeIfAbsent(key, v -> new ArrayList<>()).add(newStudent);
Четко!

2024-10-06 07:38 UTC, BobrAll commented on src/main/java/school/faang/BJS232449/Main.java
> +    static void getAll() {
Важный момент именования: исходя из имени функции человек должен получать полное представление о том, что внутри происходит. getAll() может возвращать как студентов, так и факультеты, например - нужно конкретизировать

2024-10-06 07:38 UTC, BobrAll commented on src/main/java/school/faang/BJS232449/Main.java
> +    static Map<Map<String, Integer>, List<Student>> LIST_STUDENTS = new HashMap<>();
Вообще мапы у нас как **переменной** быть не должно. Мы манипулируем только списком студентов, а мапа только возвращается из метода группировки

2024-10-06 17:09 UTC, BobrAll requested changes
В целом гуд, постарался подробнее написать про именование. Это правда очень важная тема, поэтому если вдруг что-то непонятно - пиши

2024-10-06 17:09 UTC, BobrAll commented on src/main/java/school/faang/BJS232449/Main.java
> +    static void addNewStudent(Student newStudent) {
Если убрать слово new из названия - поменяется ли смысл?

2024-10-06 17:09 UTC, BobrAll commented on src/main/java/school/faang/BJS232449/Main.java
> +            System.out.println("ADDED - " + newStudent);
У нас методы должны делать то, что написано в их названии. Метод addStudent() должен добавлять студента, но не принтить.

P.S. это не значит, что нужно давить принт в название) логикой и отображением должны заниматься разные методы. Т.к. у каждого метода должна быть 1 задача (это делает разработку и отладку легче). Хорошо описано в книге "Чистый код"

Остальных методов тоже касается)

2024-10-06 17:09 UTC, BobrAll commented on src/main/java/school/faang/BJS232449/Main.java
> +    static Map<Map<String, Integer>, List<Student>> groupStudentListToMap() {
Как тебе название groupStudentsByFacultyAndYear?
Хотел бы от тебя услышать сравнение этих имен - какое лучше и почему?

2024-10-06 18:24 UTC, Kitamuro commented on src/main/java/school/faang/BJS232449/Main.java
> +    static Map<Map<String, Integer>, List<Student>> groupStudentListToMap() {
groupStudentListToMap подразумевает что мы список студентов собираем в мапу, но об этом говорит возвращаемый тип. Поэтому слово map и list не совсем корректно.
groupStudentsByFacultyAndYear говорит о том что мы группируем студентов по факультету и году что как раз таки и делает метод. Следовательно второе наименование более корректно)

2024-10-06 18:32 UTC, Kitamuro commented on src/main/java/school/faang/BJS232449/Main.java
> +            System.out.println("ADDED - " + newStudent);
Полностью согласен! Вывод в консоль я для проверки делал чтобы тестовые данные сверить ну и работу методов посмотреть, и что-то решил что можно таки оставить.

2024-10-07 08:10 UTC, BobrAll commented on src/main/java/school/faang/BJS232449/Main.java
> +    static Map<Map<String, Integer>, List<Student>> groupStudentListToMap() {
Супер

2024-10-07 08:11 UTC, BobrAll commented
Теперь прям приятно смотреть, засчитываю

2024-10-07 08:12 UTC, merged