Alexeyzimin5726 bjs2 32438
CorporationX/god_bless pull request #11399
Opened 2024-10-05 22:03 UTC by Alexey-Zimin

см. пакет  doublecache_BJS2_32438. Также немного поигрался с тестами. В тестах, конечно есть, за что ухватиться в плане оптимизации.

2024-10-07 21:52 UTC, jibulani requested changes
Есть небольшие комментарии, но в целом все хорошо, молодец!

2024-10-07 21:52 UTC, jibulani commented on src/main/java/school/faang/doublecache_BJS2_32438/Student.java
> +package school.faang.doublecache_BJS2_32438;
предлагаю называть пакеты в соответствии с [код-стайлом](https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names)

2024-10-07 21:52 UTC, jibulani commented on src/main/java/school/faang/doublecache_BJS2_32438/Student.java
> +    int id;
обычно область видимости для полей класса ограничивают минимальной

2024-10-07 21:52 UTC, jibulani commented on src/main/java/school/faang/doublecache_BJS2_32438/Student.java
> +@NoArgsConstructor
нужен?

2024-10-07 21:52 UTC, jibulani commented on src/main/java/school/faang/doublecache_BJS2_32438/StudentRegistration.java
> +    private HashMap<Subject, List<Student>> subjectsMap = new HashMap<>();
переменные лучше объявить общим типом Map на случай, если мы захотим потом изменить реализацию с HashMap на какую-либо другую, чтобы в коде, использующего эту переменную ничего не сломалось

2024-10-07 21:52 UTC, jibulani commented on src/main/java/school/faang/doublecache_BJS2_32438/StudentRegistration.java
> +            if (subjectsMap.containsKey(subjectIntegerEntry.getKey())) {
кажется, эта проверка лишняя, по условию:
_добавление нового студента и его предметов с оценками_
не говорится, что предметы должны быть существующими, по идее возможна ситуация, когда появился новый студент с новым предметом
тут про понимание условия, в этом случае некритично, по реализации все ок

2024-10-07 21:52 UTC, jibulani commented on src/main/java/school/faang/doublecache_BJS2_32438/StudentRegistration.java
> +        studentsMap.remove(student);
из второй мапы тоже надо удалить, чтобы там не оставались неактуальные данные

2024-10-07 21:52 UTC, jibulani commented on src/main/java/school/faang/doublecache_BJS2_32438/StudentRegistration.java
> +            if (subjMap.containsKey(subject)) {
почему так? отсюда тоже надо удалить

2024-10-07 21:52 UTC, jibulani commented on src/main/java/school/faang/doublecache_BJS2_32438/Subject.java
> +public class Subject {
аналогичная ситуация с контроллером и полями, что и в Student

2024-10-07 21:52 UTC, jibulani commented on src/main/java/school/faang/doublecache_BJS2_32438/Test.java
> +        var subjects = new HashMap<Subject, Integer>(){{
по аналогии с `List.of()` существует `Map.of()`, тут можно его использовать для улучшения читаемости кода

2024-10-07 21:52 UTC, jibulani commented on src/test/java/school/faang/doublecache_BJS2_32438/StudentRegistrationTest.java
> +        var subjects = new HashMap<Subject, Integer>() {{
и тут `Map.of()`

2024-10-07 21:52 UTC, jibulani commented on src/test/java/school/faang/doublecache_BJS2_32438/StudentRegistrationTest.java
> +        var subjects = new HashMap<Subject, Integer>() {{
и дальше по тесту тоже можно заменить

2024-10-07 21:52 UTC, jibulani commented on src/test/java/school/faang/doublecache_BJS2_32438/StudentRegistrationTest.java
> +class StudentRegistrationTest {
мощно тестов накидал, красава!

2024-10-07 23:12 UTC, Alexey-Zimin commented on src/main/java/school/faang/doublecache_BJS2_32438/StudentRegistration.java
> +            if (subjectsMap.containsKey(subjectIntegerEntry.getKey())) {
оставил как есть, как раз это и имел ввиду: "когда появился новый студент с новым предметом"

2024-10-07 23:15 UTC, Alexey-Zimin commented on src/test/java/school/faang/doublecache_BJS2_32438/StudentRegistrationTest.java
> +class StudentRegistrationTest {
спасбо!

2024-10-07 23:27 UTC, Alexey-Zimin commented on src/main/java/school/faang/doublecache_BJS2_32438/StudentRegistration.java
> +        studentsMap.remove(student);
здесь имеется ввиду такая мысль, во второй мапе прописаны дисциплины, которые студент должен пройти. А в текущей мапе хранятся оценки студента по дисциплине. Оценку можно добавить, а можно по той или иной причине удалить, а дисциплина как была назначена так и останется

2024-10-07 23:38 UTC, Alexey-Zimin commented on src/main/java/school/faang/doublecache_BJS2_32438/StudentRegistration.java
> +            if (subjMap.containsKey(subject)) {
я реализовал такую логику, что нельзя далить дисциплину, если хотябы есть один студент и у него выставлена оценка по дисциплине

2024-10-08 08:19 UTC, jibulani approved these changes
все супер, в прод!

2024-10-08 08:19 UTC, merged