Java HashMap: Считаем прогулы
CorporationX/god_bless pull request #11395
Opened 2024-10-05 21:30 UTC by HoneyLegs

во время создания PR заметил что метод addStudentToList() в классе Main может выдать exception, если иммутабельный лист в него кинуть. Получается нужно каждый раз создавать новый?

2024-10-09 14:52 UTC, MiraGlaceon requested changes

2024-10-09 14:52 UTC, MiraGlaceon commented on src/main/java/school/faang/countabsences/Main.java
> +    public static Map<Group, List<Student>> getGroupedStudents(List<Student> students) {
Логику по работе со студентами можно вынести в класс-сервис. В main оставить только тестовые данные

2024-10-09 14:52 UTC, MiraGlaceon commented on src/test/java/school/faang/countabsences/MainTest.java
> +        assertEquals(groupedStudents.get(new Group("faculty_1", 1)), List.of(s1, s5));
List.of - вот этот метод у тебя может создавать иммутабельный лист, потому и ругается, замени просто на конструктор new ArrayList

2024-10-10 22:02 UTC, HoneyLegs commented on src/main/java/school/faang/countabsences/Main.java
> +    public static Map<Group, List<Student>> getGroupedStudents(List<Student> students) {
Сделал, спасибо

2024-10-10 22:07 UTC, HoneyLegs commented on src/test/java/school/faang/countabsences/MainTest.java
> +        assertEquals(groupedStudents.get(new Group("faculty_1", 1)), List.of(s1, s5));
Не здесь всё ок, не ругается, я в первом комментарии PR имел ввиду что в метод addStudentToList() в классе StudentService на вход подаётся список, в который мы добавляем Student, но этот List может быть иммутабельным, тогда выдаст exception. Нужно ли предполагать такие случаи и каждый раз создавать новый список на основе входного?

2024-10-11 15:34 UTC, MiraGlaceon commented on src/test/java/school/faang/countabsences/MainTest.java
> +        assertEquals(groupedStudents.get(new Group("faculty_1", 1)), List.of(s1, s5));
Нет, это нужно оставить на совести программиста, который использует твой код. Если он передает в твой список имутабельную мапу/лист, он должен понимать с чем работает. Такие случаи предусматривать не нужно

2025-01-17 21:27 UTC, closed without merging