BJS2-32655: Кэшируем, кэшируем
CorporationX/god_bless pull request #11405
Opened 2024-10-05 23:12 UTC by Sanasar1

2024-10-06 22:00 UTC, mysosnovskaya requested changes

2024-10-06 22:00 UTC, mysosnovskaya commented on src/main/java/bjs2_29014/Main.java
> +    public static void searchUnknownCityWeatherData(String city) {
Здесь тоже не нужно генерировать данные самостоятельно

2024-10-10 18:02 UTC, Sanasar1 commented on src/main/java/bjs2_29014/Main.java
> +        double temperature = new Random().nextDouble(-30.0, 45.0);
Я только заметил, что у меня еще и ошибка была в updateCityWeatherData в случае, когда у нас только один из параметров обновлялся.
Сейчас еще задумался о правильности генерации нового объекта WeatherData, когда мы хотим именно обновить данные о несуществующем городе. Может стоило просто отругаться, что такого города не существует, а не создавать новый? Как правильнее будет?

2024-10-10 20:19 UTC, mysosnovskaya commented on src/main/java/bjs2_29014/Main.java
> +        double temperature = new Random().nextDouble(-30.0, 45.0);
Нет, кэш не обязан знать всё. Если он чего-то не знает, то это не ошибка. Это значит нужно в него эти данные добавить и он будет знать. Вот если у нас, например, в базе данных не нашлось данных по заданному городу, то это повод сгенерировать ошибку. Ну а кэш не претендует на полноту данных, он и не для этого создан)

2024-10-10 20:19 UTC, mysosnovskaya approved these changes

2024-10-10 20:19 UTC, merged