Java HashMap: Библиотека Вестероса
CorporationX/god_bless pull request #11431
Opened 2024-10-06 08:22 UTC by lomuserg

2024-10-06 16:07 UTC, Mixalight requested changes

2024-10-06 16:07 UTC, Mixalight commented on src/main/java/school/faang/Main.java
> +    public static void getMap(Map<Book, String> map) {
Название не очень по существу, лучше print или printMap

2024-10-06 16:07 UTC, Mixalight commented on src/main/java/school/faang/Main.java
> +        for (Map.Entry<Book, String> entry : map.entrySet()) {
Ты можешь найти нужный элемент в мапе по ключу, не перебирая все её значения

2024-10-06 16:07 UTC, Mixalight commented on src/main/java/school/faang/Main.java
> +    public static String getBookFromKey(Map<Book, String> map, Book key) {
Не очень понятно, зачем тебе такое простое действие в отдельную функцию, тем более что ты его всего 1 раз используешь

2024-10-06 16:07 UTC, Mixalight commented on src/main/java/school/faang/Main.java
> +            if (entry.getKey().equals(book)) shelf += entry.getValue();
Даже если в if одна строка - стоит выделять её в {}

2024-10-07 10:22 UTC, mighty-mhsl commented
Конфликты нужно починить и смержим

2024-10-07 11:11 UTC, lomuserg commented
> Конфликты нужно починить и смержим

Смержил основную ветку в ветку с задачей, решил конфликты и запушил. Это правильно?)

2024-10-07 11:17 UTC, merged