Оптимизируем работу Дата-центра
CorporationX/god_bless pull request #11447
Opened 2024-10-06 10:52 UTC by YaKokin

Для реализации алгоритма распределения нагрузки добавил доп.поле loadIndex, чтобы равномерно распределять нагрузку в зависимости от максимальной переносимой нагрузки сервер.

Реализация LoadBalancingOptimizationStrategy равномерно распределяет нагрузку по серверам так, чтобы loadIndex у всех был одинаковый

Реализация EnergyEfficencyOptimizationStrategy уменьшает/увеличивает энергопотребление сервера в зависимости от его loadIndex

2024-10-08 00:30 UTC, mysosnovskaya requested changes

2024-10-08 00:30 UTC, mysosnovskaya commented on src/main/java/school/faang/data/center/DataCenter.java
> +    private List<Server> servers = new ArrayList<>();
Все методы по работе со списком серверов (add, remove, getTotalEnergyConsumption, allocateResources, releaseResources) лучше перенести сюда. Иначе нарушается принцип инкапсуляции.

2024-10-08 00:30 UTC, mysosnovskaya commented on src/main/java/school/faang/data/center/DataCenterService.java
> +    public DataCenterService(DataCenter dataCenter, OptimizationStrategy optimizationStrategy) {
А конструктор от ломбока не подходит?)

2024-10-08 00:30 UTC, mysosnovskaya commented on src/main/java/school/faang/data/center/DataCenterService.java
> +    private final DataCenter dataCenter;
Получается, что класс DataCenterService  умеет работать только с одним DataCenter. В таком случае логика этого класса не до конца ясна: почему всё то же самое мы не делаем внутри DataCenter? 
Я предлагаю сделать так, чтобы методы DataCenterService принимали DataCenter как параметр, к которому нужно применить данное действие. Класс DataCenterService можно воспринимать как "обслуживатель": ему дают датацентр и просят с ним что-то сделать. Потом дают другой датацентр и просят сделать с ним что-то другое. И так далее. Самое близкое из жизни - это автообслуживание, приезжают разные машины и с ними делают всякое разное =)

2024-10-08 00:30 UTC, mysosnovskaya commented on src/main/java/school/faang/data/center/DataCenterService.java
> +            } else if (server.getLoad() < requestLoad) {
if тут не нужен, других же ситуаций не может быть? Либо >= (это ты проверил в первом if), либо всё остальное (просто else)

2024-10-08 07:17 UTC, YaKokin commented on src/main/java/school/faang/data/center/DataCenterService.java
> +    private final DataCenter dataCenter;
Вау, очень крутой коммент! Я даже не подумал об этом.

2024-10-08 07:51 UTC, YaKokin commented on src/main/java/school/faang/data/center/DataCenter.java
> +    private List<Server> servers = new ArrayList<>();
Да, согласен. Только я предлагаю чуть по другому сделать. Если я сейчас перенесу все методы по обслуживанию дата центров в DataCenter, то тогда:
 - Не будет смысла держать у себя класс DataCenterService, который инкапсулирует логику обслуживания дата центров;
 - И раз в условии задачи мы договорились, что логику обслуживания мы держим в отдельном классе, то будем следовать этой договоренности.
В качестве альтернативы для решения проблемы инкапсуляции предлагаю в DataCenter явно определить геттер и сеттер.
1. Через геттер будет отдавать ссылку на копию оригинального объекта. И пусть вызывающий код делает с ним все, что захочет.
2. Дадим также возможность модифицировать список servers, но сделаем это через сеттер.
Таким образом мы всегда контролируем, что клиентский код делает с нашим состоянием, а значит соблюдаем инкапсуляцию.

2024-10-08 22:40 UTC, mysosnovskaya requested changes
Надо бы доразобраться с условием с распределением ответственности между DataCenter и DataCenterService) Я Сергею предложила в районе 22:00 завтра (в среду) быть на связи и созвониться, ты тоже можешь к этому времени подключаться в голосовой, если хочется обсудить голосом. Ну или в четверг на дейли)

2024-10-08 22:40 UTC, mysosnovskaya commented on src/main/java/school/faang/data/center/DataCenter.java
> +    private List<Server> servers = new ArrayList<>();
Мне не нравится идея с сеттером в таком виде, потому что кто угодно может перезаписать нам всё состояние серверов полностью. Захотят - вообще пустой список поставят и мы потеряем все данные. Очень небезопасно получается =) Обычно так не делают, а коллекции предпочитают делать final как раз по этой причине. 
А почему ты думаешь, что DataCenterService не будет иметь смысла? Он хранит в себе стратегию оптимизации; вызывает оптимизацию, когда это нужно; может записывать логи; и как ты написал - инкапсулирует логику обслуживания дата центров в одном месте. По-моему очень даже логично =) Можем ещё голосом обсудить

2024-10-10 20:20 UTC, mysosnovskaya approved these changes
Ура!)

2024-10-10 20:20 UTC, merged