BJS2-32410 Game of Thrones
CorporationX/god_bless pull request #11486
Opened 2024-10-06 14:32 UTC by waylaytessX

2024-10-07 18:28 UTC, Mixalight requested changes

2024-10-07 18:28 UTC, Mixalight commented on src/main/java/school/faang/GameOfThrones/Main.java
> +
Лишняя строка

2024-10-07 18:28 UTC, Mixalight commented on src/main/java/school/faang/GameOfThrones/Main.java
> +
Лишняя строка

2024-10-08 23:45 UTC, mighty-mhsl approved these changes

2024-10-08 23:45 UTC, merged