done
CorporationX/god_bless pull request #11491
Opened 2024-10-06 14:43 UTC by AndreyGustilev

2024-10-06 15:36 UTC, Mixalight requested changes

2024-10-06 15:36 UTC, Mixalight commented on src/main/java/school/faang/BJS2_33139/Book.java
> +import lombok.Data;
Лишний импорт

2024-10-06 15:36 UTC, Mixalight commented on src/main/java/school/faang/BJS2_33139/Book.java
> +import lombok.Data;
Если не путаю - intelij idea умеет убирать лишние импорты
Двойно shift и в меню написать слово import. Должен быть вариант optimize imports, что-то такое

2024-10-06 15:36 UTC, Mixalight commented on src/main/java/school/faang/BJS2_33139/Main.java
> +        if(library != null && book != null && address != null) {
Тут и в других if ниже - между if и открывающей скобкой пробел нужен

2024-10-06 15:36 UTC, Mixalight commented on src/main/java/school/faang/BJS2_33139/Main.java
> +
В начале и в конце(тут и в методах ниже) не нужны пустые строки
Между блоками кода тоже

2024-10-06 15:36 UTC, Mixalight commented on src/main/java/school/faang/BJS2_33139/Main.java
> +        if(library != null && book != null && address != null) {
Очень круто, что ты делаешь валидацию!

2024-10-06 15:36 UTC, Mixalight commented on src/main/java/school/faang/BJS2_33139/Main.java
> +
Лишние пустые строки тут и ниже
Иногда они помогают читать код, но здесь они по одной строке отделают и это неудобно

2024-10-06 15:36 UTC, Mixalight commented on src/main/java/school/faang/BJS2_33139/Book.java
> +    /*вопрос, а можно делать return в который запихивать сразу все проверки? Если нет, то почему?
В принципе можно
Но мне кажется что так код может читаться хуже + если у тебя полей побольше - там уже совсем непонятно и легко ошибиться можно будет

2024-10-06 17:43 UTC, AndreyGustilev commented on src/main/java/school/faang/BJS2_33139/Book.java
> +import lombok.Data;
убрал

2024-10-06 17:43 UTC, AndreyGustilev commented on src/main/java/school/faang/BJS2_33139/Main.java
> +        if(library != null && book != null && address != null) {
вставил

2024-10-06 17:50 UTC, AndreyGustilev commented on src/main/java/school/faang/BJS2_33139/Main.java
> +
поубирал

2024-10-07 10:23 UTC, mighty-mhsl approved these changes

2024-10-07 10:23 UTC, merged