BJS2-32441 программа для хранения студентов и их успеваемости по предметам
CorporationX/god_bless pull request #11496
Opened 2024-10-06 15:15 UTC by evgen-backend-rostov

2024-10-07 22:14 UTC, jibulani requested changes
Есть несколько замечаний, в целом все хорошо, молодец!

2024-10-07 22:14 UTC, jibulani commented on src/main/java/school/faang/doublecash/StudentsManagerService.java
> +            throw new IllegalArgumentException("Student with name " + student.getName() + " is absent in students list");
на мой взгляд не такая критичная ситуация, чтобы кидать ошибку :)
можно просто проверить наличие студента и если его нет, то завершить работу метода

2024-10-07 22:14 UTC, jibulani commented on src/main/java/school/faang/doublecash/StudentsManagerService.java
> +            value.removeIf((item) -> student.equals(item));
можно просто `value.remove(student)`

2024-10-07 22:14 UTC, jibulani commented on src/main/java/school/faang/doublecash/StudentsManagerService.java
> +    public void addNewSubjectWithStudentsList(Subject newSubject, List<Student> studentsList) {
по аналогии можно назвать попроще: `addSubjectWithStudents`

2024-10-07 22:14 UTC, jibulani commented on src/main/java/school/faang/doublecash/StudentsManagerService.java
> +            students.computeIfAbsent(student, s -> new HashMap<>()).put(newSubject, 0);
0 можно спутать с оценкой, обычно для явного указания, что значение отсутствует используется null

2024-10-07 22:14 UTC, jibulani commented on src/main/java/school/faang/doublecash/StudentsManagerService.java
> +        subjects.get(subject).removeIf((item) -> item.equals(student));
тоже можно через `remove(student)`

2024-10-08 13:18 UTC, evgen-backend-rostov commented on src/main/java/school/faang/doublecash/Main.java
> +package school.faang.doublecash;
🤑🤑🤑

2024-10-08 21:28 UTC, jibulani approved these changes
все супер, молодец!

2024-10-08 21:28 UTC, jibulani commented on src/main/java/school/faang/doublecashe/Main.java
> +package school.faang.doublecashe;
почти, все-таки правильно cache :)

2024-10-08 21:28 UTC, merged