Поисковой мини-движок Google
CorporationX/god_bless pull request #11497
Opened 2024-10-06 15:17 UTC by HoneyLegs

2024-10-09 14:14 UTC, MiraGlaceon requested changes

2024-10-09 14:14 UTC, MiraGlaceon commented on src/main/java/school/faang/googleminisearchengine/Main.java
> +    public static List<WebPage> searchByWord(String word) {
Логику по работе с веб-страницами лучше вынести в отдельный класс-сервис. В классе main можно оставить только тестовые данные и проверку запуска

2024-10-09 14:14 UTC, MiraGlaceon commented on src/main/java/school/faang/googleminisearchengine/Main.java
> +        return Stream.of(s.split(" "));
Слова могут разделяться несколькими пробелами, а так же содержать знаки пунктуации, типа запятых, точек и тд

2024-10-10 21:53 UTC, HoneyLegs commented on src/main/java/school/faang/googleminisearchengine/Main.java
> +    public static List<WebPage> searchByWord(String word) {
Спасибо, вынес в WebPageService. Так же утащил туда index как приватную переменную

2024-10-10 21:54 UTC, HoneyLegs commented on src/main/java/school/faang/googleminisearchengine/Main.java
> +        return Stream.of(s.split(" "));
Поправил

2024-10-11 15:08 UTC, MiraGlaceon approved these changes

2025-01-17 21:27 UTC, closed without merging