bjs2-31534 : Коллекционируем пользователей
CorporationX/god_bless pull request #11539
Opened 2024-10-07 06:19 UTC by lexsandr666

Создан класс User, реализован метод fingHobbyLovers для поиска пользователей у которых есть любимое хобби из списка. Создан класс Main для тестирования функционала.

2024-10-08 09:33 UTC, Mixalight requested changes

2024-10-08 09:33 UTC, Mixalight commented on src/main/java/tasks/bjs2_31534/User.java
> +    public String getName() {
Стандартные гетеры можно заменить аннотацией getter из lombock. А для information просто оставишь свой

2024-10-08 09:33 UTC, Mixalight commented on src/main/java/tasks/bjs2_31534/User.java
> +    private static int SEQUENCE_ID = 1;
Зачем это поле?

2024-10-08 09:33 UTC, Mixalight commented on src/main/java/tasks/bjs2_31534/User.java
> +import java.util.*;
Не стоит делать импорты всего, много лишнего. Делай только точечно нужные тебе, тем более ide в процессе написания кода сама импортит в большинстве случаев

2024-10-08 09:33 UTC, Mixalight commented on src/main/java/tasks/bjs2_31534/Main.java
> +    public static List<String> getHobbyLovers() {
Не очень понимаю, зачем тебе это выносить в отдельную функцию

2024-10-08 09:33 UTC, Mixalight commented on src/main/java/tasks/bjs2_31534/Main.java
> +
Лишняя строка

2024-10-08 09:33 UTC, Mixalight commented on src/main/java/tasks/bjs2_31534/Main.java
> +
Лишняя строка

2024-10-09 11:51 UTC, lexsandr666 commented
1) Добавил нотации Lombok : Data и AllArgsConstructor (
p.s. не хотел себя сразу нагружать всем, поэтому постепенно в последующих задачах стал использовать.
2) Удалил Sequence_id, перенёс заполнение идентификаторов в метод getUsers().
3) Упаковка всех импортов в '*' - Тут постарался IDE (форматирование), 
Сделал настройку code style и теперь каждый объект импорта хранится в отдельной строке.
4) getHobbyLovers() - Тут была логика такая, коль есть метод получения пользователей, по аналогии сделал метод получения хобби. Хотя согласен, метод однострочный, можно было сразу вынести значения в переменную. 
Удалил метод.
5) "Лишняя строка" - Не увидел в описании по codeStyle java что это какие-то ограничения. Даже пишут, что хорошая практика отступать одну строку от операторов (for, if, switch и т.д.) до оператора и после закрывающей скобки.
Строки удалил конечно, но не честно говоря не вижу здесь проблемы.

2024-10-10 19:48 UTC, merged

2024-10-10 19:48 UTC, SemyonKrivtsov approved these changes
Доброго времени суток! Проверил твою работу, отметил что можно улучшить. В остальном понравилось что код оформлен аккуратно, над код стайлом нужно еще поработать, это приходит с опытом. Успехов в обучении!