BJS2-32769 Считаем прогулы
CorporationX/god_bless pull request #11548
Opened 2024-10-07 09:42 UTC by Alex15265

1. Создайте класс Student, который будет содержать поля name (имя студента), faculty (факультет) и year (курс).

2. В классе Main, создайте список студентов и заполните его данными о студентах разных факультетов и курсов.

3. Создайте метод, который будет принимать список студентов и возвращать HashMap с ключом, состоящим из пары faculty и year, и значением — списком студентов, соответствующих данному факультету и курсу.

4. Реализуйте методы для следующих действий: добавление нового студента в список; удаление студента из списка по его имени, факультету и курсу; поиск всех студентов определённого факультета и курса; вывод списка всех студентов сгруппированных по факультетам и курсам

2024-10-08 20:49 UTC, jibulani requested changes
Хороший код, молодец!
Есть пара небольших мест для исправления

2024-10-08 20:49 UTC, jibulani commented on src/main/java/school/faang/truancy/Student.java
> +@AllArgsConstructor
если сделать поля финальными, то эта аннотация не потребуется

2024-10-08 20:49 UTC, jibulani commented on src/main/java/school/faang/truancy/Main.java
> +                .collect(Collectors.groupingBy(student -> new StudentGrouper(student.getFaculty(), student.getYear())));
круто, что изучаешь наперед и используешь еще не пройденные темы!

2024-10-08 20:49 UTC, jibulani commented on src/main/java/school/faang/truancy/StudentGrouper.java
> +public record StudentGrouper(String faculty, int year) {
круто, что используешь возможности java 17!
кстати, можно было обойтись без дополнительного класса и использовать String или Pair вместо него, но некритично :)

2024-10-08 20:49 UTC, jibulani commented on src/main/java/school/faang/truancy/Main.java
> +        return STUDENTS.stream()
можно упростить - получить мапу из метода groupStudents и далее по нужному ключу сразу получить список студентов через get

2024-10-09 11:39 UTC, Alex15265 commented on src/main/java/school/faang/truancy/StudentGrouper.java
> +public record StudentGrouper(String faculty, int year) {
про Pair посмотрел, но ее выпилили из jdk после 11, теперь отдельно искать надо)
про String не понял, может ты имел в виду Entry?) переписал с ними, тоже позволяют избавиться от лишнего класса

2024-10-09 22:13 UTC, jibulani commented on src/main/java/school/faang/truancy/StudentGrouper.java
> +public record StudentGrouper(String faculty, int year) {
обычный String имел в виду, то есть ключ в виде: "Факультет1 2000"

2024-10-09 22:22 UTC, jibulani approved these changes
все супер, молодец!

2024-10-09 22:22 UTC, merged