BJS2-34754
CorporationX/god_bless pull request #11662
Opened 2024-10-08 03:31 UTC by RuslanGabd

2024-10-09 19:16 UTC, jibulani requested changes
есть несколько комментариев на упрощение кода, а в целом все супер, молодец!

2024-10-09 19:16 UTC, jibulani commented on src/main/java/school/faang/filtersforinstagram/FilterProcessor.java
> +        return (image) -> function2.apply(function1.apply(image));
рабочий вариант, но можно упростить с помощью функции andThen, который делает по сути то же самое

2024-10-09 19:16 UTC, jibulani commented on src/main/java/school/faang/filtersforinstagram/FilterProcessor.java
> +        Image result = new Image("AfterFilter", "This image after filter");
если переменная не используется, ее лучше удалить

2024-10-09 19:16 UTC, jibulani commented on src/main/java/school/faang/filtersforinstagram/Image.java
> +public class Image {
можно превратить класс в record, тогда ломбоковские аннотации вообще не потребуются

2024-10-10 08:39 UTC, RuslanGabd commented on src/main/java/school/faang/filtersforinstagram/Image.java
> +public class Image {
thank you, very useful

2024-10-10 20:38 UTC, jibulani approved these changes
супер!

2024-10-10 20:38 UTC, merged