added UserActionAnalyzer
CorporationX/god_bless pull request #11674
Opened 2024-10-08 07:01 UTC by abdddev

2024-10-08 09:46 UTC, Mixalight requested changes

2024-10-08 09:46 UTC, Mixalight commented on src/main/java/school/faang/user/action/analyzer/UserAction.java
> +@Data
Data - аннотация, которая тащит за собой очень много лишнего. Лучше использовать точечно нужные тебе аннотации

2024-10-08 09:46 UTC, Mixalight commented on src/test/java/school/faang/user/action/analyzer/UserActionAnalyzerTest.java
> +
Лишняя строка

2024-10-09 05:07 UTC, abdddev commented
Спасибо, поправил
И там немного папки еще перенес

2024-10-11 07:46 UTC, SemyonKrivtsov approved these changes
Доброго времени суток! Проверил твою работу, вижу что ты сделал колоссальное усилие на исправление. Это круто! Критичных замечаний нет. Успехов в обучении!

2024-10-11 07:46 UTC, merged