Alex15265 bjs2 32666
CorporationX/god_bless pull request #11699
Opened 2024-10-08 11:00 UTC by Alex15265

1. Создайте класс Student, который будет содержать поля id (ID студента) и name (имя студента).
2. Создайте класс Subject, который будет содержать поля id (ID предмета) и name (название предмета).
3. В классе Main, создайте две HashMap: Первая HashMap с ключом типа Student и значением типа Map<Subject, Integer> (список предметов и оценок студента по каждому предмету); Вторая HashMap с ключом типа Subject и значением типа List<Student> (список студентов, изучающих данный предмет).
4. Реализуйте методы для следующих действий: добавление нового студента и его предметов с оценками; добавление нового предмета для существующего студента с оценкой; удаление студента и его предметов с оценками; вывод списка всех студентов и их оценок по предметам.
5. Реализуйте методы для работы со второй HashMap: добавление нового предмета и списка студентов, изучающих его; добавление студента к существующему предмету; удаление студента из предмета; вывод списка всех предметов и студентов, изучающих их.

2024-10-08 21:36 UTC, jibulani requested changes
все хорошо, но есть пара небольших замечаний

2024-10-08 21:36 UTC, jibulani commented on src/main/java/school/faang/doublecache/Main.java
> +        Map<Subject, Integer> alexGrades = new HashMap<>() {{
если мапа не будет меняться, можно создать ее с помощью `Map.of()`

2024-10-08 21:36 UTC, jibulani commented on src/main/java/school/faang/doublecache/Main.java
> +                addNewSubjectWithGrade(student, subject, 0);
лучше использовать null для обозначения отсутствия значения
в случае с 0 можно подумать, что у студента такая оценка

2024-10-08 21:36 UTC, jibulani commented on src/main/java/school/faang/doublecache/Student.java
> +@AllArgsConstructor
если сделать поля final, то эта аннотация не потребуется

2024-10-08 21:36 UTC, jibulani commented on src/main/java/school/faang/doublecache/Subject.java
> +@AllArgsConstructor
аналогично, как и в студенте

2024-10-09 10:55 UTC, Alex15265 commented on src/main/java/school/faang/doublecache/Main.java
> +        Map<Subject, Integer> alexGrades = new HashMap<>() {{
ага, это я знаю...она imuteable в таком случае
но т.к есть метод, который добавляет предмет студенту - сделал так, иначе unsupportedOperationException

2024-10-09 11:01 UTC, Alex15265 commented on src/main/java/school/faang/doublecache/Student.java
> +@AllArgsConstructor
точно, @Data же включает в себя @RequiredArgsConstructor

2024-10-09 11:05 UTC, Alex15265 commented on src/main/java/school/faang/doublecache/Student.java
> +@AllArgsConstructor
idea подсказала в таком случае использовать record

2024-10-09 22:31 UTC, jibulani commented on src/main/java/school/faang/doublecache/Student.java
> +@AllArgsConstructor
да, с record вообще супер!

2024-10-09 22:33 UTC, jibulani approved these changes
все супер, молодец!

2024-10-09 22:33 UTC, merged