Решение задачи "Абстракция, абстракция!"
CorporationX/god_bless pull request #11702
Opened 2024-10-08 11:22 UTC by DaniyarDostiev

Решение задачи "Абстракция, абстракция!"

2024-10-08 20:49 UTC, MiraGlaceon requested changes

2024-10-08 20:49 UTC, MiraGlaceon commented on src/main/java/abstractiontask/Character.java
> +    protected String name;
У тебя класс содержит переменные состояния объекта. Применяй принцип инкапсуляции, нужен другой модификатор доступа

2024-10-08 20:49 UTC, MiraGlaceon commented on src/main/java/abstractiontask/Archer.java
> +        character.health -= this.dexterity;
У тебя объект character приходит из вне. Как думаешь, правильно ли будет обращаться к его переменной через точку? В таких ситуация нужно использовать геттеры или сеттеры

2024-10-08 20:49 UTC, MiraGlaceon commented on src/main/java/abstractiontask/Character.java
> +    public abstract void attack(Character character);
Попробуй этот метод вынести в интерфейс и назвать его, например, Attackable и навесить на класс Character. Напиши как минимум одну причину почему это может быть удобно. Подсказку можно найти здесь: https://javarush.com/groups/posts/polimorfizm-v-java

2024-10-09 07:52 UTC, DaniyarDostiev commented on src/main/java/abstractiontask/Character.java
> +    protected String name;
![image](https://github.com/user-attachments/assets/bcd4a420-6509-4563-a000-2dd0269c1803)
В последнем пункте подсказок указано, что нужно использовать protected как я понял это сделано для того, чтобы в классах наследниках, обращаться к полям через ключевое слово this, а не через геттеры и сеттеры.
Как в итоге сделать правильно?

2024-10-09 07:54 UTC, DaniyarDostiev commented on src/main/java/abstractiontask/Archer.java
> +        character.health -= this.dexterity;
Исправил, обращаюсь к полю внешнего объекта через геттеры и сеттеры, но для того чтобы можно было обращаться к силе или ловкости того кто атакует через this, оставил protected в суперклассе.

2024-10-09 08:37 UTC, DaniyarDostiev commented on src/main/java/abstractiontask/Character.java
> +    public abstract void attack(Character character);
Попробовал вынести абстрактный метод в отдельный интерфейс, кажется получилось не очень, но это максимум до чего я додумался, чтобы сильно не переписывать остальной код в задаче.

Из плюсов использования интерфейсов, которые мне приходят в голову:
В будущем у нас могут появиться не только персонажи, а например животные, растения, которые тоже смогут наносить урон, и вообще все подобного рода сущности, можно будет объединить в группу, связанную интерфейсом Attackable, что в свою очередь позволит нам использовать все плюсы полиморфизма, т.е. мы сможем работать с огромным кол-вом разнообразных объектов как с представителями одного типа, что сделает наш код более гибким и модульным.

Моя реализация, конечно страдает, потому ни один из перечисленных плюсов интерфейсов, я нормально не использую, ибо если в будущем у нас появятся другие сущности способные атаковать они смогут бить только персонажей, а не всех представителей Attackable, но я это сделал потому в реализациях метода attack(), я обращаюсь к полям, передаваемого объекта, которые не объявлены в интерфейсе, если я не ошибаюсь я бы не смог это сделать потому что все поля в интерфейсе константы, а мне нужно их задать и регулярно менять.
Ну и в методе main я использую объекты Character, а не Attackable, потому что мне нужно проверить, что урон прошел для этого я вывожу их здоровье через getHealth(), которого в интерфейсе опять же нет.

2024-10-09 13:27 UTC, MiraGlaceon commented on src/main/java/abstractiontask/Character.java
> +    protected String name;
Раз так посоветовали, то для этой задачи принимаю

2024-10-09 13:27 UTC, MiraGlaceon approved these changes

2025-01-17 21:27 UTC, closed without merging