https://faang-school.atlassian.net/browse/BJS2-34143
CorporationX/god_bless pull request #11724
Opened 2024-10-08 13:31 UTC by 0Miha0

2024-10-09 20:48 UTC, BobrAll requested changes
Касательно темы задачи - все решено правильно. Пару правок по организации кода

2024-10-09 20:48 UTC, BobrAll commented on src/main/java/school/faang/Lambda/BJS2_34143/Droid.java
> +        return encryptor.process(message, 26 - key);
Это хорошо прям)

2024-10-09 20:48 UTC, BobrAll commented on src/main/java/school/faang/Lambda/BJS2_34143/Droid.java
> +        System.out.println(name + " отправляет зашифрованное сообщение: " + encryptedMessage);
Лишние принты лучше не вставлять в код. Может получится ситуация, когда человек вызывает метод, но при этом не рассчитывает на какой-либо вывод информации. Другое дело логирование, но System.out.println() - это не логирование :) Поэтому просто лучше удалить (и в других местах тоже)

2024-10-09 20:48 UTC, BobrAll commented on src/main/java/school/faang/Lambda/BJS2_34143/Droid.java
> +        return result.toString();
Хорошее решение: продуманное и лаконичное. Только константу забыл именовать

2024-10-11 05:03 UTC, 0Miha0 commented on src/main/java/school/faang/Lambda/BJS2_34143/Droid.java
> +        return result.toString();
Скажу честно, не сам написал,  с помощью бота написал, по итогу не особо понимаю как оно работает на 17 и 18 строке)

2024-10-11 08:49 UTC, BobrAll commented on src/main/java/school/faang/Lambda/BJS2_34143/Droid.java
> +        return result.toString();
Тебя за это ругать никто не будет, конечно. Но только зачем?)
Смысл-то выполнения задач в прокачке себя, а не просто в выполнении. Тут важен сам процесс. Лучше их решить меньше, но при этом извлечь для себя что-то полезное

2024-10-11 08:50 UTC, BobrAll reviewed
Принято

2024-10-11 08:59 UTC, merged