Секреты дроидов
CorporationX/god_bless pull request #11722
Opened 2024-10-08 13:04 UTC by YaKokin

Сделал немного по другому.
Вместо создания лямбы прямо в методе шифрования добавил возможность передавать экземпляр DroidMessageEncryptor для encryptor и decryptor прямо в конструктор дроида. Таким образом можно определять дроидов с разными алгоритмами шифрования и дешифрования

2024-10-08 22:10 UTC, mysosnovskaya requested changes

2024-10-08 22:10 UTC, mysosnovskaya commented on src/main/java/school/faang/droid/secrets/Droid.java
> +        System.out.println(name + " получил расшифрованное сообщение: " + decryptedMessage);
Я надеюсь, это всё только для дебага =)))

2024-10-08 22:10 UTC, mysosnovskaya commented on src/main/java/school/faang/droid/secrets/Droid.java
> +    private DroidMessageEncryptor encryptor;
Эта идея с полями мне нравится

2024-10-08 22:10 UTC, mysosnovskaya commented on src/main/java/school/faang/droid/secrets/Main.java
> +            for (int i = 0; i < chars.length; i++) {
Давай подумаем, как можно не дублировать код с тем, что у тебя сейчас в encryptor

2024-10-10 20:30 UTC, mysosnovskaya requested changes

2024-10-10 20:30 UTC, mysosnovskaya commented on src/main/java/school/faang/droid/secrets/Main.java
> +                        (base) -> (char) ((currentChar - base - shift + 26) % 26 + base));
Найди разницу между: 
` (base) -> (char) ((currentChar - base + shift) % 26 + base)`
и 
` (base) -> (char) ((currentChar - base - shift + 26) % 26 + base)`
Тогда и лямбда не понадобится, будет ещё проще) Но практика с функциональными интерфейсами хорошая получилась))

2024-10-10 21:19 UTC, YaKokin commented on src/main/java/school/faang/droid/secrets/Main.java
> +                        (base) -> (char) ((currentChar - base - shift + 26) % 26 + base));
я все же разобрался))
круто придумала

2024-10-14 17:15 UTC, merged