Построим CSV
CorporationX/god_bless pull request #11738
Opened 2024-10-08 14:45 UTC by YaKokin

2024-10-08 22:17 UTC, mysosnovskaya requested changes

2024-10-08 22:17 UTC, mysosnovskaya commented on src/main/java/school/faang/csv/CsvConverter.java
> +        MatrixJoiner<String> matrixJoiner = (matrix) -> {
Давай реализации этих joiner-ов вынесем в отдельные приватные методы

2024-10-08 22:17 UTC, mysosnovskaya commented on src/main/java/school/faang/csv/CsvConverter.java
> +            StringBuilder sb = new StringBuilder();
Было бы ещё хорошо убедиться, что list не пустой

2024-10-08 22:17 UTC, mysosnovskaya commented on src/main/java/school/faang/csv/CsvConverter.java
> +            sb.append(list.get(list.size() - 1));
Сложновато получилось, может быть сделаем наоборот: цикл будем начинать с запятой, а затем добавлять элемент. Ну, и ещё кое-что я не сказала, но это на подумать) Т.е. идея в том, чтобы это проблему с запятой решать не в конце, а в начале

2024-10-10 15:40 UTC, YaKokin commented on src/main/java/school/faang/csv/CsvConverter.java
> +            sb.append(list.get(list.size() - 1));
мне кажется, я понял)
круто, что решила почеленджить меня и заставила самого подумать

2024-10-10 20:09 UTC, mysosnovskaya requested changes

2024-10-10 20:09 UTC, mysosnovskaya commented on src/main/java/school/faang/csv/CsvConverter.java
> +        for (int i = 0; i < vector.size(); i++) {
Почему i = 0? Ты ведь уже выше добавил vector.get(0), повторно это делать не нужно

2024-10-10 20:09 UTC, mysosnovskaya commented on src/main/java/school/faang/csv/CsvConverter.java
> +            sb.append(",");
А так всё равно запятая в конце будет. Нужно ещё совсем немного подумать) Если что - приходи за подсказкой

2024-10-10 20:22 UTC, YaKokin commented on src/main/java/school/faang/csv/CsvConverter.java
> +            sb.append(",");
блин, поменять забыл местами)
сейчас точно все ок

2024-10-10 20:28 UTC, mysosnovskaya approved these changes

2024-10-10 20:28 UTC, merged