Evseenko bjs2 34159
CorporationX/god_bless pull request #11749
Opened 2024-10-08 15:11 UTC by dimaevseenko

BJS2-34159

2024-10-10 18:53 UTC, MiraGlaceon requested changes

2024-10-13 14:55 UTC, dimaevseenko commented on src/main/java/dima/evseenko/droid/EncryptorUtil.java
> +            return null;
Поправил

2024-10-13 14:55 UTC, dimaevseenko commented on src/main/java/dima/evseenko/droid/DroidMessageHandler.java
> +public interface DroidMessageHandler {
Поправил

2024-10-13 22:15 UTC, MiraGlaceon approved these changes

2024-10-14 10:30 UTC, merged