BJS2-34803 реализация фильтров для Инсты
CorporationX/god_bless pull request #11791
Opened 2024-10-08 20:06 UTC by evgen-backend-rostov

2024-10-09 19:25 UTC, jibulani requested changes
есть несколько небольших замечаний, в целом все круто, молодец!

2024-10-09 19:25 UTC, jibulani commented on src/main/java/school/faang/instafilters/FilterProcessor.java
> +        return (Image image) -> filterTwo.apply(filterOne.apply(image));
можно упростить, используя функцию andThen, которая делает то же самое

2024-10-09 19:25 UTC, jibulani commented on src/main/java/school/faang/instafilters/Filters.java
> +    public static final Map<String, Function<Image, Image>> FILTERS = new HashMap<>(Map.of(
зачем одновременно new HashMap и Map.of?
должно быть достаточно только Map.of

2024-10-09 19:25 UTC, jibulani commented on src/main/java/school/faang/instafilters/Image.java
> +public class Image {
можно превратить этот класс в record, тогда не потребуются ломбоковские аннотации

2024-10-11 10:39 UTC, evgen-backend-rostov commented on src/main/java/school/faang/instafilters/FilterProcessor.java
> +        return (Image image) -> filterTwo.apply(filterOne.apply(image));
Привет! Спасибо) Не знал о таком

2024-10-11 10:44 UTC, evgen-backend-rostov commented on src/main/java/school/faang/instafilters/Filters.java
> +    public static final Map<String, Function<Image, Image>> FILTERS = new HashMap<>(Map.of(
блин, это сранно, но сейчас только с Map.of работает 🤔 Я так изначально и сделал, но прога ошибку выдавала, и смог пофиксить только обернув в new HashMap<>. Магия, не иначе 😁

2024-10-11 20:11 UTC, jibulani commented on src/main/java/school/faang/instafilters/Filters.java
> +    public static final Map<String, Function<Image, Image>> FILTERS = new HashMap<>(Map.of(
Map.of() - неизменяемая мапа, возможно ты ее сначала пытался менять и поэтому не работало
Но скорее всего все-таки магия :D

2024-10-11 20:13 UTC, jibulani approved these changes
оставил некритичное замечание, а так все хорошо, поэтому аппрув 👍

2024-10-11 20:13 UTC, jibulani commented on src/main/java/school/faang/instafilters/FilterProcessor.java
> +        return (Image image) -> filterOne.andThen(filterTwo).apply(image);
можно еще проще: `return filterOne.andThen(filterTwo)`
некритично

2024-10-11 20:13 UTC, merged