added inventory manager test
CorporationX/god_bless pull request #11812
Opened 2024-10-09 06:23 UTC by abdddev

2024-10-09 19:34 UTC, BobrAll requested changes
Код приятно читать прям. Чуть правок

2024-10-09 19:34 UTC, BobrAll commented on src/main/java/school/faang/lord/of/the/rings/Character.java
> +@RequiredArgsConstructor
Сразу видно человека, пишущего на спринге

2024-10-09 19:34 UTC, BobrAll commented on src/main/java/school/faang/lord/of/the/rings/InventoryManager.java
> +        character.setInventory(updatedInventory);
Хорошо, что через стримы пробуешь делать, но конструировать весь список заново для обновления одного элемента звучит сильно расточительно. А если в листе будет 1000 объектов?

2024-10-09 19:34 UTC, BobrAll commented on src/test/java/school/faang/lord/of/the/rings/InventoryManagerTest.java
> +    void addItemAndUpdateValueTest() {
В целом я понимаю откуда такое название теста. Но сама цель этого теста - проверить функцию обновления, добавление элемента - это лишь шаг для её достижения. Поэтому мы можем в названии оставить лишь цель. 

Надеюсь понятно объяснил)

2024-10-10 03:10 UTC, abdddev commented on src/test/java/school/faang/lord/of/the/rings/InventoryManagerTest.java
> +    void addItemAndUpdateValueTest() {
Да, четко
Спасибо)

2024-10-10 08:21 UTC, merged