BSJ2-31505
CorporationX/god_bless pull request #11825
Opened 2024-10-09 08:46 UTC by dmbnetqa

2024-10-09 21:48 UTC, jibulani requested changes
в целом хороший код, молодец!
есть несколько моментов, которые нужно исправить

2024-10-09 21:48 UTC, jibulani commented on src/main/java/school/faang/Archer.java
> +        health -= agility;
тут получается, что лучник атакует сам себя и себе снижает здоровье в зависимости от своей ловкости, а надо, чтобы снижал здоровью персонажу, которого передали в аргументе метода

2024-10-09 21:48 UTC, jibulani commented on src/main/java/school/faang/Archer.java
> +package school.faang;
лучше под каждую задачу делать отдельный пакет, чтобы код не лежал потом в одной куче + меньше проблем с мержем будет

2024-10-09 21:48 UTC, jibulani commented on src/main/java/school/faang/Character.java
> +    private boolean validData(String name, int strength, int agility, int intellect) {
обычно такие методы возвращают true, если данные валидны, а у тебя наоборот, рекомендую переделать
и конструктор будет проще выглядеть:
`if (validData(...) {`

2024-10-09 21:48 UTC, jibulani commented on src/main/java/school/faang/Main.java
> +        Archer archer = new Archer("archer");
тут можно использовать переменные типа Character

чем более обобщенный код, тем проще с ним единообразно работать, если нет необходимости указывать более точный тип, то лучше и не указывать

Например, это нужно для того, чтобы можно было без проблем объявить переменную типом Character и вызывать общие для типа методы:
```
Character warrior = new Warrior("warrior");
Character archer = new Archer("archer");
warrior.attack(archer);
```

Или другой более показательный пример, у нас есть список персонажей, нам неважно, воины они или лучники, и мы хотим, чтобы каждый из списка персонажей смог атаковать цель, тогда можно написать такой код:
```
List characters = List.of(new Warrior("warrior"), new Archer("archer"));
Character target = new Warrior("target");
characters.forEach(character -> character.attack(target));
```

2024-10-09 21:48 UTC, jibulani commented on src/main/java/school/faang/Warrior.java
> +        health -= strength;
аналогичная ситуация, что и в Archer

2024-10-09 21:48 UTC, jibulani commented on src/main/java/school/faang/Character.java
> +        if (!(validData(name, strength, agility, intellect))) {
круто, что учитываешь правильность данных!

2024-10-11 21:40 UTC, jibulani requested changes
часть замечаний не учтена, надо исправить

2024-10-11 21:40 UTC, jibulani commented on src/main/java/school/faang/abstraction/Archer.java
> +        health -= agility;
получается, Archer атакует сам себя, а не character-а, которого передали в качестве аргумента

2024-10-11 21:40 UTC, jibulani commented on src/main/java/school/faang/abstraction/Warrior.java
> +        health -= strength;
и тут

2024-10-11 21:40 UTC, jibulani commented on src/main/java/school/faang/Character.java
> +    private boolean validData(String name, int strength, int agility, int intellect) {
если не переделал, то не помечай, как resolved, можешь написать, почему не стал переделывать

2024-10-11 21:40 UTC, jibulani commented on src/main/java/school/faang/Archer.java
> +        health -= agility;
ошибка осталась

2024-10-11 21:40 UTC, jibulani commented on src/main/java/school/faang/Main.java
> +        Archer archer = new Archer("archer");
не исправлено

2024-10-11 21:40 UTC, jibulani commented on src/main/java/school/faang/Warrior.java
> +        health -= strength;
не исправлено

2024-10-11 21:45 UTC, dmbnetqa commented on src/main/java/school/faang/Archer.java
> +        health -= agility;
пардон. ошибка. сейчас переделаю.

2024-10-11 21:49 UTC, dmbnetqa commented on src/main/java/school/faang/Character.java
> +    private boolean validData(String name, int strength, int agility, int intellect) {
с гитом пока на Вы.

2024-10-11 22:46 UTC, jibulani approved these changes
теперь все супер, молодец!

2024-10-11 22:47 UTC, merged