BJS2-34177
CorporationX/god_bless pull request #11855
Opened 2024-10-09 13:06 UTC by Macacin

Метод на шифрацию конечно отвал башки, частично сделал сам, частично подсмотрел в доп.материалах, плюс от себя немного изменил то как происходит шифрация/дешифрация цифр.

2024-10-09 18:31 UTC, mysosnovskaya requested changes

2024-10-09 18:31 UTC, mysosnovskaya commented on src/test/java/DroidEncryptorTest.java
> +    // тест на sendMessage решил не делать, тк уже протестил все что входит в его функционал, и не хотелось делать костыли
Ок

2024-10-09 18:31 UTC, mysosnovskaya commented on src/main/java/school/faang/droidSecrets/Droid.java
> +            StringBuilder decryptedMessage = new StringBuilder();
Очень уж похож код на предыдущий метод. Подумаем, как можно обобщить?)

2024-10-09 21:31 UTC, Macacin commented
Сидел очень долго и ломал голову как реализовать сдвиг цифр если не использовать две разные реализации шифрации/дешифрации, в итоге не допер и просто удалил эту часть. Хз как еще обобщить можно было)

2024-10-10 20:00 UTC, mysosnovskaya approved these changes

2024-10-10 20:00 UTC, mysosnovskaya commented on src/main/java/school/faang/droidSecrets/Droid.java
> +        return encryptMessage(message, -key + 26);
`26 - key` может лучше?)
А вообще это то самое решение, которое я хотела) Ведь разница действительно только в ключе и отлично, что ты это заметил 👍 Это избавило от дублирования кода полностью. Супер!)

2024-10-10 20:00 UTC, merged