Removed student's code -  Java HashMap: Ловим события
CorporationX/god_bless pull request #11865
Opened 2024-10-09 14:03 UTC by SerUKalinin

2024-10-11 12:04 UTC, Mixalight requested changes

2024-10-11 12:04 UTC, Mixalight commented on src/main/java/school/faang/BJS2_33283/Main.java
> +        if (event != null) {
Такая лесенка из if выглядит не очень читабельно
Можно сделать противоположные условия и выход
Например первое - null, тогда кидаем исключение или просто return
Тогда у тебя везде не будет больше глубины чем 1

2024-10-12 14:02 UTC, SerUKalinin commented on src/main/java/school/faang/BJS2_33283/Main.java
> +        if (event != null) {
вроде готово.

2024-10-12 14:03 UTC, SerUKalinin commented on src/main/java/school/faang/BJS2_33283/StreamEvent.java
> +@Data
убрал аннотацию @data и сделал 
@ToString
@Getter
@AllArgsConstructor
@EqualsAndHashCode

нет разницы в какой последовательности?

2024-10-12 16:16 UTC, SemyonKrivtsov commented on src/main/java/school/faang/BJS2_33283/StreamEvent.java
> +@Data
Лучше выставлять по смысле от глобальных к более тонким по настройке. Так лучше последние два поставить вначале для читаемости.

2024-10-12 16:16 UTC, SemyonKrivtsov approved these changes
Доброго времени суток! Проверил твою работу, смотри комментарии, критичных замечаний нет - ты молодец! Код оформлен аккуратно, было удобно по нему вести навигацию. Успехов в обучении!

2024-10-12 16:16 UTC, merged