Google search - BJS2-32990
CorporationX/god_bless pull request #11895
Opened 2024-10-09 17:42 UTC by Galay007

2024-10-09 22:10 UTC, jibulani requested changes
есть несколько замечаний, перемудрил с двумя мапами, но в целом все хорошо :)

2024-10-09 22:10 UTC, jibulani commented on src/main/java/school/faang/google/Main.java
> +        for (String word : toDeleteWordsContent) {
все-таки дополнительная мапа urlMap выглядит избыточным усложнением
можно пройтись по мапе indexWebPagesMap таким образом:
`for (Map.Entry<String, List<WebPage>> entry : indexWebPagesMap.entrySet()) `
и дальше из entry брать значение и с помощью метода removeIf удалять нужные страницы

2024-10-09 22:10 UTC, jibulani commented on src/main/java/school/faang/google/WebPage.java
> +public class WebPage {
в java 17 есть recoed - если на него переписать, код намного лаконичнее будет и не потребуются аннотации

2024-10-09 22:10 UTC, jibulani commented on src/main/java/school/faang/google/Main.java
> +    static Map<String, List<WebPage>> indexWebPagesMap = new HashMap<>();
я бы назвал indexedWebPages, по типу и так понятно, что это Map
некритично

2024-10-09 22:10 UTC, jibulani commented on src/main/java/school/faang/google/Main.java
> +        return indexWebPagesMap.get(index);
тут тогда тоже надо будет ключ в нижний регистр перевести для поиска

2024-10-09 22:10 UTC, jibulani commented on src/main/java/school/faang/google/Main.java
> +    public static List<WebPage> searchByIndex(String index) {
я бы назвал просто search, а по каким данным будет поиск можно понять из аргументов метода
некритично

2024-10-09 22:10 UTC, jibulani commented on src/main/java/school/faang/google/Main.java
> +    public static void deleteIndexByUrl(String url) {
аналогичные замечания по именованию

2024-10-11 05:23 UTC, Galay007 commented on src/main/java/school/faang/google/WebPage.java
> +public class WebPage {
Действительно крутая вещь. Спасибо!

2024-10-11 06:02 UTC, Galay007 commented on src/main/java/school/faang/google/Main.java
> +        for (String word : toDeleteWordsContent) {
Почему-то жалуется, что не может применить removeif в List((
![image](https://github.com/user-attachments/assets/c5073a67-ce6c-4603-808d-b74d57a0da72)

2024-10-12 21:02 UTC, jibulani requested changes
осталось побороть removeIf и в прод!

2024-10-12 21:02 UTC, jibulani commented on src/main/java/school/faang/google/Main.java
> +            //entry.getValue().removeif(condition) Я не знаю, почему она жалуется?
круто, что разобрался с работой функциональных интерфейсов!
обычно в подобных ситуациях их не выносят в отдельную переменную, а сразу используют:
`entry.getValue().removeIf(web -> web.url().contains(url));`

2024-10-21 08:11 UTC, merged