BJS2-34224: Секреты дроидов
CorporationX/god_bless pull request #11922
Opened 2024-10-09 19:43 UTC by Sanasar1

2024-10-10 20:05 UTC, mysosnovskaya requested changes

2024-10-10 20:05 UTC, mysosnovskaya commented on src/main/java/bjs2_33397/Droid.java
> +                    encryptedMessage.append((char) ((c - base - key) % 26 + base));
Если `key` будет больше разницы `c - base`, то здесь получим отрицательное значение. Будет ли это корректно работать?

2024-10-10 20:05 UTC, mysosnovskaya commented on src/main/java/bjs2_33397/Droid.java
> +            StringBuilder encryptedMessage = new StringBuilder();
Очень уж этот код похож на то, что выше. Нужно придумать, как избавиться от дублирования

2024-10-12 13:44 UTC, Sanasar1 commented on src/main/java/bjs2_33397/Droid.java
> +            StringBuilder encryptedMessage = new StringBuilder();
Подскажи, пожалуйста, правильно ли я сделал? Голова приболела со всей этой абстракцией ахаха, надо видимо руки набить, чтобы привыкнуть к ней)

2024-10-14 17:15 UTC, merged