Создан абстрактный класс "Character" и два подкласса "Warrior" и "Arc…
CorporationX/god_bless pull request #12010
Opened 2024-10-10 15:39 UTC by Amanyaz

Создан абстрактный класс "Character" и два подкласса "Warrior" и "Archer", которые наследуют класс "Character". Созданы все поля и конструкторы, указанные в задании. Реализован метод attack и выполнена вся логика, описанная в задании. Кроме того, создан класс TestCharacter для тестирования. Созданы новые объекты классов Warrior и Archer, использован метод "attack", а также выведено на экран оставшееся здоровье (здоровье) каждого персонажа. В моем коде я использовал модификаторы доступа private для всех полей, поэтому все манипуляции с полями производились через геттеры и сеттеры.v

2024-10-10 20:29 UTC, jibulani commented
> Создан абстрактный класс "Character" и два подкласса "Warrior" и "Archer", которые наследуют класс "Character". Созданы все поля и конструкторы, указанные в задании. Реализован метод attack и выполнена вся логика, описанная в задании. Кроме того, создан класс TestCharacter для тестирования. Созданы новые объекты классов Warrior и Archer, использован метод "attack", а также выведено на экран оставшееся здоровье (здоровье) каждого персонажа. В моем коде я использовал модификаторы доступа private для всех полей, поэтому все манипуляции с полями производились через геттеры и сеттеры.v

можно не расписывать так подробно :)

2024-10-10 20:35 UTC, jibulani requested changes
Есть пара замечаний, в целом хороший код, молодец!

2024-10-10 20:35 UTC, jibulani commented on src/main/java/school/faang/BJS2_31387/Archer.java
> +package school.faang.BJS2_31387;
обычно по [код-стайлу](https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names) пакеты именуют в нижнем регистре латинскими буквами, можно назвать по смыслу задачи abstraction

2024-10-10 20:35 UTC, jibulani commented on src/main/java/school/faang/BJS2_31387/Archer.java
> +        super(name);
у тебя же есть второй конструктор, который принимает все эти параметры, используй лучше его

2024-10-10 20:35 UTC, jibulani commented on src/main/java/school/faang/BJS2_31387/Character.java
> +    private int sila;
не надо именовать параметры транслитом, лучше просто словом на английском

2024-10-10 20:35 UTC, jibulani commented on src/main/java/school/faang/BJS2_31387/TestCharacter.java
> +    public static void main(String[] args) {
Молодец, что проверяешь работу кода!

2024-10-10 20:35 UTC, jibulani commented on src/main/java/school/faang/BJS2_31387/Warrior.java
> +        super(name);
аналогичная ситуация, что и в Archer

2024-10-11 13:54 UTC, Amanyaz commented on src/main/java/school/faang/BJS2_31387/Archer.java
> +package school.faang.BJS2_31387;
Изменения выполнены.

2024-10-11 13:55 UTC, Amanyaz commented on src/main/java/school/faang/BJS2_31387/Character.java
> +    private int sila;
Изменения выполнены.

2024-10-11 13:55 UTC, Amanyaz commented on src/main/java/school/faang/BJS2_31387/TestCharacter.java
> +    public static void main(String[] args) {
thanks

2024-10-11 13:56 UTC, Amanyaz commented on src/main/java/school/faang/BJS2_31387/Warrior.java
> +        super(name);
Согласно заданию, только имя должно вводиться пользователем, остальные поля должны иметь одинаковые (заданные) значения. Если использовать конструктор со всеми полями, то все поля придется вводить извне, что противоречит условиям задания. Поэтому я использовал конструктор, который имеет только имя в качестве параметра. Если я что-то неправильно понял и есть способ использовать другой конструктор, пожалуйста, объясните и дайте подсказку.                                        

Остальные изменения выполнены.

2024-10-11 20:26 UTC, jibulani commented on src/main/java/school/faang/BJS2_31387/Archer.java
> +        super(name);
все правильно, ты извне получаешь только name, который в аргументе конструктора, остальные поля задаешь заранее известными значениями, но чтобы создать объект, проще воспользоваться другим конструктором суперкласса: super(name, 3, 10, 5) - суть будет такой же, как сделал ты, просто в более лаконичной форме

2024-10-11 20:27 UTC, jibulani commented on src/main/java/school/faang/BJS2_31387/Warrior.java
> +        super(name);
такая же ситуация, как в Archer, исправь, пожалуйста

2024-10-11 20:28 UTC, jibulani requested changes
осталось чуть-чуть и в прод!

2024-10-12 04:47 UTC, Amanyaz commented on src/main/java/school/faang/BJS2_31387/Archer.java
> +        super(name);
Готово!

2024-10-12 04:48 UTC, Amanyaz commented on src/main/java/school/faang/BJS2_31387/Warrior.java
> +        super(name);
Готово!

2024-10-12 20:38 UTC, jibulani approved these changes
супер, молодец!

2024-10-12 20:38 UTC, merged