Библиотека Вестероса
CorporationX/god_bless pull request #12057
Opened 2024-10-11 06:38 UTC by m1kk1mouse

Попытаюсь исправить проблемы

2024-10-11 06:40 UTC, m1kk1mouse commented
Проблемы решены

2024-10-11 09:44 UTC, starkoracia commented on src/main/java/abstraction/abstraction/Archer.java
> +        character.setHealth(character.getHealth() - character.getDexterity());
У тебя здесь лучник бьет сам себя =)

2024-10-11 09:44 UTC, starkoracia commented on src/main/java/abstraction/abstraction/Warrior.java
> +        character.setHealth(character.getHealth() - character.getStrength());
И здесь тоже самое)

2024-10-11 10:52 UTC, m1kk1mouse commented
Прошу не обращать внимание на остальные файлы, сильно натупил в структуре проекта и коммитах, вернул все в нормальное состояние.

2024-10-11 11:08 UTC, Mixalight commented
Про лишние файлы - лучше унести их в отдельный pr, чтобы не было путаницы. Здесь ещё может не так важно, но когда вы пишите один проект командой - вам может быть очень неудобно с такими pr

2024-10-11 11:14 UTC, Mixalight requested changes

2024-10-11 11:14 UTC, Mixalight commented on src/main/java/vesterosse/library/Book.java
> +        if (this == o) return true;
Даже если в теле if одна строка - всё равно нужно выделять фигурными скобками

2024-10-11 11:14 UTC, Mixalight commented on src/main/java/vesterosse/library/Book.java
> +        if (o == null || getClass() != o.getClass()) return false;
Аналогично комментарию выше

2024-10-11 11:14 UTC, Mixalight commented on src/main/java/vesterosse/library/Book.java
> +    public static void addBook(Map<Book, String> map, Book book, String place) {
Лучше унести эти методы отсюда
Здесь класс книга, а методы относятся не совсем к нему, скорее к хранилищу книг
Так что либо сделать в main, либо отдельным классом, который будет аналог библиотеки

2024-10-12 11:36 UTC, mighty-mhsl approved these changes

2024-10-12 11:36 UTC, merged