Потренируем StreamAPI 2
CorporationX/god_bless pull request #12117
Opened 2024-10-11 15:26 UTC by m1rroxxx

2024-10-14 22:24 UTC, MiraGlaceon requested changes

2024-10-14 22:24 UTC, MiraGlaceon commented on src/main/java/school/faang/practiceStreamApi2/ListOperation.java
> +    return IntStream.range(0, numbers.size())
Немного усложнил. Попробуй найти решение, где не нужно использовать фильтер по nonNull

2024-10-15 00:11 UTC, m1rroxxx commented on src/main/java/school/faang/practiceStreamApi2/ListOperation.java
> +    return IntStream.range(0, numbers.size())
вообще идея была в том что бы избавиться от вложенного цикла и ршить за O(n), просто в задании подразумевается использовать стримы, и вот как то так получилось)

2024-10-15 00:30 UTC, m1rroxxx commented on src/main/java/school/faang/practiceStreamApi2/ListOperation.java
> +    return IntStream.range(0, numbers.size())
хотя может ты имеел ввиду вот это))

2024-10-15 18:50 UTC, MiraGlaceon approved these changes

2025-01-17 21:28 UTC, closed without merging