исправление ошибок
CorporationX/god_bless pull request #12266
Opened 2024-10-12 15:18 UTC by vifravl

2024-10-15 19:19 UTC, mysosnovskaya requested changes

2024-10-15 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/User.java
> +        if (
Лучше было бы каждый параметр провалидировать отдельно, чтобы была конкретная ошибка. Т.к. сейчас пользователю будет неясно, в каком именно значении он ошибся

2024-10-15 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/User.java
> +                        age < 18 ||
18 тоже было бы хорошо вынести в константы)

2024-10-16 05:26 UTC, vifravl commented on src/main/java/school/faang/User.java
> +                        age < 18 ||
Код исправил, но в джире самой таски нет, чтобы на rewie снова отправить

2025-01-17 21:29 UTC, closed without merging