StreamAPI2
CorporationX/god_bless pull request #12522
Opened 2024-10-14 17:48 UTC by bozhedar

2024-10-15 19:22 UTC, MiraGlaceon requested changes

2024-10-15 19:22 UTC, MiraGlaceon commented on src/main/java/school/faang/StreamAPI2/ListOperations.java
> +        Set<List<Integer>> pairs = new HashSet<>();
Тут создаешь коллекцию коллекции. Чтобы не путаться и поступать более правильно, создай класс, который будет содержать пару значений

2024-10-15 19:22 UTC, MiraGlaceon commented on src/main/java/school/faang/StreamAPI2/ListOperations.java
> +                .peek(Collections::sort)
Ознакомься с методом peek в документации. Ты для каждого элемента в массиве будешь вызывать сортировку. Сортировать элементы можно другим путем, а peek это как forEach, но не завершает поток

2024-10-17 18:20 UTC, MiraGlaceon requested changes

2024-10-17 18:20 UTC, MiraGlaceon commented on src/main/java/school/faang/StreamAPI2/ListOperations.java
> +    public static Map<Integer, Integer> UniquePairs(List<Integer> numbers, int sum){
Лучше все же создать класс для хранения пары чисел. Потому что у тебя мапа может перезаписать значение по ключу. Представь ты получишь две пары (3, 5) и (3, 7), тогда в мапу попадет что-то одно, потому что значение по ключу "3" обновится

2024-10-17 18:20 UTC, MiraGlaceon commented on src/main/java/school/faang/StreamAPI2/ListOperations.java
> +                .filter(num -> numbers.contains(sum - num))
Тут ты можешь сделать все в одном фильтре объединив условия оператором && или ||

2024-10-18 09:56 UTC, bozhedar commented on src/main/java/school/faang/StreamAPI2/ListOperations.java
> +        Set<List<Integer>> pairs = new HashSet<>();
не понимаю зачем создавать отдельный класс для этого, начал пытаться в итоге больше запутался

2024-10-18 10:00 UTC, bozhedar commented on src/main/java/school/faang/StreamAPI2/ListOperations.java
> +                .peek(Collections::sort)
наверно вы намекаете на метод sort, но я тоже не разобрался как тут его применить, .peek(Collections::sort) тут помогает от дубликатов пар избавиться по типу [1, 6] и [6, 1]

2024-10-18 19:37 UTC, MiraGlaceon commented on src/main/java/school/faang/StreamAPI2/ListOperations.java
> +        Set<List<Integer>> pairs = new HashSet<>();
Давай попробуем подробнее описать ситуацию. 
Я имел ввиду вот что:
Создаем класс, например, Pair:
public class Pair {
  private int x; // первое число
  private int y; // второе число
  
  public Pair(int x, int y) {
    this.x = x;
    this.y = y;
  }
}

Потом в твоем коде делаем следующее:
numbers.stream()
                .filter(n -> numberSet.contains(sum - n))
                .map(n -> new Pair(n, sum - n))
                .peek(Collections::sort).collect(Collectors.toSet());
                
И тогда ты на выходе получишь List<Pair> pairs

2024-10-18 19:45 UTC, MiraGlaceon commented on src/main/java/school/faang/StreamAPI2/ListOperations.java
> +                .peek(Collections::sort)
Я понял, ты сортируешь элементы списка, чтобы убрать дубликаты. И тогда идея с классом Pair усложняется тем, чтобы еще переопределять методы hashCode и equals для чистки дубликатов.
Я принимаю твое решение. Основной посыл задачи это потренировать стримы, ты с этим справился. Будет еще время поразбираться в них в будущем

2024-10-18 19:45 UTC, MiraGlaceon approved these changes

2025-01-17 21:30 UTC, closed without merging