BJS2-36047 completed
CorporationX/god_bless pull request #12654
Opened 2024-10-15 17:28 UTC by RuslanGabd

2024-10-15 21:52 UTC, jibulani requested changes
еще есть, что поправить, продолжаем работу! :)

2024-10-15 21:52 UTC, jibulani commented on src/main/java/school/faang/mice/Main.java
> +        scheduler.schedule(() -> {
можно упростить код, подождать, например, 1 секунду и вызвать shutdown, он же за один прогон должен все комнаты зачистить

2024-10-15 21:52 UTC, jibulani commented on src/main/java/school/faang/mice/Main.java
> +        house.roomsList.add(new Room(foodList1));
так ты кладешь не новый список, а тот же, получается, что две комнаты содержат одну и ту же еду

2024-10-15 21:52 UTC, jibulani commented on src/main/java/school/faang/mice/Main.java
> +        }
рекомендую в конце проверить, все ли комнаты вычищены, и добиться правильной работы метода, при которой все комнаты в конце окажутся пустыми

2024-10-17 07:59 UTC, RuslanGabd commented on src/main/java/school/faang/mice/Main.java
> +        }
Спасибо за проверку. Я не совсем понял пункт "добиться правильной работы метода" метод house.collectFood соответствует описанию задачи. Добавли ожидание в Main пока комнаты не станут пустыми, возможно это имелось ввиду, но не уверен что это best practice использовать sleep в цикле while

2024-10-17 08:01 UTC, RuslanGabd commented on src/main/java/school/faang/mice/Main.java
> +        scheduler.schedule(() -> {
у меня одной секунды не хватает, за один прогон он только две комнаты очистит.

2024-10-17 08:28 UTC, jibulani commented on src/main/java/school/faang/mice/Main.java
> +        scheduler.schedule(() -> {
у тебя же 5 потоков, каждый чистит 2 комнаты, должно хватать

2024-10-17 08:31 UTC, RuslanGabd commented on src/main/java/school/faang/mice/Main.java
> +        scheduler.schedule(() -> {
но они же рандомно берут, могут взять комнаты где уже нет еды

2024-10-17 08:34 UTC, RuslanGabd commented on src/main/java/school/faang/mice/Main.java
> +        scheduler.schedule(() -> {
сейчас проверяю из 4 раз 1 секунды хватило только в двух случаях

2024-10-17 08:40 UTC, jibulani commented on src/main/java/school/faang/mice/Main.java
> +        }
можно в конце метода main сделать `System.out.println(House.collectedFood.size());`
рекомендую несколько раз перепрогнать программу и посмотреть, какие числа там выводятся, там не всегда правильный ответ получается, рекомендую подумать, где лучше сделать синхронизацию, чтобы потоки из одной комнаты еду не дублировали

2024-10-17 08:40 UTC, jibulani commented on src/main/java/school/faang/mice/Main.java
> +        scheduler.schedule(() -> {
можно проверять, что комната с едой и только тогда ее брать,  но ок, в целом некритично

2024-10-17 08:46 UTC, jibulani requested changes
логика еще неправильно работает, подумай над тем, что и когда синхронизировать

2024-10-17 09:10 UTC, RuslanGabd commented on src/main/java/school/faang/mice/Main.java
> +        }
Спасибо! теперь понял ошибку, добавил synchronize на комнаты. Проверль выводит одинаковое число  (House.collectedFood.size())

2024-10-17 20:30 UTC, jibulani approved these changes
супер, молодец!

2024-10-18 19:58 UTC, jibulani approved these changes

2024-10-18 19:58 UTC, merged