Mice are very nice!
CorporationX/god_bless pull request #12667
Opened 2024-10-15 17:58 UTC by m1rroxxx

2024-10-17 18:59 UTC, MiraGlaceon requested changes

2024-10-17 18:59 UTC, MiraGlaceon commented on src/main/java/school/faang/TomAndJerry/Main.java
> +      while (!house.allFoodCollected()) {
Можно проверять в цикле, но ты уже используешь awaitTermination(). Попробуй поставить тайм-аут в этом методе повыше

2024-10-18 13:33 UTC, m1rroxxx commented on src/main/java/school/faang/TomAndJerry/Main.java
> +      while (!house.allFoodCollected()) {
то есть я просто вместо цикла пишу Thread.sleep(1000); и потом сразу shutdown(); и будет работать
что то с ScheduledExecutorService не очень разобрался)

2024-10-18 13:33 UTC, m1rroxxx commented on src/main/java/school/faang/TomAndJerry/Main.java
> +      while (!house.allFoodCollected()) {
или я должен сделать вот такую лямбду?
() -> {
house.collectFood();
if(house.allFoodCollected()) scheduledExecutorService.shutdown();
}

2024-10-18 16:53 UTC, MiraGlaceon approved these changes

2024-10-18 16:53 UTC, MiraGlaceon commented on src/main/java/school/faang/TomAndJerry/Main.java
> +      while (!house.allFoodCollected()) {
Не, ты тут прав, по условию задачи проходит. Я не так воспринял твой подход. Ты выполняешь потоки, пока у тебя еда в доме не закончится, все верно

2024-10-18 19:58 UTC, MiraGlaceon approved these changes

2025-01-17 21:30 UTC, closed without merging