Here we have a code for the task BJS2-36760
CorporationX/god_bless pull request #12701
Opened 2024-10-15 21:50 UTC by Andrey-O-Kotlyarov

Task "Supercow!"

2024-10-16 22:33 UTC, jibulani requested changes
нормуль, но можно упростить логику

2024-10-16 22:33 UTC, jibulani commented on src/main/java/school/faang/Player.java
> +        synchronized (boss) {
тут можно сделать проще и без синхронизации - сделать внутри только joinBattle, а затем вызвать leaveBattle (можно после задержки, для имитации реальной битвы)

метод leaveBattle определить синхронизованным внутри Boss, уменьшать в нем currentPlayers и делать notifyAll

2024-10-17 11:11 UTC, Andrey-O-Kotlyarov commented on src/main/java/school/faang/Boss.java
> +package school.faang;
ок, сделал

2024-10-17 11:12 UTC, Andrey-O-Kotlyarov commented on src/main/java/school/faang/Boss.java
> +        //вызывая этот метод, игрок пытается агрить на себя босса
комменты удалил

2024-10-17 11:12 UTC, Andrey-O-Kotlyarov commented on src/main/java/school/faang/Boss.java
> +        if (!(currentPlayers < maxPlayers)) {
переделал

2024-10-17 11:12 UTC, Andrey-O-Kotlyarov commented on src/main/java/school/faang/Main.java
> +        for (Player player : clan) {
переделал

2024-10-17 11:13 UTC, Andrey-O-Kotlyarov commented on src/main/java/school/faang/Player.java
> +        synchronized (boss) {
да, действительно так получилось проще, я все переделал

2024-10-17 20:27 UTC, jibulani requested changes
все хорошо, осталось совсем немного!

2024-10-17 20:27 UTC, jibulani commented on src/main/java/school/faang/supercow/Boss.java
> +        if (currentPlayers >= maxPlayers) {
немного неправильно понял, тут if-else вообще не нужен, просто делаешь `while (currentPlayers >= maxPlayers)`
и внутри просто можно сделать wait без указания времени, простаивающий поток продолжит работу после получения notifyAll от какого-то другого потока
если вышли из while, значит теперь игроков в битве меньше допустимого максимума и можно увеличивать количество currentPlayers

2024-10-17 20:27 UTC, jibulani commented on src/main/java/school/faang/supercow/Boss.java
> +            currentPlayers ++;
обычно перед инкрементом/декрементом не ставят пробел

2025-01-17 21:30 UTC, closed without merging