Here we have a code for the task BJS2-37055
CorporationX/god_bless pull request #12755
Opened 2024-10-16 12:49 UTC by Andrey-O-Kotlyarov

Task "The Iron Throne at any cost"

2024-10-17 08:27 UTC, jibulani requested changes
есть несколько комментариев, нужно доработать

2024-10-17 08:27 UTC, jibulani commented on src/main/java/school/faang/User.java
> +                while (!house.getAccessibleRoles().contains(role)) {
получается, что после освобождения роли, персонаж так и не получит ее
тут не нужен if-else, просто сделай while, дождись освобождения роли и назначь ее пользователю

2024-10-17 08:27 UTC, jibulani commented on src/main/java/school/faang/Main.java
> +                            user.joinHouse(listOfTheHouses.get(preferedHouse),
после получения роли можно сделать Thread.sleep на секунду для задержки с ней на какое-то время, а потом вызвать leaveHouse

2024-10-17 08:27 UTC, jibulani commented on src/main/java/school/faang/User.java
> +                house.wait(TIME_OF_BEENG_IN_THE_HOUSE);
тут wait не нужен, а leaveHouse из потока, созданного в main можно вызвать

2024-10-17 08:27 UTC, jibulani commented on src/main/java/school/faang/House.java
> +package school.faang;
рекомендую каждую задачу в отдельном пакете решать

2024-10-17 08:27 UTC, jibulani commented on src/main/java/school/faang/House.java
> +        this.quantityOfAccessibleRoles --;
некритично, но обычно пробелы не ставят перед ++ или --

2024-10-18 09:09 UTC, Andrey-O-Kotlyarov commented on src/main/java/school/faang/User.java
> +                while (!house.getAccessibleRoles().contains(role)) {
да действительно, это я затупил

2024-10-18 09:09 UTC, Andrey-O-Kotlyarov commented on src/main/java/school/faang/Main.java
> +                            user.joinHouse(listOfTheHouses.get(preferedHouse),
да, точно, мне и самому не нравилось то, что в метод джойн хаус пришлось добавлять постороннюю логику, нарушающую суть метода. Но почему-то я не догадался вынести это в мэйн

2024-10-18 09:09 UTC, Andrey-O-Kotlyarov commented on src/main/java/school/faang/House.java
> +package school.faang;
понял, принял

2024-10-18 20:02 UTC, jibulani approved these changes
супер, молодец!

2024-10-18 20:02 UTC, jibulani commented on src/main/java/school/faang/ironThrone/House.java
> +package school.faang.ironThrone;
по [код-стайлу](https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names) названия пакетов только в нижнем регистре должны быть, учти на будущее, пожалуйста

2024-10-18 20:02 UTC, jibulani commented on src/main/java/school/faang/House.java
> +public class House {
видимо лишние классы остались в основном пакете
некритично, можно в следующем пул-реквесте убрать

2024-10-23 20:23 UTC, jibulani requested changes
нужно исправить конфликт и смержу :)

2024-10-24 16:38 UTC, jibulani approved these changes
супер!

2024-10-24 16:38 UTC, merged