Железный трон любой ценой
CorporationX/god_bless pull request #13036
Opened 2024-10-18 14:59 UTC by m1rroxxx

2024-10-20 20:20 UTC, MiraGlaceon requested changes

2024-10-20 20:20 UTC, MiraGlaceon commented on src/main/java/school/faang/gameOfThrones/Main.java
> +      }else {
Не забывай проставлять пробелы. И нужно уладить вопрос с табуляцией, в проектной работе так не смогу принять твою задачу, нужно чтобы код был у всех единообразным

2024-10-20 20:20 UTC, MiraGlaceon commented on src/main/java/school/faang/gameOfThrones/Main.java
> +      throw new IllegalStateException(e.getMessage(), e);
При обработке ошибок добавляй сообщение что пошло не так. Потому что стандартное сообщение ошибки e.getMessage может быть не информативным при выполнении твоей задачи

2024-10-20 20:20 UTC, MiraGlaceon commented on src/main/java/school/faang/gameOfThrones/User.java
> +      do {
Здесь нужно реализовать по другому. Посмотри внимательнее, у тебя цикл и условие опираются на одну переменную, попробуй упростить

2024-10-20 20:26 UTC, MiraGlaceon requested changes

2024-10-20 20:26 UTC, MiraGlaceon commented on src/main/java/school/faang/gameOfThrones/User.java
> +    synchronized (house) {
Здесь у тебя два раза синхронизация. Первая по объекту this, вторая просто по объекту. От одного нужно избавляться. Тут в "монитор" нужно брать какой-то один объект

2024-10-20 22:02 UTC, m1rroxxx commented on src/main/java/school/faang/gameOfThrones/Main.java
> +      }else {
табуляцию исправил, все следующие задачи будут с ней

2024-10-21 07:45 UTC, MiraGlaceon approved these changes

2025-01-17 21:31 UTC, closed without merging