Army of heroes of might and magic
CorporationX/god_bless pull request #13165
Opened 2024-10-19 17:07 UTC by Yevgeniy5056

2024-10-21 18:38 UTC, Mixalight requested changes

2024-10-21 18:38 UTC, Mixalight commented on src/main/java/school/faang_sprint_3/army_of_heroes_sword_magic/Army.java
> +@Data
Data - аннотация, которая влечёт за собой много лишних зависимостей. Лучше точечно использовать нужные тебе части

2024-10-21 18:38 UTC, Mixalight commented on src/main/java/school/faang_sprint_3/army_of_heroes_sword_magic/Unit.java
> +@Data
Аналогично

2024-10-21 18:38 UTC, Mixalight commented on src/main/java/school/faang_sprint_3/army_of_heroes_sword_magic/PowerCalculator.java
> +@Data
Аналогично

2024-10-21 18:38 UTC, Mixalight commented on src/main/java/school/faang_sprint_3/army_of_heroes_sword_magic/PowerCalculator.java
> +
Лишняя строка

2024-10-21 18:38 UTC, Mixalight commented on src/main/java/school/faang_sprint_3/army_of_heroes_sword_magic/Main.java
> +
Лишняя строка

2024-10-21 18:38 UTC, Mixalight commented on src/main/java/school/faang_sprint_3/army_of_heroes_sword_magic/Army.java
> +        AtomicInteger totalPower = new AtomicInteger();
А зачем тебе здесь такой тип? Тебе хватит и обычного int в этой задаче. У нас суммирование в переменную, пусть потоки в рандомном порядке будут это делать - не важно

2024-10-23 20:56 UTC, SemyonKrivtsov approved these changes
Теперь ок

2024-10-23 20:56 UTC, merged