Alex15265 bjs2 37737
CorporationX/god_bless pull request #13167
Opened 2024-10-19 17:11 UTC by Alex15265

1. Создайте класс User, который представляет пользователя приложения. В нем должны быть следующие поля и методы:
name — имя пользователя.
isOnline — флаг, который показывает, находится ли пользователь в сети.
isLookingForChat — флаг, который показывает, хочет ли пользователь начать чат.
Методы для получения и изменения этих полей.
2. Создайте класс UserList, который будет содержать список всех пользователей и методы для работы с этим списком:
getOnlineUsers() — возвращает список пользователей, которые находятся онлайн и хотят начать чат.
addUser(User user) — добавляет пользователя в список.
removeUser(User user) — удаляет пользователя из списка.
3. Создайте класс Chat, который будет представлять чат между двумя пользователями:
Поля: user1 и user2 — пользователи, участвующие в чате.
Методы для работы с чатом
4. Создайте класс ChatManager, который будет управлять созданием и завершением чатов:
startChat() — начинает чат для данного пользователя. Если нет доступных собеседников, метод должен ждать, пока кто-то не присоединится.
waitForChat() — проверяет, есть ли доступный чат для пользователя. Если нет, ожидает, пока чат не будет создан.
endChat() — завершает чат и уведомляет потоки, которые ждут начала нового чата.
5. Запустите в методе main несколько потоков и протестировать работу приложения.

2024-10-21 16:07 UTC, jibulani requested changes
есть пара замечаний, а в целом все хорошо, молодец!

2024-10-21 16:07 UTC, jibulani commented on src/main/java/school/faang/mattersoftheheart/ChatManager.java
> +                log.info("{} and {} start chatting", user.getName(), companionOptional.get().getName());
несколько раз вызываешь companionOptional.get() - лучше создай переменную и проинициализируй ее этим значением, а дальше уже используй переменную

2024-10-21 16:07 UTC, jibulani commented on src/main/java/school/faang/mattersoftheheart/ChatManager.java
> +        Optional<Chat> chatOptional = chats.stream().filter(chat -> chat.user1().equals(user)).findFirst();
я бы проверял, что `chat.user1().equals(user) || chat.user2().equals(user)`, а то получается, что если пользователь на второй позиции в чате, то для него чат не закроем

2024-10-21 16:07 UTC, jibulani commented on src/main/java/school/faang/mattersoftheheart/ChatManager.java
> +            chats.remove(chatOptional.get());
тоже лучше вынести в отдельную переменную, можно еще через `ifPresent` переписать

2024-10-22 15:57 UTC, Alex15265 commented on src/main/java/school/faang/mattersoftheheart/ChatManager.java
> +        Optional<Chat> chatOptional = chats.stream().filter(chat -> chat.user1().equals(user)).findFirst();
я изначально так делал, но это приводило к некорректной работе:
в текущей реализации если пользака уже забрали в чат в качестве companion из другого потока, то его признак isLookingForChat меняется и потоки которые запущены уже на этом пользаке не могут открыть чат в startChat() по условию, но эти же потоки заходят дальше в метод endChat и не должны закрывать чат, где данный пользак выступает в качестве companion, менять признаки итд.
Поэтому здесь специально закрываю чаты только если user - создатель чата, а не companion
Надеюсь, понятно расписал)
Вот я еще думал, как вариант: если в startChat пользак не проходит условие (то есть поьзак уже забран в чат в другом потоке в качестве companion) - убивать этот поток, чтобы дальше он не выполнял последующую логику(pause, endChat).

2024-10-22 16:32 UTC, jibulani commented on src/main/java/school/faang/mattersoftheheart/ChatManager.java
> +        Optional<Chat> chatOptional = chats.stream().filter(chat -> chat.user1().equals(user)).findFirst();
понял, хорошо
да, второй вариант тоже норм

2024-10-22 16:33 UTC, merged