BJS2-36094 создание пула потоков с задачами по расписанию
CorporationX/god_bless pull request #13198
Opened 2024-10-19 20:40 UTC by evgen-backend-rostov

2024-10-20 20:51 UTC, jibulani requested changes
нужно поправить логику работы кода

2024-10-20 20:51 UTC, jibulani commented on src/main/java/school/faang/multythreating/tomandjerry/House.java
> +        executorService.scheduleAtFixedRate(() -> house.collectFood(executorService), 0, 30, TimeUnit.SECONDS);
в такой реализации у тебя каждые 30 секунд будет создаваться поток, а надо, чтобы 5 потоков одновременно начали работу, можно через цикл 5 раз запустить их по шедулеру

2024-10-20 20:51 UTC, jibulani commented on src/main/java/school/faang/multythreating/tomandjerry/House.java
> +    }
рекомендую в конце метода проверить, что все отработало правильно, например, вывести количество собранной еды
также поперезапускай программу несколько раз и убедись, что при нескольких параллельно работающих потоках программа все время правильный ответ выдает

2024-10-20 20:51 UTC, jibulani commented on src/main/java/school/faang/multythreating/tomandjerry/House.java
> +            firstRoom.clearFoodList();
почему не просто через `clear()`?

2024-10-22 18:25 UTC, evgen-backend-rostov commented on src/main/java/school/faang/multythreating/tomandjerry/House.java
> +            firstRoom.clearFoodList();
С этим я промучался больше всего, потому что изначально сделал через clear, но программа просто останавливалась, дойдя до этого метода, и дальше не шла: ни исключений, ни нормальной ошибки. Нашёл проблему методом тыка, но почему именно не сработало - не знаю(

2024-10-22 21:46 UTC, jibulani commented on src/main/java/school/faang/multythreating/tomandjerry/House.java
> +            firstRoom.clearFoodList();
да уж, странная ситуация, у других аналогичный код нормально работал

2024-10-22 21:46 UTC, jibulani approved these changes
все хорошо, молодец!

2024-10-22 21:47 UTC, merged