Распределенная армия героев меча и магии
CorporationX/god_bless pull request #13195
Opened 2024-10-19 20:23 UTC by InfernalBeard

https://faang-school.atlassian.net/browse/BJS2-35935

2024-10-21 19:18 UTC, Mixalight requested changes

2024-10-21 19:18 UTC, Mixalight commented on src/main/java/school/faang/distribarmyheroesmightmagic/Unit.java
> +public interface Unit {
Можно немного сократить код, если сделать Unit классом и сделать в нём 
```
protected int power;
```
Тогда не нужно его будет объявлять во всех остальных классах, только конструкторы
Но это по желанию

2024-10-21 19:18 UTC, Mixalight commented on src/main/java/school/faang/distribarmyheroesmightmagic/Army.java
> +                            return 0;
Лучше сделать здесь что-то типо -1. Иначе ты можешь упасть с ошибкой и получить 0, а можешь создать всех с силой 0 и будет такой же результат, не отличишь

2024-10-23 21:00 UTC, SemyonKrivtsov approved these changes
Теперь ок

2024-10-23 21:01 UTC, merged