BJS2-37256 практика использования wait/notify
CorporationX/god_bless pull request #13539
Opened 2024-10-22 20:22 UTC by evgen-backend-rostov

2024-10-22 22:25 UTC, jibulani requested changes
есть немного небольших замечаний, но в целом код хороший, молодец!

2024-10-22 22:25 UTC, jibulani commented on src/main/java/school/faang/multithreading/google/GooglePhotoAutoUploader.java
> +        synchronized (photosToUpload) {
ты же вызываешь этот метод уже из синхронизованного кода, здесь синхронизация избыточна

2024-10-22 22:25 UTC, jibulani commented on src/main/java/school/faang/multithreading/google/GooglePhotoAutoUploader.java
> +    public void oneNewPhotoAdded(String photoPath) {
по заданию метод называется onNewPhotoAdded - некритично

2024-10-22 22:25 UTC, jibulani commented on src/main/java/school/faang/multithreading/google/Main.java
> +    public static String generateRandomString() {
да, это жестко :D
обычно для генерации рандомных идентификаторов в Java используют `UUID.randomUUID()`

2024-10-23 08:43 UTC, evgen-backend-rostov commented on src/main/java/school/faang/multithreading/google/Main.java
> +    public static String generateRandomString() {
нужна была генерация рандомных строк, сильно заморачиваться не стал, взял первый попавшийся пример из инета)

2024-10-23 20:29 UTC, jibulani approved these changes
супер!

2024-10-23 20:29 UTC, merged