Собираем заказы в Amazon
CorporationX/god_bless pull request #13756
Opened 2024-10-24 14:45 UTC by m1rroxxx

2024-10-25 15:42 UTC, MiraGlaceon requested changes

2024-10-25 15:42 UTC, MiraGlaceon commented on src/main/java/school/faang/CollectingOrdersAmazon/OrderProcessor.java
> +                            executorService.shutdownNow();
В такой ситуации, можно еще разнообразить класс Order. Например не пробрасывать ошибку вверх, а в order передавать статус "failed" и записать в order ошибку в errorMessage. Тогда ты бы мог штатно обработать все заказы и в списке вывести те заказы, которые завершились хорошо и те, которые с ошибкой. Создай enum статусов и доработай логику, отпиши как тебе такой подход и его минусы/плюсы и свое мнение

2024-10-25 21:31 UTC, m1rroxxx commented on src/main/java/school/faang/CollectingOrdersAmazon/OrderProcessor.java
> +                            executorService.shutdownNow();
в методе processOrder я меняю статус на FAILED и добовляю errorMessage, а в exceptionally, просто ловлю исключение которое могло вылететь в processOrder
Такой подход конечно мне больше нравиться, это звучит логичнее, я например могу попробывтаь его обработать ещё раз или просто вывести что этот заказ был с ошибкой, плюс мне нравиться использовать enum мне кажеться намного правильнее чем писать строчки,

2024-10-27 21:04 UTC, MiraGlaceon commented on src/main/java/school/faang/CollectingOrdersAmazon/OrderProcessor.java
> +                            executorService.shutdownNow();
Enum намного эффективнее. Запись в бузу исключает возможность ошибки в тексте. То ли написать "PEDING", допустить ошибку, записать в базу неверный статус и затерять заказ пока в базу не полезешь. То ли использовать enum PENDING и всегда иметь только один статус на все случаи. И править проще всегда в одном месте. Если статус больше не называем PENDING, то строки нужно переписывать везде, а enum один раз подправил и все

2024-10-27 21:04 UTC, MiraGlaceon approved these changes

2025-01-17 22:19 UTC, closed without merging