BJS2-39142 -реализовал подсчет победителей асинхронно ( не знаю как я это написал:))
CorporationX/god_bless pull request #13802
Opened 2024-10-24 21:03 UTC by davidx5x5

2024-10-26 18:52 UTC, jibulani requested changes
есть небольшие комментарии, а в целом все супер, молодец!

2024-10-26 18:52 UTC, jibulani commented on src/main/java/school/faang/magicaltournament/School.java
> +    private List<Student> Team;
по [код-стайлу](https://google.github.io/styleguide/javaguide.html#s5.2.5-non-constant-field-names) названия полей пишут с маленькой буквы

2024-10-26 18:52 UTC, jibulani commented on src/main/java/school/faang/magicaltournament/School.java
> +        int sum = Team.stream().mapToInt(student -> student.getPoints()).reduce(0, Integer::sum);
можно реализовать немного проще:
`Team.stream().mapToInt(Student::getPoints).sum()`

2024-10-26 18:52 UTC, jibulani commented on src/main/java/school/faang/magicaltournament/School.java
> +    public List<Student> getTeam() {
можно геттеры не писать вручную, а использовать аннотацию из ломбока `@Getter`

2024-10-26 19:36 UTC, davidx5x5 commented on src/main/java/school/faang/magicaltournament/School.java
> +    private List<Student> Team;
ок

2024-10-26 19:39 UTC, davidx5x5 commented on src/main/java/school/faang/magicaltournament/School.java
> +        int sum = Team.stream().mapToInt(student -> student.getPoints()).reduce(0, Integer::sum);
спасибо,я что то перемудрил))

2024-10-26 19:39 UTC, davidx5x5 commented on src/main/java/school/faang/magicaltournament/School.java
> +    public List<Student> getTeam() {
ок)

2024-10-27 15:57 UTC, jibulani approved these changes
супер, молодец!

2024-10-27 15:57 UTC, merged