39120 Twitter
CorporationX/god_bless pull request #14038
Opened 2024-10-27 15:55 UTC by Galay007

2024-10-28 21:05 UTC, jibulani requested changes
все хорошо, но надо сделать небольшую правку :)

2024-10-28 21:05 UTC, jibulani commented on src/main/java/school/faang/stprint4/twitter/Main.java
> +            Thread.sleep(10000);
надо переделать на join, как писал в других задачах

2024-10-29 18:21 UTC, Galay007 commented on src/main/java/school/faang/stprint4/twitter/Main.java
> +            Thread.sleep(10000);
![image](https://github.com/user-attachments/assets/580bf001-155f-46ba-a6e6-14bbbaac989f)

2024-10-29 18:23 UTC, Galay007 commented on src/main/java/school/faang/stprint4/twitter/Main.java
> +            Thread.sleep(10000);
Женя, я в той задаче, где ты первый комментарий написал, я на него ответил, что я имитирую продолжительную работу main потока. Могу поставить while(true), но зачем? мне нужно было убедиться, что основной поток не блокируется. Ты предлагаешь join - я знаю, что он блокирует поток, но мне хотелось решение посложнее внедрить. Тем более условием не было ограничения.

2024-10-29 20:57 UTC, jibulani commented on src/main/java/school/faang/stprint4/twitter/Main.java
> +            Thread.sleep(10000);
просто это неправильный подход, тебе же в любом случае для решения задачи нужно дождаться результата фьючеров
делать это через sleep выглядит как костыль - если после sleep фьючеры не успеют завершиться, то программа закончит работу и не выдаст результат, то есть будет работать неправильно

про while(true) не понял, он тут тоже не нужен

ну и в продовом коде нигде не увидишь sleep в подобных задачах

вот еще ответ со стековерфлоу, если мои доводы неубедительны: https://stackoverflow.com/questions/9417260/when-is-it-sensible-to-use-thread-sleep

2024-10-29 20:58 UTC, jibulani requested changes
ответил насчет sleep, поправь, пожалуйста

2024-10-30 20:50 UTC, jibulani requested changes

2024-10-30 20:50 UTC, jibulani commented on src/main/java/school/faang/stprint4/twitter/TwitterSubscriptionSystem.java
> +                .thenRun(() -> System.out.println("\nAccount " + account.getName() + " has total " +  account.getFollowers() + " followers"));
без join программа завершается без вывода количества подписчиков

2024-11-02 10:49 UTC, Galay007 commented on src/main/java/school/faang/stprint4/twitter/TwitterSubscriptionSystem.java
> +                .thenRun(() -> System.out.println("\nAccount " + account.getName() + " has total " +  account.getFollowers() + " followers"));
Потому что основной поток заканчивается раньше, чем успевает выполниться параллельный поток. Поэтому я имитировал работу основного через Sleep. Понятно, что на проде так не делают, но у нас учебная задача и в них имитацию продолжительных операций мы имитируем через sleep.

2024-11-02 10:54 UTC, Galay007 commented on src/main/java/school/faang/stprint4/twitter/TwitterSubscriptionSystem.java
> +                .thenRun(() -> System.out.println("\nAccount " + account.getName() + " has total " +  account.getFollowers() + " followers"));
В данном случае основной поток не простаивает, а продолжает работу, имитированную методом sleep.

2024-11-02 11:00 UTC, Galay007 commented on src/main/java/school/faang/stprint4/twitter/TwitterSubscriptionSystem.java
> +                .thenRun(() -> System.out.println("\nAccount " + account.getName() + " has total " +  account.getFollowers() + " followers"));
И в задаче нет ограничения, что нужно получить ответ через join. Влад учил, что можно через join, а можно не блокировать поток и получить результат, когда он появится. Я пошел по второму варианту, так в проде делают, отлавливая пришедший результат через событие.

2024-11-03 15:41 UTC, jibulani approved these changes

2024-11-03 15:41 UTC, merged