Revers array
CorporationX/god_bless pull request #14111
Opened 2024-12-01 16:37 UTC by Maaskit

Возможно нужно было это все сделать в одном классе, но я сделал в 2-х))

2024-12-01 17:41 UTC, Kayfral requested changes

2024-12-01 17:41 UTC, Kayfral commented on src/main/java/school/faang/Example.java
> +    }
Обрати внимание, что кажись по ошибке продублировал код из класса Main в классе Example

2024-12-01 17:41 UTC, Kayfral commented on src/main/java/school/faang/Example.java
> +    public static void reverse(int[] nums) {
Отлично, к развороту массива вопросов нету. Но что будет если он по какой-то причине будет пустым? Было бы хорошо перед попыткой разворота проверить массив на пустоту

2024-12-01 17:41 UTC, Kayfral commented on src/main/java/school/faang/Example.java
> +
Здесь лишний отступ

2024-12-01 17:41 UTC, Kayfral commented on src/main/java/school/faang/Example.java
> +}
Чисто для красоты, лучше убрать отступы между "}"

2024-12-01 18:32 UTC, Kayfral requested changes

2024-12-01 18:32 UTC, Kayfral commented on src/main/java/school/faang/Example.java
> +        }
Отлично

2024-12-01 18:32 UTC, Kayfral commented on src/main/java/school/faang/Example.java
> +    }
Убери из класса Example public static void main, так как public static void main находится в классе Main)

2024-12-01 18:32 UTC, Kayfral commented on src/main/java/school/faang/Example.java
> +        int[] nums = {};
Массив не обязательно делать пустым, для наглядности лучше когда он заполнен. Но не забывай, что нужно делать обработки случаев пустых массивов

2024-12-01 19:46 UTC, Maaskit commented on src/main/java/school/faang/Example.java
> +        int[] nums = {};
понял)

2024-12-02 03:52 UTC, Kayfral approved these changes

2024-12-02 03:53 UTC, merged