Абстракция, абстракция!
CorporationX/god_bless pull request #14143
Opened 2024-12-02 07:52 UTC by exprnc

Не очень реальные условия на 5-ом пункте задачи, сделал как сам понял.

2024-12-03 10:05 UTC, 20cognosce requested changes

2024-12-03 10:05 UTC, 20cognosce commented on src/main/java/school/faang/task_43804/Archer.java
> +    private static final int INTELLIGENCE = 5;
Почему static? Это не константы

2024-12-03 10:05 UTC, 20cognosce commented on src/main/java/school/faang/task_43804/Archer.java
> +        character.health -= dexterity;
геттеры сеттеры реализовать, напрямую к полям не обращаться

2024-12-03 10:05 UTC, 20cognosce commented on src/main/java/school/faang/task_43804/Warrior.java
> +    private static final int INTELLIGENCE = 3;
Аналогично

2024-12-03 10:05 UTC, 20cognosce commented on src/main/java/school/faang/task_43804/Warrior.java
> +    private static final int INTELLIGENCE = 3;
Ну и как бы вопрос, зачем ты хранишь те же самые поля, которые у тебя итак уже есть в базовом классе

2024-12-03 10:05 UTC, 20cognosce commented on src/main/java/school/faang/task_43804/Character.java
> +    protected int health = 100;
private final

2024-12-03 10:05 UTC, 20cognosce commented on src/main/java/school/faang/task_43804/Character.java
> +    protected int health = 100;
Для данной задаче допустим это ок, но вообще - не очень

2024-12-03 10:05 UTC, 20cognosce commented on src/main/java/school/faang/task_43804/Warrior.java
> +        character.health -= power;
.

2024-12-03 10:05 UTC, 20cognosce commented on src/main/java/school/faang/task_43804/Warrior.java
> +        super(name, POWER, DEXTERITY, INTELLIGENCE);
Переделать

2024-12-03 10:26 UTC, exprnc commented on src/main/java/school/faang/task_43804/Archer.java
> +    private static final int DEXTERITY = 10;
Яндекс переводчик

2024-12-03 10:32 UTC, exprnc commented on src/main/java/school/faang/task_43804/Archer.java
> +    private static final int INTELLIGENCE = 5;
"для Warrior сила всегда выставляется в 10, ловкость в 5, интеллект в 3. Имя передаётся извне;" и "для Archer сила всегда выставляется в 3, ловкость в 10, интеллект в 5. Имя передаётся извне".  Я подумал что константы, потому что  написано "сила всегда выставляется в 10". И ещё написано что имя передаётся извне, а остальное нет

2024-12-03 10:34 UTC, exprnc commented on src/main/java/school/faang/task_43804/Archer.java
> +    private static final int INTELLIGENCE = 5;
> Почему static? Это не константы

"для Warrior сила всегда выставляется в 10, ловкость в 5, интеллект в 3. Имя передаётся извне;" и "для Archer сила всегда выставляется в 3, ловкость в 10, интеллект в 5. Имя передаётся извне". Я подумал что константы, потому что написано "сила всегда выставляется в 10". И ещё написано что имя передаётся извне, а остальное нет

2024-12-03 10:36 UTC, exprnc commented on src/main/java/school/faang/task_43804/Warrior.java
> +    private static final int INTELLIGENCE = 3;
> Аналогично

Ответил под вопросом "Почему static? Это не константы"

2024-12-03 10:37 UTC, exprnc commented on src/main/java/school/faang/task_43804/Archer.java
> +    private static final int DEXTERITY = 10;
> agility

Хех, английский плохо знаю из-за этого использую яндекс переводчик

2024-12-03 12:26 UTC, exprnc commented on src/main/java/school/faang/task_43804/Character.java
> +    protected int health = 100;
> private final

final не получится, нужен геттер

2024-12-03 20:08 UTC, 20cognosce requested changes

2024-12-03 20:08 UTC, 20cognosce commented on src/main/java/school/faang/task_43804/Archer.java
> +        int characterHealth = character.getHealth() - this.getAgility();
healthAfterDamage как-нибудь так

2024-12-03 20:08 UTC, 20cognosce commented on src/main/java/school/faang/task_43804/Character.java
> +    private int health = 100;
Так почему не final? 
Если используется конструктор по имени - устанавливаешь в нём дефолтные значения

2024-12-03 20:08 UTC, 20cognosce commented on src/main/java/school/faang/task_43804/Character.java
> +    private int health = 100;
И здоровье в конструкторе тоже выставляй

Дефолтные значение можешь вынести в статик константы

2024-12-04 11:11 UTC, 20cognosce approved these changes

2024-12-04 11:11 UTC, merged