Ловим события
CorporationX/god_bless pull request #14168
Opened 2024-12-02 12:22 UTC by exprnc

2024-12-03 10:39 UTC, 20cognosce requested changes

2024-12-03 10:39 UTC, 20cognosce commented on src/main/java/school/faang/task_44414/SpellEvent.java
> +    private String eventType;
enum

2024-12-03 10:39 UTC, 20cognosce commented on src/main/java/school/faang/task_44414/SpellEvent.java
> +    private String action;
description, а не action

2024-12-03 10:39 UTC, 20cognosce commented on src/main/java/school/faang/task_44414/SpellEvent.java
> +    private String action;
final

2024-12-03 10:39 UTC, 20cognosce commented on src/main/java/school/faang/task_44414/HogwartsSpells.java
> +    private Map<String, List<SpellEvent>> spellsByType;
final

2024-12-03 12:39 UTC, exprnc commented on src/main/java/school/faang/task_44414/SpellEvent.java
> +    private String eventType;
> enum

Не понимаю зачем тут enum, тут же не нужны константные значения

2024-12-03 12:52 UTC, exprnc commented on src/main/java/school/faang/task_44414/HogwartsSpells.java
> +        System.out.println("===============================");
> forEach

Не совсем понял, тут и так forEach используется

2024-12-03 20:21 UTC, 20cognosce requested changes

2024-12-03 20:21 UTC, 20cognosce commented on src/main/java/school/faang/task_44414/SpellEvent.java
> +    private final String eventType;
Тип события - это конечное множество вариантов, как и например категория, как статус - это всё енамы

2024-12-03 20:21 UTC, 20cognosce commented on src/main/java/school/faang/task_44414/HogwartsSpells.java
> +    public void addSpellEvent(int id, String eventType, String actionDescription) {
Почему не поправил

2024-12-03 20:21 UTC, 20cognosce commented on src/main/java/school/faang/task_44414/HogwartsSpells.java
> +        }
Можно развернуть - если null, то исключение
Тогда else блок не нужен

2024-12-04 11:32 UTC, 20cognosce approved these changes

2024-12-04 11:32 UTC, 20cognosce commented on src/main/java/school/faang/task_44414/HogwartsSpells.java
> +            throw new NullPointerException("Spell event cannot be null");
Лучше кидать IllegalArgument, или кастомное
NPE - более низкоуровневая, системная ошибка зачастую, когда мы в null по-настоящему утыкаемся

2024-12-04 11:32 UTC, merged