Вторая задача
CorporationX/god_bless pull request #14225
Opened 2024-12-02 20:00 UTC by ibai86

2024-12-03 09:15 UTC, SemyonKrivtsov requested changes
Доброго времени суток! Проверил твою работу, смотри комментарии.

2024-12-03 09:15 UTC, SemyonKrivtsov commented on src/main/java/school/faang/bjs2x43681/User.java
> +        if (name == "") {
Лучше валидацию вынести в отдельные приватные методы, чтобы разгрузить код конструктора.

2024-12-04 03:59 UTC, SemyonKrivtsov commented
Не забываем перенести задачу в jira на ревью

2024-12-04 06:41 UTC, ibai86 commented
> Не забываем перенести задачу в jira на ревью

У меня в jira в статусе review висит

2024-12-04 11:59 UTC, merged