task_BJS2-43635
CorporationX/god_bless pull request #14240
Opened 2024-12-02 22:33 UTC by VladimirGontarenko

2024-12-03 13:51 UTC, Kayfral requested changes

2024-12-03 13:51 UTC, Kayfral commented on .github/workflows/ci-prs.yaml
>                repo: context.repo.repo,
Здесь ничего менять не надо. Если не проходит проверка от checkstyle, то посмотри на что он ругается.

![image](https://github.com/user-attachments/assets/6e002c88-f314-4173-96cc-909848993d94)

2024-12-03 13:51 UTC, Kayfral commented on .github/workflows/ci-prs.yaml
>                repo: context.repo.repo,
Верни здесь все как было, чтобы в будующем не ловить git конфликты

2024-12-03 13:51 UTC, Kayfral commented on config/checkstyle/checkstyle.xml
>              <property name="tokens" value="PACKAGE_DEF, IMPORT, STATIC_IMPORT"/>
Тут тоже трогать ничего не надо

2024-12-03 13:51 UTC, Kayfral commented on src/main/java/school/faang/Example.java
> +    }
Хорошо, а что будет происходить когда массив пуст или равен null? Нужно добавить логику проверки входных данных

2024-12-03 13:51 UTC, Kayfral commented on src/main/java/school/faang/Main.java
> +        int [] nums = {1,2,3,4,5};
Вот как раз тот момент на который ругался checkstyle, после запятых должен пробел

2024-12-04 08:52 UTC, VladimirGontarenko commented on config/checkstyle/checkstyle.xml
>              <property name="tokens" value="PACKAGE_DEF, IMPORT, STATIC_IMPORT"/>
53 строчку не помню чтобы изменял, может как то случайно. Сейчас дописал её, но появились предупреждения об устаревшей версии. Но все работает

2024-12-04 08:53 UTC, VladimirGontarenko commented on src/main/java/school/faang/Example.java
> +    }
Добавил проверку, будет выводить сообщение

2024-12-04 11:56 UTC, merged