Задача: Абстракция, абстракция!
CorporationX/god_bless pull request #14241
Opened 2024-12-02 23:40 UTC by ibai86

2024-12-03 10:12 UTC, 20cognosce commented on src/main/java/school/faang/abstraction/Warrior.java
> +    }
Аналогично

2024-12-03 20:12 UTC, ibai86 commented
Убрал геттеры и сеттеры

2024-12-03 20:36 UTC, 20cognosce requested changes

2024-12-03 20:36 UTC, 20cognosce commented on src/main/java/school/faang/abstraction/Archer.java
> +    }
Воспользуйся ломбоковской аннотацией

2024-12-03 20:36 UTC, 20cognosce commented on src/main/java/school/faang/abstraction/Archer.java
> +        character.health -= this.agility;
Не обращаться так к переменным, только через геттеры / сеттеры

2024-12-03 20:36 UTC, 20cognosce commented on src/main/java/school/faang/abstraction/Archer.java
> +        super(name, ARCHER_POWER, ARCHER_AGILITY, ARCHER_INTELLECT);
Это хорошо

2024-12-03 20:36 UTC, 20cognosce commented on src/main/java/school/faang/abstraction/Character.java
> +    protected int health = 100;
final

2024-12-03 20:36 UTC, 20cognosce commented on src/main/java/school/faang/abstraction/Character.java
> +public abstract class Character {
intelligence

2024-12-03 20:36 UTC, 20cognosce commented on src/main/java/school/faang/abstraction/Character.java
> +    protected static final int ARCHER_INTELLECT = 5;
сгруппируй по типу сущности, а не по параметру

2024-12-03 20:36 UTC, 20cognosce commented on src/main/java/school/faang/abstraction/Character.java
> +    protected static final int ARCHER_INTELLECT = 5;
здесь модификатор правильный

2024-12-03 20:36 UTC, 20cognosce commented on src/main/java/school/faang/abstraction/Warrior.java
> +    }
Аналогично

2024-12-04 11:21 UTC, 20cognosce requested changes

2024-12-04 11:21 UTC, 20cognosce commented on src/main/java/school/faang/abstraction/Archer.java
> +        int healthBeforeAttack = character.getHealth();
Лучше посчитать здоровье после атаки

2024-12-04 11:21 UTC, 20cognosce commented on src/main/java/school/faang/abstraction/Archer.java
> +
Лишняя строка пустая

2024-12-04 11:21 UTC, 20cognosce commented on src/main/java/school/faang/abstraction/Character.java
> +    public Character(String name, int power, int agility, int intelligence) {
А где конструктор только по имени

2024-12-04 15:35 UTC, ibai86 commented on src/main/java/school/faang/abstraction/Character.java
> +    public Character(String name, int power, int agility, int intelligence) {
Если создаю конструктор только по имени, то не могу установить поля power, agility, intelligence как final

2024-12-07 14:07 UTC, 20cognosce approved these changes
Хорошо, принято

2024-12-07 14:07 UTC, 20cognosce commented on src/main/java/school/faang/abstraction/Archer.java
> +        super(name, ARCHER_POWER, ARCHER_AGILITY, ARCHER_INTELLIGENCE);
Хорошо

2024-12-07 14:07 UTC, 20cognosce commented on src/main/java/school/faang/abstraction/Character.java
> +    protected static final int ARCHER_INTELLIGENCE = 5;
Можно в конфиг класс, так тоже норм

2024-12-07 14:07 UTC, 20cognosce commented on src/main/java/school/faang/abstraction/Character.java
> +    private int intelligence;
final, почему не final?

2024-12-07 14:07 UTC, 20cognosce commented on src/main/java/school/faang/abstraction/Character.java
> +        this.name = name;
А здесь дефолтные настройки выставлять

2024-12-07 14:07 UTC, merged