BJS2-43836 [Абстракция, абстракция!]
CorporationX/god_bless pull request #14352
Opened 2024-12-03 21:31 UTC by Iv-an-s

2024-12-04 20:56 UTC, mysosnovskaya requested changes

2024-12-04 20:56 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/task_43502/Archer.java
> +        super(name, 3, 10, 5);
Давай числа 3, 10, 5 вынесем в константы в этом классе, чтобы было понятно, что это такое

2024-12-04 20:56 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/task_43502/Archer.java
> +    }
А зачем нужен этот конструктор, если ничего кроме name не используется?

2024-12-04 20:56 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/task_43502/Character.java
> +    protected int heath = 100;
Опечатка в названии поля, должно быть health

2024-12-04 20:56 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/task_43502/Archer.java
> +        character.heath -= this.agility;
Лучше никогда не обращаться к полям напрямую. Можно сделать отдельный метод для изменения здоровья, который к тому же будет следить за тем, чтобы здоровье не становилось меньше нуля

2024-12-04 20:56 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/task_43502/Warrior.java
> +public class Warrior extends Character {
В этом классе комментарии аналогичны классу Archer

2024-12-04 21:49 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/task_43502/Archer.java
> +        super(name, 3, 10, 5);
Давай :) Вынес в константы

2024-12-04 21:50 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/task_43502/Archer.java
> +    }
Подумал в условиях задачи подвох, в требованиях написано "переопредели конструкторы...".
Убрал.

2024-12-04 21:50 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/task_43502/Character.java
> +    protected int heath = 100;
поправил

2024-12-04 21:51 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/task_43502/Archer.java
> +        character.heath -= this.agility;
добавил геттеры, и сеттер на health, с проверкой, чтобы health не опускалось ниже нуля.

2024-12-04 21:51 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/task_43502/Warrior.java
> +public class Warrior extends Character {
поправил

2024-12-05 20:48 UTC, mysosnovskaya approved these changes
Не хватает Main класса в задаче. Лучше всегда его добавлять, т.к. во-первых, так я буду видеть, что ты правда тестировал свой код, а во-вторых, я смогу тоже его запустить и проверить)

2024-12-05 20:48 UTC, merged