Solve task_43840
CorporationX/god_bless pull request #14359
Opened 2024-12-03 22:29 UTC by shamshaev

2024-12-04 20:59 UTC, mysosnovskaya requested changes

2024-12-04 20:59 UTC, mysosnovskaya commented on src/main/java/school/faang/task_43840/Archer.java
> +@Setter
Можно эти аннотации повесить над родительским классом, чтобы не дублировать в каждом наследнике

2024-12-04 20:59 UTC, mysosnovskaya commented on src/main/java/school/faang/task_43840/Archer.java
> +        health -= character.agility;
Во-первых, логика атаки должна быть наоборот :) this наносит атаку character, т.е. у character должно измениться здоровье.
Во-вторых, лучше не обращаться к полям напрямую, а использовать для этого геттеры и сеттеры

2024-12-04 20:59 UTC, mysosnovskaya commented on src/main/java/school/faang/task_43840/Warrior.java
> +        health -= character.strength;
Здесь аналогично про логику. И кстати, было бы хорошо проверить, что character не null, а то есть риск словить NullPointerException

2024-12-04 20:59 UTC, mysosnovskaya commented on src/main/java/school/faang/task_43840/Archer.java
> +        health -= character.agility;
И ещё не забудь убедиться, что здоровье не стало меньше нуля. Минимальное возможное значение для поля health - ноль

2024-12-05 20:51 UTC, mysosnovskaya requested changes

2024-12-05 20:51 UTC, mysosnovskaya commented on src/main/java/school/faang/task_43840/Warrior.java
> +    }
Метод подозрительно похож на такой же метод в классе Archer :) Давай вынесем общую логику в родительский класс (подумай, как это лучше сделать, и если что - приходи, обсудим)

2024-12-06 16:41 UTC, shamshaev commented on src/main/java/school/faang/task_43840/Warrior.java
> +    }
Еще можно эту логику поместить в функциональный интерфейс BiConsumer и сделать его полем Character, но это будет более кривой вариант, по моему.

2024-12-06 16:58 UTC, shamshaev commented on src/main/java/school/faang/task_43840/Warrior.java
> +    }
В любом случае, то как я сделал сейчас и как с функциональным интерфейсом, мне не нравится, потому что логика относящаяся к одному методу в Warrior и Archer размазана на два метода в Character. Оптимально было в одном, но метод attack в Character по условию абстрактный, т.е. не может иметь тела.  Соответственно не понимаю, как сделать всю логику attack в одном месте (методе).

2024-12-06 18:02 UTC, mysosnovskaya requested changes
Оставила комментарии по улучшению, но глобально подход верный 👍

2024-12-06 18:02 UTC, mysosnovskaya commented on src/main/java/school/faang/task_43840/Archer.java
> +        damageHealth(character, agility);
Лучше не персонажа передавать, а у персонажа метод вызвать: `character.demageHealth(agility)`

2024-12-06 18:02 UTC, mysosnovskaya commented on src/main/java/school/faang/task_43840/Character.java
> +    protected void damageHealth(Character character, int ability) {
Метод можно назвать reduceHealth (уменьшить здоровье), как будто бы так лучше суть отражена будет. 
Ну и параметр ability нужно переименовать, можно даже просто value (если метод называется reduceHealth, то как параметр передаем ему значение - на сколько нужно здоровье уменьшить)

А в остальном всё отлично)

2024-12-06 22:49 UTC, shamshaev commented on src/main/java/school/faang/task_43840/Archer.java
> +        damageHealth(character, agility);
Если у персонажа вызывать метод, то тогда придется оставить проверку на null в методах наследников, иначе можно получить NullPointerException. И получается немного общей логики останется в наследниках.

2024-12-08 19:16 UTC, mysosnovskaya approved these changes

2024-12-08 19:16 UTC, mysosnovskaya commented on src/main/java/school/faang/task_43840/Warrior.java
> +        }
Отлично) Да, проверка на null осталась - это нормально. В ООП языке мы у объекта, с которым хотим совершить действие, вызываем метод - это самое действие. Поэтому текущая реализация является верной. Есть небольшие минусы этого (та же дублирующаяся проверка на null), но ясность кода сохраняется и стиль ООП не нарушается - это важнее)

2024-12-08 19:16 UTC, merged