fladx-BJS2-45214-Double-Cash
CorporationX/god_bless pull request #14379
Opened 2024-12-04 07:24 UTC by therealadik

2024-12-05 14:05 UTC, ArtemValt commented on src/main/java/school/faang/task_45214/util/StudentDatabase.java
> +            this.subjects.putIfAbsent(subject, new ArrayList<>());
путИфАбсет возвращает T так что можно использовать 
this.subjects.putIfAbsent(subject, new ArrayList<>()).add(student);

2024-12-05 14:06 UTC, ArtemValt commented on src/main/java/school/faang/task_45214/util/StudentDatabase.java
> +        Map<Subject, Integer> grades = students.get(student);
getOrDefault(student, new HashMap<>()); уберет лишнюю проверку

2024-12-05 14:08 UTC, ArtemValt commented on src/main/java/school/faang/task_45214/util/StudentDatabase.java
> +            this.subjects.putIfAbsent(subject, new ArrayList<>());
это относится ко всему классу

2024-12-05 14:13 UTC, ArtemValt commented on src/main/java/school/faang/task_45214/Main.java
> +        Student student1 = new Student();
можешь явно в конструкторе обьявить поля, не используя сеттеры

2024-12-05 15:18 UTC, therealadik commented on src/main/java/school/faang/task_45214/util/StudentDatabase.java
> +            this.subjects.putIfAbsent(subject, new ArrayList<>());
Метод putIfAbsent возвращает либо предыдущее значение, ассоциированное с ключом (если ключ уже есть), либо null, если ключа не было. Это вызовет исключение

2024-12-05 15:22 UTC, therealadik commented on src/main/java/school/faang/task_45214/util/StudentDatabase.java
> +        Map<Subject, Integer> grades = students.get(student);
тогда grades не будет лежать внутри students,
нужно не getOrDefault, а computeIfAbsent

2024-12-07 08:59 UTC, ArtemValt requested changes

2024-12-07 08:59 UTC, ArtemValt commented on src/main/java/school/faang/task_45214/util/StudentDatabase.java
> +        if (grades != null) {
можно на removeIf заменить

2024-12-07 09:28 UTC, therealadik commented on src/main/java/school/faang/task_45214/util/StudentDatabase.java
> +        if (grades != null) {
нельзя, это мапа

2024-12-07 16:11 UTC, ArtemValt approved these changes

2024-12-07 16:11 UTC, ArtemValt commented
ну красота же

2024-12-07 16:11 UTC, merged