BJS2-44470 was completed.
CorporationX/god_bless pull request #14381
Opened 2024-12-04 08:18 UTC by LeshaKoz

BJS2-44470 was completed.

2024-12-04 18:36 UTC, mysosnovskaya requested changes

2024-12-04 18:36 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44470/SpellEvent.java
> +    @Getter
Getter лучше добавить на все поля класса, т.к. этот класс представляет собой класс-модель и нам не жалко, если эти поля будет смотреть кто-то ещё)

2024-12-04 18:36 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44470/Main.java
> +        if ((spellEvents != null) && (!spellEvents.isEmpty())) {
Вместо isEmpty лучше использовать isBlank, он также не пропустит и строки, содержащие только пробелы

2024-12-04 18:36 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44470/Main.java
> +            spellEvents.forEach(System.out::println);
Вижу, что ты уже используешь лямбда-функции и method reference - круто! Тема будущего спринта, кстати)

2024-12-04 18:36 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44470/Main.java
> +    private static final HogwartsSpells hogwartsSpells = new HogwartsSpells();
Если это static final, то значит поле должно НАЗЫВАТЬСЯ_В_ТАКОМ_РЕГИСТРЕ, как и поля выше)

2024-12-04 18:36 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44470/HogwartsSpells.java
> +    public void addSpellEvent(int id, String eventType, String actionDescription) {
Идентификатор не должен приходить снаружи - а вдруг случайно метод addSpellEvent вызовут из разных методов и передадут одинаковые id? Так что за уникальностью id нужно следить в этом классе, в HogwartsSpells. Только он знает, какие идентификаторы уже используются, а какие - нет

2024-12-04 18:36 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44470/HogwartsSpells.java
> +        spellsByType.putIfAbsent(eventType, new ArrayList<>());
putIfAbsent это хорошо 👍 Можешь ещё посмотреть на computeIfAbsent, здесь лучше подойдет)

2024-12-04 18:36 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44470/HogwartsSpells.java
> +                }
Круто, что подумал об этом) Легко было забыть о такой логике 👍

2024-12-05 17:58 UTC, LeshaKoz commented on src/main/java/school/faang/task_44470/Main.java
> +        if ((spellEvents != null) && (!spellEvents.isEmpty())) {
В данном случае проверка List<SpellEvent> spellEvents что он не пустой. Поэтому другого варианта нет.

2024-12-05 21:20 UTC, mysosnovskaya approved these changes

2024-12-05 21:20 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44470/Main.java
> +        if ((spellEvents != null) && (!spellEvents.isEmpty())) {
Да, верно!) Мой комментарий был бы актуален для строчек, а для списка, конечно, нет)

2024-12-05 21:20 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44470/HogwartsSpells.java
> +    private int nextId = 0;
Хорошо с id получилось 👍

2024-12-05 21:20 UTC, merged