Решение задачи с реверсом массива
CorporationX/god_bless pull request #14388
Opened 2024-12-04 09:35 UTC by sanctus-germanus

Решение задачи с реверсом массива

2024-12-04 11:54 UTC, Kayfral requested changes

2024-12-04 11:54 UTC, Kayfral commented on src/main/java/ru/maks1979/ArrayReverse/Example.java
> +    }
Обрати внимание, что по условию задачи нужно создать два класса: Main и Example. Плюс, public static void main всегда должен находиться в Main, так как Main ответственен за запуск программы

2024-12-04 11:54 UTC, Kayfral commented on src/main/java/ru/maks1979/ArrayReverse/Example.java
> +        int [] testArray;
лучше объявлять массив так: int[]

2024-12-04 11:54 UTC, Kayfral commented on src/main/java/ru/maks1979/ArrayReverse/Example.java
> +        int [] testArray;
Без пробела между int и []

2024-12-04 11:54 UTC, Kayfral commented on src/main/java/ru/maks1979/ArrayReverse/Example.java
> +    public static int[] reverse (int[]nums) {
а вот тут нужно добавить пробел int[] nums

2024-12-04 11:54 UTC, Kayfral commented on src/main/java/ru/maks1979/ArrayReverse/Example.java
> +            nums[nums.length-1-i] = temp;
Сделай так, чтобы у тебя были одинаковые отступы в теле цикла for

2024-12-04 11:54 UTC, Kayfral commented on src/main/java/ru/maks1979/ArrayReverse/Example.java
> +    }
К самому развороту вопросов нету. Молодец!

Но есть два замечания:
1. Что будет если массив будет равен null или будет пуст? Необходимо добавить проверку
2. Ты методу на обратку передаешь массив nums и его разворачиваешь. Фактически, ты не создаешь новый массив, тогда, ты можешь ничего не возвращать из метода reverse. Другими словами, можешь его сделать void. Так как ты передашь массив, он его развернет и все что требовалось будет готово

2024-12-04 11:54 UTC, Kayfral commented on src/main/java/ru/maks1979/ArrayReverse/Example.java
> +    }
К самому развороту вопросов нету. Молодец!

Но есть два замечания:
1. Что будет если массив будет равен null или будет пуст? Необходимо добавить проверку
2. Ты методу на обратку передаешь массив nums и его разворачиваешь. Фактически, ты не создаешь новый массив, тогда, ты можешь ничего не возвращать из метода reverse. Другими словами, можешь его сделать void. Так как ты передашь массив, он его развернет и все что требовалось будет готово

2024-12-04 11:54 UTC, Kayfral commented on src/main/java/ru/maks1979/ArrayReverse/Example.java
> +        testArray = new int[]{1, 2, 3, 4, 5, 6, 7,9,11};
Добавь пробелы после запятых при наполнение массива

2024-12-04 11:54 UTC, Kayfral commented on src/main/java/ru/maks1979/ArrayReverse/Example.java
> +        testArray = new int[]{1, 2, 3, 4, 5, 6, 7,9,11};
Добавь пробелы после запятых при наполнение массива

2024-12-04 11:54 UTC, Kayfral commented on src/main/java/ru/maks1979/ArrayReverse/Example.java
> +        testArray = new int[]{1, 2, 3, 4, 5, 6, 7,9,11};
Добавь пробелы после запятых при наполнение массива

2024-12-04 16:32 UTC, sanctus-germanus commented on src/main/java/ru/maks1979/ArrayReverse/Example.java
> +    }
Хорошо

2024-12-05 06:12 UTC, Kayfral approved these changes

2024-12-05 06:12 UTC, merged