Maxdrattcev 1 bjs2 45283
CorporationX/god_bless pull request #14405
Opened 2024-12-04 13:50 UTC by MaxDrattcev

1) Создан класс Book с полями, в которых будет содержаться информация о книгах.
2) Создан класс LibrarySystem с методами, при помощи которых можно выполнять следующие действия:
- добавить книгу в мапу;
- удалить книгу из мапы;
- искать номер полки по названию, автору и году издания;
- вывести все книги на экран.
3) создан класс Main, в котором содержится мапа. 
4) в методе main, наполнил мапу новыми книгами, и использовал всем методы класса LibrarySystem.

2024-12-05 19:30 UTC, Kayfral requested changes

2024-12-05 19:30 UTC, Kayfral commented on src/main/java/school/faang/task_45283/Main.java
> +    private static Map<Book, String> books = new HashMap<>();
Зачем тебе тут объявлять HashMap? Ты моешь  объявить её в классе LibrarySystem и не вызывать ее из LibrarySystem по средствам Main.getBooks()

2024-12-05 19:30 UTC, Kayfral commented on src/main/java/school/faang/task_45283/LibrarySystem.java
> +    }
Что будет если книга не найдена? можно просто сделать информативное уведомление

2024-12-05 19:30 UTC, Kayfral commented on src/main/java/school/faang/task_45283/LibrarySystem.java
> +    }
Статика плохо. Ее тяжело тестировать и расширять. Просто в Main LibrarySystem library = new LibrarySystem(); и работай без статики

2024-12-05 19:30 UTC, Kayfral commented on src/main/java/school/faang/task_45283/LibrarySystem.java
> +    }
Можно добавить уведомление о ненайденной книге

2024-12-07 11:45 UTC, MaxDrattcev commented on src/main/java/school/faang/task_45283/LibrarySystem.java
> +    }
Отредактировал методы, добавил необходимые условия.

2024-12-07 11:46 UTC, MaxDrattcev commented on src/main/java/school/faang/task_45283/LibrarySystem.java
> +    }
со всех методов снял статик.

2024-12-07 11:48 UTC, MaxDrattcev commented on src/main/java/school/faang/task_45283/Main.java
> +    private static Map<Book, String> books = new HashMap<>();
Перенес HashMap в класс LibrarySystem

2024-12-07 12:06 UTC, Kayfral commented
Отлично, молодец!!!

2024-12-07 12:06 UTC, Kayfral approved these changes

2024-12-07 12:06 UTC, merged