user registration - alpha release
CorporationX/god_bless pull request #14406
Opened 2024-12-04 13:53 UTC by Maksim-13

Регистрация пользователя

2024-12-04 17:26 UTC, Kayfral requested changes
Вопросов к User нету, но где Main?

2024-12-06 06:06 UTC, Kayfral requested changes

2024-12-06 06:06 UTC, Kayfral commented on src/main/java/school/faang/bjs243751/Main.java
> +        new User("Bob", 25, "Google", "");
У тебя сделана валидация на входные данные. В случае, если эта валидация не пройдена будет исключение. Может тогда нужен блок try catch?

2024-12-06 06:06 UTC, Kayfral commented
Обрати внимание, что у тебя git конфликт. Его нужно исправить

2024-12-07 07:43 UTC, Kayfral commented
Я заметил, что ты не обратил внимание на мои комментарии. С логикой кода все хорошо, но:
1. Добавь пожалуйста блок try catch
2. Еще раз обрати внимание, что у тебя git конфликт
![image](https://github.com/user-attachments/assets/112792c4-6895-4095-88c0-706f64bd7b01)
![image](https://github.com/user-attachments/assets/bfa086f9-4416-4002-9dc0-61d1829f2e88)

Если что-то непонятно, пиши объясню

2024-12-07 10:22 UTC, Maksim-13 commented on src/main/java/school/faang/bjs243751/Main.java
> +        new User("Bob", 25, "Google", "");
Добавил блок  try catch, предлагаю в описании задачи явно указать, что необходим класс Main (в других задачах это есть) и создание разных users, просто в начале есть фраза "Вам поручено создать модуль" т.е. часть от программы, хотя далее есть фраза "Программа должна ".

2024-12-07 11:30 UTC, Kayfral commented on src/main/java/school/faang/bjs243751/Main.java
> +        new User("Bob", 25, "Google", "");
Я не спорю, что можно явно указать, что нужно добавлять, но дальше задачи будут становиться более абстрактными и там не будет столь много описательных блоков

2024-12-07 11:30 UTC, merged