BJS2-45301. Библиотека Вестероса
CorporationX/god_bless pull request #14418
Opened 2024-12-04 15:43 UTC by c00mrade

2024-12-05 19:50 UTC, Kayfral requested changes

2024-12-05 19:50 UTC, Kayfral commented on src/main/java/school/faang/libraryvesterosbjs245301/Main.java
> +    protected static Map<Book, String> numberShelf = new HashMap<>();
Зачем тебе тут объявлять HashMap? Ты моешь объявить её в классе LibrarySystem и не вызывать ее из LibrarySystem по средствам Main.numberShelf()

2024-12-05 19:50 UTC, Kayfral commented on src/main/java/school/faang/libraryvesterosbjs245301/LibrarySystem.java
> +    }
Статика плохо. Ее тяжело тестировать и расширять. Просто в Main LibrarySystem library = new LibrarySystem(); и работай без статики

2024-12-05 23:37 UTC, c00mrade commented on src/main/java/school/faang/libraryvesterosbjs245301/Main.java
> +    protected static Map<Book, String> numberShelf = new HashMap<>();
Делал, как по заданию написано,: В классе Main, создайте HashMap с ключом типа Book и значением типа String (местонахождение книги в библиотеке, например, номер полки

2024-12-05 23:37 UTC, c00mrade commented on src/main/java/school/faang/libraryvesterosbjs245301/LibrarySystem.java
> +    }
согласен, днем поправлю

2024-12-06 14:04 UTC, Kayfral commented on src/main/java/school/faang/libraryvesterosbjs245301/Main.java
> +    protected static Map<Book, String> numberShelf = new HashMap<>();
Да, так написано, но это не совсем правильно, так как если мы берем большие приложения, то там есть логическая связь между компонентами и классами. А здесь в условии задачи эта логика немного нарушена

2024-12-06 14:05 UTC, Kayfral approved these changes

2024-12-06 14:05 UTC, merged

2024-12-06 22:44 UTC, c00mrade commented on src/main/java/school/faang/libraryvesterosbjs245301/Main.java
> +    protected static Map<Book, String> numberShelf = new HashMap<>();
понял, принял)