BJS2-43793: Регистрация пользователя
CorporationX/god_bless pull request #14422
Opened 2024-12-04 16:20 UTC by VladislavZhurbin

- в классе User заданы сеттеры, валидирующие входные параметры

2024-12-04 17:27 UTC, Kayfral requested changes

2024-12-04 17:27 UTC, Kayfral commented on src/main/java/school/faang/task_43793/Main.java
> +    }
У тебя сделана валидация на входные данные. В случае, если эта валидация не пройдена будет исключение. Может тогда нужен блок try catch?

2024-12-06 04:01 UTC, VladislavZhurbin commented on src/main/java/school/faang/task_43793/Main.java
> +    }
Да, поправил. Хотел попробовать вариант сделать, когда при создании пользователя, в случае неудачи, ошибки приходят по всем параметрам, а не только по первой встреченной.

2024-12-06 06:11 UTC, Kayfral approved these changes

2024-12-06 06:11 UTC, merged