Абстракция, абстракция!
CorporationX/god_bless pull request #14420
Opened 2024-12-04 15:55 UTC by porchy21

2024-12-04 20:34 UTC, 20cognosce requested changes

2024-12-04 20:34 UTC, 20cognosce commented on src/main/java/school/faang/task_43853/Archer.java
> +        this.intellect = 5;
Сразу в конструктор передавать, magic number избегать, создать класс-конфиг с статическими дефолтными коэффициентами для каждого героя

2024-12-04 20:34 UTC, 20cognosce commented on src/main/java/school/faang/task_43853/Archer.java
> +        System.out.printf("%s атакует %s и наносит %s урона%n", this.name, character.getName(), this.agility);
Сразу подключай logback + log.info + @Slf4j

2024-12-04 20:34 UTC, 20cognosce commented on src/main/java/school/faang/task_43853/Archer.java
> +        character.setHealth(character.getHealth() - agility);
Объявить переменную healthAfterDamageTaken и её вычислив передавать в сеттер

2024-12-04 20:34 UTC, 20cognosce commented on src/main/java/school/faang/task_43853/Warrior.java
> +public class Warrior extends Character {
Аналогично

2024-12-04 20:34 UTC, 20cognosce commented on src/main/java/school/faang/task_43853/Main.java
> +        Archer archer = new Archer("Фимоз");
Отчаянный бой

2024-12-04 20:34 UTC, 20cognosce commented on src/main/java/school/faang/task_43853/Main.java
> +    public static void fight(Character character1, Character character2) {
Не писать код в мейне
Создай отдельный класс - FightManager

2024-12-04 20:34 UTC, 20cognosce commented on src/main/java/school/faang/task_43853/Main.java
> +        } while (character1.isAlive());
Не симметрично как-то - по одному ты проверяешь в if, а по второму в while
Они должны быть одинаковы по месту и способу проверки

2024-12-04 20:34 UTC, 20cognosce commented on src/main/java/school/faang/task_43853/Character.java
> +    protected int intellect;
private final

2024-12-04 20:34 UTC, 20cognosce commented on src/main/java/school/faang/task_43853/Character.java
> +    protected double health = 100;
private

2024-12-04 20:34 UTC, 20cognosce commented on src/main/java/school/faang/task_43853/Character.java
> +        this.name = name;
Задать дефолтные значения из конфиг-класса

2024-12-05 17:42 UTC, porchy21 commented
Не понял для чего и как правильно сменить модификаторы доступа в классе Character. Как в этом случае следует изменить конструкторы класса? А в классах наследниках каким образом обращаться тогда?

2024-12-05 18:41 UTC, 20cognosce requested changes

2024-12-05 18:41 UTC, 20cognosce commented on src/main/java/school/faang/task_43853/Archer.java
> +    }
Хорошо

2024-12-05 18:41 UTC, 20cognosce commented on src/main/java/school/faang/task_43853/Character.java
> +    protected double health = CHARACTER_HEALTH;
private final всё кроме здоровья

protected можно использовать для констант, которые ты вынес в отдельный класс, но в отдельном класс-конфиге предпочтительнее

2024-12-05 18:41 UTC, 20cognosce commented on src/main/java/school/faang/task_43853/Character.java
> +        this.name = name;
Доделать

2024-12-05 18:41 UTC, 20cognosce commented on src/main/java/school/faang/task_43853/Archer.java
> +    }
Но лучше сразу в конструктор по всем параметрам передать

2024-12-05 18:41 UTC, 20cognosce commented on src/main/java/school/faang/task_43853/FightManager.java
> +                log.error("Mistake: The fight lasts too long");
?
Как может выпасть эта ошибка
И как это связано с длиной боя, которую ты залогировал

2024-12-05 18:41 UTC, 20cognosce commented on src/main/java/school/faang/task_43853/FightManager.java
> +                log.error("Mistake: The fight lasts too long");
Переделать

2024-12-05 18:41 UTC, 20cognosce commented on src/main/java/school/faang/task_43853/FightManager.java
> +    }
Зачем ты написал синглтон))))

2024-12-05 18:41 UTC, 20cognosce commented on src/main/java/school/faang/task_43853/FightManager.java
> +    }
https://www.youtube.com/watch?v=-AlFSe_K27A&ab_channel=VolodyaMozhenkov

2024-12-05 18:41 UTC, 20cognosce commented on src/main/java/school/faang/task_43853/FightManager.java
> +    }
Если тебе нужен синглтон - когда начнем разработку на Spring, его контейнер контекста позволит тебе это достичь (объявить бин)

2024-12-05 19:07 UTC, porchy21 commented on src/main/java/school/faang/task_43853/FightManager.java
> +    }
Чисто логически к этому пришел (ну и так просто симпотнее). Зачем создавать несколько экземпляров класса, у которого нет свойственных этому экземпляру полей, к тому же выполняющий одну функцию. Обычно я в своих проектах использовал синглтон  в таких случаях, я не прав?

2024-12-05 21:29 UTC, 20cognosce approved these changes
Пойдет, давай другую задачу

2024-12-05 21:29 UTC, 20cognosce commented on src/main/java/school/faang/task_43853/Character.java
> +    public Character(String name, int power, int agility, int intellect) {
Ну почему конструктор по имени удалил
Его надо оставить, и в него передавать дефолтные значения для Character

2024-12-05 21:29 UTC, merged