Abstraction, abstraction - alpha release
CorporationX/god_bless pull request #14434
Opened 2024-12-04 18:17 UTC by Maksim-13

Abstraction, abstraction

2024-12-04 21:03 UTC, mysosnovskaya requested changes

2024-12-04 21:03 UTC, mysosnovskaya commented on src/main/java/school/faang/Character.java
> +@Data
Старайся не использовать аннотацию Data, т.к. она включает в себя много других аннотаций. Используй только те из них, которые тебе действительно нужны

2024-12-04 21:03 UTC, mysosnovskaya commented on src/main/java/school/faang/Archer.java
> +        this.setHealth(this.getHealth() - character.getPower());
Логика атаки должна быть наоборот - this атакует персонажа, т.е. здоровье должно измениться у character

2024-12-04 21:03 UTC, mysosnovskaya commented on src/main/java/school/faang/Character.java
> +    private int health = 100;
Молодец, что используешь приватные поля и геттеры/сеттеры для доступа к ним 👍

2024-12-04 21:03 UTC, mysosnovskaya commented on src/main/java/school/faang/Archer.java
> +        this.setIntelligence(5);
Можно воспользоваться родительским конструктором со всеми параметрами. Интересно, почему решил делать через сеттеры?

2024-12-04 21:03 UTC, mysosnovskaya commented on src/main/java/school/faang/Warrior.java
> +    public void attack(@NonNull Character character) {
С NonNull отличное решение 👍

2024-12-04 21:03 UTC, mysosnovskaya commented on src/main/java/school/faang/Warrior.java
> +        this.setHealth(this.getHealth() - character.getPower());
Кстати, нужно ещё гарантировать, что здоровье не будет меньше 0

2024-12-05 10:42 UTC, Maksim-13 commented on src/main/java/school/faang/Warrior.java
> +        this.setHealth(this.getHealth() - character.getPower());
Исправил, однако, условие  реально несколько путанное. Думаю не хватает запятых, и корректно оделить экземпляр класса Warrior(Archer) и персонажа.

2024-12-05 10:43 UTC, Maksim-13 commented on src/main/java/school/faang/Archer.java
> +        this.setIntelligence(5);
Был конструктор без name, исправил

2024-12-05 10:43 UTC, Maksim-13 commented on src/main/java/school/faang/Character.java
> +@Data
Ок

2024-12-05 10:43 UTC, Maksim-13 commented on src/main/java/school/faang/Archer.java
> +        this.setHealth(this.getHealth() - character.getPower());
Исправил

2024-12-05 21:01 UTC, mysosnovskaya requested changes

2024-12-08 19:18 UTC, mysosnovskaya requested changes

2024-12-08 19:18 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs243856/Warrior.java
> +        }
Здесь тогда тоже через Math.max лучше сделать? А то сейчас в коде для двух одинаковых по логике методов используются разные подходы

2024-12-11 12:41 UTC, Maksim-13 commented on src/main/java/school/faang/bjs243856/Warrior.java
> +        }
исправил

2024-12-11 20:36 UTC, mysosnovskaya approved these changes

2024-12-11 20:36 UTC, merged