add task BJS2-43718
CorporationX/god_bless pull request #14446
Opened 2024-12-04 20:31 UTC by MikleBoroda

2024-12-05 06:39 UTC, Kayfral requested changes

2024-12-05 06:39 UTC, Kayfral commented on src/main/java/school/faang/task_bjs43178/User.java
> +            || !VALID_ADDRESSES.contains(address)) {
Конечно можно каждое условие писать на новой строчки, но зачастую их просто пишут в ряд и если длинна строки подходит под свой максимум, то только тогда переносят

2024-12-05 06:39 UTC, Kayfral commented on src/main/java/school/faang/task_bjs43178/Main.java
> +    }
У тебя сделана валидация на входные данные. В случае, если эта валидация не пройдена будет исключение. Может тогда нужен блок try catch?

2024-12-05 15:55 UTC, MikleBoroda commented on src/main/java/school/faang/task_bjs43178/User.java
> +            || !VALID_ADDRESSES.contains(address)) {
Чекстайл говорит что надо так, я локально прогонял, он ругался.

2024-12-06 06:04 UTC, Kayfral approved these changes

2024-12-06 06:04 UTC, merged