BJS2-43644: Развернитесь!
CorporationX/god_bless pull request #14453
Opened 2024-12-04 21:44 UTC by AlejandroQuito

Развернитесь!

2024-12-05 06:35 UTC, Kayfral requested changes

2024-12-05 06:35 UTC, Kayfral commented on src/main/java/school/faang/sprint_1/task_43644/Main.java
> +        int[] example = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
Я бы немного изменил название переменной. Так как она не дает тебе понимания, что она в себе хранит

2024-12-05 06:35 UTC, Kayfral commented on src/main/java/school/faang/sprint_1/task_43644/Example.java
> +    }
К самому развороту вопросов нету. Молодец! Но что будет, если массив будет равен null или будет пуст? Необходимо добавить проверку

2024-12-05 06:35 UTC, Kayfral commented on src/main/java/school/faang/sprint_1/task_43644/Example.java
> +*/
Круто, что ты смог развернуть двумя способами, но нужно оставить только один (я за верхний). А тот, который в комментариях убрать. И просто сделаю ремарку, код должен говорить сам за себя. Следовательно, в нем не должно быть комментариев. Если в коде есть комментарии, то заначит, что код можно улучшить и убрать коменты

2024-12-05 13:49 UTC, AlejandroQuito commented on src/main/java/school/faang/sprint_1/task_43644/Main.java
> +        int[] example = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
Я же правильно понимаю, что лучше сделать что-то вроде: array или arrayOfIntegers?

2024-12-06 06:02 UTC, Kayfral commented on src/main/java/school/faang/sprint_1/task_43644/Main.java
> +        int[] example = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
Да

2024-12-06 06:02 UTC, Kayfral approved these changes

2024-12-06 06:02 UTC, merged