Разбираем склад Amazon. Initial commit
CorporationX/god_bless pull request #14499
Opened 2024-12-05 10:16 UTC by almigor1

2024-12-05 21:51 UTC, mysosnovskaya requested changes

2024-12-05 21:51 UTC, mysosnovskaya commented on src/main/java/school/faang/task45150/service/ProductCatalogue.java
> +    private static int productId = 1;
почему static?

2024-12-05 21:51 UTC, mysosnovskaya commented on src/main/java/school/faang/task45150/service/ProductCatalogue.java
> +    Map<String, List<Product>> groupedProducts = new HashMap<>();
А здесь модификаторов не хватает)

2024-12-05 21:51 UTC, mysosnovskaya commented on src/main/java/school/faang/task45150/service/ProductCatalogue.java
> +    Map<String, List<Product>> groupedProducts = new HashMap<>();
Из названия поля не ясно, по какому признаку сгруппированы продукты. Так что нужно подобрать более понятное название

2024-12-05 21:51 UTC, mysosnovskaya commented on src/main/java/school/faang/task45150/service/ProductCatalogue.java
> +        productList.removeIf(product -> product.getName().equals(name));
Я бы ещё изначально убедилась, что productList != null

2024-12-05 21:51 UTC, mysosnovskaya commented on src/main/java/school/faang/task45150/Main.java
> +        productSet.add(new Product(3, "Dairy", "Yogurht"));
Конечно, мелочь, но перебор с буквами в йогурте =) Должно быть Yogurt

2024-12-05 21:51 UTC, mysosnovskaya commented on src/main/java/school/faang/task45150/model/Product.java
> +@Data
Data использовать не рекомендуется, т.к. эта аннотация включает в себя много других. Лучше использовать точечно только необходимые аннотации

2024-12-05 21:51 UTC, mysosnovskaya commented on src/main/java/school/faang/task45150/model/Product.java
> +    public Product(Integer id, String category, String name) {
А конструктор от ломбока не подойдет? Зачем нужен свой самописный?)

2024-12-06 12:10 UTC, almigor1 commented on src/main/java/school/faang/task45150/service/ProductCatalogue.java
> +    private static int productId = 1;
потому что я устроил сквозную нумерацию по всем объектам этого класса.

2024-12-06 12:26 UTC, almigor1 commented on src/main/java/school/faang/task45150/model/Product.java
> +    public Product(Integer id, String category, String name) {
там какая то бредовая ситуация, ломбок не сумел порядок поля в конструкторе соблюсти также, как они объявлены в классе. В итоге у меня почему-то подсказки были неудобно сделаны, ну и далее еще какая то путаница с инициализацией полей. имя и категория перепутывались. 
Вот сейчас снова вернул ломбоковский конструктор и убрал свой - снова путаница.

2024-12-06 18:50 UTC, mysosnovskaya commented on src/main/java/school/faang/task45150/service/ProductCatalogue.java
> +    private static int productId = 1;
Поняла, пусть остается)

2024-12-06 18:51 UTC, mysosnovskaya commented on src/main/java/school/faang/task45150/service/ProductCatalogue.java
> +    private final Map<String, List<Product>> groupedByCategoryProducts = new HashMap<>();
Лучше назвать productsGroupedByCategory или даже просто productsByCategory

2024-12-06 18:51 UTC, mysosnovskaya commented on src/main/java/school/faang/task45150/model/Product.java
> +
Лишняя пустая строка) Удали, пожалуйста

2024-12-06 18:54 UTC, mysosnovskaya commented on src/main/java/school/faang/task45150/model/Product.java
> +    public Product(Integer id, String category, String name) {
Ломбок делает порядок такой же, как порядок полей в классе, а твоем текущем конструкторе как раз этот порядок нарушен. Давай всё-таки разберемся с проблемой (можешь написать в наш командный чат, приложить скрины, я там оперативнее отвечу, чем здесь). Решения, которые мы принимаем как разработчики, должны быть аргументированы. Если что-то не получилось сделать - это не аргумент) Нужно разбираться

2024-12-06 18:55 UTC, mysosnovskaya commented on src/main/java/school/faang/task45150/service/ProductCatalogue.java
> +        if (category.isEmpty()) throw new IllegalArgumentException("Category is empty");
Чекстайл ругается на эти две строки. Тело if-выражения всегда пишется на новой строке и обязательно нужны фигурные скобки, даже если тело состоит всего из одной строки. Такой стиль в джаве :) Поправь, пожалуйста, здесь и строчкой ниже. И сборка пройдет)

2024-12-08 19:52 UTC, mysosnovskaya reviewed
Один коммент остался не исправленным - написала подробнее. После этого будем мержить)

2024-12-08 19:52 UTC, mysosnovskaya commented on src/main/java/school/faang/task45150/service/ProductCatalogue.java
> +    private final Map<String, List<Product>> groupedByCategoryProducts = new HashMap<>();
Не понравились мои предложения?) По правилам английского языка сначала идет подлежащее (продукты), а потом - дополнения (сгруппированные по категориям).

2024-12-09 21:11 UTC, almigor1 commented on src/main/java/school/faang/task45150/service/ProductCatalogue.java
> +    private final Map<String, List<Product>> groupedByCategoryProducts = new HashMap<>();
не, похоже зарезолвил ошибочно

2024-12-09 21:24 UTC, mysosnovskaya approved these changes

2024-12-09 21:24 UTC, merged