init commit - solved the problem
CorporationX/god_bless pull request #14514
Opened 2024-12-05 12:34 UTC by lcodio

2024-12-05 21:16 UTC, mysosnovskaya requested changes

2024-12-05 21:16 UTC, mysosnovskaya commented on src/main/java/school/faang/s12task43865/Archer.java
> +    private static final int INTELLIGENCE = 5;
С константами хорошо 👍

2024-12-05 21:16 UTC, mysosnovskaya commented on src/main/java/school/faang/s12task43865/Archer.java
> +        opponent.health -= agility;
По условию задачи здоровье должно уменьшаться только у противника:

>  У противника отнимается столько же очков здоровья, сколько он получает урона.

А атакующий (this) здоровье не теряет

2024-12-05 21:16 UTC, mysosnovskaya commented on src/main/java/school/faang/s12task43865/Archer.java
> +        opponent.health -= agility;
Для доступа к полям всегда лучше использовать геттеры и сеттеры, а сами поля сделать приватными в родителе. Это поможет соблюдать принцип инкапсуляции :)

2024-12-05 21:16 UTC, mysosnovskaya commented on src/main/java/school/faang/s12task43865/Character.java
> +    int health = 100;
Нужны модификаторы доступа

2024-12-05 21:16 UTC, mysosnovskaya commented on src/main/java/school/faang/s12task43865/Warrior.java
> +        opponent.health -= strength;
И кстати, здоровье не может быть меньше нуля - нужно за этим следить. В текущей реализации это возможно

2024-12-13 14:16 UTC, 20cognosce commented on src/main/java/school/faang/s12task43865/Archer.java
> +        opponent.health -= agility;
Не обращаться к полям напрямую, это нарушает инкапсуляцию объектов

2024-12-13 14:17 UTC, 20cognosce commented on src/main/java/school/faang/s12task43865/Warrior.java
> +        if (opponent.health <= strength) {
Эта проверка выглядит непонятно, сделай тогда метод, отдающий урон пользователя
и сравнивай и вычитай урон

2024-12-13 14:19 UTC, merged