Andrey s nosov bjs2 43729
CorporationX/god_bless pull request #14572
Opened 2024-12-05 22:48 UTC by andruxaUZB

На проверку

2024-12-06 17:22 UTC, Kayfral requested changes

2024-12-06 17:22 UTC, Kayfral commented on src/main/java/school/faang/task_43729/User.java
> +                | !VALID_JOBS.contains(job)
Заметил, что в методе checkValidity ты используешь побитовый OR (|). Давай заменим его на логический OR (||) - так код будет читаться легче, и логика будет работать корректнее. И так же можно не переносить проверку на новую строку, а писать одной

2024-12-06 17:22 UTC, Kayfral commented on src/main/java/school/faang/task_43729/User.java
> +    private String address;
Предлагаю перенести приватные поля в начало класса, перед методами. Так структура класса станет более понятной и будет соответствовать общепринятым стандартам.

2024-12-06 17:22 UTC, Kayfral commented on src/main/java/school/faang/task_43729/Main.java
> +    System.out.println(user);
Здесь два замечания:
1) между запятыми должен быть пробел
2) А что будет если пользователь не пройдет валидацию? У тебя будет исключение, может тогда нужен блок try catch?

2024-12-06 17:22 UTC, Kayfral commented on src/main/java/school/faang/task_43729/Main.java
> +
Тут одного отступа хватит

2024-12-06 17:22 UTC, Kayfral commented on src/main/java/school/faang/task_43729/User.java
> +    }
Смотри, у тебя метод initDefaultJobAndAddresses() вызывается при каждой валидации. Давай сделаем проще: инициализируй VALID_JOBS и VALID_ADDRESSES сразу при объявлении через Set.of(). Код станет эффективнее и понятнее.

2024-12-06 19:35 UTC, andruxaUZB commented on src/main/java/school/faang/task_43729/Main.java
> +    System.out.println(user);
а как в IntelliJ Idea отключить временно отображение названия аргументов?, что бы потом проверять....?

2024-12-07 07:39 UTC, Kayfral requested changes

2024-12-07 07:39 UTC, Kayfral commented on src/main/java/school/faang/task_43729/User.java
> +    }
Все отлично, к финальной версии кода у меня нету вопросов. Оброти внимание на checkstyle, он ругается на эти строчки
![image](https://github.com/user-attachments/assets/0909ef67-9279-4398-a72d-b864643ce992)

2024-12-07 11:25 UTC, merged