Anton graf bjs2 45147
CorporationX/god_bless pull request #14635
Opened 2024-12-06 15:03 UTC by AntonGraf

Решение задачи "Разбираем склад Amazon"

2024-12-07 15:22 UTC, 20cognosce requested changes

2024-12-07 15:22 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Product.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
Никогда не использовать

2024-12-07 15:22 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Product.java
> +    int id;
private final все поля

2024-12-07 15:22 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Product.java
> +    final String category;
категория - Enum

2024-12-07 15:22 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Product.java
> +    }
Удалить
В этой задаче не нужно их переопределять

А когда нужно - делать это аннотациями

2024-12-07 15:22 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Product.java
> +    int id;
Ты можешь просто id сравнивать, зачем тебе equals менять

2024-12-07 15:22 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +import java.util.*;
Писал уже в другом ПРе

2024-12-07 15:22 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
.

2024-12-07 15:22 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +    }
Сразу присваивать поля

2024-12-07 15:22 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +            int id = productCounter.getAndIncrement();
Этого здесь быть не должно, сделай другой класс - генератор id
Лучше объект в принципе создавать в другом месте, а сюда принимать только собранный

2024-12-07 15:22 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +        if (!products.contains(product)) {
id - идентифицирует каждый продукт, это уникальный ключ
Наверно для упрощения можно принять, что генератор id всегда возвращает уникальный, поэтому проверка эта не нужна.

Но если хочешь гарантии на уровне сета - наверно да, надо переопределить equals и hashcode
Но если брать только по айди - этого будет достаточно

2024-12-07 15:22 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +        }
не вызывать contains без необходимости
что есть объект, что нет - remove отработает одинаково

Сравнивай результат удаления для выбрасывания ошибки

2024-12-07 15:22 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +        Product product = new Product(name, category, 0);
Что это за странности с id? Зачем ты добавляешь 0
Тебе нужно проитерировать все элементы на проверку категории и имени, потому что только айди уникальны

2024-12-07 15:22 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +                .filter(product -> product.getCategory().equals(category))
getCategory == null -> NPE
Objects.equals

2024-12-07 15:22 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +        Map<String, List<Product>> groupedProducts = new HashMap<>();
Может хранить полем? Чтобы каждый раз не пересоздавать
И заполнять в каждой операции

2024-12-07 15:22 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +        log.info(products.toString());
Здесь нужно вывести в сгруппированном по категориям виде

2024-12-07 15:22 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +        Product product = new Product(name, category, 0);
А у тебя удаление не по айди, поэтому ты заранее не знаешь, кого именно надо удалить

2024-12-08 09:37 UTC, AntonGraf commented on src/main/java/school/faang/bjs_45147/Product.java
> +    final String category;
не получается сделать Enum. В условиях - Если категории нет, создайте её.

2024-12-08 09:39 UTC, AntonGraf commented on src/main/java/school/faang/bjs_45147/Store.java
> +        Map<String, List<Product>> groupedProducts = new HashMap<>();
Добавил Map  с группировкой по категорией для всех продуктов. В этом методе предполагается группировка определенного множества продуктов не обязательно всех

2024-12-08 19:43 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Product.java
> +    final String category;
Имеется в виду создать Entry в мапе по этой категории, если еще нет ни одного товара такой категории в мапе
Не вижу здесь противоречия

2024-12-08 19:58 UTC, 20cognosce approved these changes

2024-12-08 19:58 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/GeneratorId.java
> +}
Хорошо, для этого модуля это наиболее приемлемый вариант

2024-12-08 19:58 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +    }
Не нужно писать методы, состоящие из одной строчки кода
Декомпозиция - хорошо, но всё хорошо в меру

2024-12-08 19:58 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +        return products.stream().anyMatch(product -> checkProductName(product, name)
Каждый вызов метода стрима с новой строчки
.anyMatch
.map
.collect

2024-12-08 19:58 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +                && checkProductCategory(product, category)).findFirst().orElseThrow(ProductNotFoundException::new);
Не лепииииииииить

2024-12-08 19:58 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +        }
putIfAbsent

2024-12-08 19:58 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +        return products.stream().anyMatch(product -> product.getId() == id);
Через == не сравнивать, это некорректно
Пул интов погугли
![image](https://github.com/user-attachments/assets/e4ef538a-22d2-4ae3-b926-11782f4a2f5a)

Через Objects.equals следует

2024-12-08 19:58 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +        groupedProducts.entrySet().forEach(entry -> log.info(entry.toString()));
toString можно вроде не вызывать

2024-12-08 19:58 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +            }
Objects.equals и проверку не надо городить

2024-12-08 19:58 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +        }).collect(Collectors.toUnmodifiableSet());
Отформатировать работу со стримом

2024-12-08 19:58 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +        return products.stream().filter(product -> {
и зачем тебе тут фильтрация, если у тебя уже есть мапа с группированными продуктами

2024-12-08 19:58 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +        if (!isProductByNameAndCategory(name, category)) {
Я не понял условие в скобках, более доходчиво переписать, какие ты делаешь проверки и на что

2024-12-08 19:58 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Product.java
> +    private final String category;
Насчёт Enum подумай, не понимаю почему не получилось у тебя

2024-12-08 19:59 UTC, 20cognosce requested changes
Промахнулся.
Надо доработать.

2024-12-09 03:18 UTC, AntonGraf commented on src/main/java/school/faang/bjs_45147/Store.java
> +        groupedProducts.entrySet().forEach(entry -> log.info(entry.toString()));
без него  - Cannot resolve method

2024-12-09 03:26 UTC, AntonGraf commented on src/main/java/school/faang/bjs_45147/Store.java
> +    }
убрал

2024-12-09 03:42 UTC, AntonGraf commented on src/main/java/school/faang/bjs_45147/Store.java
> +        return products.stream().anyMatch(product -> product.getId() == id);
Про пул интов слышал, но не использовал так

2024-12-09 05:57 UTC, AntonGraf commented on src/main/java/school/faang/bjs_45147/Product.java
> +    private final String category;
Смог только так заменить на Enum.

2024-12-09 13:56 UTC, 20cognosce approved these changes
В целом нормально, принято

2024-12-09 13:56 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/enums/Category.java
> +                .filter(category -> categoryName.equalsIgnoreCase(category.getName()))
categoryName = null? Ошибка
Есть что-то типо Strings.equalsIgnoreCase(string1, string2)?

2024-12-09 13:56 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/enums/Category.java
> +                .findFirst().orElseThrow(CategoryNotFoundException::new);
А если несколько енамов с одинаковым именем
Лучше ошибку кидать, если найдено больше чем 1

2024-12-09 13:56 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/enums/Category.java
> +    }
Поле name заводить не обязательно
FRUITS.name() - "FRUITS"
Весь внутрипрограммный код лучше делать на латинице, для пользователя на русский переведёт фронтенд

Или какой-нибудь отдельный модуль для локализации можно запилить, но если можно латиницу - лучше её придерживаться

2024-12-09 13:56 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +                && product.getCategory().getName().equalsIgnoreCase(category));
Когда длинное условие после лямбды можно открыть скобки -> { code }
product.getCategory().getName().equalsIgnoreCase(category)
Закон Деметры погугли, в я говорил не лепить вызовы

2024-12-09 13:56 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +        List<Product> productByCategory = groupedProducts.get(product.getCategory().getName());
.

2024-12-09 13:56 UTC, 20cognosce commented on src/main/java/school/faang/bjs_45147/Store.java
> +                .anyMatch(product -> Integer.valueOf(product.getId()).equals(id));
.

2024-12-09 13:56 UTC, merged