BJS2-45255
CorporationX/god_bless pull request #14647
Opened 2024-12-06 18:42 UTC by Narol01

2024-12-06 20:28 UTC, 20cognosce requested changes
Имена методов не соответствуют тому, что они делают
Сделать понятный нейминг и желательно по очереди из условия, чтобы я понял, что ты именно делал

2024-12-06 20:28 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/Main.java
> +    public static void main(String[] args) {
Я говорил не писать код в мейне, что это за try catch
IllegalArgument непроверяемое исключение ведь, не обязательно оборачивать

2024-12-06 20:28 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/entity/Subject.java
> +@EqualsAndHashCode(of = "id")
Только в задачах на мапу это приемлемо, но вообще такого быть не должно

2024-12-06 20:28 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/StudentDatabase.java
> +        subjects.put(subject, note);
Не понял
Map<Subject, List<Student>> subjects
Ты вызываешь .put(subject, note);
Как в список студентов ты передал Integer note? 

Что вообще такое note

2024-12-06 20:28 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/StudentDatabase.java
> +    public void addStudents(Student student, Subject subject, Integer note) throws IllegalArgumentException {
Может mark? Оценка

2024-12-06 20:28 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/StudentDatabase.java
> +    public void addStudents(Student student, Subject subject, Integer note) throws IllegalArgumentException {
почему addStudents, если ты только одного принимаешь

2024-12-06 20:28 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/StudentDatabase.java
> +        subjects.put(subject, note);
Ааа, у тебя и поле и локальная переменная одинаково называются
Понятно, это бан

2024-12-06 20:28 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/StudentDatabase.java
> +    public void removeStudents(Student student) throws IllegalArgumentException {
почему во множественном числе

2024-12-06 20:28 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/StudentDatabase.java
> +        students.remove(student);
Ну опять, ну блин
Ты делаешь два одинаковых действия
Делай сразу remove, по его результату узнаешь - был такой или нет

2024-12-06 20:28 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/StudentDatabase.java
> +    public void addSubjects(Subject subject, Student student) {
.

2024-12-06 20:28 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/StudentDatabase.java
> +        subjects.remove(subject);
.

2024-12-06 20:28 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/StudentDatabase.java
> +
Кому пустые строки

2024-12-06 20:28 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/StudentDatabase.java
> +    public void removeSubjects(Subject subject) throws IllegalArgumentException {
Удаление студента из предмета
У тебя - removeSubjects

2024-12-06 20:28 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/StudentDatabase.java
> +    public void addSubjects(Subject subject, Student student) {
Добавление студента к существующему предмету
У тебя - addSubjects

2024-12-06 20:28 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/StudentDatabase.java
> +public class StudentDatabase {
Добавление нового предмета и списка студентов, изучающих его
Не вижу

2024-12-06 20:28 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/StudentDatabase.java
> +        students.forEach((key, value) -> System.out.println("Student " + key.getName() + " " + value));
Вывод списка всех студентов и их оценок по предметам
Просто вызов value что выводит? Пришли на гитхабе скрин, как там оценки и предметы показываются в консоли

2024-12-06 23:03 UTC, Narol01 commented on src/main/java/school/faang/task_45255/StudentDatabase.java
> +        students.forEach((key, value) -> System.out.println("Student " + key.getName() + " " + value));
![image](https://github.com/user-attachments/assets/8ef7e090-96a6-4697-90fc-cc181015058c)

2024-12-07 10:00 UTC, 20cognosce approved these changes
Валидация занимает половину самих методов, в следующие разы надо выносить
Приму - делай другие задачи

2024-12-07 10:00 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/Main.java
> +        studentList.add(student3);
Жестко
Можно было бы в методы отдельные вынести
А лучше тесты написать

2024-12-07 10:00 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/StudentDatabase.java
> +        });
Это всё - валидация, ответственность другого класса, или хотя бы метода

2024-12-07 10:00 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/StudentDatabase.java
> +        Map<Subject, Integer> copyOfSubjectMarks = new HashMap<>(subjectMarks);
Почему копия берешь? subjectMarks будут модифицировать извне?

2024-12-07 10:00 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/StudentDatabase.java
> +        }
.

2024-12-07 10:00 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/StudentDatabase.java
> +        }
.

2024-12-07 10:00 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/StudentDatabase.java
> +        }
null означает, что предмета такого нет
а пустой список не обработан - это говорит, что студентов нет

2024-12-07 10:00 UTC, 20cognosce commented on src/main/java/school/faang/task_45255/StudentDatabase.java
> +        studentsInSubjects.remove(student);
Опять на те же грабли
Скажи, зачем ты два раза делаешь одну работу

2024-12-07 10:00 UTC, merged