Almigor bjs2 45240
CorporationX/god_bless pull request #14643
Opened 2024-12-06 17:26 UTC by almigor1

2024-12-06 19:02 UTC, mysosnovskaya requested changes

2024-12-06 19:02 UTC, mysosnovskaya commented on src/main/java/school/faang/task45240/model/Subject.java
> +    public static final Subject MATH = new Subject("Math");
Не думаю, что этим полям место в этом классе. Можно создать отдельный класс или вынести эти поля в Main. В идеале вообще через enum сделать) Это, конечно, небольшое отступление от задания, но логика в том виде, в котором ты её сейчас реализовал (через константы) лучше будет выглядеть с применением перечислений

2024-12-08 20:07 UTC, mysosnovskaya requested changes

2024-12-08 20:07 UTC, mysosnovskaya commented on src/main/java/school/faang/task45240/services/StudentDatabase.java
> +        for (Subject subject : subjectStudents.keySet()) {
Нам не нужно проходить вообще во всем предметам. В целях оптимизации лучше пройти только по тем предметам, которые студент точно изучал. Это мы можем получить из studentGrades (по логике там должны быть все предметы, которые студент изучает, только какие-то из них могут быть ещё без оценок - вместо оценки просто null)

2024-12-08 20:07 UTC, mysosnovskaya commented on src/main/java/school/faang/task45240/model/Subject.java
> +    }
То же самое можно сделать через ломбок, используя EqualsAndHashCode.Include (или Exclude) - посмотри про это, так будет симпатичнее)

2024-12-09 21:06 UTC, almigor1 commented on src/main/java/school/faang/task45240/model/Subject.java
> +    }
ok

2024-12-09 21:25 UTC, mysosnovskaya approved these changes

2024-12-09 21:25 UTC, merged