BJS2-44617 Ловим события
CorporationX/god_bless pull request #14650
Opened 2024-12-06 20:16 UTC by rsticks

2024-12-08 19:37 UTC, mysosnovskaya requested changes

2024-12-08 19:37 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs244617/HogwartsSpells.java
> +@AllArgsConstructor
Точно нужен?)

2024-12-08 19:37 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs244617/SpellEvent.java
> +    private SpellType eventType;
Нужен ли final?

2024-12-08 19:37 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs244617/SpellEvent.java
> +    public enum SpellType {
Круто, что сделал enum 👍

2024-12-08 19:37 UTC, mysosnovskaya commented on src/test/java/school/faang/bjs244617/HogwartsSpellsTest.java
> +public class HogwartsSpellsTest {
Можно ещё добавить тесты на граничные случае: попытка добавить дубликат или удалить несуществующий объект

2024-12-08 20:23 UTC, mysosnovskaya requested changes

2024-12-08 20:23 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs244617/SpellEvent.java
> +    private int id;
Здесь тоже final. Идентификатор объект никогда не предполагает изменений)

2024-12-08 20:23 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs244617/HogwartsSpells.java
> +@Getter
А зачем геттер? Если мы дадим возможность кому угодно смотреть на поля spellById и spellsByType, то они смогут внести в эти хэш-мапы любые изменения: удалить там все данные или добавить любые, или обновить существующие. В общем, будет полный хаос) Методы для взаимодействия с этими двумя хэш мапами должны быть только в этом классе и никто из вне не должен иметь возможности их как-то изменить в обход предоставленных методов

2024-12-08 20:28 UTC, rsticks commented on src/main/java/school/faang/bjs244617/HogwartsSpells.java
> +@Getter
геттеры чтоб как-то проверить тестами - чтоб не зависеть от методов которые возвращают какую-то информацию (вдруг вдруг баг там)

2024-12-09 20:30 UTC, mysosnovskaya requested changes

2024-12-09 20:30 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs244617/HogwartsSpells.java
> +@Getter
Но получается, что из-за тестов ты делаешь потенциальную проблему в основном коде (описала выше - в любом другом классе можно будет полностью очистить содержимое хэш мап или каким угодно образом обновить хранящиеся там данные). Так не пойдет)
Если что-то нужно только для тестов - это не нужно. 
В тестах ты можешь либо пользоваться java reflection для доступа к полям, к которым доступа быть не должно (мне этот вариант не нравится), либо тестировать с помощью тех методов, которые есть. Сделал addSpellEvent, через getSpellEventById проверил, что ивент возвращается. На самом деле тебя в тестах не должна интересовать внутренняя структура класса (может там не в хэш мапах всё хранится, а в списках?), тебе важен результат. Если ты сделал addSpellEvent, значит затем ты можешь этот объект получать и удалять. Если это так - значит всё верно)

2024-12-09 21:23 UTC, mysosnovskaya approved these changes

2024-12-09 21:23 UTC, merged