BJS2-45248 Task08. LibrarySystem
CorporationX/god_bless pull request #14668
Opened 2024-12-07 03:58 UTC by Mike-GB22

Условие задачи:

В королевстве Вестероса хранится огромное количество книг, и король поручил вам создать систему учёта этих книг, чтобы обеспечить легкий доступ к ним для жителей королевства. Вы решаете создать программу на Java, используя HashMap для хранения книг и их авторов.

Цель:

Создайте программу на Java, которая будет хранить информацию о библиотеке королевства, используя HashMap для хранения книг и их авторов. Вам нужно будет учесть особенности методов equals и hashCode.

Требования:

Создайте класс Book с полями:

title;

author;

year.

Переопределите методы equals и hashCode в классе Book, чтобы учитывать название книги, автора и год издания при сравнении книг и расчёте их хэш-кода.

В классе Main, создайте HashMap с ключом типа Book и значением типа String (местонахождение книги в библиотеке, например, номер полки).

Добавьте информацию о нескольких книгах в ваш HashMap.

Реализуйте следующие методы в классе LibrarySystem:

addBook(String title, String author, int year, String location) — добавляет новую книгу с её местонахождением в библиотеке.

removeBook(String title, String author, int year) — удаляет книгу из библиотеки по её названию, автору и году издания.

findBook(String title, String author, int year) — ищет книгу по названию, автору и году издания и выводит информацию о её местонахождении в библиотеке. Если книга не найдена, метод должен сообщить об этом.

printAllBooks() — выводит полный список всех книг в библиотеке и их местонахождение.

Тестируйте вашу программу, выполняя различные операции с HashMap и убедитесь, что она работает корректно, учитывая переопределенные методы equals и hashCode.

2024-12-07 18:06 UTC, Kayfral requested changes

2024-12-07 18:06 UTC, Kayfral commented on src/main/java/derschrank/task08/bjstwo_45248/LibrarySystem.java
> +    }
Я бы добавил некоторые информативные сообщения в случае если обращаются к книге которой нету.  Чтобы дать пользователю понять, что книги нет в библиотеке (при поиске), или книги не было в библиотеке (при удалении)

2024-12-07 18:06 UTC, Kayfral commented on src/main/java/derschrank/task08/bjstwo_45248/LibrarySystem.java
> +    }
Немного перемудрил можно же сделать так:
 public void addBook(String title, String author, int year, String location) {
        Book book = new Book(title, author, year);
        booksByLocationMap.put(book, location);
    }
    
И тогда не придется заниматься перегрузкой методов

2024-12-07 23:47 UTC, Mike-GB22 commented on src/main/java/derschrank/task08/bjstwo_45248/LibrarySystem.java
> +    }
так я как раз смерился с тем что от меня требуют работать с отдельными частями книги (имя, автор, год).
у меня это выходит за уровень мышления. Есть книга, есть ее место.

Ну раз требуют чтоб я мог книгу добавлять и искать по отдельным параметрам, из по объекте Книга, 
Удалить методы которые работают с книгой как объектом?

2024-12-08 06:55 UTC, Kayfral commented on src/main/java/derschrank/task08/bjstwo_45248/LibrarySystem.java
> +    }
Да, я увидел твою логику. И если мы уйдем немнгого за рамки данной задачи, то можем увидеть, что мы будем работать не только с параметрами книги, но и с Book book, тогда перегрузка уместна

2024-12-08 06:55 UTC, Kayfral approved these changes

2024-12-08 06:55 UTC, merged