Madmax bjs2 45280
CorporationX/god_bless pull request #14693
Opened 2024-12-07 11:39 UTC by Maksim-13

BJS2_45280 Double Cache-Cache - release

2024-12-10 21:12 UTC, mysosnovskaya requested changes

2024-12-10 21:12 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs245280/Main.java
> +        studentDatabase = new StudentDatabase(subjectGradleByStudent, studentBySubject);
Это можно (и лучше) сделать в одной строке: сразу объявил и сразу инициализировал

2024-12-10 21:12 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs245280/Main.java
> +                .findFirst().orElse(null);
Отличное применение стримов 👍

2024-12-10 21:12 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs245280/Student.java
> +        return this.name;
Может как-то поумнее этот метод сделать?)

2024-12-10 21:12 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs245280/Student.java
> +    public String toString() {
Добавь Override - так принято для всех методов, которые что-то переопределяют

2024-12-10 21:12 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs245280/StudentDatabase.java
> +    // Добавление нового студента и его предметов с оценками.
Комментарии лучше не подписывать. Имена методов должны говорить сами за себя, без дополнительных пояснений

2024-12-10 21:12 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs245280/StudentDatabase.java
> +            studentBySubject.putIfAbsent(subject, new ArrayList<>());
putIfAbsent 👍

2024-12-10 21:12 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs245280/StudentDatabase.java
> +        if (this.subjectGradleByStudent.containsKey(student)) {
this лучше не писать

2024-12-10 21:12 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs245280/StudentDatabase.java
> +
А иначе - нужно хоть сообщение об ошибке вывести, а лучшее вообще исключение выкинуть, что такого студента у нас нет. А то метод завершится успешно и никто и не узнает, что на самом деле действие не выполнено

2024-12-10 21:12 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs245280/StudentDatabase.java
> +    private final Map<Student, Map<Subject, Integer>> subjectGradleByStudent;
Вместо gradle должно быть grade (оценка), наверное?)

2024-12-11 12:52 UTC, Maksim-13 commented on src/main/java/school/faang/bjs245280/Student.java
> +    public String toString() {
Ок, добавил

2024-12-11 12:53 UTC, Maksim-13 commented on src/main/java/school/faang/bjs245280/StudentDatabase.java
> +    // Добавление нового студента и его предметов с оценками.
Ок

2024-12-11 12:54 UTC, Maksim-13 commented on src/main/java/school/faang/bjs245280/StudentDatabase.java
> +        if (this.subjectGradleByStudent.containsKey(student)) {
ок

2024-12-11 20:49 UTC, mysosnovskaya approved these changes

2024-12-11 20:49 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs245280/Student.java
> +        return this.name;
Просто в данной реализации toString не имеет смысла - вместо него можно и getName вызывать. Обычно в toString реализуется какой-то красивый вывод на экран. Например, "Student with name = Alex" или хотя бы "Student Alex"

2024-12-11 20:49 UTC, merged