BJS2-44538 [Ловим события]
CorporationX/god_bless pull request #14707
Opened 2024-12-07 14:07 UTC by Iv-an-s

2024-12-08 19:29 UTC, mysosnovskaya requested changes

2024-12-08 19:29 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/task_43513/HogwartsSpells.java
> +    }
Зачем?)

2024-12-08 19:29 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/task_43513/SpellEvent.java
> +public record SpellEvent(int id, String eventType, String action) {
О, java record! Круто 👍

2024-12-08 19:29 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/task_43513/HogwartsSpells.java
> +    private static HogwartsSpells hogwartsSpells;
Зачем это поле? Ты можешь в main создать нужный тебе экземпляр. Или ты хотел сделать singletone и неизменяемый класс? Тогда конструктор должен быть приватным)

2024-12-08 19:29 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/task_43513/HogwartsSpells.java
> +@Getter
Геттер выглядит лишним, т.к. если дать доступ к нашим HashMap снаружи, то в них можно будет складывать что угодно в обход наших методов. И удалять тоже. А нам нужно, чтобы работа с этими хэш-мапами велась только с помощью тех методов, которые есть в этом классе. И никак иначе

2024-12-10 12:00 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/task_43513/HogwartsSpells.java
> +    }
Промахнулся, хотел сделать приватным. Цель - синглтон.

2024-12-10 12:00 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/task_43513/SpellEvent.java
> +public record SpellEvent(int id, String eventType, String action) {
😊

2024-12-10 12:01 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/task_43513/HogwartsSpells.java
> +    private static HogwartsSpells hogwartsSpells;
Да, хотел сделать класс синглтоном, но что-то пошло не так :) Поправил на private

2024-12-10 12:06 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/task_43513/HogwartsSpells.java
> +@Getter
Да, точно, лишний!  Убрал.

2024-12-10 20:34 UTC, mysosnovskaya approved these changes

2024-12-10 20:34 UTC, merged