add cache-cache
CorporationX/god_bless pull request #14702
Opened 2024-12-07 13:37 UTC by bortsovamaria

2024-12-08 19:44 UTC, mysosnovskaya requested changes

2024-12-08 19:44 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44825/WeatherCacheTemplate.java
> +public abstract class WeatherCacheTemplate {
Предлагаю методы в классе организовать в другом порядке:
сначала абстрактный, потом публичные и в конце - приватный

2024-12-08 19:44 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44825/WeatherService.java
> +        Random random = new Random();
Можно сделать полем класса, чтобы не создавать при каждом вызове метода

2024-12-08 19:44 UTC, mysosnovskaya commented on src/test/java/school/faang/task_44825/DataInitializerUtils.java
> +        return new HashMap<>() {{
А почему не Map.of?

2024-12-08 19:44 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44825/WeatherService.java
> +        return new WeatherData(city, random.nextDouble(), random.nextDouble(), System.currentTimeMillis());
Для правдоподобности (и для практики работы с Random), можно задать минимальное и максимальное значение для температуры и влажности

2024-12-09 07:41 UTC, bortsovamaria commented on src/test/java/school/faang/task_44825/DataInitializerUtils.java
> +        return new HashMap<>() {{
Не работает, т.к. Map.of() даёт нам **не** иммутабельный map, а нужно кэш обновлять

2024-12-09 20:37 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44825/WeatherService.java
> +        double humidity = random.nextDouble(100 + 1);
Эти значения максимальные значения лучше вынести в константы)

2024-12-09 20:37 UTC, mysosnovskaya commented on src/test/java/school/faang/task_44825/DataInitializerUtils.java
> +        return new HashMap<>() {{
Наоборот - Map.of дает иммутабельный объект (неизменяемый), а тебе нужен мутабельный - изменяемый) Я мысль поняла, ок!

2024-12-10 20:44 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44825/WeatherService.java
> +    private static final int NUMBER_SIGN = RANDOM.nextBoolean() ? 1 : -1;
Это значение будет вычислено один раз и навсегда останется одним и тем же (константа же). Ты точно именно это хотела?) По-моему именно это вычисление должно остаться в методе

2024-12-11 07:51 UTC, bortsovamaria commented on src/main/java/school/faang/task_44825/WeatherService.java
> +    private static final int NUMBER_SIGN = RANDOM.nextBoolean() ? 1 : -1;
Ой) перенесла в локальную переменную

2024-12-11 20:45 UTC, mysosnovskaya approved these changes

2024-12-11 20:45 UTC, merged