BJS2-45160 Разбираем склад Amazon
CorporationX/god_bless pull request #14718
Opened 2024-12-07 15:30 UTC by rsticks

2024-12-08 20:02 UTC, mysosnovskaya requested changes

2024-12-08 20:02 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs245160/ProductStorage.java
> +        checkCategory(category);
Ты фактически в checkCategory уже найдешь нужный список, а потом строкой ниже опять будешь его искать. Не оптимально) Лучше найти через get и если вернулось null, то выкинуть исключение

2024-12-08 20:02 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs245160/ProductStorage.java
> +        products.get(category).remove(new Product(name, category));
Здесь тоже - ты в checkCategoryAndProduct уже найдешь нужный товар (причем создав доп объект), а в этой строке опять создаешь объект и опять ищешь товар, чтобы удалить. Тут вообще проще было бы циклом for пройти по products.get(category) и найти товар для удаления. А если не нашли, то выкинуть исключение

2024-12-08 20:24 UTC, rsticks commented on src/main/java/school/faang/bjs245160/Product.java
> +    private String category;
Задумывалось как возможность для изменений, но думаю не критично

2024-12-08 21:03 UTC, rsticks commented on src/main/java/school/faang/bjs245160/ProductStorage.java
> +        products.get(category).remove(new Product(name, category));
Создаю дополнительный лист для сохранения объектов для удаления, другого способа не нашел...

2024-12-09 20:52 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs245160/ProductStorage.java
> +        List<Product> productsToRemove = new ArrayList<>();
По-моему у нас предполагается удаление  только одного товара, а не списка, разве нет?

Без дополнительного списка можно было бы решить, если использовать цикл `for (int i =....`. Но там тоже есть маленькая хитрость, как это правильно сделать. Предлагаю подумать) Ещё можно решить с использованием метода removeIf у списков, но там нужны лямбды, а это тема второго спринта (если хочешь, тоже можешь попробовать). Но вообще можешь и оставить с доп объектом - так тоже ок)

2024-12-09 21:37 UTC, rsticks commented on src/main/java/school/faang/bjs245160/ProductStorage.java
> +        List<Product> productsToRemove = new ArrayList<>();
Тогда предлагаю такую реализацию...

2024-12-10 20:59 UTC, mysosnovskaya approved these changes

2024-12-10 20:59 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs245160/ProductStorage.java
> +                });
Круто! Мне нравится такое) Аппрув!)

2024-12-10 20:59 UTC, merged