bormoley1983-BJS2-45208
CorporationX/god_bless pull request #14725
Opened 2024-12-07 16:37 UTC by bormoley1983

2024-12-07 19:11 UTC, 20cognosce requested changes

2024-12-07 19:11 UTC, 20cognosce commented on src/main/java/school/faang/bjs245208/StudentDatabase.java
> +                && notEmptyParamCheck(studentOnCourse, "Student registered on course")) {
У тебя каждый метод обернут в это нагромождение
Лучше сделай инверсию -

if (empty or null) - исключение
продолжаем выполнение ...

2024-12-07 19:11 UTC, 20cognosce commented on src/main/java/school/faang/bjs245208/StudentDatabase.java
> +                && notEmptyParamCheck(studentOnCourse, "Student registered on course")) {
Ну и как-нибудь покороче условие это можно в одну строчку уместить

2024-12-07 19:11 UTC, 20cognosce commented on src/main/java/school/faang/bjs245208/StudentDatabase.java
> +                    .orElse(new Subject(subjectName));
.

2024-12-07 19:11 UTC, 20cognosce commented on src/main/java/school/faang/bjs245208/StudentDatabase.java
> +                            : Objects.equals(subject.getName(), subjectName))
.

2024-12-07 19:11 UTC, 20cognosce commented on src/main/java/school/faang/bjs245208/StudentDatabase.java
> +                if (students.remove(studentOnCourse)) {
В дефолтном реализации ты удалишь объект из списка ровно по той же ссылке в памяти, которую ты передал в аргументы

Правильнее чисто по id удалять все-таки

Если зайти в исходники - там обычный цикл for и поиндексное сравнение, поэтому стримом можешь по совпадению id отфильтровать, ничуть не хуже
![image](https://github.com/user-attachments/assets/6a920d34-f92c-4d43-b74f-e56d2d32081f)

2024-12-09 20:13 UTC, 20cognosce requested changes
Надо привести код в порядок и чистоту

2024-12-09 20:13 UTC, 20cognosce commented on src/main/java/school/faang/bjs245208/StudentDatabase.java
> +        //Optional can bind with addSubject if needed
Убери пожалуйста комментарии или сделай, что имеешь в виду

Можешь написать JavaDoc
Или написать 
//TODO: если хочешь что-то доработать

2024-12-09 20:13 UTC, 20cognosce commented on src/main/java/school/faang/bjs245208/StudentDatabase.java
> +                    subjectsStudents.put(subject, studentsForSubject);
Что здесь вообще что произошло, если пользователя по id нет - его добавил, а если есть - ты стираешь старый список и ставишь новый, в котором только один этот студент

А остальных зачем ты стёр

Давай не будем так заморачиваться...

2024-12-09 20:13 UTC, 20cognosce commented on src/main/java/school/faang/bjs245208/StudentDatabase.java
> +        //  if (!validate(studentid)) { return null; }
Убрать все комментарии в коде

2024-12-09 20:13 UTC, 20cognosce commented on src/main/java/school/faang/bjs245208/StudentDatabase.java
> +                });
тебе нужна строгая проверка, что такой пользователь ровно один
тут нужен reduce

Либо по старинке циклом

Никогда не возвращай null, кидай исключения!!!!!

2024-12-09 20:13 UTC, 20cognosce commented on src/main/java/school/faang/bjs245208/StudentDatabase.java
> +                });
Аналогично, нельзя findFirst использовать для поиска, что если несколько людей попали под критерий?

2024-12-09 20:13 UTC, 20cognosce commented on src/main/java/school/faang/bjs245208/StudentDatabase.java
> +        studentsScores.put(student, subjectsAndMarks);
Эта 76 строка лишняя
Ты же ссылками оперируешь, ты по ссылке subjectsAndMarks сделал put
Эта же ссылка лежит итак уже в studentsScores для юзера

2024-12-09 20:13 UTC, 20cognosce commented on src/main/java/school/faang/bjs245208/StudentDatabase.java
> +                });
.

2024-12-09 20:13 UTC, 20cognosce commented on src/main/java/school/faang/bjs245208/StudentDatabase.java
> +                });
.

2024-12-09 20:13 UTC, 20cognosce commented on src/main/java/school/faang/bjs245208/StudentDatabase.java
> +        subjectsStudents.put(subject, students);
Опять лишняя строка

2024-12-10 04:59 UTC, bormoley1983 commented on src/main/java/school/faang/bjs245208/Student.java
> +    @NotEmpty(message = "Student id cannot be empty or null")
Это не гарантировано так как мы имплементировали все возможные инициаторы

2024-12-10 06:08 UTC, bormoley1983 commented on src/main/java/school/faang/bjs245208/StudentDatabase.java
> +            }
спасибо.

2024-12-10 06:13 UTC, bormoley1983 commented on src/main/java/school/faang/bjs245208/ValidatorUtil.java
> +    public static <T> boolean validate(T object) {
я так и сделал изначально. заменил на консольный вывод для тестов

2024-12-10 18:20 UTC, 20cognosce approved these changes

2024-12-10 18:20 UTC, 20cognosce commented on src/main/java/school/faang/bjs245208/StudentDatabase.java
> +        subjectsStudents.put(subject, students);
Ты получил ссылку, по ссылке добавил студента
Зачем ту же самую ссылку снова класть в мапу, которая итак уже там

2024-12-10 18:21 UTC, merged