BJS2-43799: Развернитесь!
CorporationX/god_bless pull request #14724
Opened 2024-12-07 16:36 UTC by VladislavZhurbin

2024-12-07 17:39 UTC, Kayfral requested changes

2024-12-07 17:39 UTC, Kayfral commented on src/main/java/school/faang/task_43799/Example.java
> +    }
Отлично, но что будет если массив равен null или пуст? Может нужно добавить проверку?

2024-12-08 07:44 UTC, VladislavZhurbin commented on src/main/java/school/faang/task_43799/Example.java
> +    }
Добавил проверки

2024-12-08 11:06 UTC, Kayfral approved these changes

2024-12-08 11:06 UTC, merged