Разбираем склад Amazon
CorporationX/god_bless pull request #14736
Opened 2024-12-07 17:38 UTC by porchy21

Правильно ли я использовал в своем решении Interface? Может следовало написать в абстрактном классе?

2024-12-07 18:18 UTC, 20cognosce requested changes
Всё переделать

2024-12-07 18:18 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/Main.java
> +    private static final HashSet<Product> PRODUCTS = new HashSet<>();
Говорил код в мейне не писать

2024-12-07 18:18 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/Product.java
> +    private final String category;
Категория - Enum

2024-12-07 18:18 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/Product.java
> +    private final long id;
Почему удалил id? 
Получается два продукта с одинаковым именем и категорией, но с разными id равны?
Сомнительно

Наоборот, кажется, что только по id достаточно делать проверки для идентификации продукта

2024-12-07 18:18 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManagement.java
> +    void printAllItems();
Это похоже на интерфейс

2024-12-07 18:18 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManagement.java
> +    }
А это непонятно что, удалить это, либо переделать под вид остальных

2024-12-07 18:18 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManagement.java
> +public interface ProductManagement {
интерфейс - прилагательное
Каким свойством должном обладать объект, который его реализует - такое имя интерфейса

2024-12-07 18:18 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +    private static final HashMap<String, List<Product>> PRODUCTS_MAP = new HashMap<>();
Почему статика
Map = HashMap, LinkedHashMap, ConcurrentHashMap - чувствуешь почему слева нужна интерфейс указывать

2024-12-07 18:18 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +    private long id = 0;
Этому тут не место совсем, это другая ответственность

2024-12-07 18:18 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +    public ProductManager(HashSet<Product> products) {
Принимать только интерфейс параметрами

2024-12-07 18:18 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +                    k -> new ArrayList<>()).add(product);
Не лепить вместе, add отделить

2024-12-07 18:18 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +            }
Вот это что
Я не понял задумку автора

2024-12-07 18:18 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +    public static HashMap<String, List<Product>> groupProductsByCategory(HashSet<Product> products) {
Почему все статика? Я на первой встрече говорил никакой статики, она должна быть только к месту, почему тут везде прилеплена

2024-12-07 18:18 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +                    k -> new ArrayList<>()).add(product);
.

2024-12-07 18:18 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +        Product product = new Product(++id, name, category);
За генерацию id должен отвечать отдельный класс, через AtomicLong

2024-12-07 18:18 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +                k -> new ArrayList<>()).add(product);
.

2024-12-07 18:18 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +        Product product = new Product(id, name, category);
Откуда ты id берешь?

2024-12-07 18:18 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +            PRODUCTS_MAP.get(category).remove(product);
можно без проверки contains - сразу get, если не null - значит есть
Можно в Optional обернуть

2024-12-07 18:18 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +        if (PRODUCTS_MAP.containsKey(category)) {
.

2024-12-07 18:18 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +            log.info("The category {} does not exist", category);
log.error
и исключение выбрасывай

2024-12-07 18:18 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +        PRODUCTS_MAP.values().forEach(products -> products.forEach(System.out::println));
на грани фола по степени слепленности

2024-12-08 22:01 UTC, porchy21 commented
О боже, похоже я удалил все комменты. Оказывается если в review моде idea удалить коммент, то здесь он тоже удалится. Прощу прощения, удалял по мере их выполнения, думал удаляются локально(

2024-12-09 16:37 UTC, 20cognosce requested changes

2024-12-09 16:37 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/Product.java
> +    private static final IdGenerator ID_GENERATOR = new IdGenerator();
Лучше бы сделал метод статическим, чем нёс лишнюю зависимость в данном случае

2024-12-09 16:37 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/Product.java
> +@EqualsAndHashCode
Зачем, у тебя есть id - по нему и сравнивай идентичность

2024-12-09 16:37 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +    }
Откуда взялся этот конструктор, лучше бы отдельным метод сделал тогда уж

2024-12-09 16:37 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +                    .add(product);
Так не писать
это не монады, computeIfAbsent возвращает список

отделить add в отдельный вызов

2024-12-09 16:37 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +                .add(product);
Не лепить вызовы

2024-12-09 16:37 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +        // Product product = new Product(id, name, category);
Что это делает в коммите

2024-12-09 16:37 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +        }
Не проглатывать исключения, какой тогда в них смысл
Выше пробрасывать

2024-12-09 16:37 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +                    .equals(name))) {
Не писать внутри if бизнес-логику, очень плохо

И еще у чего ты equals вызываешь? А если там null, тут NPE на ровном месте
Objects.equals

2024-12-09 16:37 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +        }
Это неподдерживаемый код

Почему у тебя внутри ifPresentOrElse начинается новый цикл с какой-то логикой, почему ты два раза вызываешь productsMap.get(category), декомпозировать и отрефакторить всё безобразие

2024-12-09 16:37 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +                products.forEach(System.out::println));
Лучше так переносить, чем .forEach отрывать

2024-12-09 16:37 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +                    .add(product);
.

2024-12-09 16:37 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +            products.forEach(product -> System.out.println("   " + product));
Табуляцию можно сделать через "\t", а не пробелами

2024-12-09 16:37 UTC, 20cognosce commented on src/test/java/ProductManagerTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Не сворачивать импорты, за это по рукам бьют
Настроить идею
CTRL + ALT + O
CTRL + ALT + L

2024-12-09 16:37 UTC, 20cognosce commented on src/test/java/ProductManagerTest.java
> +        assertEquals(productCategory, products.get(0).getCategory());
Хорошо

2024-12-09 16:37 UTC, 20cognosce commented on src/test/java/ProductManagerTest.java
> +        assertTrue(output.contains(productCategory + ": "));
String.format("%s", object)

2024-12-09 16:37 UTC, 20cognosce commented on src/test/java/ProductManagerTest.java
> +        assertTrue(output.contains("   " + productName));
Почему разбил на две проверки? целиком вывод проверяй

2024-12-09 16:37 UTC, 20cognosce commented on src/test/java/ProductManagerTest.java
> +        assertEquals(1, gropedProducts.get(category2).size());
Лучше конкретные объекты сверять

2024-12-09 20:25 UTC, 20cognosce requested changes

2024-12-09 20:25 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/Product.java
> +    @EqualsAndHashCode.Include
Нет, не нужно вообще переопределять equals
просто сравниваешь id руками

2024-12-09 20:25 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/Product.java
> +    private final String category;
Enum

2024-12-09 20:25 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +    }
Я так и не понял, что это
Почему перенос в 22 строчке

2024-12-09 20:25 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +    }
Не надо создавать методы на одну строчку
Объединить в более крупные смысловые блоки

2024-12-09 20:25 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +    }
Метод такой сделай, по своей задумке
Не конструктор, а просто метод, и если так хочешь - в конструкторе его вызывай

2024-12-09 20:25 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +                productsMap, category);
.

2024-12-09 20:25 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +                .findFirst()
Objects.equalls
findFirst - а если несколько имен совпало? Почему только один удаляешь, это баг

2024-12-09 20:25 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +                    groupedProducts, product.getCategory());
.

2024-12-13 10:56 UTC, 20cognosce approved these changes
Принято

2024-12-13 10:56 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +        }
Хорошо

2024-12-13 10:56 UTC, 20cognosce commented on src/main/java/school/faang/task_43518/ProductManager.java
> +        List<Product> products = getProductsByCategory(category);
productsByCurrentCategory

2024-12-13 10:56 UTC, merged