BJS2-45764: Gmail Rich Filters
CorporationX/god_bless pull request #14754
Opened 2024-12-07 19:41 UTC by NankinRam

Выполнил задачу. Немного поэкспериментировал с фильтром сообщений, создав FilterEmail.class

2024-12-09 06:50 UTC, Kayfral requested changes

2024-12-09 06:50 UTC, Kayfral commented on src/main/java/school/faang/task_45764/FilterEmail.java
> +}
Круто что добавил фильтр!

2024-12-09 06:50 UTC, Kayfral commented on src/main/java/school/faang/task_45764/EmailProcessor.java
> +    }
Смотри, ты не сохраняешь результат transformation.apply(email) в методе processEmails. Давай исправим это - нужно использовать возвращаемое значение трансформации, иначе она выполняется впустую.

2024-12-09 06:50 UTC, Kayfral commented on src/main/java/school/faang/task_45764/FilterEmail.java
> +}
Можно сделать код чище в методе filter(). Промежуточная переменная filter здесь не нужна – попробуй просто вернуть лямбда-выражение напрямую, так код станет компактнее.

2024-12-09 20:29 UTC, NankinRam commented
Я чета навертел с ветками(
Решил вродебы проблему, но не уверен что

2024-12-09 20:41 UTC, NankinRam commented
Удалил пакет который относился к другой заявке

2024-12-10 15:19 UTC, Kayfral approved these changes

2024-12-10 15:19 UTC, merged