BJS2-45209 Task10. StudentDatabase. Double cash
CorporationX/god_bless pull request #14764
Opened 2024-12-07 23:11 UTC by Mike-GB22

2024-12-09 12:39 UTC, Nafanuil commented on src/main/java/derschrank/task10/bjstwo_45209/Student.java
> +public class Student {
посмотри на record классы, они тут лучше смотрятся

2024-12-09 12:40 UTC, Nafanuil commented on src/main/java/derschrank/task10/bjstwo_45209/Student.java
> +    private static int maxIdOfStudent = 0;
не стоит делать генерацию id в том же классе, сейчас это не важно но в целом этот процесс может быть достаточно сложный и выходит за рамки ответственности класса Student

2024-12-09 12:40 UTC, Nafanuil commented on src/main/java/derschrank/task10/bjstwo_45209/Subject.java
> +public class Subject {
то же самое что и для класса Student

2024-12-09 12:43 UTC, Nafanuil commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    Map<Student, Map<Subject, Integer>> studentsNotesMap;
почему ты решил сделать именно такие модификаторы для этих переменных ?

2024-12-09 12:47 UTC, Nafanuil commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void addStudent(Student student) {
делай public только то что что может реально использоваться за пределами этого классам, если я вызову его из вне то я сломаю работу других методов, не забывай об этом и пробегись по всем методам.

собственно если у тебя и нет интерфейса который ты реализовываешь то его нужно хотя-бы держать в уме, если это тебе поможет то можешь сделать интерфейс

2024-12-10 00:42 UTC, Mike-GB22 commented on src/main/java/derschrank/task10/bjstwo_45209/Student.java
> +public class Student {
спасибо за совет

2024-12-10 00:51 UTC, Mike-GB22 commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    Map<Student, Map<Subject, Integer>> studentsNotesMap;
согласен, надо было приватным сделать и финальным

2024-12-10 00:57 UTC, Mike-GB22 commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void addStudentAndHisNotes(Student student, Map<Subject, Integer> newNote) {
оценка, в условии задачи не было как называть переменную, так что выбор за мной же?

2024-12-10 01:14 UTC, Mike-GB22 commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void addStudent(Student student) {
исправил
по поводу интерфейса, интересная идея, спасибо

2024-12-10 01:16 UTC, Mike-GB22 commented on src/main/java/derschrank/task10/bjstwo_45209/Student.java
> +    private static int maxIdOfStudent = 0;
убрал

2024-12-10 12:15 UTC, Nafanuil commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void addStudentAndHisNotes(Student student, Map<Subject, Integer> newNote) {
да, за тобой, просто заметки и оценки это совершенно разные вещи, названия нужно стараться подбирать такие чтоб не было разночтений и сомнений

2024-12-10 12:24 UTC, Nafanuil commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    private final Map<Student, Map<Subject, Integer>> studentsNotesMap;
рекомендую тратить побольше времени над выбором имен:
1) добавлять тип к имени переменный считается плохим тоном и не добавляет ничего полезного
2) studentGraidsBySubject вместо studentsNotesMap отражает содержимое и в любом месте программы понятно о чем речь даже человеку который первый раз смотрит на код

2024-12-10 12:29 UTC, Nafanuil commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void addStudentAndHisNotes(Student student, Map<Subject, Integer> newNote) {
studentsNotesMap ты заполнил, хоть и дважды обратившись к мапе, что не очень продуктивно, но забыл про subjectStudentsMap

2024-12-10 12:34 UTC, Nafanuil commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void addOneNoteToStudent(Student student, Subject subject, Integer note) {
не могу найти такой метод в задание, напиши как он называется в задачке

2024-12-10 12:35 UTC, Nafanuil commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void delStudent(Student student) {
не используй сокращения в названиях

2024-12-10 12:38 UTC, Nafanuil commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +        Map<Subject, Integer> oldNote = studentsNotesMap.get(student);
рискуешь упасть тут с NPE да и в других местах тоже про него забываешь

2024-12-10 12:39 UTC, Nafanuil commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public String getStringToPrintAllStudentsWithNotes() {
не вижу такого метода в задачи, почему он publi ?

2024-12-10 12:42 UTC, Nafanuil commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public String getStringToPrintAllStudentsWithNotes() {
Здорово что ты используешь StringBuilder, но как то переусложнил сильно

2024-12-10 12:46 UTC, Nafanuil commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void addOneNoteToStudent(Student student, Subject subject, Integer note) {
метод реализован не до конца

2024-12-10 12:50 UTC, Nafanuil commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void addSubject(Subject subject) {
опять забыл про вторую мапу

2024-12-10 12:52 UTC, Nafanuil commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void addStudentsToSubject(Subject subject, Set<Student> students) {
не нашел такого метода в задании, это который?

2024-12-10 12:55 UTC, Nafanuil commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +
ниже методы тоже с ошибками

2024-12-12 04:48 UTC, Mike-GB22 commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void addStudentAndHisNotes(Student student, Map<Subject, Integer> newNote) {
так в задание сказано добавить: **Добавление нового студента и его предметов с оценками.**
не сказано, в это же время добавить и в мапу изучаемых предметов

это отдельное задание: "Реализуйте методы в классе StudentDatabase для работы со второй HashMap:
**Добавление нового предмета и списка студентов, изучающих его.**" 

вынесенно отдельными пунктами и связь между ними не обозначена

2024-12-12 04:49 UTC, Mike-GB22 commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void delStudent(Student student) {
Хорошо

2024-12-12 04:57 UTC, Mike-GB22 commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public String getStringToPrintAllStudentsWithNotes() {
Там цикл в цикле, который работает с одной и той же строкой. 
Если ее не использовать будут постоянно создаваться объект строковые, при добавлении даже одного символа.

При этом не раз видел, что даже отдельный символ эффективнее добавлять через отдельный .append(), чем через конкатенацию внутри параметра .append()

Решил запомнить что так и надо делать.

2024-12-12 04:58 UTC, Mike-GB22 commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void addSubject(Subject subject) {
Так в задании этого нет же

2024-12-12 05:01 UTC, Mike-GB22 commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +
Ну если это связанно с тем что я работаю с одной мапой?
Ну так по условию задачи.

О их связи не писали

2024-12-12 05:04 UTC, Mike-GB22 commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void addOneNoteToStudent(Student student, Subject subject, Integer note) {
Потому что не работает со второй картой (мапой)?

2024-12-12 05:07 UTC, Mike-GB22 commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public String getStringToPrintAllStudentsWithNotes() {
> не вижу такого метода в задачи, почему он publi ?

согласен, это служебный метод

2024-12-12 05:10 UTC, Mike-GB22 commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void addStudentAndHisNotes(Student student, Map<Subject, Integer> newNote) {
Согласен. Просто я спутал языки. В немецком языке оценка - это Note,

2024-12-12 05:10 UTC, Mike-GB22 commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    private final Map<Student, Map<Subject, Integer>> studentsNotesMap;
то что это карта (мапа) очень плохо указывать?
мне так легче было код читать, когда есть слово мапа в конце

2024-12-12 18:09 UTC, Nafanuil commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void addOneNoteToStudent(Student student, Subject subject, Integer note) {
я же правильно понимаю что это метод  "Добавление нового предмета для существующего студента с оценкой." если да, то да нужно работать с обеими мапами

2024-12-12 18:15 UTC, Nafanuil commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void addStudentAndHisNotes(Student student, Map<Subject, Integer> newNote) {
все так, это два совершенно не связанных метода и они оба нужны, но обе этих переменные напрямую связаны друг с другом, представь что в твое расписание добавили математику, это же в свою очередь означает что у учителя математике в списке учеников должен появится ты.

2024-12-12 22:18 UTC, Mike-GB22 commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void addOneNoteToStudent(Student student, Subject subject, Integer note) {
:five: Реализуйте методы в классе StudentDatabase для работы со второй HashMap:
*Добавление нового предмета и списка студентов, изучающих его.

Написано что работает со второй картой

2024-12-13 19:29 UTC, Mike-GB22 commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void addStudentAndHisNotes(Student student, Map<Subject, Integer> newNote) {
Сделал перекрестное добавление
для этого логику добавления в свою Карту вынес в методы xxxxOnly(x), а в перекрестную Карту, в основной метод, где вызывается еще и метод xxxxOnly(x).

Так же вынес методы из задания в интерфейс.

2024-12-13 19:30 UTC, Mike-GB22 commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void addOneNoteToStudent(Student student, Subject subject, Integer note) {
> я же правильно понимаю что это метод "Добавление нового предмета для существующего студента с оценкой." если да, то да, нужно работать с обеими мапами

выше написал, сделал перекрестное добавление
https://github.com/CorporationX/god_bless/pull/14764#discussion_r1884397986

2024-12-13 21:03 UTC, mysosnovskaya requested changes

2024-12-13 21:03 UTC, mysosnovskaya commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +            subjectStudents.get(subject).remove(student);
А метод delStudentFromSubjectOnly не подойдет?

2024-12-13 21:03 UTC, mysosnovskaya commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +        subjectStudents.get(subject).remove(student);
Если после этой операции список студентов у предмета subject стал пустым, то этот предмет нужно удалить из subjectStudents.

2024-12-13 21:03 UTC, mysosnovskaya commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void delStudentFromSubject(Student student, Subject subject) {
del -> delete

2024-12-13 21:03 UTC, mysosnovskaya commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    private void delStudentFromSubjectOnly(Student student, Subject subject) {
del -> delete

2024-12-13 21:36 UTC, Mike-GB22 commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +    public void delStudentFromSubject(Student student, Subject subject) {
Согласен

2024-12-13 21:39 UTC, Mike-GB22 commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +            subjectStudents.get(subject).remove(student);
Супер, и как раз можно будет логику на проверку "пустого" сделать

2024-12-13 21:46 UTC, Mike-GB22 commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +        subjectStudents.get(subject).remove(student);
Сделал, правда теперь вылетает.

at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
Delete the student
at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1620)

foreach перебирает в public void deleteStudent(Student student) { Карту с предметами
а мы вызываем удаление пользователя из предмета, и теперь если у предмета нет пользователя, то удаляем предмет, и foreach падает.

Но я думаю найду решение

2024-12-13 21:48 UTC, Mike-GB22 commented on src/main/java/derschrank/task10/bjstwo_45209/StudentDatabase.java
> +        subjectStudents.get(subject).remove(student);
Спасибо за рекомендацию!

2024-12-14 17:35 UTC, mysosnovskaya approved these changes

2024-12-14 17:35 UTC, merged