Darth rexsell bjs2 44032
CorporationX/god_bless pull request #14760
Opened 2024-12-07 20:22 UTC by Rexsell

Группировка пользователей по возрасту
BJS2-44032

2024-12-07 20:26 UTC, Rexsell commented
Да за шо

2024-12-08 11:47 UTC, Kayfral requested changes
По остальному коду вопросов нету

2024-12-08 11:47 UTC, Kayfral commented on src/main/java/school/faang/Main.java
> +        List<User> users = List.of(newUser1, newUser2, newUser3,newUser4, newUser5, newUser6);
Обрати внимание checkstyle ругается на этот момент. После "," должен быть пробел

![image](https://github.com/user-attachments/assets/042ff5a1-f0d8-45b9-9a2d-a6ea06048079)

2024-12-12 18:29 UTC, Kayfral approved these changes

2024-12-12 18:29 UTC, merged