fladx-BJS2-46184-Секреты-дроидов
CorporationX/god_bless pull request #14795
Opened 2024-12-08 12:19 UTC by fladx

2024-12-09 18:54 UTC, ArtemValt commented on src/main/java/school/faang/task_46184secretsdroid/CaesarCipherEncryptor.java
> +    public DroidMessageEncryptor encrypt = (message, key) -> {
константы пишутся по конвенция капсом

2024-12-09 18:54 UTC, ArtemValt commented on src/main/java/school/faang/task_46184secretsdroid/Droid.java
> +    public void receiveMessage(String encryptedMessage, int encryptionKey) {
нужен ли этому методу паблик?

2024-12-09 18:54 UTC, ArtemValt commented on src/main/java/school/faang/task_46184secretsdroid/Droid.java
> +        sendDroid.receiveMessage(encryptedMessage, encryptionKey);
почему не так 
        sendDroid.receiveMessage(encryptedMessage, encryptionKey);
->
receiveMessage(encryptedMessage, encryptionKey);
?

2024-12-10 06:43 UTC, therealadik commented on src/main/java/school/faang/task_46184secretsdroid/Droid.java
> +        sendDroid.receiveMessage(encryptedMessage, encryptionKey);
sendDroid - это кому отправить сообщение, мы же не самому себе отправляем

2024-12-10 19:20 UTC, ArtemValt requested changes

2024-12-10 19:20 UTC, ArtemValt commented on src/main/java/school/faang/task_46184secretsdroid/Droid.java
> +        sendDroid.receiveMessage(encryptedMessage, encryptionKey);
если обращаться через this ничего же не изменится, ты же и так обращаешься уже через объект дройда.

2024-12-13 09:52 UTC, therealadik commented on src/main/java/school/faang/task_46184secretsdroid/Droid.java
> +        sendDroid.receiveMessage(encryptedMessage, encryptionKey);
поменял немного имя переменной - receiveDroid

мы отправляем сообщение и вызываем sendMessage у отправляющего дроида
а вызываем принятие сообщения у другого обьекта, а не этого же - у receiveDroid

2024-12-13 14:23 UTC, ArtemValt commented on src/main/java/school/faang/task_46184secretsdroid/Droid.java
> +        sendDroid.receiveMessage(encryptedMessage, encryptionKey);
слушай да, тут я не прав

2024-12-13 14:24 UTC, ArtemValt approved these changes

2024-12-13 14:24 UTC, merged

2024-12-13 14:52 UTC, therealadik commented on src/main/java/school/faang/task_46184secretsdroid/Droid.java
> +        sendDroid.receiveMessage(encryptedMessage, encryptionKey);
да ничего) рад что прояснили