Lord of the Rings RPG
CorporationX/god_bless pull request #14796
Opened 2024-12-08 12:25 UTC by almigor1

2024-12-08 18:59 UTC, mysosnovskaya requested changes
Отличная работа! Но парочку мест для улучшения нашла :)

2024-12-08 18:59 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task45800/model/Item.java
> +    private int value;
Значение этого поля может где-то измениться? Не вижу сеттера на него

2024-12-08 18:59 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task45800/Main.java
> +        manager.addItem(legolas, bow, (item) -> System.out.println(item.getName() + " был добавлен в инвентарь."));
8 раз повторяется одна и даже лямбда-функция. Вынесем её в отдельный приватный метод?)

2024-12-08 19:38 UTC, almigor1 commented on src/main/java/school/faang/sprint2/task45800/model/Item.java
> +    private int value;
я просто думал, стоимость меняем, а мы ж через конструктор

2024-12-08 20:39 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task45800/Main.java
> +        manager.addItem(character, itemIn, (item) -> System.out.println(item.getName() + " был добавлен в инвентарь."));
Хитро =) Я вообще ожидала, что ты `(item) -> System.out.println(item.getName() + " был добавлен в инвентарь.")` вынесешь в отдельную функцию. Это будет интересным упражнением! Рекомендую всё-таки попробовать - ради практики. Код в текущем виде ок, но хочется показать тебе ещё и то, как лямбда-функции можно вынести в отдельные функции! Может быть сложно - тогда приходи в чат в дискорде или сюда - в комментарии)

2024-12-10 20:11 UTC, mysosnovskaya approved these changes

2024-12-10 20:11 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task45800/Main.java
>      private static void addItem(InventoryManager manager, Character character, Item itemIn) {
Ожидала такое =)

```
    private static Consumer<Item> addItemConsumer() {
        return (item) -> System.out.println(item.getName() + " был добавлен в инвентарь.");
    }
```

2024-12-10 20:11 UTC, merged