sprint 1.3 task BJS2-44546
CorporationX/god_bless pull request #14809
Opened 2024-12-08 14:58 UTC by lcodio

init commit - solved the problem

2024-12-09 14:15 UTC, 20cognosce requested changes
Удалить копии

2024-12-09 14:15 UTC, 20cognosce commented on src/main/java/school/faang/s13task44546/SpellEvent.java
> +    }
@RequiredArgsConstructor

2024-12-09 14:15 UTC, 20cognosce commented on src/main/java/school/faang/s13task44546/SpellEvent.java
> +    private final String eventType;
Использовать Enum

2024-12-09 14:15 UTC, 20cognosce commented on src/main/java/school/faang/s12task44546/SpellEvent.java
> +public class SpellEvent {
Почему на ревью 6 файлов, 3 из которых - копии?
Удалить лишнее

2024-12-09 14:15 UTC, 20cognosce commented on src/main/java/school/faang/s13task44546/HogwartsSpells.java
> +            System.out.println(id + " - " + spellEvent);
почему где-то лог, где-то вывод в консоль
использовать что-то одно

Убрать любые складывания строк через +
Использовать шаблонизацию
String.format("%s", param)
log.info("{}", param)

2024-12-09 14:15 UTC, 20cognosce commented on src/main/java/school/faang/s13task44546/HogwartsSpells.java
> +    }
Большая вложенность, куча if-ов, когнитивно переусложненный метод - плохо

1. Развернуть условие:
-- if (spellEvent == null), то кинуть исключение
-- продолжение выполнения 
2. List<SpellEvent> events = spellsByType.get(spellEvent.getEventType());
Как events может быть null, если ты в 27 строчке делаешь
spellsByType.putIfAbsent(eventType, new ArrayList<>()) ???

Избыточная проверка

3. if (events.isEmpty()) {
    spellsByType.remove(spellEvent.getEventType());
}

Зачем удалять пустой список? Чем бороться с null потом, лучше пусть он останется пустым, это упростит всем жизнь

P.S.
Поскольку категория заклинания - Enum, ограниченное множество, то в конструкторе можно сразу все типы заклинаний добавить в мапу и проинициализировать им new ArrayList

2024-12-13 15:13 UTC, 20cognosce requested changes

2024-12-13 15:13 UTC, 20cognosce commented on src/main/java/school/faang/s13task44546/HogwartsSpells.java
> +        spellsByType.get(eventType.name()).add(spellEvent);
Двойная работа, putIfAbsent возвращает список

2024-12-13 15:13 UTC, 20cognosce commented on src/main/java/school/faang/s13task44546/HogwartsSpells.java
> +    public void deleteSpellEvent(int id) {
Не удалила из второй мапы, он остался лежать в сгруппированном по категории списке

2024-12-13 20:07 UTC, 20cognosce requested changes

2024-12-13 20:07 UTC, 20cognosce commented on src/main/java/school/faang/s13task44546/HogwartsSpells.java
> +        spellsOfType.removeIf(event -> event.getId() == id);
Нельзя через == проверки делать, это сравнение ссылок в памяти
Возможен баг, погугли "пул интов"
![image](https://github.com/user-attachments/assets/19996aa5-60e1-48da-b3a5-e56ab83f46bb)

2024-12-14 11:11 UTC, 20cognosce approved these changes
Принято

2024-12-14 11:11 UTC, 20cognosce commented on src/main/java/school/faang/s13task44546/SpellEvent.java
> +    private final Integer id;
Можно было бы не менять примитив на обёртку, а использовать Objects.equals

2024-12-14 11:11 UTC, merged

2024-12-16 15:26 UTC, lcodio commented on src/main/java/school/faang/s13task44546/SpellEvent.java
> +    private final String eventType;
Хотела сказать, что если в Enum в скобках прописывать стринговые названия ("..."), то требуется создать либо переменную String name либо создать конструктор с аргументом name. Чтобы работал метод name самого Enum, то эти названия не надо прописывать.