task lord of the ring impl
CorporationX/god_bless pull request #14831
Opened 2024-12-08 18:58 UTC by bortsovamaria

2024-12-08 20:36 UTC, mysosnovskaya requested changes

2024-12-08 20:36 UTC, mysosnovskaya commented on src/main/java/school/faang/task_45509/InventoryManager.java
> +        }
Я бы лучше inventory сделала final и инициализировала бы сразу в Character. А из-за сеттера на это поле мы открываем доступ для изменения из любых других классов. Т.е. ты уже для существующего Character с непустым inventory сможем без проблем сделать character.setInventory(null) - и всё пропало) Не надо так

2024-12-08 20:36 UTC, mysosnovskaya commented on src/main/java/school/faang/task_45509/InventoryManager.java
> +        }
Не надо такого допускать. Поле всегда должно быть проинициализировано (об этом подробнее в комментарии выше)

2024-12-08 20:36 UTC, mysosnovskaya commented on src/main/java/school/faang/task_45509/InventoryManager.java
> +                item.setValue(map.apply(item).getValue());
А если в map будет изменяться не только поле value? В теории и имя изменить можно, у тебя оно только почему-то final. Но если появятся какие-то другие поля в Item, которые будет возможно изменить, то здесь мы 100% забудем обновить код - и тогда это потенциальный баг. Нужно полностью заменять старый Item на тот, который вернулся методом apply

2024-12-08 20:36 UTC, mysosnovskaya commented on src/main/java/school/faang/task_45509/InventoryManager.java
> +            throw new IllegalArgumentException("Character s absent");
s -> is?

2024-12-08 20:36 UTC, mysosnovskaya commented on src/main/java/school/faang/task_45509/InventoryManager.java
> +    public void updateItem(Character character, Predicate<Item> filter, Function<Item, Item> map) {
Я бы ещё переименовала filter и map во что-то более конкретное. Например, itemFilter и itemTransformer

2024-12-10 10:33 UTC, bortsovamaria commented on src/main/java/school/faang/task_45509/InventoryManager.java
> +        character.getInventory().add(item);
Здесь надо вынести метод add в Character?

2024-12-10 10:37 UTC, bortsovamaria commented on src/main/java/school/faang/task_45509/InventoryManager.java
> +                item.setValue(map.apply(item).getValue());
Обновить объект это удалить старый из списка и добавить новый?

2024-12-10 20:09 UTC, mysosnovskaya requested changes

2024-12-10 20:09 UTC, mysosnovskaya commented on src/main/java/school/faang/task_45509/InventoryManager.java
> +        character.getInventory().add(item);
В идеале да)

2024-12-10 20:09 UTC, mysosnovskaya commented on src/main/java/school/faang/task_45509/InventoryManager.java
> +    }
Да, идейно так. Но можно реализовать проще, если использовать цикл for-i на 29 строке. Тогда ты можешь одновременно и проходить по списку, и изменять его

2024-12-11 08:13 UTC, bortsovamaria commented on src/main/java/school/faang/task_45509/InventoryManager.java
> +    }
Сделала в цилке через метод .set у List

2024-12-11 19:57 UTC, mysosnovskaya approved these changes

2024-12-11 20:01 UTC, merged