Solve task_44645
CorporationX/god_bless pull request #14851
Opened 2024-12-08 21:43 UTC by shamshaev

2024-12-09 20:35 UTC, mysosnovskaya requested changes

2024-12-09 20:35 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44645/HogwartsSpells.java
> +    private Map<String, List<SpellEvent>> spellsByType = new HashMap<>();
final?

2024-12-09 20:35 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44645/HogwartsSpells.java
> +@Getter
Добавление геттера для внутренних хэш-мап, предназначенных для хранения данных, идея потенциально опасная, т.к. через этот геттер в любом другом классе можно будет сделать такое: hogwartsSpells.getSpellById().clear() - и все данные потеряются. 
Доступ к этим двум хэш мапам должен быть только через методы, реализованные в этом классе, и никак иначе. Всё, что мы разрешаем делать с маапами, это addSpellEvent, getSpellEventById, getSpellEventsByType, deleteSpellEvent, printAllSpellEvents. И только через специально созданные для этого методы

2024-12-09 20:35 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44645/HogwartsSpells.java
> +        spellsByType.put(eventType, events);
Посмотри на putIfAbsent - тогда эту строчку можно будет не писать

2024-12-09 20:35 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44645/HogwartsSpells.java
> +    public void deleteSpellEvent(int id) {
Хорошо логика реализована в этом методе 👍

2024-12-09 20:35 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44645/SpellEvent.java
> +@Setter
Точно сеттер нужен? По-моему поля не предполагают изменений, я бы их final сделала

2024-12-10 16:23 UTC, shamshaev commented on src/main/java/school/faang/task_44645/HogwartsSpells.java
> +    private Map<String, List<SpellEvent>> spellsByType = new HashMap<>();
Раньше думал, как можно сделать такое поле final, если потом мы меняем его содержимое. Спросил СhatGPT, он объяснил. Получается, если используется мутабельный объект, то так можно. Ссылка будет финальной, а содержимое может меняться.

2024-12-10 16:26 UTC, shamshaev commented on src/main/java/school/faang/task_44645/HogwartsSpells.java
> +@Getter
понял, проверил, понял, действительно мапы обнуляются. Только в этом случае не получится в main вывести мапы на печать,  а писать тесты не хочется пока. Только косвенно можно посмотреть через printAllSpellEvents

2024-12-10 16:27 UTC, shamshaev commented on src/main/java/school/faang/task_44645/SpellEvent.java
> +@Setter
Т.е. получается все-таки нужно четко соблюдать принцип: все что может быть private должно быть private, все что может быть final должно быть final?
У меня было такое понимание, что final нужно обязательно делать те поля, которые не то, что в коде не меняются, а вообще по смыслу в предметной области не должны изменяться (т.е. константы). Хотя даже так, я сейчас посмотрел проекты в Хекслете, там же есть поля id у доменных классов, которые присваиваются СУБД и они никак не могут измениться, но даже там не было модификаторов final и замечаний от менторов не было (они собственно и в учебных материалах не были final).

2024-12-10 20:35 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44645/HogwartsSpells.java
> +    private Map<String, List<SpellEvent>> spellsByType = new HashMap<>();
Верно

2024-12-10 20:35 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44645/HogwartsSpells.java
> +@Getter
Да, через printAllSpellEvents хорошее решение

2024-12-10 20:42 UTC, mysosnovskaya commented on src/main/java/school/faang/task_44645/SpellEvent.java
> +@Setter
Если говорим уже про написание моделей для базы данных, то там чаще поля не final, т.к. мы должны иметь возможность их обновлять. Например, у тебя есть User с полями id, name, email, phone. И если у твоего пользователя есть возможность обновлять данные (имя, номер телефона), то эти поля точно не будут final. чтобы ты в коде мог делать set для них. С id немного другая история, у нас сначала объект вообще без id (перед созданием), а потом id присваивается - фактически, он тоже изменяется через set. Так что выглядит так, что в твоих учебных проектах всё верно)

Но у нас ещё речи о базе данных не идет, мы смотрим текущий код. И если в текущем коде изменений этих полей не предполагается, то лучше сделать поля финальными. Вообще final добавляется по такому принципу: "я как разработчик пишу этот код и не предполагаю, что эти поля могут изменяться через set-методы или как-то ещё, тогда я делаю их final". Так что это всё именно про код

2024-12-10 20:42 UTC, mysosnovskaya approved these changes

2024-12-10 20:42 UTC, merged