BJS2-46571
CorporationX/god_bless pull request #14901
Opened 2024-12-09 13:24 UTC by az3l1t

Google Maps

2024-12-11 08:11 UTC, Kayfral requested changes

2024-12-11 08:11 UTC, Kayfral commented on src/main/java/school/faang/task_46571/LocationSearchEngine.java
> +    }
Стоит добавить проверку на null в методах. Это защитит твой код от NullPointerException и сделает его более надёжным. Давай подумаем, как это реализовать

2024-12-11 08:11 UTC, Kayfral commented on src/main/java/school/faang/task_46571/Location.java
> +public record Location(String name, Double latitude, Double longitude) {}
Отлично справился с использованием record!

2024-12-12 07:40 UTC, az3l1t commented on src/main/java/school/faang/task_46571/Location.java
> +public record Location(String name, Double latitude, Double longitude) {}
thanks

2024-12-12 07:40 UTC, az3l1t commented on src/main/java/school/faang/task_46571/LocationSearchEngine.java
> +    }
будет исправлено

2024-12-12 08:25 UTC, Kayfral approved these changes
Отлично!

2024-12-12 08:25 UTC, merged