Библиотека Вестероса. initial
CorporationX/god_bless pull request #14902
Opened 2024-12-09 13:59 UTC by alobraztsov86

2024-12-10 15:42 UTC, Kayfral requested changes

2024-12-10 15:42 UTC, Kayfral commented on src/main/java/school/faang/sprint_1/task_bjs2n45413/Book.java
> +                && year <= MAX_YEAR);
Давай добавим проверку на null для title и author в методе класса Book. Это поможет избежать NullPointerException, когда передаются пустые значения. Так код станет более надёжным. И так же можно добавить проверку на то что длина строки не равна 0

2024-12-10 15:42 UTC, Kayfral commented on src/main/java/school/faang/sprint_1/task_bjs2n45413/LibrarySystem.java
> +    private final Map<Book, String> bookStringMap;
Название bookStringMap не совсем отражает суть переменной. Предлагаю использовать что-то более понятное, например, bookLocations или libraryInventory - так сразу будет ясно, для чего эта переменная используется.

2024-12-10 15:42 UTC, Kayfral commented on src/main/java/school/faang/sprint_1/task_bjs2n45413/Book.java
> +    private static final int MIN_YEAR = -5000;
Отличная работа с константами для проверки длины и диапазона значений!

2024-12-10 15:42 UTC, Kayfral commented on src/main/java/school/faang/sprint_1/task_bjs2n45413/LibrarySystem.java
> +    }
Я бы добавил информативный комментарий для пользователя. Комментарий будет сообщать, что книга, которую пытается удалить пользователь отсутствует в библиотеке

2024-12-12 20:10 UTC, alobraztsov86 commented on src/main/java/school/faang/sprint_1/task_bjs2n45413/Book.java
> +    private static final int MIN_YEAR = -5000;
Спасибо!

2024-12-12 20:22 UTC, alobraztsov86 commented on src/main/java/school/faang/sprint_1/task_bjs2n45413/LibrarySystem.java
> +    }
добюавил проверку.

2024-12-13 05:26 UTC, Kayfral approved these changes
Отлично

2024-12-13 05:26 UTC, merged