task solution
CorporationX/god_bless pull request #14914
Opened 2024-12-09 15:38 UTC by AesaQ

2024-12-10 15:56 UTC, Kayfral commented on src/main/java/school/faang/metaverse/NotificationManager.java
> +    }
В методе registerHandler было бы здорово добавить проверку параметров на null. Это сделает твой код более устойчивым к ошибкам.

2024-12-10 15:56 UTC, Kayfral commented on src/main/java/school/faang/metaverse/Notification.java
> +}
Круто сделал через record

2024-12-12 16:29 UTC, AesaQ commented on src/main/java/school/faang/metaverse/Main.java
> +        );
вообще я просто скопировал пример метода main из задачи)) без проблем исправлю на enum
но с точки зрения обучения я не знаю, стоит ли копировать примеры метода main из заданий. Так задачи решаются чуть ли не в два раза быстрее
Я бы наверное копировал их и ревьюил, думал где что можно улучшить, как вот например с этим enum

2024-12-12 18:33 UTC, Kayfral commented on src/main/java/school/faang/metaverse/Main.java
> +        );
Да, отличная мысль, чтобы думать как улучшить примеры! Они на то и примеры, чтобы дать первоначальный вектор движения

2024-12-12 18:36 UTC, Kayfral requested changes
С остальным все отлично! Просто исправь замечания checkstyle

2024-12-12 18:36 UTC, Kayfral commented on src/main/java/school/faang/metaverse/Main.java
> +        Notification emailNotification = new Notification(NotificationType.EMAIL, "Ваша учетная запись успешно активирована");
Обрати внимание на то, что у тебя ругается checkstyle на длину данной строки
![image](https://github.com/user-attachments/assets/d222ed4e-bff5-40b3-a094-9e94a060d599)

2024-12-13 18:37 UTC, Kayfral approved these changes

2024-12-13 18:38 UTC, Kayfral commented
Круто!

2024-12-13 18:38 UTC, merged