BJS2-45555
CorporationX/god_bless pull request #14959
Opened 2024-12-09 23:31 UTC by Narol01

2024-12-10 19:18 UTC, 20cognosce requested changes

2024-12-10 19:18 UTC, 20cognosce commented on src/main/java/school/faang/Main.java
> -}
В каждом ПРе мы будем удалять мейн?

2024-12-10 19:18 UTC, 20cognosce commented on src/main/java/school/faang/task_45555/entity/Character.java
> +    private List<Item> inventory;
final
без сеттеров

2024-12-10 19:18 UTC, 20cognosce commented on src/main/java/school/faang/task_45555/entity/Item.java
> +    private int value;
final

2024-12-10 19:18 UTC, 20cognosce commented on src/main/java/school/faang/task_45555/Main.java
> +                (item) -> new Item(item.getName(), item.getValue() * 2));
Мне кажется я уже раз 100 говорил про equals и как его вызывать

getName.equals(), name = null -> NPE
Objects.equals

2024-12-10 19:18 UTC, 20cognosce commented on src/main/java/school/faang/task_45555/InventoryManager.java
> +        log.info("Successfully removed items from inventory");
Залогируй условие хоть

2024-12-10 19:18 UTC, 20cognosce commented on src/main/java/school/faang/task_45555/InventoryManager.java
> +        });
forEach - шляпа, стримы подавай

Тебе понадобится 2 стрима:
первый из тех, кто не попал под условие, собрать только их
второй из тех кто попал под условие, их смапить и собрать

И затем объединить два стрима (или двумя списками, если не получится concat стримов)

2024-12-11 15:17 UTC, 20cognosce commented on src/main/java/school/faang/task_45555/entity/Character.java
> +    private List<Item> inventory;
final

2024-12-11 15:18 UTC, 20cognosce commented on src/main/java/school/faang/task_45555/entity/Item.java
> +@Setter
Для кого сеттеры

2024-12-11 15:19 UTC, 20cognosce commented on src/main/java/school/faang/task_45555/entity/Item.java
> +@Setter
Создавай новый объект

2024-12-11 18:34 UTC, Narol01 commented on src/main/java/school/faang/task_45555/InventoryManager.java
> +        });
Почему peek, а не forEach?

2024-12-13 11:04 UTC, 20cognosce approved these changes

2024-12-13 11:04 UTC, 20cognosce commented on src/main/java/school/faang/task_45555/InventoryManager.java
> +        items.stream().filter(filter).forEach(item -> log.info("Removing item: {}", item.getName()));
Не писать стримы в строчку
.filter
.map
.collect

2024-12-13 11:04 UTC, 20cognosce commented on src/main/java/school/faang/task_45555/InventoryManager.java
> +        return new Character(character.getName(), Stream.concat(itemsAfterFilter, trueItemsAfterFilter).toList());
Сразу toList сделал бы и сохранил в переменную, и переменную уже в конструктор передал

2024-12-13 11:04 UTC, merged