BJS2-44730 [Организация системы бронирования]
CorporationX/god_bless pull request #14958
Opened 2024-12-09 23:05 UTC by Iv-an-s

2024-12-10 21:28 UTC, mysosnovskaya requested changes

2024-12-10 21:28 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/task_43514/BookingNotifier.java
> +    void notifyObservers(Booking booking, String status) {
А он не должен быть public?

2024-12-10 21:28 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/task_43514/BookingSystem.java
> +        return -1;
Лучше исключение выбросить. Хотя почему вообще может возникнуть ситуация, когда комната не добавилась? Это как?)

2024-12-10 21:28 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/task_43514/BookingSystem.java
> +            return -1;
Тоже лучше исключение. И раз уже работает с Optional, тогда предлагаю использовать orElseThrow для roomOpt

2024-12-10 21:28 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/task_43514/BookingSystem.java
> +        bookingNotifier.notifyObservers(newBooking, "BOOKING_CREATED");
Для статусов лучше создать отдельное перечисление

2024-12-10 21:28 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/task_43514/BookingSystem.java
> +                .collect(Collectors.toList());
Вместо `.collect(Collectors.toList());` можно (лучше) просто `.toList();`

2024-12-10 21:28 UTC, mysosnovskaya commented on src/test/java/school/faang/moduleone/task_43514/BookingSystemTest.java
> +        bookingSystem.getBookingNotifier().addObserver(spyObserver);
Про это написала в BookingSystem - нужен конструктор со всеми параметрами

2024-12-10 21:28 UTC, mysosnovskaya commented on src/test/java/school/faang/moduleone/task_43514/BookingSystemTest.java
> +        assertEquals(-1, bookingIdWhenTimeSlotIsNotAvailable);
Когда заменишь -1 на исключения, то здесь нужно будет использовать assertThrows

2024-12-11 21:24 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/task_43514/BookingNotifier.java
> +    void notifyObservers(Booking booking, String status) {
Да, конечно! пропустил. Теперь public.

2024-12-11 21:38 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/task_43514/BookingSystem.java
> +        return -1;
-1 поменял на выброс IllegalArgumentException. Можно было кастомное исключение создать чтобы название более корректно описывало причину, но не стал :)
Ситуация такая возникнет когда комната уже "зарегистрирована". Именно для этого использовал Set.

2024-12-11 21:47 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/task_43514/BookingSystem.java
> +            return -1;
Поправил

2024-12-11 21:55 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/task_43514/BookingSystem.java
> +        bookingNotifier.notifyObservers(newBooking, "BOOKING_CREATED");
Создал

2024-12-11 21:55 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/task_43514/BookingSystem.java
> +                .collect(Collectors.toList());
Поправил

2024-12-11 22:30 UTC, Iv-an-s commented on src/test/java/school/faang/moduleone/task_43514/BookingSystemTest.java
> +        assertEquals(-1, bookingIdWhenTimeSlotIsNotAvailable);
Поправил

2024-12-11 22:32 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/task_43514/BookingSystem.java
> +@Getter
Сделал. 
Чтобы не убирать проверки пришлось добавить дополнительные методы. Правда более целевые.

2024-12-11 22:38 UTC, Iv-an-s commented on src/test/java/school/faang/moduleone/task_43514/BookingSystemTest.java
> +        bookingSystem.getBookingNotifier().addObserver(spyObserver);
Сделал

2024-12-12 20:08 UTC, merged