Completed task BJS2-44648 HogwartsSpells
CorporationX/god_bless pull request #14961
Opened 2024-12-10 01:27 UTC by MykhailoShpakov07

2024-12-10 18:02 UTC, 20cognosce requested changes

2024-12-10 18:02 UTC, 20cognosce commented on src/main/java/school/faang/sprint1/task_44648/HogwartsSpells.java
> +        //returns spell event by its id
Имя метода все итак читают

2024-12-10 18:02 UTC, 20cognosce commented on src/main/java/school/faang/sprint1/task_44648/HogwartsSpells.java
> +        if (eventToReturn == null) {
Это хорошо

2024-12-10 18:02 UTC, 20cognosce commented on src/main/java/school/faang/sprint1/task_44648/HogwartsSpells.java
> +        //returns the list of all events by its type ( make it immutable from the outside )
JavaDoc

2024-12-10 18:02 UTC, 20cognosce commented on src/main/java/school/faang/sprint1/task_44648/HogwartsSpells.java
> +        }
Та же беда

2024-12-10 18:02 UTC, 20cognosce commented on src/main/java/school/faang/sprint1/task_44648/HogwartsSpells.java
> +            throw new NoSuchElementException("No events of this event type has been added yet");
Конкретику своих сообщениях неси, как по ним отладку делать

2024-12-10 18:02 UTC, 20cognosce commented on src/main/java/school/faang/sprint1/task_44648/HogwartsSpells.java
> +        //removes event from both maps by using id
.

2024-12-10 18:02 UTC, 20cognosce commented on src/main/java/school/faang/sprint1/task_44648/HogwartsSpells.java
> +        spellsByType.get(eventToDelete.getEventType()).remove(eventToDelete);
Отделить вызов remove

2024-12-10 18:02 UTC, 20cognosce commented on src/main/java/school/faang/sprint1/task_44648/HogwartsSpells.java
> +        if (eventToDelete == null) {
Зачем ты тут get делаешь, если remove возвращает значение итак

2024-12-10 18:02 UTC, 20cognosce commented on src/main/java/school/faang/sprint1/task_44648/HogwartsSpells.java
> +        //prints info about all the events from the spellById map
.

2024-12-11 11:37 UTC, MykhailoShpakov07 commented on src/main/java/school/faang/sprint1/task_44648/SpellEvent.java
> +    }
Можно ли в equals использовать меньше аттрибутов чем в hashCode ? Не хочу включать аттрибут id для проверки равенства

2024-12-13 11:35 UTC, 20cognosce approved these changes

2024-12-13 11:35 UTC, 20cognosce commented on src/main/java/school/faang/sprint1/task_44648/HogwartsSpells.java
> +        //check whether the event with this eventType and description is already present
Не писать бессмысленные комментарии, код должен говорить сам за себя

2024-12-13 11:35 UTC, 20cognosce commented on src/main/java/school/faang/sprint1/task_44648/SpellEvent.java
> +    }
Почему не в отдельном классе?

2024-12-13 11:35 UTC, 20cognosce commented on src/main/java/school/faang/sprint1/task_44648/SpellEvent.java
> +@EqualsAndHashCode
Зачем

2024-12-13 11:35 UTC, 20cognosce commented on src/main/java/school/faang/sprint1/task_44648/SpellEvent.java
> +    private final int id;
Наоборот, все проверки по умолчанию выполнять только по id, если метод не требует другого

2024-12-13 11:35 UTC, 20cognosce commented on src/test/java/school/faang/sprint1/task_44648/HogwartsSpellsTest.java
> +        hogwartsSpells.addSpellEvent(1, CHARM, "This charm is bad!");
Пустые строки добавляй между Arrange Act Assert

2024-12-13 11:35 UTC, 20cognosce commented on src/test/java/school/faang/sprint1/task_44648/HogwartsSpellsTest.java
> +public class HogwartsSpellsTest {
Ok

2024-12-13 11:35 UTC, 20cognosce commented on src/main/java/school/faang/sprint1/task_44648/HogwartsSpells.java
> +     * returns an immutable copied list of all events by its type
@return
@param
{@code} {@link}
Попробуй разные атрибуты

2024-12-13 11:35 UTC, 20cognosce commented on src/main/java/school/faang/sprint1/task_44648/HogwartsSpells.java
> +        spellsByType.get(eventToDelete.getEventType().name()).remove(eventToDelete);
Не лепить вместе вызовы!!!!!!

2024-12-13 11:35 UTC, 20cognosce commented on src/main/java/school/faang/sprint1/task_44648/HogwartsSpells.java
> +    }
Не хорошо делать это публичным методом

2024-12-13 11:35 UTC, merged