BJS2-46246
CorporationX/god_bless pull request #14982
Opened 2024-12-10 10:27 UTC by Narol01

2024-12-10 19:30 UTC, 20cognosce requested changes
Сделать сервис над дроидами

2024-12-10 19:30 UTC, 20cognosce commented on src/main/java/school/faang/task/Main.java
> -}
Удали один раз в конце концов

2024-12-10 19:30 UTC, 20cognosce commented on src/main/java/school/faang/task_46246/Droid.java
> +public class Droid {
Не писать бизнес-логику в сущностях, сущности только хранят данные

2024-12-10 19:30 UTC, 20cognosce commented on src/main/java/school/faang/task_46246/Droid.java
> +    private String name;
final, сколько можно

2024-12-10 19:30 UTC, 20cognosce commented on src/main/java/school/faang/task_46246/Droid.java
> +        return decrypt.encrypt(message, key);
почему у decrypt метод encrypt, забавно

2024-12-10 19:30 UTC, 20cognosce commented on src/main/java/school/faang/task_46246/Droid.java
> +    private String cryptProcess(String message, Function<Character, Character> cryptFunction) {
Хорошая задумка

2024-12-10 19:30 UTC, 20cognosce commented on src/main/java/school/faang/task_46246/Droid.java
> +        DroidMessageEncryptor encryptor = (mes, k) -> cryptProcess(mes, (charB) -> (char) (charB + k));
А что будет если я выйду за лимит, передав в сообщении последний символ? Во что на закодируется
Проверь и пришли скрин

2024-12-10 19:44 UTC, Narol01 commented on src/main/java/school/faang/task_46246/Droid.java
> +        DroidMessageEncryptor encryptor = (mes, k) -> cryptProcess(mes, (charB) -> (char) (charB + k));
![image](https://github.com/user-attachments/assets/56376a3b-48d4-431f-948c-0dd7b3845422)

2024-12-11 14:53 UTC, 20cognosce approved these changes
Работает конечно, но в результате шифрования могут получится кракозябры - это не совсем идеально соответствует условию, но пойдёт

2024-12-11 14:53 UTC, 20cognosce commented on src/main/java/school/faang/task_46246/DroidService.java
> +    }
Наверно они должны быть приватными

2024-12-11 14:54 UTC, merged