Oxana bjs2 46680
CorporationX/god_bless pull request #14990
Opened 2024-12-10 11:36 UTC by OxanaNovozhilova

2024-12-10 17:47 UTC, Kayfral requested changes

2024-12-10 17:47 UTC, Kayfral commented on src/main/java/school/faang/task_46680/Main.java
> +    }
Заметил, что ты используешь строковые литералы ('email', 'sms', 'push') в нескольких местах. Давай вынесем их в константы класса - это защитит от опечаток и упростит поддержку кода.

Или, если хочешь поднять решение на новый уровень, можешь использовать enum NotificationType, тут подумай как реализовать

2024-12-10 17:47 UTC, Kayfral commented on src/main/java/school/faang/task_46680/NotificationManager.java
> +        }
Отличное решение по фильтрации запрещённого контента! Ты здорово расширила базовый функционал задания, это очень хороший подход

2024-12-10 17:47 UTC, Kayfral commented on src/main/java/school/faang/task_46680/NotificationManager.java
> +    }
Было бы здорово добавить проверку параметров на null. Это сделает твой код более устойчивым к ошибкам (два входных параметра)

2024-12-10 17:47 UTC, Kayfral commented on src/main/java/school/faang/task_46680/NotificationManager.java
> +        Consumer<Notification> notification = notifications.get(object.getType());
Стоит добавить проверку на null для параметра object заранее. Это защитит от потенциальных NullPointerException

2024-12-11 05:28 UTC, OxanaNovozhilova commented
Кирилл, спасибо за ревью!

2024-12-11 07:48 UTC, Kayfral approved these changes

2024-12-11 07:48 UTC, merged