lcodio BJS2-45216 double cache
CorporationX/god_bless pull request #15004
Opened 2024-12-10 13:30 UTC by lcodio

solved

2024-12-10 18:56 UTC, 20cognosce requested changes

2024-12-10 18:56 UTC, 20cognosce commented on src/main/java/school/faang/s12task45216/Main.java
> +    }
Методы из одной строчки писать не надо, по объемнее как-нибудь тестируй свой функционал

2024-12-10 18:56 UTC, 20cognosce commented on src/main/java/school/faang/s12task45216/Student.java
> +@EqualsAndHashCode
Зачем тебе переопределять equals hashcode, сверяй студентов по id

2024-12-10 18:56 UTC, 20cognosce commented on src/main/java/school/faang/s12task45216/Subject.java
> +@EqualsAndHashCode
Аналогично

2024-12-10 18:56 UTC, 20cognosce commented on src/main/java/school/faang/s12task45216/StudentDatabase.java
> +    HashMap<Subject, List<Student>> subjectWithStudents;
Где модификаторы
private final

2024-12-10 18:56 UTC, 20cognosce commented on src/main/java/school/faang/s12task45216/StudentDatabase.java
> +        log.info("The Student with Subjects and Grades have added");
subjectsWithGrades вводит в заблуждение
лучше назвать studentToGrades

2024-12-10 18:56 UTC, 20cognosce commented on src/main/java/school/faang/s12task45216/StudentDatabase.java
> +        log.info("The Student with Subjects and Grades have added");
в логе писать конкретику, что произошло, чтобы по ним можно было проводить отладку

2024-12-10 18:56 UTC, 20cognosce commented on src/main/java/school/faang/s12task45216/StudentDatabase.java
> +        log.info("The Subject for Student have added");
Результат computeIfAbsent в переменную складывать и от переменной вызывать put

2024-12-10 18:56 UTC, 20cognosce commented on src/main/java/school/faang/s12task45216/StudentDatabase.java
> +        Optional.ofNullable(student).ifPresent(s -> subjectsWithGrades.remove(s));
Зачем ты Optional вообще так используешь? каждый параметр в него оборачивать не надо, только то, где может прийти null
У где второй кейс, если он всё-таки null? Почему только ifPresent?

Твой лог всегда пишется, не зависимо от того, что в студенте лежит

2024-12-10 18:56 UTC, 20cognosce commented on src/main/java/school/faang/s12task45216/StudentDatabase.java
> +        Optional.ofNullable(subject).ifPresent(s -> subjectWithStudents.put(subject, students));
Ты стёрла старых студентов
Нужно добавить к уже имеющимся по предмету

2024-12-10 18:56 UTC, 20cognosce commented on src/main/java/school/faang/s12task45216/StudentDatabase.java
> +        subjectWithStudents.computeIfAbsent(subject, s -> new ArrayList<>()).add(student);
не лепить вызовы

2024-12-10 18:56 UTC, 20cognosce commented on src/main/java/school/faang/s12task45216/StudentDatabase.java
> +                            v.removeIf(st -> st
Кто такие s, k, v? Понятные имена, кто есть кто

2024-12-10 18:56 UTC, 20cognosce commented on src/main/java/school/faang/s12task45216/StudentDatabase.java
> +                                    .equals(student));
Нельзя вызывать equals у того, что может быть null
Сравнивать Objects.equals

А тут тем более все проверки только по совпадению id должны быть

2024-12-10 18:56 UTC, 20cognosce commented on src/main/java/school/faang/s12task45216/StudentDatabase.java
> +                .ifPresent(s -> subjectWithStudents
Иначе?

2024-12-10 18:56 UTC, 20cognosce commented on src/main/java/school/faang/s12task45216/StudentDatabase.java
> +                .ifPresent(s -> subjectWithStudents
Исключение должно бросаться

2024-12-13 11:59 UTC, lcodio commented on src/main/java/school/faang/s12task45216/Main.java
> +    }
В данном случае, не знаю, наборот, разделила на методы, имитируя тестовые методы., но тесты не успеваю здесь написать.

2024-12-13 19:53 UTC, 20cognosce approved these changes
Пойдет, делай новые задачи

2024-12-13 19:53 UTC, 20cognosce commented on src/main/java/school/faang/s12task45216/StudentDatabase.java
> +            log.info("The student with id {} have removed", student.getId());
Это не правда, remove мог не удалить, он не кидает ошибку, если студента нет такого

2024-12-13 19:53 UTC, 20cognosce commented on src/main/java/school/faang/s12task45216/StudentDatabase.java
> +            log.info("The student with id {} have removed", student.getId());
Ты опять не удалила из второй мапы, где предмету соответствует список студентов
Удалять только по совпадению id

2024-12-13 19:53 UTC, merged