madmax  BJS2-44733
CorporationX/god_bless pull request #15053
Opened 2024-12-10 19:42 UTC by Maksim-13

Организация системы бронирования BJS2-44733 alpha release

2024-12-10 21:33 UTC, mysosnovskaya requested changes

2024-12-10 21:33 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs244733/Status.java
> +public enum Status {
Круто, что статус через перечисление сделал 👍

2024-12-10 21:33 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs244733/BookingNotifier.java
> +    private List<BookingObserver> observers = new ArrayList<>();
final?

2024-12-10 21:33 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs244733/BookingNotifier.java
> +@Getter
Геттер не нужен, иначе у нас кто угодно сможет менять список observers по своему желанию - добавлять в него что-то или удалять, а может даже вообще полностью очистить. Работа со списком observers должна вестись только через методы этого класса addObserver и removeObserver и никак иначе

2024-12-10 21:33 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs244733/BookingNotifier.java
> +    //метод update для всех зарегистрированных наблюдателей, уведомляя их об изменении статуса бронирования.
Комментарий не нужен. Имя метода говорит само за себя)

2024-12-10 21:33 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs244733/BookingSystem.java
> +    // — добавляет комнату в систему.
Комментарии не нужны, имена методов уже говорящие

2024-12-10 21:33 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs244733/BookingSystem.java
> +            System.out.println("Комната с ID " + room.getRoomId() + " уже добавлена.");
Лучше исключения генерировать =)

2024-12-10 21:33 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs244733/BookingSystem.java
> +                .collect(Collectors.toList());
Можно просто `.toList();` вместо `.collect(Collectors.toList());`

2024-12-11 12:20 UTC, Maksim-13 commented on src/main/java/school/faang/bjs244733/BookingNotifier.java
> +    private List<BookingObserver> observers = new ArrayList<>();
Ок

2024-12-11 12:22 UTC, Maksim-13 commented on src/main/java/school/faang/bjs244733/BookingNotifier.java
> +@Getter
остался забытым от первого решения - бывает ), убираю

2024-12-11 12:23 UTC, Maksim-13 commented on src/main/java/school/faang/bjs244733/BookingNotifier.java
> +    //метод update для всех зарегистрированных наблюдателей, уведомляя их об изменении статуса бронирования.
ок, в учебных целях, решил оставить - убираю

2024-12-11 12:26 UTC, Maksim-13 commented on src/main/java/school/faang/bjs244733/BookingSystem.java
> +            System.out.println("Комната с ID " + room.getRoomId() + " уже добавлена.");
Хорошо. (для проверки добавил, в учебных целях)

2024-12-11 12:26 UTC, Maksim-13 commented on src/main/java/school/faang/bjs244733/BookingSystem.java
> +                .collect(Collectors.toList());
Ок

2024-12-11 20:43 UTC, mysosnovskaya approved these changes

2024-12-11 20:43 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs244733/BookingSystem.java
> +            throw new UnsupportedOperationException("Комната с ID " + room.getRoomId() + " уже добавлена.");
На будущее: это исключение в данном случае не подходит, здесь лучше подошел бы IllegalArgumentException, а ещё лучше - своё собственное. 
UnsupportedOperationException используется, например, когда у неизменяемого списка вызывают метод add (пытаются изменить). То есть когда сам по себе метод невозможно выполнить, при любых входных данных

2024-12-11 20:43 UTC, merged