bormoley1983-BJS2-45552
CorporationX/god_bless pull request #15091
Opened 2024-12-11 09:45 UTC by bormoley1983

2024-12-11 15:32 UTC, 20cognosce requested changes

2024-12-11 15:32 UTC, 20cognosce commented on src/main/java/school/faang/Main.java
> -}
.

2024-12-11 15:32 UTC, 20cognosce commented on src/main/java/school/faang/bjs245552/Character.java
> +    private List<Item> inventory;
final

2024-12-11 15:32 UTC, 20cognosce commented on src/main/java/school/faang/bjs245552/Character.java
> +@AllArgsConstructor
RequiredArgs

2024-12-11 15:32 UTC, 20cognosce commented on src/main/java/school/faang/bjs245552/SampleData.java
> +        manager.removeItem(frodo, (item) -> item.getName().equals("The One Ring"));
Objects.equals
name = null -> NPE

2024-12-11 15:32 UTC, 20cognosce commented on src/main/java/school/faang/bjs245552/InventoryManager.java
> +        }
Вынести в один приватный метод валидации, принимающий Object

2024-12-11 15:32 UTC, 20cognosce commented on src/main/java/school/faang/bjs245552/InventoryManager.java
> +            System.out.println("Item was removed from character's inventory");
Тут может ведь все предметы удалить, не только 1
Логируй конкретику, что удалили, если хочешь залогировать

2024-12-11 15:32 UTC, 20cognosce commented on src/main/java/school/faang/bjs245552/InventoryManager.java
> +        }
.

2024-12-11 15:32 UTC, 20cognosce commented on src/main/java/school/faang/bjs245552/InventoryManager.java
> +        }
Нет, это не пойдет, слишком архаично

Тебе нужно сделать два стрима - один с фильтром по предикату и с маппингом по функции, а второй по отрицанию предиката
И из них двоих сделать один общий стрим через concat

2024-12-11 15:32 UTC, 20cognosce commented on src/main/java/school/faang/bjs245552/InventoryManager.java
> +        }
И обновить инвентарь

2024-12-11 15:32 UTC, 20cognosce commented on src/main/java/school/faang/bjs245552/InventoryManager.java
> +    }
Что это и зачем? убрать лишнее

2024-12-11 16:31 UTC, bormoley1983 commented on src/main/java/school/faang/bjs245552/InventoryManager.java
> +        }
У меня, кстати, есть решение со стримами в предыдушем чекине.

2024-12-13 11:47 UTC, 20cognosce approved these changes

2024-12-13 11:47 UTC, 20cognosce commented on src/main/java/school/faang/bjs245552/Character.java
> +@RequiredArgsConstructor()
Скобки пустые не нужны

2024-12-13 11:47 UTC, 20cognosce commented on src/main/java/school/faang/bjs245552/Character.java
> +    @NonNull
Ты уверен, что она сработает на обоих конструкторах? Нужен тест

2024-12-13 11:47 UTC, 20cognosce commented on src/main/java/school/faang/bjs245552/InventoryManager.java
> +    }
В этом методе допустим это работает, но это совершенно не универсально и может быть криво использовано

2024-12-13 11:47 UTC, 20cognosce commented on src/main/java/school/faang/bjs245552/InventoryManager.java
> +        validate(character, "character", item, "item", consumer, "consumer");
Не надо передавать имя, можешь вызвать .getClass().getName() - типо того, рефлексия
Только в java 17 она по умолчанию запрещена, её нужно разрешить настройкой запуска jvm

2024-12-13 11:47 UTC, 20cognosce commented on src/main/java/school/faang/bjs245552/InventoryManager.java
> +            throw new IllegalArgumentException("Item was not found in character's inventory");
Не очень рационально проходить по списку с фильтрацией и сохранить список элементов к удалению, чтобы просто потом это залогировать

Чтобы не пропадать логике впустую, может вместо removeIf лучше было использовать
```
boolean removeAll(Collection<?> c);
retainAll
replaceAll
```
что-нибудь из этого?

2024-12-13 11:47 UTC, 20cognosce commented on src/main/java/school/faang/bjs245552/InventoryManager.java
> +        character.getInventory().replaceAll(item -> predicate.test(item) ? function.apply(item) : item);
На дейли обсуждали красивое решение, так тоже пойдёт

2024-12-13 11:47 UTC, merged