Created classes and methods.
CorporationX/god_bless pull request #15097
Opened 2024-12-11 10:22 UTC by Arzamas-Ilya

2024-12-12 09:05 UTC, Kayfral requested changes

2024-12-12 09:05 UTC, Kayfral commented on src/main/java/school/faang/task_46846/Main.java
> +                notification -> System.out.println("Отправка push-уведомления: " + notification.getMessage()));
Заметил, что ты используешь строковые литералы ('email', 'sms', 'push') в нескольких местах. Как вариант, можно было бы вынести их в константы класса - это защитит от опечаток и упростит поддержку кода.

Или, если хочешь поднять решение на новый уровень, можно использовать enum NotificationTyp

2024-12-12 09:05 UTC, Kayfral commented on src/main/java/school/faang/task_46846/NotificationManager.java
> +    }
Я бы еще добавил проверку для двух параметров, чтобы в мапе лежали только целостные данные. Чтобы consumer не равнялся null

2024-12-12 09:05 UTC, Kayfral commented on src/main/java/school/faang/task_46846/NotificationManager.java
> +    }
Давай подумаем про надёжность кода. Было бы здорово добавить проверку на null, а также предусмотреть ситуацию, когда нет подходящего обработчика для типа уведомления. Так код станет устойчивее к ошибкам

2024-12-13 21:03 UTC, Arzamas-Ilya commented on src/main/java/school/faang/task_46846/NotificationManager.java
> +    }
tipe заменил на enum. А какую проверку добавить для consumer?

2024-12-14 11:03 UTC, Kayfral requested changes

2024-12-14 11:03 UTC, Kayfral commented on src/main/java/school/faang/task_46846/NotificationManager.java
> +    }
Вижу, что ты добавил проверку на null для notification - здорово! Но, давай подумаем, что будет если у нас нет подходящего обработчика для отправки уведомлений? Программа будет получать NullPointerException, следовательно нужно проверить, что тип уведомления существует

2024-12-14 11:03 UTC, Kayfral commented on src/main/java/school/faang/task_46846/NotificationManager.java
> +    }
Отлично, вижу, что ты добавил проверку на null для notification - здорово! Но, что будет если у нас нет подходящего обработчика для отправки сообщения? Будет NullPointerException, следовательно, нужно сделать пороверку, что такой обработчик существует

2024-12-15 08:53 UTC, Kayfral approved these changes
Отлично!

2024-12-15 08:53 UTC, merged