task stream 2 impl
CorporationX/god_bless pull request #15115
Opened 2024-12-11 12:49 UTC by bortsovamaria

2024-12-11 20:34 UTC, mysosnovskaya requested changes

2024-12-11 20:34 UTC, mysosnovskaya commented on src/main/java/school/faang/task_47040/Operations.java
> +                .filter(num -> set.contains(target - num))
Если в Set у нас два числа 1 и 3, а  target = 6, то таким алгоритмом мы найдем пару 3 и 3, которой в реальности нет)

2024-12-11 20:34 UTC, mysosnovskaya commented on src/main/java/school/faang/task_47040/Operations.java
> +    public static List<String> getCapitals(Map<String, String> countriesWithCapitals) {
Назвать можно getSortedCapitals, чтобы подчеркнуть, что возвращается отсортированный список

2024-12-11 20:34 UTC, mysosnovskaya commented on src/main/java/school/faang/task_47040/Operations.java
> +                .filter(s -> s.startsWith("a"))
Почему "a"? Символ лучше вынести в параметры

2024-12-11 20:34 UTC, mysosnovskaya commented on src/main/java/school/faang/task_47040/Operations.java
> +                .filter(s -> isExistAlphabet(s, alphabet))
Давай вместо отдельного метода сделаем через regex (через регулярные выражения). Так код будет проще)

2024-12-12 20:30 UTC, mysosnovskaya requested changes

2024-12-12 20:30 UTC, mysosnovskaya commented on src/main/java/school/faang/task_47040/Operations.java
> +                .filter(num -> set.contains(target - num) && num != target - num)
А теперь наоборот =)
Если в Set у нас два числа у и 3, а target = 6, то таким алгоритмом мы НЕ найдем пару 3 и 3, которая в реальности есть)

2024-12-14 12:42 UTC, bortsovamaria commented on src/main/java/school/faang/task_47040/Operations.java
> +                .filter(num -> set.contains(target - num) && num != target - num)
Добавила проверку на индексы, чтобы вычислить один там такой элемент или два  :)

2024-12-14 17:56 UTC, mysosnovskaya approved these changes

2024-12-14 17:56 UTC, merged