abstraction task
CorporationX/god_bless pull request #15164
Opened 2024-12-11 20:40 UTC by ZhannaD

2024-12-11 20:54 UTC, mysosnovskaya requested changes

2024-12-11 20:54 UTC, mysosnovskaya commented on src/main/java/school/faang/abstraction/Archer.java
> +
Я бы ещё добавила конструктор со всеми параметрами, который будет вызывать соответствующий родительский конструктор. Иначе непонятно, зачем родительский нужен) Ну и нужно иметь возможность создавать объект с параметрами НЕ по умолчанию, а с произвольными

2024-12-11 20:54 UTC, mysosnovskaya commented on src/main/java/school/faang/abstraction/Archer.java
> +        character.setHealth(character.getHealth() - DEFAULT_DEXTERITY);
1. Лучше не DEFAULT_DEXTERITY использовать, т.к. если будет конструктор со всеми параметрами (о чем мой предыдущий комментарий), то значение поля dexterity может быть произвольным
2. А также необходимо убедиться, что здоровье не стало меньше нуля. А то у нас так персонаж будет жить вечно, просто здоровье будет становится всё меньше и меньше, уходя в минус)

2024-12-11 20:54 UTC, mysosnovskaya commented on src/main/java/school/faang/abstraction/Warrior.java
> +public class Warrior extends Character {
Здесь комментарии аналогичны Archer

2024-12-12 07:48 UTC, ZhannaD commented on src/main/java/school/faang/abstraction/Archer.java
> +
constructor with all params added

2024-12-12 19:57 UTC, mysosnovskaya requested changes

2024-12-12 19:57 UTC, mysosnovskaya commented on src/main/java/school/faang/abstraction/Character.java
> +            throw new IllegalArgumentException("Health cannot be less than 0!");
В get методе уже поздно бросать исключение. Нужно сообщать о том, что что-то пошло не так, в тот момент, когда это происходит. В твоем случае это будет в set-методе.

2024-12-12 19:57 UTC, mysosnovskaya commented on src/main/java/school/faang/abstraction/Character.java
> +    private static final int DEFAULT_HEALTH = 100;
И давай наведем порядок в классе в стиле java: сначала идут поля (в самом верху константы, потом остальные), затем конструкторы, после этого абстрактные методы, потом все остальные (они кстати тоже располагаются в определенном порядке: сначала все публичные, потом приватные, но у тебя имеются только публичные)

2024-12-12 20:23 UTC, ZhannaD commented on src/main/java/school/faang/abstraction/Character.java
> +    private static final int DEFAULT_HEALTH = 100;
Thank you for your comment!

2024-12-12 20:38 UTC, mysosnovskaya approved these changes

2024-12-12 20:38 UTC, merged