BJS2-45769 Sprint02. Task04. GMail. Predicate, Consumer, Function
CorporationX/god_bless pull request #15188
Opened 2024-12-12 03:48 UTC by Mike-GB22

Вы — разработчик приложения GMail и сейчас работаете над функцией, которая позволит пользователям настраивать фильтры для входящих писем. Задача — создать систему, которая будет фильтровать, обрабатывать и преобразовывать письма с использованием функциональных интерфейсов: Predicate, Consumer, и Function.

Цель:

Создайте класс EmailProcessor, который будет применять Predicate для фильтрации писем, Consumer для их обработки и Function для преобразования.

Требования:

1. Создайте класс Email с полями:

subject — тема письма;

body — текст письма;

isImportant — флаг, указывающий, важное письмо или нет.

2. Создайте класс EmailProcessor с методом processEmails.

3. Метод processEmails должен:

принимать список входящих писем;

фильтровать их с помощью Predicate<Email>

преобразовывать тело письма с помощью Function<Email, String>.

обрабатывать каждое письмо с помощью Consumer<Email>

4. Создайте несколько лямбда-выражений для Predicate, Consumer, и Function, чтобы настроить фильтрацию и обработку писем по вашему выбору.

5. Протестируйте систему, обрабатывая несколько писем и выводя результаты в консоль.

Пример использования:

EmailProcessor emailProcessor = new EmailProcessor();

// Список входящих писем
List<Email> emails = Arrays.asList(
    new Email("Письмо 1", "Текст письма 1", false),
    new Email("Письмо 2", "Текст письма 2", true),
    new Email("Спам", "Текст спама", false)
);

// Фильтр, который пропускает только важные письма
Predicate<Email> importantFilter = email -> email.isImportant();

// Обработчик, который выводит тему письма в консоль
Consumer<Email> printEmail = email -> System.out.println("Обработано письмо: " + email.getSubject());

// Преобразователь, который переводит текст письма в верхний регистр и сохраняет изменения
Function<Email, String> toUpperCase = email -> {
    email.setBody(email.getBody().toUpperCase());
    return email.getBody();  // Возвращает преобразованный текст
};

// Обработка писем
emailProcessor.processEmails(emails, importantFilter, printEmail, toUpperCase);

// Выводим обновленные письма, чтобы убедиться, что изменения сохранились
emails.forEach(email -> System.out.println("Тема: " + email.getSubject() + ", Тело письма: " + email.getBody()));

2024-12-12 08:36 UTC, Kayfral requested changes

2024-12-12 08:36 UTC, Kayfral commented on src/main/java/derschrank/sprint02/task04/bjstwo_45769/EmailProcessor.java
> +    }
Для большей надежности кода предлагаю добавить проверку входных параметров на null в методе, чтобы у тебя не было потенциальной возможности поймать NullPointerException

2024-12-12 08:36 UTC, Kayfral commented on src/main/java/derschrank/sprint02/task04/bjstwo_45769/EmailProcessor.java
> +    }
Если хочешь, можешь for переписать при помощи stream api

2024-12-12 08:36 UTC, Kayfral commented on src/main/java/derschrank/sprint02/task04/bjstwo_45769/EmailProcessor.java
> +    }
Параметр whatWithEmailToDo лучше переименовать в emailAction или emailConsumer

2024-12-12 08:36 UTC, Kayfral commented on src/main/java/derschrank/sprint02/task04/bjstwo_45769/Main.java
> +    }
Здесь лучше убрать комментарии. Так как они излишни

2024-12-12 14:57 UTC, Mike-GB22 commented on src/main/java/derschrank/sprint02/task04/bjstwo_45769/EmailProcessor.java
> +    }
> Для большей надежности кода предлагаю добавить проверку входных параметров на null в методе, чтобы у тебя не было потенциальной возможности поймать NullPointerException

Спасибо, да, Теперь я вижу что можно заменить.
Но я хотел бы оставить так как есть, чтоб не усложнять понимание для себя.
Это же раздел Лямбд. Задачи на Стримы будут следующие, там я буду усложнять.
А тут я всегда смогу глянуть и вспомнить что и как работает

2024-12-12 14:59 UTC, Mike-GB22 commented on src/main/java/derschrank/sprint02/task04/bjstwo_45769/EmailProcessor.java
> +    }
> Для большей надежности кода предлагаю добавить проверку входных параметров на null в методе, чтобы у тебя не было потенциальной возможности поймать NullPointerException

точно! спасибо

а если я бы сделал через Stream API, можно было бы не делать проверку на null?

2024-12-12 15:01 UTC, Mike-GB22 commented on src/main/java/derschrank/sprint02/task04/bjstwo_45769/EmailProcessor.java
> +    }
> emailConsumer

всегда лучше указывать в имени перменой сперва, для чего это? ну например слово email?

2024-12-12 15:02 UTC, Mike-GB22 commented on src/main/java/derschrank/sprint02/task04/bjstwo_45769/Main.java
> +    }
Это же тестовый модуль, т.е. не программа с бизнес логикой.
Эти комментарии позволяют анализировать мне работу программы и эти комментарии я скопировал из задания.

Можно я их оставлю?

2024-12-12 18:42 UTC, Kayfral commented on src/main/java/derschrank/sprint02/task04/bjstwo_45769/EmailProcessor.java
> +    }
> > Для большей надежности кода предлагаю добавить проверку входных параметров на null в методе, чтобы у тебя не было потенциальной возможности поймать NullPointerException
> 
> точно! спасибо
> 
> а если я бы сделал через Stream API, можно было бы не делать проверку на null?



> > Для большей надежности кода предлагаю добавить проверку входных параметров на null в методе, чтобы у тебя не было потенциальной возможности поймать NullPointerException
> 
> точно! спасибо
> 
> а если я бы сделал через Stream API, можно было бы не делать проверку на null?

Не, Stream API не гарантирует защиту от NullPointerException. 

Просто представим ситуацию, что whatWithEmailToDo = null. Тогда, при вызове (accept), что при использовании Stream API, что при его не использовании мы будем получать структуру null.accept(email); А у null нет таких методов и именно по этому в этой точке будет критическая ситуация

2024-12-12 18:45 UTC, Kayfral commented on src/main/java/derschrank/sprint02/task04/bjstwo_45769/EmailProcessor.java
> +    }
> > emailConsumer
> 
> всегда лучше указывать в имени перменой сперва, для чего это? ну например слово email?

Я надеюсь, что правильно тебя понял. В имени переменной должна отражаться суть данных, которые хранятся в ней. В данном случае, если переменная носит название email, то мы ожидаем, что там будет лежать email, а не что-то другое

2024-12-12 18:47 UTC, Kayfral commented on src/main/java/derschrank/sprint02/task04/bjstwo_45769/Main.java
> +    }
Да, можешь оставить, но они все-таки излишни. Просто представь проект, где сотни и тысячи зависимостей. Там не используют комментарии, чтобы показать за что отвечает тот или иной блок. Там используются инструменты документирования кода (Их вы будете изучать дальше в программе)

2024-12-12 18:49 UTC, Kayfral commented on src/main/java/derschrank/sprint02/task04/bjstwo_45769/Main.java
> +    }
Основная идея нынешней разработки - это сделать такой код, который сам говорит за себя и не нуждается в каком-либо пояснении

2024-12-12 18:55 UTC, Kayfral requested changes

2024-12-12 18:55 UTC, Kayfral commented on src/main/java/derschrank/sprint02/task04/bjstwo_45769/EmailProcessor.java
> +    }
Тут нужно проверить все входные данные на null, потому что любой из них может дать NullPointerException. Давай, ты сделаешь эти проверки, а в комментарии к моей ремарке напишешь места потенциальных NullPointerException.

На всякий случай, я разобрал момент возникновения NullPointerException в однок коментарии на твой вопрос

2024-12-12 19:51 UTC, Mike-GB22 commented on src/main/java/derschrank/sprint02/task04/bjstwo_45769/EmailProcessor.java
> +    }
> Параметр whatWithEmailToDo лучше переименовать в emailAction или emailConsumer

просто Вы сказали что лучше назвать emailAction / emailConsumer вот и думаю, как это понять, когда надо указывать на связь с email, когда нет

2024-12-12 22:33 UTC, Mike-GB22 commented on src/main/java/derschrank/sprint02/task04/bjstwo_45769/EmailProcessor.java
> +    }
> Тут нужно проверить все входные данные на null, потому что любой из них может дать NullPointerException. Давай, ты сделаешь эти проверки, а в комментарии к моей ремарке напишешь места потенциальных NullPointerException.
> 
> На всякий случай, я разобрал момент возникновения NullPointerException в однок коментарии на твой вопрос

Теперь запутался. Мне надо проверить предикарт/функтион/косумер?

2024-12-12 22:41 UTC, Mike-GB22 commented on src/main/java/derschrank/sprint02/task04/bjstwo_45769/Main.java
> +    }
Хорошо

2024-12-13 05:22 UTC, Kayfral approved these changes

2024-12-13 05:22 UTC, merged