Maks1979 bjs2 45564
CorporationX/god_bless pull request #15202
Opened 2024-12-12 08:54 UTC by sanctus-germanus

Задача с лямбдами

2024-12-12 09:01 UTC, sanctus-germanus commented
Получается, теперь при отправке любой ветки в пулл-реквест нужно в проекте по этой ветке открывать все пакеты и исправлять там чек-стайл?

2024-12-12 18:19 UTC, SemyonKrivtsov requested changes
Давай в ПР оставим только то что относится к задаче на ревью

2024-12-12 18:19 UTC, SemyonKrivtsov commented on src/main/java/ru/maks1979/task_43633/Example.java
> +            System.out.println("Массив не может быть пустым");
Тут лучше выдавать исключение

2024-12-12 18:19 UTC, SemyonKrivtsov commented on src/main/java/ru/maks1979/task_43633/Main.java
А хотим это коммитеть? В ПР должны быть файлы только по задаче "Хогвартс, Хогвартс, наш любимый Хогвартс"

2024-12-12 18:19 UTC, SemyonKrivtsov commented on src/main/java/ru/maks1979/task_44030/Main.java
Аналогично, из другой задачи

2024-12-12 18:19 UTC, SemyonKrivtsov commented on src/main/java/ru/maks1979/task_45564/Main.java
> +        String oneMoreName = "Avos'";
Зачем кавычка?

2024-12-13 06:35 UTC, sanctus-germanus commented on src/main/java/ru/maks1979/task_45564/Main.java
> +        String oneMoreName = "Avos'";
Это типа мягкого знака в слове "авось"

2024-12-13 08:35 UTC, merged