BJS2-47177
CorporationX/god_bless pull request #15229
Opened 2024-12-12 14:27 UTC by Narol01

2024-12-12 14:30 UTC, Narol01 commented
Я понятия не имею как мне удалить этот main, я удалил его в ветке сделал коммит , потом запушил всё и потом создал новую ветку из той в которой удалил mainи вот он здесь в виде коммита

2024-12-15 14:48 UTC, 20cognosce commented
> Я понятия не имею как мне удалить этот main, я удалил его в ветке сделал коммит , потом запушил всё и потом создал новую ветку из той в которой удалил mainи вот он здесь в виде коммита

Ты должен один раз его удалить в каком-нибудь коммите и залить этот коммит в твой основную ветку narol

Затем все новые ветки, которые создаются от базовой, должны ребазироваться от последнего коммита, где мэйн уже удалён

2024-12-15 14:53 UTC, 20cognosce requested changes

2024-12-15 14:53 UTC, 20cognosce commented on src/main/java/school/faang/task_47177/StreamOperations.java
> +        Set<Integer> pairs = new HashSet<>(numbers);
Нельзя, только методами стримов

2024-12-15 14:53 UTC, 20cognosce commented on src/main/java/school/faang/task_47177/StreamOperations.java
> +        Set<Integer> pairs = new HashSet<>(numbers);
У стрима есть специальный метод для этого

2024-12-15 14:53 UTC, 20cognosce commented on src/main/java/school/faang/task_47177/StreamOperations.java
> +                    List<Integer> pair = Arrays.asList(num, sum - num);
не надо список, используй Entry или Pair класс (из Spring Core)

2024-12-15 14:53 UTC, 20cognosce commented on src/main/java/school/faang/task_47177/StreamOperations.java
> +                .map(num -> {
А можно Collections.sort(pair) отделить в отдельную стадию пайплайна стрима?

2024-12-15 14:53 UTC, 20cognosce commented on src/main/java/school/faang/task_47177/StreamOperations.java
> +        String regex = "[" + alphabet + "]+";
Использовать специальные классы для работы с регулярками

2024-12-15 14:53 UTC, 20cognosce commented on src/main/java/school/faang/task_47177/Main.java
> +        List<String> filteredByRegexAndSorted = new StreamOperations().filterAndSortByLength(words, alphabet);
Протести, что какое-нибудь слово не попадает в алфавит, а лучше тесты на все методы напиши

2024-12-16 15:55 UTC, Narol01 commented on src/main/java/school/faang/task_47177/StreamOperations.java
> +                .distinct()
да

2024-12-16 16:04 UTC, Narol01 commented on src/main/java/school/faang/task_47177/StreamOperations.java
> +                    Collections.reverse(numbers);
собирает в пары , сортирует после этого числа и я могу через distinct сделать пары уникальными вместо 6 пар где есть (1,6)  и  (6,1) только один вариант первый вариант

2024-12-16 16:10 UTC, Narol01 commented on src/main/java/school/faang/task_47177/StreamOperations.java
> +                .distinct()
(я не туда тыкнул и комментарий удалил) Я там писал что я собираю в пары и сортирую что бы создалось 6 пар три из которых одинаковы. Пример : вместо (6,1) и (1,6) создаётся две пары (1,6) и поэтому через distinct() я удаляю повторы и остаётся три уникальных пары

2024-12-16 20:59 UTC, 20cognosce approved these changes
Принято

2024-12-16 20:59 UTC, 20cognosce commented on src/main/java/school/faang/task_47177/StreamOperations.java
> +                    Collections.reverse(numbers);
Всё равно сомневаюсь и недоумеваю смотря на Collections.reverse(numbers);
Ладно, допустим

2024-12-16 20:59 UTC, merged