Solve task_45298
CorporationX/god_bless pull request #15248
Opened 2024-12-12 18:01 UTC by shamshaev

2024-12-12 21:04 UTC, mysosnovskaya requested changes
Всё хорошо, но согласованность нужно добавить)

2024-12-12 21:04 UTC, mysosnovskaya commented on src/main/java/school/faang/task_45298/StudentDatabase.java
> +public class StudentDatabase {
Обе хэш мапы (subjectGradesByStudent и studentsBySubject) должны быть согласованными. Если что-то добавилось в одну из них, то должно добавиться и во вторую. Также с удалением

2024-12-12 21:04 UTC, mysosnovskaya commented on src/main/java/school/faang/task_45298/StudentDatabase.java
> +        subjectGradesByStudent.put(student, grades);
Например, здесь ещё нужно убедиться, что в studentsBySubject записано, что студент изучает все предметы из grades

2024-12-12 21:04 UTC, mysosnovskaya commented on src/main/java/school/faang/task_45298/StudentDatabase.java
> +        subjectGradesByStudent.remove(student);
А здесь - соответственно удалить и из studentsBySubject, т.к. видимо студент выпустился или отчислился, раз все данные о нем удаляются)

2024-12-13 12:11 UTC, shamshaev commented on src/main/java/school/faang/task_45298/StudentDatabase.java
> +public class StudentDatabase {
Понял, но тогда вдвойне криво, что по условиям методы нужно создавать в StudentDatabase, a мапы в Main. Были бы мапы в StudentDatabase было бы логичнее и доступ к ним прямой

2024-12-13 14:23 UTC, shamshaev commented
Постоянно забываю, что в ваших задачах нужно смотреть шире, чем то что написано) Хорошие задачи

2024-12-13 19:24 UTC, mysosnovskaya approved these changes

2024-12-13 19:24 UTC, merged