Stream API 2
CorporationX/god_bless pull request #15279
Opened 2024-12-12 20:52 UTC by almigor1

2024-12-12 21:06 UTC, mysosnovskaya requested changes

2024-12-12 21:06 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task47405/StreamFunc.java
> +                .map(n -> Arrays.asList(n, sum - n))
Не понимаю, откуда уверенность, что число `sum - n` точно есть в numbers?

2024-12-12 21:22 UTC, almigor1 commented on src/main/java/school/faang/sprint2/task47405/StreamFunc.java
> +                .map(n -> Arrays.asList(n, sum - n))
тут я так рассуждаю:
если у нас есть некий sum, то , чтобы добить до этого sum, другое число должно быть как минимум меньше sum. 
отобрали все такие числа в стриме, далее кладем эти числа в пары

2024-12-12 21:24 UTC, almigor1 commented on src/main/java/school/faang/sprint2/task47405/StreamFunc.java
> +                .map(n -> Arrays.asList(n, sum - n))
тут я так рассуждаю:
если у нас есть некий sum, то , чтобы добить до этого sum, другое число должно быть как минимум меньше sum.
отобрали все такие числа в стриме, далее кладем эти числа в пары. 

но я , похоже не понял условие задачи, тут надо не добивать до sum любым числом, а выбирать , чем "добить" из списка. переделаю

2024-12-13 19:45 UTC, mysosnovskaya requested changes

2024-12-13 19:45 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task47405/StreamFunc.java
> +                .filter(n -> tempNumbers.contains(sum - n))
Да, с проверкой на contains это почти будет работать правильно) Но если в tempNumbers у нас два числа 1 и 3, а sum = 6, то таким алгоритмом ты найдешь пару 3 и 3, которой в реальности нет)

2024-12-13 23:17 UTC, almigor1 commented on src/main/java/school/faang/sprint2/task47405/StreamFunc.java
> +                .filter(n -> tempNumbers.contains(sum - n))
ну вот такой вариант сделал, с удалением из сета. 
У многих кстати такой тест не пройдет, я посмотрел.

2024-12-14 17:58 UTC, mysosnovskaya approved these changes

2024-12-14 17:58 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task47405/StreamFunc.java
> +                .peek(tempNumbers::remove)
Крутое решение!)

2024-12-14 17:58 UTC, merged