BJS2-44933, Project team management
CorporationX/god_bless pull request #15274
Opened 2024-12-12 20:29 UTC by Maksim-13

2024-12-13 19:58 UTC, mysosnovskaya requested changes

2024-12-13 19:58 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs244933/ProjectManager.java
> +    private Map<Integer, Employee> employeeById;
final?

2024-12-13 19:58 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs244933/ProjectManager.java
> +                if (teamMembers.get(i).getId() == employeeId) {
У тебя же есть хэш мапа employeeById, откуда ты сразу по employeeId можешь получить нужного сотрудника и сразу удалить его из teamMembers, без этого цикла

2024-12-13 19:58 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs244933/ProjectManager.java
> +    public List<Employee> getTeamMembers(int projectId) {
А метод getTeamForProject не то же самое разве делает?

2024-12-14 10:18 UTC, Maksim-13 commented on src/main/java/school/faang/bjs244933/ProjectManager.java
> +    private Map<Integer, Employee> employeeById;
Ок, исправил

2024-12-14 10:20 UTC, Maksim-13 commented on src/main/java/school/faang/bjs244933/ProjectManager.java
> +    public void setAssignmentStrategy(TeamAssignmentStrategy strategy) {
Ок, исправил

2024-12-14 10:30 UTC, Maksim-13 commented on src/main/java/school/faang/bjs244933/BalancedTeamAssignmentStrategy.java
> +            int count = projectCount.getOrDefault(employee, 0);
Содрал этот метод полностью из раздела «Дополнительные материалы» сам был удивлен, но потом подумал, в учебных целях этот метод что-то делает и хорошо, не этом смысл, главное паттерн по юзать. Конечно теперь переделал, на будущее можно обратить на это внимание, что в задачке этот метод не совсем корректный.

2024-12-14 10:56 UTC, Maksim-13 commented on src/main/java/school/faang/bjs244933/ProjectManager.java
> +                if (teamMembers.get(i).getId() == employeeId) {
исправил

2024-12-14 11:01 UTC, Maksim-13 commented on src/main/java/school/faang/bjs244933/ProjectManager.java
> +    public List<Employee> getTeamMembers(int projectId) {
Так же был удивлен, когда читал указания к задаче, но решил, раз просят добавить этот метод. ))
Можно на будущее, предупреждать студентов: "в задачах есть пасхалки, кто найдет больше всего, получит мерч". )) Удалил этот метод.

2024-12-17 15:48 UTC, merged