BJS2-47101 was completed.
CorporationX/god_bless pull request #15272
Opened 2024-12-12 20:19 UTC by LeshaKoz

BJS2-47101 was completed.

2024-12-12 20:33 UTC, mysosnovskaya requested changes

2024-12-12 20:33 UTC, mysosnovskaya commented on src/main/java/school/faang/task_47101/MultiOperations.java
> +        if (sum == 0) {
А чем плохо, когда sum равно 0? У нас может быть пара 0 и 0 или пара 1 и -1 =)

2024-12-12 20:33 UTC, mysosnovskaya commented on src/main/java/school/faang/task_47101/MultiOperations.java
> +                .filter(number -> set.contains(sum - number))
Если в Set у нас два числа 1 и 3, а target = 6, то таким алгоритмом мы найдем пару 3 и 3, которой в реальности нет)

2024-12-12 20:33 UTC, mysosnovskaya commented on src/main/java/school/faang/task_47101/MultiOperations.java
> +        }
Мне кажется, зря ты боишься пустых мап (и ниже - списков). Ничего в них страшного нет, стрим отработает корректно, тоже вернет пустой список. Это выглядит вполне корректным поведением

2024-12-12 20:33 UTC, mysosnovskaya commented on src/main/java/school/faang/task_47101/MultiOperations.java
> +        if (!Character.isLetter(letter)) {
У нас по заданию это может быть вообще любой символ, не только буква

2024-12-12 20:33 UTC, mysosnovskaya commented on src/main/java/school/faang/task_47101/MultiOperations.java
> +        String regex = "[" + alphabet + "]+";
Круто 👍

2024-12-13 19:43 UTC, mysosnovskaya requested changes

2024-12-13 19:43 UTC, mysosnovskaya commented on src/main/java/school/faang/task_47101/MultiOperations.java
> +                .filter(number -> set.contains(sum - number) && (number != (sum - number)))
А теперь наоборот: если в Set у нас два числа 3 и 3, а target = 6, то таким алгоритмом мы НЕ найдем пару 3 и 3, которая в реальности есть)

2024-12-14 19:37 UTC, LeshaKoz commented on src/main/java/school/faang/task_47101/MultiOperations.java
> +                .filter(number -> set.contains(sum - number) && (number != (sum - number)))
В интерфейсе Set не может быть два числа 3 и 3, он может хранить только уникальные значения, для чего он здесь и используется.

2024-12-14 21:19 UTC, mysosnovskaya commented on src/main/java/school/faang/task_47101/MultiOperations.java
> +                .filter(number -> set.contains(sum - number) && (number != (sum - number)))
Ошиблась, не в Set, а в List - имею в виду в numbers)

2024-12-14 23:35 UTC, LeshaKoz commented
Переделал алгоритм.

2024-12-15 17:37 UTC, mysosnovskaya approved these changes

2024-12-15 17:37 UTC, merged