BJS2-46100 Вспомним школу
CorporationX/god_bless pull request #15295
Opened 2024-12-12 23:34 UTC by rsticks

2024-12-13 19:32 UTC, mysosnovskaya requested changes

2024-12-13 19:32 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs246100/TriangleAreaCalculator.java
> +    Function<Double, Double> squareRoot = Math::sqrt;
Модификаторы доступа потерялись

2024-12-13 19:32 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs246100/TriangleAreaCalculator.java
> +        return squareRoot.apply(multiply.apply(multiply.apply(multiply.apply(semiPerimeter)
Эти семь apply нужно разбивать) Сделай несколько переменных с говорящими названиями, чтобы можно было разобраться, что здесь происходит

2024-12-13 19:32 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs246100/TriangleAreaCalculator.java
> +        return divide.apply(add.apply(add.apply(a).apply(b)).apply(c)).apply(2.0);
Здесь тоже - нужно разбить на несколько переменных

2024-12-13 19:32 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs246100/TriangleAreaCalculator.java
> +    private Double getSemiPerimeter(Double a, Double b, Double c) {
С приватным методом хорошо придумал 👍

2024-12-16 17:37 UTC, miked4king approved these changes

2024-12-18 21:33 UTC, merged