BJS2-45928
CorporationX/god_bless pull request #15297
Opened 2024-12-12 23:56 UTC by Mregzer

2024-12-13 18:32 UTC, SemyonKrivtsov requested changes

2024-12-13 18:32 UTC, SemyonKrivtsov commented on src/main/java/school/faang/sprint2/task_45928/EmailProcessor.java
> +        // Цикл сделан, через i, потому что в ином случае
Старайся не использовать комментарии в коде, хороший код сам говорит за себя.
Комментарий можно оставить в ПР

2024-12-13 18:32 UTC, SemyonKrivtsov commented on src/main/java/school/faang/sprint2/task_45928/Main.java
> +        emails.add(new Email("Письмо 1", "Текст письма 1", false));
Это можно модифицировать, чтобы не вызывать add каждый раз

2024-12-13 23:37 UTC, Mregzer commented on src/main/java/school/faang/sprint2/task_45928/Main.java
> +        emails.add(new Email("Письмо 1", "Текст письма 1", false));
Если это делать через List.of(), то List получается неизменяемым

2024-12-14 09:34 UTC, SemyonKrivtsov commented on src/main/java/school/faang/sprint2/task_45928/Main.java
> +        emails.add(new Email("Письмо 1", "Текст письма 1", false));
Тогда можно в цикле это автоматизировать

2024-12-14 09:35 UTC, merged