AntonGraf-BJS2-47153
CorporationX/god_bless pull request #15310
Opened 2024-12-13 06:51 UTC by AntonGraf

Решение задачи "Анализ активности пользователей в социальной сети"

2024-12-13 19:33 UTC, 20cognosce requested changes

2024-12-13 19:33 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +        });
Это не доработал
collect(Collectors.groupingBy) позволит тебе сделать подсчёт

2024-12-13 19:33 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +        Map<String, Integer> hashTags = new HashMap<>();
Нет, никаких хэшмап в этой задаче, только стримы

2024-12-13 19:33 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +    }
Давай без мап и дополнительных структур, только на функциональных интерфейсах и стримах

2024-12-13 19:33 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +    }
Тебе подойдет flatMap, который принимает функцию, которая на вход берет действие, а на выход стрим хэштегов

2024-12-13 19:33 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +                .forEach(action -> addHashtags(action, hashTags));
я сколько раз говорил про Objects.equals

и почему ты отфильтровал только по двум категориям?

2024-12-13 19:33 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +        Map<Integer, Integer> users = new HashMap<>();
С мапами не приму

2024-12-13 19:33 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +                .filter(action -> action.getActionType().equals(ActionType.COMMENT))
?

2024-12-13 19:33 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +                });
Нет, это легкий и не красивый путь

2024-12-13 19:33 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +        actionsByType.forEach((key, value) -> percentages.put(key, 100.0 * value / actionsCount));
Только стримами надо решить

2024-12-13 19:33 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +                .filter(action -> userId.equals(action.getUserId()))
equals...

2024-12-13 19:33 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +                .findAny()
нельзя findAny, findFirst
Надо точно - ровно один, иначе ошибка

2024-12-14 10:55 UTC, AntonGraf commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +                .forEach(action -> addHashtags(action, hashTags));
В условии: Топ-5 наиболее популярных тем обсуждения (по количеству упоминаний хештегов в постах и комментариях).

2024-12-15 15:22 UTC, 20cognosce requested changes
Первый метод не принимается

2024-12-15 15:22 UTC, 20cognosce commented on src/test/java/school/faang/bjs_47153/UserActionAnalyzerTest.java
> +    private static List<UserAction> getActions() {
Зачем в метод? Ты ведь никак исходный список не модифицируешь в стриме
List.of к тому же итак Unmodifiable список отдает

2024-12-15 15:22 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +                .stream().toList();
Не оптимально

Во-первых, тебе надо только топ-10
Во-вторых отсортировано 
В-третьих, ты только что группировал по id, а затем второй раз выполняешь полный поиск по всем событиям

Сразу имя и всё что надо захватывай, или только для последних 10 поиск выполняй (лучше как-нибудь сразу)

2024-12-15 15:22 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +                .filter(s -> s.startsWith("#"))
Лучше поиском подстроки в строке
Или хотя бы регуляркой, это больно для производительности так всех обрабатывать

2024-12-15 15:22 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +                        || Objects.equals(action.getActionType(), ActionType.POST))
Для enum`ов исключение и можно через == сравнивать, потому что они в единственном экземпляре и неизменяемы

2024-12-15 15:22 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +                        Collectors.counting()));
Лучше в одной строке, параметры не надо отрывать, лучше отрывать вызовы

2024-12-15 15:37 UTC, AntonGraf commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +                .stream().toList();
а если имена одинаковые для разных id? Только из-за этого усложнял

2024-12-16 13:39 UTC, 20cognosce requested changes

2024-12-16 13:39 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +                .limit(10)
Кого ты отобрал? Нужна сортировка перед отбором
Ты случайных 10 юзеров взял

2024-12-16 13:39 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +                );
А зачем ты тут собираешь в мапу, если ты тут уже отобрал топ-пользователей и уже можешь только имена собрать

2024-12-16 13:39 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +        String reg = "#[a-zA-Z]*";
В константу

2024-12-16 13:39 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +                    return matcher.find() ? Stream.of(matcher.group()) : Stream.empty();
Что возвращает group? Если в одном тексте несколько хэштегов, ты их все забираешь?

2024-12-16 13:39 UTC, 20cognosce commented on src/test/java/school/faang/bjs_47153/UserActionAnalyzerTest.java
> +    private final List<UserAction> actions =  Arrays.asList(
Несколько хэштегов в одном событии не протестировано

2024-12-20 11:23 UTC, 20cognosce approved these changes

2024-12-20 11:23 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +                        .map(MatchResult::group))
Хорошо

2024-12-20 11:23 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +    private static final String HASHTAG_REG = "#[a-zA-Z]*";
Гуд

2024-12-20 11:23 UTC, 20cognosce commented on src/main/java/school/faang/bjs_47153/UserActionAnalyzer.java
> +                        entry -> entry.getValue() * 100.0 / actionsCount));
Ok

2024-12-20 11:23 UTC, merged