Alexeyrnd bjs2 45608 LordOfTheRings.
CorporationX/god_bless pull request #15336
Opened 2024-12-13 13:03 UTC by alobraztsov86

2024-12-13 20:41 UTC, mysosnovskaya requested changes

2024-12-13 20:41 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_1/task_lordofringsbjs2n45608/Character.java
> +    public String toString() {
А метод от lombok не подходит?

2024-12-13 20:41 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_1/task_lordofringsbjs2n45608/InventoryManager.java
> +    Logger inventaryLogger = LoggerFactory.getLogger("inventoryLogger");
Лучше использовать аннотацию от ломбока Slf4j

2024-12-13 20:41 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_1/task_lordofringsbjs2n45608/InventoryManager.java
> +        if (Stream.of(character, item, consumer).allMatch(Objects::nonNull)) {
Оригинально =) А можно перед каждым параметром повесить аннотацию от ломбока NonNull, тогда автоматически сгенерируется код, проверяющий параметры на null

2024-12-13 20:41 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_1/task_lordofringsbjs2n45608/InventoryManager.java
> +            // Можно замемнить на  character.getInventory().removeIf(predicate::test);
Если можно, то лучше и правда заменить, так будет намного короче и понятнее)

2024-12-13 20:41 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_1/task_lordofringsbjs2n45608/Item.java
> +    public Item(String name, int value) {
Конструктор от ломбока не подходит?

2024-12-13 20:41 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_1/task_lordofringsbjs2n45608/Item.java
> +    public String toString() {
Тоже - ломбочная аннотация не подходит?

2024-12-16 09:57 UTC, Nafanuil commented on src/main/java/school/faang/sprint_1/task_lordofringsbjs2n45608/InventoryManager.java
> +@Slf4j
нигде не используется

2024-12-16 09:59 UTC, merged