[BJS2-45884] Вспомним школу
CorporationX/god_bless pull request #15347
Opened 2024-12-13 14:38 UTC by EugeneT1024

2024-12-13 19:29 UTC, mysosnovskaya requested changes

2024-12-13 19:29 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_2/task_bjs245884/TriangleAreaCalculator.java
> +    Function<Double, Double> squareRoot = Math::sqrt;
Модификаторы доступа к полям нужны

2024-12-13 19:29 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_2/task_bjs245884/TriangleAreaCalculator.java
> +        ).apply(2.0);
Это нужно разбить на несколько переменных. По названию halfPerimeter, конечно, понятно, что в итоге получится, но вот эта кучка из шести apply совершенно не понятна. Можно выделить переменные bPlusC и другие

2024-12-13 19:29 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_2/task_bjs245884/TriangleAreaCalculator.java
> +        double perimeterMinusSideC = subtract.apply(halfPerimeter).apply(sideC);
Вот эти три переменные хорошие, понятные

2024-12-13 19:29 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_2/task_bjs245884/TriangleAreaCalculator.java
> +        );
Здесь тоже нужно разбить. Вот как у тебя сейчас по строчкам, только по переменным. Станет гораздо больше ясности)

2024-12-17 18:54 UTC, miked4king requested changes

2024-12-17 18:54 UTC, miked4king commented on src/main/java/school/faang/sprint_2/task_bjs245884/TriangleAreaCalculator.java
> +    public Double calculateTriangleArea(double sideA, double sideB, double sideC) throws IllegalArgumentException {
Исключение IllegalArgumentException является непроверяемым и не требуют явной обработки или объявления в throws.

2024-12-18 17:14 UTC, miked4king approved these changes

2024-12-18 17:14 UTC, merged