Solution to task BJS2-45692
CorporationX/god_bless pull request #15348
Opened 2024-12-13 14:38 UTC by askar0103

2024-12-13 20:46 UTC, mysosnovskaya requested changes

2024-12-13 20:46 UTC, mysosnovskaya commented on src/main/java/school/faang/task_45692/Calculator.java
> +public interface Calculator<T> {
Прям совсем любые типы можно в калькулятор подставлять? Я бы всё-таки ограничила тип числом

2024-12-13 20:46 UTC, mysosnovskaya commented on src/main/java/school/faang/task_45692/Main.java
> +        while (index < nums.size()) {
Это зачем? Чтобы отсечь первые null элементы? А остальные будут отсекаться на 34 строке? А точно ли нужен этот цикл тогда, если и второй while не сломается от того, что в списке есть null? Код переусложняет сильно, а пользы как будто бы никакой. Или я чего-то не поняла?

2024-12-13 20:46 UTC, mysosnovskaya commented on src/main/java/school/faang/task_45692/Main.java
> +        while (index < nums.size()) {
А почему не через for или даже stream? В стриме можно через filter убрать все null, а потом с помощью одной из терминальных операций все элементы соединить через calculate

2024-12-14 11:25 UTC, askar0103 commented on src/main/java/school/faang/task_45692/Main.java
> +        while (index < nums.size()) {
Я перемудрил

2024-12-14 17:09 UTC, mysosnovskaya approved these changes

2024-12-14 17:10 UTC, merged