Анализ активности пользователей
CorporationX/god_bless pull request #15379
Opened 2024-12-13 22:04 UTC by almigor1

2024-12-14 17:55 UTC, mysosnovskaya requested changes

2024-12-14 17:55 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task47500/service/UserActionAnalyzer.java
> +                .collect(Collectors.groupingBy(UserAction::getName, Collectors.counting()))
Все промежуточные хэш-мапы (здесь и ниже) лучше выделить в отдельные локальные переменные, так код станет понятнее

2024-12-14 17:55 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task47500/service/UserActionAnalyzer.java
> +    public static List<String> topActiveUsers(List<UserAction> userActions) {
Подумай над другим названием метода - нужно, чтобы оно начиналось с глагола

2024-12-14 17:55 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task47500/service/UserActionAnalyzer.java
> +                .limit(10)
Все значения для limit (здесь и ниже) лучше вынести в параметры метода, что там, где методы вызываются, можно было передать желаемое количество в результате: топ-3, топ-5, топ-10

2024-12-14 17:55 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task47500/model/UserAction.java
> +    private final String actionType;
В идеале actionType лучше сделать перечислением. Необязательно, но будет круто, если переделаешь)

2024-12-14 17:55 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task47500/service/UserActionAnalyzer.java
> +                .flatMap(a -> Stream.of(a.getContent().split("[,.!\\s]+")))
"[,.!\\s]+" - это нужно вынести в константы с понятным названием

2024-12-14 17:55 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task47500/service/UserActionAnalyzer.java
> +                .filter(w -> w.startsWith("#"))
"#" тоже можно в константы

2024-12-14 17:55 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task47500/service/UserActionAnalyzer.java
> +                        && a.getActionDate().isAfter(LocalDate.now().minusDays(365))))
Почему 365? Нужно же за последний месяц)

2024-12-14 17:55 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task47500/service/UserActionAnalyzer.java
> +        double userActionsQty = userActions.size();
Qty - Quantity

2024-12-14 17:55 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task47500/service/UserActionAnalyzer.java
> +        System.out.println(userActionsQty);
А эта строчка, кажется, осталась случайно) Она не нужна

2024-12-19 19:33 UTC, almigor1 commented on src/main/java/school/faang/sprint2/task47500/service/UserActionAnalyzer.java
> +                .collect(Collectors.groupingBy(UserAction::getName, Collectors.counting()))
не совсем понял, что имеется ввиду. как это можно сделать ?

2024-12-20 05:42 UTC, miked4king requested changes

2024-12-20 05:42 UTC, miked4king commented on src/main/java/school/faang/sprint2/task47500/service/UserActionAnalyzer.java
> +                .collect(Collectors.groupingBy(UserAction::getName, Collectors.counting()))
collect является терминальной операцией и ее результат принято сохранять в переменную.
это улучшает читаемость кода и позволит избежать повторных вычислений (если они потребуются).

конкретно для этого примера 
Map<String, Long> userActionsCount = userActions.stream()
                .collect(Collectors.groupingBy(UserAction::getName, Collectors.counting()));
                
и потом return userActionsCount.entrySet() и продолжаешь уже описанный тобой стрим        
поправь в остальных методах тоже

2024-12-20 05:42 UTC, miked4king commented on src/main/java/school/faang/sprint2/task47500/service/UserActionAnalyzer.java
> +                        && a.getActionDate().isAfter(LocalDate.now().minusDays(365))))
не поправил на последний месяц, можно воспользоваться методом .minusMonths()

2024-12-20 05:42 UTC, miked4king commented on src/main/java/school/faang/sprint2/task47500/service/UserActionAnalyzer.java
> +                .filter(a -> a.getActionType().equals(ActionType.COMMENT) && !a.getContent().isEmpty())
параметр в лямбда выражении лучше более информативно называть, чтобы другим разработчикам было более понятно чем мы оперируем. если проходим по коллекции userActions, можно сделать название userAction.

в других местах тоже поправь пж

2024-12-20 17:26 UTC, almigor1 commented on src/main/java/school/faang/sprint2/task47500/service/UserActionAnalyzer.java
> +                .collect(Collectors.groupingBy(UserAction::getName, Collectors.counting()))
а, понял

2024-12-20 18:36 UTC, miked4king requested changes
сейчас по решению все хорошо, осталось только убрать лишние отступы

2024-12-20 18:36 UTC, miked4king commented on src/main/java/school/faang/sprint2/task47500/service/UserActionAnalyzer.java
> +
лишние отступы появились в начале каждого метода. 

когда у нас сигнатура метода умещается в одну строку (как сейчас у тебя) то мы не ставим отступ в начале метода. отступы принято делать только в случае когда сигнатура не помещается в одну строку, например 
 ```
public static List<List<Integer>> sumLists(List<Integer> numbers,
                                               int target,
                                               List<Integer> anotherNumbersForExample) {
        
        // some logic

        return null;
    }

2024-12-20 19:30 UTC, almigor1 commented on src/main/java/school/faang/sprint2/task47500/service/UserActionAnalyzer.java
> +
не понял про отступы перед методом.
Вроде такая структура
Class...
    public static List get.... {
    }

    public static void put .... {
    }

все это форматирование строится автоматически через Ctrl + Alt + L 

или что то после автоформатирования руками все же надо править?

2024-12-20 19:45 UTC, miked4king approved these changes

2024-12-20 19:46 UTC, merged