bormoley1983-BJS2-46209
CorporationX/god_bless pull request #15394
Opened 2024-12-14 06:13 UTC by bormoley1983

2024-12-15 15:40 UTC, 20cognosce requested changes
По организации кода вопросики, по лямбдам и логике - всё нормально

2024-12-15 15:40 UTC, 20cognosce commented on src/main/java/school/faang/Main.java
> -}
Один раз удалить и не нести в последующих ПРах
Сделай rebase после мерджа с удалением

2024-12-15 15:40 UTC, 20cognosce commented on src/main/java/school/faang/bjs246209/Droid.java
> +    };
Почему логика лежит внутри дроида?
Сделай Сервис шифратора-дешифратора и пусть дроид хотя бы имеет на них зависимость и вызывает ИХ методы

2024-12-15 15:40 UTC, 20cognosce commented on src/main/java/school/faang/bjs246209/Droid.java
> +        };
Почему тут внутри метода, а там - в поле

2024-12-15 15:40 UTC, 20cognosce commented on src/main/java/school/faang/bjs246209/Droid.java
> +    private String cryptWithAlgo(String message, int algo, boolean isEncrypt) {
булевы параметры для параметризации - зло

Лучше передавай функцию сдвига
принимает char и отдает либо char + сдвиг, либо char - сдвиг

2024-12-15 15:40 UTC, 20cognosce commented on src/main/java/school/faang/bjs246209/Droid.java
> +        }
forEach или стримы, не надо for, убрать

2024-12-15 15:40 UTC, 20cognosce commented on src/main/java/school/faang/bjs246209/Droid.java
> +        }
А почему сразу нельзя было это сделать? Зачем два этапа

2024-12-15 15:40 UTC, 20cognosce commented on src/main/java/school/faang/bjs246209/Droid.java
> +            int chr = isEncrypt ? (int) c - algo : (int) c + algo;
Тут кстати можешь вылезти за границы алфавита, "Z" должна сдвигаться в "a"
Если есть время - обработай такой кейс, если нет - так тоже приму

2024-12-16 06:56 UTC, bormoley1983 commented on src/main/java/school/faang/bjs246209/Droid.java
> +        };
Я пытаюсь научиться, использую разные подходы чтобы лучше разобраться в теме

2024-12-16 17:58 UTC, bormoley1983 commented on src/main/java/school/faang/bjs246209/Droid.java
> +    private String cryptWithAlgo(String message, int algo, boolean isEncrypt) {
Я не понял ни почему булевы параметры это зло ни идею сдвига

2024-12-16 17:59 UTC, bormoley1983 commented on src/main/java/school/faang/bjs246209/Droid.java
> +    private String cryptWithAlgo(String message, int algo, boolean isEncrypt) {
переписываю алгоритм под стрим

2024-12-16 21:19 UTC, 20cognosce requested changes

2024-12-16 21:19 UTC, 20cognosce commented on src/main/java/school/faang/bjs246209/EncryptionService.java
> +    private String cryptWithAlgo(String message, int algo, boolean isEncrypt) {
https://softwareengineering.stackexchange.com/questions/147977/is-it-wrong-to-use-a-boolean-parameter-to-determine-behavior

https://martinfowler.com/bliki/FlagArgument.html

2024-12-16 21:19 UTC, 20cognosce commented on src/main/java/school/faang/bjs246209/EncryptionService.java
> +        //                .map(c -> isEncrypt ? c - algo : c + algo)
Сделай, чтобы DroidMessageEncryptor и Decryptor наследовались от Function

И в каждом из них выполняй сам сдвиг, кстати сдвиг лучше назвать delta, а не algo

Соответственно этот метод принимает не boolean, а функцию, и в методе map ты её будешь вызывать

В методе send ты в метод cryptWithAlgo передаешь String message и DroidMessageEncryptor , в методе receiveMessage - String message и DroidMessageDecryptor

2024-12-16 21:19 UTC, 20cognosce commented on src/main/java/school/faang/bjs246209/DroidMessageDecrypt.java
> +public interface DroidMessageDecrypt<U, V, R> {
DroidMessageDecryptor

2024-12-16 21:19 UTC, 20cognosce commented on src/main/java/school/faang/bjs246209/EncryptionService.java
> +    private final DroidMessageDecrypt<String, Integer, String> decrypted = (msg, key) -> {
decryptor

2024-12-16 21:19 UTC, 20cognosce commented on src/main/java/school/faang/bjs246209/EncryptionService.java
> +    private final DroidMessageDecrypt<String, Integer, String> decrypted = (msg, key) -> {
Лучше оба внутри методов объявлять на мой взгляд

2024-12-23 07:30 UTC, merged