task analyze actions impl
CorporationX/god_bless pull request #15406
Opened 2024-12-14 09:46 UTC by bortsovamaria

2024-12-14 17:46 UTC, mysosnovskaya requested changes

2024-12-14 17:46 UTC, mysosnovskaya commented on src/main/java/school/faang/task_47144/UserActionAnalyzer.java
> +                .map(s -> s.replaceAll("^\\W+|\\W+$", "")) //убрать все спец. символы
Чтобы не подписывать комментарий, можно вынести эту строку в константы и назвать понятным образом

2024-12-14 17:46 UTC, mysosnovskaya commented on src/main/java/school/faang/task_47144/UserActionAnalyzer.java
> +                .filter(s -> s.contains("#"))
startsWith? И хэштэг лучше тоже в константы

2024-12-14 17:46 UTC, mysosnovskaya commented on src/main/java/school/faang/task_47144/UserActionAnalyzer.java
> +        Map<String, List<UserAction>> actionsByName = actions.stream()
Тебе точно эта мапа нужна? Как я вижу ниже, ты потом опять приходишь к списку всех действий (на 40 строке), тогда проще сразу изначальным actions воспользоваться

2024-12-14 17:46 UTC, mysosnovskaya commented on src/main/java/school/faang/task_47144/UserActionAnalyzer.java
> +                .limit(3)
3 лучше вынести в параметры метода, чтобы там, откуда мы вызываем метод topCommentersLastMonth, можно было указывать, топ-сколько мы хотим получить (топ-3, топ-5, топ-10...). Выше аналогично

2024-12-14 17:46 UTC, mysosnovskaya commented on src/main/java/school/faang/task_47144/UserAction.java
> +    private final String actionType;
В идеале actionType должен быть перечислением =) Необязательно менять, но очень желательно

2024-12-14 20:00 UTC, bortsovamaria commented on src/main/java/school/faang/task_47144/UserAction.java
> +    private final String actionType;
Попробовала :)

2024-12-14 20:04 UTC, bortsovamaria commented on src/main/java/school/faang/task_47144/UserAction.java
> +public class UserAction {
заменила на record

2024-12-15 17:42 UTC, mysosnovskaya requested changes

2024-12-15 17:42 UTC, mysosnovskaya commented on src/main/java/school/faang/task_47144/UserActionAnalyzer.java
> +    private static final int TOP_5 = 5;
Лучше не константы, а параметры метода. Т.е. прям в методе, например, topPopularHashtags вместе со списком actions передаешь ещё и int topN - количество, сколько нужно вернуть. Так методы станут гибче и их можно будет переиспользовать с разным значением topN

2024-12-17 19:58 UTC, miked4king approved these changes

2024-12-17 19:58 UTC, merged