Solution to task BJS2-45891
CorporationX/god_bless pull request #15426
Opened 2024-12-14 13:04 UTC by askar0103

2024-12-14 17:15 UTC, mysosnovskaya requested changes

2024-12-14 17:15 UTC, mysosnovskaya commented on src/main/java/school/faang/task_45891/TriangleAreaCalculator.java
> +    private static final Function<Double, Function<Double, Double>> add = (x) -> (y) -> x + y;
Если это константы, то называть их нужно как ADD, MULTIPLY и так далее (заглавными буквами и в SNAKE_CASE)

2024-12-14 17:15 UTC, mysosnovskaya commented on src/main/java/school/faang/task_45891/TriangleAreaCalculator.java
> +        double perimeter = add.apply(add.apply(a).apply(b)).apply(c);
Давай сумму a и b вынесем в локальную переменную: во-первых, она у тебя сейчас вычисляется дважды (здесь и на 14 строке) и это можно будет избежать, а во-вторых, тогда вот эта строчка станет понятнее, а то когда незнакомый с кодом и заданием человек увидит четыре подряд apply, то он точно далеко не сразу разберется, что происходит =) Хотя имя локальной переменной говорящее, всё равно небольшим действием можем внести ясность в код - лучше это сделать)

2024-12-14 17:15 UTC, mysosnovskaya commented on src/main/java/school/faang/task_45891/TriangleAreaCalculator.java
> +                Stream.of(
Оригинальное решение, круто 👍  Только давай параметр для apply вынесем в отдельную переменную, чтобы было легче разобраться с тем, что возводится в квадрат)

2024-12-14 17:15 UTC, mysosnovskaya commented on src/main/java/school/faang/task_45891/TriangleAreaCalculator.java
> +                ).reduce((x1, x2) -> multiply.apply(x1).apply(x2)).orElseThrow()
В orElseThrow лучше прописать исключение и понятное сообщение об ошибке

2024-12-15 11:27 UTC, askar0103 commented on src/main/java/school/faang/task_45891/TriangleAreaCalculator.java
> +                Stream.of(
Спасибо😊 Но тут на самом деле извлекается квадратный корень, а не возводится в квадрат

2024-12-16 10:38 UTC, merged