task secrets droid impl
CorporationX/god_bless pull request #15429
Opened 2024-12-14 13:33 UTC by bortsovamaria

2024-12-14 17:38 UTC, mysosnovskaya requested changes

2024-12-14 17:38 UTC, mysosnovskaya commented on src/main/java/school/faang/task_46528/DroidMessageEncryptor.java
> +    String encrypt(String message, int keyEncrypt);
keyEncrypt предлагаю переименовать в encriptionKey или просто key

2024-12-14 17:38 UTC, mysosnovskaya commented on src/main/java/school/faang/task_46528/Droid.java
> +    private String decryptMessage(String message, int decryptKey) {
Давай заметим, что код этого метода очень сильно похож на код метода encryptMessage? Нужно избавиться от дублирования)

2024-12-14 17:38 UTC, mysosnovskaya commented on src/main/java/school/faang/task_46528/Droid.java
> +                    builder.append((char) ((ch - base + encryptKey) % 26 + base));
26 можно вынести в константы

2024-12-14 19:45 UTC, bortsovamaria commented on src/main/java/school/faang/task_46528/Droid.java
> +    private String decryptMessage(String message, int decryptKey) {
Вынесла метод и добавила BiFunction для применения шифра

2024-12-15 17:52 UTC, mysosnovskaya requested changes

2024-12-15 17:52 UTC, mysosnovskaya commented on src/main/java/school/faang/task_46528/Droid.java
> +                (ch, base) -> (char) ((ch - base - key + COUNT_LETTERS_ALPHABET) % COUNT_LETTERS_ALPHABET + base));
Круто потренировалась с BiFunction, но можно ещё проще) Эти функции по-прежнему очень похожи, у них отличие буквально в одном маленьком выражении. Вот его и нужно вынести)

2024-12-17 12:35 UTC, bortsovamaria commented on src/main/java/school/faang/task_46528/Droid.java
> +                (ch, base) -> (char) ((ch - base - key + COUNT_LETTERS_ALPHABET) % COUNT_LETTERS_ALPHABET + base));
Попробовала, но не уверена, что нормально вышло :)

2024-12-17 19:20 UTC, miked4king approved these changes

2024-12-17 19:20 UTC, merged