Предположим что лямбды я понял
CorporationX/god_bless pull request #15434
Opened 2024-12-14 14:21 UTC by Rexsell

2024-12-14 14:23 UTC, Rexsell commented
Ладно, наврал :). Я так и не понял как из интерфейса возвращается строка, в смысле мы не указывали нигде и никак логику работы лямбды, но как-то работает

2024-12-14 18:31 UTC, Kayfral requested changes

2024-12-14 18:31 UTC, Kayfral commented on src/main/java/school/faang/sprint2/task_45724/SpellCaster.java
> +    }
Лучше не забывать про проверки на null, так ты точно сделаешь безопасное решение, которое не будет ловить NullPointerException. Давай сделаешь проверку входных параметров

2024-12-14 18:43 UTC, Kayfral commented
> Ладно, наврал :). Я так и не понял как из интерфейса возвращается строка, в смысле мы не указывали нигде и никак логику работы лямбды, но как-то работает

Попытаюсь объяснить логику. Смотри, ты вызываешь метод cast с двумя параметрами. Первый параметр содержит в себе название заклинания, второй лямбду. Лямбда принимает 1 входной параметр - это название заклинания, чтобы подставить его в конец строки. В методе cast ты получаешь result по средствам того, что через функциональный интерфейс происходит вызов лямбды, которая в свою очередь принимает название заклинание и возвращает строку с установленным заклинанием

2024-12-14 19:03 UTC, Rexsell commented
> > Ладно, наврал :). Я так и не понял как из интерфейса возвращается строка, в смысле мы не указывали нигде и никак логику работы лямбды, но как-то работает
> 
> Попытаюсь объяснить логику. Смотри, ты вызываешь метод cast с двумя параметрами. Первый параметр содержит в себе название заклинания, второй лямбду. Лямбда принимает 1 входной параметр - это название заклинания, чтобы подставить его в конец строки. В методе cast ты получаешь result по средствам того, что через функциональный интерфейс происходит вызов лямбды, которая в свою очередь принимает название заклинание и возвращает строку с установленным заклинанием

Вот все до return я понимаю. У меня больше вопрос был про возврат значения. просто в теле лямбды мы ведь не указываем явно что и как и в каком виде возвращать

2024-12-15 08:51 UTC, Kayfral commented
> > > Ладно, наврал :). Я так и не понял как из интерфейса возвращается строка, в смысле мы не указывали нигде и никак логику работы лямбды, но как-то работает
> > 
> > 
> > Попытаюсь объяснить логику. Смотри, ты вызываешь метод cast с двумя параметрами. Первый параметр содержит в себе название заклинания, второй лямбду. Лямбда принимает 1 входной параметр - это название заклинания, чтобы подставить его в конец строки. В методе cast ты получаешь result по средствам того, что через функциональный интерфейс происходит вызов лямбды, которая в свою очередь принимает название заклинание и возвращает строку с установленным заклинанием
> 
> Вот все до return я понимаю. У меня больше вопрос был про возврат значения. просто в теле лямбды мы ведь не указываем явно что и как и в каком виде возвращать

Почему не указываем? Давай посмотрим на одну из твоих лямбд: (spell) -> "The door is unlocked by " + spell. Обрати внимание на всю информацию после -> Это те значение, которые вернет лямбда. Если бы ты условно после -> сравнивал два элемента (Пример str1 == str2), то у тебя лямбда возвращала бы логическое значение true или false

2024-12-15 08:51 UTC, Kayfral approved these changes
Отлично!

2024-12-15 08:51 UTC, merged