Уведомления работают, кайф от лямбд получил
CorporationX/god_bless pull request #15438
Opened 2024-12-14 15:00 UTC by Rexsell

2024-12-14 18:54 UTC, Kayfral requested changes

2024-12-14 18:54 UTC, Kayfral commented on src/main/java/school/faang/sprint2/task_46856/Consumer.java
> +}
Классно справился с использованием @FunctionalInterface для Consumer! Это действительно делает код гибче и легче расширяемым

2024-12-14 18:54 UTC, Kayfral commented on src/main/java/school/faang/sprint2/task_46856/Main.java
> +        );
Заметил, что ты используешь строковые литералы ('email', 'sms', 'push') в нескольких местах. Как вариант, можно было бы вынести их в константы класса - это защитит от опечаток и упростит поддержку кода.

Или, если хочешь поднять решение на новый уровень, можно использовать enum NotificationTyp

2024-12-14 18:54 UTC, Kayfral commented on src/main/java/school/faang/sprint2/task_46856/NotificationManager.java
> +    }
В двух методах стоит сделать валидацию входных параметров, чтобы при получении некоретных данных ты не ловил NullPointerException

2024-12-14 18:54 UTC, Kayfral commented on src/main/java/school/faang/sprint2/task_46856/NotificationManager.java
> +    }
А для мапы это позволит хранить только корректные данные

2024-12-14 19:04 UTC, Rexsell commented on src/main/java/school/faang/sprint2/task_46856/Main.java
> +        );
Ну с этим я сильно не замарачивался, то есть я взял тело программы из описания задачи :)

2024-12-15 08:55 UTC, Kayfral approved these changes
Отлично!

2024-12-15 08:55 UTC, merged