bjs2-48049
CorporationX/god_bless pull request #15443
Opened 2024-12-14 15:37 UTC by etibarliparvin

* Вы работаете в Microsoft! is finished

2024-12-15 09:29 UTC, Kayfral requested changes

2024-12-15 09:29 UTC, Kayfral commented on src/main/java/school/faang/bjs248049/MailSender.java
> +    }
Такая реализация правильная и решает поставленную задачу, но к сожалению она может существовать только в контексте этой задачи. Давай немного модернизируем код. 

1) Сделай константу, где будет храниться общее количество писем для отправки, чтобы было удобно изменять количество писем и не завязываться только на 1000

2) Так же рекомендую сделать константу, которая будет хранить количество-число потоков, которые нужно будет выделить для обработки всех писем. Данная реализация позволит тебе менять объем сообщений, который обрабатывает один поток за одну итерацию

3) После ты можешь через цикл передать каждому потоку количество сообщений на обработку 

4) Не забудь убедиться, что у тебя точно отправляются все письма

2024-12-15 09:29 UTC, Kayfral commented on src/main/java/school/faang/bjs248049/SenderRunnable.java
> +    }
Тут я вижу, что ты пытался сделать задержку Thread.sleep(5000);, тем самым эмитирую нагрузку, отлично! Но, лучше будет добавить ещё задержку в тело цикла for, например Thread.sleep(10);, это тебе позволит создать эмитацию отправки сообщения

2024-12-18 19:05 UTC, Kayfral commented
Обрати внимание, что ты не поправил комментарии)

2024-12-21 09:01 UTC, etibarliparvin commented on src/main/java/school/faang/bjs248049/SenderRunnable.java
> +    }
Wow what a nice comment

2024-12-21 09:02 UTC, etibarliparvin commented on src/main/java/school/faang/bjs248049/MailSender.java
> +    }
Perfect. That again proves i rush a bit

2024-12-21 16:33 UTC, Kayfral requested changes

2024-12-21 16:33 UTC, Kayfral commented on src/main/java/school/faang/bjs248049/MailSender.java
> +    }
Отличное решение! К реализации почти нет вопросов. Но, что будет если у тебя попадется такая ситуация:

Пример: сообщений которых нужно разобрать 103, а потоков всего 5. В таком случае у тебя останется 3 сообщения, которые не попадут в выборку. Этот момент можно подправить и все будет хорошо

2024-12-22 07:39 UTC, etibarliparvin commented on src/main/java/school/faang/bjs248049/MailSender.java
> +    }
great notice

2024-12-22 08:43 UTC, Kayfral approved these changes

2024-12-22 08:43 UTC, merged