BJS2-45627 [Lord of the Rings]
CorporationX/god_bless pull request #15467
Opened 2024-12-14 18:38 UTC by Iv-an-s

2024-12-15 18:15 UTC, mysosnovskaya requested changes

2024-12-15 18:15 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/sprinttwo/task_43524/InventoryManager.java
> +        boolean isItemRemoved = false;
Посмотри на использование метода removeIf у списков

2024-12-15 18:15 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/sprinttwo/task_43524/InventoryManager.java
> +                .forEach(action);
Оригинальное решение! Я раньше встречала только через `Function<Item, Item>`, но твоё мне тоже нравится

2024-12-15 20:16 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprinttwo/task_43524/InventoryManager.java
> +        boolean isItemRemoved = false;
Поправил

2024-12-15 20:16 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprinttwo/task_43524/InventoryManager.java
> +                .forEach(action);
Хорошо, если нравится :) Переделывать не стал :)

2024-12-16 19:20 UTC, miked4king approved these changes

2024-12-16 19:20 UTC, merged