BJS-46445 [Фильтры Instagram]
CorporationX/god_bless pull request #15472
Opened 2024-12-14 18:58 UTC by Iv-an-s

2024-12-15 17:50 UTC, mysosnovskaya requested changes

2024-12-15 17:50 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/sprinttwo/task_43532/FilterProcessor.java
> +            Function<Image, Image> secondFilter) {
Лучше назвать filter1 и filter2. В java чаще используют числа, чем first, second

2024-12-15 17:50 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/sprinttwo/task_43532/FilterProcessor.java
> +        return image -> firstFilter.apply(secondFilter.apply(image));
Давай попробуем через метод andThen сделать (у Function такой есть)

2024-12-15 21:09 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprinttwo/task_43532/FilterProcessor.java
> +            Function<Image, Image> secondFilter) {
Поправил

2024-12-15 21:10 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprinttwo/task_43532/FilterProcessor.java
> +        return image -> firstFilter.apply(secondFilter.apply(image));
Спасибо! Поправил

2024-12-16 19:13 UTC, miked4king approved these changes

2024-12-16 19:13 UTC, merged