BJS2-46240 [Обрабатываем ошибки красиво]
CorporationX/god_bless pull request #15483
Opened 2024-12-14 20:52 UTC by Iv-an-s

2024-12-15 18:00 UTC, mysosnovskaya requested changes

2024-12-15 18:00 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/sprinttwo/task_46240/Main.java
> +            throw new Exception("Сервис недоступен");
Давай сделаем здесь RuntimeException, уберем throws Exception из сигнатуры метода и тогда в main не нужно будет писать лишний try-catch

2024-12-15 18:00 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/sprinttwo/task_46240/Main.java
> +        System.out.println(result);
Давай ещё добавим тестирование для успешного случая

2024-12-15 21:49 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprinttwo/task_46240/Main.java
> +            throw new Exception("Сервис недоступен");
Поправил

2024-12-15 21:49 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprinttwo/task_46240/Main.java
> +        System.out.println(result);
Добавил

2024-12-17 18:08 UTC, miked4king approved these changes

2024-12-17 18:08 UTC, merged