instagram filter task
CorporationX/god_bless pull request #15481
Opened 2024-12-14 19:42 UTC by ZhannaD

2024-12-15 12:12 UTC, AMIRZAVEL approved these changes

2024-12-15 17:49 UTC, mysosnovskaya requested changes

2024-12-15 17:49 UTC, mysosnovskaya commented on src/main/java/school/faang/instagram/FilterProcessor.java
> +        return image -> filter2.apply(filter1.apply(image));
Можно использовать метод andThen для фильтра. Попробуй, так код будет легче

2024-12-15 18:16 UTC, mysosnovskaya approved these changes

2024-12-15 18:16 UTC, merged

2024-12-16 22:07 UTC, AMIRZAVEL approved these changes
Meta Verification

2024-12-16 23:39 UTC, AMIRZAVEL commented on src/main/java/school/faang/instagram/FilterProcessor.java
> +        return image -> filter2.apply(filter1.apply(image));
I'm still new and I will need your help 
Thank you for your guidance.

2025-01-27 05:48 UTC, AMIRZAVEL approved these changes

2025-01-27 05:48 UTC, AMIRZAVEL approved these changes

2025-01-29 18:07 UTC, AMIRZAVEL approved these changes

2025-01-29 18:08 UTC, AMIRZAVEL commented
>

2025-02-09 13:50 UTC, AMIRZAVEL approved these changes

2025-04-06 05:19 UTC, AMIRZAVEL approved these changes

2025-04-06 05:19 UTC, AMIRZAVEL approved these changes

2025-04-06 05:21 UTC, AMIRZAVEL approved these changes