BJS2-47301
CorporationX/god_bless pull request #15499
Opened 2024-12-15 06:18 UTC by DMCHMB

BJS2-47301
Рекомендательная система
main output:
![image](https://github.com/user-attachments/assets/ad4d6793-ec7d-49a9-ad8f-aa9292479ce1)

2024-12-17 20:18 UTC, 20cognosce requested changes
В целом нормально

2024-12-17 20:18 UTC, 20cognosce commented on src/main/java/school/faang/sprint_2/task_bjs247301/DataParser.java
> +    private final String dirPath = "src/main/resources/sprint_2/task_bjs247301/";
Относительно папки ресурсов хранить путь

2024-12-17 20:18 UTC, 20cognosce commented on src/main/java/school/faang/sprint_2/task_bjs247301/DataParser.java
> +        File file = new File(dirPath + fileName);
Другим инструментом выполнять чтение

2024-12-17 20:18 UTC, 20cognosce commented on src/main/java/school/faang/sprint_2/task_bjs247301/Main.java
> +    private static final String ORDERS_FILENAME = "product_orders.json";
Почему самих файлов нет в коммите?

2024-12-17 20:18 UTC, 20cognosce commented on src/main/java/school/faang/sprint_2/task_bjs247301/RecommendationService.java
> +    private Stream<Product> filterProductsByTags(Stream<Product> productStream, List<String> interests) {
Лучше стримы не сохранять и не передавать, это не структура данных

2024-12-17 20:18 UTC, 20cognosce commented on src/main/java/school/faang/sprint_2/task_bjs247301/RecommendationService.java
> +    }
Не расщеплять методы на атомы, ну зачем метод на 2 строчки

2024-12-17 20:18 UTC, 20cognosce commented on src/main/java/school/faang/sprint_2/task_bjs247301/RecommendationService.java
> +                .anyMatch(order -> userIds.contains(order.userId()) && order.productId() == productId);
Нельзя через == сравнивать id

2024-12-17 20:18 UTC, 20cognosce commented on src/main/java/school/faang/sprint_2/task_bjs247301/RecommendationService.java
> +                .findFirst()
Нельзя применять findFirst при точном поиске, ты должен убедиться, что filter возвращает ровно 1 элемент, или кинуть ошибку

2024-12-17 20:18 UTC, 20cognosce commented on src/main/java/school/faang/sprint_2/task_bjs247301/RecommendationService.java
> +                limit)
Что с форматированием

2024-12-17 20:18 UTC, 20cognosce commented on src/main/java/school/faang/sprint_2/task_bjs247301/RecommendationService.java
> +                .stream()
Не слепливай, лучше отделить и в переменную сохранить

2024-12-17 23:12 UTC, DMCHMB commented
main after fix:
![image](https://github.com/user-attachments/assets/56ac34f6-dfd8-481b-89a9-2b7503090724)

2024-12-18 15:10 UTC, 20cognosce approved these changes

2024-12-18 15:10 UTC, 20cognosce commented on src/main/java/school/faang/sprint_2/task_bjs247301/RecommendationService.java
> +                        }
Кривоватенько
Лучше использовать reduce

2024-12-18 15:10 UTC, 20cognosce commented on src/main/java/school/faang/sprint_2/task_bjs247301/DataParser.java
> +        try (InputStream inputStream = DataParser.class.getClassLoader().getResourceAsStream(filePath)) {
Пойдёт

2024-12-18 15:10 UTC, merged