Обработали ошибки красиво
CorporationX/god_bless pull request #15540
Opened 2024-12-15 13:53 UTC by Rexsell

2024-12-15 18:01 UTC, mysosnovskaya requested changes

2024-12-15 18:01 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task_6/RemoteService.java
> +    public static String call(String param) throws RuntimeException {
throws RuntimeException не нужно писать, это непроверяемое исключение и в теории любой метод может сгенерировать RuntimeException (например, NullPointerException)

2024-12-15 18:01 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task_6/Main.java
> +        System.out.println(result);
Давай ещё добавим пример для успешного вызова

2024-12-15 18:21 UTC, Rexsell commented on src/main/java/school/faang/sprint2/task_6/RemoteService.java
> +    public static String call(String param) throws RuntimeException {
Воровал из вашего описания задачи!

2024-12-17 18:47 UTC, miked4king approved these changes

2024-12-17 18:48 UTC, merged