Artemon bjs2 48223 Mice are very nice!
CorporationX/god_bless pull request #15552
Opened 2024-12-15 15:21 UTC by Kuruzo

2024-12-17 17:20 UTC, 20cognosce requested changes

2024-12-17 17:20 UTC, 20cognosce commented on src/main/java/school/faang/bjs248223/model/House.java
> +            Optional<Room> anyRoom = rooms.stream().filter(room -> !room.getFoods().isEmpty()).findAny();
Почему в одну строчку слепил

2024-12-17 17:20 UTC, 20cognosce commented on src/main/java/school/faang/bjs248223/model/House.java
> +    }
addRooms
this не нужен

2024-12-17 17:20 UTC, 20cognosce commented on src/main/java/school/faang/bjs248223/model/House.java
> +        return this.collectedFood.toString();
this не нужен

2024-12-17 17:20 UTC, 20cognosce commented on src/main/java/school/faang/bjs248223/programm/Main.java
> +        executorService.scheduleAtFixedRate(house::collectFood, 0, 30, TimeUnit.SECONDS);
Где вывод когда вся еда во всех комнатах собрана?
30 секунд долго, ставь 5-10

2024-12-17 17:20 UTC, 20cognosce commented on src/main/java/school/faang/bjs248223/programm/Main.java
> +        executorService.scheduleAtFixedRate(house::collectFood, 0, 30, TimeUnit.SECONDS);
И скриншот с выводом пришли

2024-12-17 17:20 UTC, 20cognosce commented on src/main/java/school/faang/bjs248223/model/House.java
> +    }
Если смотреть на этот код в многопоточном контексте, конечно это лажа

1. Всё что тебя спасает от багов - это временная задержка между потоками

2. На выборе комнат должна быть блокировка, чтобы два потока не могли захватить одну и ту же комнату. К комнате добавь атомик флаг, что она уже очищается, и метод выбора двух комнат должен возвращать СРАЗУ две комнаты. Про блокировку хорошо подумай и пробуй уменьшать интервал, даже при нулевом интервале все должно работать исправно.

3. У тебя несколько потоков читают из списка комнат и кладут в общий сет с едой, что надо сделать?

Добавь больше потоков, больше комнат, и меньше интервал - всё развалится, убедись сам

2024-12-25 14:02 UTC, 20cognosce approved these changes

2024-12-25 14:02 UTC, 20cognosce commented on src/main/java/school/faang/bjs248223/service/RoomService.java
> +    public synchronized Room[] get2RandomRooms() {
synchronized корректно

2024-12-25 14:02 UTC, 20cognosce commented on src/main/java/school/faang/bjs248223/service/RoomService.java
> +        Room[] randomRooms = new Room[2];
Почему массив

2024-12-25 14:02 UTC, 20cognosce commented on src/main/java/school/faang/bjs248223/service/RoomService.java
> +        }
Так а где рандомность, если это просто по порядку добавления
И зачем тебе итератор, почему очередь не подошла вместо списка

2024-12-25 14:02 UTC, 20cognosce commented on src/main/java/school/faang/bjs248223/model/House.java
> +    private final Set<Food> collectedFood = Collections.synchronizedSet(new HashSet<>());
Окей

2024-12-25 14:02 UTC, 20cognosce commented on src/main/java/school/faang/bjs248223/model/House.java
> +        for (Room selectedRoom : selectedRooms) {
Зачем массив-то используешь? Не понимаю
По многопоточке корректно, принято

2024-12-25 14:31 UTC, Kuruzo commented on src/main/java/school/faang/bjs248223/service/RoomService.java
> +        }
Не подумал про очередь. Её и возьму

2024-12-25 14:32 UTC, Kuruzo commented on src/main/java/school/faang/bjs248223/model/House.java
> +        for (Room selectedRoom : selectedRooms) {
Масив создаётся быстрее чем список, и если я знаю сколько будет элементов то исльзовать масив выгоднее

2024-12-25 14:32 UTC, merged