Шифруемся от имперцев
CorporationX/god_bless pull request #15558
Opened 2024-12-15 16:36 UTC by Rexsell

Выглядит будто работает :)

2024-12-15 17:57 UTC, mysosnovskaya requested changes

2024-12-15 17:57 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task_7/Droid.java
> +    final int lettersOffset = 26;
Если это константа, то она должна быть static и называться в SNAKE_CASE заглавными буквами. Ну и модификатор доступа тоже нужен)

2024-12-15 17:57 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task_7/Droid.java
> +        return encryptor.encrypt(msg, key);  // Шифруем сообщение
Комментарий не нужен, из названия метода уже понятно, что он делает

2024-12-15 17:57 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task_7/Droid.java
> +                    encryptedMessage.append((char) ((ch - base + encryptionKey) % 26 + base));
У тебя есть lettersOffset (будущая константа), вот её и нужно здесь использовать вместо 26

2024-12-15 17:57 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task_7/Droid.java
> +    public String decryptMessage(String msg, int key) {
Код этого метода очень похож на код метода encryptMessage. Нужно избавиться от дублирования

2024-12-15 18:02 UTC, Rexsell commented on src/main/java/school/faang/sprint2/task_7/Droid.java
> +    final int lettersOffset = 26;
А вот не получится. Чекстайл ругается на SNAKE_CASE, у меня с ним вообще война :)

2024-12-15 18:26 UTC, mysosnovskaya requested changes

2024-12-15 18:26 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task_7/Droid.java
> +    private static int LETTERS_OFFSET = 26;
`private static final int LETTERS_OFFSET = 26;` - вот так выглядит корректное объявление константы) Чекстайл не будет воспринимать поле как константу, если она не static

2024-12-15 18:26 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint2/task_7/Droid.java
> +                                    + (isEncrypting ? encryptionKey : -encryptionKey)
Можно ещё проще, без этого флага. Ты можешь сразу передать в метод вместо key либо encryptionKey, либо -encryptionKey, и флаг не понадобится

2024-12-17 19:08 UTC, miked4king requested changes

2024-12-17 19:08 UTC, miked4king commented on src/main/java/school/faang/sprint2/task_7/Droid.java
> +    private static int LETTERS_OFFSET = 26;
в upper case объявляются только константы чтобы переменная стала неизменяемой требуется добавить ключевое слово final

2024-12-17 19:08 UTC, miked4king commented on src/main/java/school/faang/sprint2/task_7/Droid.java
> +    }
Думаю что Маша имела в виду то, что данные методы избыточны, так как вызывают один и тот же метод, можно отказаться от них и вызывать сразу  encryptingHandler

2024-12-17 19:08 UTC, miked4king commented on src/main/java/school/faang/sprint2/task_7/Droid.java
> +@Setter
вроде не используется

2024-12-17 19:50 UTC, Rexsell commented on src/main/java/school/faang/sprint2/task_7/Droid.java
> +@Setter
Я не уверен, в смысле я всегда их ставил чтобы методы set использовались в конструкторе без прямого доступа к полям

2024-12-17 19:52 UTC, Rexsell commented on src/main/java/school/faang/sprint2/task_7/Droid.java
> +    private static int LETTERS_OFFSET = 26;
А вот тут уже ты попался :) чекстайл не пропускает константы final в UPPER_CASE. А в статике пропускает. И Маша мне об этом тоже писала

2024-12-17 19:56 UTC, Rexsell commented on src/main/java/school/faang/sprint2/task_7/Droid.java
> +    }
Ну, я немного не соглашусь. С точки зрения использования пакета сторонним программистом, ему проще понимать что есть encrypt и decrypt. Не один метод который может все и с ним нужно по-особому работать, а два, просто обертки для понимания. Также я не соглашусь с тем что можно использовать два аргумента, так как наверное внутри пакета было бы логичнее использовать три переменные. Сообщение, ключ и булеан обозначающий шифрование или расшифрование. Да, теоретически можно обойтись и двумя, но параметр ключ - это то на сколько были сдвинуты символы. А вот булеан уже говорит, а расшифровываем ли мы сообщение с этими параметрами или зашифровываем. То есть, не ломается логика использования аргументов, мне кажется что на когнитивном уровне это было бы правильнее

2024-12-17 19:58 UTC, Rexsell commented on src/main/java/school/faang/sprint2/task_7/Droid.java
> +    private static int LETTERS_OFFSET = 26;
А, тут я попался. Вернее неправильно понял, нужно статик финал, все ок

2024-12-17 19:59 UTC, Rexsell commented on src/main/java/school/faang/sprint2/task_7/Droid.java
> +    }
Ну окей, я изменю, но для галочки - я не согласен :)

2024-12-18 05:09 UTC, miked4king commented on src/main/java/school/faang/sprint2/task_7/Droid.java
> +    }
Я согласен с твоей точкой зрения о том, что наличие отдельных методов для шифрования и расшифрования делает интерфейс более понятным и интуитивным для пользователей пакета в энтерпрайз приложении, но с учетом той логики что мы сейчас имеем, можно не плодить данные методы)

2024-12-18 05:13 UTC, miked4king commented on src/main/java/school/faang/sprint2/task_7/Droid.java
> +@Setter
У тебя стоит аннотация @AllArgsConstructor, которая генерит конструктор, и в нем не будет использоваться сеттер, будет this.name = name, сеттер нужен для того, чтобы у созданного объекта изменять значение поля, а именного этого я не увидел в коде

2024-12-18 05:13 UTC, miked4king approved these changes

2024-12-18 05:13 UTC, merged