Mice are very nice!
CorporationX/god_bless pull request #15577
Opened 2024-12-15 19:23 UTC by almigor1

2024-12-19 05:41 UTC, miked4king requested changes

2024-12-19 05:41 UTC, miked4king commented on src/main/java/school/faang/sprint3/task48930/House.java
> +    private volatile boolean isEmpty;
в классе принято сначала писать константы, потом поля класса

2024-12-19 05:41 UTC, miked4king commented on src/main/java/school/faang/sprint3/task48930/FoodCollector.java
> +    public FoodCollector(String name, House house) {
мы уже используем lombok аннотации, конструктор можно заменить на @RequiredArgsConstructor

2024-12-19 05:41 UTC, miked4king commented on src/main/java/school/faang/sprint3/task48930/House.java
> +                this.isEmpty = false;
Переменная isEmpty обновляется после сбора еды, но это может привести к несоответствию состояния, если несколько потоков попытаются изменить ее одновременно. 
Чтобы тако проблемы не возникло можно сделать эту переменную атомарной, использовав AtomicBoolean

2024-12-19 05:41 UTC, miked4king commented on src/main/java/school/faang/sprint3/task48930/House.java
> +                    + roomFood);
в логе не принято использовать конкатенацию строк, стоит использовать плэйсхолдеры, получится примерно так 
log.info("{} собрал в комнате {} {} единиц еды {}", collectorName, room.getName(), foodQty, roomFood);

2024-12-19 05:41 UTC, miked4king commented on src/main/java/school/faang/sprint3/task48930/House.java
> +            log.info(collectorName + " пришел в комнату " + room.getName() + ", но там еда уже собрана. ");
аналогично комментарию выше

2024-12-19 05:41 UTC, miked4king commented on src/main/java/school/faang/sprint3/task48930/model/Room.java
> +    ReentrantLock lock;
модификатора доступа не хватает, и отступ выше можно убрать

2024-12-19 05:41 UTC, miked4king commented on src/main/java/school/faang/sprint3/task48930/model/Room.java
> +@Slf4j
вроде ничего не логгируется в данном классе, можно убрать

2024-12-20 19:29 UTC, miked4king requested changes

2024-12-20 19:29 UTC, miked4king commented on src/main/java/school/faang/sprint3/task48930/House.java
> +    private volatile AtomicBoolean isEmpty = new AtomicBoolean(false);
использование AtomicBoolean уже обеспечивает корректное управление состоянием в многопоточной среде, так как его методы являются атомарными и обеспечивают видимость изменений между потоками без необходимости использования дополнительных синхронизаций, таких как synchronized или volatile.
можно убрать

я бы еще сделал более информативным название переменной, с ходу не понятно что именно isEmpty

2024-12-20 19:29 UTC, miked4king commented on src/main/java/school/faang/sprint3/task48930/House.java
> +    //private volatile boolean isEmpty;
забыл убрать)

2024-12-20 19:29 UTC, miked4king commented on src/main/java/school/faang/sprint3/task48930/House.java
> +                this.isEmpty.set(false);
использование this для обращения к isEmpty не требуется, поскольку:
внутри методов класса Java компилятор автоматически понимает, что обращение к isEmpty относится к полю класса, если нет локальной переменной или параметра с таким же именем.
в большинстве случаев, когда нет конфликтов имен, использование this не добавляет дополнительной ценности и может даже немного ухудшить читаемость кода.

стоит использовать this когда есть конфликт имен, либо когда это сделает код более понятным

2024-12-20 19:29 UTC, miked4king commented on src/main/java/school/faang/sprint3/task48930/model/Room.java
> +    ReentrantLock lock;
private ReentrantLock lock;

2024-12-21 11:43 UTC, almigor1 commented on src/main/java/school/faang/sprint3/task48930/model/Room.java
> +    ReentrantLock lock;
вроде правил, не сохранилось

2024-12-22 05:09 UTC, miked4king approved these changes

2024-12-22 05:09 UTC, merged