Вы работаете в Microsoft
CorporationX/god_bless pull request #15618
Opened 2024-12-16 09:54 UTC by tr1pleK

2024-12-16 17:10 UTC, SemyonKrivtsov requested changes

2024-12-16 18:17 UTC, tr1pleK commented on src/main/java/school/faang/task_48196/MailSender.java
> +            threads[i] = new Thread(new SenderRunnable(i * 200, i * 200 + 199));
я не понял, что вы тут имели в виду. Можете разъяснить подробнее?

2024-12-16 18:18 UTC, tr1pleK commented on src/main/java/school/faang/task_48196/MailSender.java
> +    public static void main(String[] args) throws InterruptedException {
и тут тоже пожалуйста немного подробнее. Вы хотите чтобы я добавил try catch?

2024-12-16 18:24 UTC, SemyonKrivtsov commented on src/main/java/school/faang/task_48196/MailSender.java
> +    public static void main(String[] args) throws InterruptedException {
Метод main не должен быть `throws InterruptedException`

2024-12-16 18:26 UTC, SemyonKrivtsov commented on src/main/java/school/faang/task_48196/MailSender.java
> +            threads[i] = new Thread(new SenderRunnable(i * 200, i * 200 + 199));
`SenderRunnable(i * 200, (i +1)*199 + i)`

2024-12-16 18:26 UTC, SemyonKrivtsov commented on src/main/java/school/faang/task_48196/MailSender.java
> +            threads[i] = new Thread(new SenderRunnable(i * 200, i * 200 + 199));
Это не замечание, а вариант для оптимизации

2024-12-17 09:26 UTC, tr1pleK commented on src/main/java/school/faang/task_48196/MailSender.java
> +    public static void main(String[] args) throws InterruptedException {
его нужно обработать с помощью try, catch?

2024-12-17 17:21 UTC, SemyonKrivtsov commented on src/main/java/school/faang/task_48196/MailSender.java
> +    public static void main(String[] args) throws InterruptedException {
> его нужно обработать с помощью try, catch?

Да

> я просто немного не понимаю почему, ведь в решении на платформе написано, что main кидает исключение

Лучше обработать

2024-12-19 17:03 UTC, merged