BJS2-48317
CorporationX/god_bless pull request #15649
Opened 2024-12-16 15:32 UTC by OxanaNovozhilova

2024-12-17 17:32 UTC, Kayfral requested changes

2024-12-17 17:32 UTC, Kayfral commented on src/main/java/school/faang/task_48317/MailSender.java
> +    }
Смотри, твоя реализация сейчас работает последовательно, а не параллельно, потому что ты создаешь поток и сразу ждешь его завершения через join. Давай сделаем так: сначала создадим и запустим все 5 потоков, а потом будем ждать их завершения

2024-12-17 17:32 UTC, Kayfral commented on src/main/java/school/faang/task_48317/SenderRunnable.java
> +    }
Можно сделать код более реалистичным. Предлагаю добавить цикл, который будет имитировать отправку каждого письма в твоем диапазоне

2024-12-18 08:06 UTC, OxanaNovozhilova commented on src/main/java/school/faang/task_48317/SenderRunnable.java
> +    }
Кирилл, спасибо за ревью)

2024-12-18 19:07 UTC, Kayfral approved these changes
Отлично!

2024-12-18 19:07 UTC, merged