Solution to task BJS2-48237
CorporationX/god_bless pull request #15662
Opened 2024-12-16 17:28 UTC by askar0103

2024-12-17 17:44 UTC, Kayfral requested changes

2024-12-17 17:44 UTC, Kayfral commented on src/main/java/school/faang/task_48237/WeasleyFamily.java
> +        executor.shutdown();
После вызова executor.shutdown() было бы здорово добавить awaitTermination. Это поможет убедиться, что все задачи успеют завершиться перед окончанием работы программы

2024-12-17 17:44 UTC, Kayfral commented on src/main/java/school/faang/task_48237/WeasleyFamily.java
> +        executor.shutdown();
Смотри, в блоке catch при обработке InterruptedException нужно не забыть восстановить флаг прерывания через Thread.currentThread().interrupt(). Это важный момент для правильной работы механизма прерывания потоков. Давай добавим этот вызов?

2024-12-17 17:44 UTC, Kayfral commented on src/main/java/school/faang/task_48237/Chore.java
> +            Thread.sleep(1000);
Классно придумал с имитацией выполнения задачи!

2024-12-17 18:12 UTC, askar0103 commented on src/main/java/school/faang/task_48237/Chore.java
> +            Thread.sleep(1000);
Это я подсмотрел в доп. материалах)

2024-12-18 19:02 UTC, Kayfral approved these changes
Отлично!

2024-12-18 19:02 UTC, merged