Блокировка Spotify
CorporationX/god_bless pull request #15683
Opened 2024-12-16 20:24 UTC by almigor1

2024-12-17 08:48 UTC, SemyonKrivtsov requested changes

2024-12-17 08:48 UTC, SemyonKrivtsov commented on src/main/java/school/faang/sprint3/task49300/Music.java
> +        thread10.start();
Копипаста, давай подумаем как оптимизировать код, чтобы не прописывать одно и тоже несколько раз.

2024-12-17 08:48 UTC, SemyonKrivtsov commented on src/main/java/school/faang/sprint3/task49300/Player.java
> +
Лишние строки

2024-12-22 08:21 UTC, almigor1 commented on src/main/java/school/faang/sprint3/task49300/Music.java
> +        thread10.start();
переделал по другому, но непонятно, почему чекстайл требует только 2 пробела после switch перед case, idea форматирует стандартно по 4 пробела

2024-12-22 10:46 UTC, SemyonKrivtsov approved these changes

2024-12-22 10:46 UTC, merged