BJS2-47259 [Анализ активности пользователей в социальной сети]
CorporationX/god_bless pull request #15692
Opened 2024-12-16 22:23 UTC by Iv-an-s

2024-12-18 17:48 UTC, miked4king requested changes

2024-12-18 17:48 UTC, miked4king commented on src/main/java/school/faang/moduleone/sprinttwo/task_43541/UserActionAnalyzer.java
> +                .collect(Collectors.groupingBy(UserAction::getName));
хочу подсветить два момента:
1) решение кажется сложным, почему бы сразу в стриме не отфильтровать source по типу "comment" и дате за последний месяц, получается пробежимся по всем элементам только один раз.
2) в конструктор передавать стрим не лучшая практика, усложняет код и выглядит менее читаемо

2024-12-18 17:48 UTC, miked4king commented on src/main/java/school/faang/moduleone/sprinttwo/task_43541/UserActionAnalyzer.java
> +        return percentagesByType;
если есть желание, то можно переделать данный код через стрим, через метод collect(Collectors.toMap(), код будет короче и чище.

в целом не критично)

2024-12-18 20:29 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprinttwo/task_43541/UserActionAnalyzer.java
> +                .collect(Collectors.groupingBy(UserAction::getName));
Спасибо, переделал.

2024-12-18 20:29 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprinttwo/task_43541/UserActionAnalyzer.java
> +        return percentagesByType;
Желание было, но что-то не сообразил сходу как это аккуратно сделать. Оставил как есть.

2024-12-19 05:07 UTC, miked4king approved these changes

2024-12-19 05:07 UTC, miked4king commented on src/main/java/school/faang/moduleone/sprinttwo/task_43541/UserActionAnalyzer.java
> +                .collect(Collectors.groupingBy(name -> name, Collectors.counting()))
комментарий на будущее, collect терминальная операция, принято сохранять ее результаты в переменную.

2024-12-19 05:07 UTC, merged