bjs2-47622 tournament in kings landing
CorporationX/god_bless pull request #15710
Opened 2024-12-17 07:35 UTC by lcodio

solved

2024-12-17 14:06 UTC, 20cognosce requested changes

2024-12-17 14:06 UTC, 20cognosce commented on src/main/java/school/faang/bjs247622/Knight.java
> +    }
Почему не аннотациями

2024-12-17 14:06 UTC, 20cognosce commented on src/main/java/school/faang/bjs247622/Knight.java
> +        for (Trial trial : trials) {
forEach!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2024-12-17 14:06 UTC, 20cognosce commented on src/main/java/school/faang/bjs247622/King.java
> +        executorService.shutdown();
Фактически это правильно, но по-хорошему в тред пул не должен передаваться в сущности

Сущности и их задачи должны передаваться в тред пул

2024-12-17 14:06 UTC, 20cognosce commented on src/main/java/school/faang/bjs247622/King.java
> +            }
Зачем два try catch?
Оставь только второй
и секунды, а не минуты в логе

2024-12-17 21:09 UTC, lcodio commented on src/main/java/school/faang/bjs247622/King.java
> +        executorService.shutdown();
понятно, условие задачи значит путает, надо переделывать структуру задачи

2024-12-19 16:15 UTC, 20cognosce approved these changes
Принято

2024-12-19 16:15 UTC, 20cognosce commented on src/main/java/school/faang/bjs247622/King.java
> +            executorService.shutdownNow();
зачем второй раз

2024-12-19 16:15 UTC, merged