BJS2-47726
CorporationX/god_bless pull request #15742
Opened 2024-12-17 11:26 UTC by OxanaNovozhilova

2024-12-17 18:02 UTC, SemyonKrivtsov requested changes

2024-12-17 18:02 UTC, SemyonKrivtsov commented on src/main/java/school/faang/task_47726/Army.java
> +                throw new RuntimeException(e);
Маскируем одно исключение другим?

2024-12-17 18:02 UTC, SemyonKrivtsov commented on src/main/java/school/faang/task_47726/Army.java
> +                throw new RuntimeException(e);
Лучше просто залогировать

2024-12-18 09:37 UTC, OxanaNovozhilova commented on src/main/java/school/faang/task_47726/Army.java
> +                throw new RuntimeException(e);
Спасибо)

2024-12-18 17:27 UTC, merged