Solution to task BJS2-49260
CorporationX/god_bless pull request #15832
Opened 2024-12-18 10:49 UTC by askar0103

2024-12-20 10:09 UTC, Nafanuil commented on src/main/java/school/faang/task_49260/Game.java
> +    public void update(boolean earnedPoints, boolean lostLife) {
старайся всегда делать блок синхронизации как можно меньше, в данном случае у нас входные параметры никак не меняются нигде, так что если сначала проверить условие а потом сделать синхронизацию то код получится более оптимизирован тк в ряде случаем нам вообще не нужно будет ее делать ведь мы не попадаем в if

2024-12-20 18:27 UTC, mysosnovskaya requested changes

2024-12-20 18:27 UTC, mysosnovskaya commented on src/main/java/school/faang/task_49260/Game.java
> +        synchronized (isGameOverLock) {
А зачем нужна синхронизация на isGameOverLock? По сути мы её меняем только один раз и это изменение всегда из false в true. Операция присваивания всегда атомарная (в отличии от инкремента). От какого случая спасает этот лок?

2024-12-21 09:22 UTC, askar0103 commented on src/main/java/school/faang/task_49260/Game.java
> +        synchronized (isGameOverLock) {
Я подумал, если один поток устанавливает isGameOver в true, то другой поток, который вызывает метод isGameOver(), может не увидеть это изменение, то есть другой поток может прочитать устаревшее значение isGameOver

2024-12-21 19:53 UTC, merged