feature(BJS2-46877) Add register and send notification
CorporationX/god_bless pull request #15838
Opened 2024-12-18 11:21 UTC by shakhzod99

2024-12-18 17:55 UTC, SemyonKrivtsov requested changes

2024-12-18 17:55 UTC, SemyonKrivtsov commented on src/main/java/school/faang/task_46877/NotificationManager.java
> +    Map<String, Consumer<Notification>> consumerMap = new HashMap<>();
Нет модификатора

2024-12-18 17:55 UTC, SemyonKrivtsov commented on src/main/java/school/faang/task_46877/Main.java
> +        notificationManager.sendNotification(emailNotification);
Дублирование кода, давай подумаем как реализовать чтобы три раза не пришлось прописывать почти одно и тоже

2024-12-19 06:42 UTC, shakhzod99 commented on src/main/java/school/faang/task_46877/Main.java
> +        notificationManager.sendNotification(emailNotification);
принял спасибо, отправил изменения

2024-12-19 06:42 UTC, shakhzod99 commented on src/main/java/school/faang/task_46877/NotificationManager.java
> +    Map<String, Consumer<Notification>> consumerMap = new HashMap<>();
спасибо, добавил

2024-12-19 07:57 UTC, merged