task google photos impl
CorporationX/god_bless pull request #15855
Opened 2024-12-18 13:54 UTC by bortsovamaria

2024-12-18 18:38 UTC, miked4king requested changes

2024-12-18 18:38 UTC, miked4king commented on src/main/java/school/faang/task_48878/GooglePhotosAutoUploader.java
> +    private void uploadPhotos(@NonNull List<String> photos) {
В целом хорошая работа!
есть замечание только по этому методу, когда метод startAutoUpload захватывает блокировку на объекте object и вызывает wait(), он освобождает блокировку, позволяя другим потокам  захватывать её.
когда object.notify() вызывается в onNewPhotoAdded, поток startAutoUpload снова получает блокировку при пробуждении, и в этот момент он снова проверяет условие и может вызвать uploadPhotos.
с учетом того, что этот метод вызывается только из startAutoUpload блокировка тут избыточна.

2024-12-19 10:23 UTC, bortsovamaria commented on src/main/java/school/faang/task_48878/GooglePhotosAutoUploader.java
> +    private void uploadPhotos(@NonNull List<String> photos) {
Точно, спасибо

2024-12-21 05:24 UTC, miked4king approved these changes

2024-12-21 05:24 UTC, merged