Распределенная армия героев меча и магии
CorporationX/god_bless pull request #15873
Opened 2024-12-18 16:49 UTC by Timka-cloud1

2024-12-18 18:16 UTC, SemyonKrivtsov requested changes

2024-12-18 18:16 UTC, SemyonKrivtsov commented on src/main/java/school/faang/spring3/task_47935/Army.java
> +            PowerThread powerThread = new PowerThread(unit);
Тут создаем переменную каждую итерацию в цикле. Давай вынесем создание переменных за цикл, а внутри будем их использовать.

2024-12-18 18:16 UTC, SemyonKrivtsov commented on src/main/java/school/faang/spring3/task_47935/Army.java
> +
Лишни строки

2024-12-19 06:52 UTC, Timka-cloud1 commented on src/main/java/school/faang/spring3/task_47935/Army.java
> +            PowerThread powerThread = new PowerThread(unit);
не понял, для чего выносить это? эти переменные нужны только в цикле и выносить их вне цикла не имеет значения. Обьясните пожалуйста что вы имели ввиду?

2024-12-19 07:55 UTC, SemyonKrivtsov commented on src/main/java/school/faang/spring3/task_47935/Army.java
> +            PowerThread powerThread = new PowerThread(unit);
Я имею ввиду, что каждый раз заново производить аллокацию памяти под переменные не рационально. Нормальный сценарий использования: вы создаете переменную, переиспользуете эту ячейку памяти. А так получается что в цикле вы каждый раз создаете переменную с таким же названием, но если проследите за адресом в памяти, то он будет меняться каждый раз. Что создает дополнительную путаницу в случае отладки и бесполезную нагрузку на интерпретатор при исполнении.

2024-12-19 08:10 UTC, merged