BJS2-47858: Распределенная армия героев меча и магии
CorporationX/god_bless pull request #15888
Opened 2024-12-18 19:44 UTC by AlejandroQuito

2024-12-19 17:19 UTC, SemyonKrivtsov requested changes

2024-12-19 17:19 UTC, SemyonKrivtsov commented on src/main/java/school/faang/sprint_3/task_47858/Army.java
> +            PowerCalculator calculator = new PowerCalculator(unit);
Переменные лучше создавать до использования в цикле, а внутри уже переиспользовать их

2024-12-19 19:23 UTC, AlejandroQuito commented on src/main/java/school/faang/sprint_3/task_47858/Army.java
> +            PowerCalculator calculator = new PowerCalculator(unit);
А как лучше быть с тем, что по сути для создания экземпляра класса в цикле мне нужен тот самый элемент цикла?
То есть если конкретно, то для создания PowerCalculator нужен unit который мы получаем идя по циклу. 
А если создавать экземпляр вне цикла то он будет не инициализирован, что по сути создает просто лишний код... 
(код для примера)
      PowerCalculator calculator;
     
      for (Unit unit : units) {
            calculator = new PowerCalculator(unit);

2024-12-20 08:13 UTC, SemyonKrivtsov commented on src/main/java/school/faang/sprint_3/task_47858/Army.java
> +            PowerCalculator calculator = new PowerCalculator(unit);
Почему лишний? У этого есть свой смысл в оптимизации при работе с памятью

2024-12-20 14:19 UTC, AlejandroQuito commented on src/main/java/school/faang/sprint_3/task_47858/Army.java
> +            PowerCalculator calculator = new PowerCalculator(unit);
Хорошо! Я просто думал почему-то что он относительно бесполезен..

2024-12-20 18:31 UTC, merged