BJS2-48553
CorporationX/god_bless pull request #15918
Opened 2024-12-19 03:09 UTC by DMCHMB

BJS2-48553
Mice are very nice!

В коде скорее всего переборщил с логгированием.
main output:
![image](https://github.com/user-attachments/assets/1604d7e2-ceb5-48d6-9e5e-741a6600b887)
![image](https://github.com/user-attachments/assets/59a78e0c-635f-4be2-b8f0-fcd1f46d5760)

2024-12-21 13:38 UTC, 20cognosce requested changes

2024-12-21 13:38 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248553/Main.java
> +        ScheduledExecutorService executor = Executors.newScheduledThreadPool(EXECUTORS_POOL_SIZE);
Отделять пустыми строками логические блоки кода, где создание, где запуск, где завершение

2024-12-21 13:38 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248553/Main.java
> +            if (house.getRoomsRemaining().get() <= 0) {
Может быть < ?

2024-12-21 13:38 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248553/Main.java
> +            log.info("All threads was stopped correctly");
shutdownNow надо вызывать если пройден await без результата

2024-12-21 13:38 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248553/Main.java
> +        log.info("All rooms was cleared: {}", allRoomsCleared);
Почему метод collectFood сам не отвечает за вывод и возвращение такого ответа

2024-12-21 13:38 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248553/Main.java
> +            if (house.getRoomsRemaining().get() <= 0) {
Зачем два аналога одно и того же

2024-12-21 13:38 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248553/House.java
> +        roomsRemaining.set(roomIndexes.size());
Почему не берешь размер очереди?

2024-12-21 13:38 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248553/House.java
> +                        })));
Круто, но зачем addAll если можно просто присвоить ссылку
И почему в конструкторе не сделать инициализацию, чтобы этот метод возвращал перемешанную по индексам очередь

2024-12-21 13:38 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248553/House.java
> +        if (roomsRemaining.get() <= 0) {
Размер очереди сверять, и если есть индексы, то вытащить два
Причем, проверка и вытаскивание должны быть под одним блоком синхронизации

2024-12-21 13:38 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248553/House.java
> +        for (int i = 0; i < roomPerThread && !roomIndexes.isEmpty(); i++) {
не писать циклы for

2024-12-21 13:38 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248553/House.java
> +        }
Это некорректно
В очереди осталась одна комната, два потока проверили !roomIndexes.isEmpty() и попали на итерацию
делают
(1) poll() - достал комнату
(2) poll() - получил ошибку

2024-12-21 13:38 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248553/House.java
> +            roomsRemaining.decrementAndGet();
Почему ты poll сделал там выше, а счетчик уменьшил только здесь - между этими событиями может быть неконсистентное состояние 

Работай с размером очереди

2024-12-21 13:38 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248553/House.java
> +            room.clearFood();
Поскольку у каждого потока свои комнаты, то на комнатах локи не нужны, это ок
Но еда всех комнат складывается в одну потокобезопасную корзину

На collectFood внутри комнаты выстави sleep на пару секунд для эмуляции очистки
+ clearFood и collectFood один и тот же метод у комнаты должен быть

2024-12-23 00:53 UTC, DMCHMB commented
рефактор и исправление замечаний
- параметры работы задаются в константах в мейне
- коллекция для сбора еды заменена на ConcurrentLinkedQueue для экономии памяти и повышения скорости записи
- добавлены номера комнат для логгирования
- методы clearFood и collectFood объединены в один collectFood
- блокировка потоков сделана только на этапе получения индексов комнат и складывания в отдельный для каждого
список для последующей обработки. Обработка комнат ведется параллельно всеми доступными потоками.
- обработан пограничный случай, когда комната осталась одна вочереди: 
поток фильтрует комнаты перед обработкой, чтобы не получить NPE 

Вывод main, когда потоки не успевают завершить работу (таймаут 3 секунды,
 должна обработаться только первая партия комнат):
![image](https://github.com/user-attachments/assets/13b77f12-4028-41b7-aabd-406868ad70c2)

Вывод main, когда потоки успели завершить работу (таймаут 30 секунд):
![image](https://github.com/user-attachments/assets/3c75eb2b-6110-449d-9210-e7410d05518c)

2024-12-23 11:01 UTC, 20cognosce requested changes
Давай убирай всё лишнее и упрощай код

2024-12-23 11:01 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248553/House.java
> +                .filter(Objects::nonNull)
У тебя тут противоречие, получается, что roomsToProcess может быть пустым?
А почему вывод, что все еда во всех комнатах собрана есть только выше

Или все-таки не может быть пустым?

2024-12-23 15:36 UTC, 20cognosce approved these changes
Принято

2024-12-23 15:36 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248553/House.java
> +    private Queue<Room> initializeRoomIndexes(List<Room> inputData) {
initializeRooms

2024-12-23 15:36 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248553/House.java
> +                .mapToObj(i -> rooms.poll())
Это корректно только за счет того, что где-то там внизу класса ты присвоил rooms = ConcurrentLinkedQueue
От этой одной строчки зависит вся потокобезопасность

2024-12-23 15:36 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248553/House.java
> +                    collectedFood.addAll(c);
А зачем очередью ConcurrentLinkedQueue делать и общую корзину еды? Не самая подходящая коллекция
По потокобезопасности - всё корректно

2024-12-23 15:36 UTC, merged