BJS2-48710 Mice are very nice!
CorporationX/god_bless pull request #15913
Opened 2024-12-19 00:37 UTC by rsticks

2024-12-21 05:51 UTC, miked4king requested changes

2024-12-21 05:51 UTC, miked4king commented on src/main/java/school/faang/bjs248710/Room.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(Room.class);
давай воспользуемся аннотацией lombok @Slf4j

2024-12-21 05:51 UTC, miked4king commented on src/main/java/school/faang/bjs248710/Main.java
> +        executorService.shutdown();
посмотри статью в которой описано как правильно завершать работу executorService
https://www.baeldung.com/java-executor-service-tutorial

2024-12-21 05:51 UTC, miked4king commented on src/main/java/school/faang/bjs248710/House.java
> +                rooms.stream().map(room -> room.getFoods().size()).reduce(0, Integer::sum));
давай вместо sout использовать логгер, так как он будет использоваться в работе.
на уровне класса аннотация @Slf4j.

и не лучшая практика писать стрим в строку, каждый новый метод в стриме лучше писать с новой строки для большего понимания (возможно стоит вынести в отдельный метод)

2024-12-21 19:43 UTC, rsticks commented on src/main/java/school/faang/bjs248710/Room.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(Room.class);
А почему лучше использовать @Slf4j ?

2024-12-22 05:13 UTC, miked4king commented on src/main/java/school/faang/bjs248710/Room.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(Room.class);
аннотации lombok предназначены для того, чтобы не засорять код конструкторами, геттерами, сеттерами и т.д.
по сути тоже самое, только вместо такой длинной строки одна аннотация на уровне класса.

2024-12-22 05:13 UTC, miked4king approved these changes

2024-12-22 05:14 UTC, merged