bjs2-48033 help a colleague
CorporationX/god_bless pull request #15937
Opened 2024-12-19 09:14 UTC by lcodio

2024-12-19 17:36 UTC, 20cognosce requested changes

2024-12-19 17:36 UTC, 20cognosce commented on src/main/java/school/faang/bjs248033/Main.java
> +        for (int i = 1; i <= PEOPLE_AMOUNT; i++) {
почему цикл for

2024-12-19 17:36 UTC, 20cognosce commented on src/main/java/school/faang/bjs248033/Main.java
> +            String workplace = String.format("Workplace%d", (i % 10) + 1);
@Builder у Person

2024-12-19 17:36 UTC, 20cognosce commented on src/main/java/school/faang/bjs248033/Main.java
> +            String workplace = String.format("Workplace%d", (i % 10) + 1);
i у тебя начинается с 1 итак

2024-12-19 17:36 UTC, 20cognosce commented on src/main/java/school/faang/bjs248033/Main.java
> +        for (int i = 1; i <= THREADS_AMOUNT; i++) {
Используй другие инструменты для итерации, это архаизм

2024-12-19 17:36 UTC, 20cognosce commented on src/main/java/school/faang/bjs248033/Main.java
> +            log.info("Thread {}: startIndex = {}, endIndex = {}", i, startIndex, endIndex);
Возьми всех людей и один раз сделай
ListUtil.partition()
Не занимайся этим...

2024-12-19 17:36 UTC, 20cognosce commented on src/main/java/school/faang/bjs248033/PersonInfoPrinter.java
> +    }
Лямбды пожалуйста

2024-12-19 17:36 UTC, 20cognosce commented on src/main/java/school/faang/bjs248033/Main.java
> +            executorService.submit(printer);
Бенчмарк сделай и пришли скрин - в одном потоке и в 10 потоках время выполнения

2024-12-20 07:58 UTC, lcodio commented on src/main/java/school/faang/bjs248033/PersonInfoPrinter.java
> +    }
Idea просит заменить на это. По сути добавляется только stream()

2024-12-20 09:40 UTC, lcodio commented on src/main/java/school/faang/bjs248033/Main.java
> +            executorService.submit(printer);
Сделала с помощью :     
long startTime = System.nanoTime();
long endTime = System.nanoTime();
log.info("Multy-thread duration: {} ms", (endTime - startTime) / 1_000_000);

разницы почти нет, на 1 потоке считается даже немного быстрее даже для 100 тыс людей

2024-12-20 09:42 UTC, lcodio commented on src/main/java/school/faang/bjs248033/Main.java
> +            executorService.submit(printer);
![multy](https://github.com/user-attachments/assets/6c886fff-f93c-4736-b2ee-344443531c82)
![single](https://github.com/user-attachments/assets/512fd2e9-e00c-4924-9411-60a9f7728376)

2024-12-20 12:40 UTC, 20cognosce approved these changes
Побольше людей добавить, чтобы заметить производительность при многопоточной работе

2024-12-20 12:40 UTC, 20cognosce commented on src/main/java/school/faang/bjs248033/ListUtil.java
> +    public static <T> List<List<T>> partition(List<T> list, int size) {
Есть такой готовый метод в библиотеке apache commons

2024-12-20 12:40 UTC, 20cognosce commented on src/main/java/school/faang/bjs248033/Main.java
> +                        .build())
Ок

2024-12-20 12:40 UTC, 20cognosce commented on src/main/java/school/faang/bjs248033/Main.java
> +            executorService.shutdownNow();
Второй раз не нужно

2024-12-20 12:40 UTC, merged