BJS2-48423 Sprint03. Task01. Parallelism. MailSender
CorporationX/god_bless pull request #15977
Opened 2024-12-19 15:46 UTC by Mike-GB22

Вы работаете в Microsoft!
👩‍💻 🧠

Условие задачи:
Вы работаете над проектом почтового клиента (что-то вроде Microsoft Outlook). В текущей реализации все сообщения отправляются последовательно в одном потоке — ваш сервис отправляет их по очереди. Но вы, как инициативный разработчик, решаете улучшить производительность и предложить параллельную отправку сообщений.

На данный момент в очереди скопилось 1000 писем, и задача состоит в том, чтобы разбить их на 5 потоков, где каждый поток будет обрабатывать и отправлять по 200 писем. Ваша цель — реализовать это распределение, чтобы ускорить процесс и сделать его более эффективным.

Требования:
1️⃣ Создать класс SenderRunnable, который реализует интерфейс Runnable. У каждого потока будет своя порция писем, поэтому в конструкторе класса передайте два параметра:

int startIndex

int endIndex.

2️⃣ В методе run() этого класса нужно описать логику отправки писем. Для упрощения — можно просто выводить сообщение об успешной отправке письма (например, "Письмо отправлено").

3️⃣ Написать класс MailSender, в котором приложение будет запускаться

4️⃣ В методе main() этого класса создать 5 потоков с помощью классов Thread и SenderRunnable. Каждый поток должен работать только со своими письмами (по 200 писем на поток).

5️⃣ Дождаться завершения всех потоков с помощью метода thread.join(). Когда все письма будут отправлены — вывести финальное сообщение об успешном завершении.

2024-12-19 17:28 UTC, SemyonKrivtsov requested changes

2024-12-19 17:28 UTC, SemyonKrivtsov commented on src/main/java/derschrank/sprint03/task01/bjstwo_48423/MailSender.java
> +            int oldPointer = pointer;
Переменные нужно создавать до цикла, чтобы их переиспользовать внутри, а не создавать каждый раз при интерациях

2024-12-19 17:28 UTC, SemyonKrivtsov commented on src/main/java/derschrank/sprint03/task01/bjstwo_48423/MailSender.java
> +                throw new RuntimeException(e);
Маскируем одно исключение другим? Лучше просто залогировать

2024-12-19 17:28 UTC, SemyonKrivtsov commented on src/main/java/derschrank/sprint03/task01/bjstwo_48423/MailSender.java
> +            int oldPointer = pointer;
Исправь везде по коду

2024-12-19 21:58 UTC, Mike-GB22 commented on src/main/java/derschrank/sprint03/task01/bjstwo_48423/MailSender.java
> +                throw new RuntimeException(e);
Хорошо, вывел в консоль

2024-12-19 22:02 UTC, Mike-GB22 commented on src/main/java/derschrank/sprint03/task01/bjstwo_48423/MailSender.java
> +            int oldPointer = pointer;
объявить переменную int oldPointer = 0?
а зачем? что это дает? 
вижу минус, это выносит мою логику за скобки, а какие плюсы?

2024-12-19 22:03 UTC, Mike-GB22 commented on src/main/java/derschrank/sprint03/task01/bjstwo_48423/MailSender.java
> +            int oldPointer = pointer;
> Исправь везде по коду

не нашел, может я не правильно понял?
а о чем идет речь?

2024-12-20 08:07 UTC, SemyonKrivtsov commented on src/main/java/derschrank/sprint03/task01/bjstwo_48423/MailSender.java
> +            int oldPointer = pointer;
`int oldPointer = pointer;` - тут закрыто два действия, создание переменной oldPointer  и присвоение ей значения. Не обязательно при создании переменной ей что-то присваивать. Создание переменной - это выделение памяти под этот тип данных. В вашем решении он перевыделяется каждую итерацию в цикле. Если вынести за цикл `int oldPointer;` , то спокойно внутри цикла можно использовать `oldPointer = pointer;`

2024-12-20 08:08 UTC, SemyonKrivtsov commented on src/main/java/derschrank/sprint03/task01/bjstwo_48423/MailSender.java
> +            int oldPointer = pointer;
> > Исправь везде по коду
> 
> не нашел больше, может я не правильно понял?

Посмотри везде где создается переменная внутри цикла - это неправильный подход

2024-12-21 19:18 UTC, merged