Bro Force!
CorporationX/god_bless pull request #15975
Opened 2024-12-19 15:37 UTC by tr1pleK

2024-12-19 16:04 UTC, KostyaGig commented on src/main/java/school/faang/task_49272/Game.java
> +        synchronized (scoreLock) {
Small optimization: if earnedPoint == false then there is no need to acquire the lock

2024-12-20 17:05 UTC, ArtemValt commented on src/main/java/school/faang/task_49272/Main.java
> +            } catch (InterruptedException e) {
при InterruptedException ошибке, нужно еще взаимодействовать с потоком 
            Thread.currentThread().interrupt();

2024-12-20 17:05 UTC, ArtemValt commented on src/main/java/school/faang/task_49272/Main.java
> +    public static void main(String[] args) {
надо добавить логику проверки на завершение работы, чтобы работа не получилась бесконечной 
try {
            if (!executorService.awaitTermination(1, java.util.concurrent.TimeUnit.MINUTES)) {
                System.err.println("Потоки не завершились вовремя");
            }
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            System.err.println("Ошибка ожидания завершения потоков: " + e.getMessage());
        }

2024-12-24 17:20 UTC, tr1pleK commented on src/main/java/school/faang/task_49272/Main.java
> +                    try {
меня просили добавить такую конструкцию, но я ее добавил и что то все поломалось, программа не завершается корректно, можно подсказку как исправить?
у меня были идея в том, чтобы game возвращал значение, и если оно false, то нужно завершить игру и выйти из цикла в main, сейчас игра вроде завершается (и то все равно некорректно, когда жизней уже меньше 0 она почему то все равно продолжает выполняться) но программа продолжает выполнение и ничего не происходит.

2024-12-24 19:08 UTC, mysosnovskaya requested changes

2024-12-24 19:08 UTC, mysosnovskaya commented on src/main/java/school/faang/task_49272/Main.java
> +                if (!game.update(earnedPoints, lostLife)) {
Здесь game.update вызывается уже второй раз за итерацию цикла. Точно ли это верная логика? А если метод update выше вернул false, то ты не узнаешь о том, что игру нужно завершить?

2024-12-24 19:08 UTC, mysosnovskaya commented on src/main/java/school/faang/task_49272/Main.java
> +                        if (!executorService.awaitTermination(1, TimeUnit.MINUTES)) {
Ты не можешь находясь внутри одного из потока, управляемого пулом потоков, ждать завершения этого потока. Такая операция должна происходить снаружи. Т.е. после цикла for

2024-12-24 21:32 UTC, mysosnovskaya approved these changes

2024-12-24 21:32 UTC, merged