BJS2-49185
CorporationX/god_bless pull request #15981
Opened 2024-12-19 15:58 UTC by OxanaNovozhilova

2024-12-19 17:43 UTC, Kayfral requested changes

2024-12-19 17:43 UTC, Kayfral commented on src/main/java/school/faang/task_49185/Player.java
> +    }
Смотри, в методах play() и pause() стоит добавить проверку текущего состояния isPlaying перед его изменением. Это поможет тебе избежать конфликтов между потоками. Такая проверка сделает код более надёжным.

Пример конфликта:

Предположим, два потока вызывают методы play() и pause() почти одновременно:

Поток A вызывает play().
Поток B вызывает pause().

Так как методы play и pause не синхронизированы, возможен такой порядок выполнения:

Поток A начинает выполнение метода play() и выводит:
Music is playing

До того как поток A вызовет changeStatus(true), поток B начинает выполнение метода pause() и выводит:
Music is stopped

Поток B вызывает changeStatus(false) и устанавливает isPlaying = false, выводя:
Status of music: false

Поток A теперь продолжает выполнение и вызывает changeStatus(true), устанавливая isPlaying = true, выводя:
Status of music: true

В результате на консоли мы увидим следующее:

Music is playing
Music is stopped
Status of music: false
Status of music: true

А как я понимаю, по твоей логике должно было бы быть, что то такое:
Music is playing
Status of music: true
Music is stopped
Status of music: false

Здесь очевидна проблема: хотя последний вызов play установил isPlaying = true, логика приложения может быть нарушена, так как действия потоков не согласованы, и их выполнение перемешивается.

2024-12-19 17:43 UTC, Kayfral commented on src/main/java/school/faang/task_49185/Music.java
> +        threadPause.start();
Посмотри в сторону ExecutorService для управления потоками.

2024-12-20 04:31 UTC, OxanaNovozhilova commented on src/main/java/school/faang/task_49185/Music.java
> +        threadPause.start();
Спасибо)

2024-12-20 04:31 UTC, OxanaNovozhilova commented on src/main/java/school/faang/task_49185/Player.java
> +    }
Спасибо)

2024-12-20 04:31 UTC, OxanaNovozhilova commented
Кирилл, спасибо за ревью)

2024-12-20 19:00 UTC, Kayfral approved these changes
Круто!

2024-12-20 19:00 UTC, merged