Потренируем StreamAPI 3
CorporationX/god_bless pull request #15994
Opened 2024-12-19 17:57 UTC by almigor1

2024-12-20 19:16 UTC, miked4king requested changes

2024-12-20 19:16 UTC, miked4king commented on src/main/java/school/faang/sprint2/task47055/service/StreamFunc.java
> +                )
этот блок можно написать гораздо более понятно и элегантно.
1) return friends.get(friend1).stream().anyMatch(friends.get(friend2)::contains); все что после return стоит вынести в отдельный метод для того чтобы сделать этот стрим наиболее понятным и читаемым.
2) вместо friends.keySet() мы можем использовать entrySet, чтобы мы могли получить как ключ, так и значение у конкретного элемента.

в целом можно сделать несколько операторов .filter например в первом проверяем что имена разные и т.д
в целом стримы сделаны для функционально и элегантного кода, если условие в методе не помещается в одну строку то стоит почти всегда вынести его в отдельный метод

2024-12-20 19:16 UTC, miked4king commented on src/main/java/school/faang/sprint2/task47055/service/StreamFunc.java
> +                .distinct()
мы можем сделать решение чуть проще и не сортировать полученный результат, если в методе выше будем возвращать не List<String> а готовую строку. и после flatMap останется только собрать эти строки в лист.

2024-12-20 19:16 UTC, miked4king commented on src/main/java/school/faang/sprint2/task47055/service/StreamFunc.java
> +                .filter(i -> Objects.equals(i, IntStream.range(1, i).filter(j -> i % j == 0).sum()))
тоже вынес бы это в отдельный метод.
стримы всегда стоит писать, перенося новый метод на новую строку, так их гораздо проще читать

2024-12-20 19:16 UTC, miked4king commented on src/main/java/school/faang/sprint2/task47055/service/StreamFunc.java
> +                })
в методе ниже ты уже пользовался методом rangeClosed, можно попробовать переписать это с его помощью.

IntStream.rangeClosed(start, end)
      .filter(i -> {
       return IntStream.range(0, number.length() / 2)
       )
       
надеюсь этой подсказки хватит)

2024-12-20 19:16 UTC, miked4king commented on src/main/java/school/faang/sprint2/task47055/service/StreamFunc.java
> +        }
приблизительно похожим образом (что и в методе выше) можно переписать тут

2024-12-21 10:09 UTC, almigor1 commented
не все замечания учел, так как сроки поджимают. вмержил, что сделал для истории

2024-12-21 10:09 UTC, merged