bjs2-46205 handle errors nicely
CorporationX/god_bless pull request #16000
Opened 2024-12-19 19:08 UTC by lcodio

commit with questions:
в методе main в строке  () -> FileUpload.uploadFile("C:\\data.txt")
метод uploadFile Idea просит обернуть в try-catch, почему?

2024-12-19 20:51 UTC, 20cognosce requested changes

2024-12-19 20:51 UTC, 20cognosce commented on src/main/java/school/faang/bjs246205/Main.java
> +                () -> FileUpload.uploadFile("C:\\data.txt"),
Ну у тебя и не компилируется этот код и падает с ошибкой, потому что Exception - обязательно проверяемое исключение строго там, где ты этот метод и вызываешь

Компилятор не устраивает то, что ты где-то там в ErrorHandler потом обработаешь это, код просто не компилируется твой

2024-12-19 20:51 UTC, 20cognosce commented on src/main/java/school/faang/bjs246205/FileUpload.java
> +    public static String uploadFile(String pathFile) throws Exception {
Здесь RuntimeException кидать

2024-12-20 07:15 UTC, lcodio commented on src/main/java/school/faang/bjs246205/Main.java
> +                () -> FileUpload.uploadFile("C:\\data.txt"),
Посмотрела, у кого-то нормально компилируется https://github.com/CorporationX/god_bless/commit/d086a51072803077b52ebb2b67004492c4287cd6
Чем отличается от моего кода?

2024-12-20 11:14 UTC, 20cognosce requested changes
Где исправления? Всё так же Build failed

2024-12-20 15:33 UTC, lcodio commented
RuntimeException сделал, 
не понятно тогда как обрабатывается исключение, тем более "красиво".

У кого-то нормально компилируется, код такой же
https://github.com/CorporationX/god_bless/commit/d086a51072803077b52ebb2b67004492c4287cd6
Чем отличается от моего кода?

2024-12-20 16:21 UTC, 20cognosce requested changes

2024-12-20 16:21 UTC, 20cognosce commented on src/main/java/school/faang/bjs246205/Main.java
> +                () -> FileUpload.uploadFile("C:\\data.txt"),
Интересно, действительно
Я и у себя проверил - тот ПР нормально компилируется

Сейчас буду проверять твой

2024-12-20 16:21 UTC, 20cognosce commented on src/main/java/school/faang/bjs246205/Main.java
> +                () -> FileUpload.uploadFile("C:\\data.txt"),
![image](https://github.com/user-attachments/assets/3ad9d6c2-bc08-41fc-8345-60b46a2651a4)
Разница в том, что ты используешь стандартный Supplier, а его метод get() в своей сигнатуре не бросает исключения

с withErrorHandling2 компилируется код

2024-12-20 16:23 UTC, 20cognosce commented on src/main/java/school/faang/bjs246205/FileUpload.java
> +    public static String uploadFile(String pathFile) throws Exception {
Переделать под свой Supplier с throws Exception

2024-12-20 17:54 UTC, lcodio commented on src/main/java/school/faang/bjs246205/Main.java
> +                () -> FileUpload.uploadFile("C:\\data.txt"),
поняла)

2024-12-21 12:54 UTC, 20cognosce approved these changes

2024-12-21 12:54 UTC, merged