BJS2-48925
CorporationX/god_bless pull request #16005
Opened 2024-12-19 20:10 UTC by DMCHMB

BJS2-48925
Google Photo sync
main output:
![image](https://github.com/user-attachments/assets/1a20c283-064c-447f-9d71-6e4719cf69a4)

2024-12-19 20:48 UTC, 20cognosce requested changes

2024-12-19 20:48 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248925/GooglePhotosAutoUploader.java
> +        while (!exit.get()) {
в цикле захватывать лок - перебор
Во вне, в тред вынес хотя бы

2024-12-19 20:48 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248925/GooglePhotosAutoUploader.java
> +                while (photosToUpload.isEmpty() && !exit.get()) {
И тут еще один цикл...
Тебе не нужны циклы в этом методе, делай их в потоке

2024-12-19 20:48 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248925/GooglePhotosAutoUploader.java
> +            }
Зачем ты тут отпустил лок и захватываешь его снова
Надо не отпуская выполнить удаление

2024-12-19 20:48 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248925/GooglePhotosAutoUploader.java
> +            temp.forEach(photo -> log.info("Thread {} is uploading photo {}", Thread.currentThread().getName(), photo));
Зачем копию делать, нельзя сначала под локом сделать лог, а затем все очистить, нафига память засорять

2024-12-19 20:48 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248925/Main.java
> +    }
Что это всё тут происходит, ну и велосипеды
Весь код в Uploader, там два метода
И оба метода синхронизированы по одному объекту

Тут в мейне ты только создаешь два потока, каждый из который вызывает один из методов

Убрать это всё

2024-12-19 20:48 UTC, 20cognosce requested changes

2024-12-19 20:48 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248925/Main.java
> +        }
Вот это тоже убрать отсюла
В мейне создание и завершение потоков, никакой логики

2024-12-20 04:43 UTC, DMCHMB commented
BJS2-48925
Google Photo sync
main after fix:
![image](https://github.com/user-attachments/assets/b778a44b-f413-4691-bb88-51f0e5b663c5)

2024-12-20 14:17 UTC, 20cognosce approved these changes

2024-12-20 14:17 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248925/Main.java
> +        newPhotoAdder.start();
Пойдёт

2024-12-20 14:17 UTC, 20cognosce commented on src/main/java/school/faang/sprint_3/task_bjs248925/GooglePhotosAutoUploader.java
> +public class GooglePhotosAutoUploader {
Хорошо, теперь принято

2024-12-20 14:17 UTC, merged