BJS2-47918 Sprint03. Task02. Parallelism. Power of Army
CorporationX/god_bless pull request #16014
Opened 2024-12-19 21:55 UTC by Mike-GB22

Распределенная армия героев меча и магии
👩‍💻 🧠

Условие задачи:
Вы — командующий армией героев меча и магии, и вам поручено вычислить общую силу армии, состоящей из разных подразделений: лучники, мечники, маги и т.д. Но армия большая, так что нужно распределить расчёты между несколькими потоками, чтобы быстрее получить результат.

Требования:
1️⃣ Создайте классы:

Archer (лучник)

Swordsman (мечник)

Mage (маг)

Если хотите, добавьте другие подразделения.

У каждого бойца должно быть поле power — это его сила. Например, лучник может иметь силу 25, а маг — 50.

2️⃣ Напишите класс Army, который будет содержать список всех ваших бойцов. Внутри этого класса напишите метод calculateTotalPower(), который вычисляет общую силу армии.

3️⃣ Метод calculateTotalPower() должен использовать распараллеливание. Это значит, что каждый поток будет считать силу для отдельного бойца, а потом все потоки объединят свои результаты. Всё, что нужно делать потоку — это складывать поле power бойцов.

4️⃣ Для создания потоков используйте класс Thread. Для удобства, можно создать свой класс, который будет наследовать Thread, чтобы хранить в нём данные для расчётов.

5️⃣ Внешняя синхронизация не должна использоваться, только внутренняя механика распараллеливания.

ВАЖНО: если вы уже знакомы с темой синхронизации, то можете использовать. Если же ещё ничего не слышали про слово synchronized или не знаете пока, как правильно им пользоваться, то делайте без него! Цель здесь — именно научиться запускать потоки и распараллеливать работу. Потенциальные проблемы синхронизации мы будем решать позже!

Пример использования:
public class Main {
    public static void main(String[] args) throws InterruptedException {
        Army army = new Army();
        army.addUnit(new Archer(25));   // считаем в потоке 1
        army.addUnit(new Swordsman(40)); // считаем в потоке 2
        army.addUnit(new Mage(50));     // считаем в потоке 3
        army.addUnit(new Mage(20));     // считаем в потоке 4

        int totalPower = army.calculateTotalPower();
        System.out.println("Общая сила армии: " + totalPower);
    }
}

2024-12-20 08:32 UTC, SemyonKrivtsov requested changes

2024-12-20 08:32 UTC, SemyonKrivtsov commented on src/main/java/derschrank/sprint03/task02/bjstwo_47918/Army.java
> +            CalculatorThread thread = new CalculatorThread(unit);
Пересоздаете переменную каждую итерацию цикла. Нужно вынести создание за цикл, а внутри переиспользовать ее.

2024-12-20 08:32 UTC, SemyonKrivtsov commented on src/main/java/derschrank/sprint03/task02/bjstwo_47918/Main.java
> +        for (int i = 0; i < 6000; i++) {
Лучше оперировать константами, а не конкретными значениями

2024-12-20 08:32 UTC, SemyonKrivtsov commented on src/main/java/derschrank/sprint03/task02/bjstwo_47918/Main.java
> +        for (int i = 0; i < 6000; i++) {
Исправь везде по коду

2024-12-21 18:59 UTC, Mike-GB22 commented on src/main/java/derschrank/sprint03/task02/bjstwo_47918/Main.java
> +        for (int i = 0; i < 6000; i++) {
готово

2024-12-21 19:04 UTC, merged