BJS2-48888
CorporationX/god_bless pull request #16016
Opened 2024-12-19 22:32 UTC by Narol01

2024-12-22 20:39 UTC, 20cognosce requested changes

2024-12-22 20:39 UTC, 20cognosce commented on src/main/java/school/faang/task_48888/House.java
> +        possiblePosition++;
Почему инкременты декременты не потокобезопасны
Баг будет

2024-12-22 20:39 UTC, 20cognosce commented on src/main/java/school/faang/task_48888/User.java
> +            houseName.notifyAll();
Тут ты делаешь нотифай по монитору строки, а там у тебя wait по монитору объекта, это вообще работает?

2024-12-22 20:39 UTC, 20cognosce commented on src/main/java/school/faang/task_48888/User.java
> +            this.userRole = null;
Никаких null

2024-12-22 20:39 UTC, 20cognosce commented on src/main/java/school/faang/task_48888/User.java
> +        synchronized (house) {
Всё жестко выстроил в один поток, корректно, но многопоточности никакой

2024-12-22 20:39 UTC, 20cognosce commented on src/main/java/school/faang/task_48888/MainApp.java
> +        });
Сделай список юзеров и делай submit в forEach

2024-12-22 20:39 UTC, 20cognosce commented on src/main/java/school/faang/task_48888/User.java
> +            if (!(house.getPossiblePosition() > 0) || !house.getUserRoles().contains(role)) {
тут while иначе ты выходишь из условия не перепроверив условие

2024-12-23 15:31 UTC, 20cognosce requested changes
Убрать houseName и EmptyHouse

2024-12-23 15:31 UTC, 20cognosce commented on src/main/java/school/faang/task_48888/User.java
> +    private House houseName = EMPTY_HOUSE;
Что это? Я не понимаю, что ты пытаешься сделать
Зачем тебе отдельный класс EmptyHouse, почему houseName = EMPTY_HOUSE...

Нельзя использовать Optional для описания возможности наличия / отсутствия дома у юзера?

2024-12-23 15:31 UTC, 20cognosce commented on src/main/java/school/faang/task_48888/User.java
> +            houseName.notifyAll();
Не исправлено

2024-12-23 15:31 UTC, 20cognosce commented on src/main/java/school/faang/task_48888/MainApp.java
> +                executor.shutdownNow();
Наоборот, если тебе пришло true, значит тред пул успешно закрылся

2024-12-23 15:31 UTC, 20cognosce commented on src/main/java/school/faang/task_48888/House.java
> +        }
Это тоже корректно, но ничем от synchronized не отличается фактически

2024-12-23 16:37 UTC, Narol01 commented on src/main/java/school/faang/task_48888/House.java
> +        }
Просто попробовать решил

2024-12-23 16:37 UTC, Narol01 commented on src/main/java/school/faang/task_48888/User.java
> +            houseName.notifyAll();
Но оно работает , Монитором является Объект House  в обоих случаях

2024-12-23 21:01 UTC, 20cognosce approved these changes
Принято

2024-12-23 21:01 UTC, 20cognosce commented on src/main/java/school/faang/task_48888/MainApp.java
> +        users.forEach(user -> executor.execute(() -> user.joinHouse(starkHouse, user.getUserRole())));
Не писать в одну строчку

2024-12-23 21:01 UTC, merged