BJS2-48427 Sprint03. Task03. Parallelism. WeasleyFamily
CorporationX/god_bless pull request #16025
Opened 2024-12-20 03:25 UTC by Mike-GB22

They were very nice but extremely poor
👩‍💻 🧠
Условия задачи
В семье Уизли всегда полно домашних хлопот, и чтобы справиться с этим волшебным хаосом, Перси решил автоматизировать выполнение задач. Его идея — использовать пул потоков с помощью метода newCachedThreadPool(), чтобы поручить выполнение всех дел сразу нескольким потокам.

Требования:
1️⃣ Создайте класс Chore, который будет реализовывать интерфейс Runnable. Этот класс будет описывать каждую домашнюю задачу, которую нужно выполнить.

2️⃣ Добавьте поле chore типа String в класс Chore, чтобы хранить название задачи (например, "помыть посуду", "подмести пол"). Создайте конструктор, который принимает название задачи как параметр.

3️⃣ В методе run() класса Chore опишите логику выполнения задачи. Используйте Thread.currentThread().getName() для вывода имени потока, который выполняет задачу, и Thread.sleep() для имитации выполнения задачи.

4️⃣ В классе WeasleyFamily создайте массив chores, содержащий список задач, которые нужно выполнить. Например, ["помыть посуду", "подмести пол", "приготовить ужин"].

5️⃣ Создайте пул потоков с помощью Executors.newCachedThreadPool(). Этот пул потоков автоматически создаст новые потоки по мере необходимости и переиспользует старые для экономии ресурсов.

6️⃣ Добавьте задачи в пул потоков. Создайте объект класса Chore для каждой задачи из массива chores и добавьте его в пул потоков

7️⃣ Завершите работу пула потоков после выполнения всех задач.

2024-12-20 08:21 UTC, SemyonKrivtsov requested changes

2024-12-20 08:21 UTC, SemyonKrivtsov commented on src/main/java/derschrank/sprint03/task03/bjstwo_48427/Main.java
> +            throw new RuntimeException(e);
Маскируем одно исключение другим? Лучше просто залогировать

2024-12-20 08:21 UTC, SemyonKrivtsov commented on src/main/java/derschrank/sprint03/task03/bjstwo_48427/Main.java
> +        for (int i = 0; i < 50; i++) {
Лучше работать с константами, а не конкретными значениями

2024-12-20 08:21 UTC, SemyonKrivtsov commented on src/main/java/derschrank/sprint03/task03/bjstwo_48427/Main.java
> +        for (int i = 0; i < 50; i++) {
Исправь везде по коды

2024-12-21 19:13 UTC, Mike-GB22 commented on src/main/java/derschrank/sprint03/task03/bjstwo_48427/Main.java
> +            throw new RuntimeException(e);
понял

2024-12-21 19:13 UTC, Mike-GB22 commented on src/main/java/derschrank/sprint03/task03/bjstwo_48427/Main.java
> +        for (int i = 0; i < 50; i++) {
хорошо, сделал

2024-12-21 19:17 UTC, merged