Железный трон любой ценой
CorporationX/god_bless pull request #16053
Opened 2024-12-20 12:08 UTC by almigor1

2024-12-22 20:37 UTC, miked4king requested changes

2024-12-22 20:37 UTC, miked4king commented on src/main/java/school/faang/sprint3/task49100/Main.java
> +    private static final int TIME_DELTA_SEC = 1;
не совсем понимаю пользу данной константы

2024-12-22 20:37 UTC, miked4king commented on src/main/java/school/faang/sprint3/task49100/Main.java
> +
лишний отступ

2024-12-22 20:37 UTC, miked4king commented on src/main/java/school/faang/sprint3/task49100/Main.java
> +            }
тоже не совсем понятно для чего мы тут спим, если есть аргументы то готов услышать)
если нет то стоит убрать

2024-12-22 20:37 UTC, miked4king commented on src/main/java/school/faang/sprint3/task49100/UserScenario.java
> +    House house;
у этих полей не хватает модификаторов доступа

2024-12-22 20:37 UTC, miked4king commented on src/main/java/school/faang/sprint3/task49100/UserScenario.java
> +    private static final int TIME_TO_SERVE_SEC = 15;
обычно добавляют отступ между константами и полями класса

2024-12-22 20:37 UTC, miked4king commented on src/main/java/school/faang/sprint3/task49100/UserScenario.java
> +    public void run() {
видимо писал метод самостоятельно)
если реализуешь интерфейс строка с название класса подчеркивается красной линией, можно поставить на нее курсор, нажать alt + enter, implement methods и метод сгенерируется автоматически, останется только написать логику.
и если реализуешь метод интерфейса принято добавлять аннотацию @Override, если делать через хоткей, как я описал выше, она тоже автоматически проставится

2024-12-22 20:37 UTC, miked4king commented on src/main/java/school/faang/sprint3/task49100/model/House.java
> +        this.availableRolesQuantity = this.availableRoles.size();
this.availableRoles = new ArrayList<>(availableRoles) - не вижу смысла создавать новый лист, можно присвоить тот, который приходит в параметре.
this.availableRoles.size() - зачем использовать this тут? у нас же приходит в параметрах лист, можно его размер получить.

2024-12-22 20:37 UTC, miked4king commented on src/main/java/school/faang/sprint3/task49100/model/House.java
> +        synchronized (availableRoles) {
Синхронизация происходит на объекте availableRoles, который является списком, который изменяется. Это может привести к проблемам, если другой поток пытается синхронизироваться на этом же списке или использовать его, когда он заблокирован.
Вместо синхронизации на изменяемом объекте лучше создать отдельный объект для синхронизации, например объект Lock

2024-12-22 20:37 UTC, miked4king commented on src/main/java/school/faang/sprint3/task49100/model/House.java
> +        synchronized (availableRoles) {
аналогично комментарию выше

2024-12-22 20:37 UTC, miked4king commented on src/main/java/school/faang/sprint3/task49100/model/User.java
> +                            + " with a role of " + this.role);
поменять на плэйсхолдеры

2024-12-22 20:37 UTC, miked4king commented on src/main/java/school/faang/sprint3/task49100/model/User.java
> +                    + ". Role " + this.role + " is vacant now.");
поменять на плэйсхолдеры

2024-12-24 20:28 UTC, almigor1 commented on src/main/java/school/faang/sprint3/task49100/Main.java
> +            }
это я подумал, что может поэкспериментировать и не запускать все сразу. чтобы вывод был более равномерный
уберу тогда вместе с константой

2024-12-24 21:24 UTC, mysosnovskaya approved these changes

2024-12-24 21:24 UTC, merged