PR-ready
CorporationX/god_bless pull request #16067
Opened 2024-12-20 15:04 UTC by bormoley1983

2024-12-22 20:15 UTC, 20cognosce requested changes

2024-12-22 20:15 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +    }
Не писать main-метод тут, вынести в класс Main

2024-12-22 20:15 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +            executor.shutdown();
Интересный подход, не видел такого раньше
Создаешь поток, который закрывает тред пул с запланированными задачами, если работает - выглядит здраво

2024-12-22 20:15 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +                    executor.shutdown();
Не должна сборка еды что-то знать о тред пуле

2024-12-22 20:15 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +                    executor.shutdown();
Все-таки ты тут закрываешь тред пул на самом деле, а в мейне тогда что происходит? Оставь что-то одно

2024-12-22 20:15 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +                long nonEmptyRoomsCount = roomsList.stream().filter(rm -> !rm.getFoodList().isEmpty()).count();
не писать стримы так в одну строчку

2024-12-22 20:15 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +            for (int i = 0; i < Constants.ROOMS; i++) {
Один поток должен взять 2 или 1, если последняя, комнат
Почему ты все пробегаешь

2024-12-22 20:15 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +        synchronized (roomsList) {
Это то же самое, что synchronized на всём методе получается
Корректно, но очень не оптимально просто жестко всё синхронизировать в один поток

2024-12-22 20:15 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +                var foodData = room.getFoodList().stream().findFirst().orElseThrow(IllegalStateException::new);
Не писать так стримы, var убрать

2024-12-22 20:15 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +                collectedFood.add(foodData);
Ты коллекции обе еще засинхронизировал, для двойной надежности xdd
Можно вынести из текущего блока синхронизации

2024-12-22 20:15 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +                }
Декомпозировать весь этот метод collectFood на приватные подметоды, сейчас каша тут написана

2024-12-22 20:15 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +        }
Можно без цикла for в цикле for пожалуйста
Такие конструкции применяют на ЕГЭ школьники, давай стримами по-взрослому

2024-12-23 19:01 UTC, bormoley1983 commented on src/main/java/school/faang/bjs248526/House.java
> +    }
Я уже запутался: нужен мейн или нет?

2024-12-23 19:04 UTC, bormoley1983 commented on src/main/java/school/faang/bjs248526/House.java
> +            for (int i = 0; i < Constants.ROOMS; i++) {
Цикл не бежит по всем комнатам. 

Тут я пробегаю за раз столько комнат, сколько указанно в константе, т.е. 2. код готов для обработки любого числа комнат в потоке которое можноуказать в константах

2024-12-23 19:07 UTC, bormoley1983 commented on src/main/java/school/faang/bjs248526/House.java
> +                    executor.shutdown();
Да, если комнаты заканчиваются внутри итерации тред закрывается тут, в противном случае треб закрывается в методе мейн

2024-12-26 16:47 UTC, 20cognosce requested changes
Начинаем сначала

2024-12-26 16:47 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/Room.java
> +        synchronized (foodList) {
Масло масленное, зачем блокировка в блокировке

2024-12-26 16:47 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +        return roomsList.stream().allMatch(room -> room.getFoodList().isEmpty());
Не писать стримы в одну строчку

2024-12-26 16:47 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +                    .filter(Room::hasFood).count();
Не писать в строчку

2024-12-26 16:47 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +        Random random = new Random();
Зачем каждый раз новый создавать

2024-12-26 16:47 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +                Room room = roomsList.get(roomId);
Зачем такой цикл...
Каждый поток должен получить ровно две комнаты, почему ты цикл по всем комнатам устраиваешь

Зачем ты каждый раз рандомную комнату достаешь, почему нельзя заранее их перемешать и по очереди брать

При этом никакой защиты от того, что ты одну и ту же комнату по нескольку раз будешь брать тут нет, переделать всю логику метода

2024-12-26 16:47 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +                synchronized (room) {
И этого быть не должно, надо сразу уникальную комнату для каждого потока давать

2024-12-26 16:47 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +                                .orElseThrow(IllegalStateException::new);
?
Что это и зачем

2024-12-26 16:47 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +                                .orElseThrow(IllegalStateException::new);
Почему по одному кусочку еды достаешь, сразу всю собирай

2024-12-26 16:47 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +                        }                        System.out.println("Food collected : " + foodData);
Это корректно и допустимо, но опять масло масленное, потому что ты сделал collectedFood синхронизированной коллекцией

2024-12-26 16:47 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +                            roomsList.remove(roomId);
Как ты можешь модифицировать коллекцию, по которой одновременно итерируешься
Это баг

2024-12-26 19:07 UTC, bormoley1983 commented on src/main/java/school/faang/bjs248526/House.java
> +                        }                        System.out.println("Food collected : " + foodData);
Я думал, что для коллекции надо давать комманды на корректную синхронизацию

2024-12-26 19:08 UTC, bormoley1983 commented on src/main/java/school/faang/bjs248526/House.java
> +                                .orElseThrow(IllegalStateException::new);
Это усложнение задачи и более ли менее описывает реальность

2024-12-26 19:08 UTC, bormoley1983 commented on src/main/java/school/faang/bjs248526/House.java
> +                                .orElseThrow(IllegalStateException::new);
Без этого вообще нет проблем с задачей

2024-12-26 19:09 UTC, bormoley1983 commented on src/main/java/school/faang/bjs248526/House.java
> +                synchronized (room) {
это связано с 
                        foodData = room.getFoodList().stream()
                                .findFirst()
                                .orElseThrow(IllegalStateException::new);
для усложнения задачи и для реальной многопоточки

2024-12-26 19:12 UTC, bormoley1983 commented on src/main/java/school/faang/bjs248526/House.java
> +                Room room = roomsList.get(roomId);
такой подход дает возможность задавать разное количество одновременно обрабатываемых комнат 
при условии первоначальной перетасовки проходит только алгоритм с забиранием всей кды с комнаты.
А тут почти полный рандом. не хватает еще рандома по еде так как сейчас забирается первая со списка

2024-12-26 19:13 UTC, bormoley1983 commented on src/main/java/school/faang/bjs248526/Room.java
> +        synchronized (foodList) {
Согласен, наверное мой косяк. я пока не знаю как реально работает синхронизация по скиску в джаве
аналогично с 
 synchronized (collectedFood) {
                            collectedFood.add(foodData);
                        }                        System.out.println("Food collected : " + foodData);

2024-12-27 18:51 UTC, 20cognosce approved these changes
Принято в общем, всё обложили блокировками, работать будет...

2024-12-27 18:51 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +    Random random = new Random();
private final

2024-12-27 18:51 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +        synchronized (roomsList) {
Ну зачем захватывать лок на всем списке комнат, если у тебя итак все его методы синхронизированы
roomsList = Collections.synchronizedList(new ArrayList<>());

2024-12-27 18:51 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +            for (int i = 0; i < (Math.min(count, Constants.ROOMS)); i++) {
У тебя очень много проблем в методе из-за этой логики

2024-12-27 18:51 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +                        }
Зачем одинаковая проверка в начале и в конце
Почему такой длинный блок кода не декомпозирован

Зачем ты перемешиваешь каждый раз еду в комнате и достаешь одну попавшуюся)))
Сам себе грабли соорудил и сам на них наступил

2024-12-27 18:51 UTC, 20cognosce commented on src/main/java/school/faang/bjs248526/House.java
> +                synchronized (room) {
Велосипеды экстремальные

2024-12-27 18:52 UTC, merged