BJS2-47244, Job Analyzer
CorporationX/god_bless pull request #16091
Opened 2024-12-20 19:07 UTC by Maksim-13

BJS2-47244, Job Analyzer - alpha release

2024-12-23 19:40 UTC, miked4king requested changes

2024-12-23 19:40 UTC, miked4king commented on src/main/java/school/faang/bjs247244/DataAnalyzer.java
> +
лишний отступ в начале метода, поправь в остальных тоже

2024-12-23 19:40 UTC, miked4king commented on src/main/java/school/faang/bjs247244/DataAnalyzer.java
> +                .collect(Collectors.groupingBy(skill -> skill, Collectors.counting()))
.collect является терминальной операцией и ее результат принято сохранять в переменную.
это улучшает читаемость кода и позволит избежать повторных вычислений (если они потребуются).

2024-12-23 19:40 UTC, miked4king commented on src/main/java/school/faang/bjs247244/DataAnalyzer.java
> +                .limit(5)
не критично в рамках данной задачи, но на будущее лучше лимит передавать в параметрах метода, чтобы он был более универсальный

2024-12-23 19:40 UTC, miked4king commented on src/main/java/school/faang/bjs247244/JobStreamProcessor.java
> +    private JobScraper jobScraper = new JobScraper();
для инициализации объекта принято использовать конструктор класса, это позволит создавать экземпляры JobStreamProcessor с разными экземплярами JobScraper, улучшит гибкость и тестируемость кода.
текущая реализация имеет изменяемое состояние, если в будущем понадобится изменить состояние jobScraper, это может привести к ошибкам, если другой код будет полагаться на неизменяемость объекта. хорошей практикой является создание иммутабельных объектов (final)

2024-12-23 19:40 UTC, miked4king commented on src/main/java/school/faang/bjs247244/JobStreamProcessor.java
> +        return processJobs;
1) лишний отступ в начале метода
2) переменная processJobs избыточная, она нигде не используется кроме return, можешь сразу вернуть результат через return (idea должна подсвечивать желтым курсивом, можешь навести курсор на линию, прожать alt + enter и она сама поправит)
3) мы вроде на проекте используем 17 java, можно collect(Collectors.toList()) сократить до .toList()

2024-12-23 19:40 UTC, miked4king commented on src/main/java/school/faang/bjs247244/JobScraper.java
> +    private final Gson gson = new Gson();
а вот тут сделал иммутабельным)
только инициализацию через конструктор стоит сделать, можешь воспользоваться аннотацией lombok @RequiredArgConstructor, чтобы не писать руками

2024-12-23 19:40 UTC, miked4king commented on src/main/java/school/faang/bjs247244/DataAnalyzer.java
> +        List<String> topItemNames = jobs.stream()
аналогичный комментарий с методом getTopSkills

2024-12-23 19:40 UTC, miked4king commented on src/main/java/school/faang/bjs247244/DataAnalyzer.java
> +                //.flatMap(job -> job.getRequirements().stream())
забыл убрать закомментированный код)

2024-12-23 19:40 UTC, miked4king commented on src/main/java/school/faang/bjs247244/Main.java
> +
лишний отступ

2024-12-23 19:40 UTC, miked4king commented on src/main/java/school/faang/bjs247244/Main.java
> +        List<Job> jobs = null;
можно явно не писать = null

2024-12-23 19:40 UTC, miked4king commented on src/main/java/school/faang/bjs247244/DataAnalyzer.java
> +        int step = 50_000;
лучше передавать данный параметр в аргументах метода, чтобы сделать метод более универсальным.

2024-12-23 19:40 UTC, miked4king commented on src/main/java/school/faang/bjs247244/DataAnalyzer.java
> +        Map<String, List<Job>> groupedBySalary = jobs.stream()
избыточная переменная, можешь сразу вернуть через return

2024-12-24 09:55 UTC, Maksim-13 commented on src/main/java/school/faang/bjs247244/DataAnalyzer.java
> +
Ок, исправил.

2024-12-24 09:56 UTC, Maksim-13 commented on src/main/java/school/faang/bjs247244/DataAnalyzer.java
> +                .collect(Collectors.groupingBy(skill -> skill, Collectors.counting()))
Ок, исправил.

2024-12-24 09:56 UTC, Maksim-13 commented on src/main/java/school/faang/bjs247244/DataAnalyzer.java
> +                .limit(5)
Хорошо, исправил.

2024-12-24 09:56 UTC, Maksim-13 commented on src/main/java/school/faang/bjs247244/JobStreamProcessor.java
> +    private JobScraper jobScraper = new JobScraper();
Спасибо, за подробное описание, исправил.

2024-12-24 09:57 UTC, Maksim-13 commented on src/main/java/school/faang/bjs247244/JobStreamProcessor.java
> +        return processJobs;
Ок, исправил.

2024-12-24 09:57 UTC, Maksim-13 commented on src/main/java/school/faang/bjs247244/DataAnalyzer.java
> +                //.flatMap(job -> job.getRequirements().stream())
Ок, исправил.

2024-12-24 09:57 UTC, Maksim-13 commented on src/main/java/school/faang/bjs247244/Main.java
> +
Ок, исправил.

2024-12-24 09:57 UTC, Maksim-13 commented on src/main/java/school/faang/bjs247244/DataAnalyzer.java
> +        int step = 50_000;
Хорошо, исправил.

2024-12-24 09:57 UTC, Maksim-13 commented on src/main/java/school/faang/bjs247244/DataAnalyzer.java
> +        Map<String, List<Job>> groupedBySalary = jobs.stream()
Ок, исправил.

2024-12-24 19:47 UTC, merged