BJS2-48686 [Вы работаете в Microsoft]
CorporationX/god_bless pull request #16135
Opened 2024-12-21 14:10 UTC by Iv-an-s

2024-12-21 19:32 UTC, SemyonKrivtsov requested changes

2024-12-21 19:32 UTC, SemyonKrivtsov commented on src/main/java/school/faang/moduleone/sprintthree/task_43554/MailSender.java
> +            int start = i * batchSize;
Переменные нужно создавать до цикла. Исправь везде по коду.

2024-12-21 20:06 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprintthree/task_43554/MailSender.java
> +            int start = i * batchSize;
Объясни пожалуйста, почему? Зачем нам переменная вне цикла, если мы ее используем только внутри цикла? Не очень понимаю...

2024-12-21 21:07 UTC, SemyonKrivtsov commented on src/main/java/school/faang/moduleone/sprintthree/task_43554/MailSender.java
> +            int start = i * batchSize;
Таким образом пересоздается переменная каждую итерацию цикла. У нее меняется адрес и происходит бессмысленная переаллокация.

2024-12-21 21:13 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprintthree/task_43554/MailSender.java
> +            int start = i * batchSize;
а это точно актуально для примитивов?

2024-12-21 21:30 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprintthree/task_43554/MailSender.java
> +            int start = i * batchSize;
А для объектных ссылок тоже не совсем понятно.. Я это вижу так: мы в стеке создали ссылку, присвоили ей адрес вновь созданного в хипе объекта, нужного только на этой итерации. Итерация закончилась, ссылки в стеке больше нет, на объект больше не ссылаемся, но он нам и не нужен. На следующей итерации в стеке новая ссылка, указывающая на новый объект.. В чем здесь проблема? Память под новый объект будет в любом случае выделяться на каждой итерации...

2024-12-22 11:03 UTC, SemyonKrivtsov commented on src/main/java/school/faang/moduleone/sprintthree/task_43554/MailSender.java
> +            int start = i * batchSize;
У вас каждую итерацию будет заново выделяться память на хранение, для чего это делать каждый раз?

2024-12-22 11:05 UTC, SemyonKrivtsov commented on src/main/java/school/faang/moduleone/sprintthree/task_43554/MailSender.java
> +            int start = i * batchSize;
![image](https://github.com/user-attachments/assets/c1d6093a-c3bf-4f58-9419-8f8035a12398)

2024-12-22 14:55 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprintthree/task_43554/MailSender.java
> +            int start = i * batchSize;
Чтобы не нарушать инкапсуляцию, и создавать переменную ровно там где она будет использоваться. Не расширяя область видимости.
И с памятью так и не понял в чем проблема. Если мы говорим про примитивы, переменная создается в стеке, и после прохода итерации из стека удаляется. Память высвобождается. Вынося переменную за пределы цикла получим прирост производительности?

2024-12-22 18:26 UTC, SemyonKrivtsov commented on src/main/java/school/faang/moduleone/sprintthree/task_43554/MailSender.java
> +            int start = i * batchSize;
Зачем создавать каждый раз, когда можно один?

2024-12-22 18:43 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprintthree/task_43554/MailSender.java
> +            int start = i * batchSize;
Чтобы улучшить читаемость
Чтобы не нарушать инкапсуляцию

2024-12-23 08:16 UTC, merged