Турнир трех волшебников
CorporationX/god_bless pull request #16148
Opened 2024-12-21 16:20 UTC by az3l1t

2024-12-23 11:53 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/task_50708/Tournament.java
> +    private final int hardTime = 6999;
Т.к. эти числа не изменяемые (final) то лучше их сделать константами. Тогда сразу будет понятно, что ими где-то пользуются и не изменяют, по этому и константы.

2024-12-23 12:05 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/task_50708/Tournament.java
> +          case 3, 4, 5 -> makingSomeTasks(school, task, baseChanceHardLevel, hardTime);
На решение задачи по многопоточности не влияет, но если прикинуть, то впринципе можно и не определять  baseChanceEasyLevel, baseChanceHardLevel. Так же можно и от switch избавиться. 

Посто из объекта брать Task брать:
difficulty - это time в методе makingSomeTasks
reward - это baseChance в методе makingSomeTasks

Например:

`
CompletableFuture.supplyAsync(() -> {
            TimeUnit.SECONDS.sleep(task.getDifficulty());
            school.setStudents(school.getStudents().stream()
                    .peek(student -> {
                            student.setPoints(student.getPoints() + task.getReward());
                    })
                    .toList());
`

2024-12-23 12:18 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/task_50708/Task.java
> +        if (difficulty >= 0 && difficulty < 6) {
Если другой разработчик будет создавать этот класс, то велика вероятность, что он задаст значения вне отрезка от 0 до 6, тогда получит ошибку. И что бы создать его правильно, разработчик должен будет пойти в конструктор и изучить его код. Лучше позаботиться о том что бы при любых значениях программа работала.
В таких случаях лучше определить дефолтные значения в виде констант. Например, 
```
private static final int HARD_DIFFICULTY = 6;
private static final int EASY_DIFFICULTY = 0;

if (difficulty < 0) {
    this.difficulty = EASY_DIFFICULTY;
} else if (difficulty >= 6) {
    this.difficulty = HARD_DIFFICULTY;
} else {
    this.difficulty = difficulty;
}
```

2024-12-23 12:21 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/task_50708/School.java
> +                .reduce(0, (sum, student) -> sum + student.getPoints(), Integer::sum);
Попробуй заменить на .reduce на .mapToInt

2024-12-23 12:23 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/task_50708/Main.java
> +        ExecutorService executorService = Executors.newFixedThreadPool(2);
А нужен ли нам executorService?)

2024-12-23 12:46 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/task_50708/Main.java
> +                    System.out.println(beauxbatonsTask.get().getStudents());
Как в итоге понять, кто победил?)
Не понятна логика победы школы. Опиши ее пожалуйста, что бы в консоли появилась строка "Победила команда школы ...."

2024-12-23 12:49 UTC, SnurnicynKonstantin requested changes
Построение многопоточности на:
CompletableFuture.supplyAsync()
allTasks.whenComplete()
allTasks.join()
реализовано верно.

Поправь пожалуйста недочеты.

2024-12-24 17:25 UTC, az3l1t commented on src/main/java/school/faang/task_50708/Main.java
> +        ExecutorService executorService = Executors.newFixedThreadPool(2);
я его везде в целом добавлял, во всех заданиях.
Как я понял - так управление количеством потоков остается на программисте, а не программе.

2024-12-25 13:03 UTC, SnurnicynKonstantin approved these changes

2024-12-25 16:24 UTC, merged