BJS2-48045 [Распределенная армия героев меча и магии]
CorporationX/god_bless pull request #16152
Opened 2024-12-21 17:04 UTC by Iv-an-s

2024-12-21 19:26 UTC, SemyonKrivtsov requested changes

2024-12-21 19:26 UTC, SemyonKrivtsov commented on src/main/java/school/faang/moduleone/sprintthree/task_43550/Army.java
> +            PowerCalculator calculator = new PowerCalculator(unit);
Переменные нужно создавать до цикла

2024-12-21 19:26 UTC, SemyonKrivtsov commented on src/main/java/school/faang/moduleone/sprintthree/task_43550/Army.java
> +            PowerCalculator calculator = new PowerCalculator(unit);
Исправь везде по коду

2024-12-21 19:26 UTC, SemyonKrivtsov commented on src/main/java/school/faang/moduleone/sprintthree/task_43550/Main.java
> +        army.addUnit(new Archer(25));   // считаем в потоке 1
Лучше не использовать комментарии в коде, хороший код сам говорит за себя

2024-12-27 17:01 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprintthree/task_43550/Main.java
> +        army.addUnit(new Archer(25));   // считаем в потоке 1
Убрал комментарии

2024-12-27 17:07 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprintthree/task_43550/Army.java
> +            PowerCalculator calculator = new PowerCalculator(unit);
Не стал выносить переменную за пределы цикла, т.к. не увидел в этом необходимости. 
К данной переменной, после того как цикл отработает, обращений не будет. 
Этой переменной на каждой итерации все равно будет переназначаться новый объект. Т.е. память не сэкономим. (А если бы созданные в цикле объекты PowerCalculator мы бы не сохраняли в листе - еще бы и потратили память, за счет хранения бесполезной ссылки на объект в хипе.)

2024-12-27 18:26 UTC, merged