Турнир трех волшебников
CorporationX/god_bless pull request #16166
Opened 2024-12-21 20:03 UTC by almigor1

2024-12-25 21:17 UTC, mysosnovskaya requested changes

2024-12-25 21:17 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint4/task51100/Main.java
> +        schoolTasks.add(tournament.startTask(schools.get(0), tasks.get(0)));
Может в цикле сделать? i от 0 до 4 (или даже до schools.size())

2024-12-25 21:17 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint4/task51100/Main.java
> +        Future<Void> allTask = CompletableFuture.allOf(schoolTasksArray);
Вот тут хорошо преобразование из списка в Future получилось 👍

2024-12-25 21:17 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint4/task51100/Main.java
> +            allTask.get();
В get лучше задать время, которое ты готов подождать. А то мало ли, какой-то поток ушел в бесконечный цикл и ты его никогда не дождешься)

2024-12-25 21:17 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint4/task51100/model/Student.java
> +        synchronized (lock) {
Точно ли нужен отдельный лок? Нельзя просто метод синхронизированным сделать?
А ещё - не получится ли реализовать это через AtomicInteger?)

2024-12-28 11:36 UTC, almigor1 commented on src/main/java/school/faang/sprint4/task51100/Main.java
> +        Future<Void> allTask = CompletableFuture.allOf(schoolTasksArray);
ой, а я по привычке переправил.
тут же по сути тоже первый элемент массива ушел? хотя тоже работало

2024-12-28 18:04 UTC, mysosnovskaya approved these changes

2024-12-28 18:04 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint4/task51100/model/Student.java
> +        return this.points.get();
this можно не писать

2024-12-28 18:04 UTC, merged