BJS2-48689:  Вы работаете в Microsoft!
CorporationX/god_bless pull request #16165
Opened 2024-12-21 19:27 UTC by viktor-ovod

2024-12-21 19:35 UTC, SemyonKrivtsov requested changes

2024-12-21 19:35 UTC, SemyonKrivtsov commented on src/main/java/school/faang/sprint3/bjs248689/MailSender.java
> +    public static void main(String[] args) throws InterruptedException {
Метод не должен вызывать исключения. Нужно обработать их внутри.

2024-12-21 19:35 UTC, SemyonKrivtsov commented on src/main/java/school/faang/sprint3/bjs248689/MailSender.java
> +            int start = i * batchSize;
Переменные нужно создавать до цикла. Исправь везде по коду.

2024-12-21 22:00 UTC, viktor-ovod commented on src/main/java/school/faang/sprint3/bjs248689/MailSender.java
> +    public static void main(String[] args) throws InterruptedException {
ок, обработал исключения внутри метода

это всегда так у метода main() не должны вызываться исключения?

2024-12-21 22:02 UTC, viktor-ovod commented on src/main/java/school/faang/sprint3/bjs248689/MailSender.java
> +            int start = i * batchSize;
вынес за цикл инициализацию двух переменных: start и end

2024-12-22 10:59 UTC, SemyonKrivtsov commented on src/main/java/school/faang/sprint3/bjs248689/MailSender.java
> +    public static void main(String[] args) throws InterruptedException {
Ваше приложение в будущем должно оставаться устойчивым к неожиданным ситуациям. В данном случае точка входа в приложение main, в будущем может быть другой, но суть остается той же.

2024-12-22 10:59 UTC, merged