Task they were very nice but extremely poor
CorporationX/god_bless pull request #16215
Opened 2024-12-22 12:36 UTC by sergeybabaev96

2024-12-22 14:22 UTC, SemyonKrivtsov requested changes

2024-12-22 14:22 UTC, SemyonKrivtsov commented on src/main/java/school/faang/bjs248493/Chore.java
> +            Thread.sleep(3000);
Лучше оперировать константами, а не конкретными значениями

2024-12-22 14:22 UTC, SemyonKrivtsov commented on src/test/java/ChoreTest.java
> +    void testExecutorServiceCompletedAllTasks() throws InterruptedException {
Нет модификатора

2024-12-23 20:57 UTC, sergeybabaev96 commented on src/test/java/ChoreTest.java
> +    void testExecutorServiceCompletedAllTasks() throws InterruptedException {
![Uploading iScreen Shoter - 20241223235454377.jpg…]()

2024-12-23 20:58 UTC, sergeybabaev96 commented on src/test/java/ChoreTest.java
> +    void testExecutorServiceCompletedAllTasks() throws InterruptedException {
![iScreen Shoter - 20241223235454377](https://github.com/user-attachments/assets/c659f37c-7728-4348-afbf-dbe34a097d5b)

2024-12-24 07:52 UTC, merged