Task-BJS2-49241 Bro Force!
CorporationX/god_bless pull request #16221
Opened 2024-12-22 13:12 UTC by senty8

2024-12-23 19:50 UTC, mysosnovskaya requested changes

2024-12-23 19:50 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_3/task_49241/Game.java
> +            synchronized (livesLock) {
Оригинально, но есть риск в будущем столкнуться с deadlock, если где-то в другом методе этого класса порядок блокировки будет другой. Поэтому лучше не рисковать и сразу разделить блокировки - сначала одну, потом вторую, последовательно

2024-12-23 19:50 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_3/task_49241/Game.java
> +    }
А где метод gameOver? По условию должен быть

2024-12-24 13:24 UTC, mysosnovskaya requested changes

2024-12-24 13:24 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_3/task_49241/Game.java
> +        Thread.currentThread().interrupt();
Вот эту строчку не поняла - как связаны окончание игры и прерывание потока? Поток ведь продолжает свою работу, с ним всё в порядке. Похоже, что ты пытаешься решить задачу остановки игры непредназначенными для этого средствами. Давай как-то по-другому скажем другим потокам о том, что игра закончилась.

2024-12-24 14:15 UTC, senty8 commented on src/main/java/school/faang/sprint_3/task_49241/Game.java
> +        Thread.currentThread().interrupt();
Прошлая логика была скорее к окончанию игры конкретного игрока, а реализовать конец игры по условию не возможно, ибо я перенес жизни в классы игроков, и соответственно игра просто считает количество потраченных жизней, а не хранит максимальное их количество. Поэтому просто сделал как бы подведение итогов.

2024-12-24 18:34 UTC, mysosnovskaya approved these changes

2024-12-24 18:34 UTC, merged