Task-BJS2-48822 Железный трон любой ценой
CorporationX/god_bless pull request #16237
Opened 2024-12-22 16:39 UTC by senty8

2024-12-23 19:04 UTC, mysosnovskaya requested changes

2024-12-23 19:04 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_3/task_48822/House.java
> +                return null;
А точно нужно return делать? Может быть опять встать в ожидание?

2024-12-23 19:04 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_3/task_48822/Main.java
> +            Thread.currentThread().interrupt();
Очень круто работаешь с прерыванием и остановкой потоков 👍

2024-12-23 19:04 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_3/task_48822/User.java
> +        // но без синхронизации тут получается неправильный вывод
Что значит неправильный? Можешь пример привести?

2024-12-23 19:04 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_3/task_48822/House.java
> +        String availableRole = availableRoles.entrySet()
Я бы этот стрим вынесла в отдельный приватный метод, чтобы код стал ещё легче

2024-12-24 07:33 UTC, senty8 commented on src/main/java/school/faang/sprint_3/task_48822/House.java
> +                return null;
ну если кто-то решил прервать выполнение потока, то логичнее завершить его выполнение в кратчайшие сроки, зачем продолжать ожидать. Или я что-то не понимаю

2024-12-24 07:36 UTC, senty8 commented on src/main/java/school/faang/sprint_3/task_48822/User.java
> +        // но без синхронизации тут получается неправильный вывод
Правильный вывод:

User User 4 joined house House(name=House 1, availableRoles={Lord=false, Archer=true, King=true, Swordsman=true}) with role Lord
User User 3 joined house House(name=House 1, availableRoles={Lord=false, Archer=false, King=true, Swordsman=true}) with role Archer
User User 1 joined house House(name=House 1, availableRoles={Lord=false, Archer=false, King=false, Swordsman=true}) with role King
User User 2 joined house House(name=House 1, availableRoles={Lord=false, Archer=false, King=false, Swordsman=false}) with role Swordsman

А именно все роли разбираются по одной, а в неправильном варианте, в логике все роли разбираются по одной, а вот в консоль выводится сразу конечная стадия логики. Например.

User User 4 joined house House(name=House 1, availableRoles={Lord=false, Archer=false, King=false, Swordsman=false}) with role Lord
User User 3 joined house House(name=House 1, availableRoles={Lord=false, Archer=false, King=false, Swordsman=false}) with role Archer
User User 1 joined house House(name=House 1, availableRoles={Lord=false, Archer=false, King=false, Swordsman=false}) with role King
User User 2 joined house House(name=House 1, availableRoles={Lord=false, Archer=false, King=false, Swordsman=false}) with role Swordsman

2024-12-24 19:04 UTC, mysosnovskaya approved these changes

2024-12-24 19:04 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_3/task_48822/User.java
> +        // но без синхронизации тут получается неправильный вывод
А, ну видимо без синхронизации роли разбирают быстрее, чем отрабатывает вывод в консоль. Допустимо так оставить)

2024-12-24 19:04 UTC, merged