Solve task_48951
CorporationX/god_bless pull request #16245
Opened 2024-12-22 18:22 UTC by shamshaev

2024-12-24 20:46 UTC, mysosnovskaya requested changes

2024-12-24 20:46 UTC, mysosnovskaya commented on src/main/java/school/faang/task_48951/GooglePhotosAutoUploader.java
> +            if (photosToUpload.isEmpty()) {
Здесь лучше будет while, т.к. поток может выйти из ожидания не только по notify и после выхода лучше убедиться, что для него есть работа

2024-12-24 20:46 UTC, mysosnovskaya commented on src/main/java/school/faang/task_48951/GooglePhotosAutoUploader.java
> +                    log.warn("Thread was interrupted", e);
Если произошло прерывание, то нужно, во-первых, восстановить флаг прерывания, а во-вторых, завершить работу метода
https://www.baeldung.com/java-interrupted-exception#2-restore-the-interrupt

2024-12-24 20:46 UTC, mysosnovskaya commented on src/main/java/school/faang/task_48951/GooglePhotosAutoUploader.java
> +    public void uploadPhotos() {
Метод должен быть приватным, наверное?

2024-12-24 20:46 UTC, mysosnovskaya commented on src/main/java/school/faang/task_48951/Main.java
> +        Runnable[] tasks = new Runnable[] {
А почему через массив, а не через список?)

2024-12-24 20:46 UTC, mysosnovskaya commented on src/main/java/school/faang/task_48951/Main.java
> +                () -> loader.startAutoUpload()
Этот поток должен работать непрерывно. Т.е. он существует как бы в фоне. Большую часть времени спит, но если его разбудили, то идет выгружать фотографии и опять засыпает до следующего пробуждения. А у тебя поток завершится сразу же после обработки первого notify

2024-12-25 17:01 UTC, shamshaev commented on src/main/java/school/faang/task_48951/GooglePhotosAutoUploader.java
> +    public void uploadPhotos() {
Ок

2024-12-25 17:03 UTC, shamshaev commented on src/main/java/school/faang/task_48951/GooglePhotosAutoUploader.java
> +                    log.warn("Thread was interrupted", e);
Видел эту статью. Правда саппорт ревьювер сказал залогировать, я и залогировал (изначально просто писал throw  в сигнатуре метода).

2024-12-25 17:15 UTC, shamshaev commented on src/main/java/school/faang/task_48951/Main.java
> +        Runnable[] tasks = new Runnable[] {
Смотрел примеры решений в интернете с многопоточностью для задач подобных самым первым здесь, почти везде массивы были. Я спросил у ChatGPT почему массивы, а не списки? Он ответил, что массивы эффективнее и быстрее и дал саммари: известно количество потоков - используй массивы, неизвестно - список.

2024-12-25 18:05 UTC, shamshaev commented on src/main/java/school/faang/task_48951/GooglePhotosAutoUploader.java
> +            if (photosToUpload.isEmpty()) {
Понял.

2024-12-25 20:27 UTC, mysosnovskaya commented on src/main/java/school/faang/task_48951/GooglePhotosAutoUploader.java
> +                    log.warn("Thread was interrupted", e);
Логировать тоже хорошо)

2024-12-25 20:28 UTC, mysosnovskaya commented on src/main/java/school/faang/task_48951/Main.java
> +        Runnable[] tasks = new Runnable[] {
Ок, принимается. Я в таком ключе не думала, т.к. у нас здесь это ни на что не повлияет, но звучит логично) Спасибо, что разобрался в вопросе!

2024-12-25 20:29 UTC, mysosnovskaya approved these changes

2024-12-25 20:29 UTC, merged