BJS2-48707 [Mice are very nice]
CorporationX/god_bless pull request #16254
Opened 2024-12-22 19:14 UTC by Iv-an-s

2024-12-24 20:31 UTC, mysosnovskaya requested changes

2024-12-24 20:31 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/sprintthree/task_43556/House.java
> +        Random random = new Random();
Лучше сделать полем класса, чтобы не создавать каждый раз при вызове метода

2024-12-24 20:31 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/sprintthree/task_43556/House.java
> +                Room room = rooms.get(roomIndex);
Между проверкой, что комнаты есть, и получением комнаты прошло определенное время и другой поток уже мог эту же комнату из списка забрать. Не безопасно получается

2024-12-24 20:31 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/sprintthree/task_43556/House.java
> +        for (int i = 0; i < 2; i++) {
2 - в константы

2024-12-24 20:31 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/sprintthree/task_43556/House.java
> +    @Setter
Почему через сеттер? Лучше один раз передать в конструктор, а поле сделать финальным

2024-12-24 20:31 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/sprintthree/task_43556/Main.java
> +        for (int i = 0; i < 5; i++) {
5 - в константы

2024-12-24 20:31 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/sprintthree/task_43556/Main.java
> +        executor.shutdown();
Нужно ещё через awaitTermination дождаться завершения всех потоков, а если это не удалось, то завершить пул потоков принудительно через shutdownNow

2024-12-24 20:31 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/sprintthree/task_43556/House.java
> +                .map(room -> room.getFoods().size())
Можно обойтись без map, если вызывать у room метод hasFood

2024-12-27 21:00 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprintthree/task_43556/House.java
> +        Random random = new Random();
Поправил

2024-12-27 21:01 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprintthree/task_43556/House.java
> +                Room room = rooms.get(roomIndex);
убрал проверку в блок синхронизации

2024-12-27 21:01 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprintthree/task_43556/House.java
> +        for (int i = 0; i < 2; i++) {
сделал

2024-12-27 21:01 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprintthree/task_43556/House.java
> +    @Setter
Да, странно сделал :) Поправил

2024-12-27 21:02 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprintthree/task_43556/Main.java
> +        for (int i = 0; i < 5; i++) {
вынес

2024-12-27 21:02 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprintthree/task_43556/Main.java
> +        executor.shutdown();
добавил

2024-12-27 21:02 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprintthree/task_43556/House.java
> +                .map(room -> room.getFoods().size())
Точно! Сделал

2024-12-28 17:59 UTC, mysosnovskaya approved these changes

2024-12-28 17:59 UTC, merged