Task-BJS2-49209 Telegram-бот
CorporationX/god_bless pull request #16265
Opened 2024-12-22 20:05 UTC by senty8

2024-12-22 20:06 UTC, senty8 commented
Не понимаю как это время работает, они вроде ждут до конца, но все равно иногда получаются несостыковки в несколько миллисекунд и оно. отправляет больше, чем 5 сообщений в секунду

2024-12-24 19:41 UTC, mysosnovskaya requested changes

2024-12-24 19:41 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_3/task_49209/Main.java
> +    private static final int Number_OF_MESSAGES = 1000;
Стиль наименования нужно поправить)

2024-12-24 19:41 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_3/task_49209/TelegramBot.java
> +        while (true) {
Очень неожиданно в методе sendMessage видеть while (true). Мы же точно знаем, если вышли из ожидания, значит нужное время прошло и можно обрабатывать запрос

2024-12-24 19:41 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_3/task_49209/TelegramBot.java
> +                requestCounter = 0;
Здесь можно поставить `requestCounter = 1;` (текущее сообщение сразу посчитать отправленным) и после этого уже можно больше ничего не проверять, сразу выходить из метода

2024-12-24 19:41 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_3/task_49209/TelegramBot.java
> +            if (requestCounter < REQUEST_LIMIT) {
А здесь можно сделать `while (requestCounter >= REQUEST_LIMIT)` ждать, а как выйдем из цикла - увеличивать счетчик

2024-12-25 21:35 UTC, mysosnovskaya approved these changes

2024-12-25 21:35 UTC, merged