BJS2-48085:  Распределенная армия героев
CorporationX/god_bless pull request #16278
Opened 2024-12-22 23:43 UTC by viktor-ovod

2024-12-23 08:20 UTC, SemyonKrivtsov requested changes

2024-12-23 08:20 UTC, SemyonKrivtsov commented on src/main/java/school/faang/sprint3/bjs248085/Army.java
> +    public int calculateTotalPower() throws InterruptedException {
Метод не должен вызывать исключения, нужно обработать внутри

2024-12-23 08:20 UTC, SemyonKrivtsov commented on src/main/java/school/faang/sprint3/bjs248085/Main.java
> +    public static void main(String[] args) throws InterruptedException {
Аналогично

2024-12-24 18:40 UTC, viktor-ovod commented on src/main/java/school/faang/sprint3/bjs248085/Army.java
> +    public int calculateTotalPower() throws InterruptedException {
это любой метод не должен вызывать исключения или только в этих задачах? то-есть так лучше стараться так не обрабатывать исключения?

2024-12-24 19:59 UTC, viktor-ovod commented
готово 👌🏼

2024-12-24 20:03 UTC, SemyonKrivtsov commented on src/main/java/school/faang/sprint3/bjs248085/Army.java
> +    public int calculateTotalPower() throws InterruptedException {
В целом ваше приложение должно быть отказоустойчивым, в случае возникновения исключительных ситуаций лучше логировать это.

2024-12-24 20:03 UTC, merged