Solve task_49681
CorporationX/god_bless pull request #16324
Opened 2024-12-23 14:06 UTC by shamshaev

2024-12-24 21:16 UTC, mysosnovskaya requested changes

2024-12-24 21:16 UTC, mysosnovskaya commented on src/main/java/school/faang/task_49681/Boss.java
> +        if (currentPlayers >= maxPlayers) {
Лучше через while, т.е. поток из wait может выйти не только из-за notify, а в твоей текущей реализации и по после прерывания поток не проверит условие currentPlayers >= maxPlayers и продолжит работу так, будто оно верно

2024-12-24 21:16 UTC, mysosnovskaya commented on src/main/java/school/faang/task_49681/Boss.java
> +                log.warn("Thread was interrupted", e);
Лучше завершить работу метода

2024-12-24 21:16 UTC, mysosnovskaya commented on src/main/java/school/faang/task_49681/Main.java
> +        Player[] players = new Player[] {new Player("John"), new Player("Mike"),
Интересно, почему массив, а не List.of

2024-12-24 21:16 UTC, mysosnovskaya commented on src/main/java/school/faang/task_49681/Main.java
> +    }
А ещё нужно пул потоков корректно завершить

2024-12-25 19:15 UTC, shamshaev commented on src/main/java/school/faang/task_49681/Main.java
> +    }
Ok

2024-12-25 19:16 UTC, shamshaev commented on src/main/java/school/faang/task_49681/Main.java
> +        Player[] players = new Player[] {new Player("John"), new Player("Mike"),
Ответил в другой задаче

2024-12-25 20:52 UTC, mysosnovskaya requested changes

2024-12-25 20:52 UTC, mysosnovskaya commented on src/main/java/school/faang/task_49681/Main.java
> +    }
Я имела в виду через awaitTermination, а то так довольно радикально получается)

2024-12-26 20:34 UTC, mysosnovskaya approved these changes

2024-12-26 20:34 UTC, merged