Собираем заказы в Amazon
CorporationX/god_bless pull request #16351
Opened 2024-12-23 20:43 UTC by almigor1

2024-12-25 21:03 UTC, mysosnovskaya requested changes

2024-12-25 21:03 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint4/task50100/OrderProcessor.java
> +        CompletableFuture<Void> voidResults = CompletableFuture.allOf((CompletableFuture<Void>) results.toArray()[0]);
Здесь не поняла, почему `results.toArray()[0]`? Это ведь только первый элемент будет? А нам нужны все объекты из массива

2024-12-25 21:03 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint4/task50100/OrderProcessor.java
> +    public static final int TIME_TO_PROCESS = 1000;
private? Не представляю, кому эта константа снаружи может потребоваться)

2024-12-27 13:29 UTC, almigor1 commented on src/main/java/school/faang/sprint4/task50100/OrderProcessor.java
> +        CompletableFuture<Void> voidResults = CompletableFuture.allOf((CompletableFuture<Void>) results.toArray()[0]);
да где то такой способ нашел, вроде даже работает.
Нашел другой способ, переделал

2024-12-27 19:21 UTC, mysosnovskaya approved these changes

2024-12-27 19:21 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint4/task50100/OrderProcessor.java
> +        CompletableFuture.allOf(results.toArray(new CompletableFuture[results.size()])).join();
Ага, так хорошо)

2024-12-27 19:21 UTC, merged