BJS2-48999, Mice are very nice
CorporationX/god_bless pull request #16373
Opened 2024-12-24 09:39 UTC by Maksim-13

BJS2-48999, Mice are very nice - alpha release

2024-12-24 21:28 UTC, mysosnovskaya requested changes

2024-12-24 21:28 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs248999/Food.java
> +    private String name;
final?

2024-12-24 21:28 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs248999/House.java
> +    private CountDownLatch countDownLatch;
А почему через setter? Лучше через конструктор передать, а поле финальным сделать

2024-12-24 21:28 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs248999/House.java
> +        for (int i = 1; i < 9; i++) {
9 - в константы (или даже в конструктор?)

2024-12-24 21:28 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs248999/House.java
> +                room.unLock();
Это лучше поместить в finally, т.к. если вдруг выше произойдет исключение, то мы unlock не сделаем

2024-12-24 21:28 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs248999/House.java
> +        for (int i = 0; i < 2; i++) {
2 нужно куда-то вынести. В константы, в поля, в параметры метода - куда угодно, лишь бы было понятно, что это за двойка такая)

2024-12-24 21:28 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs248999/Main.java
> +        System.out.println("Еда в доме собрана!");
Нужно дождаться завершения всех потоков через awaitTermination, а если за отведенное время они не завершились, то вызвать принудительное shutdownNow у executor

2024-12-24 21:28 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs248999/Officiant.java
> +    public Officiant(House house) {
А конструктор от ломбока не подойдет?)

2024-12-24 21:28 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs248999/Room.java
> +        IntStream.range(0, 6)
Оригинально 👍

2024-12-24 21:28 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs248999/Room.java
> +    public boolean isClear() {
Это хорошо с точки зрения инкапсуляции (что не делаешь в стороннем классе room.getFoods().isEmpty())

2024-12-25 07:41 UTC, Maksim-13 commented on src/main/java/school/faang/bjs248999/Food.java
> +    private String name;
Ок, исправил.

2024-12-25 07:48 UTC, Maksim-13 commented on src/main/java/school/faang/bjs248999/House.java
> +    private CountDownLatch countDownLatch;
Я так и хотел, но я же смотрел видео подсказку и это содрал из видео, и вот такая логика, что нужно указать кол-во комнат для CountDownLatch, а они будут известны после создания экземпляра объекта House )) поэтому тупо через конструктор не получается, наверняка есть решение лучше )

2024-12-25 07:51 UTC, Maksim-13 commented on src/main/java/school/faang/bjs248999/House.java
> +        for (int i = 1; i < 9; i++) {
Ок, исправил.

2024-12-25 07:56 UTC, Maksim-13 commented on src/main/java/school/faang/bjs248999/House.java
> +                room.unLock();
Ок, исправил.

2024-12-25 07:59 UTC, Maksim-13 commented on src/main/java/school/faang/bjs248999/House.java
> +        for (int i = 0; i < 2; i++) {
Ок, исправил.

2024-12-25 09:35 UTC, Maksim-13 commented on src/main/java/school/faang/bjs248999/Main.java
> +        System.out.println("Еда в доме собрана!");
Ок, исправил.

2024-12-25 09:36 UTC, Maksim-13 commented on src/main/java/school/faang/bjs248999/Officiant.java
> +    public Officiant(House house) {
Ок, исправил )

2024-12-25 20:20 UTC, mysosnovskaya requested changes

2024-12-25 20:20 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs248999/House.java
> +    private CountDownLatch countDownLatch;
Комнаты тоже можно в main создать и списком в конструктор к House передать. Как тебе такой вариант?
Оно в общем-то сейчас и странно выглядит, что сам дом отвечает за создание комнат. Обычно всё создание происходит снаружи, чтобы было максимально гибко. А сейчас получается, что я могу создать комнаты только с номерами 100, 101, 102 и так далее, а если 200 хочу? А если вообще хочу другую логику по заданию номеров? А если для части домов нужна одна логика, а для другой части - другая?... Ну в общем, предлагаю вынести)

2024-12-26 20:13 UTC, merged