Solve task_49290
CorporationX/god_bless pull request #16397
Opened 2024-12-24 15:02 UTC by shamshaev

2024-12-24 21:03 UTC, mysosnovskaya requested changes

2024-12-24 21:03 UTC, mysosnovskaya commented on src/main/java/school/faang/task_49290/Main.java
> +            Random random = new Random();
Лучше вынести в поле класса или хотя бы в переменные в начале метода, чтобы не создавать объект на каждой итерации цикла

2024-12-24 21:03 UTC, mysosnovskaya commented on src/main/java/school/faang/task_49290/Main.java
> +        service.shutdown();
Нужно ещё через awaitTermination дождаться завершения потоков и если они не завершились за отведенное время, то вызвать принудительное shutdownNow

2024-12-24 21:03 UTC, mysosnovskaya commented on src/main/java/school/faang/task_49290/Main.java
> +                log.warn("Main thread was interrupted", e);
Если такое случилось, то нужно завершить работу программы

2024-12-26 11:26 UTC, shamshaev commented on src/main/java/school/faang/task_49290/Main.java
> +        service.shutdown();
В примерах обычно видел задежку в 60-80 секунд, но не хочется создавать доп переменную, пусть будет 2 секунды

2024-12-26 11:26 UTC, shamshaev commented on src/main/java/school/faang/task_49290/Main.java
> +            Random random = new Random();
детский косяк

2024-12-26 11:54 UTC, shamshaev commented on src/main/java/school/faang/task_49290/Main.java
> +                log.warn("Main thread was interrupted", e);
В задачке Supercow был идентичный код, но там ты ничего не сказала. А какая разница между ситуацией здесь и там?

И вообще хотелось бы понять алгоритм правильный. Как я понимаю из материалов лекций, твоих комментариев и ChatGPT получается что:
1) Если exception вылетает в доп потоке, то восстанавливаем флаг прерывания через Thread.currentThread().interrupt()
2) Если вылетает в главном потоке при ожидании результата доп потока, то так делать нельзя, чтобы не остановить главный поток. Получается надо сделать обработку (повторный запуск, дефолтные значения)
3) Если вылетает при использовании метода sleep(), который как я понимаю в продакт коде использовать нельзя, чтобы не скрывать потенциальные проблемы, но здесь в учебных целях мы используем его для имитации работы или ожидания, то как обрабатывать?
4) Когда именно логировать? ChatGPT говорит не замалчивать, либо действия, либо логирование. Но если действие прописано, то можно не логировать или как?

2024-12-26 20:33 UTC, mysosnovskaya requested changes

2024-12-26 20:33 UTC, mysosnovskaya commented on src/main/java/school/faang/task_49290/Main.java
> +                log.warn("Main thread was interrupted", e);
В этом случае я ошиблась с формулировкой немного (извиняюсь): нужно прервать работу цикла while. Почему так: каждый раз, когда мы получаем InterruptedException, мы должны завершать работу потоков. Если мы получили это исключение внутри какого-то не main метода, то в нём нужно сделать return (чтобы из метода выйти). Если получили в главном потоке (в main), то нужно обработать это исключение так, чтобы работа всей программы успешно завершилась. Именно в твоем случае если поймали InterruptedException, то следующие итерации цикла продолжать не нужно. Надо переходить к service.shutdown(); и далее. В задаче Supercow цикла не было, поэтому там в любом случае был переход к остановке пула потоков, поэтому и не было комментария от меня :)

1. Верно
2. Да. Тут обработкой скорее будет логгирование и переход к корректному завершению всей программы (то, о чем выше пишу)
3. Прерывание может случиться, например, когда нашу программу решили остановить. В этом случае неважно, что она делала, просто спала или ожидала чего-то через wait - её нужно остановить. Поэтому обработка этого исключения должна быть, как я выше описываю. Переходим к завершению программы (закрываем все используемые ресурсы, печатаем "пока-пока" на экран и завершаемся).
4. Ошибки всегда лучше залоггировать. Любой catch как правило начинается с логгирования, чтобы тот, кто запустил программу, знал, что там происходит.

2024-12-27 19:18 UTC, mysosnovskaya approved these changes

2024-12-27 19:19 UTC, merged