BJS2-49133, Google Photo sync
CorporationX/god_bless pull request #16393
Opened 2024-12-24 14:32 UTC by Maksim-13

BJS2-49133, Google Photo sync - alpha release

2024-12-24 20:56 UTC, mysosnovskaya requested changes

2024-12-24 20:56 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249133/GooglePhotosAutoUploader.java
> +        this.photosToUpload = new ArrayList<>();
Почему lock инициализируется сразу при объявлении, а список - в конструкторе?) Предлагаю единообразно сделать

2024-12-24 20:56 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249133/GooglePhotosAutoUploader.java
> +                    throw new RuntimeException(e);
Лучше ещё восстановить флаг прерывания
https://www.baeldung.com/java-interrupted-exception#2-restore-the-interrupt

2024-12-24 20:56 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249133/GooglePhotosAutoUploader.java
> +            lock.notify(); // Уведомляем поток, что появились новые фотографии
Комментарии не нужны, код сам за себя говорит

2024-12-24 20:56 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249133/Main.java
> +        Thread uploadThread = new Thread(autoUploader::startAutoUpload);
Этот поток должен работать непрерывно. Т.е. он существует как бы в фоне. Большую часть времени спит, но если его разбудили, то идет выгружать фотографии и опять засыпает до следующего пробуждения. А у тебя поток завершится сразу же после обработки первого notify. Нужно сделать такой "пинг-понг": один поток загружает фотографию, а uploadThread подхватывает её, потом второй поток загружает другую фотографию, а uploadThread опять её обрабатывает

2024-12-24 20:56 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249133/Main.java
> +            autoUploader.onNewPhotoAdded("photo1.jpg");
Лучше побольше фотографий загрузить в целях тестирования

2024-12-25 11:04 UTC, Maksim-13 commented on src/main/java/school/faang/bjs249133/GooglePhotosAutoUploader.java
> +        this.photosToUpload = new ArrayList<>();
Ок, исправил.

2024-12-25 11:04 UTC, Maksim-13 commented on src/main/java/school/faang/bjs249133/GooglePhotosAutoUploader.java
> +                    throw new RuntimeException(e);
Ок, исправил.

2024-12-25 11:04 UTC, Maksim-13 commented on src/main/java/school/faang/bjs249133/GooglePhotosAutoUploader.java
> +            lock.notify(); // Уведомляем поток, что появились новые фотографии
Ок, исправил.

2024-12-25 11:04 UTC, Maksim-13 commented on src/main/java/school/faang/bjs249133/Main.java
> +        Thread uploadThread = new Thread(autoUploader::startAutoUpload);
Ок, исправил.

2024-12-25 11:05 UTC, Maksim-13 commented on src/main/java/school/faang/bjs249133/Main.java
> +            autoUploader.onNewPhotoAdded("photo1.jpg");
Ок, исправил.

2024-12-25 20:34 UTC, mysosnovskaya requested changes

2024-12-25 20:34 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249133/Main.java
> +            future.get(SERVICE_OPENING_HOURS, TimeUnit.SECONDS);
Уже темы 4 спринта, молодец 👍

2024-12-25 20:34 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249133/GooglePhotosAutoUploader.java
> +    private boolean isServiceTurnOn;
Что-то я не увидела, чтобы это поле где-то менялось. Но вообще так оно и не будет работать - ещё нужен volotile (это тема 4 спринта). Поэтому либо давай добавим volotile, если уже знаком, либо сделаем просто while (true), т.к. сейчас по сути так и есть

2024-12-26 20:13 UTC, mysosnovskaya approved these changes

2024-12-26 20:13 UTC, merged