BJS2-49833, Supercow
CorporationX/god_bless pull request #16401
Opened 2024-12-24 16:03 UTC by Maksim-13

BJS2-49833, Supercow - alpha release

2024-12-24 21:20 UTC, mysosnovskaya requested changes

2024-12-24 21:20 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249833/Main.java
> +        Thread thread1 = new Thread(() -> {
Лучше через пул потоков :)

2024-12-24 21:20 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249833/Player.java
> +    public void startBattle(Boss boss) throws InterruptedException {
InterruptedException можно обработать здесь, чтобы потом не дублировать обработку в каждом потоке отдельно

2024-12-25 07:23 UTC, Maksim-13 commented on src/main/java/school/faang/bjs249833/Main.java
> +        Thread thread1 = new Thread(() -> {
Ок, исправил

2024-12-25 07:24 UTC, Maksim-13 commented on src/main/java/school/faang/bjs249833/Player.java
> +    public void startBattle(Boss boss) throws InterruptedException {
Ок, исправил

2024-12-25 20:55 UTC, mysosnovskaya approved these changes

2024-12-25 20:55 UTC, merged