BJS2-49633, BroForce
CorporationX/god_bless pull request #16411
Opened 2024-12-24 18:40 UTC by Maksim-13

BJS2-49633, BroForce - alpha release

2024-12-24 21:08 UTC, mysosnovskaya requested changes

2024-12-24 21:08 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249633/Game.java
> +            if (earnedPoints) {
Лучше сначала проверку сделать, а потом блокировку. Так эффективнее просто =)

2024-12-24 21:08 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249633/Game.java
> +            if (lostLife) {
Аналогично

2024-12-24 21:08 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249633/Main.java
> +            boolean lostLife = Math.random() > CHANCE_LOSE_LIFE;
Хорошо с константами 👍

2024-12-24 21:08 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249633/Game.java
> +    public boolean update(boolean earnedPoints, boolean lostLife) {
Названия параметров earnedPoints lostLife больше для целых чисел подходят, а если это boolean, то лучше называть через is - isPointsEarned и isLifeLost

2024-12-25 09:47 UTC, Maksim-13 commented on src/main/java/school/faang/bjs249633/Game.java
> +    public boolean update(boolean earnedPoints, boolean lostLife) {
Я так и хотел, но я же смотрел видео подсказку и это содрал из видео, и вот такая логика, что нужно указать кол-во комнат для CountDownLatch, а они будут известны после создания экземпляра объекта House )) поэтому тупо через конструктор не получаетс
![Bro Force-example](https://github.com/user-attachments/assets/a68962ab-c411-4d7f-8e6b-ce0ce5f2a774)
я, наверняка есть решение лучше )

2024-12-25 09:48 UTC, Maksim-13 commented on src/main/java/school/faang/bjs249633/Main.java
> +            boolean lostLife = Math.random() > CHANCE_LOSE_LIFE;
Ок, исправил.

2024-12-25 09:48 UTC, Maksim-13 commented on src/main/java/school/faang/bjs249633/Game.java
> +            if (lostLife) {
Ок, исправил.

2024-12-25 09:49 UTC, Maksim-13 commented on src/main/java/school/faang/bjs249633/Game.java
> +            if (earnedPoints) {
Ок, исправил.

2024-12-25 20:50 UTC, mysosnovskaya approved these changes
Я аппрув ставлю, но мержить боюсь - у тебя тут лишний класс House появился, если смержу, то он в твоей мастер-ветке окажется. Можешь класс удалить и самостоятельно смержить.

2024-12-26 08:56 UTC, merged