Становимся celebrity в Twitter
CorporationX/god_bless pull request #16419
Opened 2024-12-24 19:25 UTC by tr1pleK

2024-12-24 19:32 UTC, tr1pleK commented on src/main/java/school/faang/task_50704/TwitterSubscriptionSystem.java
> +        }, executor); // тут я хотел бы доабавить thenRun(() -> sout("вы успешно подписались на аккаунт "
вот сюда хотел добавить еще thenRun(() -> sout("вы успешно подписались на аккаунт "), но компилятор ругался, потому что возвращаемый объект менялся на void вместо TwitterAccount, подскажите, как можно было бы реализовать что то подобное, я попробовал несколько способов, но что то не получилось :(

2024-12-25 13:27 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/task_50704/TwitterSubscriptionSystem.java
> +        }, executor); // тут я хотел бы доабавить thenRun(() -> sout("вы успешно подписались на аккаунт "
Не совсем понял зачем здесь задержка времени. Кажется ее можно удалить, тогда код будет выглядеть еще короче:
```
public CompletableFuture<TwitterAccount> followAccount(TwitterAccount account) {
    return CompletableFuture.supplyAsync(() -> addFollower(account), executorService);
}
```

Если еще и в консоль написать, то можно:
```
public CompletableFuture<TwitterAccount> followAccount(TwitterAccount account) {
    return CompletableFuture.supplyAsync(() -> addFollower(account), executorService)
            .thenApply(follower -> {
                System.out.println("Follower добавлен: " + follower);
                return follower; 
            });
}
```

Или:
```
public CompletableFuture<TwitterAccount> followAccount(TwitterAccount account) {
    return CompletableFuture.supplyAsync(() -> addFollower(account), executorService)
        .thenRun(() -> System.out.println("Follower добавлен"));;
}
```

2024-12-25 13:28 UTC, SnurnicynKonstantin requested changes
Попробуй применить мой комментарий. Решил ли он твою задачу?

2024-12-25 13:28 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/task_50704/TwitterSubscriptionSystem.java
> +        }, executor); // тут я хотел бы доабавить thenRun(() -> sout("вы успешно подписались на аккаунт "
Это то, что ты спрашивал?

2024-12-25 13:51 UTC, tr1pleK commented on src/main/java/school/faang/task_50704/TwitterSubscriptionSystem.java
> +        }, executor); // тут я хотел бы доабавить thenRun(() -> sout("вы успешно подписались на аккаунт "
![image](https://github.com/user-attachments/assets/a92c726e-a2f9-45f3-a1db-ed078ceb9cb6)
да, вы правильно поняли что я спрашивал, ваш код кажется логичным и я тоже его пробовал, но почему то среда разработки ругается, прикрепил картинку

2024-12-25 13:58 UTC, tr1pleK commented on src/main/java/school/faang/task_50704/TwitterSubscriptionSystem.java
> +        }, executor); // тут я хотел бы доабавить thenRun(() -> sout("вы успешно подписались на аккаунт "
все, я смог разобраться, прикрепляю коммичу окончательный код

2024-12-27 05:32 UTC, SnurnicynKonstantin approved these changes

2024-12-27 05:32 UTC, merged