BJS2-49266, YouTube View Counter
CorporationX/god_bless pull request #16420
Opened 2024-12-24 19:39 UTC by Maksim-13

BJS2-49266, YouTube View Counter - alpha release

2024-12-25 20:47 UTC, mysosnovskaya requested changes

2024-12-25 20:47 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249266/Main.java
> +            executor.awaitTermination(1, TimeUnit.MINUTES);
Если не получилось дождаться завершения или если было прерывание, то пул потоков нужно завершить принудительно через shutdownNow

2024-12-25 20:47 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249266/VideoManager.java
> +    private final Map<String, Integer> viewsMap = new ConcurrentHashMap<>();
И ConcurrentHashMap, и методы синхронизированные. Могу предложить задачку на подумать (но для этого могут понадобиться темы 4 спринта): нужно избежать синхронизации на методах, но при этом чтобы всё равно всё было потокобезопасно. 
Можешь этот доп не делать, тогда просто присылай задачу обратно без этой доработки)

2024-12-26 10:11 UTC, Maksim-13 commented on src/main/java/school/faang/bjs249266/VideoManager.java
> +    private final Map<String, Integer> viewsMap = new ConcurrentHashMap<>();
Ок, исправил.

2024-12-26 10:11 UTC, Maksim-13 commented on src/main/java/school/faang/bjs249266/Main.java
> +            executor.awaitTermination(1, TimeUnit.MINUTES);
Ок, исправил.

2024-12-26 20:15 UTC, mysosnovskaya approved these changes

2024-12-26 20:15 UTC, merged