Google Photo sync
CorporationX/god_bless pull request #16453
Opened 2024-12-25 09:44 UTC by tatianagritsenko

2024-12-25 22:02 UTC, mysosnovskaya requested changes

2024-12-25 22:02 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_3/task_48976/GooglePhotosAutoUploader.java
> +            if (photosToUpload.isEmpty()) {
Лучше через while, т.к. поток может выйти из ожидания по разным причинам и после выхода нужно убедиться, что для него есть работа

2024-12-25 22:02 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_3/task_48976/GooglePhotosAutoUploader.java
> +                    System.out.println("Поток " + Thread.currentThread().getName() + " прервался");
Если произошло прерывание, то метод нужно завершить. И ещё хорошо было бы восстановить флаг прерывания
https://www.baeldung.com/java-interrupted-exception#2-restore-the-interrupt

2024-12-25 22:02 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_3/task_48976/Main.java
> +                    Thread.sleep(SLEEP_FOR_UPLOADER);
А зачем это? Он ведь и сам встанет в ожидание (wait в startAutoUpload), если ему нечего делать

2024-12-25 22:02 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_3/task_48976/Main.java
> +                for (int i = 0; i < new Random().nextInt(1, BOUND_FOR_RANDOM_GENERATOR); i++) {
Random лучше сделать полем класса, чтобы не создавать новый объект на каждой итерации цикла

2024-12-26 13:30 UTC, tatianagritsenko commented on src/main/java/school/faang/sprint_3/task_48976/Main.java
> +                    Thread.sleep(SLEEP_FOR_UPLOADER);
Просто у меня облако с фотками обновляется не всегда, а когда захожу в приложение, поэтому подумала, что можно сделать не постоянную загрузку, а с интервалом. Но да, в данном случае можно убрать)

2024-12-26 21:03 UTC, mysosnovskaya approved these changes

2024-12-26 21:03 UTC, mysosnovskaya commented on src/main/java/school/faang/sprint_3/task_48976/Main.java
> +    private static final Random random = new Random();
Если константа, то тогда лучше RANDOM

2024-12-26 21:03 UTC, merged