Task-BJS2-50698 Carry отожрался
CorporationX/god_bless pull request #16462
Opened 2024-12-25 11:52 UTC by senty8

2024-12-26 11:20 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/sprint_4/task_50698/Player.java
> +            return new Item(itemName, itemPower);
Если вынести `return new Item(itemName, itemPower);` в самый конец метода, то можно избавиться от `return null;`

Напрмиер:
```
try {
            Thread.sleep(collectionTime);
            log.info(collectionMessage);
} catch (InterruptedException e) {
            log.info("Collecting interrupted");
}
return new Item(itemName, itemPower);
```

2024-12-26 11:23 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/sprint_4/task_50698/Player.java
> +        System.out.println(inventory);
Это не замечание, просто комментарий на будущее. 
Логирование обычно используют когда необходимо получить информацию о процессах, которые происходят с запущенным приложением. Если в разных классах в лог отправлять разные объекты, то не понятно что это за объекты, откуда, зачем.
Лучше писать описательные сообщения. Например "Inventory from player is: {inventory}"

2024-12-26 11:25 UTC, SnurnicynKonstantin requested changes

2024-12-26 11:25 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/sprint_4/task_50698/Player.java
> +        System.out.println(inventory);
Это не замечание, просто комментарий на будущее. 
Логирование обычно используют когда необходимо получить информацию о процессах, которые происходят с запущенным приложением. Если в разных классах в лог отправлять разные объекты, то не понятно что это за объекты, откуда, зачем.
Лучше писать описательные сообщения. Например "Inventory from player is: {inventory}"

2024-12-26 11:57 UTC, senty8 commented on src/main/java/school/faang/sprint_4/task_50698/Player.java
> +            return new Item(itemName, itemPower);
тут хотел сделать логику, что если кто-то прерывает метод, то мы не успеваем сформировать item, и вынуждены вернуть null, обернул результат в optional

2024-12-27 05:37 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/sprint_4/task_50698/Player.java
> +            return new Item(itemName, itemPower);
Понял. Тут ты был прав, но здорово, что еще и с Optional реализовал.

2024-12-27 05:45 UTC, SnurnicynKonstantin approved these changes

2024-12-27 05:45 UTC, merged