BJS2-49876 Асинхронность и Future
CorporationX/god_bless pull request #16487
Opened 2024-12-25 15:36 UTC by OxanaNovozhilova

2024-12-26 17:22 UTC, SemyonKrivtsov requested changes

2024-12-26 17:22 UTC, SemyonKrivtsov commented on src/main/java/school/faang/task_49876/MasterCardService.java
> +            Thread.sleep(10_000);
Лучше работать с константами, их можно переиспользовать

2024-12-26 17:22 UTC, SemyonKrivtsov commented on src/main/java/school/faang/task_49876/MasterCardService.java
> +            Thread.sleep(10_000);
Исправь везде по коду

2024-12-26 17:22 UTC, SemyonKrivtsov commented on src/main/java/school/faang/task_49876/MasterCardService.java
> +        } catch (InterruptedException e) {
Если сценарий обработки исключений не меняется, то можно `InterruptedException  | ExecutionException  e `

2024-12-26 17:22 UTC, SemyonKrivtsov commented on src/main/java/school/faang/task_49876/MasterCardService.java
> +//Запустите метод collectPayment() в отдельном потоке и получите результат через Future.
Хороший код сам говорит за себя. Старайся не использовать комментарии в коде.

2024-12-27 04:48 UTC, OxanaNovozhilova commented
Спасибо за ревью)

2024-12-27 07:36 UTC, merged