BJS2-49123, The Iron Throne is a favorite price
CorporationX/god_bless pull request #16500
Opened 2024-12-25 19:22 UTC by Maksim-13

BJS2-49123, The Iron Throne is a favorite price  - alpha release

2024-12-26 20:51 UTC, mysosnovskaya requested changes

2024-12-26 20:51 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249123/House.java
> +    public String addRole() {
Может быть мы методы addRole и removeRole сделаем synchronized? А то в данный момент код этих методов не потокобезопасный. Тебя спасает только то, что ты их вызываешь из synchronized блоков, но ведь может такого не быть. Если будем предполагать дальнейшее расширение задачи, то эти методы могут быть вызваны откуда угодно и не факт, что там разработчик поставит synchronized

2024-12-26 20:51 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249123/Main.java
> +            for (int i = 0; i < NUMBER_PLAYERS; i++) {
У тебя получается так, что все игроки подключаются последовательно (по одному на каждой итерации цикла), а лучше было бы под каждого игрока сделать новый поток, чтобы имитировать многопоточную среду (несколько пользователей могут подключаться одновременно, поэтому через многопоточный вариант будет реалистичнее)

2024-12-26 20:51 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249123/Main.java
> +                    throw new RuntimeException(e);
Необходимо корректно обработать прерывание

2024-12-26 20:51 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249123/Main.java
> +    public static void main(String[] args) throws InterruptedException {
InterruptedException лучше обработать так, чтобы мы смогли успешно остановить пул потоков

2024-12-26 20:51 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249123/Main.java
> +                    Thread.currentThread().interrupt();
Во, вот тут хорошо 👍

2024-12-26 20:51 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249123/Main.java
> +                executor.shutdownNow();
И здесь с обработкой всё отлично)

2024-12-26 20:51 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249123/User.java
> +    public synchronized void joinHouse(House house) throws InterruptedException {
А имеет ли смысл делать на один и тот же код две блокировки? Сначала у тебя метод помечен synchronized, а потом всё тело метода завернуто в synchronized (house). Может оставим только одну?

2024-12-27 13:41 UTC, Maksim-13 commented on src/main/java/school/faang/bjs249123/House.java
> +    public String addRole() {
Ок, исправил.

2024-12-27 13:41 UTC, Maksim-13 commented on src/main/java/school/faang/bjs249123/Main.java
> +            for (int i = 0; i < NUMBER_PLAYERS; i++) {
Ок, исправил.

2024-12-27 13:41 UTC, Maksim-13 commented on src/main/java/school/faang/bjs249123/Main.java
> +                    throw new RuntimeException(e);
Ок, исправил.

2024-12-27 13:41 UTC, Maksim-13 commented on src/main/java/school/faang/bjs249123/Main.java
> +    public static void main(String[] args) throws InterruptedException {
Ок, исправил.

2024-12-27 13:41 UTC, Maksim-13 commented on src/main/java/school/faang/bjs249123/User.java
> +    public synchronized void joinHouse(House house) throws InterruptedException {
Ок, исправил.

2024-12-27 19:17 UTC, mysosnovskaya requested changes

2024-12-27 19:17 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249123/User.java
> +    public User(String name) {
В классе всегда сначала идут поля, потом конструкторы, а потом методы. Давай поправим порядок

2024-12-27 19:17 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249123/Main.java
> +                System.out.println("Await termination interrupted!");
И executor.shutdownNow(); здесь тоже подойдет

2024-12-27 19:17 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs249123/House.java
> +    public String addRole() {
Не увидела исправления)

2024-12-30 23:06 UTC, Maksim-13 commented on src/main/java/school/faang/bjs249123/User.java
> +    public User(String name) {
Ок, исправил.

2024-12-30 23:06 UTC, Maksim-13 commented on src/main/java/school/faang/bjs249123/Main.java
> +                System.out.println("Await termination interrupted!");
Ок, исправил.

2025-01-08 12:19 UTC, merged