Solve task_49895
CorporationX/god_bless pull request #16645
Opened 2024-12-27 16:31 UTC by shamshaev

2024-12-27 18:47 UTC, SemyonKrivtsov requested changes

2024-12-27 18:47 UTC, SemyonKrivtsov commented on src/main/java/school/faang/task_49895/MasterCardService.java
> +            Thread.sleep(10_000);
Лучше работать с константами, которые можно переиспользовать

2024-12-27 18:47 UTC, SemyonKrivtsov commented on src/main/java/school/faang/task_49895/MasterCardService.java
> +            throw new RuntimeException();
Маскируем один тип исключения другим. Лучше залогировать и остановить поток.

2024-12-27 19:01 UTC, shamshaev commented on src/main/java/school/faang/task_49895/MasterCardService.java
> +            throw new RuntimeException();
См. выше

2024-12-27 19:01 UTC, shamshaev commented on src/main/java/school/faang/task_49895/MasterCardService.java
> +            Thread.sleep(10_000);
Ребята, вы в условии задачи пишете:

3. В качестве шаблона для методов collectPayment и sendAnalytics используйте следующий код:



static int collectPayment() {
    try {
        Thread.sleep(10_000);
        return 10_000;
    } catch (InterruptedException e) {
        e.printStackTrace();
        throw new RuntimeException();
    }
}

static int sendAnalytics() {
    try {
        Thread.sleep(1_000);
        return 1_000;
    } catch (InterruptedException e) {
        e.printStackTrace();
        throw new RuntimeException();
    }
}

Для вы пишете этот код, если потом сами предъявляете претензии. Только не говорите, что специально пишете с ошибками.

Лучше бы я сам с нуля написал. Но если уж даете, то будьте добры принимать его...

2024-12-27 19:41 UTC, SemyonKrivtsov requested changes

2024-12-27 19:41 UTC, SemyonKrivtsov commented on src/main/java/school/faang/task_49895/MasterCardService.java
> +            Thread.sleep(10_000);
Я не пишу условия задач. Мое дело проверить, чтобы дальше не ушел код, по моему мнению, несовершенный. Моя задача указать на недочеты. Надеюсь на понимание!

2025-01-03 16:02 UTC, shamshaev commented on src/main/java/school/faang/task_49895/MasterCardService.java
> +            throw new RuntimeException();
Так как метод не void, то просто return для прекращения выполнения метода не подходит, поэтому по рекомендации ChatGPT сделал так.

2025-01-06 10:48 UTC, merged