Ztsv bjs2 48916 - Железный трон любой ценой
CorporationX/god_bless pull request #16658
Opened 2024-12-27 18:14 UTC by ArseniAstonMartin

2024-12-27 19:14 UTC, mysosnovskaya requested changes

2024-12-27 19:14 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs48916/House.java
> +    public  enum Role {
Во-первых, тут лишний пробел, а во-вторых, Role лучше вынести в отдельный класс - в java так принято)

2024-12-27 19:14 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs48916/House.java
> +    private volatile List<Role> availableRoles;
И final?

2024-12-27 19:14 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs48916/House.java
> +    ScheduledExecutorService periodManager = Executors.newScheduledThreadPool(Role.values().length);
А здесь модификаторов не хватает

2024-12-27 19:14 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs48916/House.java
> +    public List<Role> getAvailableRoles() {
Всегда лучше избегать геттеров на внутренние коллекции класса, которые хранят какие-либо данные. Я вижу, что ты подумал об этом и добавил copyOf, но нужно стараться вообще не писать подобные методы, только в условиях крайней необходимости. Ты мог бы вместо getAvailableRoles реализовать методы boolean hasRoles() и Role findAnyRole(); и тогда был бы полный порядок) А сейчас используем лишнюю память, но по-моему это не оправдано, т.к. нет железных аргументов, почему надо именно так.

2024-12-27 19:14 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs48916/House.java
> +    public boolean joinHouse(User user, Role role) {
Вообще по заданию роль должна выдаваться внутри этого метода. Но можем так оставить. Главное, чтобы у тебя это всё было потокобезопасно

2024-12-27 19:14 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs48916/House.java
> +        synchronized (role) {
А почему синхронизация на role? Это ведь просто одно из значений перечисления. В теории у тебя может быть много домов в коде и в каждом из них может быть пользователь с ролью role, почему они все должны блокировать друг друга?

2024-12-27 19:14 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs48916/House.java
> +        synchronized (role) {
Аналогично

2024-12-27 19:14 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs48916/User.java
> +                Thread.sleep(House.GOVERNANCE_PERIOD / 2);
А как же wait и notify?) По заданию нужно использовать именно их

2024-12-27 19:14 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs48916/User.java
> +                log.error("Error while trying to acquire some role");
Нужно восстановить флаг прерывания и завершить метод. А у тебя сейчас метод продолжится, будет выполняться следующая итерация и следующая, и следующая...

2024-12-27 19:14 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs48916/User.java
> +            return;
Нельзя допустить такого, чтобы пользователь ушел от нас без роли. У него гарантированно должна быть роль, просто вопрос времени. Кому-то сразу дадут, а кто-то будет ждать

2024-12-27 19:14 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs48916/House.java
> +    public boolean joinHouse(User user, Role role) {
По заданию методы в этом классе должны быть addRole и removeRole, а у тебя joinHouse и здесь, и в User - это путает

2024-12-27 19:26 UTC, ArseniAstonMartin commented on src/main/java/school/faang/bjs48916/House.java
> +    private volatile List<Role> availableRoles;
Я тоже хотел, но пишет Illegal combination of modifiers final and volatile, я подумал тут volatile более важно

2024-12-28 17:51 UTC, mysosnovskaya approved these changes

2024-12-28 17:51 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs48916/User.java
> +                    log.info("Error while {} was in queue to try to get role", name);
Не хватает корректной обработки прерывания (через Thread.currentThread().interrupt();), а также необходимо завершить этот метод, если прерывание произошло. А у тебя случится переход на следующую итерацию цикла)

2024-12-28 17:51 UTC, mysosnovskaya commented on src/main/java/school/faang/bjs48916/House.java
> +    private final Map<Role, Object> roleLockMap;
Оригинально 👍

2024-12-28 17:51 UTC, merged