Solve task_50931
CorporationX/god_bless pull request #16745
Opened 2024-12-29 17:39 UTC by shamshaev

2024-12-29 20:08 UTC, mysosnovskaya requested changes

2024-12-29 20:08 UTC, mysosnovskaya commented on src/main/java/school/faang/task_50931/Tournament.java
> +                log.warn("Main thread was interrupted", e);
Хорошо с уровнями логгирования работаешь 👍 
Расскажи, почему здесь решил использовать warn вместо error?

2024-12-29 20:08 UTC, mysosnovskaya commented on src/main/java/school/faang/task_50931/Tournament.java
> +                int beauxbatonsPoints = beauxbatonsTask.get().getTotalPoints();
Когда мы работаем с асинхронностью, то мы избегаем любых блокирующих вызовов, кроме самого финального (в твоём случае это join на 71 строке). 
Именно в твоей текущей реализации наличие блокирующих get методов никак плохо не скажется, но лучше не привыкать так писать. Нужно подумать, как можно написать код по-другому) Можно использовать thenCombine или подвести итоги уже после join

2025-01-03 17:19 UTC, shamshaev commented on src/main/java/school/faang/task_50931/Tournament.java
> +                    student.setPoints(updatedPoints);
С одной стороны, если запустить для одной школы несколько потоков (задач), это может привести к тому, что один поток будет увеливать только у части студентов, потом приходить другой поток и опять увеливать у части, и потом третий поток и он успеет увеличить у всех и таким образом процесс увеличения будет хаотичным для школы. Но если вызывать результат в конце всех потоков, то на результат это не повлияет, но процесс будет быстрее. Пэтому можно, думаю.

2025-01-03 22:22 UTC, shamshaev commented on src/main/java/school/faang/task_50931/Tournament.java
> +                log.warn("Main thread was interrupted", e);
Точно уже сложно сказать, много времени прошло) Но полагаю, я посчитал, что проблема с исполнением кода - это более значительная проблема, чем проблема возникшая при ожидании исполнения. Хотя сейчас подумал, что если прерывается главный поток, то что может быть хуже? Это же все, краш приложения...

2025-01-04 13:22 UTC, shamshaev commented on src/main/java/school/faang/task_50931/Tournament.java
> +                int beauxbatonsPoints = beauxbatonsTask.get().getTotalPoints();
Понял. Тут по условиям надо использовать allof(), поэтому логичнее будет после join() результаты подвести.

2025-01-06 17:54 UTC, mysosnovskaya commented on src/main/java/school/faang/task_50931/Tournament.java
> +                log.warn("Main thread was interrupted", e);
Да, тут скорее error должен быть. 
warn - это когда произошла некоторая ситуация, к которой мы были готовы, ничего не сломается, но разработчика надо предупредить о том, что это было. А error - когда дальнейшая работа этого потока невозможна из-за возникшей ошибки

2025-01-06 17:55 UTC, mysosnovskaya approved these changes

2025-01-06 17:55 UTC, merged