BJS2-51109 [Турнир трех волшебников]
CorporationX/god_bless pull request #16775
Opened 2024-12-30 21:56 UTC by Iv-an-s

2025-01-06 17:46 UTC, mysosnovskaya requested changes

2025-01-06 17:46 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/sprintfour/task_43582/Tournament.java
> +            for (Student student : school.getTeam()) {
Хорошее решение 👍 Можно только вынести это в отдельный приватный метод. Может быть даже в класс School, тем более там уже есть метод getTotalPoints

2025-01-06 17:46 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/sprintfour/task_43582/Tournament.java
> +        });
Лучше указать ещё и пул потоков

2025-01-06 17:46 UTC, mysosnovskaya commented on src/main/java/school/faang/moduleone/sprintfour/task_43582/Tournament.java
> +                log.error("Ошибка при выполнении задачи: " + e.getMessage());
Нужно корректно обработать прерывание и не продолжать работу метода, если прерывание случилось

2025-01-07 12:53 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprintfour/task_43582/Tournament.java
> +            for (Student student : school.getTeam()) {
вынес в School

2025-01-07 12:53 UTC, Iv-an-s commented on src/main/java/school/faang/moduleone/sprintfour/task_43582/Tournament.java
> +        });
Да, указал

2025-01-07 16:33 UTC, mysosnovskaya approved these changes

2025-01-07 16:33 UTC, merged