task 50881 solution
CorporationX/god_bless pull request #16779
Opened 2024-12-31 02:52 UTC by alexkid2001

2025-01-06 18:24 UTC, mysosnovskaya requested changes

2025-01-06 18:24 UTC, mysosnovskaya commented on src/main/java/school/faang/task_50881/Main.java
> +//        CompletableFuture.allOf(fromChest, bought)
Если код не нужен, то его следует удалить

2025-01-06 18:24 UTC, mysosnovskaya commented on src/main/java/school/faang/task_50881/Item.java
> +        if (name.isEmpty()) {
Но при этом у тебя на поле name есть сеттер (его добавляет data), где name может принимать любые значения (и пустые в том числе). Может быть сделать поле финальным?

2025-01-06 18:25 UTC, mysosnovskaya commented
И поправь сборку, она завалилась из-за закомментированного кода)

2025-01-07 01:36 UTC, alexkid2001 commented on src/main/java/school/faang/task_50881/Main.java
> +//        CompletableFuture.allOf(fromChest, bought)
Оставил для себя, как пример, чт отам тоже можно

2025-01-07 10:39 UTC, merged