Решение задачи BJS2-4446 по регистрации пользователей в модуле 1.3 Java Core
CorporationX/god_bless pull request #4403
Opened 2024-04-04 09:50 UTC by RickHammerson

2024-04-06 11:03 UTC, RickHammerson commented
> Раздели, пожалуйста, коммиты по задачам) Таким образом, тебе будет проще, как минимум, вносить изменения, и ты упростишь всем ревью, также четко будешь по джире видеть прогресс, ведь номера задач и твои ветки связаны. Я вижу тут три задачи и для удобства разделила бы каждую в свою папку, где будет также и свой Main класс.


Ну я же и так разделил задачки по веткам ветка называется rickhammerson/rickhammerson-BJS2-4446

Плюс каждая задача в своем package находится с отдельным Main классом
![fffa](https://github.com/CorporationX/god_bless/assets/42961541/1269f9f4-e7e3-4517-a4b1-f295180a01ec)

Что имеется в виду под разделением коммитов по задачам?

2024-04-07 01:10 UTC, Sabina-Vishnya requested changes
1) имелось ввиду, для каждой задачи, свои объекты юзера, методы и тд, а так у тебя просто переиспользование, что хорошо, да, если тебе так удобно - ок, но код ревьюить будет сложнее, если ты на всё так делаешь, Задачи дальше по объектам  +- схожи, а ты, если, таким же образом будешь переиспользовать, задевая объекты/методы, которые у тебя уже сделаны, сам потом вспомнишь какой код и объекты к задачам относятся, особенно на многопоточке? А сейчас у тебя эти лва мейна падают (об этом в пункте 2 ниже). На будущие, таски, удобнее все таки разделять

2) по try-catch - раз ты захотел это реализовать, то непонятно зачем по прежнему роняешь main, это так задумано? и причем два main метода, как и было, у тебя с ошибкой падают судя по коду. 
По условия можно бросить, да, но ты решил докрутить логику исходя из необязательного комментария моего -  гуд, но у тебя все мейны создающего юзеров, падают. Моя же рекомендация заключалась в том, что точка входа падать не должна (речь о main методах ведь). Я просто советую структурировать лучше, потому что ты уже сейчас задеваешь другую задачу, где вообще это не требовалось. 

3) погуглил что делает isEmpty и isBlank? кажется, что нет, тк тогда бы не было такой проверки `if (name == null || name.isEmpty() || name.isBlank()) {`

+ какой-то конфликт снизу подстветился, посмотри, пожалуйста, что произошло у тебя, из-за каких-то влитых изменений? я в idea твой код не открывала, просто тут в ПР-е сообщение о конфликте.

2024-04-07 10:57 UTC, RickHammerson commented
Разделил сущность User и исправил Main методы
Теперь по пункту 3:
В первом просмотре PR ты указала: 
> Помимо null и "" рассмотри случай " "
> Когда пустое - это не только незаполненное ничем, но и заполненное только пробелами

Но тут же правильная проверка:
if (name == null || name.isEmpty() || name.isBlank()) 
name == null - проверка, что имя не null
name.isEmpty() - проверка, что длинна не равна 0
![image](https://github.com/CorporationX/god_bless/assets/42961541/ff52df89-0678-49e3-a2ca-02db8d41cd17)

name.isBlank() - проверка, что строка не содержит только вайтспесы
![image](https://github.com/CorporationX/god_bless/assets/42961541/9c64520f-4918-40a6-a6ce-0ed83e73db21)

Считаю,что тут код всё делает верно. Поправь,если не так понял

2024-04-07 14:34 UTC, Sabina-Vishnya requested changes
Так, всё хорошо, только два замечания поправь и усе, больше можно ничгео не править!) 

а про мейн, лишь на заметку, что же я подразумевала в комменте и хотела бы увидеть всё же, когда таким образом решили "сымитировать тесты"
я бы создала в мейн всех возможных кривых юзеров и каждый бы из них обернула в try-catch, но я бы не кидала исключение, а просто выводила бы сообщение, о том, что кривое имя, или не тот возраст и тд - таким образом, ты бы посмотрел в мейн и сразу бы понял, что все кривые случаи покрыты, а при запуске в мейн у тебя бы ничего не упало, а ты на каждый случай бы увидел соответствующее сообщение, ну и корректного юзера мы и так создадим без проблем, так что и это тоже в мейне можно показать
Примерно так, это выглядело бы с невалидным юзером:
`try {
            new User("", 20, "Google", "London");
        } catch (Exception e) {
            System.out.println("какое-то сообщение про что-то кривое");
        }
        `
        
конечно выглядело бы не 1 в 1 как в примере, надо красивее и на каждый случай должно быть свое сообщение, но я надеюсь идея, в целом, теперь ясна 
очевидно мейн получился бы уже не такой маленький, но раз мы делаем типо тесты, то такое норм + там прям можно было бы красиво и понятно сделать всё, раскидать на методы, выводить сообщения, схоже с тестами и тд
но это так, чтобы просто уже было понятно о чем я

2024-04-07 18:41 UTC, RickHammerson commented on src/main/java/faang/school/godbless/module/core/register/User.java
> +        if (name == null || name.isEmpty() || name.isBlank()) {
ох, не знал. Спасибо

2024-04-07 18:41 UTC, RickHammerson commented on src/main/java/faang/school/godbless/module/core/register/Main.java
> +            ivan = new User("Иван", 20, "Google", "London");;
Исправил

2024-04-07 19:38 UTC, Sabina-Vishnya approved these changes
красава) хотела влить, но давай прям совсем немного добьем, чтобы уж до конца)
- в мейне тебе тогда не нужно сохранять юзеров в их переменные, так как ты эти переменные никак дальше не используешь, кроме как внутри try и всё, поэтому логика не изменится, если создать сразу через new и User ivan = null; тебе тожее не нужно тогда. Но если ты хочешь дальше использовать переменные, то это одно, но по текущему коду от них можно отказаться
- раз мы говорили о проверке трех случаев для имени null, "" и " " 
давай на все три и добавим, а то сейчас есть `new User("", 20, "Google", "London");`, а null и " " нету
- строка в печате `"Ошибка валидации создания пользователя: %s \n"`и не только она - это дублирование, которое очевидно стоит вынести в константу, но есть решения намного лучше, тк даже вынеся в константу только это, дублирование все равно в коде есть, поэтому:
Один приватный метод в мейне тут, который также содержит try-catch, почти такой же из тех, что у тебя сейчас, но только это всего лишь один метод с 4-мя параметрами, каждый параметр - это поле юзера. 
Переменную в try создаешь и используешь, тк просто печатаешь сообщение об успешном создании юзере и в нем показываешь его, передав вместе с сообщением и переменную, которая только в скоупе try видна.
Остальные невалидные случаи у тебя так и будут печататься после catch, просто ты значительно уменьшишь кол-во строк и сделаешь читаемо, за счет одного метода, который вызовешь вроде 7 раз
Также, добавить 4 константы, которые содержат корректные данные для того, чтобы опять же избежать дублирования, которое у тебя есть для "Google" и "London", и код понятнее сделать. Четыре эти константы ты переиспользуешь в каждом вызове метода, в итоге успешный юзер у тебя будет содержать все эти четыре константы, а остальные невалидные юзера по три, тк одно поле будет кривым. В итоге, твой код будет вмещаться до 30 строчки idea не длиннее  
еще можешь создать методы и назвать их для каждого поля соответствующе, а в них вызывать этот метод, будет чуть понятнее даже из-за того, что у тебя не просто один метод вызывается с 4-мя параметрами, а методы на каждое поле, но это смотри сам, возможно ты в процессе рефакторинга поймешь про что речь была
Надеюсь в этот раз уже окончательно добьем, тк расписала прям максимально подробно)

2024-04-08 14:45 UTC, RickHammerson commented
Исправил
Думаю, одного метода для проверки регистрации пользователя хватит
Подскажи,а можно как-то к тебе в команду зарезервироваться? Хочу такой же код ревью, когда начнется проект

2024-04-08 15:14 UTC, Sabina-Vishnya commented
@RickHammerson у нас распределение позже будет и там рандом) не переживай, ревью ты в любом случае получишь от любого техлида и не важно, кто тебе достанется, у нас все в этом плане дают фидбек. А еще, иногда даже полезнее, если попался другой техлид - так ты можешь получить экспертизу в другой формулировке, например. И это, возможно, в будущем тебе упростит понимание замечаний от коллег)

2024-04-09 00:52 UTC, RickHammerson commented
Исправил. Спасибо за подробное ревью

2024-04-09 01:13 UTC, Sabina-Vishnya approved these changes
ну вот, красава же, взял и доделал, умничка! 🔥🔥🔥🔥🔥

2024-04-09 01:14 UTC, merged