BJS2-4275: Герои меча и магии
CorporationX/god_bless pull request #4450
Opened 2024-04-04 18:44 UTC by nuraly04

2024-04-10 12:02 UTC, nuraly04 commented on src/main/java/faang/school/godbless/BJS2_4275/main/Battlefield.java
> +            int indexFractions = random.nextInt(fractions.size());
Я после каждой атаки проверяю и если там ничего нету то присваиваю поражение игроку и цикл и игра завершаются

2024-04-10 13:37 UTC, Sabina-Vishnya requested changes
где-то отступ остался, так что всё поправил + еще замечания добавила

2024-04-10 13:37 UTC, Sabina-Vishnya commented on src/main/java/faang/school/godbless/BJS2_4275/heroes_models/Creature.java
> +    public void addQuantity(int quantity) {
тоже не видно, что метод используется, давай использовать)

2024-04-10 13:37 UTC, Sabina-Vishnya commented on src/main/java/faang/school/godbless/BJS2_4275/main/Battlefield.java
> +package faang.school.godbless.BJS2_4275.main;
вот папка main тут не нужна, вынеси этот класс на один уровень со всеми, а папку heroes_models переименуй более общим названием и одним словом или вовсе от не избавься
если очень хочется, то всех существ можно вынести в отдельную папку, а класс Battlefield должен быть в папке номера задачи BJS2_4275
также стоит создать класс Main и там метод мейн в котором вызываются методы и собственно запускается бой

2024-04-10 13:37 UTC, Sabina-Vishnya commented on src/main/java/faang/school/godbless/BJS2_4275/main/Battlefield.java
> +                Creature fractionAttack = randomFraction(tony);
Противоречит принципу DRY, обрати внимание на (почти) одинаковые части кода и подумай, что же нам лучше тут сделать, чтобы уменьшить кол-во строк и повторений

2024-04-10 13:37 UTC, Sabina-Vishnya commented on src/main/java/faang/school/godbless/BJS2_4275/main/Battlefield.java
> +                Thread.sleep(5000);
давай не будем это тащить сюда, у тебя до этого такого не было, для чего вдруг появилось? 
ну вот появится задержка теперь, мы же бой имитируем и надо подождать, да, но еще есть аргументы какие-то разве? А вот против больше - это вынуждает пробросить исключение, и ты когда запустишь код устанешь ждать. На мой взгляд можешь обойтись без этого

2024-04-10 18:09 UTC, Sabina-Vishnya requested changes
Хорошо, но надо форматирование поправить и неиспользуемые импорты удалить

1. Форматирование: ⌘⌥L (macOS) / Ctrl+Alt+L (Windows/Linux) в каждом классе.
И перед коммитом можно в idea настроить Reformat Code добавив галочку 

2. Для импортов: Ctrl + Alt + O (Windows/Linux) или ⌘ + Option + O (macOS). И Optimize imports при коммите

2024-04-13 17:30 UTC, Sabina-Vishnya approved these changes

2024-04-13 17:30 UTC, merged