Задача: Двойной кэш-кэш
CorporationX/god_bless pull request #4491
Opened 2024-04-05 16:58 UTC by Demchenkov7

2024-04-07 15:20 UTC, Sabina-Vishnya requested changes
ты по мапе много где get делаешь и тут же другой метод вызываешь, но ведь если ключа не будет, то ты ошибку по-прежнему словишь, посмотри про метод containsKey

2024-04-07 15:20 UTC, Sabina-Vishnya commented on src/main/java/faang/school/godbless/doublecachecache/Main.java
> +            if (SUBJECT_STUDENTS.get(subject).contains(student)) {
для remove не требуется это проверка, глянь его реализацию

2024-04-07 16:11 UTC, Sabina-Vishnya requested changes
а containsKey?) ну раз уж начали, давай доводить до конца)

2024-04-07 16:46 UTC, Demchenkov7 commented
Не совсем понял какой containsKey?

2024-04-07 20:46 UTC, Sabina-Vishnya requested changes
Перечитай, пожалуйста, замечания все) случаи, когда ключей не существует - ты не учитываешь по-прежнему. Ранее, тебе написала об этом и затем еще раз, но уже более подробно, про то, что ты по мапе много где get делаешь и тут же другой метод вызываешь, а если ключа не будет, то ты ошибку по-прежнему словишь, и посоветовала обратить внимание на метод containsKey
если прямо в лоб - этот метод тут не в одном месте можно использовать во избежании такой ошибки

2024-04-08 19:56 UTC, Sabina-Vishnya requested changes
Поооооочти, правим дальше, ты прям вокруг да около))

Вот смотри, например, в remove (любом из класса) можно проверить, что там не так будет, если ключ не тот или его нет у мап, а дальше попытка удалить? 
Заметь, я тебе ранее уже писала комменты такие, в них везде подсказки, которые прям явно указывают на те места, где ошибка эта вылезти может, и ты даже ответил что за ошибка. 

Все методы с ошибками указывать пока не буду и так снова сильно подсказала, хоть и не всё) Но я всё же рассчитываю, что ты самостоятельно проверишь те случаи, которые мы с тобой решили учесть и доработаешь их) 

Сейчас кажется, что ты не особо проверил это и ожидаешь конкретных подсказок, без попыток выявить уязвимые (в контексте нашей доработки) места. 
Поскольку, в случае не найденных ключей у мап, какие-то методы по-прежнему отработают с ошибкой. 

Попробуй еще раз доработать это и повнимательнее, если не понимаешь о чем вообще речь, то попытайся разобраться сначала, а потом уже, если понимаешь, что тебя это стопает и затягивается на продолжительное время, то лучше спрашивай, что непонятно. А для начала ты бы мог проверить локально свои методы, но пока видимо этого не сделал?)
В общем, давай попытаемся доработать нормально, потому что ты прям близко и верно идешь.

2024-04-09 19:59 UTC, Sabina-Vishnya requested changes
Почти.
- Все методы не увидел, забей раз трудно, но при запуске main метод теперь упадет с ошибкой, такого поведения в точке входа не должно быть. Ты снова код не проверяешь перед ПР-ом и это уже не хорошо, либо специально ошибку делаешь, поскольку твой метод в мейне изменился removeStudent(new Student("ten")); и теперь упадет, потому что как раз не найдет такого студента, а если ты специально в мейн хочешь проверить ошибку, то можно было бы обернуть вот этот кусок removeStudent(new Student("ten"));  в try-catch, но в catch не кидать ошибку, а выводить сообщение, например. Но вообще можно не делать это и тестовые данные оставить на месте. У меня лишь было замечание на то, чтобы ты эти места с потенциальными ошибками увидел и обработал, ты это сделал частично, поэтому просто верни рабочий мейн.

- Советую компактнее сделать мейн, а то уже какой-то спагетти код выходит) я понимаю, что ты для читаемого вывода это делаешь, но давай хотя бы постараешься менее длинный код делать и поработаем не только над выводом, но и самим кодом, есть ведь знаки для переноса строки например, можно этим покрутить как-то форматирование.

- Коммиты должны быть информативными и относящимися к задаче, конкретнее, что ты по ней сделал. Когда делаешь 1-ый коммит можно писать с номером таски и брать название задачи из джиры или платформы. Когда правки делаешь, то пиши что сделал, а не просто сообщения, ведь даже сейчас если ты посмотришь на свою историю коммитов, то ничего не поймешь, кроме 1-го коммита, а другой человек тем более.

2024-04-10 06:46 UTC, Demchenkov7 commented
Так да, я знаю что будет ошибка, которую я выкидываю, специально для проверки и делал.
Т.е. суть вопроса была еще в том, что помимо, проверок в методах и выбрасывания илегал аргумент, надо было их в менее обработать? 

Или есть еще какой-то метод, который я не предусмотрел и не обработал вне мейна?

2024-04-11 13:39 UTC, Sabina-Vishnya commented
> Так да, я знаю что будет ошибка, которую я выкидываю, специально для проверки и делал. Т.е. суть вопроса была еще в том, что помимо, проверок в методах и выбрасывания илегал аргумент, надо было их в менее обработать?
> 
> Или есть еще какой-то метод, который я не предусмотрел и не обработал вне мейна?


1). Смотри, желательно, чтобы в контексте нашей задачи, мейн метод не падал, потому что это:
- По сути не проверяет полностью твой сценарий, тк когда ты кинешь ошибку, у тебя остальные методы дальше уже не отработают и сценарий до конца не завершится. 
Поэтому удобнее и правильнее, если у тебя в мейне ничего не падает, а методы, которые потенциально упадут из-за того, что в них неверные данные (и ты об этом знаешь) - завернуть в блоках try-catch, например, и в catch выводить сообщение о том, что пошло не так. Тогда у тебя после запуска мейна, будет вывод просто и даже в случае ошибки не прервется сценарий кинув исключение, а будет просто печататься информативный лог. А печатать можно уже разными способами, тут главное, чтобы мейн не падал. В идеале нужны юнит тесты на позитивные и негативные сценарии, но раз мы в мейне тестим тут, тогда не стоит его ронять)
- Может сбить тебя столку спустя время, когда запустишь мейн, а он упадет. 

А в предпоследней твоей правке, метод removeStudent стал падать в мейне, из-за того, что ты подкинул ему несуществующего юзера, хотя до этого мейн работал, и я тебе всего лишь предложила учесть случай, когда нет ключа, но ты решил почему-то данные поменять частично) Ну и раз ты таким образом решил проверить, стоило бы не ронять мейн просто, а обработать в try-catch этот метод уже в мейне, как тебе выше описала - тогда бы у тебя было в выводе видно всё, без прерывания сценария. Поэтому последнее замечание касалось именно этого случая. Да и непонятно, почему ты именно один метод решил таким образом проверить, если у тебя каждый метод почти такое исключение может выбросить)

2). Что по-поводу методов, которые вне мейна, они обработаны с containsKey - верно, а кидать исключение или нет, уже твой выбор. Последний мой комент про то, что ты не увидел все методы относились к тому, что в каких-то методах у тебя две мапы, а ты проверяешь ключ только у одной. Поэтому я тебе и пишу комменты о том, чтобы ты внимательнее проверял свой код))

На будущее просто учти эти большие комментарии, а щас двигайся дальше) так то всё гуд)

2024-04-11 13:39 UTC, Sabina-Vishnya approved these changes

2024-04-11 13:40 UTC, merged