Задача: Калькулятор
CorporationX/god_bless pull request #4658
Opened 2024-04-07 20:40 UTC by Demchenkov7

2024-04-08 14:02 UTC, Sabina-Vishnya requested changes
всё, в целом, отлично, давай только поправим:
- DataCenter, почему такое именно название? хотелось бы, более говорящее
что в этом классе? что эти методы делают? 
- можно еще метод main вынести в класс Main (сам класс создать), чтобы DataCenter (который переименуешь), содержал только методы, которые мы в мейн и проверим - так чуть понятнее будет то, что мы тестируем именно в мейне, то есть в DataCenter не делать мейн метод просто. Не мешать это всё

2024-04-08 20:49 UTC, Sabina-Vishnya requested changes
- А почему в итоге DataCalculator?) Давай это обработчик будет или арифметическая операция, или сервис в конце концов, а data тут ни к чему, у нас любой класс это данные чего-то, но мы их так не называем особо, а вторым или первым слово Calculator оставить можно. Сейчас твое новое название не сильно яснее стало от того, что там просто заменилось слово на DataCenter на DataCalculator
- Поправь форматирование ⌘⌥L (macOS) / Ctrl+Alt+L (Windows/Linux)
И перед коммитом можно в idea настроить форматирование добавив галочку
- IllegalArgumentException зачем тебе? По ТЗ есть да, но по факту, нужно ли тебе?

2024-04-09 19:03 UTC, Demchenkov7 commented
Переименовал, основываясь на описание задачи

2024-04-10 19:22 UTC, Sabina-Vishnya requested changes
внимательно читаем замечания!

2024-04-10 19:28 UTC, Sabina-Vishnya commented
> Переименовал, основываясь на описание задачи

В целом или конкретное место навело на такое именование? 
Возьми вариант из предпоследнего раза где service, давай добьем уже.

2024-04-11 12:10 UTC, Sabina-Vishnya approved these changes

2024-04-11 12:11 UTC, merged