BJS2-5019: Calculator
CorporationX/god_bless pull request #4709
Opened 2024-04-08 14:47 UTC by Dminin05

Task: https://faang-school.atlassian.net/browse/BJS2-5019

2024-04-08 15:14 UTC, mighty-mhsl commented on src/main/java/faang/school/godbless/calculator/Main.java
> +    public static int calculateInteger(List<Integer> nums, Calculator<Integer> calculator) throws IllegalArgumentException {
Это unchecked исключение, почему мы его тут выбрасываем?

2024-04-08 15:14 UTC, mighty-mhsl commented on src/main/java/faang/school/godbless/calculator/Main.java
> +    public static int calculateInteger(List<Integer> nums, Calculator<Integer> calculator) throws IllegalArgumentException {
Можно метод назвать calculate. Зачем Integer в названии?

2024-04-08 15:14 UTC, mighty-mhsl commented on src/main/java/faang/school/godbless/calculator/Main.java
> +        // Возможно можно как-то сделать плавающий return type с помощью дженериков, но не особо понял как.
Здесь не нужно, но все можно просто Long сделать

2024-04-08 15:14 UTC, mighty-mhsl commented on src/main/java/faang/school/godbless/calculator/Main.java
> +        }
Два раза уже написали эту валидацию. Как избежать дублирования?

2024-04-08 15:14 UTC, mighty-mhsl commented on src/main/java/faang/school/godbless/calculator/Main.java
> +    public static int calculateInteger(List<Integer> nums, Calculator<Integer> calculator) throws IllegalArgumentException {
Я бы этот метод убрал и все делал через лонг, раз хочется. Но это не критично. Сейчас у нас просто два одинаковых метода зачем-то. Должен быть один для всего

2024-04-08 15:31 UTC, Dminin05 commented on src/main/java/faang/school/godbless/calculator/Main.java
> +    public static int calculateInteger(List<Integer> nums, Calculator<Integer> calculator) throws IllegalArgumentException {
Сделал два метода, потому что не совсем понял как взаимодействовать с дженериками если я хочу сделать метод calculate и для int и для long. Сейчас переписал все и оставил один метод для long. Но непонимание все равно осталось( Что мне нужно сделать, чтобы метод calculate смог работать с double? В моем понимании самое очевидное скопировать метод и передать в сигнатуру не Calculator<Long>, а Calculator<Double>. Но как будто это слишком колхозно и есть более обобщенное решение.

2024-04-09 13:04 UTC, Sabina-Vishnya commented on src/main/java/faang/school/godbless/calculator/Main.java
> +    public static int calculateInteger(List<Integer> nums, Calculator<Integer> calculator) throws IllegalArgumentException {
Вот это сообщение "В моем понимании самое очевидное скопировать метод и передать в сигнатуру не Calculator, а Calculator." - не поняла про Calculator и Calculator или ты что-то другое имел ввиду?)
Но в целом, понятно что ты хочешь. В задании этого не требовалось, но раз захотел усложнение, давай) Можно сделать не супер прям красиво, но зато прямолинейно и ты, скорее всего, поймешь получше тему. 

Сейчас ты возвращаешь и принимаешь конкретный тип данных, поэтому только с этим типом работать и можешь, а для того, чтобы было более универсально, надо использовать дженерики в параметрах и возвращаемом типе, погугли синтаксис. Но тогда и методы sum, product тоже должны быть универсальными. Вот подумай, что надо сделать тогда. Это можно не очень красиво реализовать, но прямо расписать с какими типами можно работать. Попробуй сделать

2024-04-09 13:09 UTC, Dminin05 commented on src/main/java/faang/school/godbless/calculator/Main.java
> +    public static int calculateInteger(List<Integer> nums, Calculator<Integer> calculator) throws IllegalArgumentException {
В комментах образуются скобочки, которые используются для дженериков)))

2024-04-09 13:09 UTC, Sabina-Vishnya commented on src/main/java/faang/school/godbless/calculator/Main.java
> +    public static int calculateInteger(List<Integer> nums, Calculator<Integer> calculator) throws IllegalArgumentException {
иногда если не можешь себе или кому-то объяснить для чего добавлено то или иное "что угодно" - лучше и не добавлять тогда))

2024-04-09 13:11 UTC, Sabina-Vishnya requested changes
давай попробуешь сделать более сложный калькулятор, как хотел)

2024-04-09 13:22 UTC, Sabina-Vishnya commented on src/main/java/faang/school/godbless/calculator/Main.java
> +    public static int calculateInteger(List<Integer> nums, Calculator<Integer> calculator) throws IllegalArgumentException {
я наверное все равно не очень поняла, что ты имеешь ввиду, по мне ты описываешь то, что изначально делал и у тебя тут не дописалось снова наверное, а ты хотел написать `Calculator<Long> calculator` и `Calculator<Integer> calculator` если это не так - попробуй реализовать два варианта, который описал ты и тот, что предлагаю я, если это не одно и тоже, то один просто закомментируй
а чтобы показать код, можно нажать кнопку **code**) 
<img width="800" alt="Screenshot 2024-04-09 at 16 21 54" src="https://github.com/CorporationX/god_bless/assets/66567450/dab3dd2d-d2f5-420a-8c9f-d58ee981dc8a">

2024-04-09 13:25 UTC, Dminin05 commented on src/main/java/faang/school/godbless/calculator/Main.java
> +    public static int calculateInteger(List<Integer> nums, Calculator<Integer> calculator) throws IllegalArgumentException {
`Calculator<Long> calculator` `Calculator<Integer> calculator` так и хотел написать

2024-04-09 16:29 UTC, Sabina-Vishnya approved these changes
ну и гуд, потом на досуге более универсальный метод реализуешь, щас погнали дальше)

2024-04-09 16:30 UTC, Sabina-Vishnya approved these changes
ну и гуд, потом на досуге более универсальный метод реализуешь, щас погнали дальше)

2024-04-09 16:30 UTC, merged