BJS2-5200: Practice stream 2
CorporationX/god_bless pull request #4897
Opened 2024-04-11 12:04 UTC by Dminin05

Task: https://faang-school.atlassian.net/browse/BJS2-5200

2024-04-11 22:15 UTC, Sabina-Vishnya requested changes
давай более длинные условия, вынесем в приватные методы хотя бы, чтобы код чуть читаемей сделать

2024-04-11 23:32 UTC, Sabina-Vishnya requested changes

2024-04-11 23:32 UTC, Sabina-Vishnya commented on src/main/java/faang/school/godbless/practice_stream_2/Main.java
> +                .filter(entry -> !people.get(key1).contains(entry.getKey())
вот такие длинные условия предлагаю вынести либо в приватные методы, либо разбивать на несколько fiilter со своим условием, иначе это трудно читается
и точно ли нужен Pair тебе в этих задачах?
Давай эти все методами юнитами покроем лучше, тем более, что ты знаешь, как их писать и этот метод вообще кажется некорректно отработает и вернет только типо Dima, Andrew и наоборот, разве так должно быть? Проверь, пожалуйста, и попробуй оптимизировать немного, если не получится ничего страшного, но тут можно это сделать, главное чтобы методы в итоге работали верно

2024-04-12 03:33 UTC, Dminin05 commented on src/main/java/faang/school/godbless/practice_stream_2/Main.java
> +                .filter(entry -> !people.get(key1).contains(entry.getKey())
<img width="308" alt="Снимок экрана 2024-04-12 в 06 31 46" src="https://github.com/CorporationX/god_bless/assets/91825998/769e8472-c352-40ad-81b4-1a971a715473">
Возможно не правильно понял задание, но разве на такие входные данные должно получится еще что-то кроме `[[Dima, Andrew], [Andrew, Dima]]`?

2024-04-12 20:57 UTC, Sabina-Vishnya approved these changes

2024-04-12 20:57 UTC, merged