Решение задачи BJS2-5301 Meta-вселенная?
CorporationX/god_bless pull request #4955
Opened 2024-04-12 11:26 UTC by RickHammerson

https://faang-school.atlassian.net/browse/BJS2-5301?atlOrigin=eyJpIjoiYWJjY2M4MTg2MjY3NDQwZDgwYjg3MTgxZDRiZjA4N2QiLCJwIjoiaiJ9

2024-04-13 18:33 UTC, Sabina-Vishnya requested changes

2024-04-13 18:33 UTC, Sabina-Vishnya commented on src/main/java/faang/school/godbless/module/second/lambda/meta/Main.java
> +        NotificationManager notificationManager = new NotificationManager();
какой смысл тогда через экземпляр класса вызывать, если это статик?

2024-04-14 19:40 UTC, RickHammerson commented on src/main/java/faang/school/godbless/module/second/lambda/meta/Main.java
> +        NotificationManager notificationManager = new NotificationManager();
Скопировал текст с задачи,а методы сам писал.Переделаю

2024-04-15 17:44 UTC, Sabina-Vishnya approved these changes

2024-04-15 17:45 UTC, merged