Задача: Потренируем StreamAPI 2
CorporationX/god_bless pull request #4977
Opened 2024-04-12 14:15 UTC by Demchenkov7

2024-04-12 21:49 UTC, Sabina-Vishnya requested changes
нужны правки, перепроверяй, пожалуйста, все методы, потому что баги в нескольких, я хоть не везде написала комменты, но как минимум в 3-х вижу кривую логику
советую написать юнит-тесты, либо нормальные проверки в мейне организовать, тк сейчас мейн просто печатает и то не везде соответствует фактическому выводу

привыкаем сразу к качественному написанию кода, на работе за баги тебе спасибо не скажут и фиксить потом это всё большой радости точно никому не доставит, особенно учитывая, что баг в одном месте может повлиять на общую логику, так что давай поправим это дело и будем проверять свой код перед ревью

2024-04-12 21:49 UTC, Sabina-Vishnya commented on src/main/java/faang/school/godbless/streamspitest2/Main.java
> +    public static void findUniquePairs(List<Integer> nums, int target) {
метод распечатает не 2 пары, а 4, тк дублирует пару, просто меня местами, это баг, переписываем

2024-04-12 21:49 UTC, Sabina-Vishnya commented on src/main/java/faang/school/godbless/streamspitest2/Main.java
> +    public static void printCapitals(Map<String, String> countries) {
тоже баг, не в том порядке будет

2024-04-12 21:49 UTC, Sabina-Vishnya commented on src/main/java/faang/school/godbless/streamspitest2/Main.java
> +                .filter(str -> str.charAt(0) == prefix)
можно использовать startsWith вместо charAt

2024-04-12 21:49 UTC, Sabina-Vishnya commented on src/main/java/faang/school/godbless/streamspitest2/Main.java
> +    public static void findPairPeopleWithMutualFriends(Map<String, List<String>> friends) {
работает некорректно и при этом также дублирует пару

2024-04-13 15:26 UTC, Demchenkov7 commented on src/main/java/faang/school/godbless/streamspitest2/Main.java
> +    public static void printCapitals(Map<String, String> countries) {
Так не, тут мы страны сортируем по алфавиту, а потом уже выводим столицы. Они уже могут быть не в алфавитном порядке

2024-04-15 01:02 UTC, Sabina-Vishnya commented on src/main/java/faang/school/godbless/streamspitest2/Main.java
> +    public static void printCapitals(Map<String, String> countries) {
метод соответствует условию, ты проверял?)

задание такое:
"Отсортируйте страны по алфавиту, а затем выведите названия их столиц в виде списка."

у тебя:
- сортировка по столицам
- сортировка значений (столиц) в порядке убывания, в контексте алфавита от Z до A

ты получаешь значение из entry2 и сравниваешь со значением из entry1 - нужно наоборот, чтобы не менять направление и нужна сортировка по ключам (странам)

2024-04-15 17:37 UTC, Sabina-Vishnya approved these changes

2024-04-15 17:37 UTC, merged