Задача: Анализатор вакансий
CorporationX/god_bless pull request #5083
Opened 2024-04-14 11:05 UTC by Demchenkov7

2024-04-14 22:28 UTC, Sabina-Vishnya requested changes
давай еще использовать методы, которые сейчас нигде не вызываются
а так огонь!

2024-04-14 22:28 UTC, Sabina-Vishnya commented on src/main/java/faang/school/godbless/jobanalyzer/JobStreamProcessor.java
> +    JobScarper scarper = new JobScarper();
а почему дефолт модификатор?

2024-04-16 19:11 UTC, Sabina-Vishnya requested changes

2024-04-16 19:11 UTC, Sabina-Vishnya commented on src/main/java/faang/school/godbless/jobanalyzer/Main.java
> +        try (Stream<String> vacancies = Files.lines(Path.of("./src/main/resources//vacancies.txt"))) {
путь кривой до файлика, по идее будет пустота в выводе
ты проверь и подрефач если что, но только чтобы вывод работал

2024-04-22 00:05 UTC, Sabina-Vishnya commented
Если ты добить задачу хочешь, то надо подебажить и проверить решение, щас будет null возвращаться, потому что в parseVacancy такая логика заложена (там исключение ловишь и возвращаешь null), криво парсит, надо править.
Сейчас лучше двигайся дальше, а эту таску, если очень хочется, добивай в более свободное время, там надо будет больше в реализацию метода копнуть, но пока можно вмерджить так(если хочешь), все равно в текущей реализации у тебя тесты написаны на объект уже, а мейн просто всегда пустоту вернет из файла, тк опять же такая реализация кривоватая сейчас

2024-04-22 11:11 UTC, Demchenkov7 commented
Да, можно смержить, но я проверял, если брать строки из json файла, у меня при запуске он выводил ту единственную строку

2024-04-22 19:10 UTC, Demchenkov7 commented
а хотя сейчас что-то сломалось...

2024-04-22 20:56 UTC, Sabina-Vishnya commented
мог бы вмерджить уже) в общем, двигайся дальше и не упирайся в это, позже разберешься, тут главное что суть уловил и проблему знаешь, так что вернуться попозже можно, а это тогда вмерджу

2024-04-22 20:56 UTC, Sabina-Vishnya commented
мог бы вмерджить уже) в общем, двигайся дальше и не упирайся в это, позже разберешься, тут главное что суть уловил и проблему знаешь, так что вернуться попозже можно, а это тогда вмерджу

2024-04-22 20:56 UTC, Sabina-Vishnya approved these changes

2024-04-22 20:57 UTC, merged