BJS2-5450: Потренируем StreamAPI 1
CorporationX/god_bless pull request #5148
Opened 2024-04-15 14:33 UTC by p1maf

2024-04-18 23:51 UTC, Sabina-Vishnya requested changes

2024-04-18 23:51 UTC, Sabina-Vishnya commented on src/main/java/BJS2_5450/Main.java
> +        // 1
все повторяющиеся значения в условиях вынеси в переменные хотя бы

2024-04-18 23:51 UTC, Sabina-Vishnya commented on src/main/java/BJS2_5450/Main.java
> +    public static Optional<Integer> findMinNumberElement(List<Integer> numbers) {
только значение 3 спрятано и это вводит в заблуждение из-за названия метода, да и в целом это не гибко и ожидается, что можно передать второй параметр, так что лучше сделать 2-ой параметр для возможности передать не только значение 3

2024-04-18 23:51 UTC, Sabina-Vishnya commented on src/main/java/BJS2_5450/Main.java
> +    public static List<String> filterStr(List<String> strings, String phrase) {
Метод фильтрует список строк и оставляет только те, которые содержат определенный подстроку ведь? а название метода вообще не говорит ни о чем, давай переименуем в что-то типо filterStrContainingSubstring

2024-04-18 23:51 UTC, Sabina-Vishnya commented on src/main/java/BJS2_5450/Main.java
> +    public static List<String> filterCountry(List<String> strings) {
1 про задание нет ни слова про страны
2 даже если это только страны, то название параметра тогда должно быть более говорящим
Метод должен сортировать список строк по длине, не уточняя, что конкретно, так и назови его

2024-04-18 23:51 UTC, Sabina-Vishnya commented on src/main/java/BJS2_5450/Main.java
> +    public static List<Integer> reverseStringInLength(List<String> strings) {
convertStringsToLengths кажется более понятнее будет

2024-04-18 23:51 UTC, Sabina-Vishnya commented on src/main/java/BJS2_5450/Main.java
> +    public static boolean correctPassword(List<String> strings) {
не поняла, откуда этот метод, судя по тз - метод, который должен проверить, все ли элементы списка удовлетворяют определённому условию
вот в подсказках есть прям очевидное то, что нам стоит использовать здесь и это предикат вторым параметром, а название метода опять же сделай более очевидное по тз, какое-то с словом check или match

2024-04-19 07:10 UTC, p1maf commented on src/main/java/BJS2_5450/Main.java
> +    public static boolean correctPassword(List<String> strings) {
там же было, что проверить что-либо поэтому и решил пароль

2024-04-19 07:17 UTC, p1maf commented on src/main/java/BJS2_5450/Main.java
> +    public static boolean correctPassword(List<String> strings) {
тк allMatch же принимает Predicated

2024-04-20 02:12 UTC, Sabina-Vishnya commented on src/main/java/BJS2_5450/Main.java
> +    public static boolean correctPassword(List<String> strings) {
Вольем, но для себя всё же хотя бы попробуй сделать, как тз. Суть в том, что у тебя явно в методе захардкоженное значение сейчас, а по тз больше подходит, чтобы в параметре был лист и предикат, и в мейне ты уже условие прописываешь, какое-то любое, например, то которое у тебя тут в методе прям) там же и подсказка есть про интерфейс. Сейчас у тебя название на проверку пароля, что неочевидно в контексте тз и значение хардкодом, а хардкодить тут вообще не стоило так

2024-04-20 02:14 UTC, Sabina-Vishnya approved these changes

2024-04-20 02:15 UTC, merged

2024-04-20 10:25 UTC, p1maf commented on src/main/java/BJS2_5450/Main.java
> +    public static boolean correctPassword(List<String> strings) {
Если так рассуждать, то да согласен, более гибкое решение получается