Задача: Supercow!
CorporationX/god_bless pull request #5394
Opened 2024-04-19 11:52 UTC by Demchenkov7

2024-04-21 17:13 UTC, Sabina-Vishnya requested changes
лок еще и статик, зачем?
используй либо lock, либо synchronized, не оба вместе

2024-04-23 08:31 UTC, Demchenkov7 commented
Не совсем понимаю, о чем идет речь. 
Я использую synchronized блок с lock, на котором вызываю wait/notify. 
Что значит использовать либо lock либо synchronized

2024-04-23 18:37 UTC, Sabina-Vishnya commented
> Не совсем понимаю, о чем идет речь. Я использую synchronized блок с lock, на котором вызываю wait/notify. Что значит использовать либо lock либо synchronized

блииииин, прости, пожалуйста!) 
у тебя норм (имелось ввиду что-то одно, synchronized метод или блок, у тебя всё норм), а я походу код перепутала с другим ПР-ом, либо меня глюкануло вовсе, пора высыпаться)

2024-04-23 18:37 UTC, Sabina-Vishnya approved these changes

2024-04-23 18:38 UTC, merged