BJS2-7808 | Регистрация пользователей
CorporationX/god_bless pull request #5840
Opened 2024-06-02 22:57 UTC by DROFEL

2024-06-05 06:41 UTC, InnMish commented on src/main/java/faang/school/godbless/group_users_by_age/User.java
> +        if(name == null || name.isEmpty()) {
имя состоящее из нескольких пробелов - тоже невалидное

2024-06-05 06:41 UTC, InnMish commented on src/main/java/faang/school/godbless/group_users_by_age/User.java
> +        if(age < 18) {
18 давай вынесем в константу

2024-06-05 06:41 UTC, InnMish commented on src/main/java/faang/school/godbless/group_users_by_age/User.java
> +}
это относится к другой задаче, надо пофиксить тоже, как там

2024-06-05 06:41 UTC, InnMish commented on src/main/java/faang/school/godbless/group_users_by_age/main.java
> +    public static void main(String[] args) {
Во-первых, с большой буквы, во-вторых, у тебя будет конфликт 

Делай так: для каждой таски создавай отдельный пакет, в этом пакете для каждой таски свой метод main

2024-06-05 16:41 UTC, DROFEL commented on src/main/java/faang/school/godbless/group_users_by_age/main.java
> +    public static void main(String[] args) {
мерджнул предыдущую задачу, в которой это пофиксил. Починилось имя класса и лист в мапе

2024-06-06 00:47 UTC, pablo023 requested changes
Пофикси)

2024-06-06 00:47 UTC, pablo023 commented on src/main/java/faang/school/godbless/group_users_by_age/Main.java
Тут нужно переделать. Смотри, логки трай-кетча заключается в том, что есть какая-то часть кода, которая может свалиться, но после неё есть часть кода, которая обязательно должна выполниться. Вот для опасной мы делаем трай-кетч, чтобы если оно свалится, у нас то, что дальше - все равно отработало. Просто кидать эксепшены мы можем без трай-кетча. Переделай это.

2024-06-06 00:47 UTC, pablo023 commented on src/main/java/faang/school/godbless/group_users_by_age/User.java
> +        if(age < AGE_CUT_OFF) {
Красавчик

2024-06-06 21:07 UTC, DROFEL commented on src/main/java/faang/school/godbless/group_users_by_age/Main.java
@pablo023 я их в трай кетч завернул как раз чтобы протестировать ошибки, ну и чтобы они все в одиной функции ранились, так как это условие задачи. Если я юнит тесты с ассертаим на эксепшин сделаю норм будет?

2024-06-10 01:59 UTC, DROFEL commented on src/main/java/faang/school/godbless/group_users_by_age/Main.java
Пофиксил

2024-06-11 01:07 UTC, pablo023 approved these changes

2024-06-11 04:32 UTC, merged