BJS2-8196 | Westeros library
CorporationX/god_bless pull request #5909
Opened 2024-06-03 21:52 UTC by DROFEL

2024-06-07 02:10 UTC, pablo023 requested changes
Чутка пофиксь, и едем дальше

2024-06-07 02:10 UTC, pablo023 commented on src/main/java/faang/school/godbless/westeros_library/Book.java
> +        return year+title.hashCode()+author.hashCode();
Можно элегантнее - через Objects.hash(). А еще круче - через аннотацию ломбока.

2024-06-07 02:10 UTC, pablo023 commented on src/main/java/faang/school/godbless/westeros_library/Book.java
> +    }
Тут проверки на нулл нет. Я бы тебе посоветовал вообще это аннотацией это делать, но вообще знаешь, не надо пока что. На собесе у тебя будут спрашивать, как equals должен сравнивать, и hashCode тоже, и это от зубов отлетать должно. Так что давай ручками пока их попишем. Но почитай еще раз, как его лучше писать.

2024-06-07 02:10 UTC, pablo023 commented on src/main/java/faang/school/godbless/westeros_library/Main.java
Мне очень нравятся названия методов)

2024-06-07 05:27 UTC, DROFEL commented on src/main/java/faang/school/godbless/westeros_library/Main.java
Рад стараться)

2024-06-07 05:46 UTC, DROFEL commented on src/main/java/faang/school/godbless/westeros_library/Book.java
> +    }
понял приня, интересно instanceof работает. На сколько глубоко посоветуешь смотреть в работу хэша объекта и если какието особенности equals?

2024-06-09 00:21 UTC, pablo023 commented on src/main/java/faang/school/godbless/westeros_library/Book.java
> +    }
Насчет обоих методов - быть в силах их написать четко, и ответить зачем они вообще нужны, на собесе, и что может пойти не так, если сделать их криво.

2024-06-09 00:58 UTC, pablo023 approved these changes

2024-06-10 01:59 UTC, merged