nikittta-BJS2-7724
CorporationX/god_bless pull request #5911
Opened 2024-06-04 02:34 UTC by Nikita2768

2024-06-05 06:36 UTC, InnMish approved these changes

2024-06-05 06:36 UTC, InnMish commented
Здесь тоже посмотри, чтобы классы этой задачи лежали в отдельном пакете, чтобы не было конфликтов между файлами. То есть Application класс и метод main Для каждой таски свой должен быть

2024-06-05 18:05 UTC, pablo023 requested changes

2024-06-07 01:19 UTC, pablo023 approved these changes

2025-01-17 21:07 UTC, closed without merging