nikittta-BJS2-7810
CorporationX/god_bless pull request #5912
Opened 2024-06-04 02:55 UTC by Nikita2768

2024-06-05 12:37 UTC, pablo023 requested changes
Почисть код

2024-06-05 12:37 UTC, pablo023 commented on src/main/java/faang/school/godbless/Application.java
Я так понял, это ты тестировал. Если ты хочешь тестировать - пиши тесты отдельными классами) Если так тестировать хочется - то так, чтобы это в ПР не попадало.

2024-06-05 12:37 UTC, pablo023 commented on src/main/java/faang/school/godbless/User.java
> +        setName(name);
this.name = name

2024-06-05 12:37 UTC, pablo023 commented on src/main/java/faang/school/godbless/User.java
> +        setPlaceOfWork(placeOfWork);
this.placeOfWork...

2024-06-05 12:37 UTC, pablo023 commented on src/main/java/faang/school/godbless/User.java
> +            throw new IllegalArgumentException();
Можно в эксепшн добавить сообщение, которое его конкретизирует. Привыкай к этому. А-ля, throw new IllegalArgumentException("Age restriction: Must be at least 18 years old. Provided user {user} age: {user.age}. );

2024-06-05 16:56 UTC, Nikita2768 commented on src/main/java/faang/school/godbless/User.java
> +        setName(name);
Там ведь условие стоит, что нужно в случае каких нибудь ограничений выбросить исключение. Лучше if в конструкторе создавать?

2024-06-05 18:18 UTC, pablo023 commented on src/main/java/faang/school/godbless/User.java
> +        setName(name);
А, ты таким образом валидацию делаешь. Идея понятна, но практика это не лучшая, т.к. это может производить сайд-эффекты. В данном случае это будет работать, но тебе нужно обрести навыки, которые будут тебе полезны в проекте на твоей работе. Да, в конструкторе валидацию лучше написать через if.

2024-06-06 02:54 UTC, Nikita2768 commented on src/main/java/faang/school/godbless/User.java
> +        setName(name);
Понял, спасибо

2024-06-11 01:10 UTC, pablo023 approved these changes
Очень хорошо

2025-01-17 21:07 UTC, closed without merging