Игра престолов
CorporationX/god_bless pull request #5925
Opened 2024-06-04 09:58 UTC by ravshanbekn

2024-06-06 01:27 UTC, pablo023 requested changes

2024-06-06 01:27 UTC, pablo023 commented on src/main/java/faang/school/godbless/game_of_thrones/House.java
> +    public static void addNewHouses(Map<String, House> houseMap, House ...houses){
Форматирование + вараргс мы в качестве параметров не используем. Если ты планируешь писать логику, которая будет обрабатывать множество объектов - указывай параметром коллекцию какую-то. И по задаче у нас только для добавления одного дома логика должна быть

2024-06-06 01:27 UTC, pablo023 commented on src/main/java/faang/school/godbless/game_of_thrones/House.java
> +    public static void deleteHousesByName(Map<String, House> houseMap, String ...names){
Тут тоже, нам нужно одно имя на вход, чтобы один дом убрать

2024-06-06 01:27 UTC, pablo023 commented on src/main/java/faang/school/godbless/game_of_thrones/House.java
> +            System.out.println(house);
Вот это выведет просто ссылку на объект. Переимплементиуй toString

2024-06-06 18:22 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/game_of_thrones/House.java
> +            System.out.println(house);
Там есть аннотация @Data, одна из ее функций имплементация toString

2024-06-07 01:47 UTC, pablo023 commented on src/main/java/faang/school/godbless/game_of_thrones/House.java
> +            System.out.println(house);
Сори, не заметил

2024-06-07 13:43 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/game_of_thrones/House.java
> +            System.out.println(house);
pull request закроете?

2025-01-17 21:07 UTC, closed without merging