Библиотека Вестеросса
CorporationX/god_bless pull request #5929
Opened 2024-06-04 10:34 UTC by ravshanbekn

2024-06-07 02:24 UTC, pablo023 requested changes
Фиксани момент создания новых объектов. Без этого надо

2024-06-07 02:24 UTC, pablo023 commented on src/main/java/faang/school/godbless/vesterros_library/Book.java
> +        Book bookToDelete = new Book(title, author, year);
Ну нет. Во-первых, создать что-то, для того, чтобы потом удалить это - это антипаттерн. Во-вторых, ты просто удаляешь книгу. А если её нет там?

2024-06-07 02:24 UTC, pablo023 commented on src/main/java/faang/school/godbless/vesterros_library/Book.java
> +        Book bookToSearch = new Book(title, author, year);
То же самое.

2024-06-07 13:52 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/vesterros_library/Book.java
> +        Book bookToSearch = new Book(title, author, year);
Как обойти создание нового объекта?

2024-06-07 20:34 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/vesterros_library/Book.java
> +        Book bookToDelete = new Book(title, author, year);
Еще можно проитерироваться по всем ключам в bookMap, но стоит ли этого делать? Пожертвовать памятью или скоростью?

2024-06-09 01:20 UTC, pablo023 commented on src/main/java/faang/school/godbless/vesterros_library/Book.java
> +        Book bookToDelete = new Book(title, author, year);
Вообще, мне нравится, что ты ставишь перед собой такие вопросы, здесь уже возможна дискуссия - а прав ли я. Всё зависит от контекста, и условно говоря, если приоритет - на скорость выполнения, то дешевле было бы действтельно сделать так, как ты делаешь. Но так не делается прям вот без сильной причины, когда нужно задержку в 0 убирать, и пишется вот всё что угодно, лишь бы она была низкой. До тех пор, пока мы изучаем ООП, и программирование в целом, с моей стороны было бы неправильно поощрять антипаттерны, поскольку есть кейсы, где они актуальны. На данный момент мы не пишем что-то безумно производительное, и мне нужно, чтобы придя на работу, ты ни в коем случае не написал вот так, если того не требуют абсолютно все обстоятельства.

2024-06-09 01:21 UTC, pablo023 commented on src/main/java/faang/school/godbless/vesterros_library/Book.java
> +        Book bookToSearch = new Book(title, author, year);
Итерацией

2024-06-09 01:21 UTC, pablo023 requested changes
Дал комменты, жду исправлений.

2024-06-09 09:15 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/vesterros_library/Book.java
> +        Book bookToDelete = new Book(title, author, year);
Понятно, исправил

2024-06-10 00:54 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/vesterros_library/Book.java
> +        Book bookToSearch = new Book(title, author, year);
Сделал

2024-06-11 02:22 UTC, pablo023 approved these changes

2024-06-11 02:22 UTC, pablo023 commented on src/main/java/faang/school/godbless/vesterros_library/Library.java
> +        Book bookToSearch = new Book(title, author, year);
Сделаю вид, что не заметил))

2024-06-11 07:17 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/vesterros_library/Library.java
> +        Book bookToSearch = new Book(title, author, year);
Сори, не заметил

2025-01-17 21:07 UTC, closed without merging