Считаем прогулы
CorporationX/god_bless pull request #5937
Opened 2024-06-04 11:44 UTC by ravshanbekn

2024-06-06 01:47 UTC, pablo023 requested changes
Тут в два захода будем ревьюить. Сначала перенеси все, кроме полей и конструктора, из студента, в мэйн. Там уже посмотрим.

2024-06-06 01:47 UTC, pablo023 commented on src/main/java/faang/school/godbless/counting_absences/FacultyAndYearPair.java
Усложнил. Я понимаю что ты это сделал для того, чтобы попасть в условие задачи, но давай попробуем обойтись без этой сущности.

2024-06-06 01:47 UTC, pablo023 commented on src/main/java/faang/school/godbless/counting_absences/Student.java
> +    }
Data создает конструктор

2024-06-06 01:47 UTC, pablo023 commented on src/main/java/faang/school/godbless/counting_absences/Student.java
> +    public static void addStudentToMap(Map<FacultyAndYearPair, List<Student>> studentMap, Student student){
форматирование

2024-06-06 18:39 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/counting_absences/Student.java
> +    }
Разве Data не имплементирует RequiredArgsConstructor, который создает конструктор и включает для него все final поля?
Если name и faculty сделаю final, то year все равно не должен быть final, или я ошибаюсь?

2024-06-07 02:05 UTC, pablo023 requested changes

2024-06-07 02:05 UTC, pablo023 commented on src/main/java/faang/school/godbless/counting_absences/Student.java
> +    }
Воу, молодец) Это круто, что ты вдаешься в детали. Давай мы выпилим имплементацию через сущность пары год и факультет, т.к. это излишество. Мы же можем представить эти два поля не через сущность, отдельно для этого созданную.

2024-06-07 13:49 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/counting_absences/Student.java
> +    }
Создал отдельный класс, куда и вынес всю логику
Там несколько коммитов, когда ревьюить будете, лучше перейдите на саму ветку, там где весь код

2024-06-07 13:49 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/counting_absences/Student.java
> +    public static void addStudentToMap(Map<FacultyAndYearPair, List<Student>> studentMap, Student student){
Хорошо

2024-06-09 00:20 UTC, pablo023 approved these changes
Молодец. Но опять не обработал сиутацию в поиске студента в searchByFacultyAndYear на случай, если такого нет. Пропущу, но пожалуйста, обращай на это внимание.

2025-01-17 21:07 UTC, closed without merging