Pavlick2745 bjs2 7823
CorporationX/god_bless pull request #5944
Opened 2024-06-04 13:19 UTC by i7rincpane

2024-06-06 00:50 UTC, pablo023 requested changes
Немножко надо пофиксить

2024-06-06 00:50 UTC, pablo023 commented on src/main/java/faang/school/godbless/User.java
> +        if (!this.validate(name, age, job, address)) {
Сделай отдельную проверку на каждое поле, т.к. у тебя летит один эксепшн без сообщения (его тоже добавь) на все проверки, и непонято что именно свалиллось

2024-06-06 00:50 UTC, pablo023 commented on src/main/java/faang/school/godbless/User.java
> +        if (age< 18) {
тут тоже по форматированию

2024-06-06 00:50 UTC, pablo023 commented on src/main/java/faang/school/godbless/User.java
> +        if (name== null || name.isEmpty()) {
форматирование съехало

2024-06-06 00:50 UTC, pablo023 commented on src/test/java/faang/school/godbless/UserTest.java
Молодец какой. Вынеси кстати возраст в константу и в классе юзер тоже. Только не нужно использовать класс-обертку, примитива хватит. Нам не нужны его методы, а по памяти сэкономим.

2024-06-07 19:03 UTC, i7rincpane commented on src/main/java/faang/school/godbless/User.java
> +        if (!this.validate(name, age, job, address)) {
Понятно

2024-06-07 19:05 UTC, i7rincpane commented on src/main/java/faang/school/godbless/User.java
> +        if (name== null || name.isEmpty()) {
понятно

2024-06-07 19:05 UTC, i7rincpane commented on src/main/java/faang/school/godbless/User.java
> +        if (age< 18) {
понятно

2024-06-11 01:11 UTC, pablo023 approved these changes
Ну это же вообще другое дело. Какой красивый код.

2025-01-17 21:07 UTC, closed without merging