Ловим события
CorporationX/god_bless pull request #5945
Opened 2024-06-04 13:20 UTC by ravshanbekn

2024-06-07 03:19 UTC, pablo023 requested changes
Давайте фиксить, чтобы было по ООП

2024-06-07 03:19 UTC, pablo023 commented on src/main/java/faang/school/godbless/catching_events/StreamEvent.java
Эти методы не должны здесь лежать. В объекте - только то, что объект может сделать. Вот тебе надо проверить - есть ли объект в мапе. И ты для этого передаешь мапу в аргументы. Это не гуд. Представь, что твоя задача - проверить, если ли какая-то штука в коробке. Ты же возьмешь коробку, и будешь в ней эту штуку искать, правильно? А тут ты берешь эту штуку, даешь ей коробку, и ищешь. Ну, типа) Не надо так. Перепиши это. В ООП важно разбираться, чтобы на работе профессионализм показывать.

2024-06-07 03:19 UTC, pablo023 commented on src/main/java/faang/school/godbless/catching_events/StreamEvent.java
> +        eventMap.remove(streamEvent.getId());
А если нет такого стрим эвента в мапе?

2024-06-07 13:55 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/catching_events/StreamEvent.java
Хорошо, сделал отдельный класс

2024-06-07 13:56 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/catching_events/StreamEvent.java
> +        eventMap.remove(streamEvent.getId());
Логгирование сойдет?

2024-06-11 02:37 UTC, pablo023 commented on src/main/java/faang/school/godbless/catching_events/StreamEvent.java
> +        eventMap.remove(streamEvent.getId());
Да, вполне.

2024-06-11 02:47 UTC, pablo023 approved these changes
Мелкие недочеты, но в целом ок. Едем дальше!

2024-06-11 02:47 UTC, pablo023 commented on src/main/java/faang/school/godbless/catching_events/StreamEventService.java
Что-то у нас тут пробелы перед фигурными скобками попропадали. not good

2024-06-11 02:47 UTC, pablo023 commented on src/main/java/faang/school/godbless/catching_events/StreamEventService.java
> +        if(!eventMap.containsKey(id)){
Форматирование

2024-06-11 02:47 UTC, pablo023 commented on src/main/java/faang/school/godbless/catching_events/StreamEventService.java
> +        StreamEvent streamEvent = new StreamEvent(id, eventData, data);
Не надо создавать объект для того ,чтобы его удалить

2024-06-11 07:37 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/catching_events/StreamEventService.java
> +        if(!eventMap.containsKey(id)){
Отформатировал

2024-06-11 07:37 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/catching_events/StreamEventService.java
> +        StreamEvent streamEvent = new StreamEvent(id, eventData, data);
Исправил

2025-01-17 21:07 UTC, closed without merging