Разбираем склад Amazon
CorporationX/god_bless pull request #5949
Opened 2024-06-04 13:54 UTC by ravshanbekn

2024-06-07 02:36 UTC, pablo023 requested changes
В целом норм, но чуть поправить можно, тебе для понимания просто ООП. Либо в мэйн, либо в отдельный сервис это кинь.

2024-06-07 02:36 UTC, pablo023 commented on src/main/java/faang/school/godbless/amazon/Product.java
> +    }
Это не должно относиться к классу Продукт. Смотри в ООП считай что продукт это вот как в реальной жизни продукт. Продукт может сгруппировать продукты? Не может. Кладовщик может, склад может, кто-то еще может, но сам продукт другие продукты - не может.

2024-06-07 02:36 UTC, pablo023 commented on src/main/java/faang/school/godbless/amazon/Product.java
> +        }
Я бы вот так написал:

for (Product product : products) {
        result.computeIfAbsent(product.getCategory(), category -> new ArrayList<>())
              .add(product);
}

Вроде и то же самое, но вроде и понятнее

2024-06-07 10:05 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/amazon/Product.java
> +        }
Хорошо, спасибо

2024-06-07 13:53 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/amazon/Product.java
> +    }
Хорошо, сделал отдельный класс для этих методов

2024-06-09 01:30 UTC, pablo023 approved these changes
Отлично

2025-01-17 21:07 UTC, closed without merging