BJS2-8206 Java HashMap: Библиотека Вестеросса
CorporationX/god_bless pull request #5954
Opened 2024-06-04 14:26 UTC by one-shot-one-kill

2024-06-07 02:12 UTC, pablo023 requested changes
Пофикси логику

2024-06-07 02:12 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_8206/Main.java
> +    books.remove(new Book(title, author, year));
Удалять через создание нового объекта - это антипаттерн. Найи её, и именно удали.

2024-06-07 02:12 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_8206/Main.java
> +    books.remove(new Book(title, author, year));
Плюс тут ты удаляешь то, чего может и не быть по сути то в мапе.

2024-06-07 02:12 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_8206/Main.java
> +    return books.get(new Book(title, author, year));
Тоже, ищешь через создание. А вдруг книги этой нет?

2024-06-07 09:27 UTC, one-shot-one-kill commented on src/main/java/faang/school/godbless/BJS2_8206/Main.java
> +    books.remove(new Book(title, author, year));
Исправлено

2024-06-07 09:27 UTC, one-shot-one-kill commented on src/main/java/faang/school/godbless/BJS2_8206/Main.java
> +    return books.get(new Book(title, author, year));
Исправлено

2024-06-09 01:05 UTC, pablo023 approved these changes
На данный момент весьма неплохо. Я искренне надеюсь, что ты пишешь это сам, и осознаешь, что ты пишешь. Почти что отлично. Могу научить лучше, на следующем спринте будем разбирать лямбы и стримы как раз, там я расскажу о том, что имеет смысл делать, что - не всегда. Едем дальше)

2025-01-17 21:07 UTC, closed without merging