nikittta-BJS2-7898
CorporationX/god_bless pull request #5963
Opened 2024-06-04 16:34 UTC by Nikita2768

2024-06-05 19:09 UTC, pablo023 requested changes
Класс Battlefield не реализовал. Исправь мелкие недочеты, что я указал, и напиши класс этот.

2024-06-05 19:09 UTC, pablo023 commented on src/main/java/faang/school/godbless/Hero.java
> +        if(creature == null || quantity == 0) {
А что если у нас в армии 10 существ, а ремувнуть мы решили 100?

2024-06-05 19:09 UTC, pablo023 commented on src/main/java/faang/school/godbless/creation/Angel.java
> +public class Angel extends Creature{
extends Creature {

Вот эти пробелы не забывай пожалуйста. Есть комбинация crtl + alt + L - она автоматически исправляет форматирование.

2024-06-08 19:30 UTC, pablo023 approved these changes
Молодец. Но просьба - пиши попроще. То, что оно работает, это, конечно, хорошо. Но очень важно думать о том, насколько твой код прозрачен.

2024-06-08 19:30 UTC, pablo023 commented on src/main/java/faang/school/godbless/hero/Battlefield.java
Сложно сделал, конечно, но интересно. За креативность +

2024-06-09 07:07 UTC, Nikita2768 commented on src/main/java/faang/school/godbless/hero/Battlefield.java
Стараюсь сделать как можно проще, но только начал изучать стримы и до другого не додумался.

2025-01-17 21:08 UTC, closed without merging