BJS2-8209: Библиотека Вестероса
CorporationX/god_bless pull request #5974
Opened 2024-06-04 17:51 UTC by EvMalk

2024-06-07 02:16 UTC, pablo023 requested changes
Хотя нет, всё таки верну. Надо же тебе подсвечивать хоть какие-то слабые места))

2024-06-07 02:16 UTC, pablo023 commented on src/main/java/faang/school/godbless/library/Main.java
> +      books.remove(bookForRemove);
Вот уж не думал, что попадешься где-то) Возвращать не буду, но проверку на то, что книга есть в библиотеке не сделал)

2024-06-07 02:16 UTC, pablo023 commented on src/main/java/faang/school/godbless/library/Main.java
> +      return books.get(bookKey);
Тоже не проверил)

2024-06-10 08:33 UTC, malkov34 commented on src/main/java/faang/school/godbless/library/Main.java
> +      books.remove(bookForRemove);
Поправил

2024-06-10 08:34 UTC, malkov34 commented on src/main/java/faang/school/godbless/library/Main.java
> +      return books.get(bookKey);
и тут)

2024-06-11 02:17 UTC, pablo023 approved these changes

2024-06-13 09:36 UTC, merged