UsersByAge
CorporationX/god_bless pull request #5996
Opened 2024-06-04 22:05 UTC by GevorgSogomonian

Вероятно есть более изящное решение, но я дошел только до такого

2024-06-05 12:02 UTC, pablo023 requested changes
В целом хорошо. По комментам отметил, что можно сделать лучше)

2024-06-05 12:02 UTC, pablo023 commented on src/main/java/faang/school/godbless/User.java
> +            if (!allAges.contains(userData.get(i).age)) {
Это будет работать, но это не очень легко читается. Давай мы здесь на итерировании по циклу будем разделять пользователя, как значение, которое мы будем добавлять в список, и его возраст, как ключ. И в целом тут удобнее было бы пройтись циклом for each, почитай про него)

2024-06-05 12:04 UTC, pablo023 commented
Называй ПР в соответствии с таской) First try - не описывает, что тут в ПР'е

2024-06-05 15:04 UTC, GevorgSogomonian commented
Исправил решение, теперь использую один for

2024-06-05 17:46 UTC, pablo023 requested changes

2024-06-05 17:46 UTC, pablo023 commented on src/main/java/faang/school/godbless/Application.java
Я понял, ты это для тестов использовал, перед отправкой на ПР убирай это, пожалуйста)

2024-06-05 17:46 UTC, pablo023 commented on src/main/java/faang/school/godbless/User.java
> +            if (!result.containsKey(user.age)) {
Вот тут ты получаешь доступ к полю age просто через объект. Хоть в данном случае это и будет работать, это не гуд. Используй геттеры для получения доступа к полям.

2024-06-05 17:46 UTC, pablo023 commented on src/main/java/faang/school/godbless/User.java
Давай сделаем имплементиуем toString() для класса юзер, т.к. сейчас оно будет выводить просто ссылки на объекты в памяти.

2024-06-06 00:28 UTC, pablo023 approved these changes

2024-06-06 00:28 UTC, pablo023 commented on src/main/java/faang/school/godbless/User.java
> +    public String toString() {
Окей. Теперь запомни- toString, equals, hashCode - такие методы, которые закидываются в самый конец, т.к. знаешь - оно нерелеватное абсолютно, и каждый дев ожидает увидеть их где-то в самом конце, после методов с логикой. Не "до". Обычно так идет:

1) Поля, от приватных к публичным
2) Конструкторы
3) Геттеры - сеттеры (если они вообще есть, их чаще аннотациями создают)
4) Логика
5) Методы класса Object переимплемеченые

Я пропускаю, но пофикси это.

2025-01-17 21:08 UTC, closed without merging