Gevorg bjs2 7837
CorporationX/god_bless pull request #6027
Opened 2024-06-05 09:41 UTC by GevorgSogomonian

2024-06-05 18:42 UTC, pablo023 requested changes

2024-06-05 18:42 UTC, pablo023 commented on src/main/java/faang/school/godbless/User.java
> +            throw new IllegalArgumentException();
Добавляй сообщения в исключения выбрасываемые, и сделай для каждой валидации отдельное.

2024-06-05 18:42 UTC, pablo023 commented on src/main/java/faang/school/godbless/User.java
> +        return result;
Это, конечно, сработает. Но... Можно написать элегантнее) Подумай над тем, чтобы вот убрать шаг с allAges. И temporaryList. Чисто из-за этого я бы не вернул, но раз уж первое править будешь, это тоже сделай.

2024-06-05 21:06 UTC, GevorgSogomonian commented on src/main/java/faang/school/godbless/User.java
> +        return result;
Исправил это в предыдущей задаче, но забыл внести изменения в эту)

2024-06-06 00:54 UTC, pablo023 approved these changes
Пропускаю, но исправь везле illEgal, и по туСтринг подумай.

2024-06-06 00:54 UTC, pablo023 commented on src/main/java/faang/school/godbless/User.java
> +    public String toString() {
Просто перечисление полей - не очень красиво. Пропущу, но в следующий раз подумай, как сделать покрасивее тут.

2024-06-06 00:54 UTC, pablo023 commented on src/main/java/faang/school/godbless/User.java
> +            throw new IllegalArgumentException(address + " is Illigal address");
illEgal. Пропущу, но проверяй себя, и исправь.

2025-01-17 21:08 UTC, closed without merging