Ravshanbekn bjs2 7955
CorporationX/god_bless pull request #6055
Opened 2024-06-05 16:22 UTC by ravshanbekn

2024-06-06 01:06 UTC, pablo023 requested changes
В целом найс, есть минорные замечания

2024-06-06 01:06 UTC, pablo023 commented on src/main/java/faang/school/godbless/sword_magic/Hero.java
> +        if(experience < 0){
форматирование

2024-06-06 01:06 UTC, pablo023 commented on src/main/java/faang/school/godbless/sword_magic/Hero.java
> +        if(level < 0){
тут тоже

2024-06-06 01:06 UTC, pablo023 commented on src/main/java/faang/school/godbless/sword_magic/Hero.java
> +        army = new HashMap<>();
А тут чего без this?

2024-06-06 01:06 UTC, pablo023 commented on src/main/java/faang/school/godbless/sword_magic/Hero.java
> +        // Если уже содержится такой тип персонажа, то нужно добавить новых персонажей поверх старых
Твой код должен это полностью описывать, комменты не нужны)

2024-06-06 01:06 UTC, pablo023 commented on src/main/java/faang/school/godbless/sword_magic/Hero.java
> +        BigDecimal damage = new BigDecimal(0);
Вот тут бы я не против был бы увидеть коммент - зачем нам биг децимал)

2024-06-06 01:06 UTC, pablo023 commented on src/main/java/faang/school/godbless/sword_magic/Hero.java
> +            armor = armor.add(finalArmor);
Сильно усложнил) Биг децимал излишен. Если хочешь тут красиво сделать - выделяй отдельными методами.

2024-06-06 01:06 UTC, pablo023 commented on src/main/java/faang/school/godbless/sword_magic/Hero.java
> +    public void showArmy(){
Форматирование

2024-06-06 08:33 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/sword_magic/Hero.java
> +    public void showArmy(){
Ты это имеешь ввиду?

2024-06-07 01:37 UTC, pablo023 commented on src/main/java/faang/school/godbless/sword_magic/Hero.java
> +    public void showArmy(){
Да

2024-06-07 01:45 UTC, pablo023 requested changes
Про бигдецимал расписал.

2024-06-07 01:45 UTC, pablo023 commented on src/main/java/faang/school/godbless/sword_magic/Hero.java
> +        // хотя у них все характеристики равные
Забей на это. БигДецимал используется в фин техе каком-то, где вот эти дроби могут не сойтись, и потом будут жесткие разборки, из-за несхождения сумм. Либо в какой-то низкоуровневой инженерии. Здесь у тебя погрешность 0.01, и из за нее ты расхожуешь где-то байтов на 80 больше на каждый BigDecimal, вместо примитивов. Я бы вообще тут до интов округлял. Когда ты придешь на работу, тебе нужно будет демонстрировать навыки, которые покажут, что ты знаешь, что и где уместно. БигДецимал уместен только там, где я тебе описал.

2024-06-07 01:45 UTC, pablo023 commented on src/main/java/faang/school/godbless/sword_magic/Hero.java
> +    private int experience;  // Влияет на damage армии
Почисить комменты. В целом их не должно быть. А если пишешь - пиши на английском.

2024-06-07 13:39 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/sword_magic/Hero.java
> +        // хотя у них все характеристики равные
Хорошо

2024-06-07 13:40 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/sword_magic/Hero.java
> +    private int experience;  // Влияет на damage армии
Хорошо

2024-06-08 00:24 UTC, pablo023 approved these changes

2025-01-17 21:08 UTC, closed without merging