Java HashMap: Кэшируем, кэшируем
CorporationX/god_bless pull request #6077
Opened 2024-06-05 19:20 UTC by legionerkz

created GlobalWeather, WeatherData and Main classes;
implemented all necessary methods.
GlobalWeather using Random for creating new temp and hummidity

2024-06-09 02:53 UTC, pablo023 requested changes

2024-06-09 02:53 UTC, pablo023 commented on src/main/java/faang/school/godbless/Main.java
> +    public static void updateWeatherByCity(String city) {
а если нет в кэше?

2024-06-09 02:53 UTC, pablo023 commented on src/main/java/faang/school/godbless/Main.java
> +        cache.remove(city);
А если нет в кэше?

2024-06-09 16:14 UTC, legionerkz commented on src/main/java/faang/school/godbless/Main.java
> +    public static void updateWeatherByCity(String city) {
Добавил инфо о погоде в кэш если нет города в кэше

2024-06-09 16:14 UTC, legionerkz commented on src/main/java/faang/school/godbless/Main.java
> +        cache.remove(city);
исправил

2024-06-11 02:53 UTC, pablo023 approved these changes
Молодец. Едем дальше

2025-01-17 21:08 UTC, closed without merging