BJS2-7907 Java HashMap: Герои меча и магии
CorporationX/god_bless pull request #6104
Opened 2024-06-06 09:02 UTC by one-shot-one-kill

2024-06-07 01:36 UTC, pablo023 requested changes
Я вот этот гет дэмедж не понял. Можешь объяснить? Либо убрать, если не можешь.

2024-06-07 01:36 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_7907/Angel.java
> +  public int getDamage() {
А зачем нам геттер, который возвращает другой геттер? Я понял, у тебя в Creature есть он, и тебе нужно было оверрайднуть - так а нужен ли он в кричере тогда? Мы же по сути два метода на одно и то же используем.

2024-06-07 09:27 UTC, one-shot-one-kill commented on src/main/java/faang/school/godbless/BJS2_7907/Angel.java
> +  public int getDamage() {
Исправлено

2024-06-08 00:05 UTC, pablo023 approved these changes
Я пропущу это, но добавь логику для ничьей, и скинь потом в чат командый

2024-06-08 00:05 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_7907/Battlefield.java
> +  }
Почему мы ничью не рассматриваем?

2025-01-17 21:08 UTC, closed without merging