Ravshanbekn bjs2 8655
CorporationX/god_bless pull request #6171
Opened 2024-06-06 20:46 UTC by ravshanbekn

2024-06-07 02:55 UTC, pablo023 requested changes
Небольшие недочеты, переделай.

2024-06-07 02:55 UTC, pablo023 commented on src/main/java/faang/school/godbless/google_search/WebPage.java
> +    }
Смотри. Объект - это объект. В нем редко должны быть методы, а если и должны - то по логике, которые этот объект сам может сделать. Вот к примеру представь себе историю - товар. Чтобы положить товар на полку  - что нужно? Нужен кто-то, кто может его положить на полку. Не может же товар сам себя на полку положить, так? Вот тут примерно та же история, веб-страница как бы сама себя в индекс добавляет. Это неправильно с точки зрения ООП. Поэтому если методы нелоично помещать в объект, выноси их куда-то. Либо в мейн пока что, либо в отдельный класс, который вот эти методы будет предоставлять. Сервис какой-нибудь.

2024-06-07 02:55 UTC, pablo023 commented on src/main/java/faang/school/godbless/google_search/WebPage.java
> +        return webPageMap.get(keyWord.toLowerCase());
А если нет её там?

2024-06-07 13:54 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/google_search/WebPage.java
> +    }
Исправил

2024-06-07 13:55 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/google_search/WebPage.java
> +        return webPageMap.get(keyWord.toLowerCase());
Исправил

2024-06-09 02:35 UTC, pablo023 approved these changes
Очень хорошо!

2024-06-09 02:35 UTC, pablo023 commented on src/main/java/faang/school/godbless/google_search/Browser.java
> +        keyWord = keyWord.toLowerCase();
ух ты, молодец какой

2025-01-17 21:08 UTC, closed without merging