Vanek bjs2 7905
CorporationX/god_bless pull request #6188
Opened 2024-06-07 10:52 UTC by vanekJpeg

2024-06-08 00:00 UTC, pablo023 requested changes
Пофикси по логике и корнер-кейсу

2024-06-11 01:26 UTC, pablo023 requested changes

2024-06-11 01:26 UTC, pablo023 commented on src/main/java/faang/school/godbless/homm3/Hero.java
> +        } else army.get(creature.getName()).setQuantity(army.get(creature.getName()).getQuantity() - quantity);
else {
    code
}

Вот так надо. И не пофиксил ситуацию, в которой дается на инпут колличество большее, чем в армии есть. Если в армии их 50, а сказали удалить 500, у тебя будет -450 существ в армии. Это неправильно.

2024-06-11 06:38 UTC, vanekJpeg commented on src/main/java/faang/school/godbless/homm3/Hero.java
> +        } else army.get(creature.getName()).setQuantity(army.get(creature.getName()).getQuantity() - quantity);
в 24 25 пофиксил же?

2025-01-17 21:08 UTC, closed without merging