Объединила решение в одном коде
CorporationX/god_bless pull request #6192
Opened 2024-06-07 11:58 UTC by KateAle

Задача BJS2-7540 Группировка пользователей по возрасту; Задача BJS2-7844 Регистрация пользователей

2024-06-07 23:49 UTC, pablo023 requested changes

2024-06-07 23:49 UTC, pablo023 commented on src/main/java/faang/school/godbless/Kate/BJS2_7540_7844/User.java
> +            if (name.isEmpty() || age<18 || !(VALID_JOBS.contains(job)) ||
Для каждой проверки нужно кидать отдельный эксепшен, с сообщением - что именно пошло не так. Так как сейчас у тебя метод будет падать, а почему - непонятно. Исправь это.

2024-06-11 01:27 UTC, pablo023 requested changes

2024-06-11 01:27 UTC, pablo023 commented on src/main/java/faang/school/godbless/Kate/BJS2_7540_7844/User.java
> +        return;
Смотри. Трай кетч мы не используем для RuntimeException, и всех его подклассов, коим является IllegalArgumentException. Условно - когда мы ловим эксепшены - когда они могут происходить при том, что всё было нормально в принципе. Например, скачка файла. Всё шло окей, но интернет отключило, и загрузка оборавалсь - такой эксепшен имеет смысл ловить, и как-то хэндлить. А здесь у тебя эксепшен летит, когда сделано что-то, что не должно было быть сделано - поданы невалидные данные. На них просто должен вылететь эксепшен, который об этом сообщит, и все.

2024-06-11 01:27 UTC, pablo023 commented on src/main/java/faang/school/godbless/Kate/BJS2_7540_7844/User.java
> +        return;
Также отдельный момент - пустой блок catch. В ситуациях, когда он нужен нам, мы там что-то делаем с ситуацией, как-то её либо исправляем, либо документируем. Но не просто оставляем как есть, или просто возвращаем ничто, как тут.

2024-06-11 01:27 UTC, pablo023 commented on src/main/java/faang/school/godbless/Kate/BJS2_7540_7844/User.java
> +    }
Не надо так) Учимся писать красиво сразу. В джаве не должно быть двух фигурных скобок, одна над другой. Где-то тт индентация съехала. Привыкай писать правильно либо рукой, либо используя каждый раз комбинацию ctrl + alt + L - она исправит всё сама.

2024-06-11 01:27 UTC, pablo023 commented on src/main/java/faang/school/godbless/Kate/BJS2_7540_7844/User.java
> +        return age;
Так можно, но не нужно. Используй ключевое слово this, чтобы выразить, что операция осуществляется не над полем класса, а над полем сущности. return this.age

2024-06-11 01:27 UTC, pablo023 commented on src/main/java/faang/school/godbless/Kate/BJS2_7540_7844/User.java
> +
Убираем это.

2024-06-11 11:07 UTC, KateAle commented on src/main/java/faang/school/godbless/Kate/BJS2_7540_7844/User.java
> +        return;
хотела сделать так, чтобы программа продолжила выполнение без создания экземпляра класса

2024-06-11 11:08 UTC, KateAle commented on src/main/java/faang/school/godbless/Kate/BJS2_7540_7844/User.java
> +    }
ок, кажется, она у меня не всегда срабатывает)

2024-06-11 11:08 UTC, KateAle commented on src/main/java/faang/school/godbless/Kate/BJS2_7540_7844/User.java
> +        return age;
Принято

2024-06-11 23:24 UTC, pablo023 approved these changes

2024-06-11 23:24 UTC, pablo023 commented on src/main/java/faang/school/godbless/Kate/BJS2_7540_7844/User.java
> +    private Set<String> VALID_JOBS = new HashSet<>(Arrays.asList("Google", "Uber", "Amazon"));
В данном случае, Set.of() подошло бы, и было бы элегантнее

2024-06-11 23:24 UTC, pablo023 commented on src/main/java/faang/school/godbless/Kate/BJS2_7540_7844/User.java
> +        } else if (age < 18) {
Почитай про антипаттерн "магическое число"

2024-06-11 23:30 UTC, merged

2024-06-14 09:12 UTC, KateAle commented on src/main/java/faang/school/godbless/Kate/BJS2_7540_7844/User.java
> +    private Set<String> VALID_JOBS = new HashSet<>(Arrays.asList("Google", "Uber", "Amazon"));
Что-то у меня с Set.of тогда не сложилось, идея ругалась, и пришлось пойти другим путем

2024-06-14 09:12 UTC, KateAle commented on src/main/java/faang/school/godbless/Kate/BJS2_7540_7844/User.java
> +        } else if (age < 18) {
👌🏻