Game Of Thrones
CorporationX/god_bless pull request #6195
Opened 2024-06-07 12:56 UTC by GevorgSogomonian

2024-06-08 00:27 UTC, pablo023 commented
Ты создал бранч из мастера. Это неправильно - видиь у тебя ошибка вылезла. Создай из мастера бранч со своим ником, и из него уже создавай бранчи под таски.

2024-06-08 07:41 UTC, GevorgSogomonian commented
Когда делал этот PR забыл поменять ветку с master на свою(Gevorg), вылезло то сообщение сверху, я понял, что ошибся, и исправил по инструкции в этом сообщении. Сейчас там вроде все в порядке, просто сообщение не стал удалять

2024-06-08 21:14 UTC, pablo023 requested changes
Чет для части ты обработал ошибки, для части - нет. Давай для всех сделаем, и дальше поедем.

2024-06-08 21:14 UTC, pablo023 commented on src/main/java/faang/school/godbless/Main.java
> +        System.out.println(houses.get(name).getSigil());
А если нет такого дома?

2024-06-08 21:14 UTC, pablo023 commented on src/main/java/faang/school/godbless/Main.java
> +        houses.put(house.getName(), house);
А если есть уже этот дом в мапе?

2024-06-11 05:23 UTC, GevorgSogomonian commented on src/main/java/faang/school/godbless/Main.java
> +        System.out.println(houses.get(name).getSigil());
Исправил

2024-06-11 05:23 UTC, GevorgSogomonian commented on src/main/java/faang/school/godbless/Main.java
> +        houses.put(house.getName(), house);
Исправил

2024-06-11 23:52 UTC, pablo023 approved these changes
Молодец

2024-06-11 23:55 UTC, merged