Задача BJS2-7641 Развернитесь!
CorporationX/god_bless pull request #6197
Opened 2024-06-07 12:59 UTC by KateAle

2024-06-07 23:56 UTC, pablo023 requested changes

2024-06-07 23:56 UTC, pablo023 commented on src/main/java/Kate/BJS2_7641/Example.java
> +    public static int[] reverse(int[] nums, int lngth){
Исправь форматирование

2024-06-07 23:56 UTC, pablo023 commented on src/main/java/Kate/BJS2_7641/Example.java
> +    public static int[] reverse(int[] nums, int lngth){
Зачем нам передавать в метод переменную lngth, если мы можем получать длину массива по полю nums.length?

2024-06-07 23:56 UTC, pablo023 commented on src/main/java/Kate/BJS2_7641/App7641.java
> +public class App7641 {
А почему этот класс называется App7641?)

2024-06-07 23:56 UTC, pablo023 commented on src/main/java/Kate/BJS2_7641/Example.java
> +            }
Это - не совсем по условию задачи. Смотри - тебе нужно реализовать метод reverse(), который принимает только массив целых чисел, и его же и разворачивает. Мы не создаем внутри новый массив, и ничего не возвращаем из метода.

2024-06-11 10:59 UTC, KateAle commented on src/main/java/Kate/BJS2_7641/App7641.java
> +public class App7641 {
по номеру задачи) исправила

2024-06-11 10:59 UTC, KateAle commented on src/main/java/Kate/BJS2_7641/Example.java
> +    public static int[] reverse(int[] nums, int lngth){
думала, что нужно получить новый массив той же длины

2024-06-11 10:59 UTC, KateAle commented on src/main/java/Kate/BJS2_7641/Example.java
> +            }
Принято

2024-06-11 23:27 UTC, pablo023 requested changes
Неправильная логика метода

2024-06-11 23:27 UTC, pablo023 commented on src/main/java/Kate/BJS2_7641/Example.java
> +            System.out.print(nums[i]+ " ");
Не так. Нам нужно не вывести в обратную сторону нумс, а изменить его так, чтобы он стал "развернутым". То есть, преобразовать входной массив так, чтобы он "развернулся".

2025-01-17 21:08 UTC, closed without merging