Library of Westeros
CorporationX/god_bless pull request #6218
Opened 2024-06-07 18:03 UTC by GevorgSogomonian

2024-06-09 01:16 UTC, pablo023 requested changes
Два коммента.

2024-06-09 01:16 UTC, pablo023 commented on src/main/java/faang/school/godbless/Main.java
> +    }
Никогда не создавай объект для того, чтобы найти его в коллекции, или удалить. Ищи в самой коллекции по полям, никогда не создавай для того, чтобы найти, или удалить.

2024-06-09 01:16 UTC, pablo023 commented on src/main/java/faang/school/godbless/Main.java
> +        Book necessaryBook = new Book(title, author, age);
Аналогично. Я бы рад это пропустить, но не могу. Ты должен запомнить, что никогда так делать нельзя, и осозавал - почему. Смотри. Во-первых, это просто логично. Ты же если хочешь найти что-то в ящике - пойдешь смотреть в ящике есть ли оно, правильно? В данном случае то же самое - тебе не нужен объект, чтобы найти его, или удалить. Ищи по коллекции. Второе - это память. Создавая новый объект, ты выделяешь под него память. На примере этой задачи это пофигу абсолютно, но в реальной работе это просто недопустимо, с точки зрения лучших практик. А вдруг у тебя будет проект, на котором операция поиска выполняется тысячи, или десятки тысяч раз в минуту? И объект там - не книга из трех полей, а структура данных. Это у нас приложение упадет попросту, потому что не будет хватать памяти. В общем. Никогда так не делай) Исправь это.

2024-06-09 06:37 UTC, GevorgSogomonian commented on src/main/java/faang/school/godbless/Main.java
> +    }
Исправил

2024-06-09 06:37 UTC, GevorgSogomonian commented on src/main/java/faang/school/godbless/Main.java
> +        Book necessaryBook = new Book(title, author, age);
Согласен, исправил

2024-06-11 02:20 UTC, pablo023 approved these changes

2024-06-11 02:20 UTC, pablo023 commented on src/main/java/faang/school/godbless/Main.java
> +        return "There is no " + "|" + title + "| |" + author + "|  " + year;
Это надо не через return, а эксепшеном кидать. Потому что если метод что-то вернул, это значит, что он выполнил ожидаемый от него контракт. Соотвественно - то, что его вызвало, например, фронтенд, ожидает название книги. А тут не оно. Возвращать из-за этого не буду, но в дальнейшеи - буду.

2025-01-17 21:08 UTC, closed without merging