Java HashMap: Герои Меча и Магии
CorporationX/god_bless pull request #6226
Opened 2024-06-07 19:39 UTC by legionerkz

Implemented all classes

2024-06-08 00:21 UTC, pablo023 requested changes
Немного тут импрувни.

2024-06-08 00:21 UTC, pablo023 commented on src/main/java/faang/school/godbless/Battlefield.java
> +    }
А почему у нас если разница силы атаки первого героя и защиты второго больше, чем разница силы атаки второго, и защиты первого, то он обязательно побеждает? Если она не больше, она ведь может быть не только меньше, они могут и равны быть. Я думаю, тут надо подумать ещё.

2024-06-08 00:21 UTC, pablo023 commented on src/main/java/faang/school/godbless/Hero.java
> +                army.merge(creature, -quantity, Integer::sum);
На мой взгляд, army.put(creature, army.get(creature) + quantity было бы чище. Не настаиваю, возможно это просто моя привычка.

2024-06-08 00:21 UTC, pablo023 commented on src/main/java/faang/school/godbless/Hero.java
> +        Optional<Integer> attack = getArmy().entrySet().stream().map(x -> x.getKey().getDamage() * x.getValue()).reduce(Integer::sum);
Лучше использовать отобразительный нейминг. Вот это x - это что? В контексте задачи, мне понятно, что это, в контексте работы на проекте, когда он здоровый, и твой код читает человек, который проект знает плохо, такой нейминг очень много головной боли может доставить. Давай писать сразу профессионально)

2024-06-08 00:22 UTC, pablo023 commented on src/main/java/faang/school/godbless/Hero.java
> +        Optional<Integer> attack = getArmy().entrySet().stream().map(x -> x.getKey().getDamage() * x.getValue()).reduce(Integer::sum);
Там этот х еще и в другом методе есть.

2024-06-08 22:11 UTC, legionerkz commented on src/main/java/faang/school/godbless/Hero.java
> +                army.merge(creature, -quantity, Integer::sum);
тут поменял!

2024-06-08 22:11 UTC, legionerkz commented on src/main/java/faang/school/godbless/Hero.java
> +        Optional<Integer> attack = getArmy().entrySet().stream().map(x -> x.getKey().getDamage() * x.getValue()).reduce(Integer::sum);
Изменил +

2024-06-11 01:30 UTC, pablo023 approved these changes
Молодец

2025-01-17 21:08 UTC, closed without merging