Counting absenteeism
CorporationX/god_bless pull request #6230
Opened 2024-06-07 20:41 UTC by GevorgSogomonian

2024-06-08 21:49 UTC, pablo023 requested changes
Пока что я отметить могу только это. Поправь это - я сделаю ревью после, еще раз

2024-06-08 21:49 UTC, pablo023 commented on src/main/java/faang/school/godbless/Flow.java
> +    private int year;
Flow - это поток по-английски. Поток чего-то физического, в прямом смысле - когда что-то движется из точки А в точку Б. Также это состояние, которое мы называем в "потоке". На этом, пожалуй, всё. В данном контексет это непреминимый термин, который меня очень сбил с толку) AcademicYear, Grade, Stage - вот это бы тут подошло.

2024-06-08 21:49 UTC, pablo023 commented on src/main/java/faang/school/godbless/Main.java
> +            if (allInfo.containsKey(flow) && !allInfo.get(flow).contains(student)) allInfo.get(student).add(student);
Ой ой ой. Вот это не хорошо) Абсолютно, АБСОЛЮТНО всегда пиши ифы через фигурные скобки. Даже если там одно условие всего, это не имеет значения. Вот так, как сейчас - никогда так не пиши)

2024-06-08 21:49 UTC, pablo023 commented on src/main/java/faang/school/godbless/Main.java
> +    private static Map<Student, Integer> hashStudents = new HashMap<>();
studentsMap было бы уместнее. На данный момент переменная типа - хэш студентов. Эт чет не то)

2024-06-08 21:49 UTC, pablo023 commented on src/main/java/faang/school/godbless/Main.java
> +                allInfo.put(flow, studentsOnFlow);
Мне не очень нравится этот кусок. У нас как будто в списке гарантированно - только студенты, которые у нас есть. А если нет такого студента в университете, который в списке был? А мы его получается засунем в мапу, которую возвращаем.

2024-06-09 05:21 UTC, GevorgSogomonian commented on src/main/java/faang/school/godbless/Main.java
> +    private static Map<Student, Integer> hashStudents = new HashMap<>();
Пофиксил

2024-06-09 05:22 UTC, GevorgSogomonian commented on src/main/java/faang/school/godbless/Main.java
> +            if (allInfo.containsKey(flow) && !allInfo.get(flow).contains(student)) allInfo.get(student).add(student);
Понял принял, больше так не буду)

2024-06-09 06:01 UTC, GevorgSogomonian commented on src/main/java/faang/school/godbless/Main.java
> +                allInfo.put(flow, studentsOnFlow);
Исправил. Изначально не правильно понял описание для этого метода

2024-06-09 06:06 UTC, GevorgSogomonian commented on src/main/java/faang/school/godbless/Flow.java
> +    private int year;
Понял, исправил)

2024-06-11 02:12 UTC, pablo023 requested changes

2024-06-11 02:12 UTC, pablo023 commented on src/main/java/faang/school/godbless/Main.java
> +        Student student = new Student(name, faculty, course);
Не создавай объект там, где нужно что-то удалить

2024-06-11 02:12 UTC, pablo023 commented on src/main/java/faang/school/godbless/Main.java
> +    private static List<Student> students= new ArrayList<>();
пробел перед "=" пропустил

2024-06-11 02:12 UTC, pablo023 commented on src/main/java/faang/school/godbless/Main.java
> +    private static Map<Student, Integer> studentsMap = new HashMap<>();
А зачем тебе эта мапа вообще?

2024-06-11 02:12 UTC, pablo023 commented on src/main/java/faang/school/godbless/Main.java
> +            }
Честно говоря, я не понимаю, зачем это тут делается с мапой вообще) У нас метод должен просто выпилить судента из списка, всё

2024-06-11 05:33 UTC, GevorgSogomonian commented on src/main/java/faang/school/godbless/Main.java
> +            if (allInfo.containsKey(flow) && !allInfo.get(flow).contains(student)) allInfo.get(student).add(student);
Исправил

2024-06-11 05:33 UTC, GevorgSogomonian commented on src/main/java/faang/school/godbless/Main.java
> +    private static List<Student> students= new ArrayList<>();
Исправил

2024-06-11 05:56 UTC, GevorgSogomonian commented on src/main/java/faang/school/godbless/Main.java
> +    private static Map<Student, Integer> studentsMap = new HashMap<>();
Исправил

2024-06-11 05:56 UTC, GevorgSogomonian commented on src/main/java/faang/school/godbless/Main.java
> +            }
Исправил

2024-06-11 05:58 UTC, GevorgSogomonian commented on src/main/java/faang/school/godbless/Main.java
> +        Student student = new Student(name, faculty, course);
Исправил

2024-06-11 23:55 UTC, pablo023 approved these changes

2025-01-17 21:08 UTC, closed without merging