Задача Абстракция, абстракция!
CorporationX/god_bless pull request #6255
Opened 2024-06-08 12:11 UTC by KateAle

2024-06-08 19:11 UTC, pablo023 requested changes
Поправь немного по комментариям.

2024-06-08 19:11 UTC, pablo023 commented on src/main/java/BJS2_7733/Character.java
> +    public int power, skill, intellect;
Не пиши поля в одну строчку, это не лучшая практика - хуже читается. Каждое на отдельной строке лучше.

2024-06-08 19:11 UTC, pablo023 commented on src/main/java/BJS2_7733/Archer.java
> +public class Archer extends Character{
Исправь форматирование. Привыкай либо писать чисто рукой, либо после написания всегда использовать комбинацию ctrl + alt + L.

2024-06-08 19:11 UTC, pablo023 commented on src/main/java/BJS2_7733/Archer.java
> +
Между методами одна пустая строка должна быть

2024-06-08 19:11 UTC, pablo023 commented on src/main/java/BJS2_7733/Character.java
> +
Лишняя пустая строка

2024-06-11 12:41 UTC, KateAle commented on src/main/java/BJS2_7733/Character.java
> +    public int power, skill, intellect;
Принято

2024-06-11 23:28 UTC, pablo023 approved these changes

2025-01-17 21:08 UTC, closed without merging