done task registration users for review
CorporationX/god_bless pull request #6406
Opened 2024-06-10 09:19 UTC by shade2903

done task

2024-06-12 19:33 UTC, pablo023 requested changes

2024-06-12 19:33 UTC, pablo023 commented on src/main/java/faang/school/godbless/registratuon_users/User.java
> +            throw new IllegalArgumentException();
Логируй с описательным сообщением каждую проверку отдельно.

18 - это антипаттерн магическое число. Почитай про него.

2024-06-13 16:28 UTC, shade2903 commented on src/main/java/faang/school/godbless/registratuon_users/User.java
> +            throw new IllegalArgumentException();
Magic number перенесены в константы.
Добален метод checkValidParam() с логированием исключительных ситуаций

2024-06-17 09:53 UTC, InnMish approved these changes

2024-06-17 09:53 UTC, merged