Абстракция, абстракция!
CorporationX/god_bless pull request #6441
Opened 2024-06-10 15:49 UTC by Kostahe

2024-06-12 19:13 UTC, pablo023 requested changes

2024-06-12 19:13 UTC, pablo023 commented on src/main/java/faang/school/godbless/task_3/Character.java
> +    Character(String name) {
Модификаторов доступа нет

2024-06-12 19:13 UTC, pablo023 commented on src/main/java/faang/school/godbless/task_3/Character.java
> +    Character(String name, int strength, int agility, int intelligence) {
Тут тоже)

2024-06-12 19:13 UTC, pablo023 commented on src/main/java/faang/school/godbless/task_3/Warrior.java
> +    }
Тут тоже)

2024-06-17 19:29 UTC, Kostahe commented on src/main/java/faang/school/godbless/task_3/Character.java
> +    Character(String name) {
Окей

2024-06-17 19:29 UTC, Kostahe commented on src/main/java/faang/school/godbless/task_3/Character.java
> +    Character(String name, int strength, int agility, int intelligence) {
Окей

2024-06-17 19:29 UTC, Kostahe commented on src/main/java/faang/school/godbless/task_3/Warrior.java
> +    }
Окей

2024-06-17 19:55 UTC, Kostahe reviewed
Фикснул модификаторы

2025-01-17 21:09 UTC, closed without merging