User registration
CorporationX/god_bless pull request #6442
Opened 2024-06-10 15:49 UTC by YPG0

2024-06-12 19:37 UTC, pablo023 requested changes
Поправь немного

2024-06-12 19:37 UTC, pablo023 commented on src/main/java/faang/school/godbless/User.java
> +        return age;
this.age* Не то, чтобы оно так не сработает, но так чище будет, если мы укажем, что вот конкретно про инстанс речь идет

2024-06-12 19:37 UTC, pablo023 commented on src/main/java/faang/school/godbless/User.java
> +            this.name = name;
Каждую проверку выполняй отдельно, и логируй с сообщением, которое конкретно говорить будет о том - что упало. Сейчас упало, и непонятно, почему.

2024-06-12 19:37 UTC, pablo023 commented on src/main/java/faang/school/godbless/User.java
> +            this.name = name;
И еще, 18 - антипаттерн магическое число. Почитай про это.

2024-06-13 15:42 UTC, YPG0 commented on src/main/java/faang/school/godbless/User.java
> +        return age;
Исправил

2024-06-13 15:43 UTC, YPG0 commented on src/main/java/faang/school/godbless/User.java
> +            this.name = name;
Проверку переписал одну в другую в каждую добавил сообщение о своем параметре. 18 вынес в константу "совершеннолетия".

2024-06-17 17:42 UTC, merged