Game of Thrones
CorporationX/god_bless pull request #6449
Opened 2024-06-10 16:13 UTC by YPG0

2024-06-12 19:46 UTC, pablo023 requested changes
Чуть не доделал

2024-06-12 19:46 UTC, pablo023 commented on src/main/java/faang/school/godbless/Main.java
> +    }
А чего бы нам не кинуть что-нибудь, если нет такого дома?

2024-06-12 19:46 UTC, pablo023 commented on src/main/java/faang/school/godbless/Main.java
> +    }
И тут тоже?

2024-06-13 16:11 UTC, YPG0 commented on src/main/java/faang/school/godbless/Main.java
> +    }
Разбил проверку на 2 части к каждой добавил свое описание в эксепшен

2024-06-17 17:54 UTC, merged