Library of Westeros
CorporationX/god_bless pull request #6451
Opened 2024-06-10 16:18 UTC by YPG0

2024-06-12 19:59 UTC, pablo023 requested changes

2024-06-12 19:59 UTC, pablo023 commented on src/main/java/faang/school/godbless/Main.java
> +            System.out.println("Переданны пустые данные");
Не в консоль выводи, а кидай эксепшен. Ну это на будущее, тут ладно.

2024-06-12 19:59 UTC, pablo023 commented on src/main/java/faang/school/godbless/Main.java
> +            Book deleteBook = new Book(name, author, years);
Не создавай объект для операций удаления.

2024-06-12 19:59 UTC, pablo023 commented on src/main/java/faang/school/godbless/Main.java
> +            Book searchBook = new Book(name, author, years);
Не создавай объект для операций поиска. Это неоптимаьное использование ресурсов. Тут это пройдет, а если у тебя программа выполняет поисковые закросы тысячи раз в секунду? Ну не дело)

2024-06-14 15:06 UTC, YPG0 commented on src/main/java/faang/school/godbless/Main.java
> +            System.out.println("Переданны пустые данные");
Поменял

2024-06-14 15:22 UTC, YPG0 commented on src/main/java/faang/school/godbless/Main.java
> +            Book deleteBook = new Book(name, author, years);
Заменил создание объекта внутри метода на передачу его сразу в метод.

2024-06-14 15:23 UTC, YPG0 commented on src/main/java/faang/school/godbless/Main.java
> +            Book searchBook = new Book(name, author, years);
Сделал так же как и в прошлом комментарии

2024-06-17 18:04 UTC, merged