Counting absenteeism
CorporationX/god_bless pull request #6452
Opened 2024-06-10 16:25 UTC by YPG0

2024-06-12 19:53 UTC, pablo023 requested changes

2024-06-12 19:53 UTC, pablo023 commented on src/main/java/faang/school/godbless/Main.java
> +            return null;
Не возвращай нулл) Никогда))) Просто не делай этого, не надо так. Если не получилось найти студента - кинь эксепшн, и туда добавь сообщение. И не надо неймингов в духе x. Это что?))

2024-06-12 19:53 UTC, pablo023 commented on src/main/java/faang/school/godbless/Main.java
> +            System.out.println("Данные не верны");
Тут то же, что и в комменте выше.

2024-06-14 14:42 UTC, YPG0 commented on src/main/java/faang/school/godbless/Main.java
> +            return null;
Убрал null в методах. Вместо x теперь с нормальные названия

2024-06-14 14:42 UTC, YPG0 commented on src/main/java/faang/school/godbless/Main.java
> +            System.out.println("Данные не верны");
Поправил

2024-06-17 17:59 UTC, merged