Meta-universe?
CorporationX/god_bless pull request #6456
Opened 2024-06-10 16:42 UTC by YPG0

2024-06-20 03:57 UTC, pablo023 requested changes

2024-06-20 03:57 UTC, pablo023 commented on src/main/java/faang/school/godbless/Notification.java
> +        return message;
this.message

2024-06-20 03:57 UTC, pablo023 commented on src/main/java/faang/school/godbless/Notification.java
> +        return type;
this.type

2024-06-20 03:57 UTC, pablo023 commented on src/main/java/faang/school/godbless/NotificationManager.java
> +    public void registerHandler(String alerts, Consumer<Notification> consumer) {
Почему alerts? notificationId / notificationIdentifier / notificationType

2024-06-20 03:57 UTC, pablo023 commented on src/main/java/faang/school/godbless/NotificationManager.java
> +        map.get(notification.getType()).accept(notification);
А если нет этого нотификейшна в мапе??

2024-06-20 16:02 UTC, YPG0 commented on src/main/java/faang/school/godbless/NotificationManager.java
> +        map.get(notification.getType()).accept(notification);
Добавил проверку через if и если нету то выбрасываю експепшен

2024-06-20 16:05 UTC, YPG0 commented on src/main/java/faang/school/godbless/NotificationManager.java
> +    public void registerHandler(String alerts, Consumer<Notification> consumer) {
Исправил

2024-06-20 16:05 UTC, YPG0 commented on src/main/java/faang/school/godbless/Notification.java
> +        return message;
Поменял гетеры на @Getter

2024-06-20 16:06 UTC, YPG0 commented on src/main/java/faang/school/godbless/Notification.java
> +        return type;
Поменял гетеры на @Getter

2024-06-20 16:27 UTC, YPG0 commented
Перенес в отдельный пакет классы. При пуше ветка сломалась (как то забрала в себя классы и пакеты с нескольких других веток) вроде лишние удалил.

2024-06-21 09:58 UTC, InnMish approved these changes

2024-06-21 09:58 UTC, merged