Done task
CorporationX/god_bless pull request #6490
Opened 2024-06-10 20:37 UTC by shade2903

2024-06-12 19:56 UTC, pablo023 requested changes
Поправь по комментам.

2024-06-12 19:56 UTC, pablo023 commented on src/main/java/faang/school/godbless/vesteros_library/Main.java
> +        BOOKS.remove(new Book(title, author, year));
Во-первых, не создавай объект, чтобы что-то удалить. Во-вторых, у тебя как будто гарантировано, что эта книга есть в библиотеке. А если нет её?

2024-06-12 19:56 UTC, pablo023 commented on src/main/java/faang/school/godbless/vesteros_library/Main.java
> +        System.out.println(BOOKS.get(new Book(title, author, year)));
Аналогично с комментом выше

2024-06-13 19:33 UTC, shade2903 commented
методы  removeBook() и findBook() используют ключ возвращенный из мапы по полям которые приходят на вход. Я понимаю, что это очень затратная операция по перебору всех ключей и значений, но на данном этапе с моими скиллами пока пришла только такая идея.

2024-06-17 03:03 UTC, pablo023 approved these changes
Очень хорошо сделал.

2024-06-17 03:03 UTC, merged