Построим CSV
CorporationX/god_bless pull request #6527
Opened 2024-06-11 10:10 UTC by ravshanbekn

Initial Commit

2024-06-14 17:51 UTC, pablo023 requested changes

2024-06-14 17:51 UTC, pablo023 commented on src/main/java/faang/school/godbless/build_csv/CsvFormatter.java
> +    public static String toCsv(List<List<String>> table) throws IllegalArgumentException {
Не надо в сигнатуру метода указывать, что может быть выкинуто исключение типа Runtime

2024-06-14 17:51 UTC, pablo023 commented on src/main/java/faang/school/godbless/build_csv/CsvFormatter.java
> +
Не пиши так, пожалуйста. Это как-то тяжеловато на голову налезает, по сравнению с тем, что если просто по шагам распишешь)

2024-06-14 18:10 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/build_csv/CsvFormatter.java
> +    public static String toCsv(List<List<String>> table) throws IllegalArgumentException {
Хорошо

2024-06-14 18:20 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/build_csv/CsvFormatter.java
> +
Ты имеешь ввиду написать в "столбик"?

2024-06-15 21:14 UTC, pablo023 commented on src/main/java/faang/school/godbless/build_csv/CsvFormatter.java
> +
В столбик было бы лучше, конечно, но вообще я имею ввиду не делать прям вот все в одном стриме. А как-то иногда его на 2, а то и три дробить, чтобы проще понимать, что происходит

2024-06-15 21:14 UTC, pablo023 approved these changes
Аппрув, но - не осатвляй, пожалуйста, комменты в коде.

2024-06-15 21:14 UTC, merged

2024-06-15 21:26 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/build_csv/CsvFormatter.java
> +
Хорошо