Lord of the Rings RPG
CorporationX/god_bless pull request #6577
Opened 2024-06-11 16:47 UTC by legionerkz

Created classes: Character, InventoryManager, Item and Main
Implemented all methods using lambdas.  All functionality has been tested into the Main class.

2024-06-13 18:09 UTC, pablo023 commented
У тебя не все файлы попали в ПР. Я не вижу InventoryManager

2024-06-13 18:09 UTC, pablo023 requested changes
Ты по ходу только мейн закоммитил

2024-06-13 19:15 UTC, legionerkz commented
Сорян, добавил все

2024-06-14 17:14 UTC, pablo023 requested changes
Убери пожалуйста все ретурны из войдов

2024-06-14 18:09 UTC, legionerkz commented on src/main/java/faang/school/godbless/BJS29071/InventoryManager.java
> +            return;
Понял, спасибо! Убрал

2024-06-15 04:46 UTC, pablo023 requested changes

2024-06-15 04:46 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS29071/InventoryManager.java
> +        character.getInventory().removeIf(predicate);
У тебя метод выпиливает ему инвентарь как будто весь, а не айтем конкретный)

2024-06-15 13:12 UTC, legionerkz commented on src/main/java/faang/school/godbless/BJS29071/InventoryManager.java
> +        character.getInventory().removeIf(predicate);
по условию: removeItem: принимает объект типа Character и объект типа Predicate<Item>, удаляет предмет из инвентаря персонажа, если предмет удовлетворяет условию, заданному предикатом;

метод removeIf у ArrayList - arraylist.removeIf(Predicate<E> filter) т.е удаляет элементы который не проходит фильтр.

2024-06-15 20:27 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS29071/InventoryManager.java
> +        character.getInventory().removeIf(predicate);
Понял, сорян)

2024-06-15 20:27 UTC, merged