Gmail Rich Filters
CorporationX/god_bless pull request #6607
Opened 2024-06-11 19:41 UTC by kpzxpf

2024-06-13 18:33 UTC, pablo023 approved these changes

2024-06-13 18:33 UTC, pablo023 commented
Пофикси конфликты

2024-06-13 19:11 UTC, pablo023 commented
Исправь конфликты

2024-06-14 16:31 UTC, InnMish commented on src/main/java/faang/school/godbless/EmailProcessor.java
> +            function.apply(email);
Ты здесь сначала выводишь строку о том, что сообщение обработано, а только потом его обрабатываешь. 

Еще: методом apply ты изменяешь исходное сообщение. То есть пользователь навсегда потеряет исходник и больше никогда не сможет вернуться к изначальному сообщению. Так нельзя делать)

2024-06-15 04:53 UTC, pablo023 requested changes

2024-06-15 04:53 UTC, pablo023 commented on src/main/java/faang/school/godbless/GmailRichFilters/EmailProcessor.java
> +    public void processEmails(
В целом неплохо, но - ты процессишь оригинальный список емейлов, тем самым после обработки теряется исходный список. Это не плохо в рамках задачи, а плохо в рамках программирования в целом. Если твоя задача подразумевает изменение данных - всегда помни о том, что перед этим надо создать их копию. Что я конкретно подразумеваю - сделать метод не войд, а возвращать из него список емейлов обработанных, который ты внутри метода создаешь

2024-06-15 08:34 UTC, kpzxpf commented on src/main/java/faang/school/godbless/GmailRichFilters/EmailProcessor.java
> +    public void processEmails(
Запомнил, метод изменил

2024-06-15 20:40 UTC, pablo023 approved these changes

2024-06-15 20:40 UTC, merged