Создал фильтры для обработки входящих писем
CorporationX/god_bless pull request #6649
Opened 2024-06-12 11:31 UTC by Caveri95

Создана система, которая применяет набор пользовательских фильтров к входящим письмам с использованием функциональных интерфейсов

2024-06-17 04:03 UTC, pablo023 requested changes

2024-06-17 04:03 UTC, pablo023 commented on src/main/java/faang/school/godbless/lambda/EmailProcessor.java
> +                .forEach(emailFunction::apply);
Почему консюмер идет до фанкшн?

2024-06-17 11:20 UTC, Caveri95 commented on src/main/java/faang/school/godbless/lambda/EmailProcessor.java
> +                .forEach(emailFunction::apply);
увидел, поправлю

2024-06-23 05:51 UTC, pablo023 requested changes
Тут баг есть

2024-06-23 05:51 UTC, pablo023 commented on src/main/java/faang/school/godbless/lambda/emailHandler/EmailProcessor.java
> +                .forEach(emailHandler);
А почему получается, что сначала применяется функция, а потом предикат проверяется?

2024-06-23 13:40 UTC, Caveri95 commented on src/main/java/faang/school/godbless/lambda/emailHandler/EmailProcessor.java
> +                .forEach(emailHandler);
Не совсем понял. Cначала применяю предикат, потом функцию в map и консьюмер в forEach

2025-01-17 21:09 UTC, closed without merging