BJS2-9111 Создание системы для управления инвентарем персонажей
CorporationX/god_bless pull request #6680
Opened 2024-06-12 15:16 UTC by Caveri95

- создан класс персонажа и вещей для инвентаря
- добавлены методы для работы с инвентарем

2024-06-15 12:31 UTC, pablo023 requested changes
Чуть чуть по деталям посмотри

2024-06-15 12:31 UTC, pablo023 commented on src/main/java/faang/school/godbless/lambda/Character.java
> +public class Character {
Тут можно рекорд. Если хочешь ими писать - прими к сведению.

2024-06-15 12:31 UTC, pablo023 commented on src/main/java/faang/school/godbless/lambda/InventoryManager.java
> +    void addItem(@NonNull Character character, @NonNull Item item, Consumer<Item> consumer) {
Пропустил модификатор доступа

2024-06-15 12:31 UTC, pablo023 commented on src/main/java/faang/school/godbless/lambda/InventoryManager.java
> +                .toList()
Мне кажется, toList здесь излишен.

2024-06-15 12:50 UTC, Caveri95 commented on src/main/java/faang/school/godbless/lambda/Character.java
> +public class Character {
Да, окей

2024-06-15 12:50 UTC, Caveri95 commented on src/main/java/faang/school/godbless/lambda/InventoryManager.java
> +    void addItem(@NonNull Character character, @NonNull Item item, Consumer<Item> consumer) {
Согласен, добавил

2024-06-15 12:52 UTC, Caveri95 commented on src/main/java/faang/school/godbless/lambda/InventoryManager.java
> +                .toList()
если убрать toList(), то возникает ошибка ConcurrentModificationException, потому что после идет forEach(), в котором мы удаляем элементы

2024-06-17 03:43 UTC, pablo023 commented on src/main/java/faang/school/godbless/lambda/InventoryManager.java
> +                .toList()
Не возникает. Вот так написал я, проверил - всё ок:

character.getInventory().stream()
                .filter(itemFilter)
                .forEach(item -> {
                    character.getInventory().remove(item);
                    character.getInventory().add(itemFunction.apply(item));
                });
    }

2024-06-17 03:43 UTC, pablo023 approved these changes

2024-06-17 03:43 UTC, pablo023 commented
Разберись с toList() и конфликтом.

2024-06-17 10:42 UTC, Caveri95 commented on src/main/java/faang/school/godbless/lambda/InventoryManager.java
> +                .toList()
![image](https://github.com/CorporationX/god_bless/assets/115732440/0055a8a2-4819-496b-b5ae-75d80dcefb2a)
если убрать эту строчку и в Main классе ничего не трогать, но ошибка не вылезет, потому что на момент вызова метода updateItem в инвентаре ничего нет, и мы идем по пустой коллекции.
Если  в инвентаре есть вещь, которая подходит под наш фильтр, то во время итерации по коллекции (в методе updateItem) мы начинаем удалять/добавлять элементы и возникает ошибка., так как этот лист unmodifiable
![image](https://github.com/CorporationX/god_bless/assets/115732440/9818fc93-1b92-4a02-a450-7d6d7c781ba0)

Картинку приложил

2024-06-23 05:20 UTC, merged