BJS2-10750 - Потренируем Stream API
CorporationX/god_bless pull request #6695
Opened 2024-06-12 16:40 UTC by ravshanbekn

added static methods, processing integers and strings

2024-06-14 18:14 UTC, pablo023 requested changes

2024-06-14 18:14 UTC, pablo023 commented on src/main/java/faang/school/godbless/stream_api1/StreamOperations.java
> +    }
Это неправильный метод. Нужно найти колличество строк, начинающихся на определенный символ, а не содержащих его.

2024-06-14 18:36 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/stream_api1/StreamOperations.java
> +    }
Исправил

2024-06-15 05:10 UTC, pablo023 approved these changes
Молодец

2024-06-15 05:11 UTC, merged