BJS2-9190 расчет площади треугольника
CorporationX/god_bless pull request #6705
Opened 2024-06-12 18:02 UTC by Caveri95

- Реализовал метод для расчета площади треугольника

2024-06-17 03:47 UTC, pablo023 requested changes

2024-06-17 03:47 UTC, pablo023 commented on src/main/java/faang/school/godbless/lambda/Main.java
> +        Double subC = sub.apply(halfPerimeter).apply(c);
А зачем нам тут классы-обертки?

2024-06-17 03:47 UTC, pablo023 commented on src/main/java/faang/school/godbless/lambda/Main.java
> +        Double fullMul = mul.apply(mul.apply(mul.apply(halfPerimeter).apply(subA)).apply(subB)).apply(subC);
что значит fullMul? И не очень это всё выглядит в одну строку, не читается.

2024-06-17 10:49 UTC, Caveri95 commented on src/main/java/faang/school/godbless/lambda/Main.java
> +        Double subC = sub.apply(halfPerimeter).apply(c);
согласен, можно без них обойтись

2024-06-17 11:05 UTC, Caveri95 commented on src/main/java/faang/school/godbless/lambda/Main.java
> +        Double fullMul = mul.apply(mul.apply(mul.apply(halfPerimeter).apply(subA)).apply(subB)).apply(subC);
окей, поправлю название и разобью на мелкие переменные

2024-06-23 05:31 UTC, pablo023 approved these changes

2024-06-23 05:31 UTC, merged