BJS2-9514 - Create withErrorHandling
CorporationX/god_bless pull request #6772
Opened 2024-06-13 15:05 UTC by kpzxpf

2024-06-14 17:24 UTC, pablo023 requested changes

2024-06-14 17:24 UTC, pablo023 commented on src/main/java/faang/school/godbless/ErrorHandling.java
> +            return null;
Никогда не надо возвращать null. Это антипаттерн на уровне языка программирования, что такое вообще возможно. Не делай так, и почитай - почему)

2024-06-14 19:20 UTC, kpzxpf commented on src/main/java/faang/school/godbless/ErrorHandling.java
> +            return null;
Понятно

2024-06-15 21:15 UTC, pablo023 approved these changes
Молодец)

2025-01-17 21:10 UTC, closed without merging