Потренируем StreamAPI 2
CorporationX/god_bless pull request #6783
Opened 2024-06-13 18:52 UTC by legionerkz

Commit for all tasks

2024-06-18 05:36 UTC, pablo023 requested changes
По условию задачи, функциональность должна быть реализована через статические методы, не через отдельные классы

2024-06-18 15:00 UTC, legionerkz commented
Положил в пакет 2 файла: Main и StreamApiMethods. Просьба смотреть туда

2024-06-21 10:23 UTC, InnMish commented on src/main/java/faang/school/godbless/SortLines.java
> +        return !lineSet.isEmpty();
Слушай, а не будет проще вот так сделать? 
 
 for (char c : line.toCharArray()) {
            if (alphabet.contains(Character.toLowerCase(c))) 


Я понимаю, что ты собираешь в сет, но это такое действие, которое создает нам доп.структуру в памяти просто для того, чтобы один и тот же символ два раза на проверке не прогонять) 
Я бы, наверное, выбрала вариант без сета, а просто вот так прогнать циклом

2024-06-21 10:23 UTC, InnMish commented on src/main/java/faang/school/godbless/SortLines.java
> +                .sorted((s1, s2) -> s1.length() - s2.length()).collect(Collectors.toList());
.sorted(Comparator.comparingInt(String::length))

2024-06-21 10:23 UTC, InnMish commented on src/main/java/faang/school/godbless/SortLines.java
> +        List<String> result = lines.stream().filter(line -> hasLetterFromAlphabet(line, alphabet))
по код стайлу: 
lines.stream 
.filter
.sorted
.collect 

разноси операции по разным строчкам, так читается гораздо проще. Сразу привыкай к таком формату написания именно, сам увидишь, насколько проще такой код понимать будет

2024-06-21 10:23 UTC, InnMish commented on src/main/java/faang/school/godbless/TargetSum.java
> +        List<List<Integer>> result = nums.stream().flatMap(firstNum -> nums.stream()
Если тут сделать Set<List>, будут только уникальные пары)

2024-06-21 10:23 UTC, InnMish commented on src/main/java/faang/school/godbless/TargetSum.java
> +                        .map(secondNum -> List.of(firstNum, secondNum)))
Вот тут душно напишу, но можно подумать: 
.map(secondNum -> List.of(Math.min(firstNum, secondNum), Math.max(firstNum, secondNum))))

Так ты руками дублирование тоже сможешь отследить)

2024-06-21 10:23 UTC, InnMish commented on src/main/java/faang/school/godbless/SortCountries.java
> +                .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue, (a, b) -> a, TreeMap::new));
а почему TreeMap здесь используешь? В чем преимущество?

2024-06-21 10:23 UTC, InnMish commented on src/main/java/faang/school/godbless/SortCountries.java
> +                .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue, (a, b) -> a, TreeMap::new));
в целом, чтобы сортировать, можно использовать метод comparingKey 

.sorted(Map.Entry.comparingByKey())

2024-06-21 10:23 UTC, InnMish commented on src/main/java/faang/school/godbless/Palindrome.java
> +    }
Нууу) Здесь логика зашита у тебя, с числами каким-то) сложно разобраться 

давай еще покопаемся, как можно здесь прийти к ответу? 
Посмотри на IntStream.rangeClosed, а затем, может быть, мы можем посимвольно проходить по числам и проверять некоторое условие? Будет неплохо, если избежим вот такой логики с десятками, она очень ручная)

2024-06-21 10:24 UTC, InnMish commented
Ой, вы там все в кучу уже собрали, а я покомментила по отдельным файлам :D Ну короче) Дублирование - зло) Сноси ненужное в следующий раз)

2024-06-25 19:37 UTC, legionerkz commented on src/main/java/faang/school/godbless/SortLines.java
> +        return !lineSet.isEmpty();
сделал

2024-06-25 19:37 UTC, legionerkz commented on src/main/java/faang/school/godbless/SortLines.java
> +                .sorted((s1, s2) -> s1.length() - s2.length()).collect(Collectors.toList());
сделал

2024-06-25 19:38 UTC, legionerkz commented on src/main/java/faang/school/godbless/SortLines.java
> +        List<String> result = lines.stream().filter(line -> hasLetterFromAlphabet(line, alphabet))
cделал

2024-06-25 19:41 UTC, legionerkz commented on src/main/java/faang/school/godbless/TargetSum.java
> +                        .map(secondNum -> List.of(firstNum, secondNum)))
я тут использовал distinct - для тренировки отсутствия повторений. На мой взгляд это более читаемое чем через Math.min и Math.max. Как и не работать с сетами.

2024-06-25 19:45 UTC, legionerkz commented on src/main/java/faang/school/godbless/SortCountries.java
> +                .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue, (a, b) -> a, TreeMap::new));
> а почему TreeMap здесь используешь? В чем преимущество?

Потому что в основе этой дата структуры идет красно-черное дерево,  для которого мы имеем сразу сортированную структуру в конце. Решил  использовать ее, для того чтобы разнообразить код.

2024-06-25 20:05 UTC, legionerkz commented on src/main/java/faang/school/godbless/Palindrome.java
> +    }
Сделал через StringBuilder и его метод reverse. Через char - можно сделать с помощью двух указателей, которые идут друг к другу, но на мой взгляд так более понятно.

2025-01-17 21:10 UTC, closed without merging