BJS2-7579 группировка пользователей
CorporationX/god_bless pull request #6798
Opened 2024-06-14 06:38 UTC by bookinisto

2024-06-15 20:24 UTC, pablo023 requested changes
Задача по логике сделана правильно. Но есть моменты, которые тебе нужно исправить, либо принять к сведению просто - про ООП.

2024-06-15 20:24 UTC, pablo023 commented on src/main/java/GroupingUsersByAge/User.java
> +    void grouping(List<User> users) {   //создаю метод группировки
Я бы этот метод вынес из класса юзер. Смотри, давай чуть-чуть про ООП здесь поговорим. Объектно-ориентированное программирование предполагает, что мы воспринимаем процесс работы нашего приложения, как взаимодействия объектов. Примерно, как в жизни. К примеру, ты приходишь на работу, ты - объект работник. Твои коллеги - тоже такие объекты. Есть там компьютер, он - объект тоже, он умеет включаться, выключаться. Ты умеешь приходить, уходить, работать, обедать, и так далее. У тебя есть функционал. А есть мероприятия, которые затрагивают вас всех - например, сформироваться в команду. Ты не можешь сам сформироваться в команду - что-то внешнее эту команду должно сформировать, чтобы ты был ее членом. К чему это я все вообще.. К тому, что метод grouping не должен быть внутри юзера. Это что-то внешнее от него. Было бы более уместно написать этот метод в main, а в классе юзер - только то, что непосредственно к нему относится.

2024-06-15 20:24 UTC, pablo023 commented on src/main/java/GroupingUsersByAge/User.java
> +        for (User user : users) {       // циклом перебираю людей из коллекции лист
Убери пожалуйста все комментарии из кода.

2024-06-15 20:24 UTC, pablo023 commented on src/main/java/GroupingUsersByAge/User.java
> +                List<User> spisok = usersMap.get(ageUser); //если такой человек есть, создаю лист spisok в который кладу значение по ключу из мапы
spisok - не вариант. users, или userList

2024-06-15 20:24 UTC, pablo023 commented on src/main/java/GroupingUsersByAge/User.java
> +            int ageUser = user.age;     //получаю возраст каждого человека из листа
userAge*

2024-06-16 15:10 UTC, bookinisto commented on src/main/java/GroupingUsersByAge/User.java
> +                List<User> spisok = usersMap.get(ageUser); //если такой человек есть, создаю лист spisok в который кладу значение по ключу из мапы
ok

2024-06-16 15:10 UTC, bookinisto commented on src/main/java/GroupingUsersByAge/User.java
> +        for (User user : users) {       // циклом перебираю людей из коллекции лист
ok

2024-06-16 15:10 UTC, bookinisto commented on src/main/java/GroupingUsersByAge/User.java
> +    void grouping(List<User> users) {   //создаю метод группировки
сейчас попробую исправить .

2024-06-16 16:48 UTC, bookinisto commented on src/main/java/GroupingUsersByAge/User.java
> +    void grouping(List<User> users) {   //создаю метод группировки
ни как не пойму как разместить метод группировки в main что бы не было ошибки в параметре. 

Vlad AI мне говорит что в Java можно писать другие методы внутри главного метода класса. Однако это не является рекомендуемой практикой для организации и читаемости кода. Лучше определять дополнительные методы вне главного метода, чтобы способствовать лучшей структуре кода и сопровождаемости.

2024-06-17 03:11 UTC, pablo023 approved these changes
Неплохо. Есть небольшие моменты - отметил в комменте.

2024-06-17 03:11 UTC, pablo023 commented on src/main/java/GroupingUsersByAge/User.java
> +    public int age;
На будущее - все поля private, по правилам инкапсуляции. Иногда protected, когда у класса, который ты пишешь, есть наследники, и это может иметь какой-то смысл. Публичные они практически никогда, это какой-то супер кейс должен быть. Ознакомься с геттерами и сеттерами, и в дальнейшем делай поля приватными.

2024-06-17 03:11 UTC, merged

2024-06-17 11:51 UTC, bookinisto commented on src/main/java/GroupingUsersByAge/User.java
> +    public int age;
понял , хорошо