BJS2-7863 регистрация User
CorporationX/god_bless pull request #6820
Opened 2024-06-14 13:19 UTC by bookinisto

2024-06-14 16:58 UTC, pablo023 requested changes
Молодец) Исправь то, что отметил, и убери все комментарии из кода.

2024-06-14 16:58 UTC, pablo023 commented on src/main/java/faang/school/godbless/Abstraction/Character.java
> +    int healf = 100;
health*

2024-06-14 16:58 UTC, pablo023 commented on src/main/java/faang/school/godbless/Abstraction/Character.java
> +
Не пиши переменные в одну строчку, и пиши их на английском, если не знаешь как - чекай переводчик) У тебя на работе всегда будут английские названия.

int power
int agility
int intelligence

2024-06-14 16:58 UTC, pablo023 commented on src/main/java/faang/school/godbless/Abstraction/Character.java
> +                                         // например Warrior war10 = new Warrior (3 , 5 ,10 );
Комментарии в пулл-реквест попадать не должны, надо почистить

2024-06-14 16:58 UTC, pablo023 commented on src/main/java/faang/school/godbless/Abstraction/Character.java
> +    void attack(Character character) {                    //метод атаки для лучника
Модификатора доступа нет. public / private / protected?

2024-06-15 20:26 UTC, pablo023 requested changes

2024-06-15 20:26 UTC, pablo023 commented on src/main/java/faang/school/godbless/Abstraction/Character.java
> +
лишние строки

2024-06-15 20:26 UTC, pablo023 commented on src/main/java/faang/school/godbless/Abstraction/Character.java
> +        character.health = character.health - power;
Лишняя строка

2024-06-15 20:26 UTC, pablo023 commented on src/main/java/faang/school/godbless/Abstraction/Character.java
> +    class Warrior extends Character {
А почему мы класс Warrior создаем внутри класса Character? Зачем так?

2024-06-15 20:26 UTC, pablo023 commented on src/main/java/faang/school/godbless/Abstraction/Character.java
> +     class Archer extends Character {
Тоже не понимаю, почему этот класс тут

2024-06-15 20:26 UTC, pablo023 commented on src/main/java/faang/school/godbless/Abstraction/Character.java
> +    Archer(String name) {
Индентация еще съехала

2024-06-16 14:52 UTC, bookinisto commented on src/main/java/faang/school/godbless/Abstraction/Character.java
> +    class Warrior extends Character {
он не внутри . закрывающая скобка класса Character как раз стоит перед объявлением класса Warrior

2024-06-16 14:52 UTC, bookinisto commented on src/main/java/faang/school/godbless/Abstraction/Character.java
> +        character.health = character.health - power;
почему лишняя ?? я же переопределяю метод attack  для класса Warrior

2024-06-16 14:54 UTC, bookinisto commented on src/main/java/faang/school/godbless/Abstraction/Character.java
> +
почему лишние ? я же создаю объекты классов. если их не создам , но смогу вызвать методы и проверить как работает код

2024-06-16 14:57 UTC, bookinisto commented on src/main/java/faang/school/godbless/Abstraction/Character.java
> +     class Archer extends Character {
этот класс тоже не в Character находиться. закрыл скобку  Warrior класса и создал Archer

2024-06-16 19:38 UTC, bookinisto commented on src/main/java/faang/school/godbless/Abstraction/Character.java
> +    Archer(String name) {
исправил

2024-06-17 03:15 UTC, pablo023 requested changes
Почти хорошо. Чуть чуть исправь.

2024-06-17 03:15 UTC, pablo023 commented on src/main/java/faang/school/godbless/Abstraction/Character.java
> +        character.health = character.health - power;
Я имел введу, 26-я строка лишняя) Та, что пустая.

2024-06-17 03:15 UTC, pablo023 commented on src/main/java/faang/school/godbless/Abstraction/Character.java
> +}
Это конечно неплохо) Но. Не надо создавать классы внутри других классов. Так делать можно, но на это должна быть какая-то прям причина, что если так не сделать, то мир перевернется) Вот это, Archer, и Warrior - в отдельные классы. Под этим я подразумеваю отдельные файлы Archer.java, etc.

2024-06-17 11:55 UTC, bookinisto commented on src/main/java/faang/school/godbless/Abstraction/Character.java
> +}
вроде понял о чем речь, сейчас сделаю

2024-06-17 17:57 UTC, merged