BJS2-10423-added methods
CorporationX/god_bless pull request #6835
Opened 2024-06-14 17:26 UTC by YPG0

2024-06-18 06:04 UTC, pablo023 requested changes
Внимательнее, и более вдумчиво пиши код, пожалуйста.

2024-06-18 06:04 UTC, pablo023 commented on src/main/java/StreamAPI1/StreamAPI.java
> +    public static int searchStringsBySymbol(List<String> words, String symbol) {
Почему search, если метод возвращает int?

Зачем сабстринг, если есть charAt?

2024-06-18 06:04 UTC, pablo023 commented on src/main/java/StreamAPI1/StreamAPI.java
> +    public static List<String> filterWords(List<String> words, String filter) {
containsSubstring* 

filterWords ну вообще никак не намекает на то, что именно тут происходит

2024-06-18 06:04 UTC, pablo023 commented on src/main/java/StreamAPI1/StreamAPI.java
> +    public static List<String> sortByLength(List<String> words) {
sort что? sortStringListByStringsLength

2024-06-18 06:04 UTC, pablo023 commented on src/main/java/StreamAPI1/StreamAPI.java
> +    public static boolean �heckListByCondition(List<Integer> list, StatusCheckForInt check) {
Тут вообще что-то попало в код лишнее, судя по всему, с из кириллицы

2024-06-18 06:04 UTC, pablo023 commented on src/main/java/StreamAPI1/StreamAPI.java
> +    public static boolean �heckListByCondition(List<String> list, StatusCheckForString check) {
аналогично

2024-06-18 06:04 UTC, pablo023 commented on src/main/java/StreamAPI1/StreamAPI.java
> +    public static int searchMinIntOnValue(List<Integer> numbers, int value) {
не search, а get

2024-06-18 06:04 UTC, pablo023 commented on src/main/java/StreamAPI1/StreamAPI.java
> +    public static List<Integer> wordsOnLength(List<String> words) {
getLengthsOfWords*

2024-06-18 15:53 UTC, YPG0 commented on src/main/java/StreamAPI1/StreamAPI.java
> +    public static int sumPositive(@NonNull List<Integer> numbers) {
Поменял на sumOfEvenNumbers

2024-06-18 15:53 UTC, YPG0 commented on src/main/java/StreamAPI1/StreamAPI.java
> +    public static int avg(@NonNull List<Integer> numbers) {
Поменял

2024-06-18 15:53 UTC, YPG0 commented on src/main/java/StreamAPI1/StreamAPI.java
> +    public static int max(@NonNull List<Integer> numbers) {
Поменял

2024-06-18 15:53 UTC, YPG0 commented on src/main/java/StreamAPI1/StreamAPI.java
> +    public static int searchStringsBySymbol(List<String> words, String symbol) {
поменял на getStringsStartingBySymbol. И заменял на charAt.  Поменял во входных данных метода требуемую букву на char или не было разницы String оставлять или char будет?

2024-06-18 15:54 UTC, YPG0 commented on src/main/java/StreamAPI1/StreamAPI.java
> +    public static List<String> filterWords(List<String> words, String filter) {
Поменял

2024-06-18 15:55 UTC, YPG0 commented on src/main/java/StreamAPI1/StreamAPI.java
> +    public static List<String> sortByLength(List<String> words) {
Поменял

2024-06-18 15:58 UTC, YPG0 commented on src/main/java/StreamAPI1/StreamAPI.java
> +    public static boolean �heckListByCondition(List<Integer> list, StatusCheckForInt check) {
Русская "с" была вместо английской "с"

2024-06-18 15:58 UTC, YPG0 commented on src/main/java/StreamAPI1/StreamAPI.java
> +    public static boolean �heckListByCondition(List<String> list, StatusCheckForString check) {
так же

2024-06-18 16:00 UTC, YPG0 commented on src/main/java/StreamAPI1/StreamAPI.java
> +    public static int searchMinIntOnValue(List<Integer> numbers, int value) {
Поправил

2024-06-18 16:01 UTC, YPG0 commented on src/main/java/StreamAPI1/StreamAPI.java
> +    public static List<Integer> wordsOnLength(List<String> words) {
Поправил

2024-06-20 07:54 UTC, pablo023 commented
Молоток

2024-06-20 07:54 UTC, merged