Анализ активности пользователей в социальной сети
CorporationX/god_bless pull request #6858
Opened 2024-06-15 01:19 UTC by legionerkz

Implemeted task

2024-06-17 04:44 UTC, pablo023 requested changes

2024-06-17 04:44 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS210258/GetRandomActionsList.java
> +        LocalDate endDate = LocalDate.of(2024, 6, 14);
Не надо так хардкодить, вынеси это куда-то в константы

2024-06-17 04:44 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS210258/UserStatistics.java
> +                .sorted(Map.Entry.<Integer, Long>comparingByValue().reversed()).limit(10)
limit(10) - не очень. Не надо хардкодить. Вынеси это значение в какую-то константу, либо сделай так, чтобы оно передавалось параметром, а метод был topNUsers, где n - переданное количество. И не topTenUsers, а getTopTenUsers.

2024-06-17 04:44 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS210258/UserStatistics.java
> +    }
Оно перегружено получается. На словах тяжело объяснить, посмотри вот такой код, и подумай - чем он лучше, чем этот?

    private void validateInputs(List<UserAction> userActionList, int topN, int monthsBack) {
        if (userActionList == null) {
            throw new IllegalArgumentException("Action llist can not be null");
        }
        if (topN <= 0) {
            throw new IllegalArgumentException("The number of top users must be greater than 0");
        }
        if (monthsBack < 0) {
            throw new IllegalArgumentException("Months back must be non-negative");
        }
    }

    private Map<Integer, Long> countUserActionsByTypeAndDate(List<UserAction> userActionList, Actions actionType, LocalDate dateThreshold) {
        return userActionList.stream()
                .filter(userAction -> userAction.getActionType().equals(actionType))
                .filter(userAction -> userAction.getActionDate().isAfter(dateThreshold))
                .collect(Collectors.groupingBy(
                        UserAction::getId,
                        Collectors.counting())
                );
    }

    private List<Integer> findTopUsers(Map<Integer, Long> userActionCounts, int topN) {
        return userActionCounts.entrySet().stream()
                .sorted(Map.Entry.<Integer, Long>comparingByValue().reversed())
                .limit(topN)
                .map(Map.Entry::getKey)
                .collect(Collectors.toList());
    }

2024-06-17 04:44 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS210258/UserStatistics.java
> +    public List<Integer> topThreeUsers(List<UserAction> userActionList) {
Тут тоже. Давай попробуешь это сделать более разделенным на логические составляющие?

2024-06-17 14:43 UTC, legionerkz commented on src/main/java/faang/school/godbless/BJS210258/UserStatistics.java
> +                .sorted(Map.Entry.<Integer, Long>comparingByValue().reversed()).limit(10)
Спасибо, вынес как параметр

2024-06-17 14:43 UTC, legionerkz commented on src/main/java/faang/school/godbless/BJS210258/UserStatistics.java
> +    }
+

2024-06-17 14:43 UTC, legionerkz commented on src/main/java/faang/school/godbless/BJS210258/UserStatistics.java
> +    public List<Integer> topThreeUsers(List<UserAction> userActionList) {
+

2024-06-18 05:34 UTC, pablo023 approved these changes
Молодец

2024-06-18 05:34 UTC, merged