BJS2-8324 склад Amazon
CorporationX/god_bless pull request #6908
Opened 2024-06-16 11:04 UTC by bookinisto

2024-06-17 03:27 UTC, pablo023 requested changes
Есть что исправить

2024-06-17 03:27 UTC, pablo023 commented on src/main/java/groupingAmazonProduct/Product.java
> +    protected int id;
Есть тут смысл делать их protected, а не private?

2024-06-17 03:27 UTC, pablo023 commented on src/main/java/groupingAmazonProduct/Product.java
> +    protected Product(String name, String category, int id) {
Почему конструктор протектед? Вот в этом смысла нет точно, они всегда должны быть публичными практически, чтобы экземпляр объекта можно было создать в любой части приложения

2024-06-17 03:27 UTC, pablo023 commented on src/main/java/groupingAmazonProduct/Product.java
> +    protected static void groupingByCategory(HashSet<Product> productSetCollection) {
В программировании практика написания кода таким образом, что перетираются изначальные данные, является плохой. 

1) Вынеси метод из класса Product куда-то в мейн, или что-то в таком духе
2) Сделай его публичным
3) Сделай, чтобы он принимал на вход какой-то хэшсет, а возвращал мапу.

4) Разберись с тем, когда действительно нужен protected

2024-06-17 03:27 UTC, pablo023 commented on src/main/java/groupingAmazonProduct/Product.java
> +    }
Неправильно сделал по логике.

Задача: Реализуйте метод для вывода информации о товарах в каждой категории, используя обход массива Entry внутри HashMap. Выведите категории товаров и их товары.

У тебя этот метод должен обойти мапу, и написать какие есть категории товаров, и какие в них товары содержатся.

2024-06-17 03:27 UTC, pablo023 commented on src/main/java/groupingAmazonProduct/Product.java
> +    public static void main(String[] args) {
Вынеси мэйн из этого класса.

2024-06-18 17:47 UTC, bookinisto commented on src/main/java/groupingAmazonProduct/Product.java
> +    protected int id;
ok

2024-06-18 17:47 UTC, bookinisto commented on src/main/java/groupingAmazonProduct/Product.java
> +    protected Product(String name, String category, int id) {
исправлю

2024-06-18 17:47 UTC, bookinisto commented on src/main/java/groupingAmazonProduct/Product.java
> +    protected static void groupingByCategory(HashSet<Product> productSetCollection) {
понял , исправил

2024-06-18 17:49 UTC, bookinisto commented on src/main/java/groupingAmazonProduct/Product.java
> +    }
несразу понял, незнал про обход массива entrySet. исправил

2024-06-18 17:49 UTC, bookinisto commented on src/main/java/groupingAmazonProduct/Product.java
> +    public static void main(String[] args) {
ок

2024-06-19 12:20 UTC, Kostahe reviewed
Code review

2024-06-19 12:20 UTC, Kostahe commented on src/main/java/groupingAmazonProduct/Product.java
> +    }
Если ты так хочешь сойденять строки то лутше это делать с помощю класса StringBuilder для улучшения производительности. Лучшим решением будет сгенерировать метод `toString()` через IDE (с помощью Ctrl + N),  а затем внести необходимые изменения в текст метода, если нетребуется кастомная реализицая то просто можна использовать аннотацию `@Data`.

2024-06-19 12:20 UTC, Kostahe commented on src/main/java/groupingAmazonProduct/MainAmazon.java
> +        collectionProduct.add(product7);
Тут лутше так сделать `collectionProduct.add(new Product("шампунь", "быт.химия", 12345));`

2024-06-20 16:11 UTC, bookinisto commented on src/main/java/groupingAmazonProduct/MainAmazon.java
> +        collectionProduct.add(product7);
да, согласен )

2024-06-20 16:12 UTC, bookinisto commented on src/main/java/groupingAmazonProduct/Product.java
> +    }
пора начинать пользоваться аннотациями

2024-06-20 16:13 UTC, bookinisto commented on src/main/java/groupingAmazonProduct/Product.java
> +    }
спасибо , попробую

2024-06-21 08:15 UTC, pablo023 approved these changes

2024-06-21 08:15 UTC, pablo023 commented on src/main/java/groupingAmazonProduct/MainAmazon.java
> +        Product product7 = new Product("куртка", "одежда", 184833);
Давай также будем отвыкать от цифр в нейминге. Это прям вот не делают целенаправленно)

2024-06-21 08:15 UTC, pablo023 commented on src/main/java/groupingAmazonProduct/MainAmazon.java
> +            }
Молодец!) Если хорошо понял и усвоил вот этот способ формирования мапы, где ключом является что-то там, а значением -коллекция, как тут - список, например, то можешь почитать про computeIfAbsent метод. Он позвляет все это в одну строку сделать)

2024-06-21 08:16 UTC, merged

2024-06-21 08:21 UTC, bookinisto commented on src/main/java/groupingAmazonProduct/MainAmazon.java
> +        Product product7 = new Product("куртка", "одежда", 184833);
хорошо)

2024-06-21 08:23 UTC, bookinisto commented on src/main/java/groupingAmazonProduct/MainAmazon.java
> +            }
спасибо , узнаю обязательно что за метод и попробую применить