nikittta-BJS2-11911
CorporationX/god_bless pull request #6923
Opened 2024-06-16 16:14 UTC by Nikita2768

2024-06-22 15:51 UTC, pablo023 requested changes
Чуть доработай пж

2024-06-22 15:51 UTC, pablo023 commented on src/main/java/faang/school/godbless/pathFinger/Main.java
> +        List<CityWorker> listWorkers = getListWither(monsters, monsterKillTime);
Witcher*

2024-06-22 15:51 UTC, pablo023 commented on src/main/java/faang/school/godbless/pathFinger/Main.java
> +            works.run();
.run() - это не про многопоточку. Новый поток - .start(), либо executorService.submit()

2024-06-22 15:51 UTC, pablo023 commented on src/main/java/faang/school/godbless/pathFinger/Main.java
> +        for(CityWorker works: listWorkers) {
workers*

2024-06-23 05:14 UTC, Nikita2768 reviewed
Разобрался и вспомнил почему сделанно именно так, в комментариях есть пометки по этому поводу

2024-06-23 05:16 UTC, Nikita2768 commented on src/main/java/faang/school/godbless/pathFinger/Main.java
> +        System.out.println("Program execution time one thread: " + (after - before));
В этом блоке кода я выполняю задачу в однопоточном режиме, по условию задачи.
"сравнить время выполнения программы в однопоточном и многопоточном режимах. Это главное условие задачи. Посмотрите, будет ли программа выполняться быстрее в один поток, чем в несколько."

2024-06-23 05:17 UTC, Nikita2768 commented on src/main/java/faang/school/godbless/pathFinger/Main.java
> +    }
В этом блоке сделал эту задачу с такимиже данными в многопоточным режиме и вывел результаты в консоль, чтобы было видно разницу по времени.

2024-06-23 05:19 UTC, merged