nikittta-BJS2-11781
CorporationX/god_bless pull request #6926
Opened 2024-06-16 16:38 UTC by Nikita2768

2024-06-20 20:35 UTC, pablo023 requested changes

2024-06-20 20:35 UTC, pablo023 commented on src/main/java/faang/school/godbless/MiceAreVeryNice/Room.java
> +    List<Food> foodInRoom;
Нет модификатора доступа

2024-06-20 20:35 UTC, pablo023 commented on src/main/java/faang/school/godbless/MiceAreVeryNice/Room.java
> +                new Room(Food.getListFood())
Это разве нельзя циклом красиво наполнить?)

2024-06-20 20:35 UTC, pablo023 commented on src/main/java/faang/school/godbless/MiceAreVeryNice/Food.java
> +    }
А зачем так делать?) Циклом нельзя этот лист наполнить?)

2024-06-20 20:35 UTC, pablo023 commented on src/main/java/faang/school/godbless/MiceAreVeryNice/House.java
> +    public House(List<Room> roms) {
rooms*

2024-06-20 20:35 UTC, pablo023 commented on src/main/java/faang/school/godbless/MiceAreVeryNice/House.java
> +            house.setCountRoom(house.getCountRoom() + 1);
У тебя эти геттер и сеттер несинхронизированы, ты тут можешь поймать состояние гонки.

2024-06-21 03:02 UTC, Nikita2768 commented on src/main/java/faang/school/godbless/MiceAreVeryNice/House.java
> +            house.setCountRoom(house.getCountRoom() + 1);
Понял

2024-06-21 03:02 UTC, Nikita2768 commented on src/main/java/faang/school/godbless/MiceAreVeryNice/House.java
> +    public House(List<Room> roms) {
Понял

2024-06-21 03:02 UTC, Nikita2768 commented on src/main/java/faang/school/godbless/MiceAreVeryNice/Food.java
> +    }
Понял

2024-06-21 03:02 UTC, Nikita2768 commented on src/main/java/faang/school/godbless/MiceAreVeryNice/Room.java
> +                new Room(Food.getListFood())
Понял

2024-06-21 03:02 UTC, Nikita2768 commented on src/main/java/faang/school/godbless/MiceAreVeryNice/Room.java
> +    List<Food> foodInRoom;
Понял

2024-06-23 03:22 UTC, pablo023 approved these changes

2024-06-23 03:22 UTC, merged