Вы работаете в Microsoft! - Created and implemented classes SenderRunnable and MailSender.
CorporationX/god_bless pull request #6996
Opened 2024-06-17 16:22 UTC by dossymbekov

Created and implemented classes SenderRunnable and MailSender.

2024-06-20 20:52 UTC, pablo023 requested changes

2024-06-20 20:52 UTC, pablo023 commented on src/main/java/faang/school/godbless/MailSender.java
> +            int startIndex = i * mailsPerThread + 1;
А как быть с мейлом под индексом 0?

2024-06-21 04:22 UTC, dossymbekov commented on src/main/java/faang/school/godbless/MailSender.java
> +            int startIndex = i * mailsPerThread + 1;
Принято!
Пропустил.

2024-06-21 04:44 UTC, dossymbekov commented on src/main/java/faang/school/godbless/MailSender.java
> +            int startIndex = i * mailsPerThread + 1;
ПОдправил.

2025-01-17 21:11 UTC, closed without merging