BJS2-11000 - Турнир в Королевской гавани
CorporationX/god_bless pull request #7056
Opened 2024-06-18 11:23 UTC by ravshanbekn

+realized functions, required in task

2024-06-20 19:59 UTC, pablo023 requested changes
Надо исправить

2024-06-20 19:59 UTC, pablo023 commented on src/main/java/faang/school/godbless/tournament/Knight.java
> +    }
Так не сработает. Ты в мейне вызываешь на экзекьютор сервисе вот этот метод, и у тебя получается один поток будет вот эти трайалы разгонять. Тебе нужно, чтобы каждый трайал запускался в одном потоке как бы, параллельно. А так у тебя синхронизированный подход получается.

2024-06-20 21:14 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/tournament/Knight.java
> +    }
Хорошо, исправил

2024-06-22 17:57 UTC, pablo023 approved these changes
Молодец!

2024-06-22 17:57 UTC, merged