BJS2-11923 You work at microsoft
CorporationX/god_bless pull request #7061
Opened 2024-06-18 12:05 UTC by shade2903

Create class SenderRunnable
implemented task processing in five threads

2024-06-21 19:25 UTC, pablo023 requested changes
Небольшой баг, и по чистоте кода можно улучшить

2024-06-21 19:25 UTC, pablo023 commented on src/main/java/faang/school/godbless/microsoft/MailSender.java
> +            int endIndex = startIndex + NUMBER_OF_LETTERS / PULL_OF_THREADS - 1;
Пришлось посчитать, как-то сложновато тут математика выглядит. В итоге у тебя элемент под индексом 0 никогда не будет обработан. Это баг. Исправь его, и напиши как-то попроще, пожалуйста)

2024-06-21 19:25 UTC, pablo023 commented on src/main/java/faang/school/godbless/microsoft/MailSender.java
> +            int endIndex = startIndex + NUMBER_OF_LETTERS / PULL_OF_THREADS - 1;
Если хочешь пример, то я бы делал так:

private static final int batchSize = NUMBER_OF_LETTERS / PULL_OF_THREADS

...

int startIndex = batchSize * i
int endIndex = startIndex + batchSize + 1

2024-06-22 16:30 UTC, shade2903 commented on src/main/java/faang/school/godbless/microsoft/MailSender.java
> +            int endIndex = startIndex + NUMBER_OF_LETTERS / PULL_OF_THREADS - 1;
Спасибо. Поправил. 
Спасибо поправил.
 int startIndex = i * NUMBER_OF_LETTERS / PULL_OF_THREADS + 1;  тут я плюсовал единицу просто что бы не было в консоли сообщения о нулевом номере

2024-06-25 02:44 UTC, pablo023 approved these changes

2024-06-25 02:44 UTC, merged