BJS2-10998 - Created a program that simulates an army of heroes of mi…
CorporationX/god_bless pull request #7063
Opened 2024-06-18 13:15 UTC by kpzxpf

…ght and magic and determines the overall strength of the army using parallelization.

2024-06-20 20:23 UTC, pablo023 requested changes
Есть ошибка по race condition

2024-06-20 20:23 UTC, pablo023 commented on src/main/java/faang/school/godbless/distributedArmyOfHeroes/Army.java
> +
Лишняя строчка

2024-06-20 20:23 UTC, pablo023 commented on src/main/java/faang/school/godbless/distributedArmyOfHeroes/Army.java
> +}
Вот тут проблема. Ты пишешь в эту переменную методом выше с аннотаций Synchronized, чтобы избежать состояния гонки. но ты не избежишь его, т.к. у тебя чтение вот этим методом несинхронизировано. Грубо говоря, если есть два потока, оба прочитают значение это, и по очереди изменят на 10, то вместо изменения на 20, оно на 10 изменится.

2024-06-21 12:21 UTC, kpzxpf commented on src/main/java/faang/school/godbless/distributedArmyOfHeroes/Army.java
> +}
Понял

2024-06-23 03:14 UTC, pablo023 approved these changes

2024-06-23 03:14 UTC, merged