BJS2-11886- написал ExecutorService для распределения писем по потокам
CorporationX/god_bless pull request #7088
Opened 2024-06-18 16:56 UTC by YPG0

2024-06-21 19:16 UTC, pablo023 requested changes
Чуть чуть надо доработать)

2024-06-21 19:16 UTC, pablo023 commented on src/main/java/faang/school/godbless/Microsoft/MailSender.java
> +        ExecutorService executor = Executors.newFixedThreadPool(5);
Не хардкодь. Пятерку можно было бы вынести в отдельную константу.

2024-06-21 19:16 UTC, pablo023 commented on src/main/java/faang/school/godbless/Microsoft/MailSender.java
> +        executor.awaitTermination(Long.MAX_VALUE, TimeUnit.NANOSECONDS);
Ммммм.. А если у нас прогарамма сломается, мы получается будем ждать 9 курвалионов наносекунд?) Зачем?)

2024-06-23 14:54 UTC, YPG0 commented on src/main/java/faang/school/godbless/Microsoft/MailSender.java
> +        ExecutorService executor = Executors.newFixedThreadPool(5);
Поправил. Дальше по задачам уже начал выносить сразу

2024-06-23 14:57 UTC, YPG0 commented on src/main/java/faang/school/godbless/Microsoft/MailSender.java
> +        executor.awaitTermination(Long.MAX_VALUE, TimeUnit.NANOSECONDS);
Похоже на то. Пойду сразу во всех задачах править.

2024-06-25 02:44 UTC, pablo023 approved these changes

2024-06-25 02:44 UTC, merged