BJS2-11004-"Распределенная армия героев меча и магии"
CorporationX/god_bless pull request #7105
Opened 2024-06-18 18:58 UTC by i7rincpane

1. добавляются группы подразделений, и затем каждая группа обрабатывается в отдельном потоке, считается сумма силы подразделения, которая затем складывается в сумму силы всех подразделений

2024-06-21 19:46 UTC, pablo023 requested changes
Раз уж ты так хорошо начал писать - давай рости)

2024-06-21 19:46 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS211004/PowerCalculateThread.java
> +            System.out.println(String.format("Считает поток %s для %s ", Thread.currentThread().getName(), subArmy.size(), subArmy.get(0).getClass().getSimpleName()));
Очень круто пишешь, но надо научиться иметь дело вот с такими гусеницами. На данный момент, это - слабое место. Как насчет такого?

        String threadName = Thread.currentThread().getName();
        int subArmySize = subArmy.size();
        String subArmyType = subArmy.get(0).getClass().getSimpleName();
        
        System.out.println(String.format("Считает поток %s для %d %s", threadName, subArmySize, subArmyType));
    }
}

2024-06-21 19:46 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS211004/PowerCalculateThread.java
> +            Thread.sleep(3000 * subArmy.size());
3000 тут - магическое число.

2024-06-21 19:46 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS211004/PowerCalculateThread.java
> +            System.out.println(String.format("Суммарная сила подразделения %s: %s", subArmy.get(0).getClass().getSimpleName(), powerSum));
И тут тоже гусеница.

2024-06-21 19:46 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS211004/Unit.java
> +@Data
Аценитровать не буду, просто для твоего же понимания, Data - универсальная аннотация, которая генерит дофига всего. В задаче ты использовал только геттер. Если бы ты написал аннотацию Getter - по производительности твой код был бы выше. Это не то, что я бы прям хотел, чтобы ты переписал тут на геттер, и тд. Просто делюсь с тобой мыслями, чтобы ты принимал это в рассчет.

2024-06-21 19:46 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS211004/PowerCalculateThread.java
> +    @SneakyThrows
Ты знаешь, что это - плохая практика?

2024-06-22 08:52 UTC, i7rincpane commented on src/main/java/faang/school/godbless/BJS211004/PowerCalculateThread.java
> +            System.out.println(String.format("Считает поток %s для %s ", Thread.currentThread().getName(), subArmy.size(), subArmy.get(0).getClass().getSimpleName()));
принял

2024-06-22 08:52 UTC, i7rincpane commented on src/main/java/faang/school/godbless/BJS211004/PowerCalculateThread.java
> +            Thread.sleep(3000 * subArmy.size());
принял

2024-06-22 08:52 UTC, i7rincpane commented on src/main/java/faang/school/godbless/BJS211004/PowerCalculateThread.java
> +            System.out.println(String.format("Суммарная сила подразделения %s: %s", subArmy.get(0).getClass().getSimpleName(), powerSum));
принял

2024-06-22 08:52 UTC, i7rincpane commented on src/main/java/faang/school/godbless/BJS211004/Unit.java
> +@Data
принял

2024-06-22 08:54 UTC, i7rincpane commented on src/main/java/faang/school/godbless/BJS211004/PowerCalculateThread.java
> +    @SneakyThrows
Да, в следующих задачах пробую выводить в отдельный метод обработки проверяемых исключений

2025-01-17 21:12 UTC, closed without merging