Implemented NotificationManager with handlers and filters for managing notifications
CorporationX/god_bless pull request #7120
Opened 2024-06-18 22:04 UTC by Meerim09

2024-06-20 04:14 UTC, pablo023 requested changes

2024-06-20 04:14 UTC, pablo023 commented on src/main/java/faang/school/godbless/metaUniverse/Main.java
> +        // Регистрация фильтров
Не надо комментарии в коде

2024-06-20 04:14 UTC, pablo023 commented on src/main/java/faang/school/godbless/metaUniverse/Main.java
> +        // Регистрация обработчиков оповещений
Не надо комментарии в коде

2024-06-20 04:14 UTC, pablo023 commented on src/main/java/faang/school/godbless/metaUniverse/Main.java
> +        // Отправка оповещений
Не надо комментарии в коде

2024-06-20 04:14 UTC, pablo023 commented on src/main/java/faang/school/godbless/metaUniverse/NotificationManager.java
> +        }
А зачем мы фильтра применяем к нотификации? Может быть оно не нужно. Тут хотя бы предикейт должен быть для того, чтобы понять - применяем ли мы фильтры?

2024-06-20 21:02 UTC, Meerim09 commented on src/main/java/faang/school/godbless/metaUniverse/Main.java
> +        // Регистрация фильтров
Removed comments, thanks!

2024-06-20 21:07 UTC, Meerim09 commented on src/main/java/faang/school/godbless/metaUniverse/NotificationManager.java
> +        }
добавилa возможность регистрировать фильтры с использованием предикатов. Теперь каждый фильтр состоит из условия (предиката) и действия (функции), которое применяется к оповещению, если условие выполняется в новом коммите

2024-06-22 22:16 UTC, pablo023 approved these changes
Молодец)

2024-06-22 22:16 UTC, merged