BJS2-11800 - Mice are very nice!
CorporationX/god_bless pull request #7130
Opened 2024-06-19 06:27 UTC by ravshanbekn

+realized functions, required in task

2024-06-23 03:27 UTC, pablo023 requested changes
Надо поправить

2024-06-23 03:27 UTC, pablo023 commented on src/main/java/faang/school/godbless/mice_nice/House.java
В условии задачи было так:

Создайте класс House, который будет содержать список комнат и еды, а также метод для сбора еды из комнат.

В классе House создайте метод main, который будет запускать пул потоков и назначать каждому потоку задачу для сбора еды из двух комнат.

Я тут этого не вижу.

2024-06-23 03:27 UTC, pablo023 commented on src/main/java/faang/school/godbless/mice_nice/Mouse.java
> +    public synchronized static void collectFood(House houseToSteelFood, List<Food> stolenFoodList) {
В цикле for запустите каждый поток в пуле с интервалом в 30 секунд, используя метод executor.schedule() и передавая ему лямбда-выражение, которое вызывает метод collectFood() из объекта house.

А какой смысл синхронизировать этот метод, если мы хотим, чтобы его вызывало несколько потоков?

2024-06-25 02:43 UTC, pablo023 requested changes
Тут очень много очень лишнего. Пожалуйста перечитай условие задачи, и делай в соответствии с ним. Тебе просто нужен класс House, в котором есть список комнат и еды, метод сбора еды из двух комнат, и просто метод, который в пяти потоках запустит эту сборку еды.

2024-06-25 02:43 UTC, pablo023 commented on src/main/java/faang/school/godbless/mice_nice/Informant.java
> +        String[] foods = getFoodList();
Это не должно быть списками строк. У тебя есть объекты Room, и Food

2024-06-25 02:43 UTC, pablo023 commented on src/main/java/faang/school/godbless/mice_nice/Informant.java
> +    }
Для чего это всё делать? У тебя логика по задаче - простая абсолютно, у тебя должны создаваться списки комнат и еды в объекте дом. Это достаточно просто сделать в конструкторе.

2024-06-25 02:43 UTC, pablo023 commented on src/main/java/faang/school/godbless/mice_nice/Informant.java
> +    }
Нет. Этот метод просто должен возващать поле rooms, которое должно быть списком обхектов Room

2024-06-25 02:43 UTC, pablo023 commented on src/main/java/faang/school/godbless/mice_nice/Informant.java
> +}
Аналогично с комментом выше.

2024-06-25 02:43 UTC, pablo023 commented on src/main/java/faang/school/godbless/mice_nice/House.java
> +            Room roomToSteelFood = null;
Никогда не надо так писать, ассайня нулл куда-либо в принципе.

2024-06-25 02:43 UTC, pablo023 commented on src/main/java/faang/school/godbless/mice_nice/House.java
> +    private Queue<Room> roomList;
Для чего здесь использовать очередь?

2024-06-25 02:43 UTC, pablo023 commented on src/main/java/faang/school/godbless/mice_nice/House.java
> +        House houseToSteelFood = Informant.findHouseToSteelFood();
Я не понимаю зачем тебе вообще этот уровень абстракции в виде класса Infromant, В условии задачи нет такого)

2024-06-25 21:34 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/mice_nice/Informant.java
> +        String[] foods = getFoodList();
Хорошо

2024-06-25 21:41 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/mice_nice/Informant.java
> +    }
Хорошо, учту

2024-06-25 21:43 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/mice_nice/Informant.java
> +    }
Понял

2024-06-25 21:43 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/mice_nice/Informant.java
> +}
Понял

2024-06-25 21:47 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/mice_nice/House.java
> +    private Queue<Room> roomList;
Изначально хотел перебирать с помощью poll. Теперь понял что room должен оставаться в house

2024-06-25 21:47 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/mice_nice/House.java
> +        House houseToSteelFood = Informant.findHouseToSteelFood();
Сори, это осталось у меня  с первого спринта.
В следующий раз буду делать только по задаче

2024-06-25 22:02 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/mice_nice/House.java
> +            Room roomToSteelFood = null;
Мне компилятор этого запрещает если я не делаю айссайн null(именно в этом прошлом коммите)
В текущем коммите, я не ассайню null, но если комнат уже нет, то делаю экстренный выход из метода. Это достигается с помощью return. Но проблема в том, что на самом первом публичном code-review ты сказал, что делать return в void методе - плохо. Тогда как мне завершить метод, если не хочу выбрасывать Exception?

2024-06-25 22:24 UTC, ravshanbekn commented
Можно ли делать return в void методе если нужно его экстренно завершить, не выбрасывая Exception? 
Я гуглил, google говорит, что есть такой pattern "return early". Можешь посмотреть, вкратце там говориться что можно сделать отдельные выходы в методе через return или throws, чем писать много вложенных if-else.  На момент этого комментария в House.java на 61 строчке стоит экстренный выход и метода. В данном случае break тоже решает эту проблему прерывая for цикл. Но что делать если, в будущем, будет такая ситуация, где мне не нужно выполнять весь остальной код в void методе?

2024-06-27 11:45 UTC, ravshanbekn commented on src/main/java/faang/school/godbless/mice_nice/House.java
Исправил

2024-06-27 23:51 UTC, pablo023 approved these changes
Нихера себе ты написал) Красиво)

2024-06-27 23:54 UTC, pablo023 commented
> Можно ли делать return в void методе если нужно его экстренно завершить, не выбрасывая Exception? Я гуглил, google говорит, что есть такой pattern "return early". Можешь посмотреть, вкратце там говориться что можно сделать отдельные выходы в методе через return или throws, чем писать много вложенных if-else. На момент этого комментария в House.java на 61 строчке стоит экстренный выход и метода. В данном случае break тоже решает эту проблему прерывая for цикл. Но что делать если, в будущем, будет такая ситуация, где мне не нужно выполнять весь остальной код в void методе? Просто на публичном code-review ты сделал замечание Kostah, что return в void методе - не очень хорошо. Поэтому спрашиваю еще раз, это нормально делать return для выходя из void метода или нет?

Это не то чтобы ненормально. Это некрасиво, и это антипаттерн. Нормально ли писать антипаттернами? На мой взгляд - нет, но глобально говоря - зависит от проекта. Если ты придешь на проект, где всё написано с игнорированием лучших практик - придется писать так, как там пишут. Либо идти на другой. Если я не забуду написать, завтра днем это уже будет где-то для всех в сообществе написано. Если забуду - не постесняйся напомнить)

2024-06-27 23:54 UTC, merged