BJS2-10912: Турнир в Королевской гавани
CorporationX/god_bless pull request #7179
Opened 2024-06-19 16:44 UTC by dossymbekov

Created and implemented classes King, Knight and Trial.
Implemented startTrial method in class King.

2024-06-19 18:19 UTC, Caveri95 commented on src/main/java/faang/school/godbless/Knight.java
> +    String name;
думаю лучше тут использовать соответствующие модификаторы доступа

2024-06-21 04:42 UTC, dossymbekov commented on src/main/java/faang/school/godbless/Knight.java
> +    String name;
Private?

2024-06-21 08:28 UTC, pablo023 requested changes

2024-06-21 08:28 UTC, pablo023 commented on src/main/java/faang/school/godbless/Knight.java
> +    String name;
> Private?

Да

2024-06-21 08:28 UTC, pablo023 commented on src/main/java/faang/school/godbless/King.java
> +        knight2.addTrial("Ride wild horse");
:D

2024-06-21 08:28 UTC, pablo023 commented on src/main/java/faang/school/godbless/King.java
> +        ExecutorService executorService = Executors.newFixedThreadPool(2);
Вот эта операция, на самом деле, дорогая вплане ресурсов процессора. По сути у тебя каждый раз создается один и тот же объект, который одно и то же делает. Допустим, этот метод вызывается 1000 раз в час. Вот у нас за этот час один и тот же объект 1000 раз создастся и убьется, при этом все эти объекты вообще ничем отличаться не будут друг от друга. Что думаешь?)

2024-06-21 08:28 UTC, pablo023 commented on src/main/java/faang/school/godbless/King.java
> +        }
Ну вот тут не совсем честный бой получится. Сначала в trials добавятся все испытания того рыцаря, который первый в списке, потом второго, и тд. Если их там будет 100, то в 99% случаев, там бОльшая часть рыцарей даже приступить не успеет, как первый уже победит. Давай подумаем над этим)

2024-06-21 09:35 UTC, dossymbekov commented on src/main/java/faang/school/godbless/King.java
> +        ExecutorService executorService = Executors.newFixedThreadPool(2);
Точно.
Думаю, нужно вывести List<Trial> trials, ExecutorService executorService вынести в main.
В методе работать с готовым объектом.
Попробую.

2024-06-21 09:40 UTC, dossymbekov commented on src/main/java/faang/school/godbless/King.java
> +        }
Они же в разных циклах, нет? Пока испытание всех рыцарей не добавит в trials не будет сабмита в executorService, нет?

2024-06-21 10:10 UTC, Kostahe reviewed
Code review

2024-06-21 10:14 UTC, dossymbekov commented on src/main/java/faang/school/godbless/King.java
> +        executorService.shutdown();
awaitTermination я уже использовал ранее в задачках. Понял тебя.

2024-06-25 03:19 UTC, merged