BJS2-11791 - Mice are very nice!
CorporationX/god_bless pull request #7185
Opened 2024-06-19 17:24 UTC by Kostahe

2024-06-29 23:50 UTC, pablo023 approved these changes
Ну ты уже почти пишешь как я, мне кажется надо было тебя медленнее учить :D

2024-06-29 23:50 UTC, pablo023 commented on src/main/java/faang/school/godbless/multithreading_parallelism/task_8/House.java
> +            room.setFoods(null);
Было бы лучше на списке еды вызывать clear. Ты бы опустошил список еды, сделав его пустым, и null бы не впихнул лишний куда-то. Вообще всегда в Java старайся избегать null,чтобы у тебя никогда он не мог вылетать ниоткуда.

2024-06-29 23:51 UTC, pablo023 requested changes
Ты знаешь, я тебе её все таки верну, чтобы ты на этот set(null) обратил внимание. Это грех смертный вообще) Исправь пожалуйста, и углубись в этот вопрос.

2024-06-30 13:27 UTC, Kostahe commented on src/main/java/faang/school/godbless/multithreading_parallelism/task_8/House.java
> +            room.setFoods(null);
Угу

2025-01-17 21:12 UTC, closed without merging