BJS2-12544 - Supercow!
CorporationX/god_bless pull request #7240
Opened 2024-06-20 14:29 UTC by Kostahe

2024-06-29 23:38 UTC, pablo023 requested changes
Вот тут я хочу, чтобы ты разобрался с тем, что такое рекорд, и почему так делать нельзя. Возвращаю.

2024-06-29 23:38 UTC, pablo023 commented on src/main/java/faang/school/godbless/multithreading_synchronization/task_3/Player.java
> +public record Player(String name) {
Так нельзя, Кость. Когда ты создаешь рекорд - у тебя не должно быть никакой декларации полей и логики далее. Рекорды задуманы как незименяемые контейнеры данных, здесь у тебя класс идёт.

2024-06-29 23:38 UTC, pablo023 commented on src/main/java/faang/school/godbless/multithreading_synchronization/task_3/SuperCow.java
> +        executor.shutdown();
Мэйн грохнет всё до того, как таски отработают.

2024-06-29 23:38 UTC, pablo023 commented on src/main/java/faang/school/godbless/multithreading_synchronization/task_3/Player.java
> +    public void startBattle(Boss boos) {
boss*

2024-06-30 13:29 UTC, Kostahe commented on src/main/java/faang/school/godbless/multithreading_synchronization/task_3/Player.java
> +public record Player(String name) {
Окей

2024-06-30 13:30 UTC, Kostahe commented on src/main/java/faang/school/godbless/multithreading_synchronization/task_3/Player.java
> +    public void startBattle(Boss boos) {
Блин как так

2024-06-30 13:30 UTC, Kostahe commented on src/main/java/faang/school/godbless/multithreading_synchronization/task_3/SuperCow.java
> +        executor.shutdown();
Окей

2025-01-17 21:12 UTC, closed without merging