BJS2-12551 - Supercow
CorporationX/god_bless pull request #7255
Opened 2024-06-20 16:39 UTC by kpzxpf

2024-06-28 01:32 UTC, pablo023 requested changes
С точки зрения ООП, присоединиться к битве, и покинуть её - это действия, которые выполняет игрок. Быть они должны в его классе, соответственно. Вызывать на объекте класса Boss метод "покинуть битву" - неправильно, т.к. покидает её не он, а игрок. Если ты хочешь, чтобы этот функционал принадлежал боссу, то нужно что-то в духе "исключить игрока из игры", но это тоже не особо логично, т.к. игрок сам решать должен - когда ему играть, а когда - покидать игру.

2024-06-28 13:55 UTC, kpzxpf commented on src/main/java/faang/school/godbless/supercow/Boss.java
> +    private List<Player> currentPlayer;
Исправил

2024-06-28 13:56 UTC, kpzxpf commented on src/main/java/faang/school/godbless/supercow/Boss.java
> +            throw new IllegalArgumentException("Player " + player.getName() + " is not on the battle!");
Изменил

2024-06-28 13:56 UTC, kpzxpf commented on src/main/java/faang/school/godbless/supercow/Main.java
> +        ExecutorService executor = Executors.newFixedThreadPool(2);
ок

2024-06-28 13:58 UTC, kpzxpf commented
> С точки зрения ООП, присоединиться к битве, и покинуть её - это действия, которые выполняет игрок. Быть они должны в его классе, соответственно. Вызывать на объекте класса Boss метод "покинуть битву" - неправильно, т.к. покидает её не он, а игрок. Если ты хочешь, чтобы этот функционал принадлежал боссу, то нужно что-то в духе "исключить игрока из игры", но это тоже не особо логично, т.к. игрок сам решать должен - когда ему играть, а когда - покидать игру.

Поменял логику, мне кажется, что сейчас логично

2024-06-30 02:24 UTC, pablo023 approved these changes
Теперь ок, молодец)

2024-06-30 02:24 UTC, merged