BJS2-BJS2-12552 Supercow
CorporationX/god_bless pull request #7325
Opened 2024-06-21 18:06 UTC by shade2903

2024-06-28 01:39 UTC, pablo023 requested changes
Не то чтобы тут есть существенные ошибки, но хочу, чтобы ты обратил на это внимание, и подумал)

2024-06-28 01:39 UTC, pablo023 commented on src/main/java/faang/school/godbless/synchronization/sypercow/Player.java
> +    private final Long TIME_ATTACK = 1000L;
Я не думаю, что нам здесь нужен класс-обертка, т.к. он нагружает память сильнее, чем примитив. Собственно, лонг - тоже. Нужен ли он тут?

2024-06-28 01:39 UTC, pablo023 commented on src/main/java/faang/school/godbless/synchronization/sypercow/Boss.java
> +    public synchronized void joinBattle(Player player) {
joinBattle - это буквально присоединиться к битве. Вызывая этот метод на объекте класса Босс, ожидаемое поведение - что этот босс в какую-то битву влезает. А у нас тут как бы он игрока к себе в битву затягивает, но.. Игрок сам заходит же поиграть?

2024-06-28 01:39 UTC, pablo023 commented on src/main/java/faang/school/godbless/synchronization/sypercow/Boss.java
> +                System.out.println(String.format("Slots is full! %s please wait....", player.getName()));
Давай использовать логирование, с Slf4j

2024-06-28 01:39 UTC, pablo023 commented on src/main/java/faang/school/godbless/synchronization/sypercow/Boss.java
> +                throw new RuntimeException(e);
Вот тут кинуть можно было бы какое-то сообщение описательное - что пошло не так, а не просто e

2024-06-28 01:39 UTC, pablo023 commented on src/main/java/faang/school/godbless/synchronization/sypercow/Boss.java
> +    public synchronized void leaveBattle(Player player) {
Ну опять таки, у нас получается босс битву покидает. А покидает то её игрок. Либо это надо в класс Player, либо если босс исключает игрока - removePlayer его назвать было бы уместнее.

2024-06-28 01:39 UTC, pablo023 commented on src/main/java/faang/school/godbless/synchronization/sypercow/Boss.java
> +            this.notify();
Как насчет notifyAll? У нас же несколько потоков могут ожидать, когда место освободися.

2024-06-28 01:39 UTC, pablo023 commented on src/main/java/faang/school/godbless/synchronization/sypercow/Player.java
> +        boss.joinBattle(this);
Нуууууууууууу. Если было бы boss.addPlayerToBattle() было бы уместнее)

2024-07-01 09:35 UTC, shade2903 commented on src/main/java/faang/school/godbless/synchronization/sypercow/Player.java
> +    private final Long TIME_ATTACK = 1000L;
Понял, поправил.

2024-07-01 09:36 UTC, shade2903 commented on src/main/java/faang/school/godbless/synchronization/sypercow/Boss.java
> +                System.out.println(String.format("Slots is full! %s please wait....", player.getName()));
Исправил на логиррование

2024-07-01 11:16 UTC, shade2903 commented on src/main/java/faang/school/godbless/synchronization/sypercow/Boss.java
> +    public synchronized void joinBattle(Player player) {
такие названи методов были по заданию. Исправил на playerJoinBattle( );

2024-07-01 11:20 UTC, shade2903 commented on src/main/java/faang/school/godbless/synchronization/sypercow/Boss.java
> +                throw new RuntimeException(e);
Добавил сообщение и логирование ошибки.

2024-07-01 11:23 UTC, shade2903 commented on src/main/java/faang/school/godbless/synchronization/sypercow/Boss.java
> +    public synchronized void leaveBattle(Player player) {
переименовал метод removePlayerFromBattle();

2024-07-01 11:24 UTC, shade2903 commented on src/main/java/faang/school/godbless/synchronization/sypercow/Boss.java
> +            this.notify();
ОК.

2024-07-01 11:24 UTC, shade2903 commented on src/main/java/faang/school/godbless/synchronization/sypercow/Player.java
> +        boss.joinBattle(this);
Поправил.

2024-07-03 09:47 UTC, merged