Железный трон любой ценой
CorporationX/god_bless pull request #7332
Opened 2024-06-21 19:53 UTC by kpzxpf

2024-06-28 03:26 UTC, pablo023 commented
На публичное код ревью

2024-06-29 12:26 UTC, pablo023 requested changes
Исправь, пожалуйста, вложенную синхронизацию.

2024-06-29 12:26 UTC, pablo023 commented on src/main/java/faang/school/godbless/theIronThroneatAnyCost/User.java
> +                synchronized (lock) {
Никогда не используем вложенную синхронизацию. Если тебе нужно построить взаимодействие на синхронизации на нескольких объектах, создавай, пожалуйста, разные локи. И будь внимателен к порядку их захвата.

2024-06-29 20:36 UTC, kpzxpf commented on src/main/java/faang/school/godbless/theIronThroneatAnyCost/User.java
> +                synchronized (lock) {
Исправил

2024-06-30 03:20 UTC, merged