BJS2-13511: Fan out – Fan In
CorporationX/god_bless pull request #7547
Opened 2024-06-25 15:05 UTC by YPG0

2024-07-01 05:36 UTC, pablo023 requested changes
Давай поправим всё таки тут.

2024-07-01 05:36 UTC, pablo023 commented on src/main/java/FanOutFanIn/Main.java
> +        allTask.join();
Вот это блокнет весь метод. По-хорошему, это надо делать иначе, и результат получать асинхронно

2024-07-03 04:29 UTC, YPG0 commented on src/main/java/FanOutFanIn/ResultConsumer.java
> +    ResultConsumer(Long init) {
Добавил

2024-07-03 04:29 UTC, YPG0 commented on src/main/java/FanOutFanIn/SquareRequest.java
> +        } catch (InterruptedException e) {
Добавил

2024-07-03 04:44 UTC, YPG0 commented on src/main/java/FanOutFanIn/Main.java
> +        allTask.join();
Вызов join перенес в мейн

2024-07-05 02:41 UTC, merged