BJS2-13852 - "WOW"
CorporationX/god_bless pull request #7650
Opened 2024-06-26 19:56 UTC by i7rincpane

1. отправил двух пользователей ассинхронно на квест, результаты отображаю после завершении квеста, не дожидаясь в главном потоке

2024-06-29 13:18 UTC, pablo023 requested changes
Есть небольшие недочеты.

2024-06-29 13:18 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS213852/ApplicationRunner.java
> +                    return null;
Не надо никогда писать return null.

2024-06-29 13:18 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS213852/ApplicationRunner.java
> +        //TODO:27.06.2024 не смог разобраться зачем у exceptionally делать return?
Комментарии никогда не должны попадать в пулл-реквест.

2024-06-29 13:18 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS213852/ApplicationRunner.java
> +
Тут было бы лучше вытащить этот экзекьтор в отдельное поле.

2024-06-29 13:18 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS213852/QuestSystem.java
> +    }
У нас тут лишний слой абстракции. Логики никакой дополнительной нет. Состояния тоже нет. Поэтому это просто лишний код.

2024-06-29 13:18 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS213852/ApplicationRunner.java
> +        questSystem.shutdown();
Вот здесь вот ты мгновенно шатдаунишь questSystem, дальше у тебя мэйн может просто не дождаться их выполнения.

2024-06-30 07:33 UTC, i7rincpane commented on src/main/java/faang/school/godbless/BJS213852/ApplicationRunner.java
> +                    return null;
Я не понимаю что exceptionally хочет чтобы я возвращал

2024-07-01 07:06 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS213852/ApplicationRunner.java
> +                    return null;
Можно залогать и швырнуть рантайм

2025-01-17 21:14 UTC, closed without merging