Ypg0 bjs2 13755
CorporationX/god_bless pull request #7660
Opened 2024-06-27 06:49 UTC by YPG0

2024-07-01 06:43 UTC, pablo023 requested changes
Чуть чуть исправь.

2024-07-01 06:43 UTC, pablo023 commented on src/main/java/CollectOrdersOnAmazon/OrderProcessor.java
> +                order.setStatus("Processed");
Это происходит вне синхронизированного контекста. Небезопасно.

2024-07-02 17:44 UTC, YPG0 commented on src/main/java/CollectOrdersOnAmazon/OrderProcessor.java
> +                order.setStatus("Processed");
Повесил на сам метод setStatus synchronized. Он же быстрый по идеи, а sleep имитирует работу и у всех она разное время займет. Потоки не встанут же в линейное выполнение?

2024-07-05 02:43 UTC, pablo023 commented on src/main/java/CollectOrdersOnAmazon/OrderProcessor.java
> +                order.setStatus("Processed");
Я понял. В линейное выполнение - ну выспятся примерно по-очереди, как процессор считает справедливым, продолжат работу.

2024-07-05 02:43 UTC, merged