Задача с методом на группировку юзеров по возрасту
CorporationX/god_bless pull request #7817
Opened 2024-08-02 12:44 UTC by ilu23ilu23

2024-08-06 04:09 UTC, pablo023 requested changes

2024-08-06 04:09 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_18436/User.java
> +        Set<Integer> ages = new HashSet<>();
ageSet*

2024-08-06 04:09 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_18436/User.java
> +                }
Ты итерируешься по пустому списку, тут этот if никогда не будет true.

2024-08-06 05:52 UTC, ilu23ilu23 commented on src/main/java/faang/school/godbless/BJS2_18436/User.java
> +        Set<Integer> ages = new HashSet<>();
ok

2024-08-06 05:52 UTC, ilu23ilu23 commented on src/main/java/faang/school/godbless/BJS2_18436/User.java
> +                }
ok

2024-08-06 06:03 UTC, ilu23ilu23 commented
Исправил

2024-08-07 11:14 UTC, pablo023 approved these changes

2024-08-07 11:14 UTC, merged