BJS2-18422 Группировка пользователей по возрасту
CorporationX/god_bless pull request #7820
Opened 2024-08-02 13:24 UTC by cemeh666

2024-08-04 16:38 UTC, pablo023 requested changes

2024-08-04 16:38 UTC, pablo023 commented on src/main/java/users/group/by/age/User.java
> +        HashMap<Integer, List<User>> groupedUsers = new HashMap<>();
Исправь HashMap на Map, писал в предыдущем ревью.

2024-08-04 16:38 UTC, pablo023 commented on src/main/java/users/group/by/age/User.java
> +                groupedUsers.put(user.age, new LinkedList<>(List.of(user)));
Зачем нам тут связанный список? Тем более, который создан из немутабельного списка, в котором лежит юзер?

2024-08-04 16:49 UTC, cemeh666 commented on src/main/java/users/group/by/age/User.java
> +                groupedUsers.put(user.age, new LinkedList<>(List.of(user)));
Связанный, так как в него быстро можно добавлять записи

2024-08-06 04:04 UTC, pablo023 commented on src/main/java/users/group/by/age/User.java
> +                groupedUsers.put(user.age, new LinkedList<>(List.of(user)));
Почитай про разницу связанного списка и динамического массива. Этот аргумент здесь не актуален, т.к. в связанный список добавляется быстрее только при условии того, что огромные данные, и вставка происходит всередину.

2024-08-06 04:06 UTC, pablo023 requested changes
В использовании связанного списка всё еще нет смысла, так не нужно писать. LinkedList - коллекция, которая применяется в исключительных случаях, когда в связанности имеется смысл. Тут его нет.

2024-08-06 07:19 UTC, cemeh666 commented on src/main/java/users/group/by/age/User.java
> +                groupedUsers.put(user.age, new LinkedList<>(List.of(user)));
поменял на ArrayList

2024-08-07 11:04 UTC, pablo023 approved these changes

2024-08-07 11:06 UTC, merged