BJS2-18396 Регистрация пользователей
CorporationX/god_bless pull request #7824
Opened 2024-08-02 13:54 UTC by cemeh666

2024-08-04 16:40 UTC, pablo023 requested changes

2024-08-04 16:40 UTC, pablo023 commented on src/main/java/users/group/by/age/User.java
> +    private static final List<String> VALID_ADDRESSES = Arrays.asList("London", "New York", "Amsterdam");
Условие задачи - объявить два статических сета, не листа.

2024-08-04 16:40 UTC, pablo023 commented on src/main/java/users/group/by/age/User.java
> +        if (name.isBlank() || age < 18 || !VALID_JOBS.contains(workPlace) || !VALID_ADDRESSES.contains(address)) {
18 в данном случае - магическое число. Почитай про этот антипаттерн в гугле. Выносить нужно в константу.

2024-08-04 16:40 UTC, pablo023 commented on src/main/java/users/group/by/age/User.java
> +    public User(String name, String workPlace, String address, int age) throws IllegalArgumentException {
Нам необязательно указывать в сигнатуре метода, что он кидает исключение-наследник RuntimeException. Смысла в этом нет, код становится длиннее.

2024-08-05 08:43 UTC, cemeh666 commented on src/main/java/users/group/by/age/User.java
> +        if (name.isBlank() || age < 18 || !VALID_JOBS.contains(workPlace) || !VALID_ADDRESSES.contains(address)) {
согласен!

2024-08-05 08:44 UTC, cemeh666 commented on src/main/java/users/group/by/age/User.java
> +    private static final List<String> VALID_ADDRESSES = Arrays.asList("London", "New York", "Amsterdam");
Окей

2024-08-05 08:44 UTC, cemeh666 commented on src/main/java/users/group/by/age/User.java
> +    public User(String name, String workPlace, String address, int age) throws IllegalArgumentException {
Хорошо

2024-08-06 04:15 UTC, merged