BJS2-18394 : Регистрация пользователей
CorporationX/god_bless pull request #7827
Opened 2024-08-02 14:29 UTC by soulasphyxia

2024-08-06 18:07 UTC, GlebKlimakhin requested changes

2024-08-06 18:07 UTC, GlebKlimakhin commented on src/main/java/users_registration/User.java
> +        if (name.trim().isEmpty() || age < 18
для этого есть метод isBlank

2024-08-06 18:07 UTC, GlebKlimakhin commented on src/main/java/users_registration/User.java
> +        if (name.trim().isEmpty() || age < 18
в задании сказано провести валидацию в конструкторе, но на будущее лучше выносить это в отдельный метод)

2024-08-09 12:24 UTC, InnMish commented on src/main/java/users_registration/User.java
> +            throw new IllegalArgumentException();
когда кидаем ошибку, всегда важно писать текст сообщения, чтобы дать пользователям понять, что пошло не так 
Голые ошибки кидать - плохая практика)

2024-08-09 12:24 UTC, InnMish commented on src/main/java/users_registration/User.java
> +        return name.isBlank() && age < 18
18 несем в константу 
Вообще числа и строчки привыкай не хардкодить вот так

2024-08-09 12:24 UTC, InnMish commented on src/main/java/users_registration/User.java
> +        return name.isBlank() && age < 18
интересный факт: в доке про isBlank написано, что он проверяет на null, но на самом деле нет хехе 
поэтому добавить проверку на нал, а до этого протестируй, что нал-имя тут и правда не кинет ошибки

2024-08-09 12:24 UTC, InnMish commented on src/main/java/users_registration/User.java
> +        return name.isBlank() && age < 18
и вообще было бы неплохо для каждого параметра кинуть свое исключение с ошибкой конкретно для этого параметра, чтобы пользователь сразу понял, какое именно поле он заполнил неправильно

2024-08-10 11:40 UTC, soulasphyxia commented on src/main/java/users_registration/ErrorMessages.java
попытался вынести все сообщения об ошибка в отдельный класс с public  константами, считаю это не более чем заглушкой, потому что насколько я знаю все такие сообщения обычно лежат в отдельном файле и там через Locale и аннотацию Value их используют

2024-08-11 02:44 UTC, merged