Создал класс User, выполнил таск BJS2-18448
CorporationX/god_bless pull request #7847
Opened 2024-08-02 17:43 UTC by wmwmaks

Создал класс User и метод sortingUsersByAge, который сортирует юзеров по возрасту.

2024-08-06 17:48 UTC, GlebKlimakhin requested changes

2024-08-06 17:48 UTC, GlebKlimakhin commented on src/main/java/faang/school/godbless/User.java
> +@AllArgsConstructor
Подумай над дефолтной имплементацией hashCode и над тем, какие проблемы могут возникнуть в связи с этим при использовании hashMap.

2024-08-06 17:48 UTC, GlebKlimakhin commented on src/main/java/faang/school/godbless/User.java
> +            usersByAge.putIfAbsent(user.getAge(), new ArrayList<>());
В мапу кладёшь пустой список, а должен положить пользователя.

2024-08-06 20:04 UTC, wmwmaks commented on src/main/java/faang/school/godbless/User.java
> +            usersByAge.putIfAbsent(user.getAge(), new ArrayList<>());
В следующей строке добавляю же в этот список пользователя?

2024-08-09 11:55 UTC, InnMish approved these changes

2024-08-09 11:55 UTC, merged