Grouping by age done
CorporationX/god_bless pull request #7857
Opened 2024-08-02 19:16 UTC by IvanTsegelnyuk

Grouping users by age

2024-08-06 04:11 UTC, pablo023 requested changes

2024-08-06 04:11 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_18459/User.java
> +            });
Даже если это и сработает, это излишне сложно написано. 

1) Итерируешься по списку пользователей
2) Если в мапе есть ключ с возрастом пользователя - кладешь пользователя в значение
3) Если нет - кладешь ключом возраст, значением - пустой список, куда докладываешь пользователя

2024-08-06 16:10 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/godbless/BJS2_18459/User.java
> +            });
Не знаю, понравился мне этот метод, везде его использовал. Вроде работает, плюс якобы используем "нововведения java 8".
Исправил

2024-08-07 11:15 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_18459/User.java
> +            });
Нововведения java 8 уместны в определенных случаях, когда нам не охота писать анонимные классы, либо большой цикл фор, который двумя строками стрим апи

2024-08-07 11:16 UTC, pablo023 approved these changes

2024-08-07 11:16 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_18459/User.java
> +            }
Окей, но почитай про computeIfAbscent.

2024-08-07 11:16 UTC, merged