Added User class, added method for group users, added tests
CorporationX/god_bless pull request #7893
Opened 2024-08-03 10:19 UTC by SharkB38

Задача Группировка пользователей по возрасту:
https://faang-school.atlassian.net/browse/BJS2-18469

Условия задачи
Создать класс 
User со следующими полями:
имя;
возраст;
место работы;
адрес.

В этом же классе создать статический метод 

groupUsers, который принимает List из объектов User и возвращает Map, где ключом является возраст пользователя, а значением — список из всех пользователей в оригинальном списке, которые имеют соответствующий возраст.

2024-08-06 17:53 UTC, GlebKlimakhin approved these changes

2024-08-06 17:53 UTC, GlebKlimakhin commented
Пожалуйста поправь конфликт для мерджа.

2024-08-06 17:55 UTC, GlebKlimakhin requested changes

2024-08-06 17:55 UTC, GlebKlimakhin commented on src/test/java/UserTest.java
> +}
Пожалуйста поправь конфликт для мерджа.

2024-08-07 02:46 UTC, SharkB38 commented on src/test/java/UserTest.java
> +}
Исправил

2024-08-09 12:00 UTC, InnMish commented on src/main/java/user/group/User.java
> +            return null;
давай лучше пустую мапу вернем 
null возвращать вообще не очень практика 
А что, если этот метод используется еще где-то, где никто не ожидает получить null?

2024-08-09 12:00 UTC, InnMish commented on src/main/java/user/group/User.java
> +        Map<Integer, List<User>> ageMap = new HashMap<>();
в названии поля можно не указывать тип этого поля, потому что я и так вижу, что это мапа)

2024-08-09 12:00 UTC, InnMish commented on src/main/java/user/group/User.java
> +            }
посмотри метод мапы computeIfAbsent  - отлично подходит для цели этой задачи

2024-08-11 01:27 UTC, merged