Регистрация пользователей
CorporationX/god_bless pull request #7945
Opened 2024-08-03 16:19 UTC by ArstanSubanov

Java Core, Задача № BJS2-18461

2024-08-06 18:18 UTC, GlebKlimakhin requested changes

2024-08-06 18:18 UTC, GlebKlimakhin commented on src/main/java/faang/school/godbless/bjs218461/User.java
> +        if (!VALID_JOBS.contains(workPlace) || workPlace == null) {
всё можно сделать одним if-ом, избавишься от дублирования

2024-08-06 18:18 UTC, GlebKlimakhin commented on src/main/java/faang/school/godbless/bjs218461/User.java
> +    public static Map<Integer, List<User>> groupUsers(List<User> users) {
здесь не должно быть этих изменений, это другая задача

2024-08-07 08:20 UTC, ArstanSubanov commented on src/main/java/faang/school/godbless/bjs218461/User.java
> +    public static Map<Integer, List<User>> groupUsers(List<User> users) {
Эта задача идёт сразу после задачи: Группировка пользователей. И в условии этой задачи нужно было использовать класс User из предыдущей задачи, так как я сделал эту задачу на онбординге, то эти 2 задачи были объединены. Поэтому тут присутствует метод из предыдущей задачи.

2024-08-11 02:45 UTC, merged