Library
CorporationX/god_bless pull request #7955
Opened 2024-08-03 17:16 UTC by IvanTsegelnyuk

Library

2024-08-06 04:41 UTC, pablo023 requested changes

2024-08-06 04:41 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_19243/Main.java
> +        library.put(new Book("Ruslan and Liudmila", "Pushkin", 1735), "1");
Почитай пожалуйста про аннотацию, и паттерн Builder.

2024-08-06 04:41 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_19243/Main.java
> +        String result = library.remove(new Book(title, author, year));
Не надо создавать новый объект просто для того, чтобы удалить что-то.

2024-08-06 04:41 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_19243/Main.java
> +        return result != null;
А зачем тебе вообще тут return?

2024-08-06 04:41 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_19243/Main.java
> +        String result = library.remove(new Book(title, author, year));
Ко всему прочему, книги, которую передали в метод, может в библиотеке не быть вовсе.

2024-08-06 04:41 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_19243/Main.java
> +        else return "There is no such book in library";
Используй фигурные скобки после if, и else. Всегда.

2024-08-06 17:58 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/godbless/BJS2_19243/Main.java
> +        else return "There is no such book in library";
Исправил

2024-08-06 17:59 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/godbless/BJS2_19243/Main.java
> +        return result != null;
Чтобы было понятно, было ли удалено переданное (true) или нет (false)
Оставил

2024-08-06 17:59 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/godbless/BJS2_19243/Main.java
> +        String result = library.remove(new Book(title, author, year));
Исправил

2024-08-06 18:01 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/godbless/BJS2_19243/Main.java
> +        library.put(new Book("Ruslan and Liudmila", "Pushkin", 1735), "1");
Был в курсе, но для простых объектов не думал его использовать. Исправил с применением билдера

2024-08-07 12:09 UTC, pablo023 approved these changes

2024-08-07 12:09 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_19243/Main.java
> +        Book book = new Book(title, author, year);
Опять создал объект лишний раз) Не нужно этого делать.

2024-08-07 12:10 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_19243/Main.java
> +        return result != null;
delete это обычно войд. Если у тебя не получилось удалить, кидаешь эксепшен и логируешь это. Либо строишь логику удаления через изначальную проверку на то, что она существует вообще - книга эта.

2024-08-07 12:10 UTC, pablo023 requested changes
Убери этот булеан из удаления, и создание объекта для поиска.

2024-08-07 20:05 UTC, IvanTsegelnyuk commented
Исправил delete, убрал создание объекта

2024-08-09 03:18 UTC, merged