Count misses
CorporationX/god_bless pull request #7984
Opened 2024-08-03 20:27 UTC by IvanTsegelnyuk

Count misses

2024-08-06 04:47 UTC, pablo023 requested changes

2024-08-06 04:47 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_19328/Main.java
> +        while(iterator.hasNext()) {
А зачем вот эта конструкция, если мы можем просто итерироваться через список всех студентов через forEach?

2024-08-06 04:47 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_19328/Main.java
> +                    });
Так не пойдет. Пишем минимально код, и как можно проще. Просто создаешь объект Group, смотришь - есть ли в мапе. Есть - добавляешь туда студента, нет - создаешь в мапе ключ значение, и добавляешь студента.

2024-08-06 18:29 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/godbless/BJS2_19328/Main.java
> +        while(iterator.hasNext()) {
Нельзя же модифицировать коллекцию без итератора?
Попробовал через forEach, получил ConcurrentModificationException. И через стандартный forEach, и через forEach с лямбдой. Либо я не так понял
Исправил на removeIf

2024-08-06 18:29 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/godbless/BJS2_19328/Main.java
> +                    });
Исправил

2024-08-06 18:31 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/godbless/BJS2_19328/Main.java
> +        while(iterator.hasNext()) {
Наверно ты имел в виду, удаляем и прекращаем итерацию... Уже так запушил.., но я понял

2024-08-07 12:23 UTC, pablo023 requested changes

2024-08-07 12:23 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_19328/Main.java
> +    }
В статических классах почти что никогда нет необходимости, лучше всегда создавать отдельные

2024-08-07 12:23 UTC, pablo023 commented on src/test/java/faang/school/godbless/BJS2_19328/MainTest.java
Ознакомься с аннотацией DisplayName для тестов

2024-08-07 12:23 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_19328/Main.java
> +                result.put(group, new ArrayList<>(List.of(student)));
Вот так когда пишешь - у тебя немутабельная коллекция List.of() потом преобразуется к мутабельной ArrayList. Проще, чище и эффективнее писать так:

new ArrayList<>().add(student)

2024-08-07 12:23 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_19328/Main.java
> +    }
А что это, почему это не в мейн методе?

2024-08-07 20:24 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/godbless/BJS2_19328/Main.java
> +    }
Понял. Сделал отдельным классом

2024-08-07 20:24 UTC, IvanTsegelnyuk commented on src/test/java/faang/school/godbless/BJS2_19328/MainTest.java
Прочитал. В будущем буду использовать

2024-08-07 20:24 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/godbless/BJS2_19328/Main.java
> +                result.put(group, new ArrayList<>(List.of(student)));
Понял. Но конкретно тут так не получается, т.к. add возвращает boolean, а у нас ожидается коллекция. Поэтому расписал полностью
![Безымянный](https://github.com/user-attachments/assets/4aa27f6b-c2e9-4f71-9958-ecbf4eeda773)

2024-08-07 20:25 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/godbless/BJS2_19328/Main.java
> +    }
Это вообще было для инициализации для тестов. Перенес в тесты

2024-08-07 21:02 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/godbless/BJS2_19328/Main.java
> +                result.put(group, new ArrayList<>(List.of(student)));
тут можно, как ты написал в другом ПРе : result.computeIfAbsent(group, k -> new ArrayList<>()).add(student);

2024-08-09 03:38 UTC, merged