Сделал класс Server, содержащий информацию о нагрузке и энергопотребл…
CorporationX/god_bless pull request #7991
Opened 2024-08-04 01:42 UTC by PLSGOTOASS

…ении сервера. Сделал класс DataCenter, который хранит список серверов.

Сделал класс ResourceRequest который является запросом на действия с ресурсами. Сделал класс DataCenterService в котором реализовал методы для работы с серверами и нагрузками. Сделал интерфейс OptimizationStrategy и реализовал его в классе DataCenterService. Реализация распределяет нагрузку по серверам (равномерно насколько возможно). Покрыл весь код unit-тестами и сделал тесты в классе Main

2024-08-07 10:11 UTC, pablo023 requested changes

2024-08-07 10:11 UTC, pablo023 commented on src/main/java/faang/school/godbless/DataCenter/DataCenterService.java
Ты не добавил метод для удаления сервера из дата-центра

2024-08-07 10:11 UTC, pablo023 commented on src/main/java/faang/school/godbless/DataCenter/DataCenterService.java
> +                server.setLoad(server.getMAX_LOAD());
Это не оптимально. Сначала сеттишь, потом проверяешь, и если получилось больше, чем можно - что-то делаешь. 

for (Server server : servers ) {
    currentLoad = server.getLoad();
    if ((currentLoad + loadToAllocate) > server.getMAX_LOAD()) {
        continue;
    } else {
        server.setLoad(server.getLoad() + loadToAllocate);
    }
}

2024-08-07 10:11 UTC, pablo023 commented on src/main/java/faang/school/godbless/DataCenter/DataCenterService.java
> +            } else break;
После else всегда ставь фигурную скобку, и переноси операцию на следующую строку. Это проще читать.

2024-08-07 10:11 UTC, pablo023 commented on src/main/java/faang/school/godbless/DataCenter/DataCenterService.java
> +        }
Если хочешь добавить логирование на такой случай, добавь в объект ResourceRequest булеан флаг какой-то типа isAllocated, и меняй его, если удалось аллоцировать реквест. В конце метода можешь на основе этого флага выполнять проверку. toAllocate != 0 - так себе

2024-08-07 10:11 UTC, pablo023 commented on src/main/java/faang/school/godbless/DataCenter/DataCenterService.java
> +            } else break;
Аналогично с тем, что сверху. Сначала проверяй, можно ли, и если можно - делай. И брейк на отдельную строку.

2024-08-07 10:11 UTC, pablo023 commented on src/main/java/faang/school/godbless/DataCenter/DataCenterService.java
> +    public void optimize() {                                 //ну короче он пытается распределить нагрузку равномерно между всеми серверами (насколько это возможно)
Не оставляй комментарии в коде, я по названию метода должен понимать что тут происходит

2024-08-07 10:11 UTC, pablo023 commented on src/main/java/faang/school/godbless/DataCenter/DataCenterService.java
> +    public void optimize() {                                 //ну короче он пытается распределить нагрузку равномерно между всеми серверами (насколько это возможно)
В целом это неплохо, но это не просто оптимизация, а что-то в духе distributeLoadEvenlyAcrossServers. Оптимизация не всегда про равномерную нагрузку, т.к. у тебя она распределяется тоже неравномерно, а ты ищешь сервер, который реквест целиком может схавать. 

Если у тебя всего 10 серверов, и максимальная нагрузка, которую может выдержать сервер, равна 100, придет реквест на 100, попадет на сервер, и потом произойдет распределение - у тебя будет по 10 едтниц нагрузки на сервер. Если после этого придет еще один реквест на 100 - он никогда не будет аллоцирован, хотя можно это сделать как угодно - раскидав ту нагрузку, что уже есть, по 50 на два сервера, либо целиком 100 кинуть на один.

2024-08-07 14:53 UTC, PLSGOTOASS commented on src/main/java/faang/school/godbless/DataCenter/DataCenterService.java
> +    public void optimize() {                                 //ну короче он пытается распределить нагрузку равномерно между всеми серверами (насколько это возможно)
Я не понял немного:
Если придёт один реквест на 100, то тогда он распределится по 10 на каждый сервер (после оптимизации, изначально его полностью схавает один сервер). Если придёт ещё один на 100, то тогда один сервер схавает 90 (10 уже забито), и второй оставшиеся 10 дожрёт. И того будет 100 20 10 10... . После оптимизации он уже спокойно должен распределить их. и будет 20 20 20 20 20.....  
Или я что то не так понимаю?

2024-08-08 21:06 UTC, miked4king commented on src/main/java/faang/school/godbless/DataCenter/DataCenter.java
> +    private final List<Server> SERVERS = new ArrayList<>();
camel case

2024-08-10 18:57 UTC, merged