Amazon
CorporationX/god_bless pull request #8028
Opened 2024-08-04 10:53 UTC by IvanTsegelnyuk

Amazon

2024-08-07 12:36 UTC, pablo023 requested changes

2024-08-07 12:36 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_19304/Main.java
> +        Map<String, List<Product>> result = new HashMap<>();
groupedProducts* Привыкай называть переменные и объекты так, чтобы название отражало суть

2024-08-07 12:36 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_19304/Main.java
> +        return result;
В этом нет смысла, это не читаемо, по сравнению с 

for (Product product : products) {
....result.computeIfAbsent(product.getCategory(), k -> new ArrayList<>()).add(product);
}

Минимум кода, максимально просто и понятно

П

2024-08-07 21:14 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/godbless/BJS2_19304/Main.java
> +        Map<String, List<Product>> result = new HashMap<>();
исправил

2024-08-07 21:17 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/godbless/BJS2_19304/Main.java
> +        return result;
До этого момента не знал, что метод put у мапы возвращает предыдущее значение, если оно было у ключа, и null, если не было. Думал, что он возвращает только что вставленное значение. Теперь понял смысл и разницу между обычным put computeIfAbsent

2024-08-09 03:33 UTC, pablo023 commented
BJS2-19304 - Java HashMap: Разбираем склад Amazon - так должен называться ПР.

2024-08-09 03:34 UTC, merged