Создал программу, которая группирует список студентов по факультетам …
CorporationX/god_bless pull request #8034
Opened 2024-08-04 11:21 UTC by wmwmaks

…и курсам с использованием HashMap.

2024-08-06 19:36 UTC, GlebKlimakhin approved these changes

2024-08-06 19:36 UTC, GlebKlimakhin commented on src/main/java/faang/school/godbless/Faculty.java
> +public class Faculty {
плохое название класса, т.к. хранишь и факультет и год. в крайнем случае можно было бы взять CompositeKey или что-то такое, более служебное

2024-08-06 19:38 UTC, GlebKlimakhin commented on src/main/java/faang/school/godbless/Faculty.java
> +public class Faculty {
и конфликт порешай пж

2024-08-06 19:39 UTC, GlebKlimakhin requested changes
конфликт

2024-08-07 10:00 UTC, wmwmaks commented on src/main/java/faang/school/godbless/Faculty.java
> +public class Faculty {
Согласен, что название плохое, но не знал как правильно назвать класс. CompositeKey возьму на заметку

2025-01-17 21:16 UTC, closed without merging