BJS2-18437 User registration
CorporationX/god_bless pull request #8073
Opened 2024-08-04 15:05 UTC by amilosh

2024-08-09 02:55 UTC, pablo023 requested changes
Ты очень много лишнего пишешь, и изобретаешь велосипеды) Абстракция нужна для реализации полиморфизма, и принципов I и D из SOLID, а не просто потому что она существует в природе, и через неё нужно писать всё, что через неё можно написать. Если ты сейчас это делаешь по фану, то окей, но на реальных задачах это мейкс но сенс, и разрабатывать нужно быстро и просто.

2024-08-09 02:55 UTC, pablo023 commented on src/main/java/faang/school/godbless/bjs2_18437/AppCollectionUtils.java
> +    public <E> boolean isCollectionContainsElement(Collection<E> collection, E e) {
Не is, а does

2024-08-09 02:55 UTC, pablo023 commented on src/main/java/faang/school/godbless/bjs2_18437/AppStringUtils.java
> +    }
Есть такая аннотация - NotBlank, в спринг буте.

2024-08-09 02:55 UTC, pablo023 commented on src/main/java/faang/school/godbless/bjs2_18437/Main.java
> +        }
Делай это через тесты, и JUnit.

2024-08-09 02:59 UTC, pablo023 requested changes

2024-08-09 02:59 UTC, pablo023 commented on src/main/java/faang/school/godbless/bjs2_18437/User.java
> +    private Integer age;
Зачем нам тут ссылочный тип? Мы будем использовать методы Integer?

2024-08-09 02:59 UTC, pablo023 commented on src/main/java/faang/school/godbless/bjs2_18437/User.java
> +    private void validateUserCreation(String name, Integer age, String jobPlace, String address, boolean throwMessage) {
А при каком кейсе в реальной жизни тебе будет приходить такой булеан параметр?

2024-08-09 02:59 UTC, pablo023 commented on src/main/java/faang/school/godbless/bjs2_18437/UserValidator.java
> +    }
Ну.. Это не имеет смысла, абсолютно) Тебе не нужно несколько обработок, которые ничем не отличаются в логике, кроме возвращаемого типа значения.

2024-08-09 20:23 UTC, amilosh commented on src/main/java/faang/school/godbless/bjs2_18437/AppCollectionUtils.java
> +    public <E> boolean isCollectionContainsElement(Collection<E> collection, E e) {
У меня логика такая была, что есть какой-то булеан
boolean сollectionContainsElement = true
А когда мы делаем get булеана, то исползуем is. По аналогии isEmpty, isValid - isсollectionContainsElement.
Поменял на does, хотя выглядит непривычно и никогда слово does не попадалась (хотя может и внимания просто не обращал).

Исправил.

2024-08-09 20:32 UTC, amilosh commented on src/main/java/faang/school/godbless/bjs2_18437/AppStringUtils.java
> +    }
Не нашел в Java core метода, который бы проверял стрингу на null и blank.
Да, есть библиотеки, у которых есть методы isBlank, isNotBlank (Apache Commons, Google Guava, Spring Framework). Но не хотел подключать либу ради одного метода.
Плюс отел поупражняться в написании утильных классов и аннотацию @UtilityClass попробовать.

Оставил как есть.

2024-08-09 20:35 UTC, amilosh commented on src/main/java/faang/school/godbless/bjs2_18437/Main.java
> +        }
Да, в идеале все задания с тестами нужно сделать, но боялся, что если буду тесты писать, на сами задания времени не хвтит.

Тесты не добавлял.

Оставил как есть.

2024-08-09 20:39 UTC, amilosh commented on src/main/java/faang/school/godbless/bjs2_18437/User.java
> +    private Integer age;
Привычка использовать Integer после работы с Entity классами. В рамка данной задачи это лишнее.

Поменял на int.

Исправил.

2024-08-09 20:47 UTC, amilosh commented on src/main/java/faang/school/godbless/bjs2_18437/User.java
> +    private void validateUserCreation(String name, Integer age, String jobPlace, String address, boolean throwMessage) {
Если у юзера 100 полей.
Нам нужно просто проверить, валидный ли он, ставим throwMessage = fallse. Тогда валидатор вернет exception при первом же невалидном параметре, что ускоряет работу.
А если нужно провалидировать юзера и прям точно узнать какие поля невалидны, ставим throwMessage = true, и валидотор пройдёт по всем полям и вернет exeption с текстом.

Я сначала написал первый способ. Потом подумал, что в реальной жизни мы выбраываем ошибку и сообщение пишем в лог, чтобы понять, что случилось.
И я решил оставить два подхода. Просто закрутил вот в такую форму с boolean throwMessage.

Не исправлял.

2024-08-09 21:43 UTC, amilosh commented on src/main/java/faang/school/godbless/bjs2_18437/UserValidator.java
> +    }
Сделал рефакторинг. Методы с одинаковой логикой вынес в отдельные методы.

Если не это имелось ввиду, то как сделать так, чтобы проверять каждое поле и возвращать уикальное сообщение с ошибкой для каждого поля. 

Исправил, но надо обсудить.

2024-08-10 02:59 UTC, pablo023 commented on src/main/java/faang/school/godbless/bjs2_18437/AppCollectionUtils.java
> +    public <E> boolean isCollectionContainsElement(Collection<E> collection, E e) {
Ну, я понял. Но просто это - неправильно по-английски было написано)

2024-08-10 02:59 UTC, pablo023 commented on src/main/java/faang/school/godbless/bjs2_18437/AppStringUtils.java
> +    }
Окей.

2024-08-10 02:59 UTC, pablo023 commented on src/main/java/faang/school/godbless/bjs2_18437/Main.java
> +        }
Понятно, окей)

2024-08-10 03:00 UTC, pablo023 commented on src/main/java/faang/school/godbless/bjs2_18437/UserValidator.java
> +    }
Я имел ввиду, что два одинаковых метода, но один сообщение кидает, а другой - не кидает, ну это конечно перевод бумаги) Незачем просто

2024-08-10 03:00 UTC, merged