BJS2-19887 Java HashMap: Игра престолов
CorporationX/god_bless pull request #8167
Opened 2024-08-05 12:49 UTC by cemeh666

2024-08-09 03:12 UTC, pablo023 requested changes

2024-08-09 03:12 UTC, pablo023 commented on src/main/java/game/of/thrones/House.java
> +    }
Было бы неплохо добавлять проверку на то, что дом с таким именем, вообще есть в мапе.

2024-08-09 03:12 UTC, pablo023 commented on src/main/java/game/of/thrones/House.java
> +            System.out.printf("Дом: %s, Герб: %s", name, house.sigil).println();
Напрямую к полям не должно быть доступа, это противоречит инкапсуляции. Через геттер доставай sigil

2024-08-09 06:48 UTC, cemeh666 commented on src/main/java/game/of/thrones/House.java
> +    }
я правильно понял про проверку?

2024-08-09 06:49 UTC, cemeh666 commented on src/main/java/game/of/thrones/House.java
> +            System.out.printf("Дом: %s, Герб: %s", name, house.sigil).println();
согласен

2024-08-10 03:14 UTC, pablo023 commented on src/main/java/game/of/thrones/House.java
> +    }
Нет, неправильно. Если его там нет - это IllegalArguentException, и в нем - сообщение, что дом с таким-то ... не был найден. Вообще, NullPointerException - это такая вещь в Java, которую никогда самому не надо кидать, и всегда стараться предугадывать, откуда может выплюнуться, и писать код так, чтобы не нарываться на неё. Это по сути - кейс, когда у тебя существует ссылка на пустоту. Короче, так никогда не должно получаться.

2024-08-10 19:42 UTC, cemeh666 commented on src/main/java/game/of/thrones/House.java
> +    }
поправил

2024-08-11 02:01 UTC, merged