Создание классов-моделей: User, Query, класса Main c логикой работы п…
CorporationX/god_bless pull request #8219
Opened 2024-08-05 17:33 UTC by ilu23ilu23

…риложения, а так же юнит тесты на методы.

2024-08-09 03:30 UTC, pablo023 requested changes

2024-08-09 03:30 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_20020/Main.java
> +        userQueries.computeIfAbsent(user, k -> new ArrayList<>()).add(query);
Почему user, k? Почему не user, queries?

2024-08-09 03:30 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_20020/Main.java
> +            if(userListEntry.getKey().equals(user)) {
А зачем так делать? Если юзер есть в мапе - мы его можем просто мгновенно оттуда достать, без итерации. Если у тебя в мапе миллион записей будет - зачем ты будешь делать миллион итераций, когда это можно мгновенно достать?

2024-08-09 03:30 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_20020/User.java
> +        return Objects.hash(getId(), getName());
Если умеешь это делать, можешь аннотациями создавать.

2024-08-09 03:30 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_20020/User.java
> +@Data
Ты не используешь весь функционал этой аннотации, она не нужна тебе.

2024-08-09 03:30 UTC, pablo023 commented on src/test/java/faang/school/godbless/BJS2_20020/MainTest.java
> +class MainTest extends Main {
Это так не делается, не надо тестовый класс наследовать от мейна.

2024-08-09 03:30 UTC, pablo023 commented on src/test/java/faang/school/godbless/BJS2_20020/MainTest.java
> +    private Query query2;
Цифры использовать в неймингах переменных нельзя в Джаве.

2024-08-09 13:49 UTC, ilu23ilu23 commented on src/main/java/faang/school/godbless/BJS2_20020/Main.java
> +        userQueries.computeIfAbsent(user, k -> new ArrayList<>()).add(query);
Привык в задачках с лямбдами называть переменную одной буквой, исправлюсь

2024-08-09 13:53 UTC, ilu23ilu23 commented on src/main/java/faang/school/godbless/BJS2_20020/Main.java
> +            if(userListEntry.getKey().equals(user)) {
Не подумал, использовал что первое в голову пришло)
Исправлюсь

2024-08-09 13:54 UTC, ilu23ilu23 commented on src/main/java/faang/school/godbless/BJS2_20020/User.java
> +        return Objects.hash(getId(), getName());
ok

2024-08-09 13:54 UTC, ilu23ilu23 commented on src/main/java/faang/school/godbless/BJS2_20020/User.java
> +@Data
ok

2024-08-09 13:57 UTC, ilu23ilu23 commented on src/test/java/faang/school/godbless/BJS2_20020/MainTest.java
> +class MainTest extends Main {
Я просто генерирую тесты через Generate... Test... в идее, это она так делает автоматически, а почему так нельзя?

2024-08-10 03:10 UTC, pablo023 commented on src/test/java/faang/school/godbless/BJS2_20020/MainTest.java
> +class MainTest extends Main {
Да, я, наверное, мог бы и поподробнее написать, что я имел ввиду. 

1) Не вытаскивай всё, что есть в либе, через *. Измени настройки идеи, чтобы никогда не тянуть лишнее из либы, а только то, что тебе нужно. Пусть там хоть 100 импортов будет - нужно только то, что реально нужно.

2) По поводу екстенда мэйна - потому что тестовые классы не наследуют тестируемые, и содержат только тестовые данные, и методы.

2024-08-10 03:11 UTC, merged