BJS2-19867 Game of thrones
CorporationX/god_bless pull request #8233
Opened 2024-08-05 19:10 UTC by amilosh

2024-08-09 03:19 UTC, pablo023 requested changes
Не реализовал 4 пункт задачи:

Реализуйте методы для следующих действий: добавление нового дома; удаление дома по его названию;поиск дома и вывод информации о гербе дома по его названию; вывод списка всех домов и их гербов.

2024-08-09 03:19 UTC, pablo023 commented on src/main/java/faang/school/godbless/bjs2_19867/Main.java
> +        var null1 = House.builder().name(null).sigil(null).build();
Не используй цифры в неймингах

2024-08-09 23:04 UTC, amilosh commented on src/main/java/faang/school/godbless/bjs2_19867/Main.java
> +        var null1 = House.builder().name(null).sigil(null).build();
Исправил.

2024-08-10 03:12 UTC, pablo023 approved these changes

2024-08-10 03:13 UTC, merged