BJS2-19332 Library of Vesteros
CorporationX/god_bless pull request #8242
Opened 2024-08-05 20:10 UTC by amilosh

2024-08-09 03:44 UTC, pablo023 requested changes
Не реализовал 5 пункт задачи:

Реализуйте методы для следующих действий: добавление новой книги и её местонахождения в библиотеке; удаление книги по её названию, автору и году издания; поиск книги и вывода информации о её местонахождении в библиотеке, используя название книги, автора и год издания; вывод списка всех книг и их местонахождения в библиотеке.

2024-08-09 03:44 UTC, pablo023 commented on src/main/java/faang/school/godbless/bjs2_19332/Book.java
> +    }
Если уверен в себе насчет этих методов - можешь генерировать их аннотациями.

2024-08-09 22:37 UTC, amilosh commented on src/main/java/faang/school/godbless/bjs2_19332/Book.java
> +    }
Если имеешь ввиду lombok @EqualsAndHashCode, то да, знаю. Тут я просто решил руками написать, попрактиковаться.

Оставил как есть.

2024-08-09 22:47 UTC, amilosh commented
5 пункт задачи в классе Main:
library.put(book1, "shelf1");
var foundBook = library.get(bookToFind);
library.remove(bookToDelete);

for (Map.Entry<Book, String> entry : library.entrySet()) {
            System.out.println(entry.getKey().toString() + " ----> " + entry.getValue());
        }

2024-08-10 03:50 UTC, pablo023 approved these changes

2024-08-10 03:50 UTC, pablo023 commented on src/main/java/faang/school/godbless/bjs2_19332/Main.java
> +    public static void put(Book book, String location) {
addBook*

2024-08-10 03:50 UTC, pablo023 commented on src/main/java/faang/school/godbless/bjs2_19332/Main.java
> +    public static void remove(String title, String author, short year) {
removeBook* ну ладно

2024-08-10 03:50 UTC, merged