Game of thrones task refactoring
CorporationX/god_bless pull request #8265
Opened 2024-08-06 07:50 UTC by sultan-inked

2024-08-07 12:40 UTC, pablo023 requested changes

2024-08-07 12:40 UTC, pablo023 commented on src/main/java/faang/school/godbless/task/game/of/thrones/HouseAndSigillManager.java
> +        stringHouseMap.remove(name);
А если нет в мапе этого дома?

2024-08-07 12:40 UTC, pablo023 commented on src/main/java/faang/school/godbless/task/game/of/thrones/HouseAndSigillManager.java
> +        return house != null ? house.sigill() : null;
Не надо возвращать нуллы. Если не нашел - кидай эксепшен с понятным сообщением, что пошло не так, где, с какими данными.

2024-08-07 12:40 UTC, pablo023 commented on src/main/java/faang/school/godbless/task/game/of/thrones/HouseAndSigillManager.java
> +    public String findSigillByHouseName(String name) {
В этом методе есть два условия, второе - вывод информации о гербе дома по его названию. Стрингу он возвращать не должен, кстати.

2024-08-07 12:40 UTC, pablo023 commented on src/main/java/faang/school/godbless/task/game/of/thrones/HouseAndSigillManager.java
> +    public List<String> getAllHouseAndSigill() {
Нет такого метода в задании. Есть вывод списка всех домов и их гербов, вывод - это вывод в консоль, а не получение листа

2024-08-09 03:24 UTC, pablo023 requested changes
Комменты дублировать не стал, исправь всё, что их касается.

2024-08-09 03:24 UTC, pablo023 commented on src/main/java/faang/school/godbless/task/game/of/thrones/HouseAndSigillManager.java
> +    private Map<String, House> nameHouseMap = new HashMap<>();
houseMap*

2024-08-09 03:24 UTC, pablo023 commented on src/main/java/faang/school/godbless/task/game/of/thrones/HouseAndSigillManager.java
> +    }
Не супер просто ты это делаешь. Лучше создать метод, который валидирует входные данные, т.к. у тебя этот код дублироваться будет, по идее. И не нужно указывать в сигнатуру метода, что оно может кинуть исключение, которое унаследовано от RuntimeException. В этом нет необходимости просто, итак понятно, что оно вылететь может вообще из любой точки программы.

2024-08-09 03:24 UTC, pablo023 commented on src/main/java/faang/school/godbless/task/game/of/thrones/HouseAndSigillManager.java
> +        if (nameHouseMap.remove(name) == null) {
Просто проверяй, что он есть там.

if (nameHouseMap.containsKey(name) {
....

2024-08-09 03:24 UTC, pablo023 commented on src/main/java/faang/school/godbless/task/game/of/thrones/HouseAndSigillManager.java
> +        }
Не надо так делать. Ты сначала тут пытаешься получить, потом смотришь - нулл или не нулл. Так не делается. Ты когда взять стакан хочешь со стола - ты рукой по пустоте не проводишь, а потом не смотришь на руку - есть там стакан или нет. Сначала смотришь, видишь его, потом берешь. Тут так же делай - проверяй сначала просто, есть ли - потом делай.

2024-08-09 07:35 UTC, sultan-inked commented
Исправил)

2024-08-10 03:12 UTC, merged