Might and magic task perform
CorporationX/god_bless pull request #8269
Opened 2024-08-06 08:27 UTC by sultan-inked

2024-08-10 03:07 UTC, pablo023 requested changes

2024-08-10 03:07 UTC, pablo023 commented on src/main/java/faang/school/godbless/task/might/and/magic/creature/Creature.java
> +@Data
Дата генерит код, который ты не используешь прямо здесь, соответсвенно - она тебе не нужна, по факту.

2024-08-10 03:07 UTC, pablo023 commented on src/main/java/faang/school/godbless/task/might/and/magic/hero/Battlefield.java
> +        return healthOfHeroA > healthOfHeroB ? heroA : heroB;
А если равны?)

2024-08-10 03:07 UTC, pablo023 commented on src/main/java/faang/school/godbless/task/might/and/magic/hero/Battlefield.java
Сделай как-то поинтереснее, с шагами) А то ты только дамаг используешь, а там же есть еще дефенс, например..

2024-08-10 10:12 UTC, sultan-inked commented on src/main/java/faang/school/godbless/task/might/and/magic/hero/Battlefield.java
> +        return healthOfHeroA > healthOfHeroB ? heroA : heroB;
Блин, точно)

2024-08-10 18:07 UTC, sultan-inked commented
Усложнил логику сражения, теперь есть метод вычисления урона у существа в зависимости от конкретного противника, и победа того или иного героя не зависит на прямую от мощи его армии, теперь в силу вступила госпожа удача в лице `Random.nextBoolean()`, которая определит какое существо сможет среагировать на вызов первой и нанести удар :crossed_swords:

2024-08-12 17:55 UTC, 20cognosce approved these changes
Супер, хорошо поработал над задачей.

2024-08-12 17:55 UTC, merged