BJS2-19345 Java HashMap: Оптимизируем работу дата-центра
CorporationX/god_bless pull request #8343
Opened 2024-08-06 21:05 UTC by Murzin34

2024-08-09 01:41 UTC, pablo023 requested changes

2024-08-09 01:41 UTC, pablo023 commented on src/main/java/faang/school/godbless/datacenter/entities/DataCenter.java
> +@AllArgsConstructor
У нас тут одно поле, зачем нам это?

2024-08-09 01:41 UTC, pablo023 commented on src/main/java/faang/school/godbless/datacenter/entities/Server.java
> +@Data
Тебе нужно всё, что Data генерирует?

2024-08-09 01:41 UTC, pablo023 commented on src/main/java/faang/school/godbless/datacenter/services/DataCenterService.java
> +        dataCenter.getServers().remove(server);
А если нет там сервера этого?

2024-08-09 01:41 UTC, pablo023 commented on src/main/java/faang/school/godbless/datacenter/services/DataCenterService.java
> +        }
А почему сразу так, а не попробовать оптимизировать текущую нагрузку на серверах, либо распределить этот реквест между несколькими серверами?

2024-08-09 01:41 UTC, pablo023 commented on src/main/java/faang/school/godbless/datacenter/services/DataCenterService.java
> +        }
Аналогично с комментом выше

2024-08-09 16:09 UTC, Murzin34 commented on src/main/java/faang/school/godbless/datacenter/entities/Server.java
> +@Data
Оставил `@Getter @Setter @EqualsAndHashCode`

2024-08-09 16:17 UTC, Murzin34 commented on src/main/java/faang/school/godbless/datacenter/services/DataCenterService.java
> +        dataCenter.getServers().remove(server);
Поправил

2024-08-15 18:23 UTC, 20cognosce approved these changes
Хорошо

2024-08-15 18:23 UTC, merged