game of thrones
CorporationX/god_bless pull request #8349
Opened 2024-08-07 05:40 UTC by natalia-dch

2024-08-11 02:03 UTC, pablo023 approved these changes

2024-08-11 02:03 UTC, pablo023 requested changes

2024-08-11 02:03 UTC, pablo023 commented on src/main/java/faang/school/godbless/gameofthrones/House.java
> +    }
Вывод информации о гербе дома по названию нужно сделать, по условию задачи)

2024-08-14 17:59 UTC, natalia-dch commented on src/main/java/faang/school/godbless/gameofthrones/House.java
> +    }
Добавила отдельный `printSigil`

2024-08-14 18:37 UTC, 20cognosce approved these changes

2024-08-14 18:37 UTC, 20cognosce commented on src/test/java/faang/school/godbless/gameofthrones/HouseTest.java
> +        System.setOut(new PrintStream(output));
Очень элегантный подход к тестированию вывода в консоль
Лайк

2024-08-14 18:37 UTC, 20cognosce commented on src/test/java/faang/school/godbless/gameofthrones/HouseTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Аналогично прошлому ПРу, не сворачивать

2024-08-14 18:38 UTC, merged