Solution register users with JUnit tests
CorporationX/god_bless pull request #8403
Opened 2024-08-07 15:38 UTC by mrkorolev

2024-08-09 00:41 UTC, pablo023 commented
BJS2-18550 - Регистрация пользователей - так должен называться твой пулл-реквест. Если ты хочешь добавить какое-то описание о том, что ты отправил - указывай это в комментарии.

2024-08-09 00:45 UTC, pablo023 requested changes

2024-08-09 00:45 UTC, pablo023 commented on src/main/java/faang/school/godbless/register_users/User.java
> +        validate(name, p -> !p.isEmpty() || !p.isBlank(), "Name cannot be empty.");
p - не лучший нейминг. Непонятный.

2024-08-09 00:45 UTC, pablo023 commented on src/main/java/faang/school/godbless/register_users/User.java
> +        validate(age, a -> a >= 18, "Age cannot be less than 18.");
18 - антипаттерн "магическое число" здесь. Выноси в константу такие числа.

2024-08-09 00:45 UTC, pablo023 commented on src/main/java/faang/school/godbless/register_users/User.java
> +        validate(name, p -> !p.isEmpty() || !p.isBlank(), "Name cannot be empty.");
Старайся по возможности избегать проверки через отрицание. Эти восклицательные знаки порой сбивают с толку.

2024-08-09 19:34 UTC, mrkorolev commented on src/main/java/faang/school/godbless/register_users/User.java
> +        validate(name, p -> !p.isEmpty() || !p.isBlank(), "Name cannot be empty.");
А как в таком случае стоит называть параметр? Если я в функцию проверки "validate" передаю и сам параметр, и лямбду которая будет его проверять? Они не могут иметь одно и то же имя, ввиду локального скоупа. Или плохая практика таким образом проверять параметры в конструкторе?

2024-08-09 19:35 UTC, mrkorolev commented on src/main/java/faang/school/godbless/register_users/User.java
> +        validate(name, p -> !p.isEmpty() || !p.isBlank(), "Name cannot be empty.");
В последнем коммите объединил через OR, чтобы использовать только одну операцию отрицания.

2024-08-10 02:50 UTC, pablo023 commented on src/main/java/faang/school/godbless/register_users/User.java
> +        validate(name, p -> !p.isEmpty() || !p.isBlank(), "Name cannot be empty.");
ну типа userName, например. Так или иначе, не критично, это просто на будущее.

2024-08-10 02:51 UTC, merged