BJS2-19737 The ELK Query Index
CorporationX/god_bless pull request #8432
Opened 2024-08-07 18:59 UTC by amilosh

2024-08-11 02:14 UTC, pablo023 requested changes

2024-08-11 02:14 UTC, pablo023 commented on src/main/java/faang/school/godbless/bjs2_19737/Main.java
> +    private static void addUserWithQueries(User user, LinkedList<Query> queries) {
Для чего ты здесь используешь связанный список?

2024-08-11 02:14 UTC, pablo023 commented on src/main/java/faang/school/godbless/bjs2_19737/Main.java
> +    private static Map<User, LinkedList<Query>> userQueries;
В классе Main, создайте HashMap с ключом типа User и значением типа List<Query> (список запросов пользователя).

List, не LinkedList.

2024-08-11 02:14 UTC, pablo023 commented on src/main/java/faang/school/godbless/bjs2_19737/Main.java
> +        userQueries.computeIfAbsent(user, q -> new LinkedList<>()).addAll(0, queries);
Это будет работать как стек. Зачем такая реализация?

2024-08-11 02:14 UTC, pablo023 commented on src/main/java/faang/school/godbless/bjs2_19737/Main.java
> +    }
Зачем реализация через линкед лист, и вставка каждой очереди в начало?

2024-08-12 18:09 UTC, amilosh commented on src/main/java/faang/school/godbless/bjs2_19737/Main.java
> +    private static void addUserWithQueries(User user, LinkedList<Query> queries) {
Логика была такая: пользователь делает запросы, я записываю их в линкед лист причём в самое начало (добавление в начало за константное время). И потом когда нам нужно вернуть список запросов, я возвращаю его как есть, без сортировки (или реверса), от самой новой к самой старой.

Готов обсудить моё видение на daily. Может я где-то просчитываюсь.

В пул-реквесте оставил два варианта.

Исправил, но надо обсудить.

2024-08-12 18:14 UTC, amilosh commented on src/main/java/faang/school/godbless/bjs2_19737/Main.java
> +    private static Map<User, LinkedList<Query>> userQueries;
Исправил.

2024-08-12 18:16 UTC, amilosh commented on src/main/java/faang/school/godbless/bjs2_19737/Main.java
> +        userQueries.computeIfAbsent(user, q -> new LinkedList<>()).addAll(0, queries);
Сам уже не помню зачем так сделал.
Поменял на просто put()

Исправил.

2024-08-12 18:17 UTC, amilosh commented on src/main/java/faang/school/godbless/bjs2_19737/Main.java
> +    }
В самом верхнем комментарии попытался объяснить.

2024-08-12 19:23 UTC, 20cognosce requested changes
Определись с одной финальной реализацией

2024-08-12 19:23 UTC, 20cognosce commented on src/main/java/faang/school/godbless/bjs2_19737/Main.java
> +        existedQueries.addFirst(query);
Тебе не гарантируется, что следующий запрос точно с бОльшим timestamp чем все текущие в списке.
Нужна явная сверка по timestamp.
Может он затерялся в очереди, и только потом до нас дошел. А на самом деле он был раньше всех.

2024-08-12 19:23 UTC, 20cognosce commented on src/main/java/faang/school/godbless/bjs2_19737/Main.java
> +    public void printAllUsersWithSortedQueries() {
По условию задачи у тебя два метода - принт всех, принт одного пользователя, используя обход массива Entry внутри HashMap

2024-08-12 19:23 UTC, 20cognosce commented on src/main/java/faang/school/godbless/bjs2_19737/Main.java
> +        var existedQueries = userQueries.get(user);
А если юзера нет?

2024-08-12 19:23 UTC, 20cognosce commented on src/main/java/faang/school/godbless/bjs2_19737/MainList.java
> +            queries.sort(Comparator.comparing(Query::getTimestamp));
Подумай как сразу хранить отсортировано, с проверкой на timestamp

2024-08-12 19:54 UTC, amilosh commented on src/main/java/faang/school/godbless/bjs2_19737/Main.java
> +    public void printAllUsersWithSortedQueries() {
Исправил.

2024-08-12 19:57 UTC, amilosh commented on src/main/java/faang/school/godbless/bjs2_19737/Main.java
> +        var existedQueries = userQueries.get(user);
Исправил.

2024-08-12 21:05 UTC, amilosh commented on src/main/java/faang/school/godbless/bjs2_19737/MainList.java
> +            queries.sort(Comparator.comparing(Query::getTimestamp));
Исправил.

2024-08-12 21:10 UTC, amilosh commented on src/main/java/faang/school/godbless/bjs2_19737/Main.java
> +            }
Искал может какое решение в существующих коллекциях есть. Но нашел либо через Tree, либо Priority, либо после каждого добавления делать sort.
Подумал, что перед тем как добавить новый элемент, наш список уже отсортирован, и достаточно просто бурбалкой один раз пройтись.

Если есть более элегантное решение, буду рад его увидеть.

2024-08-13 15:42 UTC, 20cognosce requested changes
Велосипед убери и можно мерджить

2024-08-13 15:42 UTC, 20cognosce commented on src/main/java/faang/school/godbless/bjs2_19737/Main.java
> +                }
Вот это непотребство убирай
Не изобретай велосипеды, где это не нужно
Здесь достаточно использовать встроенную в список сортировку, которая еще и эффективнее отработает чем это.

По другим вариантам - когда кладешь изначальный список, сортируешь его один раз. При добавлении нового запроса можно заюзать бинарный поиск, ты же знаешь, что все запросы которые уже есть - отсортированы. И будешь находить место новому запросу за log2(n)

Но достаточно встроенной сортировки списка

2024-08-14 08:57 UTC, amilosh commented on src/main/java/faang/school/godbless/bjs2_19737/Main.java
> +                }
Про бинарный поиск забыл. Спасибо за напоминание. Нужно будет руками хотя бы раз написать.

Исправил.

2024-08-14 14:27 UTC, 20cognosce approved these changes

2024-08-14 14:27 UTC, merged