18803
CorporationX/god_bless pull request #8436
Opened 2024-08-07 20:07 UTC by ChibixAnastasia

18803

2024-08-11 02:39 UTC, pablo023 commented
BJS2-18803 - Абстракция, абстракция! - так должен называться этот ПР.

2024-08-11 02:41 UTC, pablo023 requested changes

2024-08-11 02:41 UTC, pablo023 commented on src/main/java/faang/school/godbless/task18803/Archer.java
> +        this.intelligence = 5;
Почитай про антипаттерн "магическое число". И почему у нас на вход принимаются какие-то аргументы, а устанавливаем мы значения, которые к этим аргументам вообще отношения не имеют?

2024-08-11 02:41 UTC, pablo023 commented on src/main/java/faang/school/godbless/task18803/Archer.java
> +        this.dexterity -= 10;
Почему мы, атакуя, отнимаем у самих себя 10 единиц ловкости?

2024-08-11 02:41 UTC, pablo023 commented on src/main/java/faang/school/godbless/task18803/Warrior.java
> +        this.intelligence = 3;
В константы.

2024-08-11 02:41 UTC, pablo023 commented on src/main/java/faang/school/godbless/task18803/Warrior.java
> +        this.power -= 10;
Почему мы сами у себя отнимаем силу, атаковав?

2024-08-12 04:40 UTC, pablo023 requested changes

2024-08-12 04:40 UTC, pablo023 commented on src/main/java/faang/school/godbless/task18803/Warrior.java
> +        defending.power -= POWER;
Зачем мы ему отнимаем силу? И зачем нам в аргументах attacking, если внутри метода мы ничего им не делаем?

2024-08-12 04:40 UTC, pablo023 commented on src/main/java/faang/school/godbless/task18803/Archer.java
> +        attacking.power -= POWER;
Зачем эта строчка?

2024-08-12 04:40 UTC, pablo023 commented on src/main/java/faang/school/godbless/task18803/Archer.java
> +        defending.health -= POWER;
По условию задачи, у атакуемого персонажа лучником, отнимается здоровье в размере ловкости лучника.

2024-08-12 04:40 UTC, pablo023 commented on src/main/java/faang/school/godbless/task18803/Archer.java
> +    public void attack(Character attacking, Character defending) {
Почему мы у атакующего отнимаем силу?

2024-08-12 16:39 UTC, 20cognosce approved these changes

2024-08-12 16:40 UTC, merged