grouped students
CorporationX/god_bless pull request #8450
Opened 2024-08-08 05:58 UTC by natalia-dch

2024-08-12 05:04 UTC, pablo023 requested changes

2024-08-12 05:04 UTC, pablo023 commented on src/main/java/faang/school/godbless/uni/Uni.java
> +    Map<String, List<Student>> grouped = new HashMap<>();
модификатор доступа?

2024-08-12 05:04 UTC, pablo023 commented on src/main/java/faang/school/godbless/uni/Uni.java
> +    public boolean addStudent(String name, String faculty, int year) {
Это не булеан метод, а войд. Методы, которые что-то удаляют, либо добавляют - войды. Если у тебя что-то не получилось сделать по ходу метода, ты кидаешь исключение, а не фолс. Булеан методы - это методы, которые выполняют проверку, и дают ответ - да / нет.

2024-08-12 05:04 UTC, pablo023 commented on src/main/java/faang/school/godbless/uni/Uni.java
> +        return grouped;
Тут должен быть вывод список студентов, сгруппированный по факультетам и курсам, а не возврат мапы просто.

2024-08-14 17:44 UTC, natalia-dch commented on src/main/java/faang/school/godbless/uni/Uni.java
> +        return grouped;
Добавила отдельный `printGrouped`. Я умею писать `System.out.println` в цикле, честное слово))

2024-08-14 18:33 UTC, 20cognosce approved these changes
Аппрув

2024-08-14 18:33 UTC, 20cognosce commented on src/test/java/faang/school/godbless/uni/UniTest.java
> +import static org.junit.jupiter.api.Assertions.*;
На импорты поглядывай, всегда раскрывай их
Как уберешь автосворачивание в IntellijIDEA - можно использовать Ctrl + Alt + O

2024-08-14 18:33 UTC, merged