BJS2-19448
CorporationX/god_bless pull request #8475
Opened 2024-08-08 11:48 UTC by Alginin

2024-08-09 01:23 UTC, pablo023 approved these changes

2024-08-09 01:23 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS219448/Main.java
> +                studentMap.put(pair, new ArrayList<>());
Тут можно сразу добавить

studentMap.put(pair, new ArrayList<>().add(student));

2024-08-09 01:23 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS219448/Main.java
> +        listStudent.remove(student);
А если нет студента в списке?

2024-08-09 01:23 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS219448/Main.java
> +        List<Student> findStudent = new ArrayList<>();
Список "найди студента"?)

2024-08-09 01:23 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS219448/Main.java
> +    private static List<Student> listStudent = new ArrayList<>();
studentList*

2024-08-09 01:23 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS219448/Main.java
> +    public static Map<Pair, List<Student>> groupStudent(List<Student> students) {
groupStudents*

2024-08-09 01:23 UTC, pablo023 requested changes
Исправь замечания

2024-08-09 08:21 UTC, Alginin commented on src/main/java/faang/school/godbless/BJS219448/Main.java
> +                studentMap.put(pair, new ArrayList<>());
Не получилось сделать, компилятор ругается.

2024-08-09 08:22 UTC, Alginin commented on src/main/java/faang/school/godbless/BJS219448/Main.java
> +        listStudent.remove(student);
Добавил проверку.

2024-08-09 08:25 UTC, Alginin commented on src/main/java/faang/school/godbless/BJS219448/Main.java
> +        List<Student> findStudent = new ArrayList<>();
Изменил метод, так как при добавлении проверки (выше), смены нейминга - "все пошло не по плану" метод перестал отрабатывать.

2024-08-09 11:53 UTC, InnMish commented on src/main/java/faang/school/godbless/BJS219448/Main.java
> +                studentMap.put(pair, new ArrayList<>());
Ну потому что нельзя хе-хе 
put нам ничего не возвращает, это void метод, значит, мы не можем обратиться к результату выполнения 
Но мы же можем все это дело вообще организовать через computeIfAbsent? 
Вместе с contains

2024-08-09 11:53 UTC, InnMish commented on src/main/java/faang/school/godbless/BJS219448/Main.java
> +            studentList.remove(student);
а вот remove возвращает тебе удаленную сущность) 
Поэтому можно не проверять на contains, а сделать remove без проверок, а для ошибок проверить результат ремува - если null, то студент не в листе 

Но это мелочь, можешь не править)

2024-08-10 11:51 UTC, Alginin commented on src/main/java/faang/school/godbless/BJS219448/Main.java
> +            studentList.remove(student);
1. Выполнил с помощью computeIfAbsent
2. Принял к сведению

2024-08-12 18:20 UTC, 20cognosce approved these changes

2024-08-12 18:20 UTC, merged