Google search task perform
CorporationX/god_bless pull request #8507
Opened 2024-08-08 18:37 UTC by sultan-inked

2024-08-12 05:39 UTC, pablo023 requested changes

2024-08-12 05:39 UTC, pablo023 commented on src/main/java/faang/school/godbless/task/google/search/Google.java
> +        }
Никогда не кидай NPA. Тебе всегда нужно писать код таким образом, чтобы избегать НПА, и не кидать ее самому. И вообще нпа - это когда что-то указывает "вникуда", а не когда тебе "ничто" пришло на вход. Если пришли кривые данные на вход - это IllegalArgumentException.

2024-08-12 05:39 UTC, pablo023 commented on src/main/java/faang/school/godbless/task/google/search/Google.java
> +    private void webPageValidOrThrowNullPointerException(WebPage webPage) {
Если у тебя валидация есть - называешь ее validateWebPage, и туда можешь что-то положить. Не надо вообще кстати длинные названия метода писать, "OrThrowNullPointerException" - вот такую часть вообще не пиши никогда в названиях. Просто validateWebPage достаточно. Потом будешь создавать класс валидатор, там будут отдельные методы для валидации полей, пока что достаточно просто метода validateWebPage

2024-08-12 07:09 UTC, sultan-inked commented
Исправил

2024-08-13 20:05 UTC, 20cognosce approved these changes
Всё ок

2024-08-13 20:05 UTC, merged