weather cache
CorporationX/god_bless pull request #8525
Opened 2024-08-09 06:02 UTC by natalia-dch

2024-08-12 04:50 UTC, pablo023 requested changes

2024-08-12 04:50 UTC, pablo023 commented on src/main/java/faang/school/godbless/cash/WeatherForecast.java
> +    private final Map<String, WeatherData> forecasts = new HashMap<>();
forecastMap*

2024-08-12 04:50 UTC, pablo023 commented on src/main/java/faang/school/godbless/cash/WeatherForecast.java
> +    public void clearCache(String city) {
clearCache - это очистить кэш, т.е. всё оттуда удалить. Неудачный нейминг, лучше - removeFromCache.

2024-08-12 04:50 UTC, pablo023 commented on src/main/java/faang/school/godbless/cash/WeatherForecast.java
> +            //presuming that weather service is reliable and always returns data
Не нужно оставлять комментарии в коде. Если твой код без них непонятен - упрощай код. Если понятен без них - комментарии излишни.

2024-08-12 04:50 UTC, pablo023 commented on src/main/java/faang/school/godbless/cash/WeatherService.java
> +        int humility = rnd.nextInt(20, 60);
А что это за цифры? Их нужно вынести куда-то, в константы, например.

2024-08-12 04:50 UTC, pablo023 commented on src/main/java/faang/school/godbless/cash/WeatherService.java
> +    private static final Random rnd = new Random();
random*

2024-08-12 04:50 UTC, pablo023 commented on src/test/java/faang/school/godbless/cash/WeatherForecastTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Не тащи весь пакет, измени у себя в настройках IDE, чтобы импортилось только то, что нужно.

2024-08-12 04:50 UTC, pablo023 commented on src/test/java/faang/school/godbless/cash/WeatherForecastTest.java
Ознакомься с аннотацией DisplayName, для методов тестов.

2024-08-14 18:21 UTC, 20cognosce approved these changes
Ок, аппрув

2024-08-14 18:21 UTC, 20cognosce commented on src/main/java/faang/school/godbless/cash/WeatherService.java
> +    public static WeatherData getForecast(String city) {
static используем только для хранения глобальных констант или методов в утилитарном классе (что тем не менее все равно не очень одобряемо)
В сервисах бизнес-логики методы не должны быть static

2024-08-14 18:21 UTC, 20cognosce commented on src/main/java/faang/school/godbless/cash/WeatherService.java
> +    private static final Random random = new Random();
Аналогично, random - не константа)

2024-08-14 18:21 UTC, merged