Elk query index task perform
CorporationX/god_bless pull request #8537
Opened 2024-08-09 09:44 UTC by sultan-inked

2024-08-11 20:37 UTC, 20cognosce requested changes
Переименуй ПР - Индекс запросов ELK BJS2-19765

2024-08-11 20:37 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/elk/query/index/User.java
> +    private final int id;
id бывает Long или UUID, в таких задачках подойдет Long, инта может не хватить по размеру, ну это на будущее.

2024-08-11 20:37 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/elk/query/index/Query.java
> +    private final int id;
Аналогично User

2024-08-11 20:37 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/elk/query/index/QueryManager.java
> +        userValidOrNullPointerExceptionThrow(user);
Зачем в этой задаче проверки на null?) И если null, то ты всё равно кидаешь NPE, и в чем тогда прикол?)))
Если ты хочешь сказать пользователям своего API, что null - нельзя, используй аннотации @ NotNull @ NonNull или вроде. Если ты готов их обрабатывать - то тогда обрабатывай как-нибудь, но не просто кидая NPE.
В этой задаче можно удалить это.

2024-08-11 20:37 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/elk/query/index/QueryManager.java
> +            userNotFoundExceptionThrow(user);
Хорошо, что подумал над этим. Но делать целый метод, вся функция которого это только кидание эксепшена - это нерационально. Ты можешь прям тут кинуть NoSuchElementException.

2024-08-11 20:37 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/elk/query/index/QueryManager.java
> +        userAndQueryListMap.computeIfAbsent(user, k ->
разбей на две строчки - 1. сompute, 2. add.
Чтобы было видно, что compute отдает текущий список запросов если они есть, или новый пустой, если нет юзера / список null.

2024-08-11 20:37 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/elk/query/index/QueryManager.java
> +        if (!userAndQueryListMap.containsKey(user)) {
бессмысленные проверки, remove отработает нормально без этого

2024-08-11 20:37 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/elk/query/index/QueryManager.java
> +        List<Query> queries = userAndQueryListMap.get(user);
По условию задачи, надо пройти по массиву entries через for

2024-08-11 20:37 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/elk/query/index/QueryManager.java
> +        queries.sort(Comparator.comparing(Query::getTimeStamp));
Это ок, а можно сразу хранить запросы в отсортированном виде?)

2024-08-11 20:37 UTC, 20cognosce commented on src/test/java/faang/school/godbless/task/elk/query/index/QueryManagerTest.java
> +public class QueryManagerTest {
Здорово, что ты написал тесты, только ни в одном из них ты не сверяешь фактический вывод в консоль с ожиданием.

Сделай, чтобы все методы что-то возвращали (или по изменению состояния мапы сверку делать в некоторых методах), а не только в консоль писали, тогда их можно будет протестировать. Просто вызов метода - ничего не проверяет.

2024-08-12 05:31 UTC, sultan-inked commented on src/main/java/faang/school/godbless/task/elk/query/index/QueryManager.java
> +        userValidOrNullPointerExceptionThrow(user);
Я изначально не делал проверку на нулл в врошлых задачах, и кида ексепшны прямо в метода, написали что надо проверять на нулл, есть в списке объект перед тем как доставать и сделать отдельный метод который проверяет на нул, вот я и сделал...

2024-08-12 05:35 UTC, sultan-inked commented on src/main/java/faang/school/godbless/task/elk/query/index/QueryManager.java
> +        userValidOrNullPointerExceptionThrow(user);
И про нон нулл тоже знаю, но мне написали что надо сообщение обязательно в ексепшн добавлять, а в нон нулл не добавить, но в любом случае исправлю, спасибо

2024-08-12 06:13 UTC, sultan-inked commented
Исправил, тестовый класс удалил, в задании информацию только выводят в консоль, разбираться как тестировать вывод в консоль мне кажется сейчас не рационально, потому что лучше потратить время на новый спринт, там много задачь

2024-08-12 06:24 UTC, pablo023 commented
> Исправил, тестовый класс удалил, в задании информацию только выводят в консоль, разбираться как тестировать вывод в консоль мне кажется сейчас не рационально, потому что лучше потратить время на новый спринт, там много задач

Забей на тестирование вывода в консоль вообще)

2024-08-12 06:27 UTC, merged