Danke Villetti BJS2-19565
CorporationX/god_bless pull request #8541
Opened 2024-08-09 10:16 UTC by DankeVilletti

2024-08-14 00:09 UTC, pablo023 commented
BJS2-19565 - Java HashMap: Считаем прогулы - так должен называться этот ПР.

2024-08-14 00:12 UTC, pablo023 requested changes
В основном из-за PairKey возвращаю

2024-08-14 00:12 UTC, pablo023 commented on src/main/java/faang/school/godbless/countAbsences/PairKey.java
> +    private final S second;
Чего? Тут должна быть пара faculty, которая стринг, и year, который int

2024-08-14 00:12 UTC, pablo023 commented on src/main/java/faang/school/godbless/countAbsences/PairKey.java
> +    private final S second;
И нейминги тоже как-то вообще не имеют отношения к сути.

2024-08-14 00:12 UTC, pablo023 commented on src/main/java/faang/school/godbless/countAbsences/Faculty.java
> +@Data
Тебе не нужна дата, ты не используешь всё, что она генерирует. Озакомься: https://projectlombok.org/features/Data

2024-08-14 00:12 UTC, pablo023 commented on src/main/java/faang/school/godbless/countAbsences/Student.java
> +
А это что?

2024-08-14 00:12 UTC, pablo023 commented on src/main/java/faang/school/godbless/countAbsences/Student.java
> +@Data
Тебе не нужна дата.

2024-08-14 00:12 UTC, pablo023 commented on src/test/java/faang/school/godbless/countAbsencesTest/countAbsences.java
Ознакомься с аннотацией DisplayName

2024-08-16 09:35 UTC, mysosnovskaya requested changes
В основном стилистические замечания, но есть одно важное - не хватает методов, описанных в условии задачи.

2024-08-16 09:35 UTC, mysosnovskaya commented on src/test/java/faang/school/godbless/countAbsencesTest/countAbsencesTest.java
> +public class countAbsencesTest {
Назови класс большой буквы - в java так принято)

2024-08-16 09:35 UTC, mysosnovskaya commented on src/test/java/faang/school/godbless/countAbsencesTest/countAbsencesTest.java
> +    @BeforeEach
Перед BeforeEach нужна пустая строка, так логические блоки "поля" и "методы" будут разделены друг с другом

2024-08-16 09:35 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/countAbsences/Faculty.java
> +    private String name;
А это имя для чего-то используется? Думаю, это лишнее поле

2024-08-16 09:35 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/countAbsences/Faculty.java
> +    public static Map<PairFacultyYearKey, List<Student>> MapOfStudentsByFacultiesAndYears(List<Student> students) {
Все методы в java называются с маленьких букв, даже статические. Переименуй, пожалуйста)

2024-08-16 09:35 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/countAbsences/Faculty.java
> +}
В задаче есть такой пункт:
`Реализуйте методы для следующих действий: добавление нового студента в список; удаление студента из списка по его имени, факультету и курсу; поиск всех студентов определённого факультета и курса; вывод списка всех студентов сгруппированных по факультетам и курсам`
Не вижу методов добавления, удаления, поиска и вывода - их нужно добавить

2024-08-16 20:23 UTC, mysosnovskaya requested changes

2024-08-16 20:23 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/countAbsences/Student.java
> +
Удали пустые строчки)

2024-08-16 20:23 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/countAbsences/Student.java
> +    private Faculty faculty;
Может быть всё-таки проще здесь String faculty хранить, а класс Faculty вообще удалить?

2024-08-16 20:23 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/countAbsences/StudentManager.java
> +    private final Map<PairFacultyYearKey, List<Student>> studentMap;
Это поле не нужно. Вот как раз такую мапу должен возвращать метод getStudentsGroupedByFacultiesAndYears, но он должен вычислять её самостоятельно на основе переданного списка студентов (по заданию).

2024-08-16 20:23 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/countAbsences/StudentManager.java
> +        studentMap.computeIfAbsent(key, k -> new ArrayList<>()).add(student);
Эта мапа должна создаваться методом getStudentsGroupedByFacultiesAndYears по переданному списку студентов (по заданию). А ты её пытаешься "на лету" заполнять)

2024-08-16 20:23 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/countAbsences/StudentManager.java
> +        students.add(student);
Думаю, нужно какую-то валидацию на данные студента добавить. Например, мы потом будет использовать факультет и год и нам важно, чтобы они были заполнены.

2024-08-16 20:23 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/countAbsences/StudentManager.java
> +    public void removeStudent(String name, String facultyName, int year) {
Вот это хорошо, только нужно логику с хэш мапой удалить. Она сильно усложняет код. Вот увидишь, когда удалишь, то код станет намного легче и приятнее)

2024-08-16 20:23 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/countAbsences/StudentManager.java
> +    public Map<PairFacultyYearKey, List<Student>> getStudentsGroupedByFacultiesAndYears() {
Здесь нужно принимать список студентов. И в методе должна быть логика по созданию хэш мапы

2024-08-16 20:23 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/countAbsences/StudentManager.java
> +public class StudentManager {
Не хватает ещё одного метода:
`вывод списка всех студентов, сгруппированных по факультетам и курсам`

2024-08-19 09:43 UTC, merged