Danke Villetti BJS2-19675
CorporationX/god_bless pull request #8553
Opened 2024-08-09 14:38 UTC by DankeVilletti

2024-08-14 00:15 UTC, pablo023 requested changes

2024-08-14 00:15 UTC, pablo023 commented on src/main/java/faang/school/godbless/Amazon/Product.java
> +@Data
Тебе не нужна Data, ты не используешь всё, что она тебе генерирует. Ознакомься: https://projectlombok.org/features/Data

Если будешь использовать всё, что она генерит - используй её, если нет - используй только то, что тебе по факту нужно.

2024-08-14 00:15 UTC, pablo023 commented on src/main/java/faang/school/godbless/Amazon/Main.java
> +    public void AllCategoryWithProducts() {
методы называются только с маленькой буквы.

2024-08-14 00:15 UTC, pablo023 commented on src/main/java/faang/school/godbless/Amazon/Main.java
> +    public void putProductToMap(@NonNull String category, List<Product> products) {
Во-первых, метод должен называться в соответствии с бизнес-логикой. Во-вторых, он должен принимать HashSet с товарами и возвращать HashMap с ключом типа String (категория товара) и значением типа List<Product> (список товаров в данной категории).

2024-08-16 09:53 UTC, mysosnovskaya requested changes
Нужно внимательно разобраться с условием задачи. Я в комментариях постаралась объяснить, что именно требуется)

2024-08-16 09:53 UTC, mysosnovskaya commented on src/test/java/faang/school/godbless/init.txt
Этот пустой файл предлагаю удалить

2024-08-16 09:53 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/Amazon/Main.java
> +        Main main = new Main();
Можно остальные методы сделать static, тогда здесь не придется создавать объект класса Main

2024-08-16 09:53 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/Amazon/Main.java
> +        main.sortingProductsByCategories("Food",cat1);
По заданию:
`В классе Main, создайте HashSet с объектами класса Product`
Не вижу, где создается HashSet?

2024-08-16 09:53 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/Amazon/Main.java
> +    public void sortingProductsByCategories(@NonNull String category, List<Product> products) {
Не понимаю, зачем нужен этот метод, если есть второй. Они по смыслу идентичные, только этот наполняет мапу из поля класса, а второй - сам создает мапу и её наполняет. По требованиям к задаче именно второй метод является верным (из задания: "_Реализуйте метод для группировки товаров по категориям, который будет принимать HashSet с товарами и возвращать HashMap_"). А т.к. этот дублирует логику, то его можно удалить, как и поле uniqueProduct

2024-08-16 09:53 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/Amazon/Main.java
> +    public Map<String, Set<Product>> sortingProductsByCategoriesAndGettingTemporaryMap(@NonNull String category, List<Product> products) {
Входные параметры у этого метода должны быть другими. Цитирую задачу:
`принимать HashSet с товарами`
А возвращать нужно:
`HashMap с ключом типа String (категория товара) и значением типа List<Product>`
Т.е. в возвращаемой мапе вместо Set должен быть List

2024-08-16 09:53 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/Amazon/Main.java
> +        Map<String, Set<Product>> Products = new HashMap<>();
Переменные в java называются с маленькой буквы. С большой только классы именуются) А поля, методы, переменные - всё с маленькой

2024-08-16 09:53 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/Amazon/Main.java
> +            Products.computeIfAbsent(category, key -> new HashSet<>()).add(pr);
computeIfAbsent это хорошее решение)

2024-08-16 09:53 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/Amazon/Main.java
> +        List<Product> cat1 = new ArrayList<>();
Отдельные списки с категориями не нужны. Категория задается сразу у продукта (это есть), а затем HashSet с продуктами передается в метод, который должен вернуть Map<String, List<Product>>. Отдельно списки категорий выделять не нужно

2024-08-16 13:08 UTC, DankeVilletti commented on src/main/java/faang/school/godbless/Amazon/Main.java
> +    public void sortingProductsByCategories(@NonNull String category, List<Product> products) {
Я думаю так
Первый метод имитирует БД для долговременного хранения, второй временная выборка (список всех продуктов и категорий можно будет как раз получить из первого)

2024-08-16 20:11 UTC, mysosnovskaya requested changes

2024-08-16 20:11 UTC, mysosnovskaya commented on src/test/java/faang/school/godbless/init.txt
Пустой файл нужно удалить)

2024-08-16 20:11 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/Amazon/Main.java
> +        Set<Product> cat1 = new HashSet<>();
Нет, сеты должны быть не по категориям, а просто со всеми продуктами. По категориям разделять будем потом, в соответствующем методе)

2024-08-16 20:11 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/Amazon/Main.java
> +    public Map<String, List<Product>> sortingProductsByCategoriesAndGettingTemporaryMap(@NonNull String category, Set<Product> products) {
Вот это верно) Продублирую ещё раз, что метод sortingProductsByCategories нам в данной ситуации не нужен и его лучше удалить. Всё-таки по заданию никакого хранения мы обеспечивать не должны, а сейчас из-за него код становится "грязнее", менее понятным

2024-08-16 20:11 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/Amazon/Main.java
> +public class Main {
Поправь стиль кода, не хватает пробелов, присутствуют лишние пустые строчки

2024-08-16 20:11 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/Amazon/Main.java
> +        Main main = new Main();
Это по-прежнему актуально. Обычно когда задачи реализовываются в main, то все остальные методы тоже делают static. Так проще :)

2025-01-17 21:17 UTC, closed without merging