Double cache cache task perform
CorporationX/god_bless pull request #8554
Opened 2024-08-09 14:43 UTC by sultan-inked

2024-08-12 06:23 UTC, pablo023 requested changes

2024-08-12 06:23 UTC, pablo023 commented on src/main/java/faang/school/godbless/task/doubl/cache/cache/StudentSubjectManager.java
> +    }
Про такие проверки и нпа писал в предыдуших ревью, так не надо

2024-08-12 06:23 UTC, pablo023 commented on src/main/java/faang/school/godbless/task/doubl/cache/cache/StudentSubjectManager.java
Мы работаем в рамках задачи с двумя мапами статическими, нам не нужно, чтобы метод мог принять любую мапу, и что-то с ней сделать

2024-08-12 06:23 UTC, pablo023 commented on src/main/java/faang/school/godbless/task/doubl/cache/cache/StudentSubjectManager.java
Давай так - я на примере этой задачи тебе покажу, как надо, и дальше ты поймешь

2024-08-12 06:23 UTC, pablo023 commented on src/main/java/faang/school/godbless/task/doubl/cache/cache/StudentSubjectManager.java
private static final Map<Student, Map<Subject, Integer>> studentGrades = new HashMap<>();
    private static final Map<Subject, List<Student>> subjectsMap = new HashMap<>();

    public static void addOrUpdateStudentGrades(Student student, Map<Subject, Integer> grades) {
        if (student == null || grades == null) {
            throw new IllegalArgumentException("Neither student nor grades can be null.");
        }
        studentGrades.put(student, grades);
    }

    public static void addStudentToSubject(Subject subject, Student student) {
        if (subject == null || student == null) {
            throw new IllegalArgumentException("Neither subject nor student can be null.");
        }
        subjectsMap.computeIfAbsent(subject, k -> new ArrayList<>()).add(student);
    }

    public static void removeStudentFromSubject(Subject subject, Student student) {
        if (subject == null || student == null) {
            throw new IllegalArgumentException("Neither subject nor student can be null.");
        }
        List<Student> students = subjectsMap.getOrDefault(subject, new ArrayList<>());
        if (!students.remove(student)) {
            throw new NoSuchElementException("Student not found in subject.");
        }
    }

    public static void printAllStudentGrades() {
        if (studentGrades.isEmpty()) {
            System.out.println("No student grades available.");
            return;
        }
        studentGrades.forEach((student, grades) -> {
            System.out.println("Student: " + student);
            grades.forEach((subject, grade) ->
                    System.out.println("Subject: " + subject + ", Grade: " + grade));
        });
    }

    public static void printAllSubjectsAndStudents() {
        if (subjectsMap.isEmpty()) {
            System.out.println("No subjects with enrolled students.");
        } else {
            subjectsMap.forEach((subject, students) -> {
                System.out.println("Subject: " + subject);
                students.forEach(student ->
                        System.out.println("Student: " + student));
        }
        });
    }
}

2024-08-12 06:23 UTC, pablo023 commented on src/main/java/faang/school/godbless/task/doubl/cache/cache/StudentSubjectManager.java
Дублирую ли я тут код - да, дублирую. Можно ли это сделать и без лишних методов, и без дублирования, и элегантно - да, можно, но пока что об этом рано говорить. Можешь почитать про аннотацию Valid. Почти что каждая практика лучшая или худшая в зависимости от контекста. На мой взгляд, то что я предложил, чище и проще читать, чем твой вариант. Как ты думаешь?

2024-08-12 06:49 UTC, sultan-inked commented
Этот комит сделал до того как увидел твои сообщения, сейчас переделаю

2024-08-12 06:50 UTC, sultan-inked commented on src/main/java/faang/school/godbless/task/doubl/cache/cache/StudentSubjectManager.java
> +    }
Возможно я не так понял, сори

2024-08-12 06:52 UTC, sultan-inked commented on src/main/java/faang/school/godbless/task/doubl/cache/cache/StudentSubjectManager.java
Согласен, Spring Validation решает эти проблемы, тога в рамках этих задач можно просто @NonNull прописывать?

2024-08-12 06:56 UTC, sultan-inked commented on src/main/java/faang/school/godbless/task/doubl/cache/cache/StudentSubjectManager.java
Согласен

2024-08-12 07:09 UTC, sultan-inked commented
Справил

2024-08-13 19:28 UTC, 20cognosce approved these changes
Ок

2024-08-13 19:28 UTC, merged