Library - done
CorporationX/god_bless pull request #8573
Opened 2024-08-09 18:07 UTC by evgenywork

2024-08-12 04:58 UTC, pablo023 commented
BJS2-19342 - Java HashMap: Библиотека Вестеросса - вот так должен называться этот ПР.

2024-08-12 04:59 UTC, pablo023 requested changes
Тут опять всё подряд. Почисть, пожалуйста, так не должно быть.

2024-08-12 07:08 UTC, evgenywork commented
> Тут опять всё подряд. Почисть, пожалуйста, так не должно быть.

Надеюсь больше не будет таких косяков )) с неймингом тоже понял

2024-08-12 07:36 UTC, pablo023 requested changes

2024-08-12 07:36 UTC, pablo023 commented on src/main/java/faang/school/godbless/java/sql/library/Book.java
> +    }
Можешь использовать ломбок - AllArgsConstructor, или RequiredArgsConstructor

2024-08-12 07:36 UTC, pablo023 commented on src/main/java/faang/school/godbless/java/sql/library/Book.java
> +}
Можешь генерить это аннотациями, если уверен в себе.

2024-08-12 07:36 UTC, pablo023 commented on src/main/java/faang/school/godbless/java/sql/library/App.java
> +    public static void addBookToLibrary(Map<Book, String> libraryMap, String shelf, String title, String author, int year) {
Этот метод должен принимать только книгу, и полку, в качестве аргументов.

2024-08-12 07:36 UTC, pablo023 commented on src/main/java/faang/school/godbless/java/sql/library/App.java
> +    public static void removeBookFromLibrary(Map<Book, String> libraryMap, String title, String author, int year) {
Мапу этот метод принимать не должен.

2024-08-12 07:36 UTC, pablo023 commented on src/main/java/faang/school/godbless/java/sql/library/App.java
> +    public static void findBookInLibrary(Map<Book, String> libraryMap, String title, String author, int year) {
Этот метод не должен принимать мапу в аргументах

2024-08-12 07:36 UTC, pablo023 commented on src/main/java/faang/school/godbless/java/sql/library/App.java
> +        }
По уму, нужно просто сначала глянуть - есть ли эта книга, и если есть - удалить, если нет - можешь об этом сообщить. Иначе, это выглядит так - ты по полке проводишь рукой, и смотришь - в руке пусто, или книга? Если пусто - говоришь, что пусто, если книга - убираешь её. Но в жизни ты же так не делаешь. Смотришь - книга, и берешь её. Тут тоже так надо.

2024-08-14 17:45 UTC, evgenywork commented on src/main/java/faang/school/godbless/java/sql/library/App.java
> +    public static void addBookToLibrary(Map<Book, String> libraryMap, String shelf, String title, String author, int year) {
для наглядности вынес все в LibraryService. Там же создал приватную HashMap чтобы ее использовать в качестве хранилища и чтобы не передавать , как параметр

2024-08-14 17:45 UTC, evgenywork commented on src/main/java/faang/school/godbless/java/sql/library/App.java
> +        }
Исправил

2024-08-14 18:28 UTC, 20cognosce approved these changes
Ок

2024-08-14 18:28 UTC, merged