BJS2-20298 Java HashMap: LRU Cache
CorporationX/god_bless pull request #8599
Opened 2024-08-10 07:23 UTC by Murzin34

2024-08-14 19:57 UTC, 20cognosce requested changes
В целом нормально, но есть недоработки, давай править их.

И желательно написать юнит-тесты на все пограничные случаи для проверки, как твой код их обрабатывает.

2024-08-14 19:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/lrucashe/Data.java
> +@lombok.Data
просто Data
и lombok в import

2024-08-14 19:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/lrucashe/DataService.java
> +    private final Map<Integer, Data> dataMap = new HashMap<>(CACHE_SIZE);
Так ты задал только начальный размер мапы, но никак не установил ей лимит

2024-08-14 19:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/lrucashe/DataService.java
> +        if (dataMap.size() >= CACHE_SIZE) {
У тебя мапа физически не должна иметь возможности расшириться за лимит, некорректная проверка

2024-08-14 19:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/lrucashe/DataService.java
> +        data.setTimestamp(LocalDateTime.now());
Только на get

2024-08-14 19:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/lrucashe/DataService.java
> +                .orElseThrow(() -> new IllegalArgumentException("Invalid id"));
>если объекта нет в кэше, получите его из структуры данных, добавьте в кэш и обновите время последнего обращения.

Эксепшен не засчитывается

2024-08-14 19:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/lrucashe/DataService.java
> +        if (dataMap.size() >= CACHE_SIZE) {
Строгое равно

2024-08-14 19:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/lrucashe/DataService.java
> +                .ifPresent(dataEntry -> dataMap.remove(dataEntry.getKey()));
Не очень оптимальная тема, а можно как-нибудь сразу знать, кого удалять?

2024-08-14 20:11 UTC, Murzin34 commented on src/main/java/faang/school/godbless/lrucashe/Data.java
> +@lombok.Data
Тут вроде не получится т.к. класс над которым стоит аннотация называется Data)
![image](https://github.com/user-attachments/assets/b4fff9eb-6129-4bb4-baa8-fa0fa1fbe80f)

2024-08-14 20:20 UTC, Murzin34 commented on src/main/java/faang/school/godbless/lrucashe/DataService.java
> +    private final Map<Integer, Data> dataMap = new HashMap<>(CACHE_SIZE);
Поправил.

2024-08-14 20:30 UTC, Murzin34 commented on src/main/java/faang/school/godbless/lrucashe/DataService.java
> +        data.setTimestamp(LocalDateTime.now());
Удалил этот вызов метода.

2024-08-14 21:21 UTC, Murzin34 commented on src/main/java/faang/school/godbless/lrucashe/DataService.java
> +                .orElseThrow(() -> new IllegalArgumentException("Invalid id"));
Поправил реализацию метода.

2024-08-15 00:10 UTC, Murzin34 commented on src/main/java/faang/school/godbless/lrucashe/Data.java
> +@lombok.Data
Поменял `@Data` на `@Getter`, `@Setter`, `@ToString` и `@EqualsAndHashCode`

2024-08-15 00:13 UTC, Murzin34 commented on src/main/java/faang/school/godbless/lrucashe/DataService.java
> +                .ifPresent(dataEntry -> dataMap.remove(dataEntry.getKey()));
Добавил PriorityQueue

2024-08-17 17:41 UTC, 20cognosce approved these changes
По мне 10/10
Не будем зацикливаться на хэшмапе

2024-08-17 17:41 UTC, 20cognosce commented on src/main/java/faang/school/godbless/lrucashe/DataService.java
> +    private final Queue<Data> cacheQueue = new PriorityQueue<>(Comparator.comparing(Data::getTimestamp));
Зачем тебе dataMap? 
По-хорошему, если бы не было условия на использование хэшмапы, то одной очередью бы эта задача решалась.
А без очереди тут надо хорошо подумать, в этом и задача)

2024-08-17 17:43 UTC, 20cognosce commented
Не хорошо конечно, что ты дважды хранишь один и тот же элемент - в мапе для быстрого доступа, а в очереди для сортировки. Оверхэд по памяти, ну ок

2024-08-17 17:44 UTC, merged