Реализация индексатора
CorporationX/god_bless pull request #8620
Opened 2024-08-10 11:34 UTC by lexus-74

2024-08-10 21:24 UTC, vang31 reviewed
Не большой комментарий, по л улучшению вида кода

2024-08-10 21:24 UTC, vang31 commented on src/main/java/faang/school/godbless/BJS2_20360/Main.java
> +                });
if (!INDEXER.containsKey(word)) {
                        INDEXER.put(word, new ArrayList<>(List.of(webPage)));
                    } else {
                        if (!INDEXER.get(word).contains(webPage))
                            INDEXER.get(word).add(webPage);
                    }
                    
                    можем упростить. сначала проверка по словам, потом через и, проверка слова на веб странице.
                    тем самым нас будет 1 иф с двумя условиями. если условия не выполнятся, то без элс будем выполнять код на следующей строке.                         INDEXER.put(word, new ArrayList<>(List.of(webPage)));

2024-08-17 14:19 UTC, 20cognosce requested changes

2024-08-17 14:19 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20360/Main.java
> +import java.util.*;
Не сворачивай импорты

2024-08-17 14:19 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20360/Main.java
> +        String[] content = webPage.getContent().split(" ");
а знаки препинания - точки, запятые, кавычки там? мы их считаем частью слов получается

2024-08-17 14:19 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20360/Main.java
> +        String[] content = webPage.getContent().split(" ");
Регулярное выражение нужно regex

2024-08-17 14:19 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20360/Main.java
> +                     //   if (!INDEXER.get(word).contains(webPage))
Таких комментариев быть не должно

2024-08-17 14:19 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20360/Main.java
> +                        INDEXER.put(word, new ArrayList<>(List.of(webPage)));
Тут баг
Если было word -> {page1, page2}
и ты попал на условие !INDEXER.get(word).contains(webPage)) при добавлении page3 к этому слову

То у тебя будет word -> {page3}, а 1 и 2 ты потеряешь просто

2024-08-17 14:19 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20360/Main.java
> +            }
Один раз возьми список страниц в entry: entry.getValue
И используй метод списка removeIf

Это велосипед сейчас написан

2025-01-17 21:18 UTC, closed without merging