BJS2-19447 Java HashMap: Оптимизируем работу дата-центра
CorporationX/god_bless pull request #8654
Opened 2024-08-10 19:46 UTC by cemeh666

2024-08-12 07:20 UTC, pablo023 requested changes

2024-08-12 07:20 UTC, pablo023 commented on src/main/java/data/center/ResourceRequest.java
> +    private final long id = System.nanoTime();;
Зачем тебе это? По условию задачи этого нет)

2024-08-12 07:20 UTC, pablo023 commented on src/main/java/data/center/DataCenterService.java
Не реализовал метод по удалению сервера.

2024-08-12 07:20 UTC, pablo023 commented on src/main/java/data/center/DataCenterService.java
> +    public void allocateResources(ResourceRequest request) throws Exception {
Ты здесь можешь кинуть просто RuntimeException, и не указывать в сигнатуре метода то, что может вылететь что-то. В этом просто нет необходимости здесь.

2024-08-12 07:20 UTC, pablo023 commented on src/main/java/data/center/DataCenter.java
> +    public boolean allocateResources(ResourceRequest resourceRequest) {
Возвращаемый тип значения boolean - для методов, которые выполняют проверку, где должен быть ответа типа да / нет. Если ты хочешь, чтобы твой метод как-то сообщал о том, что операцию выполнить не удалось - пускать будет выброшено исключение, но не false.

2024-08-12 07:20 UTC, pablo023 commented on src/main/java/data/center/Server.java
> +    public boolean allocatedLoad(double load) {
allocateLoad*

2024-08-12 07:20 UTC, pablo023 commented on src/main/java/data/center/Server.java
По условию задачи, класс Server содержит только три поля:

double load
double maxLoad
double energyConsumption

Логика аллокации ресурсов, по условию задачи, должна лежать на DataCenterService

2024-08-12 07:20 UTC, pablo023 commented on src/main/java/data/center/Server.java
> +        this.load = allocatedLoad;
Ты здесь перетираешь ту нагрузку, которая уже была на сервере. Это не соответствует условию задачи, т.к. за снятие нагрузки у нас отвечает метод releaseResources

2024-08-12 07:20 UTC, pablo023 commented on src/main/java/data/center/DataCenter.java
По условию задачи, у тебя дата центр содержит список серверов. Мапа, которая соотносит запрос ресурсов с сервером, не нужна, и противоречит логике условия задачи.

2024-08-12 11:46 UTC, cemeh666 commented on src/main/java/data/center/ResourceRequest.java
> +    private final long id = System.nanoTime();;
переделал по условиям задачи

2024-08-12 11:46 UTC, cemeh666 commented on src/main/java/data/center/DataCenterService.java
добавил

2024-08-12 11:47 UTC, cemeh666 commented on src/main/java/data/center/DataCenter.java
> +    public boolean allocateResources(ResourceRequest resourceRequest) {
переделал

2024-08-12 11:47 UTC, cemeh666 commented on src/main/java/data/center/Server.java
> +    public boolean allocatedLoad(double load) {
переименовал

2024-08-12 11:47 UTC, cemeh666 commented on src/main/java/data/center/Server.java
переделал по условиям задачи

2024-08-12 11:48 UTC, cemeh666 commented on src/main/java/data/center/DataCenter.java
переделал по условиям задачи

2024-08-12 11:48 UTC, cemeh666 commented on src/main/java/data/center/Server.java
> +        this.load = allocatedLoad;
переделал

2024-08-13 15:54 UTC, 20cognosce approved these changes
Всё хорошо, кроме эксепшенов, аппрув

2024-08-13 15:54 UTC, 20cognosce commented on src/main/java/data/center/Server.java
> +        throw new RuntimeException();
Лучше создавать кастомные эксепшены и добавлять описание самой ошибки, чтобы было понятно, что стрельнуло

2024-08-13 15:54 UTC, 20cognosce commented on src/main/java/data/center/EnergyEfficencyOptimizationStrategy.java
> +                } catch (RuntimeException ignored) {}
Ну залогировал бы хотя бы

2024-08-13 15:54 UTC, 20cognosce commented on src/main/java/data/center/DataCenterService.java
> +        throw new RuntimeException("Невозможно разместить: " + request.getLoad());
Ну так уже нормально

2024-08-13 15:54 UTC, 20cognosce commented on src/main/java/data/center/DataCenterService.java
> +        throw new RuntimeException("Невозможно разместить: " + request.getLoad());
Только старайся всё писать на английском, иначе из-за проблем с кодировками собственные логи прочитать не сможешь

2024-08-13 15:54 UTC, 20cognosce commented on src/main/java/data/center/DataCenterService.java
> +            throw new RuntimeException();
Аналогично

2024-08-13 15:54 UTC, 20cognosce commented on src/main/java/data/center/DataCenterService.java
> +            throw new RuntimeException();
Аналогично

2024-08-13 15:55 UTC, merged