LRU Cache
CorporationX/god_bless pull request #8684
Opened 2024-08-11 11:57 UTC by SharkB38

Задача LRU Cache
https://faang-school.atlassian.net/browse/BJS2-20249

2024-08-17 20:10 UTC, mysosnovskaya requested changes

2024-08-17 20:10 UTC, mysosnovskaya commented on src/main/java/lru/cache/Main.java
> +            System.out.println("\nThis data is already in database");
А если хочется обновить данные? Лучше всё-таки предусмотреть такой вариант

2024-08-17 20:10 UTC, mysosnovskaya commented on src/main/java/lru/cache/Main.java
> +    private final Map<Integer, Data> cache = new LinkedHashMap<>(CACHE_SIZE) {
Отлично, что использовал LinkedHashMap. Простое, удобное и понятное решение

2024-08-17 20:10 UTC, mysosnovskaya commented on src/test/java/lru/cache/test/DataTest.java
> +                () -> assertThrows(
Ещё бы добавить случай, когда всё корректно. Для полноты картины)

2024-08-18 13:12 UTC, SharkB38 commented on src/main/java/lru/cache/Main.java
> +            System.out.println("\nThis data is already in database");
Добавил отдельный метод для обновления данных в базе

2024-08-18 18:11 UTC, mysosnovskaya approved these changes

2024-08-18 18:11 UTC, mysosnovskaya commented on src/main/java/lru/cache/Main.java
> +            System.out.println("\nThis data is already in database");
На будущее: в случае update необходимо обновить данные в кэше (или удалить старые оттуда), чтобы не получилось так, что пользователь видит неактуальное состояние. Но т.к. спринт уже закончился и это не было требованием, то просто отмечу)

2024-08-18 18:11 UTC, merged