Java HashMap: LRU Cache
CorporationX/god_bless pull request #8692
Opened 2024-08-11 13:52 UTC by Peregruzochka

2024-08-14 19:21 UTC, 20cognosce requested changes
Давай всё по новой

2024-08-14 19:21 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20228/Data.java
> +    private static int indexData = 0;
Давай больше не будем создавать это поле...

2024-08-14 19:21 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20228/Data.java
> +public class Data implements Comparable<Data> {
Укороти пожалуйста этот класс, более компактно хочется его видеть

2024-08-14 19:21 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20228/Main.java
> +    private static void addDataToStorage(Data data) {
поля -> конструкторы -> public методы -> private методы
в таком порядке в классе все должно быть расположено

2024-08-14 19:21 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20228/Main.java
> +        storage.put(data.getId(), data);
Так, а где тут вообще проверка если у нас CACHE_SIZE переполнен?

2024-08-14 19:21 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20228/Main.java
> +        addDataToStorage(four);
У тебя лимит 3, а ты добавил 4 вообще без лимита

2024-08-14 19:21 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20228/Main.java
> +    private static Data requestData(int id) {
getData
request - сетевой вызов

2024-08-14 19:21 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20228/Main.java
> +        storage.put(data.getId(), data);
Пункт 3) Если кэш превышает CACHE_SIZE, удалите самый старый объект (с наименьшим временем последнего обращения) перед **_добавлением_** нового объекта.

2024-08-14 19:21 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20228/Main.java
> +                idIndexesByTimestamp.put(dataFromStorage, dataFromStorage.getId());
Вот такие простыни никогда не пиши, на это смотреть страшно... как понять, что тут происходит...
Декомпозируй на маленькие private подметоды с понятными названиями

2024-08-14 19:21 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20228/Main.java
> +    private static SortedMap<Data, Integer> idIndexesByTimestamp = new TreeMap<>();
1 мапа
Используй только одну мапу
LinkedHashMap идеально подойдет для этой задачи
Sorted тоже подойдет, но только что-то одно

2024-08-15 09:21 UTC, Peregruzochka commented on src/main/java/faang/school/godbless/BJS2_20228/Main.java
> +        storage.put(data.getId(), data);
4. Реализуйте методы для следующих действий. 1) Добавления нового объекта Data в **структуру данных**. 2) Получения объекта Data по его ID: если объект есть в **кэше**, верните его и обновите время последнего обращения; если объекта нет в **кэше**, получите его из **структуры данных**, добавьте в **кэш** и обновите время последнего обращения. 3) Если **кэш** превышает CACHE_SIZE, удалите самый старый объект (с наименьшим временем последнего обращения) перед добавлением нового объекта.

я видимо неправильно понял условие задачи, и создал **структуру данных** в которой я храню абсолютно все объекты Data: `private static Map<Integer, Data> storage = new HashMap<>();`
и отдельно **кэш** в котором размер которого не превышает CACHE_SIZE:
`private static Map<Integer, Data> cache = new HashMap<>();`

2024-08-17 16:40 UTC, 20cognosce approved these changes
Ну а так вообще красота
Я бы нобелевку за это дал

2024-08-17 16:40 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20228/Main.java
> +    private static final boolean CACHE_ACCESS_ORDER = true;
accessOrder это ты интересно придумал

2024-08-17 16:40 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20228/Main.java
> +        protected boolean removeEldestEntry(Map.Entry<Long, Data> eldest) {
Тоже красивый подход, сам додумался?

2024-08-17 16:40 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20228/Main.java
> +        protected boolean removeEldestEntry(Map.Entry<Long, Data> eldest) {
Ну все-таки, если ты хорошо покопался в реализации, этот метод вызывается в afterNodeInsertion, то есть мы вставляем элемент сверх лимита, затем вызывается метод afterNodeInsertion, и мы попадаем сюда, где узнаем, что наиболее старый по обращению элемент надо убрать. Ты превышаешь лимит)

2024-08-17 16:41 UTC, merged