Java HashMap: Индекс запросов ELK BJS2-19741
CorporationX/god_bless pull request #8693
Opened 2024-08-11 13:58 UTC by evgenywork

2024-08-11 19:59 UTC, 20cognosce requested changes
Переименуй PR просто на: Индекс запросов ELK BJS2-19741

Жду правок и юнит-тесты.

2024-08-11 19:59 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/elk/User.java
> +    public boolean equals(Object o) {
toString, equals, hashcode сгенерированы IntelijIDEA? Ок, но можно короче, используя Lombok

2024-08-11 19:59 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/elk/User.java
> +    private int id;
Если не предусмотрено обновления полей - они final.

id бывает Long или UUID, в таких задачках подойдет Long, инта может не хватить по размеру, ну это на будущее.

2024-08-11 19:59 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/elk/Query.java
> +    private int id;
Аналогично по final и типу id

2024-08-11 19:59 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/elk/App.java
> +        Map<User, List<Query>> userQueriesMap = new HashMap<>();
Это должно быть поле класса, а не переменная внутри метода

2024-08-11 19:59 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/elk/App.java
> +        addNewUserWithQueries(userQueriesMap, userVasia, vasiaQueries);
Внутрь метода передавать саму мапу как параметр - плохо (у тебя же не будет других мап?). Поэтому надо убрать в поле.

2024-08-11 19:59 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/elk/App.java
> +    public static void main(String[] args) {
Тестирование подразумевает написание Unit-тестов))
То что внутри метода main разнеси по нескольким юнит-тестам и проверь, что результат их работы соответствует ожиданиям. 
Проверка глазами по тому, что пишет в консоль - это такое себе, на коленочное тестирование))

2024-08-11 19:59 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/elk/App.java
> +        userQueriesMap.computeIfAbsent(user, k -> new ArrayList<>()).add(query);
Не понял, как работает computeIfAbsent? Наверно, если по ключу нет значения, то вычисляет ему значение. Но тут, если у нас по ключу - юзеру, уже есть список запросов? Он типо стирается?)))) И делается новый список с одним новым запросом. Кажется это бажина, нужны тесты.

2024-08-11 19:59 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/elk/App.java
> +    public static void showUsersQueries(Map<User, List<Query>> userQueriesMap) {
Метод вывода всех пользователей не требует for по всем entries. Перепиши, итерируясь более естественно по entries хэшмапы, не через for.

2024-08-11 19:59 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/elk/App.java
> +        for (Query query: userQueriesMap.get(user)) {
Два раза get одного и того же юзера, попробуй один раз.
Можно хранить сразу отсортированно, а можно достать, отсортировать, сохранить и отдать. Или еще как-нибудь придумать.

Плюс: в этом методе нужен обход массива entries через for.

2024-08-11 20:13 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/elk/App.java
> +        userQueriesMap.computeIfAbsent(user, k -> new ArrayList<>()).add(query);
Загляни в доку этого метода через нажатие Ctrl + B в идее:

The default implementation is equivalent to the following steps for this map, then returning the current value or null if now absent:
if (map.get(key) == null) {     V newValue = mappingFunction.apply(key);     if (newValue != null)         map.put(key, newValue); }

2024-08-11 20:25 UTC, 20cognosce requested changes

2024-08-11 20:25 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/elk/App.java
> +        userQueriesMap.computeIfAbsent(user, k -> new ArrayList<>()).add(query);
И что будет, если передать в этот метод юзера, которого нет в мапе?

2024-08-12 19:32 UTC, evgenywork commented on src/main/java/faang/school/godbless/java/sql/elk/User.java
> +    private int id;
Согласен

2024-08-12 19:33 UTC, evgenywork commented on src/main/java/faang/school/godbless/java/sql/elk/App.java
> +        Map<User, List<Query>> userQueriesMap = new HashMap<>();
Я шел по заданию и там было так написано 
`В классе Main, создайте HashMap с ключом типа User и значением типа List<Query> (список запросов пользователя).`

2024-08-13 18:23 UTC, evgenywork commented
> Переименуй PR просто на: Индекс запросов ELK BJS2-19741
> 
> Жду правок и юнит-тесты.

Все правки сделал. Если я правильно понял , то HashMap и методы я из main вынес в отдельный сервис? так же написал unit тесты .

2024-08-13 19:11 UTC, 20cognosce requested changes
Давай в последним раз ПР почистим

2024-08-13 19:11 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/elk/App.java
> +//            System.out.println();
Ой ой ой...
Вот такого артефакта в коде быть не должно

2024-08-13 19:11 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/elk/ElkService.java
> +        for (Map.Entry<User, List<Query>> entry: this.userQueriesMap.entrySet()) {
Я просил тут не через for
Ладно

2024-08-13 19:11 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/elk/ElkService.java
> +        List<Query> queries = userQueriesMap.get(user);
А тут через for надо было

2024-08-13 19:11 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/elk/ElkService.java
> +    private final Map<User, List<Query>> userQueriesMap = new HashMap<>();
Я попросил сделать полем, потому что в хорошей практике static - только константы, которые глобальны для приложения

Либо методы в утилитарных классах, но это не очень хорошая практика

2024-08-13 19:11 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/elk/ElkService.java
> +    private final Map<User, List<Query>> userQueriesMap = new HashMap<>();
Но на этих задачках пофиг, я просто твой ПР одним из первых проверял, поэтому зацепился взгляд на это, непривычно

2024-08-13 20:06 UTC, evgenywork commented on src/main/java/faang/school/godbless/java/sql/elk/App.java
> +//            System.out.println();
извини , совсем забыл удалить

2024-08-13 20:07 UTC, evgenywork commented on src/main/java/faang/school/godbless/java/sql/elk/ElkService.java
> +        for (Map.Entry<User, List<Query>> entry: this.userQueriesMap.entrySet()) {
> Я просил тут не через for Ладно

Я прочитал , но не мог понять , через что именно сделать. forEach?

2024-08-13 20:08 UTC, evgenywork commented on src/main/java/faang/school/godbless/java/sql/elk/ElkService.java
> +        List<Query> queries = userQueriesMap.get(user);
Я так понимаю , что тут как раз правильно for?

2024-08-13 20:09 UTC, evgenywork commented on src/main/java/faang/school/godbless/java/sql/elk/ElkService.java
> +    private final Map<User, List<Query>> userQueriesMap = new HashMap<>();
> Но на этих задачках пофиг, я просто твой ПР одним из первых проверял, поэтому зацепился взгляд на это, непривычно

У меня такой вопрос по тестам и по сервису ElkService все ок? Спасибо!

2024-08-13 20:10 UTC, 20cognosce approved these changes

2024-08-13 20:10 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/elk/ElkService.java
> +        List<Query> queries = userQueriesMap.get(user);
Тут ты get делаешь, а по условию нужно было сделать for по entrySet
Ладно забей, аппрув

2024-08-13 20:10 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/elk/ElkService.java
> +        List<Query> queries = userQueriesMap.get(user);
Главное закомментированный код убрал и в выше методе for / forEach ты различаешь

2024-08-13 20:10 UTC, merged