Java HashMap: LRU Cache - BJS2-20181
CorporationX/god_bless pull request #8729
Opened 2024-08-11 20:02 UTC by evgenywork

2024-08-14 19:10 UTC, 20cognosce requested changes
Ну, все-таки не доделано

2024-08-14 19:10 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/lru/App.java
> +            }
Вот здесь фактически ты ищешь самый старый объект
1. Вынеси это в отдельный приватный метод
2. Поработай над алгоритмом, сейчас он выглядит криво. Особенно if
Можно выделить две переменные - текущая дата, и кандидат на самую старую, и их два элемента сравнивать. Это было бы понятнее...

Можно использовать LinkedHashMap и сразу хранить entries в отсортированном виде

2024-08-14 19:10 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/lru/App.java
> +public class App {
Не вижу метода на получение Data по id с установкой ей текущего времени

2024-08-16 15:18 UTC, evgenywork commented on src/main/java/faang/school/godbless/java/sql/lru/App.java
> +        dataList.sort(Comparator.comparing(Data::getTimestamp));
Хотел распечатать отсортированные по дате запросы

2024-08-16 15:21 UTC, evgenywork commented on src/main/java/faang/school/godbless/java/sql/lru/App.java
> +public class App {
Добавил

2024-08-16 15:21 UTC, evgenywork commented on src/main/java/faang/school/godbless/java/sql/lru/App.java
> +            }
Вынес все методы в тесты , так же поменял таблицу на linkedhashmap. написал тесты , нашел , как тестировать sout (линк добавил в тест). Ты тогда на дейлике сказал , что есть такая возможность.

2024-08-16 18:19 UTC, 20cognosce approved these changes
Всё, апррув короче, давай другие задачи

2024-08-16 18:19 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/lru/Constants.java
> +    public final static int SLEEP_TIME = 1;
public static final

2024-08-16 18:19 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/lru/LruService.java
> +        this.cachedData = sortedData;
Можно же сразу присвоить ссылку на новую, зачем clear?
Сборщик мусора итак удалит старую мапу.

2024-08-16 18:19 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/lru/LruService.java
> +                        LinkedHashMap::new
Ну вот это можно и в одну строчку, тут ты задаешь просто правила создания новой мапы, логических вызовов вроде нет

2024-08-16 18:19 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/lru/LruService.java
> +        this.cachedData.put(data.getId(), data);
Ты сначала переполняешь лимит
А потом пытаешься кэш очистить, чтобы вернуться в лимит
Как сам думаешь, это ок?)

2024-08-16 18:19 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/lru/LruService.java
> +        }
И поэтому всего этого быть не должно, если у тебя лимит 4
То максимум 4 элемента может храниться

Если надо добавить - один удаляешь, становится 3, добавляешь
И ты сразу берешь самый последний в LinkedHashMap, 4-ый, потому что ты уже отсортировал, просто по индексу

И его убираешь для высвобождения места

2024-08-16 18:19 UTC, 20cognosce commented on src/main/java/faang/school/godbless/java/sql/lru/LruService.java
> +        this.cleanOldEntriesFromCache();
А зачем лишние вызовы сортировок, чтоб наверняка?
И ты удаляешь элемент из кэша просто так, ничего нового добавлять же не собирались еще

2024-08-16 18:19 UTC, 20cognosce commented on src/test/java/faang/school/godbless/java/sql/lru/LruServiceTest.java
> +public class LruServiceTest {
Тесты норм

2025-01-17 21:18 UTC, closed without merging