Моя реализация задачи LRU Cache
CorporationX/god_bless pull request #8740
Opened 2024-08-12 06:33 UTC by wmwmaks

2024-08-17 20:23 UTC, mysosnovskaya requested changes
В реализации присутствует путаница между базой данных и кэшем. База данных - это мапа с хранением всех данных, данные из нее не удаляются, а хранятся навсегда (ну или пока сам пользователь не захочет удалить). А вот кэш - это временное хранение. Причем хранятся только несколько записей (в твоем случае 3), которые пользователь просматривал последними. А у тебя в реализации как-то всё немного наоборот) Поправь, пожалуйста

2024-08-17 20:23 UTC, mysosnovskaya commented on src/main/java/lru/cache/Main.java
> +            if (dataBase.size() > CACHE_SIZE) {
Тут какая-то путаница. Зачем удалять объект из базы данных, если превыше размер кэша? За кэш другая мапа отвечает

2024-08-17 20:23 UTC, mysosnovskaya commented on src/main/java/lru/cache/Main.java
> +            System.out.println("Данные полученны из базы и добавлены в кэш.");
Если данные уже были в кэше (о чем говорит `cache.containsKey(id)`), то здесь некорректно писать, что они получены из базы данных и добавлены в кэш. Они получены из кэша

2024-08-17 20:23 UTC, mysosnovskaya commented on src/main/java/lru/cache/Main.java
> +        return RANDOM.nextInt(MAX_RANDOM_ID_FOR_DATA) + 1;
А почему id случайным образом назначается? А если двум разным объектам один и тот же id попадется, то мы один из них потеряем? Лучше назначать по порядку: 1, 2, 3...

2024-08-18 18:15 UTC, mysosnovskaya requested changes

2024-08-18 18:15 UTC, mysosnovskaya commented on src/main/java/lru/cache/Main.java
> +    public static void main(String[] args) {
В main лучше сделать проверку своего кода по типу тестов. Предлагаю сделать так: создай 4 объекта Data и затем сделай get для них в следующем порядке: 1, 2, 3, 1, 4 - в кэше должны быть объекты 3, 1, 4. Если у тебя будет не так, то значит где-то в коде закралась ошибка)

2024-08-18 20:03 UTC, mysosnovskaya requested changes

2024-08-18 20:03 UTC, mysosnovskaya commented on src/main/java/lru/cache/Main.java
> +    public static void getData(int id) {
Метод get подразумевает, что он должен что-то возвращать, т.е. быть НЕ void. Лучше так и сделать

2024-08-18 20:03 UTC, mysosnovskaya commented on src/main/java/lru/cache/Main.java
> +            cache.put(id, cache.remove(id));
Можно реализовать за меньшее число обращений к кэшу. Кэш хоть и предназначен для быстрого доступа к данным, но всё равно не нужно обращаться к нему лишний раз. Т.е. ты можешь сделать так:
```
... data = cache.remove(id);
data.set...;
cache.put(...);
...println(data);
```
Всего два обращений вместо четырех :)

2024-08-19 06:08 UTC, wmwmaks commented on src/main/java/lru/cache/Main.java
> +            cache.put(id, cache.remove(id));
О таких вещах я пока не задумывался. Так, правда, выглядит лучше)

2024-08-19 16:26 UTC, mysosnovskaya approved these changes

2024-08-19 16:26 UTC, merged