Vii bjs2 19541
CorporationX/god_bless pull request #8741
Opened 2024-08-12 06:41 UTC by wmwmaks

2024-08-16 10:28 UTC, mysosnovskaya requested changes
Нужно разобраться с зависимостями классов :) В комментариях постаралась расписать подробно, но здесь напишу коротко ещё раз:
DataCenter - класс, который хранит список серверов и умеет с этим списком работать. Больше он ни про кого не знает.
DataCenterService  - класс, умеющий управлять датацентрами, а также имеет возможность оптимизировать нагрузку, используя заданную стратегию OptimizationStrategy (как поле класса).
OptimizationStrategy - интерфейс, который может иметь несколько разных стратегий оптимизации. В качестве доп задания можно их реализовать.
Все остальные мои комментарии в ПРе по сути являются следствием этого основного, про зависимость классов)

2024-08-16 10:28 UTC, mysosnovskaya commented on src/main/java/data/centre/ResourceRequest.java
> +    public ResourceRequest(double load) {
AllArgsConstructor не подойдет?)

2024-08-16 10:28 UTC, mysosnovskaya commented on src/main/java/data/centre/Server.java
> +    public Server(double load, double energyConsumption, double maxLoad) {
Аннотации AllArgsConstructor и ToString не подойдут?)

2024-08-16 10:28 UTC, mysosnovskaya commented on src/main/java/data/centre/DataCenter.java
> +    protected DataCenterService dataCenterService;
Не очень понимаю с полями. DataCenter не должен зависеть от DataCenterService. Наоборот, сервис может управлять датацентрами. Т.е. датацентр просто хранит в себе список (если хочешь, пусть будет хэш-мапа) серверов и умеет с этим списком работать: добавлять в него сервера, удалять, отдавать какую-то информацию. На этом функциональность класса DataCenter заканчивается. Про DataCenterService напишу в другом комментарии)

2024-08-16 10:28 UTC, mysosnovskaya commented on src/main/java/data/centre/DataCenterService.java
> +public class DataCenterService implements OptimizationStrategy {
Сейчас получается циклическая зависимость: DataCenterService зависит от DataCenter, а DataCenter зависит от DataCenterService. От второй нужно избавиться (писала в комментарии к DataCenter). Могу предложить ещё такой вариант: в DataCenterService  не хранить поле dataCenter, а в каждом методе принимать dataCenter, с которым нужно совершить некоторую операцию. Т.е. DataCenterService отвечает за управление датацентрами, вызывая их соответствующие методы. Можешь оставить и dataCenter как поле, но тогда сервис будет управлять только одним датацентром - негибко :)

2024-08-16 10:28 UTC, mysosnovskaya commented on src/main/java/data/centre/DataCenterService.java
> +        int finalId = RANDOM.nextInt(MAX_SERVER_COUNT) + 1;
А почему рандом? Можно же просто по порядку генерировать? Тогда гарантированно коллизий (совпадений) не будет и цикл while не понадобится

2024-08-16 10:28 UTC, mysosnovskaya commented on src/main/java/data/centre/DataCenterService.java
> +        dataCenter.serverIdMap.put(finalId, server);
Тут было бы хорошо вызывать метод addServer у dataCenter

2024-08-16 10:28 UTC, mysosnovskaya commented on src/main/java/data/centre/DataCenterService.java
> +        if (dataCenter.serverIdMap.containsKey(id)) {
Поле serverIdMap лучше сделать приватным, а всё взаимодействие с ним должно происходить только через методы класса DataCenter

2024-08-16 10:28 UTC, mysosnovskaya commented on src/main/java/data/centre/DataCenterService.java
> +        for (Server server : dataCenter.serverIdMap.values()) {
Логичнее реализовать метод getTotalServerEnergyConsumption у класса DataCenter так, чтобы он считал общее потребление энергии серверами, находящимися в этом дата центре. Потому что только DataCenter знает про свои сервера. А DataCenterService знает только про датацентры и умеет вызывать их методы.

2024-08-16 10:28 UTC, mysosnovskaya commented on src/main/java/data/centre/DataCenterService.java
> +    public void addService(Server server) {
Метод, наверное, должен называться addServer?

2024-08-16 10:28 UTC, mysosnovskaya commented on src/main/java/data/centre/DataCenterService.java
> +public class DataCenterService implements OptimizationStrategy {
Сам DataCenterService  не является OptimizationStrategy. У него просто должно быть такое поле - OptimizationStrategy - по которому он будет определять, как оптимизировать. Т.е. в классе DataCenterService  должен быть метод, отвечающий за оптимизацию. И он должен использовать стратегию оптимизации (т.е. у поля optimizationStrategy вызывать метод optimize). В качестве доп задания можно сделать реализации интерфейса OptimizationStrategy (по сути одна реализация уже написана в текущей версии метода optimize).

2024-08-18 20:15 UTC, mysosnovskaya requested changes
Вот теперь отличная структура классов 👍 Остались совсем небольшие замечания. В целом код написан очень понятно, даже не смотря на свою кажущуюся сложность. Молодец!

2024-08-18 20:15 UTC, mysosnovskaya commented on src/main/java/data/centre/SimpleOptimizationStrategy.java
> +public class SimpleOptimizationStrategy implements OptimizationStrategy {
В названии класса нужно отразить суть. Основная идея этой стратегии в том, что останавливаются неиспользуемые сервера. Вот об этой логике и нужно сказать в названии

2024-08-18 20:15 UTC, mysosnovskaya commented on src/main/java/data/centre/SimpleOptimizationStrategy.java
> +            for (Integer serverId : deleteServerIdSet) {
А почему бы здесь не использовать обычный for, раз нам нужен индекс?

2024-08-18 20:15 UTC, mysosnovskaya commented on src/main/java/data/centre/Server.java
> +    public Server(double load, double energyConsumption, double maxLoad) {
Это по-прежнему актуальный вопрос) Если эти аннотации подходят, то лучше использовать их. Если нет, то напиши почему в ответном комментарии)

2024-08-18 20:15 UTC, mysosnovskaya commented on src/main/java/data/centre/DataCenterService.java
> +                if (newLoadServer != server.getLoad()) {
А в каком случае они могут быть равны? По логике allocatedCapacity всегда > 0, а значит newLoadServer  всегда будет больше server.getLoad()

2024-08-19 06:33 UTC, wmwmaks commented on src/main/java/data/centre/DataCenterService.java
> +                if (newLoadServer != server.getLoad()) {
@AllArgsConstructor дописал, а стандартный вывод toString мне кажется не очень красивым. Поэтому мне приятнее его поправить самому. Хотя бы добавить пробелы до и после "=", а по умолчанию там все слеплено.

2024-08-19 06:51 UTC, wmwmaks commented on src/main/java/data/centre/DataCenterService.java
> +                if (newLoadServer != server.getLoad()) {
allocatedCapacity получаем из server.getMaxLoad() - server.getLoad(), а там может быть 0, если сервер нагружен на максимум. Но тогда мы не войдем в if и работать с этим сервером не будем. Тогда проверка if (newLoadServer != server.getLoad()) лишняя. Видимо, запутался в этом моменте немного.

2024-08-19 16:25 UTC, mysosnovskaya approved these changes

2024-08-19 16:26 UTC, merged