BJS2-21236 Lord of the Rings RPG
CorporationX/god_bless pull request #8834
Opened 2024-08-12 17:14 UTC by Murzin34

2024-08-16 19:28 UTC, 20cognosce requested changes
updateItem надо переделать

2024-08-16 19:28 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/lotrrpg/InventoryManager.java
> +        character.getInventory().replaceAll(item -> itemFilter.test(item) ? updateFunction.apply(item) : item);
чоооооо
то есть ты переобновляешь все элементы инвентаря
даже те, кто не подойдут, ты им снова переприсвоишь их собственные ссылки

Переписывай на Stream.filter()

2024-08-16 19:28 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/lotrrpg/Main.java
> +
Пустые строки лишние

2024-08-16 19:28 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/lotrrpg/Main.java
> +                new Item(item.getName(), item.getValue() * 2));
Когда много параметров, что даже в одну строчку не влезают, по нескольким строчкам их распредели

2024-08-16 20:48 UTC, Murzin34 commented on src/main/java/faang/school/godbless/modul2/lotrrpg/InventoryManager.java
> +        character.getInventory().replaceAll(item -> itemFilter.test(item) ? updateFunction.apply(item) : item);
Поправил реализацию.

2024-08-16 20:48 UTC, Murzin34 commented on src/main/java/faang/school/godbless/modul2/lotrrpg/Main.java
> +
Убрал.

2024-08-16 20:52 UTC, Murzin34 commented on src/main/java/faang/school/godbless/modul2/lotrrpg/Main.java
> +                new Item(item.getName(), item.getValue() * 2));
Тут не совсем понял. Данный вызов метода взят из задания. Все, что я сделал, это сделал перенос.

2024-08-17 14:34 UTC, 20cognosce requested changes
Баг в updateItem

2024-08-17 14:34 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/lotrrpg/InventoryManager.java
> +                .collect(Collectors.toList());
Это хорошо, но ты упустил момент, что в строчке
`character.setInventory(updatedItems);`
ты в инвентарь положил все обновленные предметы
а те, что не попали под предикат? Ты их выкинул

2024-08-17 14:34 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/lotrrpg/Main.java
> +                new Item(item.getName(), item.getValue() * 2));
Я хотел это увидеть скорее как
![image](https://github.com/user-attachments/assets/0507225e-73c0-447f-ac26-a87b40d77e5b)

2024-08-17 14:34 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/lotrrpg/Main.java
> +                new Item(item.getName(), item.getValue() * 2));
Чтобы каждый параметр был с новой строки

2024-08-17 16:19 UTC, 20cognosce requested changes

2024-08-17 16:19 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/lotrrpg/InventoryManager.java
> +        character.getInventory().retainAll(updatedItems);
Retains only the elements in this list that are contained in the specified collection. In other words, removes from this list all of its elements that are not contained in the specified collection.

То есть ты из инвентаря всё удалил. Давай еще раз)))))
Напиши тесты хоть, прежде чем отправлять на ревью))))

2024-08-17 16:19 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/lotrrpg/Main.java
> +        manager.showInventory(frodo);
Этот "тест" у тебя сработал только потому, что у тебя в инвентаре лишь один элемент

2024-08-17 18:12 UTC, 20cognosce approved these changes

2024-08-17 18:12 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/lotrrpg/InventoryManager.java
> +                .forEach(i -> inventory.set(i, updateFunction.apply(inventory.get(i))));
Вот мой вариант решения:
https://code.yandex-team.ru/9cee967c-7091-48df-8620-c7e5accb6a19

2024-08-17 18:14 UTC, merged