BJS2-21238 Lord of the Rings RPG
CorporationX/god_bless pull request #8869
Opened 2024-08-12 23:21 UTC by amilosh

2024-08-16 20:04 UTC, 20cognosce requested changes

2024-08-16 20:04 UTC, 20cognosce commented on src/main/java/faang/school/godbless/bjs2_21238/InventoryManager.java
> +            inventory.set(i, function.apply(item));
Внутри map не просто выполни function.apply, а и еще удали из инвентаря этот элемент, который прошел filter
Затем после map сделаешь collect, и тогда просто собранный список прибавишь к инвентарю.

2024-08-17 16:44 UTC, amilosh commented on src/main/java/faang/school/godbless/bjs2_21238/InventoryManager.java
> +        var inventory = character.getInventory();
Это рекомендация, чтобы пулл реквесты было удобно проверять?

Просто IDEA подсвечивает тип и я всегда клепал var не задумываясь.

Исправил.

2024-08-19 09:14 UTC, 20cognosce approved these changes

2024-08-19 09:14 UTC, 20cognosce commented on src/main/java/faang/school/godbless/bjs2_21238/InventoryManager.java
> +        inventory.addAll(updatedNewItems);
Зачем подсмотрел моё решение)

2024-08-19 09:14 UTC, 20cognosce commented on src/main/java/faang/school/godbless/bjs2_21238/InventoryManager.java
> +                        : item)
можно в одну строку, это простая конструкция

2024-08-19 09:15 UTC, merged