Решение задачи Meta-вселенная?
CorporationX/god_bless pull request #8888
Opened 2024-08-13 08:53 UTC by wmwmaks

2024-08-14 17:25 UTC, InnMish commented on src/main/java/meta/universe/Notification.java
> +    String type;
а почему модификатор дефолтный берешь?

2024-08-14 17:25 UTC, InnMish commented on src/main/java/meta/universe/Notification.java
> +    public Notification(String type, String message) {
я бы конструктор ломбоком собрала

2024-08-14 17:34 UTC, wmwmaks commented on src/main/java/meta/universe/Notification.java
> +    String type;
Я случайно

2024-08-14 17:35 UTC, wmwmaks commented on src/main/java/meta/universe/Notification.java
> +    public Notification(String type, String message) {
Я почему-то в начале решения подумал, что мне нужно будет что-то в конструкторе менять, а потом понял, что нет. И в итоге остался обычный. Ломбок класс

2024-08-16 11:13 UTC, mysosnovskaya requested changes
Хорошая работа! Одно небольшое исправление и поставлю аппрув)

2024-08-16 11:13 UTC, mysosnovskaya commented on src/main/java/meta/universe/NotificationManager.java
> +            System.err.println("Уведомления типа " + notification.getType() + " не поддерживаются");
Думаю, лучше через исключение сделать. В будущем всегда будем исключениями пользоваться, нужно привыкать)

2024-08-18 18:31 UTC, mysosnovskaya approved these changes

2024-08-18 18:31 UTC, merged