Фильтруем спам
CorporationX/god_bless pull request #8910
Opened 2024-08-13 10:41 UTC by SharkB38

Задач Фильтруем спам
https://faang-school.atlassian.net/browse/BJS2-22102

2024-08-16 18:14 UTC, mysosnovskaya requested changes

2024-08-16 18:14 UTC, mysosnovskaya commented on src/main/java/spam/MessageFilter.java
> +public interface MessageFilter <T> {
Пробел лишний перед треугольной скобкой. Для автоформатирования кода используй ctrl + alt + L (или code -> reformat code)

2024-08-16 18:14 UTC, mysosnovskaya commented on src/main/java/spam/MessageProcessor.java
> +            result = result && filter.filter(message);
Метод filter вернет false, если сообщение не подходит, т.е. должно быть отфильтровано, и true, если с сообщением всё ок. (сейчас такая логика заложена в фильтры). Поэтому как только в этом цикле мы найдем фильтр, который вернет false, то значит сообщение должно быть отфильтровано и дальше другими фильтрами его проверять не нужно. Можно сразу вернуть результат (return true/false в зависимости от того, какую логику в результат ты закладываешь). Предлагаю переписать без использования переменной result.

2024-08-16 18:14 UTC, mysosnovskaya commented on src/main/java/spam/MessageProcessor.java
> +        for(MessageFilter<String> filter : filters) {
Тут пробел после for нужен)

2024-08-17 18:51 UTC, mysosnovskaya requested changes

2024-08-17 18:51 UTC, mysosnovskaya commented on src/main/java/spam/Main.java
> +            System.out.println("Message: " + message + " | Skipped: " + isFiltered);
В текущей реализации у тебя метод processMessage вернет true только тогда, когда сообщение НЕ нужно пропускать, т.е. оно не является спамом и удовлетворяет другим условиям. А вывод в консоль будет выглядеть так (skipped означает пропущено): 
`"Message: "Hello world!" | Skipped: true"`
Давай либо здесь изменим, либо в processMessage. Нужно для себя определить смысл, которым ты наделяешь метод processMessage (в какой ситуации он возвращает true, а в какой false) и следовать ему по всему коду.

2024-08-17 19:12 UTC, SharkB38 commented on src/main/java/spam/Main.java
> +            System.out.println("Message: " + message + " | Skipped: " + isFiltered);
Наверное skipped неудачное слово. Тут как на пропускном пункте, если с сообщением все хорошо то пропускаем его дальше, то есть true, если нет то задерживается то есть false. Наверное тут подойдет Pass, чтобы не было путаницы?

2024-08-18 18:32 UTC, mysosnovskaya commented on src/main/java/spam/Main.java
> +            System.out.println("Message: " + message + " | Skipped: " + isFiltered);
Да, согласна, с Passed будет лучше)

2024-08-18 18:33 UTC, mysosnovskaya approved these changes

2024-08-18 18:33 UTC, merged