Решение задачи Фильтруем спам
CorporationX/god_bless pull request #8912
Opened 2024-08-13 10:49 UTC by wmwmaks

2024-08-14 17:30 UTC, InnMish commented on src/main/java/filter/spam/MessageProcessor.java
> +                return true;
а как у тебя ретерн сработает?)
Ты запускаешь цикл по всем фильтрам, но при этом на 10 строчке если только самый первый фильтр прошел успешно, ты сразу говоришь, что все ок - возвращаешь тру
Но на самом деле у тебя еще осталось несколько непроверенных фильтров ведь!)

2024-08-14 17:48 UTC, wmwmaks commented on src/main/java/filter/spam/MessageProcessor.java
> +                return true;
Я думал так и задумано. Нужно, чтобы каждое сообщение проверялось по всем фильтрам? Получается, и вывод нужно менять, чтобы информацию по всем фильтрам для каждого сообщения выводить?

2024-08-18 18:36 UTC, mysosnovskaya requested changes

2024-08-18 18:36 UTC, mysosnovskaya commented on src/main/java/filter/spam/Main.java
> +            System.out.println("Message: " + message + " | Filter: " + isFiltered);
Надо разобраться с этими true-false. В текущей реализации так: если processMessage вернул true, то это значит, что сообщение не является спамом (оно корректное и ни под один фильтр не попало). А это значит, что в консоль выведется: Filter: true - что означает, что сообщение отфильтровано (т.е. к сообщению применился один из фильтров). По-моему тут путаница возникла? Нужно либо здесь изменить работу с результатом метода processMessage, либо в processMessage изменить логику true/false

2024-08-18 19:43 UTC, mysosnovskaya approved these changes

2024-08-18 19:43 UTC, merged