BJS2-21433 - Калькулятор
CorporationX/god_bless pull request #8984
Opened 2024-08-13 16:46 UTC by GusevVrn

2024-08-13 21:53 UTC, GusevVrn commented
Как-то можно сократить instanceof'ы ?

2024-08-16 01:27 UTC, Sabina-Vishnya reviewed
раз решил расширить калькулятор в обход заданию, давай попробуем поменять реализацию, щас читается сложнее, к тому же опечатки есть

предлагаю не юзать wildCard, это чревато проблемами и лучше стараться их не использовать, а использовать дженерик (будет условное Т)

подумай как это сделать (интерфейс поправить надо будет, calculate в CalculatorImplementation немного измениться, но логика упроститься, а для других методов будет по прежнему проверка экземпляров, но вроде все равно должно быть по коду более структурирование) можно в общем попробовать переписать, раз усложнение себе придумал

2024-08-16 13:24 UTC, GusevVrn commented
@Sabina-Vishnya такое ощущение что стало хуже))

2024-08-20 00:25 UTC, pablo023 requested changes
Тут получился кривой велосипед. Если ты хочешь сделать что-то по уму, делай по уму до конца) По уму калькулятор единственное, что должен дополнительно делать вне задания - при операции, где одно число - плавающее, а другое - нет, возвращать плавающее, всё. Но я не советую тебе впредь таким заниматься. Писать нужно максимально коротко, и просто. Если тебе нужен простор для творчества - ты можешь взять сложную задачу. Из простой лепить сложную не нужно)

2024-08-20 00:25 UTC, pablo023 commented on src/main/java/faang/school/godbless/calculator/CalculatorImplementation.java
> +        }
Это немножко бесполезно, т.к. ты вряд ли когда-то будешь иметь дело с List<Object>, где у тебя могут быть такие разные типы.

2024-08-20 00:25 UTC, pablo023 commented on src/main/java/faang/school/godbless/calculator/CalculatorImplementation.java
> +                return (Integer) a * (Integer) b;
Зачем ты кастишь, если ты уже убедился, что а и б - Integer?

2024-08-20 00:25 UTC, pablo023 commented on src/main/java/faang/school/godbless/calculator/CalculatorImplementation.java
> +    private void checkIfAllElementsIsNumber(List<T> numbers) {
areNumbers*

2024-08-20 00:25 UTC, pablo023 commented on src/main/java/faang/school/godbless/calculator/CalculatorImplementation.java
> +    public Number sumIntegers(List<T> nums) {
В этом нет смысла. Если ты называешь метод сумма интеджеров, ты не должен на вход ожидать чего-то кроме интеджеров. В целом, настолько узкие абстракции нет смысла делать. Имеет смысл написать короткий и элегантный метод, который тебе что угодно суммировать будет, а не 100 методов на каждый тип данных.

2024-08-20 00:25 UTC, pablo023 commented on src/main/java/faang/school/godbless/calculator/Main.java
> +                return (Double) a + (Double) b;
Зачем ты кастишь, если ты уже проверку сделал, что они - этого типа?

2024-08-20 12:01 UTC, GusevVrn commented on src/main/java/faang/school/godbless/calculator/CalculatorImplementation.java
> +        }
Согласен, изначально я не расширялся от Number, поэтому проверял в методе

2024-08-20 12:02 UTC, GusevVrn commented on src/main/java/faang/school/godbless/calculator/CalculatorImplementation.java
> +                return (Integer) a * (Integer) b;
Если оставить просто a + b получаю ошибку Operator '+' cannot be applied to 'java.lang.Number', 'java.lang.Number'
Забыл что улучшили instance of. Переделал, но разве в таком случае не будет перерасход по памяти? У тебя же отдельно память выделяется под `a instanceof Integer elem`
Опять же в рамках текущей задачи некритично, но если что-то серьезнее будет?
Просто каст разве не проще?

2024-08-20 12:12 UTC, GusevVrn commented
@pablo023 я изначально когда к задаче приступил, было написано везде числа, вот и подумал про Number. Только когда  доделал уже обратил внимание что в задании требовалось сделать чтоб integers работали, но не стал переделывать, попробовал сделать чтоб сразу попробовать все по максимуму и wildcards и обобщенные типы.

2024-08-24 01:24 UTC, pablo023 commented on src/main/java/faang/school/godbless/calculator/CalculatorImplementation.java
> +                return (Integer) a * (Integer) b;
Если честно, это вообще не так делается по уму. Хотелось бы объяснить - как, но наверное лучше будет, если я тебе посоветую книгу Elegant Objects, от Егора Бугаенко. В двух словах правильный подход к ООП не объяснить. Там в 2-3 главах как раз этот кейс рассмотрен.

2024-08-24 01:25 UTC, pablo023 commented
> @pablo023 я изначально когда к задаче приступил, было написано везде числа, вот и подумал про Number. Только когда доделал уже обратил внимание что в задании требовалось сделать чтоб integers работали, но не стал переделывать, попробовал сделать чтоб сразу попробовать все по максимуму и wildcards и обобщенные типы.

Я понимаю твой интеншен, но раз уж взялся - делай до конца с ним, а то на полпути так сказать оставил. Окей, двигаемся дальше.

2024-08-24 01:25 UTC, merged