feat: добавлен метод findHobbyLovers для поиска пользователей по активностям
CorporationX/god_bless pull request #8991
Opened 2024-08-13 17:24 UTC by Suragany98

- Создан метод findHobbyLovers в классе User, который принимает список пользователей и множество активностей.
- Метод возвращает мапу, где ключом является пользователь, а значением — первая активность, совпавшая с переданными.
- Реализована логика фильтрации и поиска совпадающих активностей с использованием Stream API.
- Добавлен пример использования метода в классе Main с выводом результатов в консоль.

2024-08-17 20:20 UTC, Suragany98 commented on src/main/java/faang/school/godbless/BJS2_18458/User.java
> +     */
ok ponyal sled raz tak y sdelayu )

2024-08-17 20:31 UTC, mysosnovskaya requested changes

2024-08-17 20:31 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/BJS2_18458/User.java
> +    }
Всё супер, только лишняя фигурная скобка :)

2024-08-18 18:03 UTC, mysosnovskaya approved these changes

2024-08-18 18:03 UTC, merged