BJS2-22425 Потренируем StreamAPI 2
CorporationX/god_bless pull request #9018
Opened 2024-08-13 21:09 UTC by Murzin34

2024-08-19 09:57 UTC, 20cognosce requested changes
Если бы не 1 и 4 задачи, то я бы принял.

2024-08-19 09:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/streamapi2/Main.java
> +                        .map(j -> i + " + " + j + " = " + num))
Я не уверен, что это норм

2024-08-19 09:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/streamapi2/Main.java
> +                        .map(j -> i + " + " + j + " = " + num))
Это цикл в цикле фактически
```
for (i)
    for (j)
```
Можно было получше придумать

2024-08-19 09:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/streamapi2/Main.java
> +                .forEach(System.out::println);
Надо список отдавать

2024-08-19 09:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/streamapi2/Main.java
> +        }));
forEach - это не стримы
внутри if дикое условие

декомпозируй это всё и перепиши на flatmap

2024-08-19 09:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/streamapi2/Main.java
> +                .forEach((department, avrSalary) ->
forEach под запретом, отдавай мапу, как по условию

2024-08-19 09:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/streamapi2/Main.java
> +                .filter(word -> word.chars().allMatch(c -> lettersStr.indexOf(c) >= 0))
почему не contains?

2024-08-19 09:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/streamapi2/Main.java
> +        integers.forEach(i -> System.out.println(i + " = " + Integer.toBinaryString(i)));
Список на выходе

2024-08-19 09:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/streamapi2/Main.java
> +                .filter(num -> String.valueOf(num).equals(new StringBuilder(String.valueOf(num)).reverse().toString()))
Эту строчку декомпозировать

2024-08-19 09:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/streamapi2/Main.java
> +                .filter(word -> word.equalsIgnoreCase(new StringBuilder(word).reverse().toString()))
Аналогично
И вернуть список

2024-08-19 09:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/streamapi2/Main.java
> +                .filter(num -> IntStream.rangeClosed(1, num / 2).filter(d -> num % d == 0).sum() == num)
.filter с новой строки и в отдельный метод

2024-08-21 17:14 UTC, 20cognosce approved these changes
В целом хорошо, выглядит чисто

2024-08-21 17:14 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/streamapi2/Main.java
> +import java.util.*;
Не сворачивать

2024-08-21 17:14 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/streamapi2/Main.java
> +                .collect(Collectors.toSet());
Хорошо, но перестановки (1; 2) и (2; 1) получатся на выходе

2024-08-21 17:14 UTC, 20cognosce commented on src/main/java/faang/school/godbless/modul2/streamapi2/Main.java
> +                .filter(word -> word.chars().allMatch(c -> lettersStr.contains(Character.toString(c))))
Эта строчка должна была быть декомпозирована, так как chars - создает новый стрим

2024-08-21 17:14 UTC, merged

2024-08-21 17:19 UTC, Murzin34 commented on src/main/java/faang/school/godbless/modul2/streamapi2/Main.java
> +                .collect(Collectors.toSet());
А ВОТ И НЕ ПОЛУЧАЮТСЯ! Я же возвращаю Set, поэтому distinct не нужен.
![image](https://github.com/user-attachments/assets/c547d873-8a2c-446c-a7b3-d7bba971d46e)