BJS2-21314 : Gmail Rich Filters
CorporationX/god_bless pull request #9028
Opened 2024-08-14 03:24 UTC by soulasphyxia

2024-08-14 06:48 UTC, InnMish commented on src/main/java/gmail_rich_filters/EmailProcessor.java
> +                    System.out.println(convertor.apply(mail));
смотри, accept выводит на экран сообщение о том, что мы обработали сообщение
но по факту обрабатываешь его ты только на следующей строчке хехе

еще: у тебя функция в мейне берет тело имейла, который ты передаешь и переводит его в upper case  
если ты передаешь исходный имейл, мы теряем его изначальное состояние после того, как сработала функция 

Это значит, что пользовать никогда больше не сможет вернуться к исходному письму 
На почте так, конечно, делать нельзя) 
давай подумаем, как не потерять изначальное сообщение

2024-08-14 15:37 UTC, soulasphyxia commented on src/main/java/gmail_rich_filters/EmailProcessor.java
> +                    System.out.println(convertor.apply(mail));
1 замечание поправил, спасибо!
есть вопрос по второму: разве когда мы вызываем такие методы в stream, оригинальная коллекция меняется? мне кажется, что если бы я использовал map, и затем вернул список писем, то да, там будут другие, но вот я вывел письма после работы функции, они остались такими же, поэтому они не потеряются, а обработанные уже можно куда-нибудь сохранить, если дополнить метод

2024-08-16 15:50 UTC, mysosnovskaya requested changes

2024-08-16 15:50 UTC, mysosnovskaya commented on src/main/java/gmail_rich_filters/EmailProcessor.java
> +        emails.forEach(mail -> System.out.println(mail.getBody()));
Получается, какие-то письма выведутся дважды: в обработанном и необработанном варианте?) Думаю, можно не выводить вообще все письма, достаточно только обработанных.

2024-08-16 15:50 UTC, mysosnovskaya commented on src/main/java/gmail_rich_filters/EmailProcessor.java
> +                    System.out.println(convertor.apply(mail));
В твоем случае как раз processor отвечает за вывод на экран. Получается, вывод будет дублироваться? 
Я думаю, можно использовать Email в качестве второго параметра функции (т.е. что-то делаем с письмом и возвращаем его преобразованную копию). Тогда здесь внутри forEach можно сначала выполнить convertor, получить Email, а потом к этому Email применить processor. 

Или если опираться на предоставленный в задаче пример, то для простоты можно здесь Function<Email, String> написать, подразумевая, что эта функция применяется только к содержимому письма. Тогда можно получить String от convertor, создать копию письма с преобразованным содержимым и к нему применить processor.

Мне вообще первый вариант больше нравится, но ты можешь выбрать любой из двух)

2024-08-16 19:31 UTC, mysosnovskaya approved these changes

2025-01-17 21:18 UTC, closed without merging