BJS2-21440   Gmail Rich Filters
CorporationX/god_bless pull request #9045
Opened 2024-08-14 08:20 UTC by ilu23ilu23

2024-08-17 15:34 UTC, 20cognosce requested changes

2024-08-17 15:34 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_21440/Email.java
> +    boolean isImportant;
Почему нет модификатора

2024-08-17 15:34 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_21440/EmailProcessor.java
> +            emailStringFunction.apply(email);
Такая же проблема как и другого твоего коллеги, копипастну:

Ты должен использовать полученное значение
А не делать что-то внутри и забивать на ответ
У тебя между консьюмером, функцией и предикатом разницы тогда нет в этой реализации

2024-08-18 08:10 UTC, ilu23ilu23 commented on src/main/java/faang/school/godbless/BJS2_21440/Email.java
> +    boolean isImportant;
Торопился и не написал

2024-08-18 08:16 UTC, ilu23ilu23 commented on src/main/java/faang/school/godbless/BJS2_21440/EmailProcessor.java
> +            emailStringFunction.apply(email);
ок

2024-08-18 08:27 UTC, 20cognosce approved these changes

2024-08-18 08:27 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_21440/EmailProcessor.java
> +                emailStringFunction.apply(email);
Фишка функции в том, что она возвращает значение
Внутри нее email не должен менять свое состояние, ты должен новый объект создать и вернуть здесь

2024-08-18 08:28 UTC, 20cognosce commented
Conflicting files
src/main/java/faang/school/godbless/BJS2_20880/SpellCaster.java

2024-08-18 08:28 UTC, closed without merging