BJS2-21237 Lord of the Rings RPG
CorporationX/god_bless pull request #9063
Opened 2024-08-14 11:58 UTC by cemeh666

2024-08-16 19:39 UTC, 20cognosce requested changes

2024-08-16 19:39 UTC, 20cognosce commented on src/main/java/lord/of/the/rings/InventoryManager.java
> +                System.out.printf("Предмет '%s' был удалён из инвенторя", item.getName()).println();
for больше не используем, старайся писать через stream 
Если есть предикат - Stream.filter

2024-08-16 19:39 UTC, 20cognosce commented on src/main/java/lord/of/the/rings/InventoryManager.java
> +                System.out.printf("Предмет '%s' был удалён из инвенторя", item.getName()).println();
Ну тут ты и ничего не удалил вообще

2024-08-16 19:39 UTC, 20cognosce commented on src/main/java/lord/of/the/rings/InventoryManager.java
> +                System.out.printf("Предмет '%s' был удалён из инвенторя", item.getName()).println();
Можно даже без итераций - готовый метод у списка removeIf (но так как я тебе его уже сам сказал, то переделывай через filter)

2024-08-16 19:39 UTC, 20cognosce commented on src/main/java/lord/of/the/rings/InventoryManager.java
> +                return;
Никаких for и if, переделываем

2024-08-16 19:39 UTC, 20cognosce commented on src/main/java/lord/of/the/rings/InventoryManager.java
> +        System.out.println("Предмет не был найден");
Лучше эксепшн кидать, запись в консоли растворится моментально и никто ничего не заметит

2024-08-16 19:39 UTC, 20cognosce commented on src/main/java/lord/of/the/rings/Main.java
> +        manager.removeItem(frodo, (item) -> item.getName().equals("Knife"));
Поэтому надо писать тесты, потому что баги из-за невнимательности

2024-08-16 19:39 UTC, 20cognosce commented on src/main/java/lord/of/the/rings/InventoryManager.java
> +                System.out.printf("Предмет '%s' был удалён из инвенторя", item.getName()).println();
И зачем нам два принта?

2024-08-16 19:39 UTC, 20cognosce commented on src/main/java/lord/of/the/rings/InventoryManager.java
> +                return;
И еще ты удаляешь только один предмет
А если все предметы удовлетворяют условию

2024-08-16 19:39 UTC, 20cognosce commented on src/main/java/lord/of/the/rings/InventoryManager.java
> +                return;
И обновить опять-таки надо ВСЕ предметы, которые попадают под предикат

2024-08-17 07:51 UTC, cemeh666 commented on src/main/java/lord/of/the/rings/InventoryManager.java
> +                return;
по условию задачи  

> удаляет **предмет** из инвентаря персонажа

2024-08-17 07:54 UTC, cemeh666 commented on src/main/java/lord/of/the/rings/Main.java
> +        manager.removeItem(frodo, (item) -> item.getName().equals("Knife"));
Причём тут тесты? это пример, когда предмет не был найден

2024-08-17 08:36 UTC, cemeh666 commented on src/main/java/lord/of/the/rings/InventoryManager.java
> +                System.out.printf("Предмет '%s' был удалён из инвенторя", item.getName()).println();
всё переделал

2024-08-17 08:37 UTC, cemeh666 commented on src/main/java/lord/of/the/rings/InventoryManager.java
> +                return;
всё переделал

2024-08-17 14:54 UTC, 20cognosce commented on src/main/java/lord/of/the/rings/InventoryManager.java
> +            .findFirst();
У тебя в инвентаре 3 яблока и 2 апельсина.

Вызывается метод removeItem с предикатом "Удали предмет, если это яблоко"
И ты оставляешь в инвентаре 2 яблока и 2 апельсина.

Как сам думаешь, это ожидаемое поведение данного метода? 

+ Ты берешь первое попавшееся, то есть какое-то рандомное из этих 3-х яблок, этот метод тогда вообще генерирует хаотические состояние инвентаря.
+ Ты ссылаешься на ТЗ, что мол там "предмет" в единственной числе. Но вообще ТЗ бывает кривым и ошибочным, если с точки зрения логики в нем есть ошибка, то твоя задача как разработчика её подсветить, обсудить и справить с аналитиком. Если ты просто слепо реализуешь какую-то фигню, и это всплывет во время эксплуатации - ты конечно можешь успешно спихнуть этот косяк на аналитика, что он тебе некорректное ТЗ подсунул. Но за косяки ответственность перед бизнесом лежать все равно будет на всей команде и премии лишат вас всех.

2024-08-17 14:54 UTC, 20cognosce commented on src/main/java/lord/of/the/rings/InventoryManager.java
> +            character.getInventory().remove(item.get());
Давай удалим все предметы, которые попали под предикат.

2024-08-17 14:54 UTC, 20cognosce commented on src/main/java/lord/of/the/rings/InventoryManager.java
> +        character.getInventory().replaceAll(item -> itemPredicate.test(item) ? itemFunction.apply(item) : item);
replaceAll - очень неудачный метод для этой задачи, потому что ты переобновляешь все элементы в коллекции, даже те, которые трогать не надо, ты всё равно им обновляешь ссылки.

2024-08-17 14:54 UTC, 20cognosce commented on src/main/java/lord/of/the/rings/InventoryManager.java
> +        character.getInventory().replaceAll(item -> itemPredicate.test(item) ? itemFunction.apply(item) : item);
Это тоже можно сделать через 
stream
.filter
.map()
.collect();

Только не потеряй предметы, которые под предикат не попали.

2024-08-17 14:54 UTC, 20cognosce commented on src/main/java/lord/of/the/rings/Main.java
> +        manager.updateItem(frodo, (item) -> item.getName().equals("The One Ring"), (item) -> new Item(item.getName(), item.getValue() * 2));
Когда параметры в одну строчку не влезают и создают однородную кашу - переноси каждый параметр на отдельную строку для читаемости
![image](https://github.com/user-attachments/assets/87efa389-daae-4189-86b5-b9589a1996d6)

2024-08-17 14:54 UTC, 20cognosce commented on src/main/java/lord/of/the/rings/Main.java
> +        manager.removeItem(frodo, (item) -> item.getName().equals("Knife"));
> Причём тут тесты?
Отсылка была к тому, что метод removeItem не удалял предмет из инвентаря.

2024-08-18 11:24 UTC, cemeh666 commented on src/main/java/lord/of/the/rings/InventoryManager.java
> +            .findFirst();
несомненно я понимаю, что такие моменты требуют уточнения, но у нас на БК нету аналитика, а дёргать тебя или ещё кого-то не целесообразно. исходя из этого так и получается.
Подниму этот вопрос на ретре

2024-08-18 12:12 UTC, 20cognosce approved these changes
Закончим с этой задачей

2024-08-18 12:12 UTC, 20cognosce commented on src/main/java/lord/of/the/rings/InventoryManager.java
> +            });
Тут потенциально может выстрелить
Нельзя модифицировать коллекцию, по которой ты сейчас итерируешься (remove, add)
С set может оно прокатит, но здесь ты модифицируешь элементы стрима вне этого самого стрима, пока в стриме по этим элементам бежишь

У тебя может быть, что ты применил set -> объект изменился, и стрим увидел, что у тебя новый объект в стриме. И он снова начинает его пропускать через пайплайн стрима, так что **возможно, ты применишь itemFunction для одного элемента несколько раз**

2024-08-18 12:12 UTC, 20cognosce commented on src/main/java/lord/of/the/rings/InventoryManager.java
> +            });
Лучше реализовывать этот метод так:

```
List<Item> inventory = character.getInventory();
List<Item> updatedOldItems = new ArrayList<>(); //здесь лежат ссылки на предметы, которые будут обновлены
List<Item> updatedNewItems = inventory.stream() //здесь лежат ссылки на новые предметы, взамен обновляемых
        .filter(itemFilter)
        .map(item -> {
            updatedOldItems.add(item);
            return updateFunction.apply(item);
        })
        .toList();

inventory.removeAll(updatedOldItems);
inventory.addAll(updatedNewItems);
```

2024-08-18 12:13 UTC, merged