Lord of the Rings RPG BJS2-21261
CorporationX/god_bless pull request #9078
Opened 2024-08-14 13:33 UTC by vestmen

2024-08-16 20:34 UTC, 20cognosce requested changes

2024-08-16 20:34 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint2/lordOfTheRings/Character.java
> +    private final String NAME;
что за капс
капсом пишутся константы - public / private static final
final поле - это не константа

Вот число ПИ - константа, она public static final
А имя человека - не константа, но оно тоже не меняется и у каждого своё, присваивается один раз и поэтому private final,

2024-08-16 20:34 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint2/lordOfTheRings/Item.java
> +    private final String NAME;
переделать такие имена следует

2024-08-16 20:34 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint2/lordOfTheRings/InventoryManager.java
> +        boolean rsl = false;
кого? что? 
что за магическая переменная с магическим именем

2024-08-16 20:34 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint2/lordOfTheRings/InventoryManager.java
> +    public boolean updateItem(Character character, Predicate<Item> predicate, Function<Item, Item> function) {
update - void, упростим себе жизнь

2024-08-16 20:34 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint2/lordOfTheRings/InventoryManager.java
> +        }
ты два раза делаешь get одного и того же item

раз все равно переделывать - перепиши на stream.filter().map(), без цикла for

2024-08-16 20:34 UTC, 20cognosce commented on src/test/java/faang/school/godbless/sprint2/lordOfTheRings/InventoryManagerTest.java
> +        String[] result = {""};
зачем массив из одного элемента?

2024-08-16 20:34 UTC, 20cognosce commented on src/test/java/faang/school/godbless/sprint2/lordOfTheRings/InventoryManagerTest.java
> +    void isRemoved() {
зачем разделять removeItem / isRemoved 
updateItem / isUpdated

и почему isRemoved / isUpdated проверяет false?

2024-08-18 10:22 UTC, vestmen commented on src/test/java/faang/school/godbless/sprint2/lordOfTheRings/InventoryManagerTest.java
> +        String[] result = {""};
Если просто в переменную String записывал в люмбде результат, то выдавало ошибку "Variable used in lambda expression should be final or effectively final", вывел эту переменную в приватное поле и заработало, спасибо

2024-08-18 11:38 UTC, vestmen commented on src/main/java/faang/school/godbless/sprint2/lordOfTheRings/Character.java
> +    private final String NAME;
Понял

2024-08-18 11:39 UTC, vestmen commented on src/main/java/faang/school/godbless/sprint2/lordOfTheRings/Item.java
> +    private final String NAME;
Понял

2024-08-18 11:40 UTC, vestmen commented on src/main/java/faang/school/godbless/sprint2/lordOfTheRings/InventoryManager.java
> +        boolean rsl = false;
для того, чтобы вывести информацию об обновлении / не обновлении ввел результирующую переменную, которую потом вернул

2024-08-18 11:41 UTC, vestmen commented on src/main/java/faang/school/godbless/sprint2/lordOfTheRings/InventoryManager.java
> +    public boolean updateItem(Character character, Predicate<Item> predicate, Function<Item, Item> function) {
Хорошо

2024-08-18 11:41 UTC, vestmen commented on src/main/java/faang/school/godbless/sprint2/lordOfTheRings/InventoryManager.java
> +        }
прочитал, что мы не можем поменять один лишь объект коллекции через stream, а нужно создавать новую коллеккцию (но в таком случае тратится больше памяти), только если проходить не по самой коллекции, а по индексам - в данном случае тоже делается get 2 раза: IntStream.range(0, inventory.size())
.filter(i -> predicate.test(inventory.get(i)))
.forEach(i -> inventory.set(i, function.apply(inventory.get(i))));

2024-08-18 11:41 UTC, vestmen commented on src/test/java/faang/school/godbless/sprint2/lordOfTheRings/InventoryManagerTest.java
> +    void isRemoved() {
изначально сделал методы булевыми, чтобы они возвращали true/false (был удален элемент или нет), тесты проверяют на false для проверки был ли удален элемент

2024-08-18 12:22 UTC, merged