BJS2-23016 complete
CorporationX/god_bless pull request #9101
Opened 2024-08-14 16:32 UTC by mktlamer

2024-08-20 04:11 UTC, pablo023 requested changes
Это нужно сделать через реализацию методов

2024-08-20 06:57 UTC, mktlamer commented
поправил, commit добавил

2024-08-21 09:41 UTC, pablo023 requested changes
Поправь по комментам.

2024-08-21 09:41 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_23016/Main.java
> +                .filter(word -> word.startsWith("H"))
А почему with "H"? Символ, с которого начинается строка, должен передаваться аргументом в метод, а не просто из головы браться.

2024-08-21 09:41 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_23016/Main.java
> +    }
Тебе не надо брать условия из головы, под "удовлетворением определённому условию", подразумевается, что передаётся предикат, по которому мы тут фильтруем.

2024-08-21 11:11 UTC, mktlamer commented on src/main/java/faang/school/godbless/BJS2_23016/Main.java
> +    }
поправил, видимо уставший был и сделал условие по длине, как в предыдущем методе )

2024-08-22 02:08 UTC, merged