Meta-вселенная!!!!
CorporationX/god_bless pull request #9121
Opened 2024-08-14 20:04 UTC by RuslanIovlev

2024-08-16 11:15 UTC, mysosnovskaya requested changes
Хорошая работа! Одно небольшое исправление и поставлю аппрув)

2024-08-16 11:15 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/BJS2_22043/NotificationManager.java
> +            handlers.get(notification.getType()).accept(notification);
Стоило убедиться, что в handlers есть что-то по такому ключу. А то рискуем NPE (NullPointerException) словить)

2024-08-22 17:22 UTC, mysosnovskaya requested changes

2024-08-22 17:22 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/BJS2_22043/NotificationManager.java
> +        if (!filterNotification(notification) && !handlers.isEmpty()) {
handlers может быть не пустым, но не содержать хэндела по ключу notification.getType(). Тогда на следующей строке  `handlers.get(notification.getType())` вернет null и далее мы получим NullPointerException. Вот это нужно предотвратить и проверить, что в handlers есть подходящий обработчик. 
И лучше сначала это проверить, а затем уже фильтровать, т.к. если вдруг нужного хэндлера не окажется, то зря делали работу по фильтрации)

2024-08-22 19:05 UTC, RuslanIovlev commented
описание комита не правильно указал, вроде проверил на то чтобы значение были не пустыми

2024-08-22 20:26 UTC, mysosnovskaya requested changes

2024-08-22 20:26 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/BJS2_22043/NotificationManager.java
> +        if (!handlers.values().isEmpty()){
Нет, нам не на пустоту проверять нужно :)
Смотри, в handlers могут быть обработчики для email и спам -> handlers не пустой. Но тебе в метод sendNotification пришло sms. У тебя обработчика для sms нет. Нужно об этом сообщить и ничего больше не делать (filterNotification не нужно вызывать). Т.е. прежде чем обрабатывать входящий notification, нужно убедиться, что у тебя для него есть обработчик.

2024-08-23 09:39 UTC, mysosnovskaya approved these changes

2024-08-23 09:39 UTC, merged