BJS2-22013 - Meta Universe
CorporationX/god_bless pull request #9148
Opened 2024-08-15 09:16 UTC by mrkorolev

Хотел спросить совета по поводу случая с sms: не смог модерировать сообщение без изменения состояния уведомления (Notification.message), подскажите, как это можно было здесь провернуть.

2024-08-18 18:45 UTC, 20cognosce commented
> с sms: не смог модерировать сообщение без изменения состояния уведомления (Notification.message)

```
nm.registerHandler("sms", (notification, detectedSet) -> {
            String moderatedMsg = notification.getMessage();
            if (!detectedSet.isEmpty()) {
                moderatedMsg = "Moderated notification - detected " + detectedSet.size() + " banned words: " + detectedSet;
            }

            return moderatedMsg;
        });
```
Ты тут никак notification не изменил
?
Запусти в debug, и посмотри, что у тебя в notification исходное сообщение

2024-08-18 18:45 UTC, 20cognosce requested changes
Давай красиво сделаем

2024-08-18 18:45 UTC, 20cognosce commented on src/main/java/faang/school/godbless/meta/NotificationManager.java
> +    private static final Set<String> MODERATION_TRIGGERS = Set.of("buy", "vote", "donate", "bitch", "purchase");
Зачем ругаемся

2024-08-18 18:45 UTC, 20cognosce commented on src/main/java/faang/school/godbless/meta/Main.java
> +
Пустые строки

2024-08-18 18:45 UTC, 20cognosce commented on src/main/java/faang/school/godbless/meta/Main.java
> +
Пустые строки для кого

2024-08-18 18:45 UTC, 20cognosce commented on src/main/java/faang/school/godbless/meta/Main.java
> +                detectedSet.forEach(trg -> notification.setMessage(notification.getMessage().replaceAll(trg, REPLACER.repeat(trg.length()))));
Не в одну строку, каша

2024-08-18 18:45 UTC, 20cognosce commented on src/main/java/faang/school/godbless/meta/Main.java
> +                notification.setMessage(notification.getMessage().concat(" (moderated)"));
За один setMessage все изменения примени

2024-08-18 18:45 UTC, 20cognosce commented on src/main/java/faang/school/godbless/meta/Notification.java
> +    private String type;
Почему тут type

2024-08-18 18:45 UTC, 20cognosce commented on src/main/java/faang/school/godbless/meta/NotificationManager.java
> +        notificationStore.put(id, handler);
А тут id?

2024-08-18 18:45 UTC, 20cognosce commented on src/main/java/faang/school/godbless/meta/NotificationManager.java
> +    }
Почему у тебя одна и та же логика модерации раскидана по двум разным местам - в Main у sms/push/email каждый по-своему работает с ключевыми словами, а тут ты и еще сверху что-то проверяешь. Всё должно быть в одном месте.

2024-08-18 18:45 UTC, 20cognosce commented on src/main/java/faang/school/godbless/meta/NotificationManager.java
> +
Пустые строки

2024-08-18 18:45 UTC, 20cognosce commented on src/main/java/faang/school/godbless/meta/NotificationManager.java
> +        String moderatedMsg = notificationStore.get(notification.getType()).apply(notification, detectTriggers(notification));
не в одну строку, пожалуйста

2024-08-19 00:59 UTC, mrkorolev commented on src/main/java/faang/school/godbless/meta/Main.java
> +
@20cognosce Между именами пакета и класса не должно быть пустой строчки?)  И соответственно между именем класса и константой тоже?

2024-08-19 01:00 UTC, mrkorolev commented on src/main/java/faang/school/godbless/meta/NotificationManager.java
> +
@20cognosce Тот же вопрос что и выше

2024-08-19 09:10 UTC, mrkorolev commented on src/main/java/faang/school/godbless/meta/NotificationManager.java
> +    }
@20cognosce не уверен что понял тебя - этот кусок не за логику модерации отвечает, а за получение списка detected triggers. А вот что уже с ним дальше делать - дело каждого хэндлера.

2024-08-19 16:58 UTC, 20cognosce commented on src/main/java/faang/school/godbless/meta/Main.java
> +
Только между классом и полями не нужны

2024-08-19 17:00 UTC, merged