Вспомним школу 20534
CorporationX/god_bless pull request #9171
Opened 2024-08-15 12:03 UTC by Peregruzochka

2024-08-15 19:58 UTC, 20cognosce requested changes

2024-08-15 19:58 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20534/Main.java
> +        if (a > sum.apply(b).apply(c)) {
Равенства тоже быть не может

2024-08-15 19:58 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20534/Main.java
> +        if (a > sum.apply(b).apply(c)) {
Можно в отдельный метод кстати

2024-08-15 19:58 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20534/Main.java
> +        double halfPerimeter = mul.apply(div.apply(1.0).apply(2.0)).apply(perimeter);
такое умножение на 1/2?
Интересно, надеюсь, ты от скуки так решил сделать

2024-08-15 19:58 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20534/Main.java
> +        double halfPerimeter = mul.apply(div.apply(1.0).apply(2.0)).apply(perimeter);
Кстати я не уверен в том что это работает
 1 / 2 = 0, тебя спасает что ты числа с плавающей запятой передаешь

2024-08-15 19:58 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20534/Main.java
> +        return sqrt.apply(mul.apply(mul.apply(mul.apply(halfPerimeter).apply(halfPerimeterMinusA)).apply(halfPerimeterMinusB)).apply(halfPerimeterMinusC));
Тебе самому не показалось это громоздким?))
В одну строчку так писать не надо

2024-08-15 19:58 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20534/Main.java
> +        System.out.println(application.triangleArea(3, 1, 1));
Попробуй-ка нарисовать такой треугольник)))
Не, это надо переделывать

Сам себя поймал

2024-08-15 19:58 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20534/Main.java
> +        System.out.println(application.triangleArea(3, 1, 1));
Не работают эксепшены

2024-08-15 21:13 UTC, Peregruzochka commented on src/main/java/faang/school/godbless/BJS2_20534/Main.java
> +        double halfPerimeter = mul.apply(div.apply(1.0).apply(2.0)).apply(perimeter);
там просто div без дела лежал

2024-08-15 21:17 UTC, Peregruzochka commented on src/main/java/faang/school/godbless/BJS2_20534/Main.java
> +        return sqrt.apply(mul.apply(mul.apply(mul.apply(halfPerimeter).apply(halfPerimeterMinusA)).apply(halfPerimeterMinusB)).apply(halfPerimeterMinusC));
Я думал в этом суть задания, чтобы страдать)

2024-08-15 21:17 UTC, Peregruzochka commented on src/main/java/faang/school/godbless/BJS2_20534/Main.java
> +        System.out.println(application.triangleArea(3, 1, 1));
Я тестил, как выбрасываются exception)

2024-08-16 10:39 UTC, 20cognosce approved these changes

2024-08-16 10:39 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_20534/Main.java
> +        return Arrays.stream(nums).reduce(1.0, (result, num) -> mul.apply(result).apply(num));
1.0  - identity в reduce это типо первоначальное значение для умножения?
да, работает, но это не так очевидно воспринимается при первом взгляде
я бы написал так:

```
return Arrays.stream(nums)
        .reduce((firstNumber, secondNumber) -> mul.apply(firstNumber).apply(secondNumber))
        .orElseThrow();
```

2024-08-16 10:39 UTC, merged