BJS2-21244 - Реализованы методы для работы с инвентарем
CorporationX/god_bless pull request #9193
Opened 2024-08-15 14:40 UTC by GusevVrn

2024-08-19 23:54 UTC, pablo023 commented
BJS2-21244 - Lord of the Rings RPG - вот так должен называться этот Pull-Request.

2024-08-19 23:58 UTC, pablo023 requested changes

2024-08-19 23:58 UTC, pablo023 commented on src/main/java/faang/school/godbless/lordOfTheRings/InventoryManager.java
> +        //character.getInventory().stream().filter(filter)..map(handler).count();
Забыл убрать. Следи за таким.

2024-08-19 23:58 UTC, pablo023 commented on src/main/java/faang/school/godbless/lordOfTheRings/InventoryManager.java
> +        itemInInventory.ifPresent(handler::apply);
Вот эта штука у тебя просто вызывается, возможно что-то применяет, возможно - нет, но она не апдейтит вещь, которая в инвентаре. Состояние вещи в инвентаре останется неизменённым.

2024-08-20 12:22 UTC, GusevVrn commented on src/main/java/faang/school/godbless/lordOfTheRings/InventoryManager.java
> +        itemInInventory.ifPresent(handler::apply);
Тут именно в Optional вопрос?
В main же проверял:
```        inventoryManager.updateItem(character,
                item -> item.getName().equalsIgnoreCase(knife.getName()),
                itemHandler);
        System.out.println(character.getInventory());

        inventoryManager.updateItem(character,
                item -> item.getName().equalsIgnoreCase(apple.getName()),
                itemHandler);
        System.out.println(character.getInventory());
[Item(name=knife, value=1)]    - было до
[Item(name=knife, value=2)]    - после обновления
[Item(name=knife, value=2)]

```

Вывел весь список того что сейчас есть: 1, вызвал обновление предмета , получил 2
Функция как раз просто повышает количество на 1
```
        Function<Item, Item> itemHandler = item -> {
            item.setValue(item.getValue() + 1);
            return item;
        };
```

2024-08-24 01:22 UTC, pablo023 commented on src/main/java/faang/school/godbless/lordOfTheRings/InventoryManager.java
> +        itemInInventory.ifPresent(handler::apply);
Ты прав, извини, погнал

2024-08-24 01:22 UTC, merged