BJS2-22036 - Meta-вселенная?
CorporationX/god_bless pull request #9224
Opened 2024-08-15 17:40 UTC by evgenywork

2024-08-18 19:01 UTC, 20cognosce requested changes
Функция
Консьюмер
Предикат

Это не одно и то же

2024-08-19 08:15 UTC, evgenywork commented on src/main/java/faang/school/godbless/sprint/two/metauniverse/NotificationManager.java
> +            return;
Поскольку задания я как понял , так и сделал . Если ты можешь сказать , как должно , то я напишу, поэтому данный return нужен.
так как ниже после If блока идет такое сообщение System.out.println("Cannot find notification type: " + notification.getType());

2024-08-19 08:49 UTC, evgenywork commented on src/main/java/faang/school/godbless/sprint/two/metauniverse/App.java
> +        notificationManager.registeredFilters(Constants.CHECK_BAD_WORDS, (notificationMessage) -> Arrays.stream(Constants.BAD_WORDS).anyMatch(notificationMessage.toLowerCase()::contains));
> не пишите монады в одну строку, пожалуйста, нет

Согласен , после стрим апи задач уже так не делаю ))

2024-08-19 08:53 UTC, evgenywork commented on src/main/java/faang/school/godbless/sprint/two/metauniverse/NotificationManager.java
> +            if (notificationFilters.get(Constants.CHECK_BAD_WORDS).apply(notification.getMessage())) {
> Что тут вообще написано? Если внутри мапы notificationFilters есть ключ "check_bad_words" применяем его значение к notification А сам notification ты проверил, надо к нему применять или нет?

Ты прав сейчас еще раз перечитал , по другому понял задачу . переделал. 
поместил фильтр в переменную , чтобы if лучше смотрелся или ты хотел ,как то  более элегантно?

2024-08-23 17:37 UTC, 20cognosce approved these changes

2024-08-23 17:37 UTC, merged