meta universe - чесно говоря, мне не понятно когда и какие лямбды нуж…
CorporationX/god_bless pull request #9236
Opened 2024-08-15 19:00 UTC by Killhimka

…но использовать, я просидел 3 часа над этой задачей, читал у ИИ спрашивал, разные лямбды прикрутить сюда,

 хотел
 мне не доходит.
Читать этот код очень трудно, я не могу настроить свой мозг понять эту тему ....
Мапу кстати финал подсветила идея по этому и поставил, хотя тоже не догоняю почему .... короче ппц(((

2024-08-19 23:24 UTC, Sabina-Vishnya commented on src/main/java/faang/school/functionalinterfacesandlambdas/metauniverse/NotificationManager.java
> +                if (consumer != null) {
почему это все нельзя в один (ну два) ифа сделать?
и что значит эти печати 1,2,3, в чем смысл этих шагов? также, какой смысл во втором элсе, если третий тоже самое сообщение напечатает?
вроде суть проверки простая тут вложена, но кода столько много, а можно сделать более линейным и читаемым.
Попробуй, учитывая эти вопросы, подумать над упрощением. 
В такие моменты лучше думать про это, а чтобы к этому упрощению прийти, стоит свежим взглядом взглянуть на свой код еще раз и попытаться оценить его простоту. Часто глаз замыливается и свой код самому сложнее оценить, он либо кажется понятный и простым, либо непонятным вовсе, но сама попытка, какой-то хоть и субъективной оценки, в перспективе принесет свои плоды по качеству кода.

у тебя задача то по сути выполнена, но вот эта куча лишних проверок слегла портит всю картину)

2024-08-20 16:25 UTC, Killhimka commented on src/main/java/faang/school/functionalinterfacesandlambdas/metauniverse/NotificationManager.java
> +    public void sendNotification(Notification notification) {
есть

2024-08-20 16:32 UTC, Killhimka commented on src/main/java/faang/school/functionalinterfacesandlambdas/metauniverse/NotificationManager.java
> +                if (consumer != null) {
Да это я после ревью Инны с Пашей, нафигачил такого

2024-08-20 16:32 UTC, Killhimka commented on src/main/java/faang/school/functionalinterfacesandlambdas/metauniverse/NotificationManager.java
> +        }
просто сократим проверку

2024-08-20 20:25 UTC, Sabina-Vishnya commented on src/main/java/faang/school/functionalinterfacesandlambdas/metauniverse/NotificationManager.java
> +    public void sendNotification(Notification notification) {
где?

2024-08-20 20:31 UTC, Sabina-Vishnya commented on src/main/java/faang/school/functionalinterfacesandlambdas/metauniverse/NotificationManager.java
> +                if (consumer != null) {
если даже тебе рекомендовали, то стоит понять - зачем и в каких случаях?) сказать, любой может и важно понимать контекст
если берешься применять это на задачах, то осознаннее применяй, для себя в первую очередь найди объяснение, почему и для чего, а не просто "мне сказали")

2024-08-24 01:35 UTC, pablo023 requested changes

2024-08-24 01:35 UTC, pablo023 commented on src/main/java/faang/school/functionalinterfacesandlambdas/metauniverse/NotificationManager.java
> +        }
public void registerHandler(String notification, Consumer<Notification> consumer) {
        if (notification == null || notification.isBlank()) {
            throw new IllegalArgumentException("Notification was not provided");
        }
        if (consumer == null) {
            throw new IllegalArgumentException("Consumer was not provided");
    }

        notificationHandler.put(notification, consumer);
    }

2024-08-24 01:35 UTC, pablo023 commented on src/main/java/faang/school/functionalinterfacesandlambdas/metauniverse/NotificationManager.java
> +    public void sendNotification(Notification notification) {
?

2024-08-24 23:08 UTC, pablo023 approved these changes

2024-08-24 23:08 UTC, merged