BJS2-23057 done
CorporationX/god_bless pull request #9243
Opened 2024-08-15 20:12 UTC by DenysDovgan

2024-08-20 04:16 UTC, pablo023 requested changes
Убери комменты, и это надо сделать через имплементацию методов по заданию

2024-08-21 14:30 UTC, DenysDovgan commented
> Убери комменты, и это надо сделать через имплементацию методов по заданию

Так вроде у меня все нормально. Есть метода которые принимают лист и доп. аргумент. Все с помощью стримов...

2024-08-22 02:10 UTC, pablo023 approved these changes

2024-08-22 02:10 UTC, pablo023 commented on src/main/java/faang/school/godbless/sprint2/streamAPI/BJS2_23057/Tasks.java
> +                .filter(s -> s.startsWith(substring))
Тут должно быть contains, а не startsWith. Но ладно, не страшно

2024-08-22 02:10 UTC, merged