BJS2-21249 — Lord of the Rings RPG
CorporationX/god_bless pull request #9293
Opened 2024-08-16 17:15 UTC by finariny

2024-08-16 19:45 UTC, mysosnovskaya requested changes
Немного переусложнено получилось из-за хэш мапы в Character. Вот если её убрать, то всё будет отлично) Молодец, что соблюдаешь стиль в коде! Я ни одной стилевой ошибки не заметила)

2024-08-16 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/BJS2_21249/Character.java
> +    private final Map<Item, Integer> inventoryMap = new HashMap<>();
А зачем нужно это поле? Вообще у персонажа должен быть только список предметов, при этом я бы это поле сделала финальным. Ну т.е. есть у персонажа условный рюкзак, он в него что-то складывает, что-то достает оттуда, но заменить один рюкзак на другой никто не может.

2024-08-16 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/BJS2_21249/InventoryManager.java
> +            character.getInventory().add(itemCount, item);
Вот этой строчки достаточно: нужно просто сразу в inventory положить новый предмет. Причем можно просто add(item) - новый предмет добавится в конец списка и никому не помешает)

2024-08-16 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/BJS2_21249/InventoryManager.java
> +        for (Item item : characterInventory) {
Посмотри метод removeIf для списков - он тебе здесь может хорошо помочь и сократить код)

2024-08-16 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/BJS2_21249/InventoryManager.java
> +                character.getInventory().set(character.getInventoryMap().get(item), function.apply(item));
Тут для вычисления индекса предмета можно использовать обычный for с индексами. Тогда необходимость в inventoryMap отпадет)

2024-08-16 19:45 UTC, mysosnovskaya commented on src/test/java/faang/school/godbless/BJS2_21249/InventoryManagerTest.java
> +class InventoryManagerTest {
Отличные тесты! Покрывают необходимые случаи, понятно названы, нет дублирования) Супер!)

2024-08-16 19:45 UTC, mysosnovskaya commented on src/test/java/faang/school/godbless/BJS2_21249/Constants.java
> +public class Constants {
Хорошее решение с тестовыми константами) Я бы только, наверное, переименовала класс в TestConstants, чтобы явно обозначить, что это только для тестов

2024-08-17 18:15 UTC, finariny commented
Привет! Добавила поля "inventoryMap" и "itemCounter" для того, чтобы можно было за константное время найти / удалить элементы в списке "inventory"

2024-08-17 18:23 UTC, mysosnovskaya approved these changes

2024-08-17 18:25 UTC, merged