Danke Villetti BJS2-20985
CorporationX/god_bless pull request #9295
Opened 2024-08-16 17:36 UTC by DankeVilletti

2024-08-16 18:58 UTC, mysosnovskaya requested changes

2024-08-16 18:58 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/DroidsSecrets/DroidMessageEncryptor.java
> +    String cipher(String text, int cipherKey, String methodName);
Думаю, название encrypt для метода лучше подойдет

2024-08-16 18:58 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/DroidsSecrets/Droid.java
> +    public String sendEncryptedMessage(String text, int cipherKey, String methodName) {
По заданию всё-таки нужен метод receiveEncryptedMessage - и я тоже думаю, что лучше его добавить. Иначе неочевидно, что метод с названием sendEncryptedMessage умеет расшифровывать сообщения)

2024-08-16 18:58 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/DroidsSecrets/Droid.java
> +    private final DroidMessageEncryptor encryptor = (message, key, methodName) -> {
Думаю, лямбда не должна ничего знать про то, шифрует она или дешифрует. Ей главное получить сообщение и ключ. А вот в зависимости от того, какой ключ ей передадут, такой результат и будет получаться. Т.е. я предлагаю, чтобы решение о том, какой ключ передать (с + или с -) принималось бы до вызова этой лямбды. Как раз когда будет два метода (sendEncryptedMessage и receiveEncryptedMessage) это можно будет сделать в них.

2024-08-16 18:58 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/DroidsSecrets/Droid.java
> +                encrypted.append((char) ((ch - base + key + 26) % 26 + base));
А зачем здесь + 26?

2024-08-19 16:13 UTC, DankeVilletti commented on src/main/java/faang/school/godbless/DroidsSecrets/Droid.java
> +                encrypted.append((char) ((ch - base + key + 26) % 26 + base));
без +26 "y" почему-то неправильно шифрует

2024-08-19 16:35 UTC, mysosnovskaya requested changes

2024-08-19 16:35 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/DroidsSecrets/Droid.java
> +public class Droid {
В классе нужно поправить стиль

2024-08-19 16:35 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/DroidsSecrets/Droid.java
> +        String msg = c3po.sendEncryptedMessage(encryptedMsg, encryptionKey,EncryptorMethodName.DECRYPT);
Должен быть метод receiveEncryptedMessage

2024-08-19 16:35 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/DroidsSecrets/Droid.java
> +    private final DroidMessageEncryptorOrDecrypt encryptionManager = (message, key, encryptorMethodName) -> {
Давай не будем вводить параметр encryptorMethodName. Передавай в эту лямбду либо key, либо -key, так и будет определяться, что с сообщением делается.

2024-08-19 16:35 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/DroidsSecrets/Droid.java
> +            encrypted.append((char) ((ch - base + key + 26) % 26 + base));
Это + 26 спасает именно при дешифровании (т.к. ключ отрицательный, то мы должны взять такой же ключ, но положительный: вместо -3 взять 23, т.е. смещать не на три влево, а на 23 вправо - результат одинаковый, а выражение ch - base + key гарантированно положительное), а для шифрования оно не нужно. Поэтому его можно вынести в ключ. Надо потестировать, разобраться)

2024-08-19 16:35 UTC, mysosnovskaya commented on src/main/java/faang/school/godbless/DroidsSecrets/Droid.java
> +    public String sendEncryptedMessage(String text, int cipherKey, EncryptorMethodName encryptorMethodName) {
Я предлагаю сделать как по заданию два метода: sendEncryptedMessage и receiveEncryptedMessage, оба они будут вызывать encryptionManager, но с разным параметром ключа. Так и будет происходить шифрование или дешифрование)

2024-08-21 15:29 UTC, merged