filter spam
CorporationX/god_bless pull request #9325
Opened 2024-08-17 12:38 UTC by Killhimka

2024-08-17 18:37 UTC, Sabina-Vishnya commented on src/main/java/faang/school/functionalinterfacesandlambdas/filterspam/MessageProcessor.java
> +    public boolean processMessage(String message, List<MessageFilter> messageFilters) {
кривовато работать будет
мы можем пропустить пустоту тогда, хотя это не валидно и пропускать такое не должны, при этом null если сообщение будет, все равно поймаем NPE

и если один из фильтров окажется null мы об этом лишь напечатаем, а не кинем ошибку - это задумано так было намеренно? 
если так, то ок, но в данном случае будто не очень корректно раз уж такая проверка есть,  то ошибку можно было бы и кинуть (но только, чтобы мейн не падал естественно), в целом не критично

2024-08-20 20:38 UTC, Sabina-Vishnya commented on src/main/java/faang/school/functionalinterfacesandlambdas/filterspam/MessageProcessor.java
> +    public boolean processMessage(String message, List<MessageFilter> messageFilters) {
что изменилось?

2024-08-24 01:41 UTC, pablo023 requested changes

2024-08-24 01:41 UTC, pablo023 commented on src/main/java/faang/school/functionalinterfacesandlambdas/filterspam/MessageProcessor.java
> +    public boolean processMessage(String message, List<MessageFilter> messageFilters) {
Вот эта вложенность глубокая - очень плохой паттерн. Тяжело читать, непонятно, выглядит тоже не очень. Вот так:

    public boolean processMessage(String message, List<MessageFilter> messageFilters) {
        if (message == null || message.isBlank()) {
            throw new IllegalArgumentException("Message cannot be null or blank.");
        }

        if (messageFilters == null || messageFilters.isEmpty()) {
            throw new IllegalArgumentException("Message filters cannot be null or empty.");
        }

        for (MessageFilter messageFilter : messageFilters) {
            if (!messageFilter.filter(message)) {
                return false;  // Return false if any filter does not pass
            }
        }

        return true;
    }

2024-08-24 23:09 UTC, merged