BJS2-22689 Анализатор вакансий
CorporationX/god_bless pull request #9327
Opened 2024-08-17 12:52 UTC by ostermal7

2024-08-22 03:54 UTC, pablo023 reviewed
В целом, в порядке. Есть недочеты - почитай про них, и после сам можешь вмержить.

2024-08-22 03:54 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_22689/DataAnalyzer.java
> +    }
Эти два метода одно и то же делают по сути. Не нужно дублированием функциональности заниматься.

2024-08-22 03:54 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_22689/JobScraper.java
> +            throw new RuntimeException(e);
Не нужно перебрасывать рантайм. Обрабатывай ошибки явно, и предоставляй информацию пользователю о том, что тут случилось.

2024-08-22 03:54 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_22689/DataAnalyzer.java
> +                .limit(3)
Антипаттерн магическое число. Погугли, пожалуйста

2024-08-22 03:54 UTC, pablo023 commented
Хотя нет, не мерж. Вот этот дубликат кода - это серьезный косяк. Надо исправлять

2024-08-22 03:55 UTC, pablo023 requested changes
.

2024-08-22 14:32 UTC, ostermal7 commented on src/main/java/faang/school/godbless/BJS2_22689/JobScraper.java
> +            throw new RuntimeException(e);
Это предлагает сам кэтч блок, не моя инициатива. Если тут обработать не ошибкой, то мне надо делать return чего-то, а если вернуть Null, до дальше в метода выбросится Nullpointer, что уже путает, т.к. ошибка изначально была не про это

2024-08-23 01:10 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_22689/JobScraper.java
> +            throw new RuntimeException(e);
Ну я имел ввиду, что кинь не рантайм, а какой-то уместный эксепшен, и добавь сообещние к нему понятное - что там произошло, где произошло, на каких данных

2024-08-23 01:10 UTC, pablo023 commented
Вмержи сам как прочтешь про рантайм

2024-08-23 19:31 UTC, merged