stream2
CorporationX/god_bless pull request #9374
Opened 2024-08-17 20:51 UTC by natalia-dch

2024-08-19 10:56 UTC, 20cognosce commented on src/main/java/faang/school/godbless/stream2/Stream2.java
> +        return pairs.stream().map(pair -> List.of(pair, sum - pair)).toList();
forEach - это тот же цикл for

2024-08-19 10:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/stream2/Stream2.java
> +        return pairs.stream().map(pair -> List.of(pair, sum - pair)).toList();
Попробуй использовать вспомогательный HashSet, и сравнивать числа в нем с числами в стриме

2024-08-19 10:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/stream2/Stream2.java
> +        return strings.stream().filter(str -> str.startsWith(String.valueOf(starts))).sorted(Comparator.comparingInt(String::length)).toList();
Не в одну строку

2024-08-19 10:58 UTC, 20cognosce commented on src/main/java/faang/school/godbless/stream2/Stream2.java
> +    }
Есть готовые методы в стандартных библиотеках

2024-08-19 10:59 UTC, 20cognosce commented on src/main/java/faang/school/godbless/stream2/Stream2.java
> +    }
Воспользуйся приведением к строке, это компактнее будет

2024-08-25 13:09 UTC, natalia-dch commented on src/main/java/faang/school/godbless/stream2/Stream2.java
> +        return pairs.stream().map(pair -> List.of(pair, sum - pair)).toList();
Поправила

2024-08-25 13:48 UTC, 20cognosce requested changes

2024-08-25 13:48 UTC, 20cognosce commented on src/main/java/faang/school/godbless/spotify/Player.java
> +    }
Вот это как попало в пулл реквест

2024-08-25 13:48 UTC, 20cognosce commented on src/main/java/faang/school/godbless/stream2/Stream2.java
> +        return strings.stream().filter(str -> str.startsWith(String.valueOf(starts))).sorted(Comparator.comparingInt(String::length)).toList();
Почему опять все стримы в одну строку, это невозможно читать
stream()
.peek()
.filter()
.map()
.collect()

2025-01-17 21:19 UTC, closed without merging