Java HashMap Индекс запросов ELK : bjs2 20011
CorporationX/god_bless pull request #9377
Opened 2024-08-17 22:55 UTC by GaribAghayev

2024-08-18 08:56 UTC, 20cognosce requested changes

2024-08-18 08:56 UTC, 20cognosce commented on src/main/java/faang/school/godbless/Maps/BJS2_20011/User.java
> +    private List<Query> queries = new ArrayList<>();
Ну нет, ну нет
User и Query - это просто как структуры данных, которые хранят в себе состояние
В них не должно быть бизнес-логики, вся логика в классах-сервисах

2024-08-18 08:56 UTC, 20cognosce commented on src/main/java/faang/school/godbless/Maps/BJS2_20011/User.java
> +    }
Не читери, делай по условию задачи

2024-08-19 01:07 UTC, GaribAghayev commented on src/main/java/faang/school/godbless/Maps/BJS2_20011/User.java
> +    }
Ладно)) это не сложно) просто показалось, что так лучше ))

2024-08-19 09:21 UTC, 20cognosce approved these changes

2024-08-19 09:21 UTC, 20cognosce commented on src/main/java/faang/school/godbless/Maps/BJS2_20011/Main.java
> +            queryMap.computeIfAbsent(user, k -> new ArrayList<Query>()).add(query);
одного computeIfAbsent достаточно, если значение есть, он отдаст текущее

2024-08-19 09:21 UTC, 20cognosce commented on src/main/java/faang/school/godbless/Maps/BJS2_20011/Main.java
> +        }
Это тоже через computeIfAbsent и addAll делается в одну строку

2024-08-19 09:22 UTC, merged