errors
CorporationX/god_bless pull request #9396
Opened 2024-08-18 08:20 UTC by natalia-dch

2024-08-18 09:09 UTC, 20cognosce requested changes

2024-08-18 09:09 UTC, 20cognosce commented on src/main/java/faang/school/godbless/errors/ErrorHandlingService.java
> +    ) {
На строчку выше

2024-08-18 09:09 UTC, 20cognosce commented on src/main/java/faang/school/godbless/errors/ErrorHandlingService.java
> +    }
Почему тут не написала через лямбду?

2024-08-18 09:09 UTC, 20cognosce commented on src/main/java/faang/school/godbless/errors/ErrorHandlingService.java
> +        ExceptionHandler exceptionHandler = System.out::println;
Ну и это не лямбда

2024-08-18 09:09 UTC, 20cognosce commented on src/main/java/faang/school/godbless/errors/ErrorHandlingService.java
> +    }
Это должны быть две лямбды, которые реализуют FunctionWithException
Соответственно у них должна быть одинаковая сигнатура, почему одна кидает эксепшн в сигнатуре, а другая нет

Можешь не создавать вообще никакие методы, а прям в параметрах передавать как 
withErrorHandling (
() -> {},
() -> {},
param);

2024-08-25 13:19 UTC, natalia-dch commented on src/main/java/faang/school/godbless/errors/ErrorHandlingService.java
> +    }
Поменяла на лямбды

2024-08-25 13:45 UTC, 20cognosce approved these changes

2024-08-25 13:45 UTC, 20cognosce commented on src/main/java/faang/school/godbless/errors/ErrorHandlingService.java
> +    ) {
) { 
их на строчку выше, не надо отрывать

2024-08-25 13:45 UTC, 20cognosce commented on src/main/java/faang/school/godbless/errors/ErrorHandlingService.java
> +        }, System.out::println, "params"));
params -> throw
тут скобки не нужны, тебе даже IDE их серым красит

2024-08-25 13:45 UTC, 20cognosce commented on src/main/java/faang/school/godbless/errors/ErrorHandlingService.java
> +        System.out.println(withErrorHandling(params -> "result", System.out::println, "params"));
Вот так, да

2024-08-25 13:45 UTC, merged