Накормите Питера Гриффина BJS2-23928
CorporationX/god_bless pull request #9422
Opened 2024-08-18 11:10 UTC by sultan-inked

2024-08-19 19:32 UTC, 20cognosce requested changes

2024-08-19 19:32 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/feed/peter/griffin/FoodDeliveryTask.java
> +    private final Logger logger = LoggerFactory.getLogger(FoodDeliveryTask.class);
@Slf4j

2024-08-19 19:32 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/feed/peter/griffin/FoodDeliveryTask.java
> +            Thread.sleep(getRandomMillisecond());
А что тут пробел не вставил

2024-08-19 19:32 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/feed/peter/griffin/GriffinsFoodDelivery.java
> +    private static final Logger logger = LoggerFactory.getLogger(GriffinsFoodDelivery.class);
@Slf4j

2024-08-19 19:32 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/feed/peter/griffin/GriffinsFoodDelivery.java
> +    }
В чем необходимость инициализации в статическом блоке?

2024-08-19 19:32 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/feed/peter/griffin/FoodDeliveryTask.java
> +    private final Random random;
То что ты в конструкторе передаешь Random - это очень странная затея

2024-08-19 19:32 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/feed/peter/griffin/GriffinsFoodDelivery.java
> +                    executorService.submit(() -> new FoodDeliveryTask(characterNames[i], getFoodAmount(), random).run());
А у тебя тут нет ошибки компиляции вообще? Как это ты сабмитишь вызов void метода run?

2024-08-19 19:49 UTC, sultan-inked commented on src/main/java/faang/school/godbless/task/multithreading/feed/peter/griffin/GriffinsFoodDelivery.java
> +                    executorService.submit(() -> new FoodDeliveryTask(characterNames[i], getFoodAmount(), random).run());
Не знаю, работает) Сейчас поменяю

2024-08-19 19:53 UTC, sultan-inked commented on src/main/java/faang/school/godbless/task/multithreading/feed/peter/griffin/FoodDeliveryTask.java
> +            Thread.sleep(getRandomMillisecond());
Я не понял где пробел пропустил

2024-08-20 16:26 UTC, 20cognosce approved these changes

2024-08-20 16:26 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/feed/peter/griffin/FoodDeliveryTask.java
> +            Thread.sleep(getRandomMillisecond());
После принта

2024-08-20 16:26 UTC, merged