BJS2-23386 Распределенная армия героев меча и магии
CorporationX/god_bless pull request #9428
Opened 2024-08-18 12:19 UTC by 108ardev

2024-08-21 09:37 UTC, pablo023 requested changes

2024-08-21 09:37 UTC, pablo023 commented on src/main/java/faang/school/godbless/distributedarmy/Army.java
> +        return units.parallelStream()
Параллельные стримы - неэффективны на малых объёмах данных, в данном случае однопоточный стрим был бы более производительным.

2024-08-21 09:37 UTC, pablo023 commented on src/main/java/faang/school/godbless/distributedarmy/Army.java
> +        return units.parallelStream()
Аа, ты хотел вот тут в отдельных потоках считать силу юнитов. Так это не сработает, тебе нужен ExecutorService, и ты должен ему отгружать задачи по одной, для каждого юнита.

2024-08-21 11:31 UTC, 108ardev commented on src/main/java/faang/school/godbless/distributedarmy/Army.java
> +        return units.parallelStream()
Исправил. Можешь объяснить, почему не будет работать?

2024-08-23 22:49 UTC, pablo023 reviewed
Вмержи сам после прочтения коммента.

2024-08-23 22:49 UTC, pablo023 commented on src/main/java/faang/school/godbless/distributedarmy/Army.java
> +        return units.parallelStream()
Конечно. Конкретно так, и конкретно здесь это сработает, но я не хочу тебя учить такой практике, было бы лучше, если бы ты вообще не знал, что так можно, т.к. этот подход - это поручение стримам всего, что связано с потоками - их созданию, управлению ими, их количеству, обработке ошибок, и так далее. В реальных условиях такой подход не сработает, т.к. ты его не контролируешь, и не можешь полагаться на то, что он нормально всё сделает, поэтому так мы не пишем. Он может просадить перформанс и положить тебе сервер, а ты даже не поймешь - что случилось.

2024-08-23 22:52 UTC, pablo023 commented on src/main/java/faang/school/godbless/distributedarmy/Army.java
> +        return units.parallelStream()
Конечно. Конкретно так, и конкретно здесь это сработает, но я не хочу тебя учить такой практике, было бы лучше, если бы ты вообще не знал, что так можно, т.к. этот подход - это поручение стримам всего, что связано с потоками - их созданию, управлению ими, их количеству, обработке ошибок, и так далее. В реальных условиях такой подход не сработает, т.к. ты его не контролируешь, и не можешь полагаться на то, что он нормально всё сделает, поэтому так мы не пишем. Он может просадить перформанс и положить тебе сервер, а ты даже не поймешь - что случилось.

2024-08-24 12:04 UTC, merged