Распределенная армия героев меча и магии BJS2-23382
CorporationX/god_bless pull request #9432
Opened 2024-08-18 12:44 UTC by sultan-inked

2024-08-20 17:06 UTC, 20cognosce requested changes

2024-08-20 17:06 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/might/and/magic/Army.java
> +                        return futures.get(i).get();
Ты дождался выполнения всех потоков прежде чем get() делать?

2024-08-20 17:06 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/might/and/magic/Army.java
> +                        return futures.get(i).get();
Через join() делай ожидание
Или по-взрослому: https://stackoverflow.com/questions/19348248/waiting-on-a-list-of-future

2024-08-21 09:01 UTC, sultan-inked commented
Вроде все условия выполнил, кроме применения AtomicInteger, думаю в моей реализации он не нужен, возможно ошибаюсь

2024-08-21 17:38 UTC, 20cognosce approved these changes
Дикий оверинжиниринг конечно, ну на вид работает корректно

2024-08-21 17:38 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/might/and/magic/Army.java
> +                        .toList());
Можно не лепить, вынеси в переменную

2024-08-21 17:38 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/might/and/magic/Army.java
> +                    .get();
Можно не лепить, ну не лепить
Что это за черная магия, код должен читаться легко

2024-08-21 17:38 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/might/and/magic/Army.java
> +    }
Было бы хорошо увидеть тут задержку, и выводы в консоль, что оно реально параллельно отрабатывает

2024-08-21 17:38 UTC, merged

2024-08-21 19:00 UTC, sultan-inked commented on src/main/java/faang/school/godbless/task/multithreading/might/and/magic/Army.java
> +    }
```
> Task :Main.main()
23:50:56.388 [pool-1-thread-2] INFO  - Power sum of Mage, even: 175 
23:50:56.388 [pool-1-thread-1] INFO  - Power sum of Archer, even: 150 
23:50:56.388 [pool-1-thread-3] INFO  - Power sum of Swordsman, even: 240 
Total army power: 565
```

2024-08-21 19:01 UTC, sultan-inked commented on src/main/java/faang/school/godbless/task/multithreading/might/and/magic/Army.java
> +                    .get();
```
private int calculate() {
        try {
            return CompletableFuture.allOf(futures.toArray(new CompletableFuture[0]))
                    .thenApply(v -> sumIntInFuture())
                    .get();
        } catch (InterruptedException | ExecutionException e) {
            log.error("Error: {}", e.getMessage());
            return 0;
        }
    }

    private int sumIntInFuture() {
        return futures.stream()
                .map(CompletableFuture::join)
                .mapToInt(Integer::intValue)
                .sum();
    }
    ```

2024-08-21 19:04 UTC, sultan-inked commented on src/main/java/faang/school/godbless/task/multithreading/might/and/magic/Army.java
> +                    .get();
Так правильно декомпозировал?

2024-08-21 19:06 UTC, sultan-inked commented on src/main/java/faang/school/godbless/task/multithreading/might/and/magic/Army.java
> +    }
Расчет по каждому типу юнитов в отдельном потоке

2024-08-21 19:13 UTC, sultan-inked commented on src/main/java/faang/school/godbless/task/multithreading/might/and/magic/Army.java
> +                        .toList());
Не совсем понял что ты имеешь в виду, я же и так храню результат в отдельной переменной `Integer` обёрнутую в `CompletableFuture<Integer>` что бы дождаться выполнения всех потоков

2024-08-21 19:21 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/might/and/magic/Army.java
> +                        .toList());
у тебя стрим внутри addAll()

2024-08-21 19:21 UTC, 20cognosce commented on src/main/java/faang/school/godbless/task/multithreading/might/and/magic/Army.java
> +                        .toList());
у тебя стрим внутри addAll()

2024-08-21 19:28 UTC, sultan-inked commented on src/main/java/faang/school/godbless/task/multithreading/might/and/magic/Army.java
> +                        .toList());
Вот так норм?
```
public int calculateTotalPower() {
    futures.addAll(getFutures());
    executor.shutdown();
    return calculate();
}

private List<CompletableFuture<Integer>> getFutures() {
    return army.values()
            .stream()
            .map(this::startThread)
            .toList();
}
```