BJS2-20991 - Секреты дроидов - шифрование и дешифрование через сдвиг
CorporationX/god_bless pull request #9441
Opened 2024-08-18 13:41 UTC by GusevVrn

Сделал ограничение для алфавита. Логика if-else, это если дошли до сдвига ниже Aa или выше Zz

2024-08-24 01:20 UTC, pablo023 requested changes
Надо переделать. Тут много лишнего, и усложнено без надобности

2024-08-24 01:20 UTC, pablo023 commented on src/main/java/faang/school/godbless/droids/Droid.java
> +    }
Стремись писать код максимально просто, элегантно, и понятно.

    public String sendEncryptedMessage(String message, int key) {

        DroidMessageEncryptor droidMessageEncryptor = (incomingMessage, shift) -> {
            StringBuilder shiftedString = new StringBuilder();

            for (char ch : incomingMessage.toCharArray()) {
                if (Character.isUpperCase(ch)) {
                    shiftedString.append((char) ('A' + (ch - 'A' + shift) % 26));
                } else if (Character.isLowerCase(ch)) {
                    shiftedString.append((char) ('a' + (ch - 'a' + shift) % 26));
                } else {
                    shiftedString.append(ch);  // Non-alphabetical characters remain unchanged
                }
            }

            return shiftedString.toString();
        };

        return droidMessageEncryptor.encryptDecryptMessage(message, key);
    }

2024-08-26 20:18 UTC, Sabina-Vishnya commented on src/main/java/faang/school/godbless/droids/Droid.java
> +    public String receiveEncryptedMessage(String encryptedMessage, int key) {
1 - шифр цезаря должен учитывать и отрицательный сдвиг, тут не учитывается и формула кривая
такие штуки можно через онлайн генераторы проверять, большинство из них хоть простые проверки покажет нормально
2 - тест кейсов больше должно быть, например:
```
граничные значения 0 и 26
> 26
< 26
аналогичное с отрицательными ключами
символы и цифры
разные регистры
```

3 Код по идее не должен выйти большим, что-то типа такого я бы сделала:
```
@Getter
@Setter
@ToString
@AllArgsConstructor
public class Droid {

    private static final int ALPHABET_SIZE = 26;

    public String encrypt(String message, int key) {
        return process(message, key);
    }

    public String decrypt(String encryptedMessage, int key) {
        return process(encryptedMessage, -key);
    }

    private String process(String message, int key) {
        StringBuilder result = new StringBuilder();

        for (char ch : message.toCharArray()) {
            if (Character.isUpperCase(ch)) {
                result.append(shift(ch, key, 'A'));
            } else if (Character.isLowerCase(ch)) {
                result.append(shift(ch, key, 'a'));
            } else {
                result.append(ch);
            }
        }

        return result.toString();
    }

    private char shift(char ch, int key, char baseChar) {
        int offset = (ch - baseChar + key + ALPHABET_SIZE) % ALPHABET_SIZE;
        return (char) (baseChar + offset);
    }
}
```
По формуле не оч вдавалась, мб не всё учтено и корректно, проверила на каких-то разных значениях и ок. Но суть просто в том, что общая может быть

2024-08-26 20:22 UTC, Sabina-Vishnya commented on src/main/java/faang/school/godbless/droids/Droid.java
> +    public String receiveEncryptedMessage(String encryptedMessage, int key) {
1 - шифр цезаря должен учитывать и отрицательный сдвиг, тут не учитывается и формула кривая
такие штуки можно через онлайн генераторы проверять, большинство из них хоть простые проверки покажет нормально
2 - тест кейсов больше должно быть, например:
```
граничные значения 0 и 26
> 26
< 26
аналогичное с отрицательными ключами
символы и цифры
разные регистры
```

3 Код по идее не должен выйти большим, что-то типа такого я бы сделала:
```
@Getter
@Setter
@ToString
@AllArgsConstructor
public class Droid {

    private static final int ALPHABET_SIZE = 26;

    public String encrypt(String message, int key) {
        return process(message, key);
    }

    public String decrypt(String encryptedMessage, int key) {
        return process(encryptedMessage, -key);
    }

    private String process(String message, int key) {
        DroidMessageEncryptor droidMessageEncryptor = (incomingMessage, shift) -> {

            StringBuilder result = new StringBuilder();

            for (char ch : message.toCharArray()) {
                if (Character.isUpperCase(ch)) {
                    result.append(shift(ch, key, 'A'));
                } else if (Character.isLowerCase(ch)) {
                    result.append(shift(ch, key, 'a'));
                } else {
                    result.append(ch);
                }
            }

            return result.toString();
        };
        
        return droidMessageEncryptor.encryptDecryptMessage(message, key);
    }

    private char shift(char ch, int key, char baseChar) {
        int offset = (ch - baseChar + key + ALPHABET_SIZE) % ALPHABET_SIZE;
        return (char) (baseChar + offset);
    }
}

```
По формуле не оч вдавалась, мб не всё учтено и корректно, проверила на каких-то разных значениях и ок. Но суть просто в том, что общая может быть

2024-08-26 20:26 UTC, Sabina-Vishnya commented
@GusevVrn поправь просто и вливай, тут по идее уже всё написано по коду (это если не заморачиваться) и косметические правки нужны лишь 
задачку в done кину, тк закрывать хотели стримы уже, но если захочешь еще раз ревьюшку, то скидывай в дс прям тогда

2024-08-27 07:25 UTC, merged