Накормите Питера Гриффина
CorporationX/god_bless pull request #9456
Opened 2024-08-18 15:10 UTC by fragmatik-top

2024-08-24 00:37 UTC, pablo023 requested changes

2024-08-24 00:37 UTC, pablo023 commented on src/main/java/com/multithreading/griffin/FoodDeliveryTask.java
> +        }
https://www.baeldung.com/java-interrupted-exception

2024-08-24 00:37 UTC, pablo023 commented on src/main/java/com/multithreading/griffin/GriffinsFoodDelivery.java
> +}
Забыл блок с awaitTermination

2024-08-25 14:49 UTC, mikhailov26 approved these changes

2024-08-25 14:49 UTC, merged