BJS2-23575-microsoft
CorporationX/god_bless pull request #9469
Opened 2024-08-18 17:27 UTC by StepnovaVarvara

2024-08-22 01:58 UTC, Sabina-Vishnya commented on src/main/java/faang/school/godbless/microsoft/MailSender.java
> +        for (int i = 0; i < THREAD_COUNT; i++) {
Это неверно. Тут последовательное исполнение, а не параллельное, тебе нужно одновременно или почти одновременно запустить потоки, а сейчас основной поток-мейн будет ждать завершения текущего потока
подробнее: https://www.baeldung.com/java-thread-join

2024-08-22 03:46 UTC, StepnovaVarvara commented on src/main/java/faang/school/godbless/microsoft/MailSender.java
> +        for (int i = 0; i < THREAD_COUNT; i++) {
Да, чет я вообще какой-то бред написала. Щас сделала отдельно создание, запуск и приостановку. Погоди, тогда у меня с join всегда потоки попорядку будут выполняться

2024-08-24 02:05 UTC, pablo023 requested changes

2024-08-24 02:05 UTC, pablo023 commented on src/main/java/faang/school/godbless/microsoft/SenderRunnable.java
> +    private Thread thread;
В этом проблема, нужно убрать

2024-08-24 02:05 UTC, pablo023 commented on src/main/java/faang/school/godbless/microsoft/MailSender.java
> +            int startIndex = i * MESSAGES_PART + 1;
Нулевой индекс никогда не будет обработан

2024-08-25 00:01 UTC, Sabina-Vishnya commented on src/main/java/faang/school/godbless/microsoft/MailSender.java
> +            threads.add(new Thread(() -> new SenderRunnable(startIndex, endIndex)));
зачем тут лямбда? у тебя ведь так run не вызовется никогда
советую код перед ревью проверять, тем более если пока без этого неочевидно

2024-08-25 07:48 UTC, merged