BJS2-23934 Накормите Питера Гриффина
CorporationX/god_bless pull request #9510
Opened 2024-08-19 08:50 UTC by cemeh666

2024-08-19 19:38 UTC, 20cognosce requested changes

2024-08-19 19:38 UTC, 20cognosce commented on src/main/java/feed/peter/griffin/GriffinsFoodDelivery.java
> +        executor.close();
Это на какой версии джавы такой метод есть у экзекьютора?

2024-08-20 07:22 UTC, cemeh666 commented on src/main/java/feed/peter/griffin/GriffinsFoodDelivery.java
> +        executor.close();
на 19. сменил SDK на 17. переделал

2024-08-20 16:23 UTC, 20cognosce approved these changes

2024-08-20 16:23 UTC, merged