BJS2-23410   Распределенная армия героев меча и магии
CorporationX/god_bless pull request #9511
Opened 2024-08-19 09:10 UTC by ilu23ilu23

2024-08-20 17:39 UTC, 20cognosce requested changes

2024-08-20 17:39 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23410/Army.java
> +        }
стримы, forEach

2024-08-20 17:39 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23410/Army.java
> +            Thread thread = new Thread(() -> totalPower.addAndGet(unit.getPower()));
Когда ты применяешь Atomic - это супер оптимизированная, но блокировка

Тут нет параллельности.

Когда все потоки пишут в одну переменную, по факту в каждый момент времени у тебя будет работать только один поток, а все остальные - ждать когда он отпустит totalPower

2024-08-25 08:04 UTC, ilu23ilu23 commented on src/main/java/faang/school/godbless/BJS2_23410/Army.java
> +        }
ок

2024-08-25 08:04 UTC, ilu23ilu23 commented on src/main/java/faang/school/godbless/BJS2_23410/Army.java
> +            Thread thread = new Thread(() -> totalPower.addAndGet(unit.getPower()));
ок

2024-08-25 12:42 UTC, 20cognosce requested changes

2024-08-25 12:42 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23410/Army.java
> +    }
Перегруженный метод, он должен быть в два раза короче

2024-08-25 12:42 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23410/Army.java
> +                .collect(Collectors.groupingBy(Unit::getClass));
Вот это почему нельзя было сделать в addUnit сразу

2024-08-25 12:42 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23410/Army.java
> +        Map<Class<? extends Unit>, AtomicInteger> powerByType = new HashMap<>();
Вот это почему создается только в этом методе, почему не как поля класса

2024-08-25 12:42 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23410/Army.java
> +        for (Map.Entry<Class<? extends Unit>, List<Unit>> entry : unitsByType.entrySet()) {
entrySet().forEach()

2024-08-25 12:42 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23410/Army.java
> +        }
forEach, отдельный метод

2024-08-25 12:42 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23410/Army.java
> +                for (Unit unit : entry.getValue()) {
forEach

2024-08-25 12:42 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23410/Army.java
> +                    totalPower.addAndGet(unit.getPower());
ВОПРОС
Если у тебя один поток на один entry
Один поток считает сумму сил по списку только своих юнитов
И результат только один поток пишет каждый в свою переменную

Зачем тебе атомик? У тебя за totalPower нет конкуренции, у каждого потока своя единственная totalPower

2024-08-27 09:07 UTC, 20cognosce requested changes

2024-08-27 09:07 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23410/Army.java
> +        return armyList.parallelStream()
Чтоооо, а где весь код из прошлого ревью? Ты чего всё удалил и не доделал?
Это не решение.

2024-08-27 12:03 UTC, 20cognosce requested changes

2024-08-27 12:03 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23410/Army.java
> +        }
forEach
несколько потоков пишут в одну не потокобезопасную переменную

Почему отдельный поток на каждую сущность, если должен быть один на несколько сущностей одного класса

2024-08-28 16:36 UTC, 20cognosce approved these changes
Теперь ошибок нет

2024-08-28 16:36 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23410/Army.java
> +                    totalPower.addAndGet(typePower);
Это не надо сразу делать, можно после join
И атомик тебе тогда вообще не понадобится

2024-08-28 16:36 UTC, merged