nf BJS2-22863 vacancy analyzer added
CorporationX/god_bless pull request #9512
Opened 2024-08-19 09:20 UTC by Rashit86

2024-08-23 19:40 UTC, pablo023 requested changes
Не нужно в одну гусеницу засовывать все операции, которые нужно сделать. Разбивай на шаги, чтобы это было легко читать.

2024-08-23 19:40 UTC, pablo023 commented on src/main/java/faang/school/godbless/vacancy/analyzer/DataAnalyzer.java
> +                .collect(Collectors.groupingBy(Function.identity(), Collectors.counting()))
Вот это вот можно вынести в первый шаг

2024-08-23 19:40 UTC, pablo023 commented on src/main/java/faang/school/godbless/vacancy/analyzer/DataAnalyzer.java
> +                .sorted(Map.Entry.<String, Long>comparingByValue().reversed())
Вот это во второй

2024-08-23 19:40 UTC, pablo023 commented on src/main/java/faang/school/godbless/vacancy/analyzer/DataAnalyzer.java
> +                .toList();
Вот это в третий.

2024-08-26 07:04 UTC, Rashit86 commented
Я разбил по количеству терминальных операций, т.е на две части. Получилось что длина самого длина стрима 5 строк (строки типа map.entrySet().stream() оформил одной строкой), читается легко. На три стрима не стал разбивать, чтоб не захламлять лишний раз память и не добавлять еще одну терминальную операцию, т.е не грузить процессор лишний раз

2024-08-26 15:32 UTC, mikhailov26 approved these changes

2024-08-26 15:33 UTC, merged