BJS2-23392 Распределенная армия героев меча и магии
CorporationX/god_bless pull request #9543
Opened 2024-08-19 14:34 UTC by cemeh666

2024-08-20 17:12 UTC, 20cognosce requested changes

2024-08-20 17:12 UTC, 20cognosce commented on src/main/java/stream/api1/Main.java
Что это делает в ПРе

2024-08-20 17:12 UTC, 20cognosce commented on src/main/java/stream/api2/Main.java
> +        char targetChar = 'A';
И это

2024-08-20 17:12 UTC, 20cognosce commented on src/main/java/army/of/heroes/of/might/and/magic/Army.java
> +        if(creature == null) {
Ctrl + Alt + L

2024-08-20 17:12 UTC, 20cognosce commented on src/main/java/army/of/heroes/of/might/and/magic/Army.java
> +        if(creature == null) {
Используй Optional

2024-08-20 17:12 UTC, 20cognosce commented on src/main/java/army/of/heroes/of/might/and/magic/Army.java
> +        return this.threads.stream().mapToInt(CustomThread::getTotalPower).sum();
Не пиши в одну строчку

2024-08-20 17:12 UTC, 20cognosce commented on src/main/java/army/of/heroes/of/might/and/magic/Army.java
> +        return this.threads.stream().mapToInt(CustomThread::getTotalPower).sum();
Ты не дождался выполнения всех потоков, а сразу пошел собирать результат
Попробуй добавить sleep(2000) до присвоения totalPower в run метод и увидишь, что получится

2024-08-20 17:50 UTC, cemeh666 commented on src/main/java/army/of/heroes/of/might/and/magic/Army.java
> +        if(creature == null) {
поменял

2024-08-20 17:51 UTC, cemeh666 commented on src/main/java/army/of/heroes/of/might/and/magic/Army.java
> +        return this.threads.stream().mapToInt(CustomThread::getTotalPower).sum();
добавил join
при добавлении **sleep(2000)** никакого изменения (перезапускал раз 10)

2024-08-20 18:18 UTC, 20cognosce commented on src/main/java/army/of/heroes/of/might/and/magic/Army.java
> +        return this.threads.stream().mapToInt(CustomThread::getTotalPower).sum();
> добавил join при добавлении **sleep(2000)** никакого изменения (перезапускал раз 10)

Сначала sleep, а потом присвоение делал?
Нужен дебаг, но вообще, если не дожидаться завершения потока - можно получить сайд эффект, что обращаешься к полю, которое еще не было посчитано.

2024-08-20 18:28 UTC, 20cognosce commented on src/main/java/army/of/heroes/of/might/and/magic/Army.java
> +        return this.threads.stream().mapToInt(CustomThread::getTotalPower).sum();
@cemeh666 Ты используй метод start(), который рекомендуется, а не run() у CustomThread
Ты заоверрайдил метод run(), он не запускает параллельное исполнение потока, а просто логику внутри себя исполняет

2024-08-20 18:29 UTC, 20cognosce commented on src/main/java/army/of/heroes/of/might/and/magic/Army.java
> +        return this.threads.stream().mapToInt(CustomThread::getTotalPower).sum();
![image](https://github.com/user-attachments/assets/f3c6e69c-7197-456b-a5b2-5577e8f8b812)
Вот, о чем я и говорил
Он не дожидается sleep() каждого из потоков, а сразу отдает недосчитанную силу в размере 0

2024-08-20 18:31 UTC, 20cognosce requested changes

2024-08-20 18:31 UTC, 20cognosce commented on src/main/java/army/of/heroes/of/might/and/magic/Army.java
> +        this.threads.forEach(CustomThread::run);
Написал тебе в диалоге к прошлому ревью, вызов run - некорректно

2024-08-21 07:22 UTC, cemeh666 commented on src/main/java/army/of/heroes/of/might/and/magic/Army.java
> +        this.threads.forEach(CustomThread::run);
да. ты прав. при запуске run а не start. выполнение происходить последовательно!

2024-08-21 17:44 UTC, 20cognosce approved these changes

2024-08-21 17:44 UTC, 20cognosce commented on src/main/java/army/of/heroes/of/might/and/magic/Army.java
> +        return this.threads
```
return this.threads.stream()
    .map()
    .sum()
```

2024-08-21 17:44 UTC, 20cognosce commented on src/main/java/army/of/heroes/of/might/and/magic/CustomThread.java
> +    private AtomicInteger totalPower;
В данной реализации это избыточно, у тебя же только 1 поток работает только с одним объектов, и соответственно только с 1 этой переменной

2024-08-21 17:44 UTC, merged