BJS2-23881 Путь пальцем проложи
CorporationX/god_bless pull request #9555
Opened 2024-08-19 16:16 UTC by ostermal7

2024-08-23 23:51 UTC, pablo023 requested changes
Когда стрим не читается - в нем нет смысла, нужно переделать.

2024-08-23 23:51 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_23881/CityWorker.java
> +    }
Нет смысла писать это через стрим. Это же непонятно, сложно читать, сложно понимать. Какой тогда в этом смысл, по сравнению с циклом?

2024-08-23 23:51 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_23881/CityWorker.java
> +        return journeyDistance * 50;
А что это за 50?

2024-08-24 08:23 UTC, ostermal7 commented on src/main/java/faang/school/godbless/BJS2_23881/CityWorker.java
> +    }
Вынес расчет в отдельный метод для лучшей читаемости. Но, как мне кажется, 3 строчки стрима приятнее выглядят, чем циклы с вот этим прыганьем по переменным
    if (distance < minDistance) {
        minDistance = distance;
        closestMonster = monster;
    }

2024-08-24 08:26 UTC, ostermal7 commented on src/main/java/faang/school/godbless/BJS2_23881/CityWorker.java
> +        return journeyDistance * 50;
Хотел дорогу чутка более долгой сделать, чтобы не мгновенные были убийства)

2024-08-25 07:44 UTC, merged