BJS2-23658 done
CorporationX/god_bless pull request #9566
Opened 2024-08-19 17:17 UTC by DenysDovgan

2024-08-23 23:31 UTC, pablo023 requested changes
Есть ошибка в логике формирования батчей.

2024-08-23 23:31 UTC, pablo023 commented on src/main/java/faang/school/godbless/sprint3/BJS2_23658/MailSender.java
> +            int startIndex = i * mailsPerThread + 1;
Индекс под номером 0 никогда не будет обработан.

2024-08-23 23:31 UTC, pablo023 commented on src/main/java/faang/school/godbless/sprint3/BJS2_23658/MailSender.java
> +        int totalMails = 800;
В очереди их 1'000 по условию задачи, не 800.

2024-08-28 09:35 UTC, mikhailov26 approved these changes

2024-08-28 09:35 UTC, merged