Путь пальцем проложи…
CorporationX/god_bless pull request #9574
Opened 2024-08-19 18:21 UTC by fragmatik-top

2024-08-23 23:56 UTC, pablo023 requested changes
Надо бы сделать почище это дело.

2024-08-23 23:56 UTC, pablo023 commented on src/main/java/com/multithreading/witcher/CityWorker.java
> +    }
Длинные стримы тяжело читать, и понимать - что тут произойдет. Такое лучше написать циклом. Можешь в командный чат скинуть скрин вот этого, и того же самого, написанного циклом, и спросить у ребят - что быстрее понять из этого они смогут

2024-08-23 23:56 UTC, pablo023 commented on src/main/java/com/multithreading/witcher/CityWorker.java
> +        return 5;
Почему 5?

2024-08-23 23:56 UTC, pablo023 commented on src/main/java/com/multithreading/witcher/CityWorker.java
> +        }
https://www.baeldung.com/java-interrupted-exception

2024-08-25 14:46 UTC, mikhailov26 approved these changes

2024-08-25 14:47 UTC, merged