BJS2-23669 - Вы работаете в Microsoft!
CorporationX/god_bless pull request #9578
Opened 2024-08-19 18:55 UTC by evgenywork

2024-08-19 18:58 UTC, 20cognosce requested changes

2024-08-19 18:58 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/three/microsoft/MailSender.java
> +                thread.join();
Нет.
Ты сразу запустил поток, сразу Main дождался его исполнения, и ты пошел на следующую итерацию.

Нужно сделать так, чтобы ты все потоки с разной длительностью исполнения одновременно запустил.

Затем Main-поток всех их сджоинил, и только тогда твой Main-поток будет ждать исполнения самого долгого потока, и после этого чет вывести, что все письма отправлены.

https://www.baeldung.com/java-thread-join

When we invoke the join() method on a thread, the calling thread goes into a waiting state. It remains in a waiting state until the referenced thread terminates.

2024-08-19 18:58 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/three/microsoft/MailSender.java
> +            end = start + batchMails;
Разбиение на порции и понятнее распиши

2024-08-20 12:57 UTC, evgenywork commented on src/main/java/faang/school/godbless/sprint/three/microsoft/MailSender.java
> +                thread.join();
Понял ошибку , я запустил все последовательно

2024-08-20 16:20 UTC, 20cognosce approved these changes
Good

2024-08-20 16:20 UTC, merged