Распределенная армия героев меча и магии BJS2-23416
CorporationX/god_bless pull request #9610
Opened 2024-08-20 08:06 UTC by vestmen

2024-08-20 17:52 UTC, 20cognosce requested changes
По многопоточке применение join - корректно, но общая логика программы требует доработки
1. Раздели сборку и сортировку юнитов одним этапом
2. Созданием потоков вторым этапом
3. Одновременный запуск по одному потоку на каждый тип героя
4. Каждый один поток должен посчитать сумму сил всех его геров, НЕ ХРАНИТЬ СИЛУ ПОЛЕМ ВНУТРИ ПОТОКА
5. Дождаться выполнения всех потоков
6. Просуммировать финальные силы всех потоков

2024-08-20 17:52 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint3/armyHeroes/Unit.java
> +    }
boilerplate код

2024-08-20 17:52 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint3/armyHeroes/Unit.java
> +    }
ломбок

2024-08-20 17:52 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint3/armyHeroes/Army.java
> +        for (Unit unit : unitThreadsMap.keySet()) {
forEach

2024-08-20 17:52 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint3/armyHeroes/Army.java
> +    public void calculateUnitsPower() throws InterruptedException {
Почему два одинаковых имени у методов, это путает

2024-08-20 17:52 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint3/armyHeroes/Army.java
> +        for (UnitThread unitThread : unitThreadsMap.get(unit)) {
Не пиши циклами for

2024-08-20 17:52 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint3/armyHeroes/Army.java
> +        unitThread.start();
Почему у тебя поток запускается для каждого отдельного юнита, если ты даже разбил их на отряды по типу

2024-08-21 08:28 UTC, vestmen commented on src/main/java/faang/school/godbless/sprint3/armyHeroes/Unit.java
> +    }
хорошо

2024-08-21 08:28 UTC, vestmen commented on src/main/java/faang/school/godbless/sprint3/armyHeroes/Army.java
> +        for (UnitThread unitThread : unitThreadsMap.get(unit)) {
писал через цикл потому что при использовании stream api обязательно нужно использовать try catch, а если через цикл for, то можно исключение вынести в сигнатуру метода

2024-08-22 18:22 UTC, 20cognosce approved these changes

2024-08-22 18:22 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint3/armyHeroes/Swordsman.java
> +        setName("Swordsman");
1. Почему сразу в конструкторе не передавать
2. Мне не нравится что ты руками задаешь имя класса
Есть метод, getClass

2024-08-22 18:22 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint3/armyHeroes/Army.java
> +            UnitThread unitThread = new UnitThread(value);
Я не сразу понял, что value - это список
нужно понятнее имена присваивать...

2024-08-22 18:22 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint3/armyHeroes/Army.java
> +                .sum();
Вот это декомпозировать и по красоте сделать
А по логике многопоточки всё правильно, огонь!

2024-08-22 18:22 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint3/armyHeroes/Army.java
> +                .stream()
Можно IntStream использовать вроде, короче выйдет суммирование

2024-08-22 18:23 UTC, merged