Mice are very nice!
CorporationX/god_bless pull request #9635
Opened 2024-08-20 12:43 UTC by Silencemess1ah

2024-08-24 02:08 UTC, pablo023 requested changes
Исправь то, что отметил, и почисть код

2024-08-24 02:08 UTC, pablo023 commented on src/main/java/BJS2_23820_MiceAreVeryNice/House.java
> +        }
Это не совсем корректная обработка этого типа исключения. Вот тут почитай, пожалуйста, как это делать правильно https://www.baeldung.com/java-interrupted-exception

2024-08-24 02:08 UTC, pablo023 commented on src/main/java/BJS2_23820_MiceAreVeryNice/House.java
> +            delay += 30;
Зачем мы это делаем тут?

2024-08-24 02:08 UTC, pablo023 commented on src/main/java/BJS2_23820_MiceAreVeryNice/House.java
> +                    System.out.println("All food have been collected and room " + room.getRoomName() + " is clear!");
Тяжело читать, много лишнего выводишь в консоль.

2024-08-25 07:29 UTC, Silencemess1ah commented on src/main/java/BJS2_23820_MiceAreVeryNice/House.java
> +            delay += 30;
Не много не понял к чему вопрос? По условию запустить пять потоков с интервалом в 30 секунд, изначально задержка ноль и дальше каждые 30 секунд будет запускаться новый поток который обходит комнаты

2024-08-25 07:48 UTC, merged