BJS2-23457 done
CorporationX/god_bless pull request #9641
Opened 2024-08-20 13:25 UTC by DenysDovgan

2024-08-23 23:21 UTC, pablo023 requested changes

2024-08-23 23:21 UTC, pablo023 commented on src/main/java/faang/school/godbless/sprint3/BJS2_23457/Knight.java
> +        } catch (Exception e) {
Нет, так не подойдет. Не надо ловить просто Excetion, лови конкретные, которые могут произойти. В данном случае - InterruptedException.

2024-08-23 23:21 UTC, pablo023 commented on src/main/java/faang/school/godbless/sprint3/BJS2_23457/Knight.java
> +            e.printStackTrace();
И так тоже не подойдет. По уму это делается так - ты кидаешь тут исключение какое-то, которое соответствует проблеме, и логируешь это дополнительно. Погугли, и начни использовать Slf4j аннотацию.

2024-08-28 09:24 UTC, mikhailov26 approved these changes

2024-08-28 09:24 UTC, merged