Mktlamer bjs2 23755
CorporationX/god_bless pull request #9657
Opened 2024-08-20 14:54 UTC by mktlamer

2024-08-23 23:48 UTC, pablo023 requested changes
Учимся писать не только рабочий, но и опрятный, красивый код.

2024-08-23 23:48 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_23755/House.java
> +            executor.schedule(house::collectFood, 30 * (i + 1), TimeUnit.SECONDS);
А что это за 30? Такое надо выносить в поля, вполне возможно - в константы.

2024-08-23 23:48 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_23755/House.java
> +            executor.schedule(house::collectFood, 30 * (i + 1), TimeUnit.SECONDS);
(я знаю что это за 30, но не пиши так, это антипаттерн магическое число)

2024-08-23 23:48 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_23755/House.java
> +        }
Вот так оно должно обрабатываться: https://www.baeldung.com/java-interrupted-exception

2024-08-23 23:48 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_23755/House.java
> +                )
Что она тут делает?

2024-08-24 11:26 UTC, mktlamer commented on src/main/java/faang/school/godbless/BJS2_23755/House.java
> +                )
Не совсем понял вопрос. Метод идет по списку комнат, отбрасывает пустые комнаты, берет всю еду из первых двух комнат и кладет в List

2024-08-25 07:44 UTC, merged