BJS2-24116 - The Big Bang Theory
CorporationX/god_bless pull request #9664
Opened 2024-08-20 17:08 UTC by GusevVrn

2024-08-24 02:20 UTC, pablo023 requested changes

2024-08-24 02:20 UTC, pablo023 commented on src/main/java/faang/school/godbless/bigBangTheory/Task.java
> +        }
Это не совсем корректная обработка этого типа исключения. Вот тут почитай, пожалуйста, как это делать правильно https://www.baeldung.com/java-interrupted-exception

2024-08-24 02:20 UTC, pablo023 commented on src/main/java/faang/school/godbless/bigBangTheory/BigBangTheory.java
> +            executorService.shutdownNow();
Почему shutdownNow? Разберись с тем, как он работает, и что у тебя тут произойдет из-за него. И также почитай про блок awaitTermination.

2024-08-25 12:48 UTC, GusevVrn commented on src/main/java/faang/school/godbless/bigBangTheory/Task.java
> +        }
Переделал

2024-08-25 12:49 UTC, GusevVrn commented on src/main/java/faang/school/godbless/bigBangTheory/BigBangTheory.java
> +            executorService.shutdownNow();
Я хотел явно отобразить пункт В случае прерывания задачи, вывести сообщение об этом и завершить выполнение метода.

2024-08-25 17:45 UTC, Sabina-Vishnya approved these changes

2024-08-25 19:38 UTC, merged