BJS2-23780   Mice are very nice!
CorporationX/god_bless pull request #9710
Opened 2024-08-21 06:55 UTC by ilu23ilu23

2024-08-24 19:40 UTC, 20cognosce requested changes

2024-08-24 19:40 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23780/Main.java
> +                        + rooms.get(index).getName() + " и " + rooms.get(index + 1).getName());
Что это за ужас...

2024-08-24 19:40 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23780/House.java
> +    }
Не принимается. Сделай параллельное выполнение задач без каких-либо блокировок. 
Поток собирает еду только в своих комнатах, зачем ему блокироваться и ждать, если другой еще не собрал в своих?

Заранее распредели комнаты и списки собранных блюд для каждого потока, они не должны никак пересекаться, это позволить избежать блокировок.

В конце, когда все отработают - посчитаешь финальный список собранной еды

2024-08-24 19:40 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23780/Main.java
> +        }, 200, TimeUnit.SECONDS);
Вот это можно убрать из планировщика пожалуйста, этому в нем не место

2024-08-25 13:03 UTC, 20cognosce requested changes

2024-08-25 13:03 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23780/Main.java
> +            if (house.allFoodCollected()) {
сделай тут цикл "пока не собрана" и на rooms блокировку какую-нибудь
И проверку делай с интервалом, не нонстопом дергай её

2024-08-25 13:03 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23780/Main.java
> +            if (house.allFoodCollected()) {
И перед executor пустую строку

2024-08-25 13:03 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23780/Main.java
> +        }, 200, TimeUnit.SECONDS);
Вот это вообще удалить, сделай просто через awaitTermination

2024-08-26 07:22 UTC, ilu23ilu23 commented on src/main/java/faang/school/godbless/BJS2_23780/Main.java
> +        }, 200, TimeUnit.SECONDS);
ok

2024-08-26 07:25 UTC, ilu23ilu23 commented on src/main/java/faang/school/godbless/BJS2_23780/House.java
> +        for (Room room : assignedRooms) {
ок

2024-08-26 07:41 UTC, ilu23ilu23 commented on src/main/java/faang/school/godbless/BJS2_23780/Main.java
> +        House house = new House(rooms);
ок

2024-08-26 07:41 UTC, ilu23ilu23 commented on src/main/java/faang/school/godbless/BJS2_23780/House.java
> +        collectedFood.addAll(localCollectedFood);
ок

2024-08-26 08:00 UTC, ilu23ilu23 commented on src/main/java/faang/school/godbless/BJS2_23780/Main.java
> +            if (house.allFoodCollected()) {
ок

2024-08-26 08:00 UTC, ilu23ilu23 commented on src/main/java/faang/school/godbless/BJS2_23780/Main.java
> +        }, 200, TimeUnit.SECONDS);
ок

2024-08-27 09:43 UTC, 20cognosce requested changes

2024-08-27 09:43 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23780/Main.java
> +            executor.shutdown();
Зачем ты каждые 30 секунд вызываешь shutdown

2024-08-27 09:43 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23780/House.java
> +    private List<Food> collectedFood = Collections.synchronizedList(new ArrayList<>());
Это еще хуже, тут все методы просто жестко синхронизированы

2024-08-27 09:43 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23780/House.java
> +    private CountDownLatch latch;
Зачем он тебе?

2024-08-27 09:43 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23780/House.java
> +        latch = new CountDownLatch(assignedRooms.size());
Ты каждый раз новый создаешь для каждого потока, они смотрят на разные счетчики

2024-08-27 09:43 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23780/House.java
> +                latch.await();
Ну а где у тебя гарантия, что не будет так:
поток 1 нажимает countDown
latch.await() срабатывает, счетчик обнулился
поток 2 нажимает countDown

Ты же тем более с задержкой запускаешь их, так и будет, что все ждут непонятно что

Удаляй это

2024-08-28 16:39 UTC, 20cognosce approved these changes
По многопоточке всё корректно
Использование очереди для хранения - сомнительно, ну окэй

2024-08-28 16:39 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_23780/Main.java
> +        System.out.println("Еда в доме собрана!");
Интересно было бы посмотреть на содержимое ConcurrentLinkedQueue

2024-08-28 16:39 UTC, merged