BJS2-23827 - Mice are very nice!
CorporationX/god_bless pull request #9725
Opened 2024-08-21 09:58 UTC by GusevVrn

2024-08-24 02:10 UTC, pablo023 requested changes

2024-08-24 02:10 UTC, pablo023 commented on src/main/java/faang/school/godbless/tomAndJerry/Room.java
> +    private int lock;
Это для чего здесь?

2024-08-24 02:10 UTC, pablo023 commented on src/main/java/faang/school/godbless/tomAndJerry/Room.java
> +@Data
Зачем тебе дата? Ты не используешь всего, что она генерирует

2024-08-24 02:10 UTC, pablo023 commented on src/main/java/faang/school/godbless/tomAndJerry/House.java
> +                    room.setLock(1);
Что это такое?

2024-08-24 17:51 UTC, GusevVrn commented on src/main/java/faang/school/godbless/tomAndJerry/Room.java
> +    private int lock;
Т.к. этот модуль без синхронизации, попытался сделать какой-то свой аналог синхронизации. Где lock это просто показатель занята ли комната (lock = 1) или пустая (lock=0)

2024-08-24 17:51 UTC, GusevVrn commented on src/main/java/faang/school/godbless/tomAndJerry/Room.java
> +@Data
поправил

2024-08-25 17:44 UTC, Sabina-Vishnya approved these changes

2024-08-25 19:37 UTC, merged