BJS2-23839 Mice are very nice!
CorporationX/god_bless pull request #9728
Opened 2024-08-21 10:34 UTC by cemeh666

2024-08-24 19:32 UTC, 20cognosce requested changes
Синхронизация под запретом в этой задаче, сделай чистую параллельность без блокировок.

2024-08-24 19:32 UTC, 20cognosce commented on src/main/java/mice/are/very/nice/House.java
> +    }
Почему у тебя все потоки синхронизируются на всем списке комнат и на список собранной всеми ими еды

1. Каждый поток собирает еду только в своих комнатах, ему не надо делить список комнат с другими потоками. Разбивай rooms заранее на пары для каждого потока, чтобы не было никакой синхронизации
2. Общий список collectedFood тоже разбивай на подсписки, чтобы у каждого потока был свой
Когда все потоки отработают, тогда подсписки объединишь в один финальный

То что сейчас - это не параллелизм

2024-08-24 19:32 UTC, 20cognosce commented on src/main/java/mice/are/very/nice/House.java
> +            if (room.isEmpty()) {
Вот тут кстати нет синхронизации, это некорректно
Как только ты получил room и отпустил блокировку, до наступления 22 строчки другие потоки уже могли всё изменить в текущем состоянии списка rooms

2024-08-24 19:32 UTC, 20cognosce commented on src/main/java/mice/are/very/nice/House.java
> +            if (room.isEmpty()) {
Да, у тебя еда не добавляется в текущей реализации, но потенциально это баг

2024-08-26 07:34 UTC, cemeh666 commented on src/main/java/mice/are/very/nice/House.java
> +    }
сделал реализацию попроще

2024-08-26 07:34 UTC, cemeh666 commented on src/main/java/mice/are/very/nice/House.java
> +            if (room.isEmpty()) {
сделал реализацию попроще

2024-08-27 09:51 UTC, 20cognosce approved these changes
Так хорошо

2024-08-27 09:51 UTC, 20cognosce commented on src/main/java/mice/are/very/nice/House.java
> +            this.collectedFood.addAll(room.getFoods());
Несколько потоков пишут в collectedFood, нужна потокобезопасная коллекция

2024-08-27 09:51 UTC, merged