BJS2 - 23424 Распределенная армия героев меча и магии
CorporationX/god_bless pull request #9731
Opened 2024-08-21 10:47 UTC by Silencemess1ah

2024-08-24 01:56 UTC, pablo023 requested changes

2024-08-24 01:56 UTC, pablo023 commented on src/main/java/BJS2_23424_HoMM_Multithreading/Army.java
> +            throw new RuntimeException(e);
1) Ты перемешал ответственность тут. addUnit должен просто делать this.units.add(unit). У тебя тут просто всё происходит.

2) Запускать подсчет силы надо в другом методе

3) После запуска сразу джоинишь - неправильно, многопоточки не будет тут, т.к. он сразу будет ждать выполнения после запуска, в итоге выполнение кода вырождается в синхронное исполнение задач.

2024-08-25 17:01 UTC, Sabina-Vishnya commented on src/main/java/BJS2_23424_HoMM_Multithreading/Army.java
> +public class Army {
будет работать, но код сложный и намешано всё подряд по прежнему, можно было бы влить, но давай сделаем по-человечески всё таки и поправим, а то это неполноценно как-то выходит

1 - в мейн метод всю логику не надо было тащить, а просто добавлять юнитов и считать силу с выводом на консоль, пример для мейна прям в тз есть и этого было достаточно
 ```
 Army army = new Army();
army.addUnit(new Archer(25)); // считаем в потоке 1
army.addUnit(new Swordsman(40)); // считаем в потоке 2
army.addUnit(new Mage(50)); // считаем в потоке 3
army.addUnit(new Mage(20)); // считаем в потоке 4

int totalPower = army.calculateTotalPower();
System.out.println("Total army power: " + totalPower);
```
Т.е. надо было создать просто мейн-класс с этим мейн-методом из ТЗ
2 - статиков тут не должно нигде быть кроме сигнатуры главного метода мейн.
3 - ты привязываешься к типам юнитов зачем-то, от чего добавляешь лишнюю логику, а юниты могли бы храниться в одном списке независимо от их типа, тут в принципе нет смысла в таком разделении. В итоге, у тебя убирается эта куча листов и проверка по экземпляру. 

В результате, мейн-метод тебе скинула выше
Основная логика в Army - без статиков, с одним списком и методами add и calculateTotalPower
Также тебе нужен отдельный класс с run методом и получение силы

Разбор этой задачи есть в доп.материалах, если непонятно даже после замечаний, что создавать и как - посмотри.

2024-08-29 22:11 UTC, Sabina-Vishnya commented on src/main/java/BJS2_23424_HoMM_Multithreading/Army.java
> +                powerThread.join();
вызываешь джоин сразу после запуска каждого потока, значит дожидаетесь завершения каждого потока по очереди, а не параллельно.

2024-09-01 08:33 UTC, merged