BJS2-23437 - Распределенная армия героев меча и магии
CorporationX/god_bless pull request #9742
Opened 2024-08-21 12:55 UTC by evgenywork

2024-08-21 18:25 UTC, 20cognosce requested changes

2024-08-21 18:25 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/three/heroes/Army.java
> +        powerThread.start();
Зачем ты сразу запустил, надо создать, сохранить всех
И только потом одновременно все потоки запускать одновременно

2024-08-21 18:25 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/three/heroes/Army.java
> +        String unitType = unit.getClass().getSimpleName();
Можно в мапу сразу класс хранить, не обязательно имя

2024-08-21 18:25 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/three/heroes/Army.java
> +                totalHeroPower.set(totalHeroPower.get() + thread.getPower());
Там есть addAndGet

2024-08-21 18:25 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/three/heroes/Army.java
> +                totalHeroPower.set(totalHeroPower.get() + thread.getPower());
Такое применение Atomic - бесполезно
Ты строчкой выше уже выполнил join, у тебя поток отработал, на join мы стоим и ждем его завершения

Никакой параллельности уже нет, всё посчитано и в power положено

Atomic - когда несколько потоков одновременно в эту одну переменную что-то пишут, она для этого и нужна, чтобы быть атомарной между ними

А вообще в природе даже операция инкремента не атомарна

2024-08-21 18:25 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/three/heroes/Army.java
> +            heroesPower.put(entry.getKey(), totalHeroPower.get());
У тебя атомик просто в цикле функцию обычной переменной выполняет
Ты еще зачем-то создал мапу для хранения промежуточный результатов, когда у тебя **_уже параллельности нет_**

Знаешь, в чем проблема, что у тебя один поток считает одного героя. Тогда нет смысла в распределении. Сделай, чтобы один поток считал всех героев одного класса. 


Сначала все потоки собери
Одновременно запусти, один entry - один поток
Сразу их результаты промежуточные клади в эту мапу

Затем в самом конце делай join() - так ты точно дождешься, что все свои результаты потоки в мапу положили

И просуммируй промежуточные результаты в самом конце

2024-08-22 07:14 UTC, evgenywork commented on src/main/java/faang/school/godbless/sprint/three/heroes/Army.java
> +        powerThread.start();
> Зачем ты сразу запустил, надо создать, сохранить всех И только потом одновременно все потоки запускать одновременно

Что то сильно затупил с этой задачкой

2024-08-22 07:17 UTC, evgenywork commented on src/main/java/faang/school/godbless/sprint/three/heroes/Army.java
> +        String unitType = unit.getClass().getSimpleName();
@20cognosce можешь глянуть пожалуйста класс Unit, так норм ? потомучто , когда я через ломбок переопределял хэшкод и иквелс он автоматом подставлял power и получалась ерунда. Списки не правльно собиралась.

2024-08-22 07:18 UTC, evgenywork commented on src/main/java/faang/school/godbless/sprint/three/heroes/Army.java
> +                totalHeroPower.set(totalHeroPower.get() + thread.getPower());
Спасибо!

2024-08-22 07:21 UTC, evgenywork commented on src/main/java/faang/school/godbless/sprint/three/heroes/Army.java
> +            heroesPower.put(entry.getKey(), totalHeroPower.get());
@20cognosce можешь пожалуйста глянуть , правильно сейчас? и это норм делать два цикла - один под запуск всех потоков , а второй на ожидание их выполнения или как то можно более изящно сделать?

2024-08-22 07:22 UTC, evgenywork commented on src/main/java/faang/school/godbless/sprint/three/heroes/Army.java
> +            heroesPower.put(entry.getKey(), totalHeroPower.get());
и подход со второй мапой , которая в качестве значения содержит AtomicInteger это норм подход?

2024-08-22 18:15 UTC, 20cognosce requested changes
Так многопоточка типо работать будет, но из-за косяков не по многопоточке надо переделать

а заодно и многопоточку до ума доведи

2024-08-22 18:15 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/three/heroes/Unit.java
> +    }
То есть ты считаешь, что все объекты этого класса равно между собой?
Сильное заявление

2024-08-22 18:15 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/three/heroes/Army.java
> +        unitsMap.computeIfAbsent(unit, k -> new ArrayList<>()).add(powerThread);
Опять таки, что говорил на дейли, я хотел увидеть не один поток на каждого юнита, а один поток на один класс юнитов

2024-08-22 18:15 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/three/heroes/PowerThread.java
> +    private int power;
Поскольку у тебя один поток на один объект, то в эту переменную пишет только один поток, так что ОК, что она не Atomic

2024-08-22 18:15 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/three/heroes/Army.java
> +        for (Map.Entry<Unit, List<PowerThread>> entry: unitsMap.entrySet()) {
Так в цикле for итерировать мапу это жесть конечно

2024-08-22 18:15 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/three/heroes/Army.java
> +        for (Map.Entry<Unit, List<PowerThread>> entry: unitsMap.entrySet()) {
forEach хотя бы давай сделаем...

2024-08-22 18:15 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/three/heroes/Army.java
> +                        k -> new AtomicInteger(0)).addAndGet(thread.getPower());
Этот цикл for у тебя выполняется в одном потоке Main.
Ты сделал join, значит твой созданный поток X доработал.
(Ты все эти созданные потоки в однопоточном цикле перебираешь и join'ом дожидаешься каждого, пока он доработает)

И зачем тебе тогда тут Atomic, если никакой конкуренции уже нет, ты каждого дожидаешься и в последовательность выстраиваешь

И так переопределять equals / hashcode чтобы просто put без ручных проверок работал... Такое... А класс теперь поломанный ваще

2024-08-23 17:37 UTC, evgenywork commented
> Так многопоточка типо работать будет, но из-за косяков не по многопоточке надо переделать
> 
> а заодно и многопоточку до ума доведи

@20cognosce Ух , надеюсь я тебя сейчас правильно понял и все пофиксил

2024-08-23 17:47 UTC, 20cognosce requested changes
И вновь продолжается бой

2024-08-23 17:47 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/three/heroes/Swordsman.java
> +@EqualsAndHashCode(callSuper = false)
Ты equals и hashcode переопределяешь по одному полю name,  в котором хранишь имя класса, написанное собственными руками?
Ну это дичь, не трогай вообще hashcode и equals, используй .getClass и всё

2024-08-23 17:47 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/three/heroes/Army.java
> +        unitsMap.computeIfAbsent(unit, k -> new PowerThread()).addUnit(unit);
В ключе должен быть класс, класс как объект .getClass
или его имя через String хотя бы, то что сейчас - это бан

2024-08-23 17:47 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/three/heroes/PowerThread.java
> +    }
Ты тут сделал метод с таким же именем? Чтобы я окончательно запутался))))

2024-08-23 17:47 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/three/heroes/PowerThread.java
> +                .mapToInt(Unit::getPower).sum();
Это окей, один поток - одна обычная переменная
только форматирование поправь, зачем тебе this

2024-08-23 17:47 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/three/heroes/Army.java
> +                allPower.addAndGet(thread.getPower());
Зачем тебе тут атомик, если ты уже в последовательность join()'ом все потоки цикла выстроил

2024-08-24 09:14 UTC, evgenywork commented on src/main/java/faang/school/godbless/sprint/three/heroes/PowerThread.java
> +                .mapToInt(Unit::getPower).sum();
я честно говоря думал , что this обязательно , так как например в пхп или питон будет ошибка.
Ок! больше не буду использовать

2024-08-24 09:18 UTC, evgenywork commented on src/main/java/faang/school/godbless/sprint/three/heroes/Army.java
> +                allPower.addAndGet(thread.getPower());
@20cognosce все понял свою ошибку , спасибо , что подробно объясняешь .
перенес ссылку на АтомикИнт в PowerThread. теперь получаеться , что все потоки пытаются в него записать

2024-08-24 09:20 UTC, evgenywork commented
> И вновь продолжается бой

Ахахаха , надеюсь закончили))

2024-08-24 18:55 UTC, 20cognosce approved these changes

2024-08-24 18:55 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/three/heroes/PowerThread.java
> +                        .mapToInt(Unit::getPower).sum()
Не лепить
Отдельно стрим посчитай, отдельно результат суммируй

2024-08-24 18:55 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/three/heroes/Army.java
> +    private final AtomicInteger allPower = new AtomicInteger(0);
Окэй, ты в каждый поток кладешь коммунальную переменную, но она Atomic - значит потокобезопасна
Непонятно, зачем тебе всем потокам писать в одну переменную

Если каждый может писать только в свою, не атомик, затем мы всех дожидаемся, и все их промежуточные суммы суммируем

2024-08-24 18:55 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint/three/heroes/Army.java
> +    private final AtomicInteger allPower = new AtomicInteger(0);
Текущая реализация корректна, но не оптимальна, потоки можно полностью распараллелить, у них нет привязки к общему объекту
А так ты их блокируешь на запись в эту перемененную allPower, ну ладно
пойдет

2024-08-24 18:55 UTC, merged