microsoft
CorporationX/god_bless pull request #9744
Opened 2024-08-21 13:16 UTC by natalia-dch

2024-08-21 17:20 UTC, 20cognosce requested changes
По логике многопоточки - Ок, но по стилю кода хочу увидеть исправления

2024-08-21 17:20 UTC, 20cognosce commented on src/main/java/faang/school/godbless/microsoft/MailSender.java
> +        }
Где стримы, гдееееее

2024-08-21 17:20 UTC, 20cognosce commented on src/main/java/faang/school/godbless/microsoft/SenderRunnable.java
> +@AllArgsConstructor
Слишком много параметров, конструктор очень раздут
@Builder

2024-08-21 17:20 UTC, 20cognosce commented on src/main/java/faang/school/godbless/microsoft/SenderRunnable.java
> +            System.out.println("sent by " + threadIndex + ":" + messages.get(i));
Тебе не надо передавать поток как параметр, ты вызываешь Thread.currentThread().getName() - типо того, чтобы всегда в этой строчке знать, какой поток её исполняет

2024-08-31 08:43 UTC, natalia-dch commented on src/main/java/faang/school/godbless/microsoft/SenderRunnable.java
> +@AllArgsConstructor
Правильно понимаю, что имеет смысл вообще всегда использовать builder вместо конструктора?

2024-09-01 09:25 UTC, 20cognosce commented on src/main/java/faang/school/godbless/microsoft/SenderRunnable.java
> +@AllArgsConstructor
Если больше 3-х параметров, то да
Но это справедливо только для объектов - сущностей
Для объектов, исполняющих бизнес-логику лучше через конструктор, чтобы если возникнет ошибка в конструкторе, никакие поля не оказались null и при запуске мы бы просто упали

2024-09-01 09:30 UTC, 20cognosce approved these changes

2024-09-01 09:30 UTC, 20cognosce commented on src/main/java/faang/school/godbless/microsoft/MailSender.java
> +        List<String> messages = IntStream.range(0, 1000).mapToObj(i -> "message" + i).toList();
не писать в одну строчку

2024-09-01 09:30 UTC, 20cognosce commented on src/main/java/faang/school/godbless/microsoft/MailSender.java
> +                IntStream.range(0, 5).mapToObj(i -> new Thread(SenderRunnable.builder().startIndex(i * 200).endIndex(i * 200 + 199).messages(messages).build())).toList();
Как ты сама думаешь, это читаемо хоть в какой-то мере?

2024-09-01 09:30 UTC, 20cognosce commented on src/main/java/faang/school/godbless/microsoft/MailSender.java
> +                IntStream.range(0, 5).mapToObj(i -> new Thread(SenderRunnable.builder().startIndex(i * 200).endIndex(i * 200 + 199).messages(messages).build())).toList();
```
List<Thread> threads = IntStream.range(0, 5)
    .mapToObj(i -> new Thread(
        SenderRunnable.builder()
            .startIndex(i * 200)
            .endIndex(i * 200 + 199)
            .messages(messages)
            .build()))
    .toList();
```

Хотя бы так. Если я буду натыкаться на такие строчки - ПР будет отправлен на доработку

2024-09-01 09:31 UTC, merged