Решение задачи Потренируем StreamAPI 2
CorporationX/god_bless pull request #9749
Opened 2024-08-21 13:46 UTC by wmwmaks

2024-08-21 16:13 UTC, mysosnovskaya requested changes

2024-08-21 16:13 UTC, mysosnovskaya commented on src/main/java/streamapi/two/AverageSalary.java
> +                        , Collectors.averagingDouble(Employee::getSalary)));
Запятую надо вернуть на предыдущую строку :)

2024-08-21 16:13 UTC, mysosnovskaya commented on src/main/java/streamapi/two/Palindrome.java
> +    public static IntStream findPalindromeInRange(int start, int end) {
Вернуть нужно список чисел, являющихся палиндромами, а не стрим

2024-08-21 22:21 UTC, wmwmaks commented on src/main/java/streamapi/two/Main.java
> +                .flatMap(i -> integerList.stream()
Мне подсказал Валера в ПП)

2024-08-22 17:54 UTC, mysosnovskaya requested changes

2024-08-22 17:54 UTC, mysosnovskaya commented on src/main/java/streamapi/two/Friends.java
> +                            if (person.compareTo(person2) < 0) {
Предложу улучшение твоей идеи: можно предварительно отфильтровать всех, у кого person.compareTo(person2) < 0. Т.е. если есть пара [1,2] и [2,1], то из нее останется только одна, а вторая пройдет дальше после этого фильтра. Код так будет выглядеть легче

2024-08-22 17:54 UTC, mysosnovskaya commented on src/main/java/streamapi/two/Main.java
> +                .filter(str -> pattern.matcher(str).matches())
Хорошо реализовано 👍

2024-08-24 17:34 UTC, mysosnovskaya approved these changes

2024-08-24 17:34 UTC, merged