big bang
CorporationX/god_bless pull request #9758
Opened 2024-08-21 14:24 UTC by natalia-dch

2024-08-21 19:17 UTC, 20cognosce requested changes

2024-08-21 19:17 UTC, 20cognosce commented on src/main/java/faang/school/godbless/big_bang/BigBangTheory.java
> +    }
8. Когда все задачи будут выполнены, остановить ExecutorService.

Доделай пожалуйста ожидание выполнения всех задач и остановку планировщика

2024-08-31 08:09 UTC, natalia-dch commented on src/main/java/faang/school/godbless/big_bang/BigBangTheory.java
> +    }
«остановка планировщика» — это ведь executor.shutdown, нет?

добавила ожидание выполнения задач через future/get

2024-09-01 09:45 UTC, 20cognosce requested changes

2024-09-01 09:45 UTC, 20cognosce commented on src/main/java/faang/school/godbless/big_bang/BigBangTheory.java
> +    }
Нет.

Почитай доку на методы ExecutorService
shutdown
shutdownNow
awaitTermination

2024-09-01 17:19 UTC, natalia-dch commented on src/main/java/faang/school/godbless/big_bang/BigBangTheory.java
> +    }
Поняла, спасибо! Запишу себе, здесь уже переделовать ничего не буду — дедлайн уже прошёл🙃

2024-09-01 17:19 UTC, closed without merging