Решение задачи Анализ активности пользователей в социальной сети
CorporationX/god_bless pull request #9776
Opened 2024-08-21 16:28 UTC by wmwmaks

2024-08-21 16:29 UTC, wmwmaks commented
Если с помощью Lombook сделать конструктор со всеми аргументами чему будет равно поле this.actionDate?
Я что-то засомневался, что оно будет .now() и решил явно руками сделать.

2024-08-21 16:43 UTC, mysosnovskaya requested changes

2024-08-21 16:43 UTC, mysosnovskaya commented on src/main/java/streamapi/three/Main.java
> +        Map<Integer, Long> userActionsCount = userActions.stream()
Очень хорошо, что вынес эту промежуточную мапу в отдельную переменную 👍 Код становится понятнее)

2024-08-21 16:43 UTC, mysosnovskaya commented on src/main/java/streamapi/three/Main.java
> +                .limit(10)
Такие магические числа лучше выносить в параметры метода. Тогда метод будет более гибким и его можно будет переиспользовать с другими значениями

2024-08-21 16:43 UTC, mysosnovskaya commented on src/main/java/streamapi/three/Main.java
> +                .collect(Collectors.groupingBy(Function.identity(), Collectors.counting()))
Вот тут тоже было бы хорошо промежуточную Map вынести в отдельную локальную переменную

2024-08-21 16:43 UTC, mysosnovskaya commented on src/main/java/streamapi/three/Main.java
> +                .limit(5)
Здесь тоже 5 нужно вынести в параметры метода

2024-08-21 16:43 UTC, mysosnovskaya commented on src/main/java/streamapi/three/Main.java
> +                .flatMap(action -> extractHashtags(action.getContent()).stream())
Эта строчка сложновато выглядит. Может быть продолжить всё в этом стриме? flatMap, в котором split контента происходит, потом filter на startsWith, потом collect. На мой взгляд, так будет проще восприниматься

2024-08-21 16:43 UTC, mysosnovskaya commented on src/main/java/streamapi/three/Main.java
> +        LocalDateTime oneMonthsAgo = LocalDateTime.now().minusMonths(1);
Реализация с minusMonths отличная 👍 Молодец, что применил этот метод

2024-08-21 16:43 UTC, mysosnovskaya commented on src/main/java/streamapi/three/Main.java
> +                .collect(Collectors.groupingBy(UserAction::getUserId,
В отдельную локальную переменную)

2024-08-21 16:43 UTC, mysosnovskaya commented on src/main/java/streamapi/three/Main.java
> +                .limit(3)
В параметры метода

2024-08-21 16:43 UTC, mysosnovskaya commented on src/main/java/streamapi/three/Main.java
> +                .collect(Collectors.groupingBy(UserAction::getActionType,
В отдельную локальную переменную

2024-08-21 16:43 UTC, mysosnovskaya commented on src/main/java/streamapi/three/Main.java
> +                        action -> 100.0 * action.getValue() / userActions.size()
Умножить на 100.0 сразу в числителе - хорошо 👍

2024-08-21 16:43 UTC, mysosnovskaya commented on src/main/java/streamapi/three/UserAction.java
> +    private String actionType;
actionType лучше сделать перечислением, т.к. у этого поля строго ограниченный набор значений

2024-08-21 16:45 UTC, mysosnovskaya commented
> Если с помощью Lombook сделать конструктор со всеми аргументами чему будет равно поле this.actionDate? Я что-то засомневался, что оно будет .now() и решил явно руками сделать.

Да, будет null, но поле можно сделать финальным и явно задать значение:
private final LocalDate actionDate = LocalDate.now(), тогда всё будет корректно

2024-08-22 17:57 UTC, mysosnovskaya approved these changes

2024-08-22 17:57 UTC, merged