BJS2-24174 The Big Bang Theory.
CorporationX/god_bless pull request #9778
Opened 2024-08-21 16:46 UTC by VitoS1C

2024-08-24 00:57 UTC, pablo023 requested changes

2024-08-24 00:57 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_24174/BigBangTheory.java
> +        }
https://www.baeldung.com/java-interrupted-exception

2024-08-24 00:57 UTC, pablo023 commented on src/main/java/faang/school/godbless/BJS2_24174/Task.java
> +            return;
Нужно не ретурн тут, а кидать исключение

2024-08-24 15:47 UTC, VitoS1C commented on src/main/java/faang/school/godbless/BJS2_24174/BigBangTheory.java
> +        }
Правильно ли я понял, что тут нужно пробрасывать исключение дальше?

````java
public static void main(String[] args) throws InterruptedException

2024-08-24 15:49 UTC, VitoS1C commented on src/main/java/faang/school/godbless/BJS2_24174/Task.java
> +            return;
А в методе run нужно вот так?

````java
catch (InterruptedException e) {
            System.out.println("Error");
            Thread.currentThread().interrupt();
        }

2024-08-26 14:45 UTC, mikhailov26 approved these changes

2024-08-26 14:45 UTC, merged