Google Photo Sync
CorporationX/god_bless pull request #9784
Opened 2024-08-21 17:05 UTC by SharkB38

Задача Google Photo Sync
https://faang-school.atlassian.net/browse/BJS2-24461

2024-08-21 17:48 UTC, mysosnovskaya requested changes

2024-08-21 17:48 UTC, mysosnovskaya commented on src/main/java/google/photosync/GooglePhotoAutoUploader.java
> +    private boolean serviceWorking = true;
Это поле лучше не вводить, с ним дело обстоит чуть сложнее. В следующем спринте про это будет) Но если интересно, почитай про volatile

2024-08-21 17:48 UTC, mysosnovskaya commented on src/main/java/google/photosync/GooglePhotoAutoUploader.java
> +            synchronized (photosToUpload) {
Лучше всё-таки ввести отдельное поле lock. Так будет очевиднее: есть поле lock, оно явно используется в качестве лока и ни для чего другого. А сейчас совсем не очевидно, что photosToUpload выступает локом. Кто-то из будущих разработчиков может этого не заметить, убрать с поля final и тогда всё сломается)

2024-08-22 01:54 UTC, SharkB38 commented on src/main/java/google/photosync/GooglePhotoAutoUploader.java
> +            synchronized (photosToUpload) {
Разобрался

2024-08-22 18:53 UTC, mysosnovskaya approved these changes

2024-08-22 18:53 UTC, merged