BJS2-23891 done (not sure xd)
CorporationX/god_bless pull request #9790
Opened 2024-08-21 17:54 UTC by DenysDovgan

2024-08-24 00:28 UTC, pablo023 requested changes

2024-08-24 00:28 UTC, pablo023 commented on src/main/java/faang/school/godbless/sprint3/BJS2_23891/CityWorker.java
> +        } catch (IOException e) {
Откуда у тебя тут IOException может взяться, если ты не лезешь никуда вовне из программы?

2024-08-24 00:28 UTC, pablo023 commented on src/main/java/faang/school/godbless/sprint3/BJS2_23891/CityWorker.java
> +    public double getJourneyDistance() throws IOException {
Почему этот метод кидает эксепшен? Откуда он вылететь может?

2024-08-28 09:40 UTC, mikhailov26 approved these changes

2024-08-29 13:44 UTC, merged