BJS2-24154 - Накормите Питера Гриффина
CorporationX/god_bless pull request #9799
Opened 2024-08-21 18:52 UTC by mrkorolev

2024-08-21 19:28 UTC, 20cognosce requested changes

2024-08-21 19:28 UTC, 20cognosce commented on src/main/java/faang/school/godbless/family_guy/FamilyGuyFoodDelivery.java
> +        try {
Почему столько лишнего запихнул в try catch?

2024-08-21 19:28 UTC, 20cognosce commented on src/main/java/faang/school/godbless/family_guy/FamilyGuyFoodDelivery.java
> +                            new FoodDeliveryTask(fmn, ((new Random()).nextInt(5) + 1))
что со скобками?

2024-08-21 19:28 UTC, 20cognosce commented on src/main/java/faang/school/godbless/family_guy/FamilyGuyFoodDelivery.java
> +            executor.awaitTermination(15, TimeUnit.SECONDS);
Ты не дождался завершения, читай доку на этот метод

2024-08-21 19:39 UTC, mrkorolev commented on src/main/java/faang/school/godbless/family_guy/FamilyGuyFoodDelivery.java
> +        try {
Проглядел - дурачок немножко)

2024-08-21 19:39 UTC, mrkorolev commented on src/main/java/faang/school/godbless/family_guy/FamilyGuyFoodDelivery.java
> +                            new FoodDeliveryTask(fmn, ((new Random()).nextInt(5) + 1))
Проглядел - дурачок немножко)

2024-08-22 19:18 UTC, 20cognosce approved these changes

2024-08-22 19:18 UTC, 20cognosce commented on src/main/java/faang/school/godbless/family_guy/FamilyGuyFoodDelivery.java
> +            String[] familyMembersNames = {"Peter", "Lois", "Meg", "Chris", "Stewie", "Brian"};
Поля класса

2024-08-22 19:18 UTC, 20cognosce commented on src/main/java/faang/school/godbless/family_guy/FamilyGuyFoodDelivery.java
> +                while (!executor.awaitTermination(7, TimeUnit.SECONDS)) {
Так уже лучше, но это получается бесконечное ожидание
Ты вечно ждешь отрывками по 7 секунд, собери волю чтобы все-таки прервать цикл, если ты не дождешься

2024-08-22 19:18 UTC, merged

2024-08-24 16:24 UTC, mrkorolev commented on src/main/java/faang/school/godbless/family_guy/FamilyGuyFoodDelivery.java
> +            String[] familyMembersNames = {"Peter", "Lois", "Meg", "Chris", "Stewie", "Brian"};
@20cognosce Не понял, private static final String[] familyMembersNames?

2024-08-24 18:46 UTC, mrkorolev commented on src/main/java/faang/school/godbless/family_guy/FamilyGuyFoodDelivery.java
> +                while (!executor.awaitTermination(7, TimeUnit.SECONDS)) {
@20cognosce 
1) Объявил константу: private static final long TIMEOUT = 6000;
2) Переписал блок try с твоими изменениями. Прости меня если можешь, что я сюда скинул код :) Скажи, оптимально ли это:
           
executor.shutdown();
long startTime = System.currentTimeMillis();
try {
    while (!executor.awaitTermination(3, TimeUnit.SECONDS)) {
        if (System.currentTimeMillis() - startTime > TIMEOUT) {
            System.out.printf("Tasks failed to finish, timeout reached: %d%n", TIMEOUT);
            executor.shutdownNow();
        } else {
            System.out.println("--------- Tasks not finished yet...");
        }
    }
} catch(InterruptedException e) {
    e.printStackTrace();
}
System.out.println("================================================");
System.out.println("Thread pool finished executing!");