Счетчик просмотров Youtube
CorporationX/god_bless pull request #9807
Opened 2024-08-21 21:07 UTC by SharkB38

Задача Счетчик просмотров Youtube
https://faang-school.atlassian.net/browse/BJS2-24294

2024-08-22 19:55 UTC, mysosnovskaya requested changes

2024-08-22 19:55 UTC, mysosnovskaya commented on src/main/java/youtube/VideoManager.java
> +        synchronized (lock) {
Думаю, необязательно было вводить lock в этом случае. Можно было метод отметить как synchronized.
Ты на дейлике спрашивал про блокировку по videoId. В целом это можно организовать и имело бы смысл, если бы нужно было бы повышать производительность кода. Идея хорошая. Если интересно, можешь попробовать сделать, но учти, что использовать в качестве лока просто videoId - идея плохая, т.к. теоретически в методы addView и getViewCount могут быть переданы два одинаковых videoId, но представленные разными строками (разные объекты с разными ссылками, если создавать строки через new). Поэтому нужно придумать более интересный механизм) Предлагаю в качестве факультативной задачки.

2024-08-22 19:55 UTC, mysosnovskaya commented on src/main/java/youtube/Main.java
> +            videoIds.add(sb.toString());
Рекомендую почитать про uuid (часто используется для id). Использовать в Java так:  UUID.randomUUID()

2024-08-22 21:50 UTC, SharkB38 commented on src/main/java/youtube/VideoManager.java
> +        synchronized (lock) {
А с UUID в качестве lock сработает? Сначала подумал сделать метод который возвращает уникальный объект, используя строку с videoId для генерации, но по сути UUID выполняет ту же роль?

2024-08-23 17:55 UTC, mysosnovskaya commented on src/main/java/youtube/VideoManager.java
> +        synchronized (lock) {
Нет, проблема аналогичная использованию String:
synchronized работает по ссылке на объект. Я могу создать два разных объекта UUID с одинаковым значением (например, используя метод UUID.fromString(...), передав туда одинаковую строчку, могу получить сколько угодно физически разных объектов, но имеющих одинаковое значение). Тогда это будет два разных lock с точки зрения synchronized. Поэтому так дело не пойдет =)

2024-08-23 17:55 UTC, mysosnovskaya requested changes

2024-08-23 17:55 UTC, mysosnovskaya commented on src/main/java/youtube/VideoManager.java
> +        synchronized (video.getId()) {
Так не пойдет, отписала в комментарии на твой вопрос)

2024-08-24 02:12 UTC, SharkB38 commented on src/main/java/youtube/VideoManager.java
> +        synchronized (lock) {
Сделал мапу с lock объектами для каждого id, как-будто бы должно сработать?

2024-08-24 18:41 UTC, mysosnovskaya commented on src/main/java/youtube/VideoManager.java
> +        synchronized (lock) {
Да, мне такое решение нравится)

2024-08-24 18:42 UTC, mysosnovskaya approved these changes

2024-08-24 18:42 UTC, merged