Железный трон любой ценой
CorporationX/god_bless pull request #9821
Opened 2024-08-22 01:50 UTC by SharkB38

Задача Железный трон любой ценой
https://faang-school.atlassian.net/browse/BJS2-24088

2024-08-22 19:21 UTC, mysosnovskaya requested changes

2024-08-22 19:21 UTC, mysosnovskaya commented on src/main/java/ironthrone/Main.java
> +            executor.awaitTermination(5, TimeUnit.MINUTES);
Рекомендую почитать про корректную обработку ошибки InterruptedException
https://www.baeldung.com/java-interrupted-exception

2024-08-22 19:21 UTC, mysosnovskaya commented on src/main/java/ironthrone/House.java
> +        availableRoleSlots.put(role, availableRoleSlots.get(role) - 1);
Я бы всё-таки убедилась, что мы здесь в отрицательные значения не уйдем, а то мало ли чего случиться может)

2024-08-22 21:19 UTC, SharkB38 commented on src/main/java/ironthrone/User.java
> +                        house.getLock().wait();
Переписал synchronized на lock, ide подсвечивала предупреждение, что нежелательно делать synchronized на аргумент метода. Так будет правильнее?

2024-08-23 18:17 UTC, mysosnovskaya requested changes

2024-08-23 18:17 UTC, mysosnovskaya commented on src/main/java/ironthrone/User.java
> +                        house.getLock().wait();
Мне кажется, что у такого варианта нарушена логика в плане зависимостей: User зависит от House, House зависит от Lock, при этом User идет мимо House и пользуется его Lock, как будто перепрыгивает через голову. У меня для тебя два варианта:
1. В User сделать поле Object lock и во всех пользователей передавать тот же самый объект, что и в House
2. В House сделать методы synchronized, а в User в качестве лока использовать house

2024-08-24 01:31 UTC, SharkB38 commented on src/main/java/ironthrone/User.java
> +                        house.getLock().wait();
Переделал по второму варианту, но ide не нравится synchronized по параметру метода и по полю которое не является final. В первом варианте тоже будет жаловаться на synchronized по не final полю. Это получается не очень хорошая практика?

2024-08-24 18:04 UTC, mysosnovskaya commented on src/main/java/ironthrone/User.java
> +                        house.getLock().wait();
Да, нужно делать final. Как раз из-за того, что synchronized работает по ссылке, а в случае нефинального поля ссылка в любой момент может измениться.

2024-08-24 18:34 UTC, mysosnovskaya approved these changes

2024-08-24 18:34 UTC, mysosnovskaya commented on src/main/java/ironthrone/User.java
> +        synchronized (house) {
Действительно практика не очень хорошая. Как говорит idea 
`It is very difficult to guarantee correct operation when such synchronization is used.`
Но по заданию дом у пользователя может измениться. Я предлагаю оставить такую синхронизацию на house. На мой взгляд, для выполнения задания этого достаточно) Иначе пришлось бы делать другую структуру кода, противоречащую заданию: оставлять классы-модели User и House, но без методов, наполненных логикой (как сейчас joinHouse или isAnyRoleAvailable), а эти методы переносить в отдельный класс-менеджер. Этот класс отвечал бы за связывание игроков и домов, назначение, хранение и удаление ролей, у него был бы свой механизм блокировки. Тогда можно было бы избежать предупреждений) Но это уже выйдет за рамки задания. А текущий код поставленную задачу решает корректно.

Я поставлю аппрув, отправлю в back to work, мержить не буду, чтобы у тебя была возможность задать ещё вопросы) Если их не будет - можешь самостоятельно смержить и закрыть задачу. Если будут - пиши здесь в комментариях)

2024-08-24 20:16 UTC, merged