BJS2-24398 Блокировка Spotify
CorporationX/god_bless pull request #9826
Opened 2024-08-22 07:38 UTC by vestmen

2024-08-23 18:00 UTC, 20cognosce requested changes

2024-08-23 18:00 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint3/spotify/Music.java
> +        IntStream.rangeClosed(1, 5).forEach(cur -> {
Кто такой cur

2024-08-23 18:00 UTC, 20cognosce commented on src/main/java/faang/school/godbless/sprint3/spotify/Player.java
> +        if (!isPlaying) {
У тебя isPlayng не потокобезопасна, синхронизации для нее никакой нет
И у тебя несколько потоков ее пишут и читают, это бан

2024-08-24 06:20 UTC, vestmen commented on src/main/java/faang/school/godbless/sprint3/spotify/Music.java
> +        IntStream.rangeClosed(1, 5).forEach(cur -> {
Текущий индекс

2024-08-24 18:57 UTC, 20cognosce approved these changes

2024-08-24 18:57 UTC, merged