Решение задачи Анализатор вакансий
CorporationX/god_bless pull request #9832
Opened 2024-08-22 08:54 UTC by wmwmaks

2024-08-22 18:19 UTC, mysosnovskaya requested changes

2024-08-22 18:19 UTC, mysosnovskaya commented on src/main/java/streamapi/four/DataAnalyzer.java
> +                .collect(Collectors.groupingBy(skill -> skill,
Вместо `skill -> skill` можно использовать `Function.identity()`

2024-08-22 18:19 UTC, mysosnovskaya commented on src/main/java/streamapi/four/DataAnalyzer.java
> +        Map<String, Long> skillCountMap = jobs.stream()
Молодец, что выделил промежуточную Map в отдельную переменную - так код легче читается и понимается)

2024-08-22 18:19 UTC, mysosnovskaya commented on src/main/java/streamapi/four/DataAnalyzer.java
> +                .sorted(Map.Entry.<String, Long>comparingByValue().reversed())
Эту промежуточную Map тоже было бы хорошо вынести в отдельную переменную, как в первом методе) В двух следующих методах тоже

2024-08-22 18:19 UTC, mysosnovskaya commented on src/main/java/streamapi/four/DataAnalyzer.java
> +        double salaryValue = Double.parseDouble(salary.replaceAll("[^0-9.]", ""));
По-моему, salary сразу нужно сделать double, прям в классе Job)

2024-08-22 18:19 UTC, mysosnovskaya commented on src/main/java/streamapi/four/Job.java
> +    private String salary;
Лучше выбрать тип double

2024-08-22 18:19 UTC, mysosnovskaya commented on src/main/java/streamapi/four/JsonJobScraper.java
> +        return objectMap.readValue(json, Job.class);
Какой результат будет, если json == null или пустой строке? Хорошо было бы предусмотреть обработку таких ситуаций

2024-08-22 18:19 UTC, mysosnovskaya commented on src/main/java/streamapi/four/JobScraper.java
> +    protected ObjectMapper objectMap;
Круто, что вынес objectMapper в отдельное поле 👍

2024-08-22 18:19 UTC, mysosnovskaya commented on src/main/java/streamapi/four/JobScraper.java
> +public abstract class JobScraper {
Интересно, а какие ещё варианты реализации могут быть?) Действительно ли абстрактный класс оправдан? Можешь в комментариях рассказать, как рассуждал и почему решил сделать класс абстрактным

2024-08-24 08:14 UTC, wmwmaks commented on src/main/java/streamapi/four/DataAnalyzer.java
> +                .collect(Collectors.groupingBy(skill -> skill,
Но так тоже будет работать же? В таких ситуациях принято использовать Function.identity()?

2024-08-24 08:15 UTC, wmwmaks commented on src/main/java/streamapi/four/DataAnalyzer.java
> +                .sorted(Map.Entry.<String, Long>comparingByValue().reversed())
От чего это зависит? Это делается не для того, чтобы разделить большой длинный код? Просто хорошая практика промежуточные мапы выносить в отдельные переменные?

2024-08-24 08:25 UTC, wmwmaks commented on src/main/java/streamapi/four/JobScraper.java
> +public abstract class JobScraper {
В задании указано, что это "Базовый класс для парсеров". Я прочитал так, что он должен быть общим для разных реализаций. Интерфейс тут не подошел бы, а абстрактный класс, кажется, да.
У меня такая реализация, потому что у нас в проекте "implementation("com.fasterxml.jackson.core:jackson-databind:2.14.2")". Я не очень разбираюсь в парсерах, поэтому загуглил. И получается, что, если добавить в проект другие библиотеки, то можно написать и другие реализации. И еще есть ручной парсинг, как вариант.

2024-08-24 08:35 UTC, wmwmaks commented on src/main/java/streamapi/four/JsonJobScraper.java
> +        return objectMap.readValue(json, Job.class);
Лучше вручную обрабатывать json == null или лучше использовать @NonNull в аргументе метода?

2024-08-24 17:35 UTC, mysosnovskaya commented on src/main/java/streamapi/four/DataAnalyzer.java
> +                .collect(Collectors.groupingBy(skill -> skill,
Да, работать будет, конечно. Обычно используют Function.identity() :)

2024-08-24 17:36 UTC, mysosnovskaya commented on src/main/java/streamapi/four/DataAnalyzer.java
> +                .sorted(Map.Entry.<String, Long>comparingByValue().reversed())
Для удобства чтения. И по типу переменной будет сразу видно, что в мапе находится (какой ключ, какое значение). Сейчас приходится глазами искать collect и разбираться, почему что же там к чему)

2024-08-24 17:43 UTC, mysosnovskaya commented on src/main/java/streamapi/four/JsonJobScraper.java
> +        return objectMap.readValue(json, Job.class);
Зависит от того, как ты хочешь эту ситуацию обрабатывать. Если хочется проверить на null **и на пустоту,** а затем выкинуть какое-то свое исключение, то тогда нужно вручную. Если подходит NullPointerException (при этом проверяется только на null, а пустую строчку можно), то можно и NonNull оставить. В нашем случае, конечно, только первый вариант из-за проверки на пустоту

2024-08-24 17:44 UTC, mysosnovskaya commented on src/main/java/streamapi/four/JobScraper.java
> +public abstract class JobScraper {
Принято! Действительно есть другие парсеры (например, библиотека gson). Тогда пусть остается так, с абстрактным классом)

2024-08-24 17:45 UTC, mysosnovskaya approved these changes

2024-08-24 17:45 UTC, merged