BJS2-24084 - Помогите коллеге
CorporationX/god_bless pull request #9849
Opened 2024-08-22 12:06 UTC by mrkorolev

2024-08-22 19:24 UTC, 20cognosce requested changes
Давай доделаешь

2024-08-22 19:24 UTC, 20cognosce commented on src/main/java/faang/school/godbless/help_colleague/Main.java
> +                batch = new ArrayList<>();
clear()
Зачем новый список плодить, а о старом забывать, подумай о garbage collector

2024-08-22 19:24 UTC, 20cognosce commented on src/main/java/faang/school/godbless/help_colleague/Main.java
> +        for(int i = 0; i < people.size(); i++) {
где форматирование, почему банальный for
почему вообще все в один метод слепил?

Сразу красиво привыкать писать

2024-08-22 19:24 UTC, 20cognosce commented on src/main/java/faang/school/godbless/help_colleague/Main.java
> +            while(!executor.awaitTermination(5, TimeUnit.SECONDS)) {
Бесконечное ожидание

2024-08-22 19:24 UTC, 20cognosce commented on src/main/java/faang/school/godbless/help_colleague/Main.java
> +    private static final int BATCH_SIZE = LIST_SIZE / THREADS;
Маловато потоков, проведи бенчмарки
Я ставлю на то, что оптимальнее было бы разделить на 100 потоков по 100 человек

2024-08-22 19:24 UTC, 20cognosce commented on src/main/java/faang/school/godbless/help_colleague/Main.java
> +        for(int i = 0; i < people.size(); i++) {
По условию у тебя всё в main, но не надо так делать, выдели дополнительные методы

2024-08-22 20:01 UTC, mrkorolev commented on src/main/java/faang/school/godbless/help_colleague/Main.java
> +            while(!executor.awaitTermination(5, TimeUnit.SECONDS)) {
@20cognosce Погоди, я вызвал его сразу после shutdown(), теперь он будет периодически вызываться - до тех пор, пока задачи не завершатся. Как только это произойдет - все прекратится, нет разве?

2024-08-23 06:36 UTC, 20cognosce commented on src/main/java/faang/school/godbless/help_colleague/Main.java
> +            while(!executor.awaitTermination(5, TimeUnit.SECONDS)) {
А если не произойдет никогда - ты будешь ждать вечно?

2024-08-25 12:41 UTC, mrkorolev commented on src/main/java/faang/school/godbless/help_colleague/Main.java
> +        for(int i = 0; i < people.size(); i++) {
@20cognosce Спасибо за ревью, не совсем понял про выделение в отдельные методы - ты про подготовку данных? Остальное все вроде стандартное - обработка завершения задач executorService по timeout.

2024-08-25 13:35 UTC, 20cognosce requested changes

2024-08-25 13:35 UTC, 20cognosce commented on src/main/java/faang/school/godbless/help_colleague/Main.java
> +                .toList();
Вот это можно было отдельно сделать и не лепить в кучу

2024-08-25 13:35 UTC, 20cognosce commented on src/main/java/faang/school/godbless/help_colleague/Main.java
> +                batch.clear();
Вот это шедевр
У тебя batch - это ссылка на один и тот же список
Ты в Printer передаешь ccылку на список

И после этого сразу по этой ссылке удаляешь всё, что там лежало

Фантастично, ты это тестировал вообще?)

2024-08-25 13:35 UTC, 20cognosce commented on src/main/java/faang/school/godbless/help_colleague/PersonNamePrinter.java
> +        people.forEach(p -> System.out.println("Person processed: " + p.getName()));
Тут у тебя реально не пустой вывод? Ты удалил всех людей после передачи в принтер

2024-08-25 13:35 UTC, 20cognosce commented on src/main/java/faang/school/godbless/help_colleague/PersonNamePrinter.java
> +        people.forEach(p -> System.out.println("Person processed: " + p.getName()));
![image](https://github.com/user-attachments/assets/928d0701-871c-4cc5-ad51-befc82108284)
![image](https://github.com/user-attachments/assets/11f5c193-2268-4a0f-bde9-7295d237e405)
Ну да, халтура, Никита

2024-08-25 13:39 UTC, mrkorolev commented on src/main/java/faang/school/godbless/help_colleague/Main.java
> +                batch.clear();
Блин, ж0ско тупанул, извиняюсь.

2024-08-25 13:57 UTC, 20cognosce approved these changes

2024-08-25 13:57 UTC, 20cognosce commented on src/main/java/faang/school/godbless/help_colleague/Main.java
> +        });
Почему ты это не декомпозировал епрст

2024-08-25 13:57 UTC, merged