BJS2-24541 Google Photo sync
CorporationX/god_bless pull request #9876
Opened 2024-08-22 14:29 UTC by cemeh666

2024-08-23 19:11 UTC, 20cognosce requested changes
Не доделана логика

2024-08-23 19:11 UTC, 20cognosce commented on src/main/java/google/photo/sync/GooglePhotosAutoUploader.java
> +                lock.wait();
А чего мы ждем-то сразу, грузить надо

2024-08-23 19:11 UTC, 20cognosce commented on src/main/java/google/photo/sync/GooglePhotosAutoUploader.java
> +            while (!Thread.currentThread().isInterrupted()) {
Просто ломаешь свою программу

2024-08-23 19:11 UTC, 20cognosce commented on src/main/java/google/photo/sync/GooglePhotosAutoUploader.java
> +        for (String photo : this.photosToUpload) {
forEach

2024-08-23 19:11 UTC, 20cognosce commented on src/main/java/google/photo/sync/GooglePhotosAutoUploader.java
> +            Thread.sleep(ADD_PHOTO_DELAY);
Сначала sleep, потом notify()

2024-08-23 19:11 UTC, 20cognosce commented on src/main/java/google/photo/sync/GooglePhotosAutoUploader.java
> +            Thread.sleep(ADD_PHOTO_DELAY);
Ты уже отпустил монитор, а твой метод еще типо выполняет что-то

2024-08-23 19:11 UTC, 20cognosce commented on src/main/java/google/photo/sync/Main.java
> +        uploadPhotoThread.join();
зачем дважды?

2024-08-23 19:11 UTC, 20cognosce commented on src/main/java/google/photo/sync/Main.java
> +            uploadPhotoThread.join();
И здесь

2024-08-23 19:11 UTC, 20cognosce commented on src/main/java/google/photo/sync/Main.java
> +        }
Это в загрузчике должно быть
Не надо спать, надо ждать на wait() пока новое фото добавят в список

2024-08-26 08:04 UTC, cemeh666 commented on src/main/java/google/photo/sync/GooglePhotosAutoUploader.java
> +                lock.wait();
исправил

2024-08-26 08:04 UTC, cemeh666 commented on src/main/java/google/photo/sync/GooglePhotosAutoUploader.java
> +            while (!Thread.currentThread().isInterrupted()) {
сделал по другому

2024-08-26 08:04 UTC, cemeh666 commented on src/main/java/google/photo/sync/GooglePhotosAutoUploader.java
> +        for (String photo : this.photosToUpload) {
сделал

2024-08-26 08:05 UTC, cemeh666 commented on src/main/java/google/photo/sync/GooglePhotosAutoUploader.java
> +            Thread.sleep(ADD_PHOTO_DELAY);
поправил

2024-08-26 08:05 UTC, cemeh666 commented on src/main/java/google/photo/sync/Main.java
> +        }
сделал по другому

2024-08-26 08:05 UTC, cemeh666 commented on src/main/java/google/photo/sync/Main.java
> +        uploadPhotoThread.join();
убрал

2024-08-27 09:55 UTC, 20cognosce approved these changes
Ок

2024-08-27 09:55 UTC, merged