BJS2-24560   Google Photo sync
CorporationX/god_bless pull request #9939
Opened 2024-08-23 09:49 UTC by ilu23ilu23

Созданы классы GooglePhotosAutoUploader, Main c с демонстрацией работы программы.

2024-08-23 19:29 UTC, 20cognosce requested changes

2024-08-23 19:29 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_24560/Main.java
> +            addPhotoThread.join();
Смысл это делать если дальше по коду никакой логики нет, итак они до конца отработают

2024-08-23 19:29 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_24560/GooglePhotosAutoUploader.java
> +                    System.out.println("Фото " + photo + " загружено!");
Сначала сделай - потом говори об этом

2024-08-23 19:29 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_24560/GooglePhotosAutoUploader.java
> +            photosToUpload.clear();
А если тут эксепшн

2024-08-23 19:29 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_24560/Main.java
> +            uploadThread.join();
У тебя там бесконечный цикл кстати, чего ты тут ждешь - оно никогда не случится
Либо условие в цикле меняй - либо таймер ожидания ставь

2024-08-25 08:28 UTC, ilu23ilu23 commented on src/main/java/faang/school/godbless/BJS2_24560/Main.java
> +            addPhotoThread.join();
ок

2024-08-25 08:28 UTC, ilu23ilu23 commented on src/main/java/faang/school/godbless/BJS2_24560/GooglePhotosAutoUploader.java
> +                    System.out.println("Фото " + photo + " загружено!");
ок

2024-08-25 08:28 UTC, ilu23ilu23 commented on src/main/java/faang/school/godbless/BJS2_24560/GooglePhotosAutoUploader.java
> +            photosToUpload.clear();
ок

2024-08-25 08:28 UTC, ilu23ilu23 commented on src/main/java/faang/school/godbless/BJS2_24560/Main.java
> +            uploadThread.join();
ок

2024-08-25 13:54 UTC, 20cognosce approved these changes

2024-08-25 13:54 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_24560/GooglePhotosAutoUploader.java
> +                    }
Зачем это тут?

2024-08-25 13:54 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_24560/GooglePhotosAutoUploader.java
> +        synchronized (lock) {
Ты же итак вызываешь этот метод внутри синхронизированного блока

2024-08-25 13:54 UTC, 20cognosce commented on src/main/java/faang/school/godbless/BJS2_24560/GooglePhotosAutoUploader.java
> +        }
Ну как бы непонятно, если вызовется uploadPhotos на пустом списке - ну ничего не произойдет
Зачем там накрутил if(!running) { return }

2024-08-25 13:54 UTC, merged